### ISSUE TITLE
[1.16.1] Registry Sync Module 

### ISSUE THREAD

**Issue by FlashyReese** [FabricMC/fabric#1005]
As stated in https://github.com/FabricMC/fabric/pull/507#issuecomment-671258265

![image](https://user-images.githubusercontent.com/30311066/89772063-ff4f7a80-dac6-11ea-8e21-b040b04145eb.png)

This occurs on a 1.16.1 mp server, even if freshly generated. Use the workaround method does not work(deleting ```fabricRegistry.dat```)
__NOTE__: This does not occur in SP worlds.
- Fabric API 0.17.+build.386
- Fabric Loader 0.9.1+build.205

![image](https://user-images.githubusercontent.com/30311066/89772223-42a9e900-dac7-11ea-859f-960567bdd262.png)

Edit: Also all client sided mods such as LambDynamicLights and Sodium are not present in the server.

**Comment by plusls** [comment]
You use Vanilla to connect a fabric server which have a mod that add new Block?

**Comment by plusls** [comment]
I write a gravestone mod, when player dead, mod will place a gravestone block to store player’s item.

https://github.com/uestclug/gravestone

But I want this mod support Vanilla, so I Mixin PalettedContainer to cheat client that the gravestone block is a player skull.

It work fine in 1.16 with fabric-api-0.14.0+build.371-1.16, but when I update to 1.16.2 with fabric 0.17.2+build.396-1.16, Blockstate is out of order.

I found that  fabric-registry-sync will remap registry, and send sync packet to fabric client. But if client don’t install mod which register block, the block registry will not update. In addition, the Vanilla client will not update block registry, too. I don't know how to solve this problem elegantly.

**Comment by Technici4n** [comment]
I haven't seen this bug in years.
