### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by unlsycn** [FabricMC/fabric#1006]
There is only a fabric-api-0.17.0+build.386-1.16.1.jar in my mods folder.
I have tried to  delete all config and download Minecraft again but it still crash.
here is the crash report:https://paste.ubuntu.com/p/c2dGQJN4f2/

**Comment by artun42** [comment]
same on arch linux

**Comment by i509VCB** [comment]
Can you describe how you got this error? It seems like `World` is missing which means something has gone horribly wrong.

Edit 1:
@2str8, if you can give me steps to reproduce, I can test it since I am using arch on my laptop

**Comment by artun42** [comment]
I got help in the discord channel, crash causes by incompatible version of Sodium with Fabric/Minecraft. So i ran it on 1.16.1 and everything works perfectly now. Thanks

**Comment by unlsycn** [comment]
> Can you describe how you got this error? It seems like `World` is missing which means something has gone horribly wrong.

I just ran my Minecraft with Fabric mod loader and Fabric API, then it crash and the crash report pop up. There is no other mods in the mod folder. I tried to decompile Minecraft by Yarn and it seems to cause by "net.minecraft.world.World". 
But interestingly everything works fine on 1.16.2.

**Comment by i509VCB** [comment]
Can you give me the entire log? That will contain the mod list and OS details

**Comment by unlsycn** [comment]
> Can you give me the entire log? That will contain the mod list and OS details

Sure.
log:https://paste.ubuntu.com/p/yy4x78PgYr/
crash-report:https://paste.ubuntu.com/p/rn9gpP8MSj/

**Comment by i509VCB** [comment]
Every single mixin in fabric api failed to apply...
![68747470733a2f2f63646e2e646973636f72646170702e636f6d2f656d6f6a69732f3730373031363138363238313539303835352e706e673f763d31](https://user-images.githubusercontent.com/30619168/90325595-4b754180-df43-11ea-9f94-aa98cb96b119.png)

Something is definitely wrong.

Which launcher are you using? If it's MultiMC, can we have instance info?

**Comment by unlsycn** [comment]
Sorry, I am using PCL to launch Minecraft. I have switched to other launcher like HMCL and it crash as well.
I can launch other versions by PCL and HMCL perfectly so I think it's not the launcher's problem.

**Comment by liach** [comment]
Try with mojang launcher or multimc.

**Comment by Leo40Git** [comment]
Out of curiosity, what are PCL and HMCL? I've never heard of those launchers.

**Comment by unlsycn** [comment]
> Out of curiosity, what are PCL and HMCL? I've never heard of those launchers.

I think it doesn't matter.

**Comment by unlsycn** [comment]
Fabric works well on 1.16.2 now. I have gave up to get clear about this problem so I will close this issue. Thank you all for help

**Comment by Leo40Git** [comment]
For future reference: both PCL and HMCL seem to have cracked functionality.
We do not support clients, cheats, or modifications that allow you to access the game without paying for it.

**Comment by modmuss50** [comment]
Yes, this issue here clearly looks like an issue with the launcher as well.
