### ISSUE TITLE
fabric-api-0.17.2+build.396-1.16 prevents connecting to multiplayer servers

### ISSUE THREAD

**Issue by Ricoware** [FabricMC/fabric#1008]
I have fabric-installer-0.6.1.45 installed.
- When launching with no mods, I can see the connection status of multiplayer servers and can connect to them as expected.
- When I enable fabric-api-0.17.2+build.396-1.16, none of my saved multiplayer servers can be connected to.

![image](https://user-images.githubusercontent.com/526091/90047736-a252f080-dc8f-11ea-8f12-ef7b16dd411d.png)

**Comment by i509VCB** [comment]
Well probably need more information in order to do anything, like version of fabric api and mod list.

**Comment by i509VCB** [comment]
Closing since this is not an issue with Fabric API and lack of feedback. If you need further assistance, please join the Fabric discord https://discord.gg/v6v4pMv

Seems like a network issue from what I see, check your Antivirus and Firewall settings.
