### ISSUE TITLE
Gradle takes forever when trying to download latest fabric api version for 1.16.2

### ISSUE THREAD

**Issue by TelepathicGrunt** [FabricMC/fabric#1009]
It's hard to explain the issue but whenever I am trying to implement the latest fabric api version to stop one of the other dependencies from downloading an outdated version of fabric api in 1.16.2 
(all dependencies only modCompile fabric api but none bundles it. So gradle seems to be trying to automatically download a fabric api version that's too old or at least, that's what people are saying is happening) 

The line I used:
`modImplementation "net.fabricmc.fabric-api:fabric-api:0.17.2+build.396-1.16"`

When I exclude it, gradle is able to import and resolve the dependencies and all just fine. But when I do include it, it gets stuck looping through the fabric api stuff forever when I refresh gradle (I even ran it upward to an hour and still no progress)
![image](https://user-images.githubusercontent.com/40846040/90088443-f5a75c00-dcec-11ea-833f-2e2446f6ba12.png)

My build.gradle: https://hatebin.com/gkgzpncrqf
My gradle.properties: https://hatebin.com/agdfohqzwd

I am following the example fabric mod here to get the right fabric api version and build.gradle line: https://github.com/FabricMC/fabric-example-mod/blob/master/gradle.properties

Might also be a Loom issue too. Kind of stuck right now and can't develop in 1.16.2 unless I can get the newer fabric api version in my project so it stops crash at runtime like it does with the old version it automatically downloads.

**Comment by TelepathicGrunt** [comment]
Yes, I have tried clearing gradle caches, gradle clean, invalidate cache and restart intellij, etc. But the hang only occurs when fabric api is added to my build.gradle. Does not happen for any of the other dependencies

**Comment by i509VCB** [comment]
Is this still an issue with the latest versions?

**Comment by TelepathicGrunt** [comment]
Nope. It only happened that one day. Very weird.
