### ISSUE TITLE
Mod resource packs vanish on resource reload

### ISSUE THREAD

**Issue by JamiesWhiteShirt** [FabricMC/fabric#101]
On initial load the resource pack works fine, but on reload all assets disappear.

We manage to inject mod resource packs just fine [on initial load](https://github.com/FabricMC/fabric/blob/master/src/main/java/net/fabricmc/fabric/mixin/resources/MixinMinecraftGame.java#L57-L60). However, [on resource reload](https://github.com/FabricMC/fabric/blob/master/src/main/java/net/fabricmc/fabric/mixin/resources/MixinMinecraftGame.java#L62-L65) the resource packs are injected into the list AFTER the call to `ReloadableResourceManager.method_18232`.

**Comment by asiekierka** [comment]
Fixed in #103 (Fabric 0.2.3).
