### ISSUE TITLE
i have fabric loader 0.91 build 205 for 1.16.1 and i have no idea which api works

### ISSUE THREAD

**Issue by SnotaroKujo** [FabricMC/fabric#1013]
i tried most of the 1.16 api but none seem to work

**Comment by i509VCB** [comment]
It may seem odd, but you need to use the `1.16.1` appended jar. We do plan to bind the suffix to the actual major version for 1.17 and beyond

Also which jar did you use? specifically the file name

**Comment by SnotaroKujo** [comment]
installer or api

**Comment by i509VCB** [comment]
Fabric API

**Comment by SnotaroKujo** [comment]
i usesd fabric api build 394 1.16

**Comment by uiytt** [comment]
So use : fabric api 0.17.0+build.386-1.16.1 instead

**Comment by i509VCB** [comment]
Closing since there has not been any activity on this issue for a while. Please open a new issue if you need further assistance.
