### ISSUE TITLE
Crash with log4j config option

### ISSUE THREAD

**Issue by fenhl** [FabricMC/fabric#1015]
For our custom tooling, we modify the log format using `-Dlog4j.configurationFile=log4j2.xml`. However, Fabric crashes on startup if this option is given. (The vanilla server does not crash when using the same configuration file.) We had to [disable this option for modded worlds](https://github.com/wurstmineberg/systemd-minecraft/blob/riir/src/lib.rs#L186-L188) for the time being, but this also [breaks some features](https://github.com/wurstmineberg/wurstmineberg.de/issues/31) that work by reading the log.

**Comment by i509VCB** [comment]
This issue would probably be better asked on the Fabric Loader repository. Fabric api should be having no effect on this at all.

**Comment by uiytt** [comment]
Can someone close this on this end please?
