### ISSUE TITLE
including resource loader 0.2.9 seems to break it in production

### ISSUE THREAD

**Issue by nnym** [FabricMC/fabric#1017]
When I include version 0.2.9+e5d3217f4e of the resource loader module in my mod and use it in production (Minecraft version 1.16.2), its mixins' targets seem to not be remapped: https://hastebin.com/bisobigawu.
Downgrading to the 0.2.8+35e08e3351 version fixes the issue. This was tested with only my mod, which includes this module.

**Comment by i509VCB** [comment]
Closing since log is no longer accessible, if this is still an issue please open a new issue.
