### ISSUE TITLE
Crash on startup with online mode

### ISSUE THREAD

**Issue by unlsycn** [FabricMC/fabric#1018]
#1006  I followed the suggestion to use MultiMC but it crash again.
log:https://paste.ee/p/KBRgv

**Comment by Leo40Git** [comment]
OptiFine causes a lot of incompatibilities with other mods due to its nature.
Additionally, OptiFabric, the mod that allows OptiFine to work in a Fabric environment, is deprecated.
I'd recommend looking at this list of OptiFine alternatives: https://gist.github.com/LambdAurora/1f6a4a99af374ce500f250c6b42e8754

**Comment by unlsycn** [comment]
> OptiFine causes a lot of incompatibilities with other mods due to its nature.
> Additionally, OptiFabric, the mod that allows OptiFine to work in a Fabric environment, is deprecated.
> I'd recommend looking at this list of OptiFine alternatives: https://gist.github.com/LambdAurora/1f6a4a99af374ce500f250c6b42e8754

Thanks.
By the way, does Fabric limit it to run by unofficial launcher? I have Minecraft account but I'm used to using it because it can connect to mirror server to download files to get faster speed.

**Comment by pluiedev** [comment]
Yeah im familliar with that. Shame that the official launcher doesnt allow you to specify a mirror site when downloading and 100MB takes an eternity.

**Comment by LeoCTH** [comment]
Yeah im familliar with that. Shame that the official launcher doesnt allow you to specify a mirror site when downloading and 100MB takes an eternity.

**Comment by zml2008** [comment]
Fabric could work with any launcher, but the only launcher the fabric installer works with is the official one. Other launchers would have to have support added by their developers.

**Comment by unlsycn** [comment]
thanks
