### ISSUE TITLE
Audio from ModNioResourcePack randomly freezes the game when played

### ISSUE THREAD

**Issue by JamiesWhiteShirt** [FabricMC/fabric#102]
Playing audio from a ModNioResourcePack will randomly print the following to the console, then the client thread will freeze.

```
Error in class 'CodecJOrbis'
Error reading the header
```

CodecJOrbis will catch a ClosedByInterruptException which apparently is related to the introduction of NIO InputStreams by ModNioResourcePack.

**Comment by asiekierka** [comment]
Fixed in #103 (Fabric 0.2.3).
