### ISSUE TITLE
Build 397 (1.16.2) Requires... 20w28a?

### ISSUE THREAD

**Issue by rdenno** [FabricMC/fabric#1021]
Basically the title. When I try starting my server with build 397 it says that mod 'fabric' requires 20.28.a. Please send help

**Comment by Earthcomputer** [comment]
Please ensure you are actually in Minecraft 1.16.2 and not Minecraft 1.16.1

**Comment by rdenno** [comment]
> Please ensure you are actually in Minecraft 1.16.2 and not Minecraft 1.16.1

But shouldn't the API be for 1.16.2 proper rather than a snapshot? So if that were the case wouldn't it say requires 1.16.2 rather than 1.16.2.20.28.a or whatever?

**Comment by Earthcomputer** [comment]
The API depends on `~1.16.2-alpha.20.28.a`, the `~` means it works in 1.16.2. Please update to it.

**Comment by i509VCB** [comment]
Closing since message above resolves the issue. If you need further assistance, please join the Fabric discord https://discord.gg/v6v4pMv
