### ISSUE TITLE
QuadEmitter#sprite default implementation is broken

### ISSUE THREAD

**Issue by Technici4n** [FabricMC/fabric#1024]
Here is my code:

https://github.com/Technici4n/fabric-rendering-issue/blob/master/src/main/java/net/fabricmc/example/FourSidedFurnaceModel.java

Result:
![image](https://user-images.githubusercontent.com/13494793/90483943-d3bb3880-e135-11ea-9b27-e7498d39291d.png)

Expected result:
![image](https://user-images.githubusercontent.com/13494793/90483986-e2095480-e135-11ea-96a8-af851b092f49.png)

**Comment by dblsaiko** [comment]
Your expected result expect the X axis to be flipped for each negative-axis facing. This should not be the case imo since it would mean that making a box with quads is more difficult since you can no longer use the same coordinates for the two opposite sides.

**Comment by grondag** [comment]
The square method was meant (iirc) to use left-right coordinates from the perspective of the viewer, vs world axis coordinate.  Doing it the other way is fairly straightforward using vertex coordinates directly.

**Comment by dblsaiko** [comment]
Ah, okay. If it was intended to work the other way then this is indeed a bug :p
