### ISSUE TITLE
Registry Remapping Failed Joining 1.16.1 Server

### ISSUE THREAD

**Issue by braxten509** [FabricMC/fabric#1037]
So I am hosting a Minecraft Fabric server, and whenever I try to join it, I get this error: 
![Capture](https://user-images.githubusercontent.com/46695819/90861238-4f88d100-e340-11ea-8b8f-5b8f0c749946.PNG)

I have looked at other errors similar to this, but none of them had the solution. This is 1.16.1, any help would be greatly appreciated!

**Comment by ghost** [comment]
It usually means that the server has the rings of ascension mod, but the client doesn't.

**Comment by braxten509** [comment]
That's really weird, as both do. Here are screenshots:
![Minecraft Mods](https://user-images.githubusercontent.com/46695819/90941763-e3ea4680-e3c7-11ea-8427-ea045d2c8bea.PNG)

![Fabric Server](https://user-images.githubusercontent.com/46695819/90941755-e0ef5600-e3c7-11ea-9a63-8d9408543d4a.PNG)

**Comment by ghost** [comment]
Make sure the config on the client and server are identical.  I've also seen this error when the config on the client disables an item while the server doesn't.
If that's the case, please do report it with the mod author.  This really isn't a Fabric issue.

**Comment by braxten509** [comment]
That was it! I'll report it to them, thanks!
