### ISSUE TITLE
 frrabic api can not be launched 

### ISSUE THREAD

**Issue by gameplays12303** [FabricMC/fabric#1038]
this is a problem with the AI the game says it can't be launch i use the twitch installer which is set the the newest release
i don't have the log anymore because i was just trying to get the game to work sorry all i can say is your late release isn't bootable  
i have look down all 3 pages and couldn't find anything about this 
(reading the titles ) 
minecraft version 1.16 
build version late released 
i whished i keep the log but i can say this every time i tryed it just brought me to  a failed screen

**Comment by uiytt** [comment]
What is written on the failed screen ? 
Also, the fabric loader version is needed, late release is not good because it always change

**Comment by liach** [comment]
don't think twitch works with fabric. use multimc or just vanilla launcher.

**Comment by ghost** [comment]
Yeah, twitch launcher won't work unless you're using [Jumploader](https://www.curseforge.com/minecraft/mc-mods/jumploader). That being said, the fabric api GitHub repository is not the right place to be asking support questions relating to installation. In the future, if you'd like help with installing fabric api or other mods, please join the [fabric discord](https://discord.gg/v6v4pMv) and post your questions in the #player-support channel, and we'll be glad to help.

**Comment by i509VCB** [comment]
Closing since this is not an issue with Fabric API. Please ask on the Fabric discord if you have any issues with individual mods https://discord.gg/v6v4pMv.
