### ISSUE TITLE
cant open minecraft

### ISSUE THREAD

**Issue by simonas-z** [FabricMC/fabric#1039]
everytime i try to play minecraft with fabric (currently im trying 1.16.1) it says 
![image](https://user-images.githubusercontent.com/54555539/90952051-054f3f00-e469-11ea-98e6-1af200473ba8.png)

**Comment by simonas-z** [comment]
also here are my mods 
![image](https://user-images.githubusercontent.com/54555539/90952127-c53c8c00-e469-11ea-858b-dedeb0710013.png)

**Comment by Earthcomputer** [comment]
`worldedit-forge` :thinking:

**Comment by simonas-z** [comment]
oh

**Comment by uiytt** [comment]
Can someone close this ?
