### ISSUE TITLE
EntityType<Fox>.Spawn Causes crash

### ISSUE THREAD

**Issue by biom4st3r** [FabricMC/fabric#104]
Crash Dump: https://pastebin.com/JUVuZ2ZM

When typing to spawn a Fox Using
Entity e = et.spawn(iuc.getWorld(), new CompoundTag(), null, null, iuc.getBlockPos(), SpawnType.EVENT,false,false);

Causes a Crash

**Comment by asiekierka** [comment]
Well ,this is an NPE. Maybe one of these nulls or empty tags is causing an issue?

**Comment by biom4st3r** [comment]
That's possible, but those 2 are for TextComponent for Custom Name and PlayerEntity, and it also works on all other mobs(to my knowledge)

**Comment by biom4st3r** [comment]
I tried passing non-null arguments into though spots, but still NPE

**Comment by Prospector** [comment]
This doesn't seem like a fabric api issue to me.
