### ISSUE TITLE
server crashes on startup

### ISSUE THREAD

**Issue by PheoYT** [FabricMC/fabric#1041]
Im using aternos to start a server, and these are the mods.
![image](https://user-images.githubusercontent.com/70139595/91031836-be0aaf00-e61e-11ea-9143-fa8261ebbc00.png)
and here is the log-

https://mclo.gs/Eqdbc6b

any help?

**Comment by PheoYT** [comment]
update: i dont know why it says the server is vanilla, but yes it is fabric

**Comment by CheaterCodes** [comment]
Seems like at least one of your mods is outdated (Depends on an outdated version of Artifice).
All you can do really is remove mods one by one until it is fixed and then check if there's a newer version of that mod.

**Comment by PheoYT** [comment]
> 
> 
> Seems like at least one of your mods is outdated (Depends on an outdated version of Artifice).
> All you can do really is remove mods one by one until it is fixed and then check if there's a newer version of that mod.

damn, okay ill go with that i guess

**Comment by uiytt** [comment]
Can someone please close this, as it is not a fabric-api problem ?

**Comment by i509VCB** [comment]
Closing, if this is still an issue please make a new issue.
