### ISSUE TITLE
Place block event

### ISSUE THREAD

**Issue by Genau6502** [FabricMC/fabric#1042]
I would love to see an event similar to PlayerBreakBlockEvents(AFTER), called on the logical server when a block is placed. UseBlockCallback is good, however it does not give the position of the block that is broken.

**Comment by Earthcomputer** [comment]
You can get the position of the block via the `hitResult`

**Comment by Genau6502** [comment]
> You can get the position of the block via the `hitResult`

Thanks

**Comment by Genau6502** [comment]
> You can get the position of the block via the `hitResult
What method would need to be called to get the position?
