### ISSUE TITLE
Server runs fine, but client crashes

### ISSUE THREAD

**Issue by PheoYT** [FabricMC/fabric#1045]
I Hosted a server on aternos, and the server is working completely fine, but my client crashes,
i load in the server, and when it gets to "Loading Terrain" it crashes.
Here is the log-

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 8/25/20 2:53 PM
Description: Rendering screen

java.lang.NoClassDefFoundError: net/minecraft/class_5481
	at io.github.apace100.origins.screen.ChooseOriginScreen.renderOriginContent(ChooseOriginScreen.java:182)
	at io.github.apace100.origins.screen.ChooseOriginScreen.renderOriginWindow(ChooseOriginScreen.java:117)
	at io.github.apace100.origins.screen.ChooseOriginScreen.method_25394(ChooseOriginScreen.java:110)
	at net.minecraft.class_757.method_3192(class_757.java:603)
	at net.minecraft.class_310.method_1523(class_310.java:1021)
	at net.minecraft.class_310.method_1514(class_310.java:654)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_5481
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at io.github.apace100.origins.screen.ChooseOriginScreen.renderOriginContent(ChooseOriginScreen.java:182)
	at io.github.apace100.origins.screen.ChooseOriginScreen.renderOriginWindow(ChooseOriginScreen.java:117)
	at io.github.apace100.origins.screen.ChooseOriginScreen.method_25394(ChooseOriginScreen.java:110)

-- Screen render details --
Details:
	Screen name: io.github.apace100.origins.screen.ChooseOriginScreen
	Mouse location: Scaled: (213, 120). Absolute: (427.000000, 240.000000)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2.000000

-- Affected level --
Details:
	All players: 1 total; [class_746['PheoYT'/222, l='ClientLevel', x=-141.50, y=66.00, z=194.50]]
	Chunk stats: SodiumChunkCache: 169
	Level dimension: minecraft:overworld
	Level spawn location: World: (-144,67,192), Chunk: (at 0,4,0 in -9,12; contains blocks -144,0,192 to -129,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 4684 game time, 4684 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2181)
	at net.minecraft.class_310.method_1514(class_310.java:672)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 264002504 bytes (251 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Patchouli open book context: n/a
	Fabric Mods: 
		adorn: Adorn 1.10.1+1.16.1
		adventurez: AdventureZ 1.0.8
		appleskin: AppleSkin 1.0.11
		artifice: Artifice 0.8.1+1.16.1
		autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
		betternether: Better Nether 3.5.4
		blockus: Blockus 1.6.2
		blue_endless_jankson: jankson +
		byg: BYG 1.0.13
		caelus: Caelus API 0.0.7-1.16.1
		campanion: Campanion 1.1.13+build.35
		cardinal-components-base: Cardinal Components API (base) 2.5.0-nightly.1.16.2-rc2
		cardinal-components-entity: Cardinal Components API (entities) 2.5.0-nightly.1.16.2-rc2
		cavebiomes: Cave Biomes 0.2.4
		chainmail: Chainmail 0.1.1
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.0.8
		cloth-config2: Cloth Config v4 4.7.0-unstable
		colytra: Colytra 1.0.1-1.16.1
		cotton-resources: Cotton Resources 1.7.1
		decorative: Decorative 2.0.0 - Summer 2020 Update
		diggusmaximus: Diggus Maximus 1.3.1-1.16
		extrapieces: Extra Pieces 2.9.0
		fabric: Fabric API 0.17.0+build.386-1.16.1
		fabric-api-base: Fabric API Base 0.1.3+12a8474cfa
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea86602
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8902
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339802
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083602
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f02
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86602
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d02
		fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b305302
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f02
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b02
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.0+fe81e12502
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b02
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963602
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+f404f3be02
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c502
		fabric-language-kotlin: Fabric Language Kotlin 1.3.72+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+e83e061c02
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+386eb69e02
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9902
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d602
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b02
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f02
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.7+2242e77202
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+a2d21ddd02
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a7002
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c02
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb802
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.4+34d6c87102
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.1.0+be551d3c02
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d02
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.8+b7084faa02
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049002
		fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d702
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.6+f41e209802
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+97324d1102
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.7+a4c57d8e02
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb802
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.1+91fca5cd02
		fabricloader: Fabric Loader 0.9.2+build.206
		fiber: fiber 0.23.0-1
		jankson: Jankson 3.0.0+j1.2.0
		kyrptconfig: Kytpt Config 1.1.2-1.16
		lacrimis: Lacrimis 1.2.2
		libcd: LibCapableData 2.4.1+1.16-pre2
		libgui: LibGui 2.0.1+1.16.1
		libstructure: Libstructure 1.3
		lithium: Lithium 0.5.1
		minecraft: Minecraft 1.16.1
		mobz: MobZ 2.4.4
		more_gems: More Gems 1.0.48
		mostructures: Mo' Structures 1.0.0-pre2+mc.1.16
		org_jetbrains_annotations: annotations 17.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.72
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.72
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.3.72
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.72
		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.7
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.7
		origins: Origins 1.16.2-0.3.6
		parchment: Parchment 1.0.2+1.15.2
		patchouli: Patchouli 1.16-37-FABRIC
		phosphor: Phosphor 0.6.0+build.7
		qcommon-croco: Croco 2.1.2
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		roughlyenoughitems: Roughly Enough Items 5.2.7
		roughlyenoughitems-api: REI (API) 5.2.7
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.2.7
		roughlyenoughitems-runtime: REI (Runtime) 5.2.7
		silky_spawners: Silky Spawners 2.0.0+build.1-1.16
		sodium: Sodium 0.1.0
		torcherino: Torcherino 2.11.67
		voxelmap: VoxelMap 1.10.7
	Launched Version: fabric-loader-0.9.2+build.206-1.16.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 451.67, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 1600 Six-Core Processor 

Here are the mods - 
![image](https://user-images.githubusercontent.com/70139595/91157519-0d1a1800-e6e3-11ea-94bd-55be4a709b71.png)
Any help?

**Comment by BoogieMonster1O1** [comment]
You seem to be using the 1.16.2 version of Origins. 
Use this: https://www.curseforge.com/minecraft/mc-mods/origins/files/3027557

**Comment by PheoYT** [comment]
> 
> 
> You seem to be using the 1.16.2 version of Origins.
> Use this: https://www.curseforge.com/minecraft/mc-mods/origins/files/3027557

ohh thank you! lemme try it out

**Comment by ghost** [comment]
You'll also need Campanion 1.2.0 for 1.16.2 support. That being said, the fabric api GitHub repository is not the right place to be asking questions about other mods causing crashes. In the future, if you'd like help with troubleshooting crashes, please join the [fabric discord](https://discord.gg/v6v4pMv) and post your questions in the #player-support channel, and we'll be glad to help.

**Comment by i509VCB** [comment]
Closing since this is not an issue with Fabric API. Please ask on the Fabric discord if you have any conflicts with individual mods https://discord.gg/v6v4pMv
