### ISSUE TITLE
cannot find symbol import net.minecraft.world.RayTraceContext;

### ISSUE THREAD

**Issue by Succubussix** [FabricMC/fabric#1054]
why I can't import this? I got all my GUI stuff and function stuff and i decided to mess with custom can see feature. it works fine on debugging using eclipse but building nope.. I can import this on eclipse run it on debug.. but building failed 

```cannot find symbol import net.minecraft.world.RayTraceContext;```

```
# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

# Fabric Properties
	# check these on https://fabricmc.net/use
	minecraft_version=1.16.2
	yarn_mappings=1.16.2+build.42
	loader_version=0.9.2+build.206

# Mod Properties
	mod_version = 1.0.0
	maven_group = net.blah.blah
	archives_base_name = blah-blah

# Dependencies
	# currently not on the main fabric site, check on the maven: https://maven.fabricmc.net/net/fabricmc/fabric-api/fabric-api
	fabric_version=0.19.0+build.398-1.16


```

```id 'fabric-loom' version '0.5-SNAPSHOT'```

**Comment by haykam821** [comment]
This class is named `RayCastContext` now.

**Comment by Succubussix** [comment]
where is that located? please?

btw I found out what's causing this .. the fabric example works but when I update using this https://modmuss50.me/fabric.html
that's where RayTraceContext is gone.

**Comment by haykam821** [comment]
Before you update, you need to run `./gradlew migrateMappings --mappings "1.16.2+build.43"`. Then, move the contents of `remappedSrc` to your `src/main/java` (or similar) folder. This will automatically change the names, and after which, you can update.

**Comment by Succubussix** [comment]
I tried ```import net.minecraft.world.RayCastContext;```

base on this update..  https://github.com/FabricMC/yarn/blob/6db313ddaa54e486ae1cfe363dacdca3f8c7340b/mappings/net/minecraft/world/RaycastContext.mapping

but I can't import it or build it.

``` 
error: cannot find symbol
import net.minecraft.world.RayCastContext;
```

i did ./gradlew migrateMappings --mappings "1.16.2+build.43" and still ```import net.minecraft.world.RayTraceContext;```

I also tried to gen source again 

![image](https://user-images.githubusercontent.com/12135498/91675415-da52a280-eb6e-11ea-908b-860a5c5eb4ec.png)

then exec migrateMappings --mappings "1.16.2+build.43" 
the import dint change still RayTraceContext

trying to import it and use it gives me red lint on eclipse

try to build it 

```
> Task :compileJava FAILED
2020-08-31 09:49:23,948 Execution worker for ':' WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStreamNote: SpongePowered MIXIN Annotation Processor Version=0.8.1
Note: ObfuscationServiceFabric supports type: "official:intermediary"
Note: ObfuscationServiceFabric supports type: "official:named"
Note: ObfuscationServiceFabric supports type: "intermediary:official"
Note: ObfuscationServiceFabric supports type: "intermediary:named"
Note: ObfuscationServiceFabric supports type: "named:official"
Note: ObfuscationServiceFabric supports type: "named:intermediary"
Note: ObfuscationServiceMCP supports type: "searge"
Note: ObfuscationServiceMCP supports type: "notch"
Note: Loading named:intermediary mappings from C:\...................\.gradle\caches\fabric-loom\mappings\yarn-1.16.2+build.42-v2.tiny
Note: Writing refmap to ...................refmap.json
Note: Writing refmap to ...................refmap.json
Note: Writing named:intermediary output TinyMappings to C:\...................\build\loom-cache\mixin-map-1.16.2-1.16.2+build.42-v2.tiny
....................java:29: error: cannot find symbolimport net.minecraft.world.RayCastContext;
```

**Comment by haykam821** [comment]
Oops, that should be `import net.minecraft.world.RaycastContext;` instead. Make sure you are still using the old version of Yarn when you use the `migrateMappings` task.

**Comment by Succubussix** [comment]
ow it kinda works thanks.. now my problem is my eclipse giving lint.. do I have to regen my eclipse?

**Comment by Succubussix** [comment]
ow that did it.. i regen it.. thanks. 💯  💯  💯  💯  💯  💯  💯
