### ISSUE TITLE
[Feature Request] Custom elytra support

### ISSUE THREAD

**Issue by oliviathevampire** [FabricMC/fabric#1055]
I would love to have the possibility for us to easily add new custom elytras, rn a lot of stuff are hardcoded for them so it's a lot of work to get a custom one working, maybe a registry or something could work?

**Comment by OverlordsIII** [comment]
There's already a lib for this, I don't know when they would add it to Fabric API though.
https://github.com/adriantodt/FallFlyingLib

**Comment by skylorbeck** [comment]
You can also use https://github.com/TheIllusiveC4/Caelus/tree/1.16.x-fabric

**Comment by Technici4n** [comment]
Linking the relevant PR: #1374.

**Comment by Technici4n** [comment]
Added in #1815.
