### ISSUE TITLE
 [1.16.2] Fabric API 0.20.0 build 399 Crashes Servers Instantly

### ISSUE THREAD

**Issue by CorgiTaco** [FabricMC/fabric#1058]
Basically, this version crashes servers with the following:
Latest.Log: https://hatebin.com/esasjqvtht
Crashlog: No Crash log is created.
No mods are added and this is only with Fabric API installed. Works perfectly fine w/ [1.16.2] Fabric API 0.19.0 build 398.

**Comment by modmuss50** [comment]
Looking into it now.
