### ISSUE TITLE
Fabric Biomes Mixin Startup Crash

### ISSUE THREAD

**Issue by P3NG00** [FabricMC/fabric#1064]
Hello!

I have been experiencing a startup crash. This is the [crash log (Paste.ee)](https://paste.ee/p/mul3X).

minecraft_version=1.16.2
yarn_mappings=1.16.2+build.46
loader_version=0.9.3+build.207
fabric_version=0.20.1+build.401-1.16

♥

**Comment by i509VCB** [comment]
The biome api has not been updated to 1.16.2 yet and it does not exist in newer versions. Some other mod is pulling it in. So I'd exclude fabric api dependency from any mods you depend on.

**Comment by P3NG00** [comment]
@i509VCB @i509VCB Im developing, not playing
