### ISSUE TITLE
Relocate custom values specified by fabric api

### ISSUE THREAD

**Issue by i509VCB** [FabricMC/fabric#1068]
Fabric API uses custom values in some of the modules, currently Indigo to specify whether the default rendering implementation should be enabled. 

However I see cases where additional custom values may be defined in the future, which could be a mess in the root of the custom values object.

The concept here is the consolidate all fabric api added custom values into a single `fabricApi` object within the custom values.

Each module which provides custom values should then make a sub object for their custom fields. 

Below of the possible setup of the new format:

```json
"custom": {
    "fabricApi": {
        "fabric-rendering-api-v1": {
            "contains_renderer": true
        }
    }
} 
```

All old custom values defined this way will be deprecated and a logger message emitted for mods which still use the old format.

**Comment by Pyrofab** [comment]
What exactly is wrong with having a lot of values in the root object ? As long as they are identified with the mod id, there should be no conflict.

**Comment by i509VCB** [comment]
Closing since the response seems to be that this isn't needed.
