### ISSUE TITLE
my fabric api mod is build 370 and the highest on my java installer is 207 LINUX

### ISSUE THREAD

**Issue by dolphin-cat** [FabricMC/fabric#1070]

**Comment by dolphin-cat** [comment]
rename the files from txt to jar because github dose not support jar

[fabric-api-0.13.1+build.370-1.16.txt](https://github.com/FabricMC/fabric/files/5201930/fabric-api-0.13.1%2Bbuild.370-1.16.txt)
[fabric-installer-0.6.1.51.txt](https://github.com/FabricMC/fabric/files/5201922/fabric-installer-0.6.1.51.txt)

**Comment by Daomephsta** [comment]
It's unclear what your issue is

**Comment by YTG1234** [comment]
The installer doesn't install the API. It installs the loader.

**Comment by modmuss50** [comment]
Closing as no extra info provided.
