### ISSUE TITLE
The fabric installer does not start. _JAVA_OPTIONS

### ISSUE THREAD

**Issue by SnowBees** [FabricMC/fabric#1077]
The fabric installer does not start.

If the following is described in _JAVA_OPTIONS, an error will occur and it will not start. .jar and .exe

[-Dsun.stdout.encoding = UTF8 -Dsun.err.encoding = UTF8 -Dfile.encoding = UTF8 -Dsun.jnu.encoding = UTF8]

**Comment by i509VCB** [comment]
Further information is needed such as the log when trying to start the installer. Also this issue should be on https://github.com/FabricMC/fabric-installer

**Comment by i509VCB** [comment]
Closing, please open the issue on installer repository.
