### ISSUE TITLE
Minecraft hangs at 90% after reloading resource packs

### ISSUE THREAD

**Issue by secretdataz** [FabricMC/fabric#108]
Same issue as #97, but happens on resource reload instead of launching.
OS is Windows 10.
Using the following Fabric dependencies.
```
dependencies {
	minecraft "com.mojang:minecraft:19w08b"
	mappings "net.fabricmc:yarn:19w08b.7"
	modCompile "net.fabricmc:fabric-loader:0.3.7.109"
	modCompile "net.fabricmc:fabric:0.2.3.106"
}
```
I also have some resources in my mod which can be seen [here](https://github.com/secretdataz/ThaiFixes-Fabric/tree/master/src/main/resources).
[dev environment log](https://pastebin.com/4fq38NXx).

**Comment by asiekierka** [comment]
If you have a custom reload listener and it throws an exception without being caught on your side, the loading will hang with no error.

Annoying, I know. We should probably patch this.

**Comment by Prospector** [comment]
Is this still an issue?

**Comment by secretdataz** [comment]
It doesn't seem to be an issue with Fabric build 127 loader build 154 anymore.
