### ISSUE TITLE
Could not find required mod: wurst requires {fabric @ [>=0.12.1]}

### ISSUE THREAD

**Issue by dreemi** [FabricMC/fabric#1080]
I don't know how to fix this, I've searched everywhere online, or maybe I'm just being stupid.

**Comment by ramidzkh** [comment]
Why did you create two issues? You need to download fabric-api from https://www.curseforge.com/minecraft/mc-mods/fabric-api

**Comment by Owlidk** [comment]
Idk if this works, i tried it a bunch of times it gives me an error and now the program refuses to start so ye

**Comment by Winkia** [comment]
Hi, i have same problem. After updating all my mods, I started getting this error and at the same time I have the latest 1.17.1 updated version of everything, Fabric-api, fabric-loader, modmenu, optifabric and normal Optifine. So download newest version probably won't work for me.

**Comment by modmuss50** [comment]
We dont support hacks or cheats.
