### ISSUE TITLE
how to add your own cakes?

### ISSUE THREAD

**Issue by Miros77** [FabricMC/fabric#1083]
![sad](https://user-images.githubusercontent.com/59547044/93026283-9ef3b180-f60d-11ea-84f0-b0340fa7a439.png)

**Comment by YanisBft** [comment]
This repo is not for modding advices. You better off with the [fabric discord](https://discord.gg/v6v4pMv)

**Comment by Miros77** [comment]
> This repo is not for modding advices. You better off with the [fabric discord](https://discord.gg/v6v4pMv)

OK
