### ISSUE TITLE
I can't give the cakes my properties

### ISSUE THREAD

**Issue by Miros77** [FabricMC/fabric#1084]
so that you can: increase or decrease hunger and satiety

**Comment by Miros77** [comment]
error: The method tryEat(WorldAccess, BlockPos, BlockState, PlayerEntity) of type ModCakeBlock must override or implement a supertype method

**Comment by ghost** [comment]
I would recommend using a custom mixin for this if you want to change the vanilla cake. This is not something that fabric api is likely to support any time soon. It should be as easy as targeting the tryEat method in the `CakeBlock.class` and modfying the constants for food and saturation using a `@ModifyConstant` mixin.

Your second message is because your child class is not implementing all of the methods that it's required to implement by the parent. Going back to what it says "ModCakeBlock must [define the method] tryEat(WorldAccess, BlockPos, BlockState, PlayerEntity)" because it inherits from CakeBlock. https://www.tutorialspoint.com/java/java_inheritance.htm

**Comment by Miros77** [comment]
> I would recommend using a custom mixin for this if you want to change the vanilla cake. This is not something that fabric api is likely to support any time soon. It should be as easy as targeting the tryEat method in the `CakeBlock.class` and modfying the constants for food and saturation using a `@ModifyConstant` mixin.
> 
> Your second message is because your child class is not implementing all of the methods that it's required to implement by the parent. Going back to what it says "ModCakeBlock must [define the method] tryEat(WorldAccess, BlockPos, BlockState, PlayerEntity)" because it inherits from CakeBlock. https://www.tutorialspoint.com/java/java_inheritance.htm

here's the code that doesn't work

package com.miros77.rbp.registry.all_cake;

import net.minecraft.block.CakeBlock;

  import net.minecraft.block.BlockState;
  import net.minecraft.entity.player.PlayerEntity;
  import net.minecraft.item.ItemStack;
  import net.minecraft.stat.Stats;
  import net.minecraft.util.ActionResult;
  import net.minecraft.util.Hand;
  import net.minecraft.util.hit.BlockHitResult;
  import net.minecraft.util.math.BlockPos;
  import net.minecraft.world.World;
  import net.minecraft.world.WorldAccess;

public class ModCakeBlock extends CakeBlock {
	public ModCakeBlock(Settings settings) {
		super(settings);
	}


@Override
public ActionResult onUse(BlockState state, World world, BlockPos pos, PlayerEntity player, Hand hand, BlockHitResult hit) {
        if (world.isClient) {
            ItemStack itemStack = player.getStackInHand(hand);
            if (this.tryEat(world, pos, state, player).isAccepted()) {
                return ActionResult.SUCCESS;
            }

            if (itemStack.isEmpty()) {
                return ActionResult.CONSUME;
            }
        }
 
        return this.tryEat(world, pos, state, player);
	}
	
@Override
public ActionResult tryEat(WorldAccess world, BlockPos pos, BlockState state, PlayerEntity player) {
        if (!player.canConsume(false)) {
            return ActionResult.PASS;
        } else {
            player.incrementStat(Stats.EAT_CAKE_SLICE);
            player.getHungerManager().add(2, 0.1F);
            int i = (Integer)state.get(BITES);
            if (i < 6) {
                world.setBlockState(pos, (BlockState)state.with(BITES, i + 1), 3);
            } else {
                world.removeBlock(pos, false);
            }

            return ActionResult.SUCCESS;
        }
	}
}

**Comment by Miros77** [comment]
code
![фигня](https://user-images.githubusercontent.com/59547044/94366444-fc453380-00e0-11eb-9bea-580b762addfc.PNG)
error
![фигня_1](https://user-images.githubusercontent.com/59547044/94366453-0830f580-00e1-11eb-8c99-a23bcfdb6e93.PNG)

**Comment by Miros77** [comment]
help

**Comment by Miros77** [comment]
> I would recommend using a custom mixin for this if you want to change the vanilla cake. This is not something that fabric api is likely to support any time soon. It should be as easy as targeting the tryEat method in the `CakeBlock.class` and modfying the constants for food and saturation using a `@ModifyConstant` mixin.


I would recommend using a custom mixin for this if you want to change the vanilla cake. This is not something that fabric api is likely to support any time soon. It should be as easy as targeting the tryEat method in the CakeBlock.class and modfying the constants for food and saturation using a @ModifyConstant mixin. - when will it be done

**Comment by Miros77** [comment]
I managed to do

**Comment by Miros77** [comment]
public class ChokoladeCakeBlock extends CakeBlock {
	public ChokoladeCakeBlock() {
		super(FabricBlockSettings.of(Material.CAKE));
	}

   public ActionResult onUse(BlockState state, World world, BlockPos pos, PlayerEntity player, Hand hand, BlockHitResult hit) {
      if (world.isClient) {
         ItemStack itemStack = player.getStackInHand(hand);
         if (this.tryEat(world, pos, state, player).isAccepted()) {
            return ActionResult.SUCCESS;
         }

         if (itemStack.isEmpty()) {
            return ActionResult.CONSUME;
         }
      }

      return this.tryEat(world, pos, state, player);
   }

   public ActionResult tryEat(WorldAccess world, BlockPos pos, BlockState state, PlayerEntity player) {
      if (!player.canConsume(false)) {
         return ActionResult.PASS;
      } else {
         player.incrementStat(Stats.EAT_CAKE_SLICE);
         player.getHungerManager().add(7, 0.5F);
         int i = (Integer)state.get(BITES);
         if (i < 6) {
            world.setBlockState(pos, (BlockState)state.with(BITES, i + 1), 3);
         } else {
            world.removeBlock(pos, false);
         }

         return ActionResult.SUCCESS;
      }
   }
}

**Comment by i509VCB** [comment]
~~Is this your extended cake or the vanilla one?~~ (lmao I should have just read)

For the extended cake, you would add the property via `appendProperties`

**Comment by Miros77** [comment]
how to add effects

**Comment by haykam821** [comment]
```java
player.applyStatusEffect(new StatusEffectInstance(effect, amplifier, duration);
```
