### ISSUE TITLE
Could not find required mod (fabric loader 0.9.3+build. 207-1.16.3) 

### ISSUE THREAD

**Issue by chainsawpenguin** [FabricMC/fabric#1101]
Using (trying to) fabric 1.16.3
"Could not find required mod: betterf3 requires minecraft @ 1.16.2"
"creating empty clause"
   I removed betterf3 completely, still same error. 
Even with all mods removed, fabric api being the mod mod in the folder, and reinstalling everything. 
Nothing. 
Everytime same failed to launch error and minecraft says: "game crashed exit code 0"
Any help would be greatly appreciated. This is driving me crazy.

**Comment by ghost** [comment]
In this case you have to use exactly minecraft 1.16.2 because of how the mod developer defined it in the manifest, not 1.16.1 or 1.16.3 otherwise it'll crash.

**Comment by i509VCB** [comment]
Closing since this is not an issue with Fabric API and lack of feedback. If you need further assistance, please join the Fabric discord https://discord.gg/v6v4pMv
