### ISSUE TITLE
crash on interacting with villager

### ISSUE THREAD

**Issue by melzyy** [FabricMC/fabric#1103]
crashlog below
[crash-2020-09-26_13.17.56-client.txt](https://github.com/FabricMC/fabric/files/5286508/crash-2020-09-26_13.17.56-client.txt)
just clicking villager in any world and game crashes

**Comment by zerofelero** [comment]
having same issue i opened issue #1105

**Comment by i509VCB** [comment]
I see the issue, we fixed this on 1.16 branch but never cherrypicked it to 1.15, will open a fix in a second

**Comment by i509VCB** [comment]
I have opened a fix, sorry for the late response. Should be fixed in when modmuss can attend to fabric api.

**Comment by i509VCB** [comment]
Issue has been resolved. Please update fabric api for the fix.
