### ISSUE TITLE
Crash when trying to trade with villager. only happens when trying to open villager GUI (see pastebin link for crash log)

### ISSUE THREAD

**Issue by zerofelero** [FabricMC/fabric#1105]
https://pastebin.com/0fZYtfvq

**Comment by i509VCB** [comment]
I have a fix open for this, you may need to wait a bit till modmuss wakes up.

**Comment by Miros77** [comment]
> modmuss wakes up

modmuss wakes up :)

**Comment by modmuss50** [comment]
where is the fix?

**Comment by modmuss50** [comment]
Oh this 1.15, through it was another crash in 1.16 :D once im done working ill sort it

**Comment by Miros77** [comment]
> Oh this 1.15, through it was another crash in 1.16 :D once im done working ill sort it

sorry

**Comment by i509VCB** [comment]
Issue has been resolved. Please update fabric api for the fix.
