### ISSUE TITLE
dark texture on versions 1 16 2/1 16 3

### ISSUE THREAD

**Issue by Miros77** [FabricMC/fabric#1131]
https://github.com/Miros77/Realistic-Bakery-Products---Fabric/edit/master/src/main/java/com/miros77/rbp/RBPclient.java

https://github.com/Miros77/Realistic-Bakery-Products---Fabric/blob/master/src/main/java/com/miros77/rbp/registry/all_cake/StrawberryBushBlock.java

https://github.com/Miros77/Realistic-Bakery-Products---Fabric/blob/master/src/main/java/com/miros77/rbp/registry/ModItems.java

Bug
![image](https://user-images.githubusercontent.com/59547044/96655404-0c4ddd00-1346-11eb-9d19-a4ef7a895ffe.png)

what changes from version 1 16 2?

**Comment by Miros77** [comment]
the code is written correctly

**Comment by i509VCB** [comment]
I assume this is a json model?

I am not fully sure what the difference is between the two bushes.

**Comment by Miros77** [comment]
> I assume this is a json model?
> 
> I am not fully sure what the difference is between the two bushes.

I tried changing the model but it still doesn't work

**Comment by Miros77** [comment]
> I assume this is a json model?
> 
> I am not fully sure what the difference is between the two bushes.

error in code, can't find

**Comment by Miros77** [comment]
![2020-10-18_19 15 28](https://user-images.githubusercontent.com/59547044/96657101-f9d5a280-1349-11eb-8317-f09509843a88.png)
this is what happens when you put a bush model

**Comment by Miros77** [comment]
![2020-10-04_02 18 34](https://user-images.githubusercontent.com/59547044/96657285-78324480-134a-11eb-9574-36e81167999d.png)
this is how they should be

**Comment by OverlordsIII** [comment]
> ![2020-10-18_19 15 28](https://user-images.githubusercontent.com/59547044/96657101-f9d5a280-1349-11eb-8317-f09509843a88.png)
> this is what happens when you put a bush model

The bushes should be specified with a rendercutout
try putting this into your ClientModInitializer
```java
BlockRenderLayerMap.INSTANCE.putBlock(YOUR_BLOCK, RenderLayer.getCutoutMipped());
//Maybe that will work

**Comment by OverlordsIII** [comment]
> https://github.com/Miros77/Realistic-Bakery-Products---Fabric/edit/master/src/main/java/com/miros77/rbp/RBPclient.java
> 
> https://github.com/Miros77/Realistic-Bakery-Products---Fabric/blob/master/src/main/java/com/miros77/rbp/registry/all_cake/StrawberryBushBlock.java
> 
> https://github.com/Miros77/Realistic-Bakery-Products---Fabric/blob/master/src/main/java/com/miros77/rbp/registry/ModItems.java
> 
> Bug
> ![image](https://user-images.githubusercontent.com/59547044/96655404-0c4ddd00-1346-11eb-9d19-a4ef7a895ffe.png)
> 
> what changes from version 1 16 2?

As for this, you could try putting .nonOpaque() in your block settings for that specific block

**Comment by Miros77** [comment]
> > https://github.com/Miros77/Realistic-Bakery-Products---Fabric/edit/master/src/main/java/com/miros77/rbp/RBPclient.java
> > https://github.com/Miros77/Realistic-Bakery-Products---Fabric/blob/master/src/main/java/com/miros77/rbp/registry/all_cake/StrawberryBushBlock.java
> > https://github.com/Miros77/Realistic-Bakery-Products---Fabric/blob/master/src/main/java/com/miros77/rbp/registry/ModItems.java
> > Bug
> > ![image](https://user-images.githubusercontent.com/59547044/96655404-0c4ddd00-1346-11eb-9d19-a4ef7a895ffe.png)
> > what changes from version 1 16 2?
> 
> As for this, you could try putting .nonOpaque() in your block settings for that specific block

he lies there

**Comment by Miros77** [comment]
![image](https://user-images.githubusercontent.com/59547044/96658333-e4ae4300-134c-11eb-8031-8a5467ae94cb.png)

**Comment by OverlordsIII** [comment]
What do you mean by "he lies there"?

**Comment by OverlordsIII** [comment]
Oh then, i dont know about that specific bush sorry

**Comment by Miros77** [comment]
> ```java
> BlockRenderLayerMap.INSTANCE.putBlock(YOUR_BLOCK, RenderLayer.getCutoutMipped());
> Maybe that will work
> ```

i will try this

**Comment by Miros77** [comment]
![image](https://user-images.githubusercontent.com/59547044/96659443-9fd7db80-134f-11eb-8250-d8fbcf769fcc.png)
???

**Comment by ghost** [comment]
Right [here](https://github.com/Miros77/Realistic-Bakery-Products---Fabric/blob/035d2883d222c30521efb2fefa318b17cf1ed455/src/main/resources/fabric.mod.json#L23), do this:
```json
"entrypoints": {
    "main": [
      "com.miros77.rbp.Tutorial"
    ],
    "client": [
      "com.miros77.rbp.RBPclient"
    ]
},
```
And it'll work.

In the future, other curse forge pages, and the issues for fabric api, are not the places to go looking for help with your own mod. The fabric wiki is a good place to look. In fact they have a whole article on how to do exactly what you want (https://fabricmc.net/wiki/tutorial:blockappearance). If you aren't getting the help you want the [fabric discord](https://discord.gg/v6v4pMv) is also a good place to go. Specifically the `#mod-dev-1`, `#mod-dev-2`, and `#mod-dev-3` channels.

**Comment by Miros77** [comment]
> Right [here](https://github.com/Miros77/Realistic-Bakery-Products---Fabric/blob/035d2883d222c30521efb2fefa318b17cf1ed455/src/main/resources/fabric.mod.json#L23), do this:
> 
> ```json
> "entrypoints": {
>     "main": [
>       "com.miros77.rbp.Tutorial"
>     ],
>     "client": [
>       "com.miros77.rbp.RBPclient"
>     ]
> },
> ```
> 
> And it'll work.
> 
> In the future, other curse forge pages, and the issues for fabric api, are not the places to go looking for help with your own mod. The fabric wiki is a good place to look. In fact they have a whole article on how to do exactly what you want (https://fabricmc.net/wiki/tutorial:blockappearance). If you aren't getting the help you want the [fabric discord](https://discord.gg/v6v4pMv) is also a good place to go. Specifically the `#mod-dev-1`, `#mod-dev-2`, and `#mod-dev-3` channels.

Oh, thank you very much!!!!
