### ISSUE TITLE
Fabric Item Groups Clash

### ISSUE THREAD

**Issue by ghost** [FabricMC/fabric#1132]
Cinderscapes (1.16.3) and Astromine (1.16.3) are encountering a compatibility issue that I believe might actually be an issue with fabric api. When Astromine is installed it causes the Cinderscapes item group to take over the vanilla item groups (TerraformersMC/Cinderscapes#91). From my testing this only occurs when Astromine is installed, I haven't encountered any other mods that do this (including large mods that add item groups like Terrestria and Tech Reborn). Both Astromine and Cinderscapes, however, use fabric api (seemingly as intended) in order to add item groups which makes me believe this is maybe an edge case in how fabric api implements item groups and needs to be fixed. The following are code snippets as to how both mods use fabric api to create item groups.

### Astromine
```java
public static ItemGroup register(String id, Supplier<ItemConvertible> icon) {
    return FabricItemGroupBuilder.build(AstromineCommon.identifier(id), () -> new ItemStack(icon.get()));
}
```

### Cinderscapes
```java
public static void init() {
     FabricItemGroupBuilder.create(Cinderscapes.id("items"))
         .icon(() -> CinderscapesBlocks.UMBRAL_FUNGUS.asItem().getDefaultStack())
         .appendItems((stacks) -> {
             Registry.ITEM.stream().filter((item) -> {
                 return Registry.ITEM.getId(item).getNamespace().equals(Cinderscapes.NAMESPACE);
             }).forEach((item) -> stacks.add(new ItemStack(item)));
         })
         .build();
}
```

Which both seem to be valid uses of the api. I think a good fix that I'm going to try will be to add a registry iterator and callback outside of the item group creator and add items that way, but either way this seems like the api is somehow broken.

**Comment by ghost** [comment]
Update, could possibly have been an issue with Astromine and CCA in which case this issue should be closed. A follow up should be done on the Astromine/CCA side to make sure everything is fine.

**Comment by Miros77** [comment]
what is this bug about?
https://github.com/FabricMC/fabric/issues/1131

**Comment by Vaerian** [comment]
@Miros77 Why are you here, your personal modding issues have literally nothing to do with any of my projects, nor this issue. It seems like multiple people have tried to help you at this point I don't know what more I can even do.

**Comment by ghost** [comment]
Update, it's not just one thing making me think it really is fabric api. Curios API (Yes only the library for Curios) also triggers it making me think again that it's probably a fabric api issue.
