### ISSUE TITLE
[ViaVersion] Ignoring incoming plugin channel register of 'fabric-screen-handler-api-v1:open_screen', as it is longer than 32 characters

### ISSUE THREAD

**Issue by xhmr** [FabricMC/fabric#1133]
When joining the server with 1.16.3 it shows a warning/error in the server's console:
[ViaVersion] Ignoring incoming plugin channel register of 'fabric-screen-handler-api-v1:open_screen', as it is longer than 32 characters

**Comment by i509VCB** [comment]
This is caused by via version on the other side which is probably running on a 1.15.2 server.

I know paper has a system property that can lengthen that

**Comment by xhmr** [comment]
@i509VCB 1.16.3. is not allowing channels that are longer than 32 chars or something like that. Server is on 1.8.

**Comment by creeper123123321** [comment]
ViaVersion skips plugins channels longer than 32 because old spigot versions imposes that limit by kicking the player

**Comment by xhmr** [comment]
@creeper123123321 is it safe?

**Comment by i509VCB** [comment]
This shouldn't cause any issues since the server is likely vanilla-like and 1.8 and this is just a warning in the log. This should not affect gameplay.
