### ISSUE TITLE
RAM leaking 

### ISSUE THREAD

**Issue by JosersRu** [FabricMC/fabric#1139]
Hi, I have a problem. I run  minecraft server and it uses RAM on the empty server - it's ok, but after a while, when we're on the server (5-10 players) the memory starts leaking. Server uses over 3.5GB of RAM, even though all players close to each other on the map.

server config - 1 cpu, 3 GB RAM, this server is virtual (i dont have access to server console), I have installed fabric installer 0.6.1.51

On image -
1 - Players online (0)
2 - CPU usage
3 - RAM usage

![image](https://user-images.githubusercontent.com/14889459/97008495-91eeaa00-154b-11eb-874a-f49900aee267.png)

PS - Also server starts using about 80% of ram after some time (from 5 to 10 hours), even if nobody have connected to the server in that period

**Comment by Genau6502** [comment]
The 80% usage is normal, any server will do that. If you can’t send any information such as logs then we can’t help. The RAM leaking is probably a problem with your host, java will kill a program if it cannot stay under the memory limit

**Comment by i509VCB** [comment]
We are going to need more information about the setup, installed mods, whether the hosting using some oddball jvm args, etc

**Comment by maityyy** [comment]
Newer versions use a lot of memory, so this is not a Fabric issue. By the way, I recommend changing your hosting)

**Comment by modmuss50** [comment]
Closing this due to lack of infomation. If there is an issue profiling results would help a lot in tracking the issue down.
