### ISSUE TITLE
Long gamerule names get hidden by enum buttons

### ISSUE THREAD

**Issue by Pyrofab** [FabricMC/fabric#1145]
![image](https://user-images.githubusercontent.com/25536265/97791275-f60b1100-1bd0-11eb-83eb-fa08bcfec65b.png)
The boolean gamerule's name gets wrapped properly, but not the enum gamerule's.

One fix could be to change the way text is wrapped to account for the bigger size of enum buttons, but that would require either a mixin to `NamedRuleWidget` or a copy-paste of `drawName`.

**Comment by i509VCB** [comment]
We could just return the enum button to normal size.

There is a limitation with Minecraft's list widget. We cannot just go to double height entries for the rule widget from what I see. We could just add two entries but that is hacky.

**Comment by i509VCB** [comment]
Oops didn't mean to close
