### ISSUE TITLE
Ore Dictionary 

### ISSUE THREAD

**Issue by rantuhin** [FabricMC/fabric#1154]
Will the Fabric have something like Ore Dictionary (as in Forge)?

**Comment by YTG1234** [comment]
Fabric has tag conventions

**Comment by YTG1234** [comment]
does Forge still even have oredict in the newer versions?

**Comment by Leo40Git** [comment]
[No sense in implementing something Vanilla already has.](https://minecraft.gamepedia.com/Tags)
I'm pretty sure Forge itself also yeeted oredict in favor of tags.

**Comment by YTG1234** [comment]
Yep, Forge has things like `forge:ores/iron`, while with Fabric we use `c:iron_ores`

**Comment by YTG1234** [comment]
(Actually iron ores may be a vanilla thing, I haven't checked)

**Comment by rantuhin** [comment]
I tried to do it like this: 
https://github.com/CottonMC/CottonResources/blob/1.15.2/src/main/resources/data/c/tags/items/aluminum_dusts.json
https://github.com/CottonMC/CottonResources/blob/1.15.2/src/main/resources/data/c/tags/items/aluminum_dust.json
But:
> [22:52:55] [main/ERROR] (Minecraft) Couldn't load item tag c:sand_dust as it is missing following references: c:sand_dust (from SandProject)
[22:52:55] [main/ERROR] (Minecraft) Couldn't load item tag c:sand_dusts as it is missing following references: c:sand_dust (from SandProject),#c:sand_dust (from SandProject)

**Comment by YTG1234** [comment]
well, of course, you need to define the tag

**Comment by YTG1234** [comment]
src/main/resources/data/c/tags/items/sand_dusts:
```json
{
    "replace": false,
    "values": [
        "yourmodid:youritem"
    ]
}
```

**Comment by rantuhin** [comment]
sand_dusts:
```json
{
  "replace": false,
  "values": [
    "sandproject:sand_dust",
    "#sandproject:sand_dust"
  ]
}
```
sand_dust:
```json
{
  "replace": false,
  "values": [
    "c:sand_dust"
  ]
}
```
>[23:13:05] [main/ERROR] (Minecraft) Couldn't load item tag c:sand_dust as it is missing following references: c:sand_dust (from SandProject)
[23:13:05] [main/ERROR] (Minecraft) Couldn't load item tag c:sand_dusts as it is missing following references: #sandproject:sand_dust (from SandProject)

I don't understand why cottonmc has "c:tag" tags everywhere and everything works (otherwise the developer changed it), but it doesn't work for me

**Comment by YTG1234** [comment]
what are you doing here, just do:
```json
{
  "replace": false,
  "values": [
    "sandproject:sand_dust"
  ]
}
```
Assuming `sandproject:sand_dust` is your item's name

**Comment by Prospector** [comment]
For modding support, I would recommend visiting the Fabric discord server: https://discord.gg/v6v4pMv
