### ISSUE TITLE
Crashing on game load

### ISSUE THREAD

**Issue by Kangy1103** [FabricMC/fabric#1169]
Hi, I'm developing a custom modpack on Fabric. However, whenever I try to load the pack I get "java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'imm_ptl_core'!"

So I disable the mod and any other dependencies for it. Reload the pack and then I get the same error but with a different mod. This carries on indefinitely.

Not sure what's causing it as i'm brand new to Fabric but here is my crash log
[crash-2020-11-19_00.03.00-client.txt](https://github.com/FabricMC/fabric/files/5563452/crash-2020-11-19_00.03.00-client.txt)

I'm using Minecraft 1.16.3 and Fabric Loader 0.10.8.

Let me know if you need any more information from me :)

**Comment by OverlordsIII** [comment]
Well from this crash there are a number of things that are being suppressed but from the main crash it looks like you would need sodium in your modpack as one of your mods depends on it, which seems to be `hiding_in_the_bushes` (relative name, might be bundled with another mod). Try installing sodium if you dont have it. If you have it...


something else went wrong big time lol

**Comment by Kangy1103** [comment]
> Well from this crash there are a number of things that are being suppressed but from the main crash it looks like you would need sodium in your modpack as one of your mods depends on it, which seems to be `hiding_in_the_bushes` (relative name, might be bundled with another mod). Try installing sodium if you dont have it. If you have it...
> 
> something else went wrong big time lol

Hi, thanks for the response. I do have sodium installed.

The 'hiding_in_the_bushes' isn't on my mod list so must be a part of something else

**Comment by Kangy1103** [comment]
Going to close this. Iron Jetpacks, Immersive Portals and Doors of Infinity were causing my issues
