### ISSUE TITLE
[Bug] Features Not Generating in 0.26.0 With Custom Biomes

### ISSUE THREAD

**Issue by ghost** [FabricMC/fabric#1170]
In version 0.26.0, custom features don’t seem to generate. My mod, which includes a “End Forest” biome, should have naturally spawning End Trees, a custom feature that worked when spawned in a custom Overworld biome in 0.25.7, no longer works in 0.26.0. I have also noticed that in 0.26.0, any features such as ores that I had included in custom biomes or in biome modifications, would not spawn. To recreate, just attempt to make a custom feature spawn anywhere in custom biomes, especially the End.

**Comment by i509VCB** [comment]
Could you provide a minimal example to reproduce this?

**Comment by ghost** [comment]
Of course, sorry I didn't get back sooner.

**Comment by ghost** [comment]
Here are a few of my pastebins from the mod...

[Registry](https://pastebin.com/MweLzcBx), [Feature](https://pastebin.com/Ue79NXrR), and [Biome](https://pastebin.com/Nx4M4aak)

But when I generate the biomes and tp to them, no features generate. I then checked to see if my custom ores were still generating using BiomeModifications in the Overworld, and they were not. I then took away the end biome and tried the custom feature, as well as custom ores, in the wiki's tutorial biome and again: nothing happened. When I reverted to 0.25.7, everything fixed itself, except there is no End Biome API, so I'm not able to create the custom End Biome.

0.26.0:
![2020-11-20_16 43 30](https://user-images.githubusercontent.com/54190597/99857891-e50b4b00-2b51-11eb-91e8-142d64f1f7a8.png)

0.25.7:
![image](https://user-images.githubusercontent.com/54190597/99858407-1e908600-2b53-11eb-9629-19e0f87bbd86.png)

**Comment by Steven-Baez** [comment]
this same thing is happening to me

**Comment by Technici4n** [comment]
Please open a new issue if such problems are still occurring in 1.18+.
