### ISSUE TITLE
[1.17 (20w46a)] Rendering entity

### ISSUE THREAD

**Issue by ghost** [FabricMC/fabric#1171]
It's unable to render entity in 20w46a use the following code:

`public class CubeEntityModel extends EntityModel<CubeEntity> {
 
    private final ModelPart base;
 
    public CubeEntityModel() {
        base = new ModelPart(this, 0, 0);
        base.addCuboid(-6, -6, -6, 12, 12, 12);
    }
 
    [...]
}`

How can I do this another way?

**Comment by i509VCB** [comment]
I believe the code there has changed a considerable amount. If you know of what needs to be done to restore that feature please let us know.

We don't guarantee stability on snapshots but we do accept help from anyone who wants to get them working.
If you ask on the fabric discord someone is bound to know what needs to be done to fix it.
