### ISSUE TITLE
UseBlockCallback called multiple times for one click

### ISSUE THREAD

**Issue by phase** [FabricMC/fabric#119]
```java
UseBlockCallback.EVENT.register((player, world, hand, hitResult) -> {
            System.out.println("hit thing");
});
```
If I right click a block with an empty hand, this is printed out 4 times.
If I place a block, this is printed 2 times.
I'm using 19w07a.

**Comment by asiekierka** [comment]
It's called once on the server and client. Being called twice on each is definitely a bit odd, though.

**Comment by InsomniaKitten** [comment]
Once for each hand

**Comment by phase** [comment]
Doing a hand & side check made it fire once. Thanks!

**Comment by flier268** [comment]
How do I know that who call UseBlockCallback?
(client or server)

**Comment by Blayyke** [comment]
> How do I know that who call UseBlockCallback?
> (client or server)

world.isClient() will return true if it is on the client, and false on the server.

**Comment by flier268** [comment]
Thanks a lot
