### ISSUE TITLE
"Could not find required mod: fabric requires {minecraft @ [~1.17-alpha.20.45.a]}"

### ISSUE THREAD

**Issue by TheSexyYeti** [FabricMC/fabric#1198]
I'm trying to play Minecraft 1.16.4 with fabric. I have fabric 1.16.4 installed. But I Keep getting this message.

**Comment by OroArmor** [comment]
you are trying to play with a 1.17 version of fabric-api, which does not work with 1.16. you need to replace your version of fabric-api with a 1.16 version

**Comment by TheSexyYeti** [comment]
No the version of fabric i installed was for Minecraft 1.16.4. The folder for fabric that I installed even says 1.16.4. So either it's installing the wrong version and it's miss labeled. Or it's the loader version that's at fault here. So which loader version do I use to fix this issue?.
![FABRIC](https://user-images.githubusercontent.com/50222286/100933303-23dac280-34bb-11eb-9e95-e742e38bd5fc.jpg)

**Comment by OroArmor** [comment]
yes, fabric is installed correctly. however, you have the wrong version of fabric-api in your mods folder

you need the 1.16.4 version, not the 1.17 snapshot versions. *This is for the fabric-api mod, not your installation*

**Comment by TheSexyYeti** [comment]
Hmmm you're right. The new CurseForge Launcher downloaded the wrong version. Much appreciated.

**Comment by OroArmor** [comment]
thanks! could you close the issue?

**Comment by K0-RR** [comment]
Hi, just a friendly reminder - maybe someone closes this already. @TheSexyYeti
