### ISSUE TITLE
Registry for custom entities (???)

### ISSUE THREAD

**Issue by Hoborific** [FabricMC/fabric#12]
Unable to find anything remotely close what I am trying to achieve of registering a custom entity extending a custom render

**Comment by liach** [comment]
It should be in entitytypes

**Comment by asiekierka** [comment]
Yes, but tracking is necessary.

I propose a two-part approach, not unlike what we do with ToolManager:

* Add a TrackableEntityTypeRegistry, which has a Map<EntityType, EntityTrackingEntry>, or something of the sort.
* For most people, add a FabricEntityTypeBuilder which acts like EntityType.Builder but adds a .trackable(...) option, which automatically registers in said registry.

**Comment by asiekierka** [comment]
https://paste.asie.pl/SaMR

Here's how to make a chicken.
