### ISSUE TITLE
Make it easier for server admins to ban players for playing with a controller instead of mouse and keyboard

### ISSUE THREAD

**Issue by SoniEx2** [FabricMC/fabric#1200]
Fabric should tell server admins that users are playing with a controller because it's cheating and they should totally be banned for it.

Apparently, anyway.

(We don't stand for DRM. Yes, this is passive-aggressive. Please don't add DRM. We've gone 2 years without DRM, we don't need it now. Leave DRM to forgeland.)

**Comment by haykam821** [comment]
Not in scope for Fabric API

**Comment by SoniEx2** [comment]
Is sending the mod list not part of Fabric API?

**Comment by haykam821** [comment]
No

**Comment by SoniEx2** [comment]
what's it part of then?

**Comment by Ueaj-Kerman** [comment]
a mod

**Comment by i509VCB** [comment]
Completely out of scope for fabric api.
