### ISSUE TITLE
20w49a Fabric API crashes server

### ISSUE THREAD

**Issue by catter1** [FabricMC/fabric#1203]
My Fabric server is running 20w49a. When using Fabric API, the server will crash every 10 seconds to 10 minutes. Sample crash log (out of many) found here: [Pastebin](https://pastebin.com/bAbHykdS)

I brought this up in the Discord, but wanted to make an official report so y'all would know what's going on. Let me know if you would like more information.

**Comment by i509VCB** [comment]
Hi, I found the issue. Writing up a fix for it. There was a change in 20w49a within one of the methods which broke one of our redirects.

**Comment by DrKendall** [comment]
I want to share that I have the exact same issue. Was on 20w49a, now rolled back to 20w48a and still got the same problem.

**Comment by i509VCB** [comment]
The fix has been published. Please download new fabric api.
