### ISSUE TITLE
fabric-resource-loader: assets not loaded from non-`main` source sets in dev

### ISSUE THREAD

**Issue by TwilightFlower** [FabricMC/fabric#1219]
Resource loader doesn't load assets from source sets apart from `main` in dev. This causes issues with annotation processors that generate resources, as they output into the `default` source set (at least under Eclipse.) This appears to be caused by the resources being loaded from the filesystem rather than from the classpath.

**Comment by i509VCB** [comment]
Do you have a simple test case to reproduce this?

**Comment by TwilightFlower** [comment]
Not exactly, considering there doesn't really exist such a thing as a non-complex annotation processor. Will try to clean up a bit of the awful code in mine and upload it, though.

**Comment by TwilightFlower** [comment]
Uploaded my annotation processor that can be used to reproduce this issue [here](https://github.com/Nuclearfarts/mc-ap). The code that actually utilizes it looks something like this:
```
@RegistryContainer("modid", blockModel = BlockModelAction.BASIC_BLOCK)
public class Init implements ModInitializer {
@RegisterBlock("test")
public static final Block Test = ...

public void onInitialize() {InitRegistrar.register();}
}
```
(InitRegistrar is also generated by the annotation processor.)

**Comment by Technici4n** [comment]
With the newer Fabric Loader versions, it is now possible to specify multiple paths for a specific mod, so you can add extra paths for the additional resource folders.
