### ISSUE TITLE
Structure Location API

### ISSUE THREAD

**Issue by oliviathevampire** [FabricMC/fabric#123]
We should have an API for structure location, since then we can locate our structures a lot easier, maybe even make the /locate command be able to locate every registered structure instead of just hardcoded ones

**Comment by i509VCB** [comment]
Ideally for this we would listen to registrations of new structures going into the registry and add them into the list.

**Comment by liach** [comment]
Think vanilla chunk generator already supports structure locating.

**Comment by i509VCB** [comment]
If I recall, the command doesn't register the literals for custom structures, which is what this module would potentially do

**Comment by i509VCB** [comment]
In 1.16+ the locate command now uses the structures map supplied by the structure api.

This issue has been resolved and is closed for 1.16.
