### ISSUE TITLE
Ability to create an EnumRarity

### ISSUE THREAD

**Issue by marcus8448** [FabricMC/fabric#125]
Just the ability to create an `EnumRarity` - There's no create method right now.

**Comment by asiekierka** [comment]
Enums can't be created at runtime, though? Not with our existing toolset, anyway.

**Comment by liach** [comment]
you can copy paste the existing reflection-based enum creator online, but currently you cannot guard against jvm optimizations.

**Comment by Boundarybreaker** [comment]
:voldethonk:

also yeah, trying to add to an enum rarely works well, I'd recommend just using the § color marker to change the color of your item's name

**Comment by marcus8448** [comment]
Ok, thanks.
