### ISSUE TITLE
FabricLoader.getInstance doesn't exist.

### ISSUE THREAD

**Issue by imreallybadatnames** [FabricMC/fabric#1261]
The only way to access the instance of `FabricLoader` is to use `FabricLoader.INSTANCE`.

**Comment by haykam821** [comment]
Is there a Fabric API problem here?

**Comment by shedaniel** [comment]
imported the wrong FabricLoader there

**Comment by pluiedev** [comment]
ye they used `net.fabricmc.loader.FabricLoader` instead of `nf.loader.api.FabricLoader` (https://discord.com/channels/507304429255393322/721100785936760876/796743691032985600)

**Comment by imreallybadatnames** [comment]
Ok, found it in the interface. The interface selection didn't show up when i first imported it. Closing issue.

**Comment by imreallybadatnames** [comment]
Strange that it only showed the class. Had to manually insert `.api` into the import.
