### ISSUE TITLE
canSend in server no work in BungeeCord server.

### ISSUE THREAD

**Issue by plusls** [FabricMC/fabric#1262]
I use `ServerPlayNetworking.canSend` in normal server and it work perfectly, but after I install BungeeCord server, it no works.

But I can send packet directly.

**Comment by i509VCB** [comment]
Not sure if it may be bungeecord not propagating the registration packet to the client or if it is something on one of bungeecord's reserved channels.

**Comment by liach** [comment]
Hmm, I think many of those bridge stuff does not propagate any of the handshake packets.

**Comment by liach** [comment]
Also, if bungee consumed the packets, canSend would still update in my original v1 design (it sends minecraft:register if it didn't receive handshake payload). Does it work a while after the connection has established?

**Comment by apple502j** [comment]
Resolved in #3244
