### ISSUE TITLE
Carpet not in the list of commands

### ISSUE THREAD

**Issue by RileyMcQuin** [FabricMC/fabric#1275]
When I press /  and type carpet it does not come up even though I have mod menu, fabric loader and fabric api

**Comment by i509VCB** [comment]
Not really a question relating to fabric api, please ask on discord for further queries. Are you sure you have carpet installed and have the proper server permissions to use it (carpet may require you are an operator).

**Comment by RileyMcQuin** [comment]
What is the discord

**Comment by Technici4n** [comment]
https://discord.gg/v6v4pMv
