### ISSUE TITLE
wrong info about supported launchers

### ISSUE THREAD

**Issue by ghost** [FabricMC/fabric#1276]
Hello, the website did not mentchen TLancher as a supported lancher. But when I tried, it worked how it should.

**Comment by pluiedev** [comment]
Again, TLauncher is not supported as it enables piracy. Please use a legit launcher. (Also this is the wrong repo)

**Comment by ghost** [comment]
wait no

**Comment by ghost** [comment]
it worked!!

**Comment by ghost** [comment]
i will send screen shorts if you want!

**Comment by ghost** [comment]
and inwhick repo should i ask this?

**Comment by pluiedev** [comment]
To reiterate, pirated launchers are not allowed here. Even if those *are* allowed this is still the wrong place to ask. Github repositories should be used for technical questions only

**Comment by Suya1671** [comment]
TL is an illegal launcher, and fabric does not support it

**Comment by Genau6502** [comment]
Tlauncher allows piracy, please close

**Comment by Technici4n** [comment]
We do not support non-official launchers, and we only support users who paid for the game.

**Comment by ghost** [comment]
BUT... it worked when i tried!!!

**Comment by Suya1671** [comment]
doesnt matter, we do not encourage use of pirated launchers

**Comment by ghost** [comment]
want screen shorts?

**Comment by ghost** [comment]
oh ok

**Comment by Suya1671** [comment]
we do not care if it works, its illegal

**Comment by Genau6502** [comment]
We don’t care, you’re behaving like an 8 year old. Pay for the game

**Comment by ghost** [comment]
um ok.. I'm a 10 year old

**Comment by Technici4n** [comment]
**We do not support non-official launchers, and we only support users who paid for the game.**
If it works good for you, but you're on you're own and we don't want to know about it.
Now everyone please stop commenting and reacting, this is getting ridiculous.

**Comment by ghost** [comment]
ok bye

**Comment by Suya1671** [comment]
> um ok.. I'm a 10 year old

thats illegal. GH requires to be 13 or 14 years or older

**Comment by ghost** [comment]
gonta leave

**Comment by Suya1671** [comment]
ok bye

**Comment by ghost** [comment]
oh ok

**Comment by ghost** [comment]
i'm in whitehat

**Comment by ghost** [comment]
and they said to use github

**Comment by ghost** [comment]
so yea

**Comment by ghost** [comment]
bye

**Comment by Neubulae** [comment]
how many cringe can I receive from this single issue...?
I guess the answer is **YES** as of the moment...
