### ISSUE TITLE
Latest Fabric API (0.30.0) crashes w/ OptiFabric + OptiFine

### ISSUE THREAD

**Issue by HatTrkPatrk** [FabricMC/fabric#1288]
Minecraft 1.16.5

Version 0.30.0 of the Fabric API which released 5 hours ago (at time of this posting) causes a fatal crash at the title screen when using OptiFabric 1.8.16 and OptiFine 1.16.5 HD_U_G6 (both of which are most recent releases at time of posting as well).

The crash occurs when the title screen is coming up but the buttons (such as singleplayer, multiplayer, options etc) have not yet been rendered on screen.

Downgrading back to Fabric API version 0.29.4 fixes the crash.

I'll attach the latest.log produced by the crash.
[latest.log](https://github.com/FabricMC/fabric/files/5884000/latest.log)

Let me know if any further info would be helpful

**Comment by OroArmor** [comment]
this is something optifine/optifabric will have to fix. Fabric API doesn't support them

**Comment by Chocohead** [comment]
This is fixed in [OptiFabric 1.9.1+](https://www.curseforge.com/minecraft/mc-mods/optifabric/files/3183995)

**Comment by Technici4n** [comment]
We do not support Optifine. Please open an issue on Optifabric's repository if this issue persists.
