### ISSUE TITLE
Fabric API 0.30.0 Conflicts with Optifabric

### ISSUE THREAD

**Issue by Blobanium** [FabricMC/fabric#1290]
Ok so once i updated the fabric API From 0.29.4 to 0.30.0 my game started crashing on startup, Narrowing it down seems like Optifabric is the issue. I Can Open an issue with optifabric if i need to. I think its on optifabric's end but im opening an issue thread here just to be sure.

Crash log
[crash-2021-01-28_10.26.15-client.txt](https://github.com/FabricMC/fabric/files/5889360/crash-2021-01-28_10.26.15-client.txt)

Mods
![Capture](https://user-images.githubusercontent.com/45613796/106182687-0d1bb980-6154-11eb-8b1b-4cd500b3a6eb.PNG)

tell me if i need anything else thanks.

**Comment by Dolphin2Point1** [comment]
update your optifabric to 1.9.2

**Comment by Blobanium** [comment]
ok that seemed to work thanks for your help
