### ISSUE TITLE
When I load fabric it comes up with this "Could not find required mod: mmorpg requires {autoconfig1u @ [*]}"

### ISSUE THREAD

**Issue by edbertauduong** [FabricMC/fabric#1292]
If anyone can help please let me know

**Comment by OroArmor** [comment]
it means you need to download auto config
this is not an issue.

**Comment by OroArmor** [comment]
https://www.curseforge.com/minecraft/mc-mods/auto-config-updated-api

**Comment by edbertauduong** [comment]
oh whoops
sorry for the inconvenience
