### ISSUE TITLE
Banner Pattern API.

### ISSUE THREAD

**Issue by prohitman** [FabricMC/fabric#1294]
It would so nice if the fabric api provided a specific banner pattern api, of which we can add custom patterns without the need of going through the risks of ASMs. And i know abt the impossibilty of having extensible enums in general, but isnt there a specific way to make custom banner patterns easily doable?

**Comment by haykam821** [comment]
FabLabs has [Banner++](https://github.com/FabLabsMC/banner-plus-plus), which hopefully will become part of Fabric API eventually.

**Comment by prohitman** [comment]
> FabLabs has [Banner++](https://github.com/FabLabsMC/banner-plus-plus), which hopefully will become part of Fabric API eventually.

Oh that's nice! So it is confirmed?

**Comment by LemmaEOF** [comment]
> Oh that's nice! So it is confirmed?

It's under debate, and we're gonna see if it gets merged in. For now, just use Banner++ directly.

**Comment by haykam821** [comment]
Banner patterns can now be added using a registry:

```java
Identifier id = new Identifier("mymod", "pattern");
Registry.register(Registries.BANNER_PATTERN, id, new BannerPattern(id.toString()));
```

**Comment by islamzaoui** [comment]
> Banner patterns can now be added using a registry:
> 
> ```java
> Identifier id = new Identifier("mymod", "pattern");
> Registry.register(Registries.BANNER_PATTERN, id, new BannerPattern(id.toString()));
> ```

is there any guide to how to use it?
