### ISSUE TITLE
Fabrics fall from grace

### ISSUE THREAD

**Issue by TekiFromFabric** [FabricMC/fabric#1297]
Hello

I cannot fathom how it’s even possible for such a big discord to be so biased and prone to mob justice. Again, and again drama because moderators won’t get their shit together. And when shit finally hits the fan moderators simply side with who screams louder, simply pathetic.

Quick reminder for those who skipped biology lessons:

> The XY sex-determination system is the sex-determination system found in humans, most other mammals, some insects (Drosophila), and some plants (Ginkgo). In this system, the sex of an individual is determined by a pair of sex chromosomes (gonosomes). Females have two of the same kind of sex chromosome (XX), and are called the homogametic sex. Males have two distinct sex chromosomes (XY), and are called the heterogametic sex.

How does genetics equal being transphobic is beyond me, how this deserves a ban is even more of a mystery. 

**A person’s freedom ends where another man’s freedom begins.** 

You have all right to do to yourself whatever you want, be it dyeing hair, or invasive operations. You may call yourself whatever you want, do whatever you want until you encroach others right to freedom. Going along your make believe is a sing of goodwill especially if it’s against science and objective physical truth. Not abiding by your wishes is not being transphobic but simply realistic with is not a crime.

Cheers,

Teki (muted until further notice)

**Comment by i509VCB** [comment]
This does not belong on github. Take it to discord.
