### ISSUE TITLE
maybe have some question

### ISSUE THREAD

**Issue by csosy** [FabricMC/fabric#1299]
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2021-02-01 23:26:15 CST
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: org/apache/logging/log4j/util/ReflectionUtil
    at Not Enough Crashes deobfuscated stack trace.(1.15.2+build.14)
    at com.sk89q.worldedit.log4jbridge.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:42)
    at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:46)
    at com.sk89q.worldedit.log4jbridge.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:29)
    at com.sk89q.worldedit.slf4j.LoggerFactory.getLogger(LoggerFactory.java:358)
    at com.sk89q.worldedit.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
    at com.sk89q.worldedit.WorldEdit.<clinit>(WorldEdit.java:104)
    at com.sk89q.worldedit.fabric.FabricWorldEdit.setupPlatform(FabricWorldEdit.java:123)
    at com.sk89q.worldedit.fabric.FabricWorldEdit.onStartServer(FabricWorldEdit.java:168)
    at net.fabricmc.fabric.api.event.server.ServerStartCallback.lambda$null$0(ServerStartCallback.java:28)
    at net.minecraft.server.MinecraftServer.handler$zlg000$afterSetupServer(MinecraftServer:2810)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer:634)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.util.ReflectionUtil
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 12 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.15.2
  Minecraft Version ID: 1.15.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_241, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 7832733800 bytes (7469 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
  CPUs: 4
  JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx8192m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
  Suspected Mods: WorldEdit (worldedit), Fabric Events Lifecycle (v0) (fabric-events-lifecycle-v0), Fabric Loader (fabricloader)
  Fabric Mods: amecs: Amecs 1.2.9+1.15-pre5
               appleskin: AppleSkin 1.0.8
               autoconfig1u: Auto Config v1 Updated 1.2.4
               autofish: Autofish 0.8.5
               bbor: BoundingBoxOutlineReloaded 1.0.14-1.15.1
               carpet: Carpet Mod in Fabric 1.3.10
               carpet-extra: Carpet Extra 1.3.9
               cloth-config2: Cloth Config v2 2.8.3
               customskinloader: CustomSkinLoader 14.12-SNAPSHOT-109
               easiercrafting: EasierCrafting 1.15-fabric0.4.23-1.6.0.beta2
               easiervillagertrading: EasierVillagerTrading 1.14.4-fabric0.4.1-1.4
               fabric: Fabric API 0.4.32+build.292-1.15
               fabric-api-base: Fabric API Base 0.1.2+28f8190f42
               fabric-biomes-v1: Fabric Biomes (v1) 0.1.5+3b05f68e0c
               fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea890c
               fabric-commands-v0: Fabric Commands (v0) 0.1.2+b7f9825d0c
               fabric-containers-v0: Fabric Containers (v0) 0.1.3+b7f9825d0c
               fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825d0c
               fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d0c
               fabric-dimensions-v1: fabric-dimensions-v1 0.2.4+203491ea0c
               fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.2.7+a1bd31180c
               fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+b7f9825de8
               fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.6+ec40b2e10c
               fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+933c24c242
               fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.5+e08a73050c
               fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.1+28f8190f42
               fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d60c
               fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.3+e08a73050c
               fabric-networking-v0: Fabric Networking (v0) 0.1.8+9421522de7
               fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.3+e4c9a9c30c
               fabric-particles-v1: fabric-particles-v1 0.1.1+dfdb52d60c
               fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.6+f3d8141b0c
               fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.10+f08b61330c
               fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.23+9290e2ed0c
               fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a600c
               fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d0c
               fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+12515ed90c
               fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104900c
               fabric-rendering-v1: Fabric Rendering (v1) 0.1.0+534104900c
               fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.10+06c939b395
               fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+d423005742
               fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba70c
               fabricloader: Fabric Loader 0.7.8+build.184
               gbfabrictools: GBfabrictools 1.1.0
               handystructures: Handy Structures 1.0.3
               hopperoptimizations: Hopper Optimizations 0.1.14
               inventoryprofiles: Inventory Profiles 0.1.0-dev.6
               litematica: Litematica 0.0.0-dev.20200220.211141
               lithium: Lithium 0.3.2
               loadcatcher: Entrypoint Catcher 1.1.0
               malilib: MaLiLib 0.10.0-dev.20+arne.3
               me_shedaniel_cloth_basic-math: basic-math 0.3.0
               minecraft: Minecraft 1.15.2
               minihud: MiniHUD 0.19.0-dev.20200121.203515
               mm: Manningham Mills 2.0
               modmenu: Mod Menu 1.10.1+build.30
               mousewheelie: Mouse Wheelie 1.4.0+1.15.2-pre1
               nbtcrafting: NBT Crafting 2.0.0-alpha.12+1.15.2
               notenoughcrashes: Not Enough Crashes 1.2.2+1.15.1
               optifabric: Optifabric 1.0.0-beta4
               orderly: Orderly 2.0.0-alpha+build.7-1.15
               org_slf4j_slf4j-api: slf4j-api 1.7.30
               org_slf4j_slf4j-simple: slf4j-simple 1.7.30
               org_zeroturnaround_zt-zip: zt-zip 1.14
               pathsuggestion: Path Suggestion 0.3.0
               right-click-clear: Right Click Clear 1.1.1-unstable.201912010707
               shulkerboxtooltip: Shulker Box Tootip 1.4.5+1.15
               smallerfpsincrements: Smaller max FPS increments 1.0.1
               tweakeroo: Tweakeroo 0.10.0-dev.20200303.202420
               tweed: Tweed API 2.2.8
               voxelmap: VoxelMap 1.9.14
               waila: Hwyla 1.9.20
               worldedit: WorldEdit 7.1.0;8e55131
               worldeditcui: WorldEditCUI 1.15.1_01
  Player Count: 0 / 8; []
  Data Packs: vanilla (incompatible), fabric/fabric-mining-levels-v0 (incompatible), fabric/handystructures (incompatible)
  Type: Integrated Server (map_client.txt)
  Is Modded: Definitely; Client brand changed to 'fabric'

when I opened my saves it went wrong

**Comment by HastumeM** [comment]
hmm that looks like worldedit crashed to me?

**Comment by liach** [comment]
https://stackoverflow.com/questions/52700803/im-getting-noclassdeffounderror-org-apache-logging-log4j-util-reflectionutil

Worldedit needs an update. It is using outdated log4j.
