### ISSUE TITLE
Fabric MC Server crashes

### ISSUE THREAD

**Issue by Username-Is-Unavailabl** [FabricMC/fabric#1303]
I have set up a fabric MC Server and the server crashes due to a fatal error.
This is what the server shows me when it crashes: https://pastebin.com/tAH95paP
(If you couldn't tell, i'm a newbie when it comes to MC server hosting)

**Comment by YTG1234** [comment]
This issue should be transferred to [FabricMC/fabric-loader](https://github.com/FabricMC/fabric-loader).

You have an outdated (1.16.1 I think) version of Couplings. Update it.

**Comment by Username-Is-Unavailabl** [comment]
Ok, thanks for the fast reply!
The issue is now here: https://github.com/FabricMC/fabric-loader/issues/376
Also, i have Couplings version 1.3.1, wich is the latest version.
Should i leave this issue open or close it?
