### ISSUE TITLE
Issue with Fabric API When Seamless loading screen is installed

### ISSUE THREAD

**Issue by Blobanium** [FabricMC/fabric#1307]
So when i try to leave a server (i think maybe one with a resource pack maybe) i crash, thankfully i have not enough crashes installed and it suspected it to be the Fabric Screen API (Witch is a part of Fabric API)

Video of how i reproduced
https://streamable.com/opop6o

Mods folder
![mods folder](https://user-images.githubusercontent.com/45613796/106988482-bd755900-6724-11eb-8b6f-5586f32f7c21.PNG)

Crash log
[crash-2021-02-04_20.03.34-client.txt](https://github.com/FabricMC/fabric/files/5930032/crash-2021-02-04_20.03.34-client.txt)

And not enough crashes identifying it is Fabric screen API that causes the issue
![crash](https://user-images.githubusercontent.com/45613796/106988658-32e12980-6725-11eb-8e89-a6f62dcdd80b.PNG)

tell me if i need anything else thanks

**Comment by Prospector** [comment]
This is a known issue, tracking it here: #1289
