### ISSUE TITLE
ArrayBackedEvent assuming invoker generation when there is single callback

### ISSUE THREAD

**Issue by liach** [FabricMC/fabric#1311]
In the ArrayBackedEvent, the logic assumes that when there is a single callback, it can be used straight as an invoker.

However, this is not the case, as frequently invoker factory has different logic beyond simple dispatches.

An example: https://github.com/FabricMC/fabric/pull/1210/files#diff-11d2ce35b7dd909366a206d94a5b08a5f4d7fb4a37e8949c5e0ad2a741fed199R38-R45

Similarly, some invokers might have some arguments null when invoked, only lazily computed when listeners are present.

**Comment by liach** [comment]
Anyone has any comment? I don't know if we have an issue tag for discussion issues.

**Comment by Technici4n** [comment]
Wait this issue exists... 😄
This will be resolved by #1369.

**Comment by Technici4n** [comment]
Closed by the merge of #1369.
