### ISSUE TITLE
When I use Fabric, Im not able to open worlds/severs

### ISSUE THREAD

**Issue by Fport1** [FabricMC/fabric#1318]
Hi, Im having issues with Fabric. Since 2 weeks ago, when I use Fabric Minecraft, Im not able to enter to my worlds, or servers, since when I do this the game crashes. This doesn't happen with Vanilla Minecraft, but stills is better for me to use Fabric instead of Vanilla. Here is my last crash. 

[crash-2021-02-14_09.56.54-client.txt](https://github.com/FabricMC/fabric/files/5978547/crash-2021-02-14_09.56.54-client.txt)

Thanks for your help.

**Comment by liach** [comment]
@Fport1 Try removing not enough crashes mod and run again. If it crashes again upload the new crash report

**Comment by Fport1** [comment]
This don't solve the crash 

[crash-2021-02-14_18.52.20-client.txt](https://github.com/FabricMC/fabric/files/5978786/crash-2021-02-14_18.52.20-client.txt)

Also thanks for giving help

**Comment by liach** [comment]
Don't know what's at work here, but something is crashing so that you are actually crashing when the game crashes (i.e. this crash hides what actually caused your crash). And there is no sign on what caused this crash that prevents reporting the regular crash.

**Comment by Daomephsta** [comment]
Blame alters crash reports, so it's a possible cause.
