### ISSUE TITLE
FabricMC Groovy Language Adapter Submission

### ISSUE THREAD

**Issue by TheSledgeHammer** [FabricMC/fabric#132]
Hey, 
I don't know if you're interested but I have built a Groovy language adapter for FabricMC. I haven't uploaded it to curseforge or GitHub yet. I Was wondering if you guys & girls were interested in it before I did?
It hasn't had huge testing. Aside from the fact that it runs fine in Intellij
I have licensed it under the Apache 2.0
Let me know.
TheSledgeHammer

**Comment by asiekierka** [comment]
Approach modmuss50 on the Discord and discuss accordingly - most likely, it would become an official Fabric project (as language adapters tend to be).

**Comment by modmuss50** [comment]
Yeah, I’m sure we can sort something out.

**Comment by TheSledgeHammer** [comment]
I joined the discord channel. To make it easier. I am the same as on GitHub: TheSledgeHammer
