### ISSUE TITLE
Having Fabric Lifestyle Events (Fabric API) And MAmbience May Cause crashing when trying to TP To another Dimension

### ISSUE THREAD

**Issue by Blobanium** [FabricMC/fabric#1325]
I Also Opened an issue on MAmbience's issue tracker if u need further info [here](https://bitbucket.org/andre111/mambience/issues/18/trying-to-tp-to-another-dimension-may)

Heres the Crash log
[crash-2021-02-16_10.03.19-client.txt](https://github.com/FabricMC/fabric/files/5990874/crash-2021-02-16_10.03.19-client.txt)

My Fabric API Version is 0.30.3 and MAmbience's version im using is 3.0.0
Heres MAmbience's [Source Code](https://bitbucket.org/andre111/mambience/src/1.16/) if u need it

Heres the crash log 
[crash-2021-02-16_10.03.19-client.txt](https://github.com/FabricMC/fabric/files/5990906/crash-2021-02-16_10.03.19-client.txt)

tell me if i need to include anything else thanks

**Comment by liach** [comment]
So looks like this would happen if your connection is bad (i.e. registry packets are not received immediately). mambience should expect cases where registry packets are not processed in the first ticks into a new world.

**Comment by Blobanium** [comment]
Closing this issue as mambience fixed this on their end
