### ISSUE TITLE
Allow the use of Minecraft's test framework

### ISSUE THREAD

**Issue by LambdAurora** [FabricMC/fabric#1328]
[The Minecraft test framework described by Henrik Kniberg](https://www.youtube.com/watch?v=vXaWOJTCYNg) is a great tool.

It would be incredibly useful to Fabric API and other modders as well.

The current issue with it is that, only some parts are available in the Minecraft jar we get, some of the stuff like the `GameTestHelper` is removed by proguard.

This issue aims at the creation of a new module like `test-api-v1` (or a better name if you can find one) to allow the use of Minecraft's test framework and restore some of its missing classes/methods.

Once the test framework works, it would also be important to consider to extend it to allow tests of more stuff.

**Comment by Technici4n** [comment]
Oops I didn't mean to do that 😅

**Comment by Technici4n** [comment]
Was implemented a while ago.
