### ISSUE TITLE
Minecraft 1.16.5 Freeze on entering /hub on Server

### ISSUE THREAD

**Issue by SparkleArts** [FabricMC/fabric#1345]
My Minecraft Freeze on entering /hub on Server.

[Here](https://drive.google.com/file/d/1WEp6UnYOATWqFLv4k-SSkW1LYErFGHGI/view?usp=sharing) is a ZIP File of all Mods I installed for Fabric. Maybe is there a Mod that the Freeze occurs.

**Comment by Technici4n** [comment]
Hello, could you please post a thread dump so that we can see what your client is doing during the freeze? That would really help a ton! (search on google for how to do it)

**Comment by SparkleArts** [comment]
If you mean a thread dump through server console, then its not possible, because the server where my Game freeze is on GommeHD Server. Has over 1000 Players daily play on the server.

**Comment by modmuss50** [comment]
I would first post the logs instead of trying to get a thread dump.

**Comment by SparkleArts** [comment]
Here is the latest [log](https://drive.google.com/file/d/1CLpfFV_ixBohDOElL_zoux6QZnsC1eEW/view?usp=sharing).

**Comment by Technici4n** [comment]
How do you have 300 Mb of logs? That's not normal at all... I'll check when the download finishes.

**Comment by Technici4n** [comment]
Well the log is spamming `[14:07:59] [main/INFO]: OpenGL debug message, id=1280, source=API, type=ERROR, severity=HIGH, message=Error has been generated. GL error GL_INVALID_ENUM in (null): (ID: 173538523) Generic error`, whatever that is.

I see however that you are using Wurst, and we don't support hacked clients.
