### ISSUE TITLE
How to do client sided commands (fix your docs)

### ISSUE THREAD

**Issue by arduinka55055** [FabricMC/fabric#1349]
your current documentation says:
 ![https://i.imgur.com/LmALkw8.png](https://i.imgur.com/LmALkw8.png)
https://i.imgur.com/LmALkw8.png

cottonMC github says:
 ![https://i.imgur.com/rYYntrs.png](https://i.imgur.com/rYYntrs.png)
https://i.imgur.com/rYYntrs.png

i need to create client side only command, so can you tell how to do this (and update a bit outdated docs)

sorry if i missed that, but anyways i googled solution for hours and didnt find solution

**Comment by modmuss50** [comment]
Fabric API very recently got a client command API, you can see an example here: https://github.com/FabricMC/fabric/blob/1.16/fabric-command-api-v1/src/testmod/java/net/fabricmc/fabric/test/command/client/ClientCommandTest.java

The wiki page will need updating to reflect this.

**Comment by arduinka55055** [comment]
wow, thanks for quick reply :)

you helped me
