### ISSUE TITLE
Vanilla client compatibility

### ISSUE THREAD

**Issue by creeper123123321** [FabricMC/fabric#135]
Fabric doesn't try to check if mods are compatible with vanilla clients and don't remap the registry IDs for vanilla clients
Reproduction steps:
- Start a server with 19w11b with Fabric API only
- Upgrade the server to 19w14a
- Connect with a vanilla client - you may have a crash because the entity ids are wrong

**Comment by modmuss50** [comment]
I can confirm this, there are 2 issues here. Fabric should check the registries to see if the client can connect. As well fabric's registry should handle vanilla id changes between versions.

**Comment by UpcraftLP** [comment]
related to #88 kind of
