### ISSUE TITLE
Right clicking a villager leads to a game crash

### ISSUE THREAD

**Issue by gbl** [FabricMC/fabric#1360]
After summoning a villager and right clicking him, the game crashed. This happened with 21w10a and Fabric API 0.32.1+1.17.

The villager did not have a job as it was newly summoned, not sure if having a job would change anything.

Crashlog see gist: https://gist.github.com/gbl/f41e79adb6aff024acbe5ee1f50a430d

**Comment by Tunfisch96** [comment]
Not only Villagers. On every interaction with another entity the game/server crashes.

**Comment by RealRTTV** [comment]
Occurs on every entity lol

**Comment by Awakened-Redstone** [comment]
https://paste.gg/p/AwakenedRedstone/90160868d4574412bfc7980f0cb13a6c
For more information if needed

**Comment by modmuss50** [comment]
Fixed. Update.
