### ISSUE TITLE
Fabric launcher not loading when immersive portals is present

### ISSUE THREAD

**Issue by TheHuntHunter** [FabricMC/fabric#1372]
12:09:08.765
Preparing to launch minecraft client for fabric-loader-0.11.2-1.16.5
12:09:12.234
Checking installations.
12:09:12.235
Minecraft client fabric-loader-0.11.2-1.16.5 is ready to start.
12:09:12.235
Starting!
12:09:13.782
Using default game log configuration client-1.12.xml (outputs XML)
12:09:14.431
Loading for game Minecraft 1.16.5
12:09:14.744
The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
12:09:14.801
[FabricLoader] Loading 59 mods: fallflyinglib@1.1.0, fabric-renderer-api-v1@0.4.1+ca58154a7d, fabric-keybindings-v0@0.2.1+ca58154a7d, fabricloader@0.11.2, fabric-structure-api-v1@1.1.4+ca58154a7d, fabric-containers-v0@0.1.10+ca58154a7d, fabric-dimensions-v1@2.0.2+ca58154a7d, fabric-object-builder-api-v1@1.9.3+ca58154a7d, pehkui@1.8.0+21w08b, java@8, fabric-game-rule-api-v1@1.0.6+ca58154a7d, fabric-api-base@0.2.0+daa38b3d7d, fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d, fabric-textures-v0@1.0.6+ca58154a7d, fabric-rendering-fluids-v1@0.1.13+ca58154a7d, reach-entity-attributes@1.0.1, fabric-blockrenderlayer-v1@1.1.5+ca58154a7d, fabric-lifecycle-events-v1@1.2.1+ca58154a7d, fabric-renderer-registries-v1@2.2.1+ca58154a7d, immersive_portals@0.80, fabric-loot-tables-v1@1.0.2+ca58154a7d, fabric@0.29.4+1.16, fabric-particles-v1@0.2.4+ca58154a7d, fabric-networking-v0@0.3.2+ca58154a7d, imm_ptl_core@0.80, fabric-networking-blockentity-v0@0.2.8+ca58154a7d, minecraft@1.16.5, fabric-screen-handler-api-v1@1.1.1+ca58154a7d, modmenu@1.14.6+build.31, fabric-command-api-v1@1.0.10+ca58154a7d, cloth-basic-math@0.5.1, origins-classes@1.1.1, fabric-tool-attribute-api-v1@1.2.6+ca58154a7d, fabric-renderer-indigo@0.4.4+ca58154a7d, extraorigins@1.16.5-8, fabric-crash-report-info-v1@0.1.3+ca58154a7d, fabric-item-api-v1@1.2.1+ca58154a7d, fabric-events-interaction-v0@0.4.2+ca58154a7d, fabric-entity-events-v1@1.0.3+ca58154a7d, origins@0.5.2, fabric-rendering-v0@1.1.2+ca58154a7d, fabric-key-binding-api-v1@1.0.2+ca58154a7d, fabric-rendering-v1@1.5.1+ca58154a7d, cloth-config2@4.8.2, fabric-resource-loader-v0@0.4.2+ca58154a7d, autoconfig1u@3.2.2, fabric-content-registries-v0@0.2.1+ca58154a7d, fabric-tag-extensions-v0@1.1.1+ca58154a7d, fabric-biome-api-v1@3.1.1+ca58154a7d, cardinal-components-entity@2.7.1, fabric-commands-v0@0.2.2+ca58154a7d, fabric-registry-sync-v0@0.7.4+ca58154a7d, cardinal-components-base@2.7.1, fabric-mining-levels-v0@0.1.3+ca58154a7d, fabric-networking-api-v1@1.0.1+ca58154a7d, fabric-events-lifecycle-v0@0.2.1+ca58154a7d, fabric-item-groups-v0@0.2.3+ca58154a7d, fabric-models-v0@0.2.1+ca58154a7d, fabric-object-builders-v0@0.7.2+ca58154a7d
12:09:14.827
SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/Admin/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.9.2+mixin.0.8.2/sponge-mixin-0.9.2+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT

**Comment by Technici4n** [comment]
Harmless warning, you can ignore it.
