### ISSUE TITLE
Trade helper bugs

### ISSUE THREAD

**Issue by i509VCB** [FabricMC/fabric#1377]
The way fabric api works on trades, the trade reloading logic won't work.

The trade reloading logic is a bit too mod load order dependent. Take this example:

Mod registers via helper
Another mod registers directly to offer map
A third mod registers but via helper
2nd mod's trades drop. 

This means depreciating the existing api regarding reloading and depreciating the registration consumer.

This should just become a [level, profession] = trade.

I originally intended to add that api to allow for data reloadable trades but it wont really work.

**Comment by liach** [comment]
Why not just do it in like two batches, one for addition and one extra round for removal

**Comment by Player3324** [comment]
Fixed via https://github.com/FabricMC/fabric/pull/1430, please reopen if issues persist.
