### ISSUE TITLE
Weird glitch on fabric server

### ISSUE THREAD

**Issue by Swiftform** [FabricMC/fabric#1378]
I don't know if I should ask here or the mods that caused this but Ill ask here.

What happened was that I placed a block with another block and it crashed client-side. I joined back but it said, "There was a problem rendering". The crash report was also from Sodium and a mod named Companion which the block I placed was from. I deleted companion from my server mod folder and it started up. I tried to join back but it said that there were missing tags. I added companion back and this is when the glitch happened. 

![2021-03-13_21 25 19](https://user-images.githubusercontent.com/80437594/111346505-822b4b80-863b-11eb-9695-941efe0eb2b8.png)
![2021-03-13_21 24 56](https://user-images.githubusercontent.com/80437594/111346512-848da580-863b-11eb-9c43-c90460246780.png)

As you can see, my sword turned into a arrow, bucket turned into porkchop.

**Comment by liach** [comment]
Hmm, is this a registry sync issue? I am not sure if registry sync is supposed to keep int ids when some mods are removed.

**Comment by modmuss50** [comment]
It shouldnt re-assign the ID's and should assgin them back again once the mod is added back. It's even more odd that its happening for items as they are sent over the network usually with their full string ident if im not mistaken.

Do you have the same set of mods on the client and server? It shouldnt cause issues but it may be here?

**Comment by Swiftform** [comment]
> It shouldnt re-assign the ID's and should assgin them back again once the mod is added back. It's even more odd that its happening for items as they are sent over the network usually with their full string ident if im not mistaken.
> 
> Do you have the same set of mods on the client and server? It shouldnt cause issues but it may be here?

Yes, I have the same set of mods for the client and the server, it worked before and placing a block broke the server. Also, sorry for late reply.

**Comment by Swiftform** [comment]
bump?
