### ISSUE TITLE
Fabric doesn’t launch(or give a crash log) with immersive portals nor Optifabric/fine installed

### ISSUE THREAD

**Issue by TheHuntHunter** [FabricMC/fabric#1385]
I have looked around everywhere, tried finding dependencies, re-downloaded everything (including fabric api, fabric, every mod) My Minecraft doesn’t have a crash_log for some reason?? I have no idea why any of this is happening or how to fix it.

**Comment by frqnny** [comment]
Uh, have you tried making sure that launching the game multiple times won't fix it? Sometimes I have to do that from the MC launcher, idk why.

**Comment by liach** [comment]
The vanilla launcher would always have a window even if the game doesn't generate a crash report. You can post that the next time.
