### ISSUE TITLE
Invalid plugin channels on minecraft:(un)register causes kicks

### ISSUE THREAD

**Issue by creeper123123321** [FabricMC/fabric#140]
BungeeCord and Waterfall seem to send invalid plugin channels for 1.13+ clients when 'forge-support' is enabled, potentially causing issues with Fabric API
Reproduction:
Install https://github.com/ViaVersion/ViaFabric, enable client-side mode and try to enter a 1.13 server with BungeeCord with 'forge-support' and get kicked 
![Captura de tela de 2019-04-07 16-47-53](https://user-images.githubusercontent.com/7974274/55688938-fbe93380-5954-11e9-8504-7290583a60a0.png)

**Comment by asiekierka** [comment]
That is not a Fabric issue, though. The crash, for all I can see, is because legacy packet channel names are not translated to Mojang's spec. Report to them first, probably trying with Paper's fork first.
