### ISSUE TITLE
is it a good time to bikeshed the name of api-lookup-api yet

### ISSUE THREAD

**Issue by LemmaEOF** [FabricMC/fabric#1400]
During the merge of API Lookup API, I voiced concerns about the module name. The term API already has a well-established definition both inside and out of the Minecraft modding space, which doesn't line up with how it's used here. An API is the *whole* of a project's interface, not a single part of it. You're not looking up an API in ALA, you're looking up just one part of it. I proposed the name "properties" both in discord and on the issue/PR, as it hasn't yet been taken as a name for hooks to objects (with "attributes", "components", and "capabilities" all being other names used by various mods for similar function). The module is still in its infancy, as it only currently supports blocks natively, so I feel like now would be a good time to change things before it becomes too entrenched to be a major issue.

As I said before, this is not a blocking-level problem, but I do still feel it should be addressed to make development more accessible and easier to understand. Repeated use of terms in different contexts proves to be immensely confusing - see [yarn#2090](https://github.com/FabricMC/yarn/pull/2090). If anyone else has ideas for alternate names, please suggest them as well.

**Comment by Technici4n** [comment]
> An API is the whole of a project's interface, not a single part of it.

Not really, when I talk about the BuildCraft Wrench API it's quite clear that I am talking only about [the wrench part](https://github.com/BuildCraft/BuildCraftAPI/blob/8.0.x-1.12.2/api/buildcraft/api/tools/IToolWrench.java) of the [BC public API (which also includes MJ and whatnot)](https://github.com/BuildCraft/BuildCraftAPI/tree/8.0.x-1.12.2/api/buildcraft/api). (edit: MCP warning)

Fundamentally, this is the module enabling "Fluid API", "Wrench API", "Transfer API", "Energy API", etc... So it makes sense to use the name API directly imo, especially given that the README and the package-info define it:
> What we call an API is any object that can be offered or queried, possibly by different mods, to be used in an agreed-upon manner.

And we are still lacking a decent fluid/item API, so I think reviewing #1352 and #1356 is more important than discussing this.

**Comment by liach** [comment]
Imo this should be a "lookup api". What's looked up can be considered apis, but there is nothing preventing you from using it for your impl details.

**Comment by Technici4n** [comment]
Whatever... I can't be annoyed to deprecate and duplicate the API.

This discussion is not very important compared to the actual `ItemApiLookup` and transfer API.
I'd rather have new APIs than debate the naming of existing ones.
