### ISSUE TITLE
Inventory Deletes itself

### ISSUE THREAD

**Issue by ghost** [FabricMC/fabric#1410]
Created a Custom Container ([FuelChest](https://github.com/DanielGolan-mc/TheBoson/blob/master/src/main/java/net/danielgolan/boson/blocks/containers/FuelChest.java)) that when I'm exiting the world and coming back, cannot be opened, but if I brake the block, it's content dropped.

**Comment by OroArmor** [comment]
1. Not an api thing
2. Make sure you save the contents to the tag in the read/write nbt methods to save the inventory

**Comment by ghost** [comment]
I thought it's API because nobody could help me. [See? I got the read / write!](https://github.com/DanielGolan-mc/TheBoson/blob/master/src/main/java/net/danielgolan/boson/blocks/containers/FuelChest.java#L112) the problem is I can't open!

**Comment by OroArmor** [comment]
Oh it can't be opened :concern: use break points to see it trying to open

**Comment by ghost** [comment]
The `onOpen()` method not even being called

**Comment by liach** [comment]
You should register your screen handler in your mod main entrypoint. Call this to register your screen handler https://github.com/FabricMC/fabric/blob/351679a7decdd3044d778e74001de67463bee205/fabric-screen-handler-api-v1/src/main/java/net/fabricmc/fabric/api/screenhandler/v1/ScreenHandlerRegistry.java#L82

**Comment by Technici4n** [comment]
Marking this as closed, please ask on the `#mod-dev` channels on our official Discord server if you have further questions.
