### ISSUE TITLE
Portal Gun crash on Aternos server

### ISSUE THREAD

**Issue by AccurateFranky** [FabricMC/fabric#1411]
I can't use the portal gun mod on my Aternos server.
How can I use it?

Here is the part of the log where it states that,

Failed to start the minecraft server
--
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'portalgun'!

Here is the full error

Failed to start the minecraft server
--
5 | java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'portalgun'!
6 | at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53) ~[fabric.jar:?]
7 | at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[fabric.jar:?]
8 | at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:32) ~[fabric.jar:?]
9 | at net.minecraft.server.Main.main(Main.java:92) [intermediary-server.jar:?]
10 | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
11 | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
12 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
13 | at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
14 | at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric.jar:?]
15 | at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric.jar:?]
16 | at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric.jar:?]
17 | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
18 | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
19 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
20 | at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
21 | at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62) [fabric.jar:?]
22 | at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106) [fabric.jar:?]
23 | at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50) [fabric.jar:?]
24 | Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_310
25 | at tk.meowmc.portalgun.items.PortalGunItem.<clinit>(PortalGunItem.java:52) ~[portalgun-1.1.5-mc1.16.5-fabric.jar:?]
26 | at tk.meowmc.portalgun.Portalgun.<clinit>(Portalgun.java:21) ~[portalgun-1.1.5-mc1.16.5-fabric.jar:?]
27 | at java.lang.Class.forName0(Native Method) ~[?:1.8.0_222]
28 | at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_222]
29 | at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45) ~[fabric.jar:?]
30 | at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:112) ~[fabric.jar:?]
31 | at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:99) ~[fabric.jar:?]
32 | at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:184) ~[fabric.jar:?]
33 | at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37) ~[fabric.jar:?]
34 | at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric.jar:?]
35 | ... 17 more
36 | Caused by: java.lang.ClassNotFoundException: net.minecraft.class_310
37 | at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_222]
38 | at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_222]
39 | at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_222]
40 | at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_222]
41 | at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:56) ~[fabric.jar:?]
42 | at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_222]
43 | at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168) ~[fabric.jar:?]
44 | at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_222]
45 | at tk.meowmc.portalgun.items.PortalGunItem.<clinit>(PortalGunItem.java:52) ~[portalgun-1.1.5-mc1.16.5-fabric.jar:?]
46 | at tk.meowmc.portalgun.Portalgun.<clinit>(Portalgun.java:21) ~[portalgun-1.1.5-mc1.16.5-fabric.jar:?]
47 | at java.lang.Class.forName0(Native Method) ~[?:1.8.0_222]
48 | at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_222]
49 | at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45) ~[fabric.jar:?]
50 | at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:112) ~[fabric.jar:?]
51 | at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:99) ~[fabric.jar:?]
52 | at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:184) ~[fabric.jar:?]
53 | at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37) ~[fabric.jar:?]
54 | at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric.jar:?]

**Comment by ghost** [comment]
This seems to be an error with the portal gun mod as they are accessing client only code when the mod is running on a dedicated server, you should report the issue to the mod author instead.
