### ISSUE TITLE
Minecraft wont launch, "error loading companion plugin class"  (Error code 0 from MC launcher)

### ISSUE THREAD

**Issue by Woopagadon17** [FabricMC/fabric#1412]
Not sure what happened here!

Log:  https://gist.github.com/Woopagadon17/c52b22c3698d5b4de9fa0ef9f0625504#file-latest-log

My first time asking for help with a log, I just need to be pointed in the right direction if the error is not to do with Fabric API.

Thanks in advance!

**Comment by liach** [comment]
Hmm, this seems like some fabric asm classloading issue, but I am not a pro on how it works.

**Comment by Woopagadon17** [comment]
everything seems to work now, just updated my mods!
