### ISSUE TITLE
Could not Find Required Mod: (modname) Requires {fabric @ [*]}

### ISSUE THREAD

**Issue by ghost** [FabricMC/fabric#1419]
what
i compiled raion 1.16 and installed fabric 1.16.5 and now this happens
why

**Comment by Technici4n** [comment]
Make sure you also download fabric API from https://www.curseforge.com/minecraft/mc-mods/fabric-api

**Comment by ghost** [comment]
Already did

**Comment by Technici4n** [comment]
Did you put it in your `mods` folder?

**Comment by Technici4n** [comment]
If that doesn't work, please ask in the `#player-support` channel on our discord server, you will get more interactive help.
