### ISSUE TITLE
Commands don't work on dedicated servers

### ISSUE THREAD

**Issue by Runemoro** [FabricMC/fabric#142]
https://github.com/FabricMC/fabric/blob/master/src/main/java/net/fabricmc/fabric/mixin/commands/MixinServerCommandManager.java#L40

They're only registered if `!dedicated`, so only on integrated servers.

**Comment by asiekierka** [comment]
Cannot reproduce, and that's not the right PR anyway

**Comment by Prospector** [comment]
Is allegedly fixed and unreproducable
