### ISSUE TITLE
Building Fabric API

### ISSUE THREAD

**Issue by ghost** [FabricMC/fabric#1420]
I cloned the repository and did `./gradlew build`. Which folder is the actual API in? Would it be this: `fabric-api-0.32.9+local-1.17.jar` ?

**Comment by OroArmor** [comment]
yes, but why are you building from source?

**Comment by ghost** [comment]
I have a script that builds all the mods I use on my server.
Obviously, I need the Fabric API as well.

**Comment by ghost** [comment]
It is just the easiest way to update everything.

**Comment by OroArmor** [comment]
Ah ok. then yeah, the file is in `build/libs`

**Comment by ghost** [comment]
Thank you!
