### ISSUE TITLE
Fabric causes crash on world gen. 

### ISSUE THREAD

**Issue by toErIpNid** [FabricMC/fabric#1424]
crash log: 
[crash-2021-04-18_17.36.25-server.txt](https://github.com/FabricMC/fabric/files/6332356/crash-2021-04-18_17.36.25-server.txt)

fabric api version: 0.33.0
fabric version: 0.11.3
mc version 1.16.5

**Comment by liach** [comment]
Hmm, something is causing an infinite loop here

**Comment by modmuss50** [comment]
Going to close this as there is little info, and other mods were present. Feel free to re-open with more info 👍
