### ISSUE TITLE
TradeHelpers will duplicate trade entries like crazy

### ISSUE THREAD

**Issue by TelepathicGrunt** [FabricMC/fabric#1427]
Not only was TradeHelpers[ nuking other mod's trades a thing](https://github.com/FabricMC/fabric/issues/1377), it seems the API is also broken as well. Using the latest Fabric API, I noticed that villagers would show multiple entries for the same trade even though I only added it once.
![image](https://user-images.githubusercontent.com/40846040/115612693-8a6d4b00-a2b9-11eb-8de6-8d42e0530dbe.png)

In this case with a custom villager, calling `TradeOfferHelper.registerVillagerOffers` multiple times to add trades to each trade level will duplicate all the other trade levels each time. Specifically, the issue is caused by [refreshVillagerOffers](https://github.com/FabricMC/fabric/blob/12865e786ce2102d344304a679b70084be84d166/fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/impl/object/builder/TradeOfferInternals.java#L80-L102) being called every time `TradeOfferHelper.registerVillagerOffers` is called by a mod. 

Here is a more detailed look at what is going on using a debugger. I am calling `TradeOfferHelper.registerVillagerOffers` 5 times in order to add trades to each trade level. Show here is the entries in `TradeOfferInternals.VILLAGER_TRADE_FACTORIES` at the start of refreshVillagerOffers.

After the 1st TradeOfferHelper.registerVillagerOffers call:
![image](https://user-images.githubusercontent.com/40846040/115613324-43cc2080-a2ba-11eb-9008-957385e9749a.png)

After the 2nd TradeOfferHelper.registerVillagerOffers call:
![image](https://user-images.githubusercontent.com/40846040/115613360-4cbcf200-a2ba-11eb-80b1-ea26ac81d5b8.png)

After the 3rd TradeOfferHelper.registerVillagerOffers call:
![image](https://user-images.githubusercontent.com/40846040/115613383-5181a600-a2ba-11eb-84d8-27ba72ee670a.png)

Notice how on the second call, level 1 trades were duplicated. And on the third call, level 1 and 2 trades were duplicated again. And it keeps growing every time it is called making the trade map bloated like crazy. Someone suggested it is because it doesn't do a deep copy of the original vanilla maps it is suppose to replace. Instead it is feeding itself over and over.
https://github.com/FabricMC/fabric/blob/12865e786ce2102d344304a679b70084be84d166/fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/mixin/object/builder/TradeOffersMixin.java#L42

However, a better solution for everyone is to trash the whole system and have the API just add/remove trades directly from vanilla's trade maps instead with none of these caching and reloadable system. It would both solve this issue and prevent the API from nuking other mod's trades when those mods do not use the API.

**Comment by Technici4n** [comment]
So it's indeed creating a new `Map<Map<>>` every time it refreshes the trade offers, so the outer map is copied but the inner maps are shared, leading to duplicate trade offers.

I am willing to fix this myself, most likely by just writing to the map directly like TelepathicGrunt suggested, but I have a question first (liach maybe?): What is `refreshOffers`? There is really no point imo, unless it re-runs the `Consumer<List<TradeOffers.Factory>>`, but that would be a breaking change I believe. I think we can remove its body and deprecate it without notice given how broken the API is!

https://github.com/FabricMC/fabric/blob/bc7a746fabe505dab1bd482e86a9c4a3b36c9605/fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/trade/TradeOfferHelper.java#L64

**Comment by liach** [comment]
Imo a way to fix this would be keeping the trade factories from our callback in a list than keeping original ones in a separate list. And Imo the factory creation should be lazy at best or reload performance would be horrible.

**Comment by Technici4n** [comment]
We should just write to the map directly imo.

**Comment by Technici4n** [comment]
Data-driven trades could then be removed from the map directly if necessary, for now it will require a mixin, and we can add an API for that later on.

**Comment by Player3324** [comment]
Fixed via https://github.com/FabricMC/fabric/pull/1430, please reopen if issues persist.
