### ISSUE TITLE
Fabric Rendering API v0 is seemingly left behind

### ISSUE THREAD

**Issue by actuallyasmartname** [FabricMC/fabric#1434]
The v0 version of the Rendering API is left behind, with v1 existing. Probably forgotten to be deleted?

**Comment by Player3324** [comment]
Introducing a new module version usually involves changing the previous version into an adapter to the new API. This way mods keep working and can update at their own pace.

Considering how little effort it is to keep those adapters around, the benefits for removal are rather unclear and keep decreasing as we introduce new techniques to deal with remaining fallout.
