### ISSUE TITLE
1.16.1 crash

### ISSUE THREAD

**Issue by Civil35** [FabricMC/fabric#1437]
whenever i have fabric api installed into fabric minecraft 1.16.1 crashes

**Comment by ghost** [comment]
Some major changes where made in minecraft 1.16.2, try this version of fabric-api: https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3049057

**Comment by Civil35** [comment]
that’s the one im trying. should i use 1.16.2?

**Comment by ghost** [comment]
Could you share the crash log, also it would be best to update as a lot of mods are targeting 1.16.2+
