### ISSUE TITLE
The [1.16.5] Fabric API 0.34.0 doesnt let me break blocks

### ISSUE THREAD

**Issue by DKLYNTLY** [FabricMC/fabric#1443]
[1.16.5] Fabric API 0.34.0 has cardinal components which doesn't let me break blocks 

modlist:

better-end-0.9.5-pre.jar
betterbiomeblend-1.16.4-1.1.4-forge.jar
fabric-api-0.33.1+1.16.jar
RebornCore-1.16-4.7.2+build.132.jar
seasons-1.1.1-BETA.jar
TechReborn-1.16-3.8.2+build.220.jar
adapaxels-1.0.7+1.16.5.jar
antighost-1.16.5-fabric0.30.0-1.1.3.jar
besmirchment-1.16.5-3.jar
megane-3.1.6+1.16.5.jar
soulsegg-2.0.0+1.16.5.jar
undestroying-fabric-1.16.5-1.1.1.jar
wthit-2.8.1-fabric.jar
[Fabric] Wildfire Female Gender Mod-2.4.1.jar
Adorn-1.13.0+1.16.5.jar
architectury-1.12.148-fabric.jar
Autofish-0.9.2-fabric-mc1.16.4.jar
BasicNetherOres-1.16.5-5.5.0-Fabric.jar
BetterCaves-Fabric-1.16.5-1.1.jar
BetterMineshafts-Fabric-1.16.4-1.0.1.jar
bewitchment-1.16.5-11.jar
biome-makeover-1.16.5-1.3.8.jar
BowInfinityFix-1.16.x-fabric-rv9.jar
byg-1.1.7.jar
cloth-api-1.4.9.jar
crawl-0.8.3.jar
cullleaves-2.1.0.jar
curiousshulkerboxes-fabric-1.1.1-1.16.5.jar
dark-enchanting-0.1.1+mc.1.16.5.jar
deepmoblearning-refabricated-0.3.3-beta1.jar
EntityCulling-Fabric-1.2.2.jar
FallingTree-1.16.5-2.11.3.jar
ferritecore-2.0.4-fabric.jar
geckolib-fabric-1.16.5-3.0.33.jar
haema-1.7.0.jar
HWGMod-1.16.5-1.0.11.jar
illuminations-1.5.jar
Impersonate-2.2.0.jar
indium-1.0.0-modified.jar
indrev-1.9.7-BETA.jar
kibe-1.16.5-1.6.7-BETA.jar
lithium-fabric-mc1.16.5-0.6.4.jar
Modern-Industrialization-0.3.17.jar
mythicmetals-0.9.9.jar
phosphor-fabric-mc1.16.3-0.7.2+build.12.jar
repurposed_structures-1.16.5-1.10.5-fabric.jar
rer-2.1.3.jar
RoughlyEnoughItems-5.11.218.jar
seamless-loading-screen-1.3.4+1.16.2.jar
secretrooms-0.9.3+1.16.5.jar
sodium-extra-0.2.6.jar
stoneholm-1.2.0.jar
TaxFreeLevels-1.1.jar
terrestria-2.2.0.jar
traverse-3.3.2.jar
worldedit-mod-7.2.5-dist.jar
wraith-alloy_forgery-1.1.0.jar
Xaeros_Minimap_21.7.1_Fabric_1.16.5.jar
XaerosWorldMap_1.13.4_Fabric_1.16.5.jar
YungsApi-1.16.5-Fabric-2.jar
[1.16.4]+MoreTooltips-1.0.1.jar
adventurez-1.2.2.jar
amecs-1.3.4+mc.1.16.3.jar
Angel-Ring-Fabric-1.16.4-1.0.0.jar
artifacts-3.2.0+fabric.jar
astromine-1.11.5+fabric-1.16.5.jar
autobackup-1.4.4.jar
backslot-1.1.9.jar
battletowers-3.3.4-1.16.4.jar
bedspreads-fabric-1.3.1-1.16.4.jar
better-local-server-1.1.1.jar
better-nether-5.0.7.jar
betterthanmending-1.3.0.jar
blame-1.16.4-2.4.1.jar
blockus-2.1.1+1.16.5.jar
BOMD-1.0.2-1.16.5.jar
carrier-1.7.5.jar
castle_dungeons-2.2-1.16.5-fabric.jar
cavebiomes-0.6.2.jar
cherishedworlds-fabric-1.3.0-1.16.4.jar
chestcavity-2.10.2.jar
cinderscapes-1.3.3.jar
cleancut-mc1.16-2.1-fabric.jar
cloth-config-4.11.19-fabric.jar
CompactStatusEffects-1.3.0.jar
conjuring-0.1.7.jar
curios-fabric-0.0.13-1.16.5.jar
curiouselytra-fabric-1.1.1-1.16.5.jar
DamageTilt-1.16-fabric-0.1.2.jar
deep-dungeons-1.0.0-1.16.5.jar
diggusmaximus-1.4.2-1.16.3.jar
DisableCustomWorldsAdvice-1.2.jar
DungeonsModLite-1.16.5-1.0.0.jar
dynamic-fps-2.0.1.jar
DynamicSoundFilters-1.2.0+1.16.5.jar
emotecraft-for-MC1.16.5-2.0.1-fabric.jar
expandedstorage-5.6.33+1.16.5.jar
fabric-language-kotlin-1.5.0+kotlin.1.4.31.jar
fastfurnace-2.4.jar
fatxporbs-0.0.9+1.16.4.jar
gate-of-babylon-1.4.2-1.16.5.jar
gg_enchantments-1.1.1.jar
give-me-hats-1.16-1.5.1.jar
glassential-fabric-1.16.4-1.1.5.jar
Gobber2-Fabric_1.16.5-2.3.71.jar
golemancy-1.0.1.jar
HealthOverlay-1.16.4-3.6.14.jar
Heartbond-1.16-1.0.0.jar
inmis-2.2.1-1.16.5.jar
InventorySorter-1.7.9-1.16.jar
lambdynamiclights-fabric-1.3.4+1.16.jar
lapisreserve-1.0.6.jar
libcd-3.0.3+1.16.3.jar
lightstones-1.3.0.jar
literally_chunk_loader
magic-lanterns-1.4.5.jar
mermod-fabric-1.3.jar
mixintrace-1.0.0.jar
MobFarmHelpers-1.16.5-1.4.2-fabric.jar
mobz-2.4.6.jar
modifiers-0.1.1-fabric.jar
modmenu-1.16.9.jar
MoEnchantments-1.13.8.jar
mostructures-1.1.1+mc.1.16.5.jar
mousewheelie-1.6.4+mc1.16.4.jar
netherite-plus-mod-1.4.3-1.16.5-fabric.jar
noenchantcap-4.1.0.jar
notenoughbreeding-1.16.5-fabric.jar
notenoughcrashes-3.2.0-fabric.jar
OfflineSkins-1.16.5-v1-fabric.jar
okzoomer-4.0.1+1.16.2.jar
opchanter-1.16.5-fabric.jar
Origins-1.16.5-0.7.0.jar
Origins-Classes-1.16.5-1.1.1.jar
Patchouli-1.16.4-50-FABRIC.jar
Pehkui-2.0.0+21w14a.jar
PerspectiveModRedux-0.0.5.jar
pling-1.3.0.jar
polymorph-fabric-0.0.10-1.16.5.jar
quickshulker-1.1.14-1.16.jar
rare-ice-0.2.2.jar
ratsmischief-1.1.jar
reroll-1.2.1-1.16.5.jar
respawnablepets-1.16.5-2.jar
RingsOfAscension-1.16.4-1.1.1.jar
SakuraRosea-1.6.0-MC1.16.3-fabric.jar
sgod-1.0.0.jar
Silky-Spawners-2.1.0+build.2-1.16.jar
SimpleBackpack_Fabric_1.16.5-1.0.38.jar
simplesoundmuffler-1.16.2_0.2.1.jar
simpleteleporters-2.2.1.jar
sizeshiftingpotions-1.1.0.jar
slotlock-1.0.3-BETA.jar
smoothboot-fabric-1.16.5-1.6.0.jar
sodium-fabric-mc1.16.4-0.1.1-Next_Comp500_3-14-2021.jar
somnus-fabric-0.0.11-1.16.5.jar
spark-fabric.jar
spawnlanterns-1.0.1.jar
spellbound-1.2.1.jar
staffofbuilding-1.2.6-1.16.5.jar
trinkets-2.6.7.jar
TTLG-1.1.1.jar
vanguard-uninstaller.jar
vanilla-hammers-3.0.3-1.16.5.jar
wolves-with-armor-1.5.4-1.16.5.jar
world_blender-1.16.5-2.1.5.jar
wraith-waystones-1.1.1.1.jar
x-enchant-1.0.3.jar

**Comment by Technici4n** [comment]
Can you break blocks with fabric API 0.33.1?

**Comment by DKLYNTLY** [comment]
yes

**Comment by Technici4n** [comment]
Hmmm ok, what makes you think this is related to cardinal components?

**Comment by DKLYNTLY** [comment]
because i took carnidal componets out and I could break blocks again with fabric API 0.33.1

**Comment by DKLYNTLY** [comment]
when i updated to the newst api cardinal components appeared

**Comment by Technici4n** [comment]
hmmm that sounds bad, is the modpack available for download?

**Comment by DKLYNTLY** [comment]
yes

**Comment by DKLYNTLY** [comment]
i will send it on discord text me M¥s†içål®uß¥™#1907

**Comment by Technici4n** [comment]
The culprit is Mo Enchantements, and in particular this event preventing (creative? that's only what I tested) players from breaking blocks: https://gitlab.com/biom4st3r/moenchantments/-/blob/default/src/main/java/com/biom4st3r/moenchantments/api/events/OnBlockBreakAttemptEvent.java#L45.

I assume the factory is broken as it stands, but fabric < 0.34.0 would just bypass it when only 1 listener was registered (which is the case in the modpack you sent me).
Old behavior was:
```java
    Event<OnBlockBreakAttemptEvent> EVENT = EventFactoryImpl.createArrayBacked(OnBlockBreakAttemptEvent.class, (listeners)->
    (manager,pos,reason)->
    {
        if (listeners.length == 1) return listeners[0].onBreak(manager, pos, reason);

        // custom logic never called for exactly 1 listener
        for(OnBlockBreakAttemptEvent callback : listeners)
        {
            ActionResult result = callback.onBreak(manager, pos, reason);
            if(!result.isAccepted() && reason.isSuccessful()) return ActionResult.FAIL;
            else if(result.isAccepted() && reason.isFailure()) return ActionResult.SUCCESS;
        }
        return ActionResult.PASS;
    });
```
but the new behavior is:
```java
    Event<OnBlockBreakAttemptEvent> EVENT = EventFactoryImpl.createArrayBacked(OnBlockBreakAttemptEvent.class, (listeners)->
    (manager,pos,reason)->
    {
        // custom logic always called
        for(OnBlockBreakAttemptEvent callback : listeners)
        {
            ActionResult result = callback.onBreak(manager, pos, reason);
            if(!result.isAccepted() && reason.isSuccessful()) return ActionResult.FAIL;
            else if(result.isAccepted() && reason.isFailure()) return ActionResult.SUCCESS;
        }
        return ActionResult.PASS;
    });
```

You will have to remove Mo Enchantements for now, and ask @Biom4st3r to fix it.
