### ISSUE TITLE
Problem with multiple mods

### ISSUE THREAD

**Issue by Emeraldnickel** [FabricMC/fabric#1450]
Hello! I'm trying to make a modpack for fabric to run on a server. I've been getting crash reports similar to the attached report a lot, and I have no idea how to fix them! Does anyone here know how to fix them??
[crash-2021-05-11_18.01.40-client.txt](https://github.com/FabricMC/fabric/files/6457741/crash-2021-05-11_18.01.40-client.txt)

**Comment by Technici4n** [comment]
It seems custom portals forgot to include `cardinal-components-world`. You can work around this by installing Cardinal Components API yourself: https://www.curseforge.com/minecraft/mc-mods/cardinal-components.
