### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by speege** [FabricMC/fabric#1454]
i tried installing the fabric api but when i double clicked on the java file nothing happens.

**Comment by thecatcore** [comment]
https://fabricmc.net/use/

**Comment by Blobanium** [comment]
Mods are not JAR Executables. However they can be loaded through the fabric loader. Here's some links that may help you with that.

https://fabricmc.net/wiki/install (for installing the fabric loader if you don't have it yet)
https://fabricmc.net/wiki/tutorial:adding_mods (for adding fabric mods)

Also if you need anything else i would personally check the [fabric wiki](https://fabricmc.net/wiki/start) first before asking anyone for any additional help.
