### ISSUE TITLE
Game crashes with exit code 0. No crash log for some reason.

### ISSUE THREAD

**Issue by TheFurru** [FabricMC/fabric#1455]
So, i am trying to play the bewitchment mod, and while installing its dependencies, when i placed cloth config , and loaded it up again to see the next dependency, it crashed with exit code 0.

Mod list, so far.

Bewitchment 1.16.5-12
Cloth-Config 4.10.13
Fabric API 0.34.2
Impersonate 2.2.1
Patchouli-1.16.4-50 (closest to 1.16.5 that im playing on.)
Pehkui 2.1.0
Somnus0.0.11
trinkets-2.6.7
All of these are dependencies. anyone know whats going on?

**Comment by TheFurru** [comment]
This crash was a particular minecraft crash, no fabric window telling me launch failed or anything.

**Comment by Technici4n** [comment]
Please check the `crash-reports` folder. Can you find something there?

**Comment by TheFurru** [comment]
i have already fixed this. i forgot to close it, one of the mods needed a redownload.
