### ISSUE TITLE
error initializing game

### ISSUE THREAD

**Issue by DKLYNTLY** [FabricMC/fabric#1458]
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 5/17/21 8:54 AM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.5)
	at net.minecraft.client.MinecraftClient.handler$zjo000$onOpenScreen(MinecraftClient:6876)
	at net.minecraft.client.MinecraftClient.openScreen(MinecraftClient)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:579)
	at net.minecraft.client.main.Main.main(Main:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Mac OS X (x86_64) version 10.16
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2463977672 bytes (2349 MB) / 3892314112 bytes (3712 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 4
	JVM Flags: 8 total; -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Mixins in Stacktrace: 
		net.minecraft.class_310:
			fudge.notenoughcrashes.mixins.client.CatchInitMInecraftClientMixin (notenoughcrashes.fabric.mixins.json)
			paulevs.betternether.mixin.client.MinecraftClientMixin (betternether.mixins.client.json)
			net.fabricmc.fabric.mixin.screen.MinecraftClientMixin (fabric-screen-api-v1.mixins.json)
			io.github.joaoh1.okzoomer.client.mixin.MinecraftClientMixin (okzoomer.mixins.json)
			ru.betterend.mixin.client.MinecraftClientMixin (betterend.mixins.client.json)
			net.fabricmc.fabric.mixin.event.lifecycle.client.MinecraftClientMixin (fabric-lifecycle-events-v1.mixins.json)
			top.theillusivec4.polymorph.loader.mixin.core.MinecraftClientAccessor (polymorph.mixins.json)
			me.lambdaurora.lambdynlights.mixin.MinecraftClientMixin (lambdynlights.mixins.json)
			me.steven.carrier.mixin.MixinMinecraftClient (carrier.mixins.json)
			com.minenash.seamless_loading_screen.mixin.MinecraftClientMixin (seamless_loading_screen.mixins.json)
			vazkii.patchouli.mixin.client.MixinMinecraftClient (patchouli.mixins.json)
			draylar.omegaconfig.mixin.ClientMixin (omega-config.mixins.json)
			me.shedaniel.cloth.mixin.client.events.MixinMinecraftClient (cloth-client-events-v0.mixins.json)
			me.shedaniel.architectury.mixin.fabric.client.MixinMinecraft (architectury.mixins.json)
			de.siphalor.mousewheelie.client.mixin.MixinMinecraftClient (mousewheelie.mixins.json)
			net.fabricmc.fabric.mixin.registry.sync.client.MixinMinecraftClient (fabric-registry-sync-v0.mixins.json)
			me.flashyreese.mods.sodiumextra.mixin.features.gui.MinecraftClientAccessor (sodium-extra.mixins.json)
			dynamicfps.mixin.MinecraftClientMixin (dynamicfps.mixins.json)
			xaero.common.mixin.MixinMinecraftClient (xaerominimap.mixins.json)
			net.fabricmc.fabric.mixin.command.client.MinecraftClientMixin (fabric-command-api-v1.mixins.json)
			net.fabricmc.fabric.mixin.event.interaction.MixinMinecraftClient (fabric-events-interaction-v0.mixins.json)
			xyz.rongmario.cleancut.MixinMinecraftClient (mixins.cleancut.json)
			xaero.map.mixin.MixinMinecraftClient (xaeroworldmap.mixins.json)
			com.sefodopo.autobackup.mixins.PauseMixin (autobackup.mixins.json)
			net.fabricmc.fabric.mixin.networking.accessor.MinecraftClientAccessor (fabric-networking-api-v1.mixins.json)
			com.swordglowsblue.artifice.mixin.MixinMinecraftClient (artifice.mixins.json)
			fudge.notenoughcrashes.mixins.client.MixinMinecraftClient (notenoughcrashes.mixins.json)
			malte0811.ferritecore.mixin.fabric.MinecraftMixin (ferritecore.fabric.mixin.json)
			com.rdvdev2.disablecustomworldsadvice.mixin.MixinMinecraftClient (disable_custom_worlds_advice.mixins.json)
			io.github.lucaargolo.slotlock.mixin.MinecraftClientMixin (slotlock.mixins.json)
			ml.rederpz.betterlocalserver.mixin.impl.MinecraftClientMixin (better-local-server.mixins.json)
			me.jellysquid.mods.sodium.mixin.features.options.MixinMinecraftClient (sodium.mixins.json)
			de.siphalor.nbtcrafting.mixin.client.MixinMinecraftClient (nbtcrafting.mixins.json)
			ladysnake.satin.mixin.client.event.MinecraftClientMixin (mixins.satin.client.json)
			me.lambdaurora.spruceui.mixin.MinecraftClientMixin (spruceui.mixins.json)
		net.minecraft.client.main.Main:
			io.github.ultimateboomer.smoothboot.mixin.client.MainMixin (smoothboot.mixins.json)
			fudge.notenoughcrashes.mixins.client.MixinMain (notenoughcrashes.fabric.mixins.json)
	Suspected Mods: Fabric Loader (fabricloader)
	Fabric Mods: 
		adapaxels: AdaPaxels 1.0.7+1.16.5
		adorn: Adorn 1.13.0+1.16.5
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		adventurez: AdventureZ 1.2.2
		alloy_forgery: Alloy Forgery 1.2.0
		amecs: Amecs 1.3.4+mc.1.16.3
		amecsapi: Amecs API 1.1.4+mc1.16.5
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		antighost: AntiGhost 1.16.5-fabric0.30.0-1.1.3
		architectury: Architectury 1.14.156
		artifacts: Artifacts 3.2.1+fabric
		artifice: Artifice 0.14.6+1.16.5
		astromine: Astromine 1.11.5+fabric-1.16.5
		astromine-core: Astromine: Core 1.11.5+fabric-1.16.5
		astromine-discoveries: Astromine: Discoveries 1.11.5+fabric-1.16.5
		astromine-foundations: Astromine: Foundations 1.11.5+fabric-1.16.5
		astromine-technologies: Astromine: Technologies 1.11.5+fabric-1.16.5
		astromine-transportations: Astromine: Transportations 1.11.5+fabric-1.16.5
		autobackup: Auto Backup Mod 1.4.4
		autoconfig1u: Auto Config v1 Updated 3.3.1
		autofish: Autofish 0.9.2
		backslot: BackSlot 1.1.11
		battletowers: Battle Towers 3.3.4-1.16.4
		bedspreads: Bedspreads 1.3.1-1.16.4
		bendy-lib: Bendy api 1.1.0
		besmirchment: Besmirchment 1.16.5-6
		better-local-server: Better Local Server 1.1.1
		bettercaves: YUNG's Better Caves 1.16.5-1.2
		betterend: Better End 0.9.6-pre
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0.1
		betternether: Better Nether 5.0.7
		betterthanmending: BetterThanMending 1.3.0
		bewitchment: Bewitchment 1.16.5-12
		biomemakeover: Biome Makeover 1.16.5-1.3.8
		blade: Blade 2.0.0
		blame: Blame 1.16.5-3.0.1-fabric
		blockus: Blockus 2.1.4+1.16.5
		blue_endless_jankson: jankson 1.2.0
		bno: Basic Nether Ores 1.16.5-5.5.0-Fabric
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.0.2-1.16.5
		bowinfinityfix: Bow Infinity Fix rv9
		byg: BYG 1.1.8
		caelus: Caelus API 0.0.15-1.16.4
		cardinal-components: Cardinal Components API 2.6.0
		cardinal-components-base: Cardinal Components API (base) 2.8.2
		cardinal-components-block: Cardinal Components API (blocks) 2.7.10
		cardinal-components-chunk: Cardinal Components API (chunks) 2.7.10
		cardinal-components-entity: Cardinal Components API (entities) 2.8.2
		cardinal-components-item: Cardinal Components API (items) 2.8.2
		cardinal-components-level: Cardinal Components API (world saves) 2.7.10
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.6.0
		cardinal-components-util: Cardinal Components API (utilities) 2.7.10
		cardinal-components-world: Cardinal Components API (worlds) 2.7.10
		carrier: Carrier 1.7.6
		castle_dungeons: Castle Dungeons 2.2
		cavebiomes: Cave Biomes 0.6.2
		chainmail: Chainmail 0.5.0
		cherishedworlds: Cherished Worlds 1.3.0-1.16.4
		chestcavity: Chest Cavity 2.11.0.1
		cinderscapes: Cinderscapes 1.3.3
		cleancut: CleanCut mc1.16-2.1-fabric
		cloth-api: Cloth API 1.4.9
		cloth-armor-api-v1: Cloth Armor API v1 1.4.9
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-common-events-v1: Cloth Common Events v1 1.4.9
		cloth-config2: Cloth Config v4 4.11.26
		cloth-datagen-api-v1: Cloth Datagen v1 1.4.9
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.5.47
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.9
		cloth-scissors-api-v1: Cloth Scissors API v1 1.4.9
		cloth-utils-v1: Cloth Utils v1 1.4.9
		com_github_nathanpb_safer: Safer 1.1.0
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		compactstatuseffects: Compact Status Effects 1.3.0
		conjuring: Conjuring 0.1.7
		cotton-client-commands: Cotton Client Commands 1.0.1+1.16-rc1
		crawl: Crawl 0.8.4
		crowdin-translate: CrowdinTranslate 1.2
		cullleaves: Cull Leaves 2.1.0
		curios: Curios API 0.0.13-1.16.5
		curiouselytra: Curious Elytra 1.1.1-1.16.5
		curiousshulkerboxes: Curious Shulker Boxes 1.1.1-1.16.5
		customportalapi: customportalapi 0.0.1-beta18-1.16
		damagetilt: Damage Tilt 1.16-fabric-0.1.2
		dark-enchanting: Dark Enchanting 0.1.1+mc.1.16.5
		deep-dungeons: Deep Dungeons 1.0.0-1.16.5
		diggusmaximus: Diggus Maximus 1.4.2-1.16.3
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.2
		dml-refabricated: Deep Mob Learning: Refabricated 0.3.3-beta1
		doomangelring: Doom Angel Ring 1.0.0
		dungeonsmod: Dungeons Mod Lite 1.16.5-1.0.5
		dynamicfps: Dynamic FPS 2.0.2
		dynamicsoundfilters: Dynamic Sound Filters 1.2.0+1.16.5
		emotecraft: Emotecraft 2.0.4
		enchant_giver: Enchant Giver 1.0.3
		entityculling: EntityCulling-Fabric 1.2.2
		expandedstorage: ExpandedStorage 5.6.33
		fabric: Fabric API 0.34.2+1.16
		fabric-api-base: Fabric API Base 0.3.0+c88702897d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+c88702897d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.6.0+kotlin.1.5.0
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.3.0+bc7a746f7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.3+e3c9d0627d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+c88702897d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.2+2868a2287d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+2868a2287d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
		fabricdrawer: Fabric Drawer 3.2.1-20w19a
		fabricloader: Fabric Loader 0.11.3
		fallflyinglib: FallFlyingLib 1.1.0
		fallingtree: FallingTree 2.11.3
		fastfurnace: FastFurnace 2.4
		fasttransferlib: Fast Transfer Lib 0.3.1
		fatxporbs: Fat Experience Orbs 0.0.9
		fermion: Fermion 2.1.191
		fermion-modkeys: Fermion Modifier Keys 1.10.218
		ferritecore: FerriteCore 2.0.4
		fiber: fiber 0.23.0-2
		gateofbabylon: Gate Of Babylon 1.4.2-1.16.5
		geckolib3: Geckolib 3.0.34
		gg_enchantments: Good Game Enchantments 1.1.1
		givemehats: Give Me Hats! 1.5.1
		glassential: Glassential 1.16.4-1.1.5
		gobber2: Gobber2 2.3.71
		golemancy: Golemancy 1.0.1
		haema: Haema 1.7.0
		healthoverlay: Health Overlay 3.6.14
		heartbond: Heartbond 1.0.0
		hwg: Happiness is a Warm Gun 1.0.11
		illuminations: Illuminations 1.5.1
		impersonate: Impersonate 2.2.1
		indium: Indium 1.0.0
		indrev: Industrial Revolution 1.9.12-BETA
		inmis: Inmis 2.2.1-1.16.5
		inventorysorter: Inventory Sorter 1.7.9-1.16
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		kibe: Kibe 1.6.7-BETA
		ktdatataglib: KtDataTagLib 1.4.0
		kyrptconfig: Kytpt Config 1.1.6-1.16
		lambdynlights: LambDynamicLights 1.3.4+1.16
		lapisreserve: Lapis Reserve 1.0.7
		libblockattributes: LibBlockAttributes 0.8.4
		libblockattributes_core: LibBlockAttributes (Core) 0.8.7
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.7
		libblockattributes_items: LibBlockAttributes (Items) 0.8.5
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.4.0+1.16.5
		libstructure: LibStructure 1.5
		lightstones: Lightstones 1.3.0
		lithium: Lithium 0.6.4
		lookingglass: Through the Looking Glass Release - 1.1.0
		maelstrom_library: Maelstrom Library 1.2-1.16.5
		magic_lanterns: Magic Lanterns 1.4.5
		magna: Magna 1.5.3-1.16.5
		maybe-data: Maybe data 1.0.0-1.16.2
		megane: megane 4.0.0+1.16.5
		megane-applied-energistics-2: megane-applied-energistics-2 4.0.0+1.16.5
		megane-art-of-alchemy: megane-art-of-alchemy 4.0.0+1.16.5
		megane-astromine: megane-astromine 4.0.0+1.16.5
		megane-base: megane-base 4.0.0+1.16.5
		megane-fabric-furnaces: megane-fabric-furnaces 4.0.0+1.16.5
		megane-fast-transfer-lib: megane-fast-transfer-lib 4.0.0+1.16.5
		megane-industrial-revolution: megane-industrial-revolution 4.0.0+1.16.5
		megane-kibe: megane-kibe 4.0.0+1.16.5
		megane-lib-block-attributes: megane-lib-block-attributes 4.0.0+1.16.5
		megane-modern-industrialization: megane-modern-industrialization 4.0.0+1.16.5
		megane-runtime: megane-runtime 4.0.0+1.16.5
		megane-team-reborn-energy: megane-team-reborn-energy 4.0.0+1.16.5
		megane-tech-reborn: megane-tech-reborn 4.0.0+1.16.5
		megane-vanilla: megane-vanilla 4.0.0+1.16.5
		mermod: Mermod 1.4
		minecraft: Minecraft 1.16.5
		mixintrace: MixinTrace 1.0.0
		mm: Manningham Mills 2.2
		mobfarmutilities: Mob Farm Helpers 1.4.2
		mobz: MobZ 2.4.6
		modern_industrialization: Modern Industrialization 0.3.17
		modifiers: Modifiers 0.1.1
		modify-drops-api: Modify Drops API 0.3.1
		modmenu: Mod Menu 1.16.9
		more_tooltips: MoreTooltips 1.0.1
		mostructures: Mo' Structures 1.1.1+mc.1.16.5
		mousewheelie: Mouse Wheelie 1.7.1+mc1.16.5
		multi_item_lib: Multi Item Lib 1.3.0
		multipart_entities: MultipartEntities 1.1.1-SNAPSHOT
		mythicmetals: Mythic Metals 0.9.9
		nbtcrafting: NBT Crafting 2.0.11+mc1.16.4
		netherite_plus: Netherite Plus Mod 1.4.4-1.16.5
		noenchantcap: NoEnchantCap 4.1.0
		notenoughbreeding: Not Enough Breeding 1.16.5-fabric
		notenoughcrashes: Not Enough Crashes 3.2.0
		offlineskins: OfflineSkins 1.16.5-v1-fabric
		okzoomer: Ok Zoomer 4.0.1+1.16.2
		omega-config: OmegaConfig 1.0.4
		opchanter: OPChanter 1.16.5-fabric
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.0
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0-RC
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0-RC
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.0
		org_jetbrains_kotlinx_kotlinx-serialization-runtime: kotlinx-serialization-runtime 0.14.0
		org_joml_joml: joml 1.10.0
		origins: Origins 0.7.1
		origins-classes: Origins: Classes 1.1.1
		oro_config: OroArmor Config 3.0.0
		patchouli: Patchouli 1.16.4-50-FABRIC
		pehkui: Pehkui 2.1.0+21w18a
		phosphor: Phosphor 0.7.2+build.12
		piglib: Piglib 1.0.1
		playerabilitylib: Pal 1.2.1
		pling: Pling 1.3.0
		polymorph: Polymorph 0.0.10-1.16.5
		pugh_lib: Pugh Lib 1.1.0
		quickshulker: Quick Shulker 1.1.14-1.16
		rare-ice: Rare Ice 0.2.2
		ratsmischief: Rat's Mischief 1.1.1
		reach-entity-attributes: Reach Entity Attributes 1.1.1
		reborncore: Reborn Core 4.7.2+build.132
		recipeconditions: Fabric Recipe Conditions 0.4.0
		repurposed_structures: Repurposed Structures 1.16.5-1.10.5-fabric
		reroll: Reroll 1.2.1-1.16.5
		respawnablepets: Respawnable Pets 1.16.5-2
		ringsofascension: Rings of Ascension 1.1.1
		roughlyenoughitems: Roughly Enough Items 5.11.218
		roughlyenoughitems-api: REI (API) 5.11.218
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.11.218
		roughlyenoughitems-runtime: REI (Runtime) 5.11.218
		roughlyenoughresources: Roughly Enough Resources 2.1.3
		sakurarosea: Sakura Rosea 1.6.0-MC1.16.3-fabric
		satin: Satin 1.5.1
		seamless_loading_screen: Seamless Loading Screen 1.3.4
		seasons: Fabric Seasons 1.2-BETA
		secretrooms: Secret Rooms 0.9.5+1.16.5
		sgod: Save Gear on Death 0.0.2
		shulkerutils: shulkerutils 1.0.1-1.16
		silky_spawners: Silky Spawners 2.1.0+build.2-1.16
		simple_backpack: SimpleBackpack 1.0.38
		simplesoundmuffler: Simple Sound Muffler 0.2.1
		simpleteleporters: Simple Teleporters 2.2.1
		sizeshiftingpotions: Potionofshrinking 1.1.0
		slotlock: SlotLock 1.0.3-BETA
		smoothboot: Smooth Boot 1.16.5-1.6.0
		sodium: Sodium 0.1.1-SNAPSHOT
		sodium-extra: Sodium Extra 0.2.6
		somnus: Somnus API 0.0.11-1.16.5
		soulsegg: Souls Egg 2.0.0+1.16.5
		spark: spark 1.5.2
		spawnlanterns: Spawn Lanterns 1.0.1
		spellbound: Spellbound 1.2.1
		spruceui: SpruceUI 2.0.4+1.16
		staffofbuilding: Staff of Building 1.2.6-1.16.5
		static-content: Static Content 1.0.2-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stoneholm: Stoneholm 1.2.1
		structure-helpers: Structure Helpers 3.0.0
		taxfreelevels: Tax Free Levels 1.1
		team_reborn_energy: Energy 0.1.1
		techreborn: Tech Reborn 3.8.3+build.231
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.4
		terraform-config-api-v1: Terraform Config API (v1) 1.0.3
		terraform-dirt-api-v1: Terraform Dirt API (v1) 1.1.3
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.3
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.3
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.3
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.4
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.4
		terrestria: Terrestria 2.2.0
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.6
		traverse: Traverse 3.3.2
		trinkets: Trinkets 2.6.7
		tweed: Tweed 3.0.0-beta.26
		undestroying: Undestroying (Fabric) 1.16.5-1.1.1
		vanilla-hammers: Vanilla Hammers 3.0.3-1.16.5
		voyager: Voyager 1.0.0
		waystones: Waystones 1.1.1.1
		wildfire_gender: Wildfire's Gender Mod 2.5.1
		wolveswitharmor: Wolves With Armor 1.5.4-1.16.5
		world_blender: World Blender 1.16.5-2.1.5
		worldedit: WorldEdit 7.2.5+57d5ac9
		wrenchable: Wrenchable 1.0.0+1.16.1
		wthit: wthit 2.10.0
		xaerominimap: Xaero's Minimap 21.8.1
		xaeroworldmap: Xaero's World Map 1.13.5
		xenchant: xenchant 1.0.3
		yungsapi: YUNG's API 1.16.5-Fabric-5
	Patchouli open book context: n/a
	Launched Version: fabric-loader-0.11.3-1.16.5
	Backend library: LWJGL version 3.2.1 build 12
	Backend API: Intel(R) Iris(TM) Graphics 6100 GL version 2.1 INTEL-16.2.16, Intel Inc.
	GL Caps: Using framebuffer using ARB_framebuffer_object extension
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 4x Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz

**Comment by liach** [comment]
It's quite hard to know which mods added the problematic redirect that can cause the crash. Try remove half of your mods at once and try and see if your game still crashes; if not, you try with the other half of your mods, and then you split the current mods you are testing with into half, so on, etc.
