### ISSUE TITLE
Exception in server tick loop caused by Fabric Lifecycle Events and LuckPerms.

### ISSUE THREAD

**Issue by Cookie-Kurokami** [FabricMC/fabric#1461]
So, I tried writing to LuckPerms about this issue and they told me to come here instead, and so here I am. Every single time I try to use LuckPerms in my server, it crashes with this error relating to Fabric Lifecycle Events. The crash report is pasted below. I want to be able to use LuckPerms because so many mods rely on it, but this is making it impossible. Why is this happening and how do I fix it?
[crash-2021-05-20_02.09.05-server.txt](https://github.com/FabricMC/fabric/files/6512735/crash-2021-05-20_02.09.05-server.txt)

**Comment by Technici4n** [comment]
This looks related to a mixin by the mod `Impersonate`, not sure if Fabric API is at fault or not.
