### ISSUE TITLE
Biome modification API stabilization

### ISSUE THREAD

**Issue by Technici4n** [FabricMC/fabric#1465]
It can be stabilized now that #1269 is fixed, if anyone wants to PR that.

**Comment by frqnny** [comment]
The biome api does not work for me in 21w20a. Fix it before removing "stable" on 1.17.

**Comment by liach** [comment]
Does it work after 9e521e1377470d3d19b1ebec8b3a3cdfe52c04c6?

Imo, we can stabilize api part by part; there is nothing that force us to mark the whole api as stable. We can mark those working parts as stable first

**Comment by Technici4n** [comment]
Was done in edf35c6176cf3df32b88d3e13b58f4b6194e0229.
