### ISSUE TITLE
FabricBlockEntityTypeBuilder should be backported

### ISSUE THREAD

**Issue by haykam821** [FabricMC/fabric#1466]
The [`FabricBlockEntityTypeBuilder`](https://github.com/FabricMC/fabric/blob/9e521e1377470d3d19b1ebec8b3a3cdfe52c04c6/fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/block/entity/FabricBlockEntityTypeBuilder.java) class is useful for modding on 1.17, but isn't available on 1.16. For mods that are attempting to have compatibility with both, a backport would be useful.

**Comment by Technici4n** [comment]
I'm not sold, where do we stop? Do we implement tag support for mineable blocks so that 1.16 modders can use them?

**Comment by haykam821** [comment]
It should stop at API classes. The 1.16 version can defer to the vanilla class with 1.17-compatible arguments for the factory.

**Comment by modmuss50** [comment]
I dont think this will help with compatibilty between the two versions, sure it would make this specific thing compatible, but then its going to break down right when you hit the vanilla BE changes.

If this API is expanded to do something else for what ever reason and that also fits into 1.16 then yes it could be backported.

**Comment by haykam821** [comment]
Block entities theoretically can be made compatible between 1.16 and 1.17 using mixin. This is the only roadblock I have.

**Comment by modmuss50** [comment]
Sounds like a bad idea to me, if your doing that surely you can just make a wrapper around this api with the 1.16 and 1.17 apis.
