### ISSUE TITLE
Fabric API Overrides Datapack Sky Color Change

### ISSUE THREAD

**Issue by MrTalk** [FabricMC/fabric#1471]
When you change the color of a biomes sky and you have fabric-api-0.34.8+1.17 installed, the color of the sky reverts back to default minecraft sky colors

**Comment by MrTalk** [comment]
After further investigation I have concluded that the model fabric-networking-api-v1-1.0.11+b7ab6121a0.jar is causing the revert. Hope this helps.

**Comment by Technici4n** [comment]
Closing in favor of the more general  #1478.
