### ISSUE TITLE
Fabric API breaks underwater smooth lighting

### ISSUE THREAD

**Issue by Lentern** [FabricMC/fabric#1475]
Using Fabric API breaks the [underwater smooth lighting fix](https://bugs.mojang.com/browse/MC-68129) that was implemented in 1.17-pre2.

Affects Minecraft 1.17-pre2+ & API 0.34.8-0.57.3 and is fixed in API 0.58.0 for all Minecraft releases.

**Comment by koopaboopa** [comment]
I've found a potential workaround for this bug. You can edit the file at .minecraft/config/fabric/indigo-renderer.properties, and change `ambient-occlusion-mode=hybrid` to `ambient-occlusion-mode=vanilla`

Doing so restored the underwater smooth lighting behavior for me, but I've only tested it on my machine. (Windows, Java 17, Intel integrated graphics)
