### ISSUE TITLE
Tooltip on title screen suppresses texture draw in AFTER_RENDER event

### ISSUE THREAD

**Issue by jackassmc** [FabricMC/fabric#1477]
This happens in the Screen API test mod in 1.17. It does not happen in 1.16.

The texture gets drawn here: https://github.com/FabricMC/fabric/blob/b7ab612143d0de808476ea6039740c123c109231/fabric-screen-api-v1/src/testmod/java/net/fabricmc/fabric/test/screen/ScreenTests.java#L80-L84

The tooltip gets drawn here: https://github.com/FabricMC/fabric/blob/b7ab612143d0de808476ea6039740c123c109231/fabric-screen-api-v1/src/testmod/java/net/fabricmc/fabric/test/screen/StopSoundButton.java#L45-L47

Here's a screenshot of the title screen of the Screen API test mod in 1.17:
![Screenshot_2021-06-05_16-50-31](https://user-images.githubusercontent.com/84429870/120895674-632acd00-c61e-11eb-90cd-b4d309ca65af.png)

Here's a screenshot of the title screen of the Screen API test mod in 1.17 with the tooltip:
![Screenshot_2021-06-05_16-50-44](https://user-images.githubusercontent.com/84429870/120895717-8d7c8a80-c61e-11eb-8381-c3c25349906b.png)

**Comment by Technici4n** [comment]
Is this fixed by #1474?

**Comment by jackassmc** [comment]
> Is this fixed by #1474?

No, that only fixed buttons not rendering.

**Comment by Technici4n** [comment]
Ok weird, if you want to have a look why not, otherwise someone will eventually.

**Comment by jackassmc** [comment]
Turns out this is just a test mod issue.

https://github.com/FabricMC/fabric/blob/18ef9af8ecc61270b7165ae9e58efb4dde181564/fabric-screen-api-v1/src/testmod/java/net/fabricmc/fabric/test/screen/ScreenTests.java#L82
is outdated, it's supposed to be:
```java
RenderSystem.setShader(GameRenderer::getPositionTexShader);
RenderSystem.setShaderTexture(0, InGameHud.GUI_ICONS_TEXTURE);
```

<hr>

`Screen.renderTooltipFromComponents` calls
```java
RenderSystem.setShader(GameRenderer::getPositionColorShader);
```
so in the AFTER_RENDER event the shader is wrong if the tooltip gets rendered but is accidentally right if it isn't.
