### ISSUE TITLE
Could not find required mod: fabric requires {java @ [>=16]}

### ISSUE THREAD

**Issue by chichibooxd** [FabricMC/fabric#1482]
I can't launch fabric despite having Java 16 and OpenJDK 16 installed. I can launch vanilla minecraft and is using Java 16 (see attached).
![2021-06-10_12 24 35](https://user-images.githubusercontent.com/30566483/121464721-faa96a80-c9e6-11eb-93db-456ec8a06e04.png)

**Comment by haykam821** [comment]
What version of Fabric loader are you using?

**Comment by chichibooxd** [comment]
It seems to be a minecraft launcher issue, not fabric.

**Comment by haykam821** [comment]
Could you post more details about how you fixed the problem so this issue could be used as a reference for others having the same problem?

**Comment by chichibooxd** [comment]
I am using TLauncher as the primary launcher. It seems to be an issue on their side so I just returned on the official launcher and it worked.
