### ISSUE TITLE
Fabric server not starting on 1.17 jars

### ISSUE THREAD

**Issue by legoraft** [FabricMC/fabric#1487]
My server won't start when trying to launch it for the fiirst time, I also tested this with brand new jars, but it also didn't work. Also tried updating java, but it also won't work. 
This console is when I already updated java and new jars from the installer and the default generated start scripts
[1.17 startup.txt](https://github.com/FabricMC/fabric/files/6639635/1.17.startup.txt)

**Comment by Player3324** [comment]
> [17:47:06] [main/INFO]: [FabricLoader] Loading 3 mods: minecraft@1.17, java@8, fabricloader@0.11.3

You are still running Java 8, but 1.17 needs Java 16. You may have installed a newer Java version, but the active Java install is still 8 (active as in the version on your PATH or wherever resolves it on Windows)

**Comment by legoraft** [comment]
> 
> 
> > [17:47:06] [main/INFO]: [FabricLoader] Loading 3 mods: minecraft@1.17, java@8, fabricloader@0.11.3
> 
> You are still running Java 8, but 1.17 needs Java 16. You may have installed a newer Java version, but the active Java install is still 8 (active as in the version on your PATH or wherever resolves it on Windows)

Thanks, will figure out how to fix it

**Comment by PhoenixIV** [comment]
@sfPlayer1 The current recommended JRE is _8 Update 291_ (https://www.java.com/)
Am I missing something?

Nowhere in the Fabric documentation it says you need the JDK, which is, indeed, version 16.

**Comment by PhoenixIV** [comment]
@LegoRaft 
I solved this issue myself. It appears that Minecraft 1.17 (not only Fabric) now requires the JDK 16 (which is super shady to me, but whatsoever). I found this article on the issue: https://piunikaweb.com/2021/06/11/minecraft-jni-error-java-exception-1-17-update/
I solved this by installing [AdoptOpenJDK for version 16](https://adoptopenjdk.net/?variant=openjdk16&jvmVariant=hotspot). AdoptOpenJDK does not require you to have a service contract with Oracle, the company behind Java.

**Comment by modmuss50** [comment]
That is correct, Minecraft now requires Java 16, you can see it in the changelog here: https://www.minecraft.net/en-us/article/minecraft-snapshot-21w19a

There is nothing shady about this. we can do a better job with the error messages here however.

**Comment by PhoenixIV** [comment]
Another update: There also seems to be a much smaller JRE for 16 available [at AdoptOpenJDK via "Other platforms"](https://adoptopenjdk.net/releases.html?variant=openjdk16&jvmVariant=hotspot).
The JDK (Development Toolkit) has roughly 4x the size of the JRE (Runtime Environment).

@modmuss50 Shady to me because there are no download options higher than 8 available via the official java frontend that I know, which is java.com

**Comment by modmuss50** [comment]
Ah, I see. Yes i do agree with you that it can be confusing to know where to get java these days. AdoptOpenJDK is widely trusted. Microsoft has their own dist https://www.microsoft.com/openjdk as well as Amazon https://aws.amazon.com/corretto/ that will both work if you want something from a more well known source.

**Comment by PhoenixIV** [comment]
**[Feature request]** Include Java version warning in the launcher
