### ISSUE TITLE
@Mixin target net.minecraft.server.world.ThreadedAnvilChunkStorage$EntityTracker was not found net.fabricmc.fabric.mixins.common.json:entity.MixinEntityTracker

### ISSUE THREAD

**Issue by JamiesWhiteShirt** [FabricMC/fabric#149]
NOTE: This does not apply in development environments.

The mixin does not apply causing the accessor interface to not be applied, causing issues in clothesline-fabric and other mods using PlayerStream.

[ClassCastException in clothesline-fabric](https://gist.github.com/JamiesWhiteShirt/73b72d982bebe1c6763b5947c3275ae4)

Installed mods: `developer-mode@1.0.11, fabric@0.2.7+build.126, fabricloader@0.4.2+build.130, clothesline-fabric@0.0.14`

Apparently this mixin is unique in that it mixes into an inaccessible class, using string "targets".

**Comment by asiekierka** [comment]
Fixed in 0.4.2+build.131. Wrong repo, use fabric-loader or Mixin next time.
