### ISSUE TITLE
Add SHA2 verification of client mods, not unlike the resource pack system of forcing clients to use the resource pack or get kicked

### ISSUE THREAD

**Issue by uselessknickknacks** [FabricMC/fabric#1496]
Honestly did not know where to provide this feedback/request.

Some fabric mods require the client to also have the mod installed in order to properly display it's contents, typically things that add items and mobs.
While for some mods one can use fairly creative solutions of making life a bit miserable (such as invisible entities attacking you since you don't have the mod installed, or invisible blocks making people stutter and lagg, thus not able to reach the exit), it's fairly bad and feels bad to experience than a straightforward kick and a explanation.

I'd like to request something not unlike the texture pack enforcement thing that has been added to minecraft, whereas if you decline to install the mods the server asks you to install, it will simply kick you and list in the message which mods are required. Also allow us to add a optional tag.

If this already exists, please point me to it.

**Comment by Technici4n** [comment]
If the server has mods adding content that the client doesn't have, the client will usually fail to connect with such a message:
![image](https://user-images.githubusercontent.com/13494793/121823608-a2a08b80-cca6-11eb-80f4-89ea652464a6.png)

Ghost blocks are not supposed to happen, if you have experienced them it might be a bug in one of the mods you have installed.

**Comment by uselessknickknacks** [comment]
Oh so you are supposed to get disconnected if you try to connect to a server which uses a mod that the client also needs to have installed?

The mod I tried with was https://www.curseforge.com/minecraft/mc-mods/mini-extras-fabric
I had to have it and cloth config installed on the client too in order for the blocks to work normally. Otherwise they were invisible, causing the below behaviour in the videos. (First one is without the mod installed on client, the second in daytime is with the mod installed on client, mod was installed on the fabric server during both videos). 

I'll make the mod author aware then that one is supposed to get disconnected if the client does not have the mod. I have never worked with fabric before.
(and only very little very basic plugin work and small modifications to existing plugins on spigot) 
so I have no idea how this can be caused.

https://user-images.githubusercontent.com/59621139/121869761-46ffed80-ccfa-11eb-888c-e939ed029326.mp4
https://user-images.githubusercontent.com/59621139/121869778-4a937480-ccfa-11eb-87ba-eb2e1f520c5e.mp4

EDIT: Would it be possibly for the server to reply with a more sensible thing to the player to make them aware that they are missing a mod? Perhaps make it toggleable in the server so one can decide to have what's in that picture as a "debug" kick message. While a more human friendly one for normal players I.E
"You are missing these mods:
Better End
Untitled Duck Mod"

Etc.

**Comment by Technici4n** [comment]
> Would it be possibly for the server to reply with a more sensible thing to the player to make them aware that they are missing a mod? Perhaps make it toggleable in the server so one can decide to have what's in that picture as a "debug" kick message. While a more human friendly one for normal players I.E
"You are missing these mods:
Better End
Untitled Duck Mod"

I agree with you, the current solution is not great and we would want such an error message in the future, but for that someone has to implement #463. I am closing this as a duplicate.
