### ISSUE TITLE
Fabric not opening

### ISSUE THREAD

**Issue by 3lovetobepink** [FabricMC/fabric#1500]
when i try to open fabric-loader-0.11.5-1.16.5 it says Could not find required mod: fabric requires {minecraft @ [~1.17-alpha.21.19.a]}
and when i try to open fabric-loader-0.11.6-1.17 it says 
[20:22:28 ERROR]: Game ended with bad state (exit code 1)
[20:22:28 INFO]: Ignoring visibility rule and showing launcher due to a game crash
what do i do
log for fabric-loader-0.11.6-1.17
[latest.log](https://github.com/FabricMC/fabric/files/6659442/latest.log)

**Comment by frqnny** [comment]
Can you try updating fabric api to the latest? it seems very weird

**Comment by 3lovetobepink** [comment]
> Can you try updating fabric api to the latest? it seems very weird

I did

**Comment by warjort** [comment]
Your log says you have 2 versions of fabric-api installed.

````
 - Conflicting versions found for fabric-api-base: used 0.3.0+a02b4463c6, also found 0.3.0+a02b44633d
 - Conflicting versions found for fabric-blockrenderlayer-v1: used 1.1.5+ca58154a7d, also found 1.1.5+a02b4463c6
 - Conflicting versions found for fabric-networking-v0: used 0.3.2+92519afac6, also found 0.3.2+ca58154a7d
 - Conflicting versions found for fabric-crash-report-info-v1: used 0.1.3+ca58154a7d, also found 0.1.3+a02b4463c6
````

The version it is actually using is for snapshot 21w20a (according to curseforge)
````
fabric@0.34.5+1.17
````

At time of writing, 0.35.2+1.17 is the latest.

**Comment by 3lovetobepink** [comment]
So do i uninstall fabric api

**Comment by frqnny** [comment]
No, you get the latest fabric api. You seem to have two jars of fabric api inside your mod folder, So delete them and make sure you download the latest.

**Comment by 3lovetobepink** [comment]
> No, you get the latest fabric api. You seem to have two jars of fabric api inside your mod folder, So delete them and make sure you download the latest.

i just did now its saying this
[latest.log](https://github.com/FabricMC/fabric/files/6665094/latest.log)
do you think the fabric language kotlin mod has something to do with it

**Comment by Juuxel** [comment]
The problem is that you have both 1.16 and 1.17 mods in the same `mods` folder, which doesn't work. If you want to use Fabric on both 1.16 and 1.17, you have to separate the game directories, which is explained in step 2 here: https://fabricmc.net/wiki/player:tutorials:install_mcl:windows

**Comment by 3lovetobepink** [comment]
> The problem is that you have both 1.16 and 1.17 mods in the same `mods` folder, which doesn't work. If you want to use Fabric on both 1.16 and 1.17, you have to separate the game directories, which is explained in step 2 here: https://fabricmc.net/wiki/player:tutorials:install_mcl:windows

Do I put anything in the folder because when it opens it says modded but my mods aren't showing up

**Comment by warjort** [comment]
Yes, but only put 1.16 mods in a 1.16 minecraft installation.

If you want to run 1.17 minecraft as well you will need a different installation with 1.17 mods only.

**Comment by 3lovetobepink** [comment]
Do you mean a folder for just 1.17 mods

**Comment by frqnny** [comment]
Yes. FLoader will attempt to load all the mods that are inside the mods folder, including 1.16 and 1.17 mods. You need to move the 1.16 mods somewhere else.

**Comment by 3lovetobepink** [comment]
Like where do i make a folder named 1.16 mods

**Comment by frqnny** [comment]
It doesn't really matter? just make it somewhere else. If you are trying to load mods to MC 1.17, you only need 1.17 mods in the 'mods' folder.

**Comment by warjort** [comment]
From an earlier comment:

> which is explained in step 2 here: https://fabricmc.net/wiki/player:tutorials:install_mcl:windows

The installer lets you have many minecraft installations for different versions or different collections of mods.

**Comment by 3lovetobepink** [comment]
i tryed opening it it said
Could not find required mod: blockus requires {fabric @ [*]}
it gave me 3 logs
[2021-06-16-2.log](https://github.com/FabricMC/fabric/files/6665354/2021-06-16-2.log)
[latest.log](https://github.com/FabricMC/fabric/files/6665355/latest.log)
[2021-06-16-1.log](https://github.com/FabricMC/fabric/files/6665356/2021-06-16-1.log)

**Comment by frqnny** [comment]
You seem to have removed fabric api. You still need fabric api, but just download the latest for 1.17.

**Comment by 3lovetobepink** [comment]
i downloaded it and it still is saying the same thing

**Comment by 3lovetobepink** [comment]
i updated the mod menu but when it opens it only shows the 1.17 mods 
heres the crash report
[crash-2021-06-16_15.56.44-client.txt](https://github.com/FabricMC/fabric/files/6665568/crash-2021-06-16_15.56.44-client.txt)

**Comment by warjort** [comment]
This is just going around in circles. :-)

I would suggest you take this to somewhere like:
https://www.reddit.com/r/fabricmc/
which is for help requests.

This issues list is for bug reports.

**Comment by warjort** [comment]
Your last crash says you don't have cloth config installed.

**Comment by 3lovetobepink** [comment]
I don't know what to do I have done everything 😥
[crash-2021-06-16_16.56.26-client.txt](https://github.com/FabricMC/fabric/files/6665972/crash-2021-06-16_16.56.26-client.txt)
[crash-2021-06-16_17.31.11-client.txt](https://github.com/FabricMC/fabric/files/6665973/crash-2021-06-16_17.31.11-client.txt)
[crash-2021-06-16_17.33.08-client.txt](https://github.com/FabricMC/fabric/files/6665974/crash-2021-06-16_17.33.08-client.txt)
[crash-2021-06-16_16.30.29-client.txt](https://github.com/FabricMC/fabric/files/6665975/crash-2021-06-16_16.30.29-client.txt)
[crash-2021-06-16_16.42.45-client.txt](https://github.com/FabricMC/fabric/files/6665976/crash-2021-06-16_16.42.45-client.txt)
my recent crash reports i'm sorry to keep bothering you
[latest.log](https://github.com/FabricMC/fabric/files/6665996/latest.log)

**Comment by warjort** [comment]
This is still not a Fabric api issue. 

You are back to the original mistake:

````
java.lang.UnsupportedClassVersionError: me/shedaniel/autoconfig/example/ExampleInits has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0
````

You are trying to load a  minecraft 1.17 mod (compiled for java 16) using minecraft 1.16.5 and java 8

````
Minecraft Version ID: 1.16.5
Java Version: 1.8.0_51, Oracle Corporation
````

Try using something like curseforge if you can't keep track of which mod goes with which minecraft version.
https://curseforge.overwolf.com/

**Comment by warjort** [comment]
I won't be answering any further on this thread.

**Comment by Technici4n** [comment]
Calm down @warjort, I know it can be frustrating.

@3lovetobepink This is not really the place for tech support. I'd recommend joining [our official Discord server](https://discord.gg/v6v4pMv) to get more interactive help. In particular, you can seek help in the `#player-support` channel!
