### ISSUE TITLE
Fabric error

### ISSUE THREAD

**Issue by 3lovetobepink** [FabricMC/fabric#1502]
Could not find required mod: fabric requires {minecraft @ [~1.17-alpha.21.19.a]}
I'm trying to run 1.16.5 fabric loader but it wont work
how do i run both 1.16.5 fabric and 1.17 Fabric at once

**Comment by calloatti** [comment]
Join the Fabric Discord here https://discord.gg/v6v4pMv and ask for help in the #player-support channel.
