### ISSUE TITLE
Shockbyte crash report 

### ISSUE THREAD

**Issue by rayduit** [FabricMC/fabric#1508]
Note: I don’t know any code or literally anything on what to do. Speak to me like I am a child.

20.06 16:48:56 [Server] main/WARN @Mixin target net/minecraft/class_3898$class_3208 is public in fabric-networking-api-v1.mixins.json:accessor.EntityTrackerAccessor and should be specified in value
20.06 16:49:00 [Server] main/WARN Error loading class: org/jetbrains/annotations/ApiStatus$ScheduledForRemoval (java.lang.ClassNotFoundException: org/jetbrains/annotations/ApiStatus$ScheduledForRemoval)

**Comment by transcental** [comment]
Can you give the entire log?
If you haven't started the server since, it'll be in logs/latest.log on your FTP section.

**Comment by liach** [comment]
If you don't post the log or the crash report, people can't help you.

**Comment by transcental** [comment]
@rayduit Log please?
Go to `FTP/logs/latest.log`. If this issue is solved, then close the issue with the `Close` button at the bottom of the page.

**Comment by liach** [comment]
Don't think the submitter will take care of the issue any more after the initial report, and can't help hence.
