### ISSUE TITLE
When will there be Fabric API/Loom/Loader 1.0?

### ISSUE THREAD

**Issue by kanpov** [FabricMC/fabric#1509]
Currently, all Fabric API (and also Loom and Loader) versions start with a 0.

Will there ever be a 1.0 version or will it stay like it is currently?

Sorry if it's a stupid question.

**Comment by Player3324** [comment]
We're not quite where we want to be to call it stable. Should happen at some point, but not yet. The semver semantics for minor+patch version handling should already be in line with the expectations from 1.x+

**Comment by kanpov** [comment]
Okay, thanks! Closing this.
