### ISSUE TITLE
BUG- zombie acts like zombified piglin

### ISSUE THREAD

**Issue by wb1016** [FabricMC/fabric#1511]
in Fabric API 0.36.0, zombie AI seems overwrited by zombified piglin AI.
they are kind of less agressive but as soon as player attack them, all nearby zombies get angry like silverfish and zombie pigmen.
they tracks player from extremely long distance, even behind 10 blocks wide wall, and even underground.
this affects almost all of zombies from loaded chunks, causing TPS drop down to 4.
the lag can be reduced by lithium mod. 17TPS instead of 4. but this does not solve origin of problem; the bug.

tested platform list

-MultiMC, official javaw runtime, windows 10 20H2, ZGC, heavily modded
-MultiMC, official javaw runtime, windows 10 20H2, no java argument (will select G1GC automatically), only Fabric API installed, clean install
-dedicated server, AdoptOpenJDK16, windows 10 20H2, ZGC, modded
-dedicated server, AdoptOpenJDK16, windows 10 20H2, G1GC, only Fabric API installed

detailed info in this youtube video.
https://youtu.be/0-jtwIlExyg

**Comment by haykam821** [comment]
I can reproduce this behavior on vanilla Minecraft 1.17.

**Comment by embeddedt** [comment]
I've reproduced this on vanilla 1.16 as well (without Fabric installed). I think this is intended behavior. Zombies have a mechanic where they can send a cry for help to nearby zombies. Presumably this allows them to pathfind to you even without line-of-sight.

**Comment by wb1016** [comment]
after @embeddedt commented, i reproduced this on 1.8.9 vanilla.
turns out this was a vanilla **feature**.
