### ISSUE TITLE
Java Virtual Machine error? (Inexperienced)

### ISSUE THREAD

**Issue by onyx0718** [FabricMC/fabric#1512]
I've no clue what I did, but I am trying to play a modpack from Overwolf's Curseforge. It's called Euphoric Curiosity. It uses the newest version of Minecraft at 1.17, and all of the different mods are for Fabric. It uses Fabric 0.11.6, which I'm not sure if I have. But I do know, using my computer's command screen, that I have the correct Java version (Java 16). 

Once I downloaded it the first time, I played it for a little bit and then it crashed. After it crashed I was never able to open it again. I cannot find the original crash log, but now whenever I try to open it; it shows this error message:

![image](https://user-images.githubusercontent.com/86316388/122967847-e9eae400-d358-11eb-93e9-c61a589972ab.png)

Then I close out of that message, it takes me to the MC launcher, and shows an additional error message:

![image](https://user-images.githubusercontent.com/86316388/122967984-0b4bd000-d359-11eb-8b19-6c47b02eae03.png)

This same thing occurs with similar fabric modpacks on curseforge, just giving me an error message without the game launching. There are no crash reports, or logs. 

If this is a problem with my hardware, the modpacks, or some other factor, then I'm sorry for the inconvenience. I'd also appreciate it if you have patience with me, as this is the first time I have to deal with something like this.

**Comment by liach** [comment]
In your game directory, there should be `hs_err_pid` files generated by java virtual machine. Share the latest one.

**Comment by onyx0718** [comment]
> In your game directory, there should be `hs_err_pid` files generated by java virtual machine. Share the latest one.

I can't seem to find it, could you be more specific as to where to find it?
Also, I did find a file titled launcher_log, which might have some useful info.
I tried launching the modpack again, with the same message at around 10 PM June 23rd
Here's what the launcher_log says:

[launcher_log.txt](https://github.com/FabricMC/fabric/files/6705846/launcher_log.txt)

**Comment by liach** [comment]
In line 1442 the crash happened immediately, less than 1 second after attempting to launch. Interesting.

Can you check `C:\Users\Blue\Twitch\Minecraft\Instances\Euphoric Curiosity` for the crash reports or hs err pid files?

Also navigate to `C:\Users\Blue\Twitch\Minecraft\Install\runtime\java-runtime-alpha\windows-x64\java-runtime-alpha\bin`. Then open a command prompt/powershell there (shift + right click in the folder's empty parts), and type `java -version` to check the java version.

**Comment by onyx0718** [comment]
No crash reports or hs_err_pid files in C:\Users\Blue\Twitch\Minecraft\Instances\Euphoric Curiosity, nor in any internal folders within that.

And using the powershell, I see that it uses Java 16.0.1; which I downloaded just recently for fabric. Is that the correct version?


> In line 1442 the crash happened immediately, less than 1 second after attempting to launch. Interesting.
> 
> Can you check `C:\Users\Blue\Twitch\Minecraft\Instances\Euphoric Curiosity` for the crash reports or hs err pid files?
> 
> Also navigate to `C:\Users\Blue\Twitch\Minecraft\Install\runtime\java-runtime-alpha\windows-x64\java-runtime-alpha\bin`. Then open a command prompt/powershell there (shift + right click in the folder's empty parts), and type `java -version` to check the java version.

**Comment by liach** [comment]
Hmm, can you try remove `-XX:+UseConcMarkSweepGC` entry from the java vm arguments?

**Comment by onyx0718** [comment]
How do I do that?

> Hmm, can you try remove `-XX:+UseConcMarkSweepGC` entry from the java vm arguments?

**Comment by liach** [comment]
So first go here to edit your launch profile (I think twitch opens a minecraft launcher for you)
![image](https://user-images.githubusercontent.com/7806504/123196483-a0d98380-d46f-11eb-9531-0378f80db5b4.png)
Then `more options`
![image](https://user-images.githubusercontent.com/7806504/123196535-b77fda80-d46f-11eb-862f-bfe1cd2f9230.png)
Then scroll down, and this one is what you want
![image](https://user-images.githubusercontent.com/7806504/123196588-ccf50480-d46f-11eb-87b4-fdb3b050d67d.png)

Remove the `-XX:+CMSIncrementalMode` and `-XX:+UseConcMarkSweepGC` entries in that field. The "CMS" has been removed in java 14, and we are now on java 16.


(I use `-Xmx8G -Xms8G -XX:+UnlockExperimentalVMOptions -XX:+UseZGC -Xlog:gc -XX:+ShowCodeDetailsInExceptionMessages` which is commands specific to jdk 16)

**Comment by onyx0718** [comment]
Alright, it seems to work now that I've done that. But when I launch through Curseforge, it defaults back to having those arguments in there. Is there any way of changing the default on curseforge to make sure it doesn't do that? If you're not sure then that's fine.

Otherwise, it is working now. I'll just have to remove those entries each time I launch. Thank you so much for your support. I'll close this issue page here soon unless there's any additional thoughts

**Comment by liach** [comment]
So yes, this is a curseforge/twitch bug. They are using command-line options that have been unsupported by java since java 14 in java 16. Please report this to them (to remove `-XX:+CMSIncrementalMode` and `-XX:+UseConcMarkSweepGC` for java 16 vm arguments) so we can avoid such problems in the future.

Thank you for your patience and walking through this! Since this is not directly related to fabric api, I will close the issue. But you can still comment here and feel free to if you have more to questions or comments.
