### ISSUE TITLE
Please Add a Command Line Character

### ISSUE THREAD

**Issue by eyoung100** [FabricMC/fabric#1516]
While setting up a Minecraft Server on a Pi 4B 8gb with Ubuntu Server  21.04, I noticed a small cosmetic issue.  If I install Paper, after server load, I receive a line with a Command Prompt
`>` with a blinking block.

On Fabric I get:
![MC ServerPromptMissing](https://user-images.githubusercontent.com/5230163/123031566-124efe80-d3aa-11eb-9d2d-b1f896f78196.png)
Note the left side terminal

I'd like to see some sort of prompt or wording etc, so that I know it's safe to enter commands.

PS: If this is some odd behavior due to KTerm, is it fixable?

**Comment by liach** [comment]
I think you can always enter commands; I think commands you entered too early will be processed by the server when the server is ready. Fabric doesn't change vanilla behavior for server consoles, maybe except the loader has some bug with the server swing gui.

**Comment by eyoung100** [comment]
>  has some bug with the server swing gui.

I'll agree with that possibility.  How can I help investigate?

**Comment by modmuss50** [comment]
This is out of scope for what fabric-api should be doing imo. Feel free to install/make a mod to do this 👍
