### ISSUE TITLE
issue fabric loader

### ISSUE THREAD

**Issue by RTEo13718295349** [FabricMC/fabric#1517]

**Comment by RTEo13718295349** [comment]
issue fabric loader, Could not find required mod: fabric requires {minecraft @ [~1.17-alpha.21.19.a]}. I am trying to do smt but idk what to. Could u guys help

**Comment by liach** [comment]
You should install fabric for the right minecraft version. You seems to be installing 1.16 fabric on Minecraft 1.17.
