### ISSUE TITLE
Limited RAM with VS Code Environment

### ISSUE THREAD

**Issue by thegamingninja** [FabricMC/fabric#152]
- Minecraft Version: 1.14
- Yarn Mappings: 1.14+build.1
- Loader Version: 0.4.2+build.132
- Fabric Version: 0.2.7+build.127

I set up a Fabric development environment for VS Code following the tutorial on the wiki, everything works fine except for the debugging client, it's limited to about ~530mb of RAM ([Screenshot was taken while generating new world](https://imgur.com/a/Z192ZSC)) and 32bit Java, any attempt to change the RAM amount for the JVM in `gradle.properties` to anything over 1G causes the build to fail, and adding `-Xmx1G` to the `vmArgs` area of `launch.json` allows it to use a full 1gb of RAM but anything over 1gb doesn't launch.

**Comment by sekwah41** [comment]
What do you get when you run in command prompt `java -version`?

If it states a 32 bit version there I would suggest uninstalling java 32bit and reinstalling the desired JDK you want to work with.

**Comment by Prospector** [comment]
This doesn't seem like it would have anything to do with Fabric API anyway. If it is a fabric issue, it would be with Fabric Loader.
