### ISSUE TITLE
Profiler Error Messages

### ISSUE THREAD

**Issue by rustylocks79** [FabricMC/fabric#1521]
I have noticed some weird behavior with the profiler which I believe to be a bug. I recreated this issue using the fabric-example-mod linked to by the wiki. When I open the pie graph (shift + F3) error messages similar to the following begin to appear in the log. 

> [18:20:47] [Render thread/WARN] (Minecraft) Something's taking too long! 'root' took aprox 124.2761 ms 
> [18:20:48] [Render thread/WARN] (Minecraft) Something's taking too long! 'root.gameRenderer.gui.debug' took aprox 110.1133 ms
> [18:20:48] [Render thread/WARN] (Minecraft) Something's taking too long! 'root.gameRenderer.gui' took aprox 111.1128 ms
> [18:20:48] [Render thread/WARN] (Minecraft) Something's taking too long! 'root.gameRenderer' took aprox 131.3807 ms
> [18:20:48] [Render thread/WARN] (Minecraft) Something's taking too long! 'root' took aprox 173.8007 ms
> [18:20:50] [Render thread/WARN] (Minecraft) Something's taking too long! 'root.gameRenderer.level.terrain' took aprox 150.464 ms
> [18:20:50] [Render thread/WARN] (Minecraft) Something's taking too long! 'root.gameRenderer.level' took aprox 156.1843 ms
> [18:20:50] [Render thread/WARN] (Minecraft) Something's taking too long! 'root.gameRenderer' took aprox 163.6167 ms
> [18:20:50] [Render thread/WARN] (Minecraft) Something's taking too long! 'root' took aprox 200.022 ms

Subsequently, when leaving the game the log displays these messages. 

> [18:21:02] [Render thread/ERROR] (Minecraft) Cannot push 'forcedTick' to profiler if profiler tick hasn't started - missing startTick()?
> [18:21:02] [Render thread/ERROR] (Minecraft) Cannot push 'sound' to profiler if profiler tick hasn't started - missing startTick()?
> [18:21:02] [Render thread/ERROR] (Minecraft) Cannot pop from profiler if profiler tick hasn't started - missing startTick()?
> [18:21:02] [Render thread/ERROR] (Minecraft) Cannot push 'render' to profiler if profiler tick hasn't started - missing startTick()?
> [18:21:02] [Render thread/ERROR] (Minecraft) Cannot push 'display' to profiler if profiler tick hasn't started - missing startTick()?
> [18:21:02] [Render thread/ERROR] (Minecraft) Cannot pop from profiler if profiler tick hasn't started - missing startTick()?
> [18:21:02] [Render thread/ERROR] (Minecraft) Cannot pop from profiler if profiler tick hasn't started - missing startTick()?
> [18:21:02] [Render thread/ERROR] (Minecraft) Cannot push 'gameRenderer' to profiler if profiler tick hasn't started - missing startTick()?
> [18:21:02] [Render thread/ERROR] (Minecraft) Cannot pop from profiler if profiler tick hasn't started - missing startTick()?
> [18:21:02] [Render thread/ERROR] (Minecraft) Cannot push 'toasts' to profiler if profiler tick hasn't started - missing startTick()?
> [18:21:02] [Render thread/ERROR] (Minecraft) Cannot pop from profiler if profiler tick hasn't started - missing startTick()?
> [18:21:03] [Render thread/ERROR] (Minecraft) Cannot push 'blit' to profiler if profiler tick hasn't started - missing startTick()?
> [18:21:03] [Render thread/ERROR] (Minecraft) Cannot pop from profiler if profiler tick hasn't started - missing startTick()?
> [18:21:03] [Render thread/ERROR] (Minecraft) Cannot push 'updateDisplay' to profiler if profiler tick hasn't started - missing startTick()?
> [18:21:03] [Render thread/ERROR] (Minecraft) Cannot push 'mouse' to profiler if profiler tick hasn't started - missing startTick()?
> [18:21:03] [Render thread/ERROR] (Minecraft) Cannot pop from profiler if profiler tick hasn't started - missing startTick()?
> [18:21:03] [Render thread/ERROR] (Minecraft) Cannot push 'mouse' to profiler if profiler tick hasn't started - missing startTick()?
> [18:21:03] [Render thread/ERROR] (Minecraft) Cannot pop from profiler if profiler tick hasn't started - missing startTick()?
> [18:21:03] [Render thread/ERROR] (Minecraft) Cannot pop from profiler if profiler tick hasn't started - missing startTick()?
> [18:21:03] [Render thread/ERROR] (Minecraft) Cannot push 'yield' to profiler if profiler tick hasn't started - missing startTick()?
> [18:21:03] [Render thread/ERROR] (Minecraft) Cannot pop from profiler if profiler tick hasn't started - missing startTick()?
> [18:21:03] [Render thread/ERROR] (Minecraft) Cannot push 'fpsUpdate' to profiler if profiler tick hasn't started - missing startTick()?
> [18:21:03] [Render thread/ERROR] (Minecraft) Cannot pop from profiler if profiler tick hasn't started - missing startTick()?
> [18:21:03] [Render thread/ERROR] (Minecraft) Cannot pop from profiler if profiler tick hasn't started - missing startTick()?

My assumption is that this is an error caused by Fabric API. A full log is attached below. 
Additionally, I am unable to get the /debug start and stop commands to output to a profile file. This may or may not be related. 
[latest.log](https://github.com/FabricMC/fabric/files/6712441/latest.log)

**Comment by liach** [comment]
Interesting. Maybe some of fabric's mixins were ported incorrectly. However, I don't see such happening in production. What is the minimum setup needed? Just the example mod?

**Comment by rustylocks79** [comment]
It is just a clone of the fabric example mod. No modifications were made (imported directly through IntelliJ). The Gradle project was built and the Minecraft Client was run in the ide. I am creating a creative super flat world on peaceful difficulty.  I open up the debug pie (Shift F3). The errors appear consistently when leaving the game from the title screen.

**Comment by liach** [comment]
The ones when f3 is on may be the performance problems with your device, but the messages when you leave the world for the menu is most likely bugs.

> leaving the game from the title screen
Do you mean these print at the instant when you press the button to exit the game?

**Comment by rustylocks79** [comment]
Yes, that is correct error messages are printed at the instant the "Quit Game" button is pressed on the title screen. 

Note, it is very possible that the warnings are performance issues. The computer I am running this on is not made for graphics.
