### ISSUE TITLE
Server is always 200-500 behind when trying to enter the nether

### ISSUE THREAD

**Issue by MentegaaTerbaang** [FabricMC/fabric#1522]
Crash report https://pastebin.com/gM00mLQv

**Comment by liach** [comment]
Post as many crash reports as possible, as those might give a better view on the whole problem. This one appears to be server waiting for a region file writing when the watchdog kills the server. How good are your server's hard drives?

If you don't want watchdog, you can set the timeout in server.properties to -1.
