### ISSUE TITLE
I am getting this crash/error while loading into a single player world.

### ISSUE THREAD

**Issue by VikranthMallru** [FabricMC/fabric#1529]
I am getting this error while loading into a single player world. The world loads till 100% then crashes the whole game.
PS: the txt file for crash report.
 EDIT: i sent the wrong file, here is the correct one :
[crash-2021-06-28_20.54.19-client.txt](https://github.com/FabricMC/fabric/files/6730709/crash-2021-06-28_20.54.19-client.txt)

**Comment by silask7188** [comment]
try removing optifabric+optifine(if you have it)

**Comment by VikranthMallru** [comment]
I dont have an mods/ optifine/ optifabric running.

**Comment by frqnny** [comment]
This is literally Forge crash report. What the heck.

**Comment by VikranthMallru** [comment]
I have no idea what to do now, i can confirm that i was tryna run fabric, but it just crashes when i try to get into a single player world and it just crashes at 100%.

**Comment by frqnny** [comment]
Well the log you gave us has optifine running. So you have fabric set up wrong or you gave us the wrong log

**Comment by VikranthMallru** [comment]
Oh yeaa, I apologise for sending the wrong file, the attached file is the correct one.
[crash-2021-06-28_20.54.19-client.txt](https://github.com/FabricMC/fabric/files/6730683/crash-2021-06-28_20.54.19-client.txt)

**Comment by VikranthMallru** [comment]
> Well the log you gave us has optifine running. So you have fabric set up wrong or you gave us the wrong log

[crash-2021-06-28_20.54.19-client.txt](https://github.com/FabricMC/fabric/files/6730751/crash-2021-06-28_20.54.19-client.txt)
The correct file is this.

**Comment by frqnny** [comment]
Interesting. Must be a FRAPI rendering crash, can anyone who knows rendering try to explain what happened? He's just using FAPI and that's it.

**Comment by VikranthMallru** [comment]
Uh, so what do i do now? pls help.

**Comment by Technici4n** [comment]
Duplicate of #1479
