### ISSUE TITLE
Error with BlockRenderLayerMap on server

### ISSUE THREAD

**Issue by transcental** [FabricMC/fabric#1530]
Hi,

I'm creating my Fabric mod, and when I put the latest build on a server with Lithium, API and BYG, I'm getting an issue about BlockRenderLayerMap not being found in the Fabric API.

All of the mod versions are correct.

Please can somebody help me here?

[Error Log](https://gist.github.com/dbarnes18/3fdaa7ef274c7be5c289d92c2f8f2706)

My mod is: https://github.com/DillonB07/blocks-blocks-blocks

The mod also works fine on the IntelliJ IDEA CE built-in client.

**Comment by warjort** [comment]
Rendering classes are only available on the client.

You need to separate your initialization of the block rendering into a client entrypoint that won't get run in dedicated server mode.

https://fabricmc.net/wiki/tutorial:side.
https://fabricmc.net/wiki/documentation:entrypoint
