### ISSUE TITLE
Could not execute entrypoint stage 'main' due to errors

### ISSUE THREAD

**Issue by JelliBelli1223** [FabricMC/fabric#1531]
I've been getting this error whenever I launch the game, and even if I disable or remove the mod associated with the error, it then says another mod is causing the issue. I looked up the error and most results pulled me here so hopefully you can help me out.

Here is the Report

---- Minecraft Crash Report ----
// There are four lights!

Time: 6/28/21, 6:47 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'rusted-iron'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	Suppressed: java.lang.NoSuchFieldError: APOLI_IDENTIFIER
		at com.archecraft.minecraft.acorigins.registry.ACOPowers.init(ACOPowers.java:79)
		at com.archecraft.minecraft.acorigins.ACOrigins.onInitialize(ACOrigins.java:19)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 11 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_5548
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:170)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:466)
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.lambda$getOrCreate$0(EntrypointStorage.java:106)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:104)
	at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:191)
	at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_5548
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:175)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 25 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)

-- Patchouli Book Info --
Details:
	Patchouli open book context: n/a
Stacktrace:
	at net.minecraft.class_128.handler$dgh000$fillPatchouliContext(class_128.java:521)
	at net.minecraft.class_128.<init>(class_128.java:36)
	at net.minecraft.class_128.method_560(class_128.java:266)
	at net.minecraft.client.main.Main.main(Main.java:185)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Initialization --
Details:

-- System Details --
Details:
	Minecraft Version: 1.17
	Minecraft Version ID: 1.17
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 3349796240 bytes (3194 MiB) / 4370464768 bytes (4168 MiB) up to 8925478912 bytes (8512 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
	Identifier: Intel64 Family 6 Model 94 Stepping 3
	Microarchitecture: Skylake (Client)
	Frequency (GHz): 3.19
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: Radeon(TM) RX 460 Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x67ef
	Graphics card #0 versionInfo: DriverVersion=27.20.21003.8013
	Graphics card #1 name: Intel(R) HD Graphics 530
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x1912
	Graphics card #1 versionInfo: DriverVersion=27.20.100.8682
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 2.13
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 2.13
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 37507.45
	Virtual memory used (MB): 24008.86
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 128.02
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8512m -Xms256m -XX:PermSize=256m
	Fabric Mods: 
		acorigins: ArchesOrigins 0.3.1
		additionalbars: Additional Bars 2.0.5
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		adventurez: AdventureZ 1.2.7
		amecsapi: Amecs API 1.1.4+mc21w16a
		animal_feeding_trough: Animal Feeding Trough 1.0.2
		apoli: Apoli 1.0.3
		appleskin: AppleSkin mc1.17-2.0.0
		apugli: Apugli 1.0.2
		aqupdgrizzly: Grizzly Bear mob 1.1.1
		architects_palette: Architect's Palette Fabric 1.2
		architectury: Architectury 2.0.16
		arfo: Artificial Foliage 1.3
		artifality: Artifality 0.2.4
		autoconfig1u: Auto Config v1 Updated 3.3.1
		bedspreads: Bedspreads 1.4.0-1.17
		betterdroppeditems: Better Dropped Items 1.3.0-1.17
		betternether: Better Nether 5.1.0
		biom4st3r_repackaged_expressions: expj4_repackaged 0.1.0
		bitsandchisels: BitsAndChisels 2.5.0
		blast: BLAST 1.6.2
		blue_endless_jankson: jankson 1.2.1
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.2.1-1.17
		caelus: Caelus API 0.0.16-1.17
		calio: Calio 1.0.1
		cardinal-components: Cardinal Components API 3.0.0
		cardinal-components-base: Cardinal Components API (base) 3.0.0
		cardinal-components-block: Cardinal Components API (blocks) 3.0.0
		cardinal-components-chunk: Cardinal Components API (chunks) 3.0.0
		cardinal-components-entity: Cardinal Components API (entities) 3.0.0
		cardinal-components-item: Cardinal Components API (items) 3.0.0
		cardinal-components-level: Cardinal Components API (world saves) 3.0.0
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 3.0.0
		cardinal-components-util: Cardinal Components API (utilities) 3.0.0
		cardinal-components-world: Cardinal Components API (worlds) 3.0.0
		carrier: Carrier 1.8.0
		castle_dungeons: Castle Dungeons 2.3-1.17-fabric
		caves-and-cliffs-add-on-for-william-wythers-overhauled-overworld: Caves and Cliffs add-on for William Wythers Overhauled Overworld 1.0
		charm: Charm 3.2.2
		charmonium: Charmonium 3.1.0
		cleancut: CleanCut 1.17-4.0-fabric
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 5.0.34
		clumps: Clumps fabric-1.17-7.0.0.2
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_flowpowered_flow-math: flow-math 1.0.3
		com_github_dimensionaldevelopment_poly2tri_java: poly2tri.java 0.1.1
		com_github_draylar_omega-config_omega-config: omega-config 1.0.8-1.17
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		comforts: Comforts 0.0.4-1.17
		companion_bats: Companion Bats 1.16.5
		conjuring: Conjuring 1.0.4
		creeperspores: Creeper Spores 1.6.0
		croptopia: Croptopia ${mod_version}
		dark-enchanting: Dark Enchanting 0.3.1-1.17
		dawn: Dawn API 2.0.3
		dazzle: Dazzle 2 1.0
		de_javagl_obj: obj 0.3.0
		dehydration: Dehydration 1.1.6
		dimdoors: DimensionalDoors 4.0.0+beta.2-11.06.2021
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.3
		doggomod: Doggo Mod 1.0.2
		dualwielding: Dual Wielding 1.0.6
		dynamicfps: Dynamic FPS 2.0.4
		earthtojavamobs: Earth2Java 1.7.1+1.17
		elytratrinket: Elytra Trinket 2.0.1-1.17
		emerald_tools: Emerald Tools 1.2.15
		enchant_giver: Enchant Giver 1.1.0
		enchantmentdescriptions: Enchantment Descriptions 3.0.11
		enhanced_mushrooms: Enhanced Mushrooms 1.0.4
		environmentz: EnvironmentZ 1.1.4
		expandedstorage: Expanded Storage 7.0.0-alpha.31
		extrakeybinds: ThatRobin's Extra Origins Keybinds 1.17-0.1.1
		extraorigins: Extra Origins 1.17-5
		fabric: Fabric API 0.36.0+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b44633d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d03d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea83d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b44633d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+a02b44633d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa3d
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b44633d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b44633d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da3103d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.10+a02b44633d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b44633d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c03d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa3d
		fabric-furnaces: Fabric Furnaces 2.0.1-1.17
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+a02b44633d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b44633d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab61213d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b4463a0
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e3d
		fabric-language-kotlin: Fabric Language Kotlin 1.6.2+kotlin.1.5.20
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b4463a0
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b44633d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa3d
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b44633d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.11+b7ab6121a0
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b44633d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa3d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab61213d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b44633d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b44633d
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee3d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.3+676f40fa3d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b44633d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b44633d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b44633d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b44633d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa3d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b44633d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab6121a0
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+198a96213d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b44633d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.11+e36969833d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b4463d5
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b44633d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab6121a0
		fabricloader: Fabric Loader 0.11.6
		fabricshieldlib: Fabric Shield Lib 1.3.5-21w05b
		fallflyinglib: FallFlyingLib 3.0.0-beta.2
		fallingleaves: Falling Leaves 1.7.0+1.17
		fallingtree: FallingTree 2.12.0
		fermion: Fermion 2.11.241
		fermion-modkeys: Fermion Modifier Keys 1.10.241
		fiber: fiber 0.23.0-2
		firstperson: FirstpersonModel ${version}
		flytre_lib: FlytreLib 0.2.18
		gateofbabylon: Gate Of Babylon 1.5.0-1.17
		geckolib3: Geckolib 3.0.6
		geodes: More Geodes 1.0.4
		givemehats: Give Me Hats! 1.6
		goat: Goat origin 1.0.0
		golemsgalore: Golems Galore 1.0.2+mc.1.17
		grindenchantments: Grind Enchantments 1.2.1+1.17
		haema: Haema 1.7.2
		impaled: Impaled 1.0.1
		incantationem: Incantationem 1.1
		inventoryhud: Inventory HUD + 3.3.2
		inventorysorter: Inventory Sorter 1.7.9-1.17
		ironbundles: Iron Bundles 1.0.2+20w51a
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		kirin: Kirin UI 1.8.7-1.17
		kyrptconfig: Kytpt Config 1.1.10-1.17
		lacrimis: Lacrimis 2.1.1+1.17
		lambdabettergrass: LambdaBetterGrass 1.2.0+1.17
		lambdynlights: LambDynamicLights 2.0.1+1.17
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.0.0+1.17
		libninepatch: LibNinePatch 1.1.0
		lithium: Lithium 0.7.2
		maelstrom_library: Maelstrom Library 1.2.1-1.17
		magick: Magick: Potions and Pearls 1.0.1
		magna: Magna 1.5.5-1.17-pre4
		matrix: Matrix 1.0.0
		maybe-data: Maybe data 1.0.1-1.17
		mcda: MC Dungeons Armors 1.6.4
		mcdar: MC Dungeons Artifacts 1.3.0
		mcdw: MC Dungeons Weapons 3.2.2-1.17
		medievalweapons: Medieval Weapons 1.1.5
		megane: megane 5.0.0
		megane-base: megane-base 5.0.0
		megane-runtime: megane-runtime 5.0.0
		megane-vanilla: megane-vanilla 5.0.0+1.17
		minecraft: Minecraft 1.17
		moborigins: Mob Origins 1.5.0
		modmenu: Mod Menu 2.0.2
		moenchant_lib: Mo'Enchantment Library 0.1.1
		moenchantments: Mo'Enchantments 1.17.4
		monsters_in_the_closet: Monsters in the Closet 1.0.2+1.17
		mooblooms: Mooblooms 1.5.0
		more-structures-add-on-for-william-wythers-overhauled-overworld: More Structures add-on for William Wythers Overhauled Overworld 1.1
		moreberries: More Berries 1.4.2
		morevillagers-fabric: MoreVillagersFabric 2.0.1-SNAPSHOT
		mostructures: Mo' Structures 1.2.1-1.17
		mousewheelie: Mouse Wheelie 1.7.3+mc1.17-rc1
		multipart_entities: MultipartEntities 1.1.2-1.17
		myron: Myron 1.6.0
		newcaves: New Caves 2.1
		notenoughanimations: NotEnoughAnimations 1.3.0
		npcvariety: NPC Variety 2.1.0
		nyfsquivers: Nyf's Quivers Fabric-0.2.2
		omega-config: OmegaConfig 1.0.8
		onsoulfire: On Soul Fire 1.17-1
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.20
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.1
		org_jgrapht_jgrapht-core: jgrapht-core 1.1.0
		origins: Origins 1.0.2
		origins-classes: Origins: Classes 1.2.1
		owo: OwO 0.1
		particle_emitter_biom4st3r: Particle Emitters LIB 0.1.0
		particlerain: Particle Rain 1.3.1
		patchouli: Patchouli 1.17-54-FABRIC
		pehkui: Pehkui 2.2.1+1.14.4-1.17
		pigsteel: Pigsteel Mod 1.6.3
		playerabilitylib: Pal 1.3.0-nightly.1.17-rc1
		powershot: Powershot 1.2.0-1.17-fabric
		presencefootsteps: Presence Footsteps r31-1.17-rc1
		puddles: Puddles 1.1.0
		quartzelv: Quartz Elevator 1.2.3
		quickshulker: Quick Shulker 1.1.14-1.17
		rangers_haven: Ranger's Haven 2.2.1
		ratsmischief: Rat's Mischief 1.1.3
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		respawnablepets: Respawnable Pets 1.17-1
		rightclickharvest: Right Click Harvest 1.3.0
		roughlyenoughitems: Roughly Enough Items 6.0.260-alpha
		runelic: Runelic 2.0.5
		rusted-iron: Rusted Iron 21w01a-1.0.1
		satin: Satin 1.6.0-nightly.1.17-pre3
		seasons: Fabric Seasons 1.2.2-BETA+1.17
		seedy-behavior: Seedy Behavior 1.0.1
		shulkerutils: shulkerutils 1.0.1-1.17
		sit: Sit 1.17-12
		somnus: Somnus API 0.0.12-1.17
		spruceui: SpruceUI 3.2.0+1.17
		stacc: Stacc 1.0.1
		staffofbuilding: Staff of Building 1.3.0-1.17
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		stoneholm: Stoneholm 1.2.7
		structurized: Structurized 1.3.0
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.4
		terrarianslimes: Terrarian Slimes 1.1-BETA+1.17
		the_bumblezone: The Bumblezone - Fabric 1.17-3.0.3-fabric
		things: Things 0.2.1
		toolstats: Tool Stats 2.0.1
		toomanyorigins: TooManyOrigins 0.1.3b
		transliterationlib: TRansliterationLib 1.1.0
		trinketofundying: Trinket of Undying 2.0.0-1.17
		trinkets: Trinkets 3.0.0
		trinketshulkerboxes: Trinket Shulker Boxes 2.0.0-1.17
		tweed: Tweed 3.0.0-beta.26
		universal_ores: Universal Ores 1.0
		upgradedechests: Upgraded Ender Chests 1.0.1-1.17
		urns: Urns 1.0.0
		vanilla-hammers: Vanilla Hammers 3.1.1-1.17
		veinmining: Vein Mining 0.0.10-1.17
		villagernames: Villager Names 2.0.0
		voicechat: Simple Voice Chat 1.17-1.2.4
		voidz: VoidZ 1.0.3
		wandering_collector: Wandering Collector 1.0.2+mc1.17
		waystones: Waystones 2.0.1
		wildfire_gender: Wildfire's Female Gender Mod 2.6.1
		william-wythers-overhauled-overworld: William Wythers Overhauled Overworld 1.3
		winged: Winged Mod 1.17-3.0.0-beta.2
		witherite: Witherite 0.0.5
		wolveswitharmor: Wolves With Armor 1.6.0-1.17
		wrenchable: Wrenchable 1.1.0+1.17
		wthit: wthit 3.6.1
		xaerominimap: Xaero's Minimap 21.12.2
		xlpackets: XLPackets 1.1
	Launched Version: fabric-loader-0.11.6-1.17
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

**Comment by warjort** [comment]
````
Suppressed: java.lang.NoSuchFieldError: APOLI_IDENTIFIER
at com.archecraft.minecraft.acorigins.registry.ACOPowers.init(ACOPowers.java:79)
at com.archecraft.minecraft.acorigins.ACOrigins.onInitialize(ACOrigins.java:19)
````

You should report this to the archecraft/ACOrigins mod (assuming you have the correct/latest version of that mod).

**Comment by liach** [comment]
You are using a 1.16 mod for 1.17. `class_5548` is old copper block class.
