### ISSUE TITLE
ArmorRenderingRegistry missing in 1.17

### ISSUE THREAD

**Issue by quiqueck** [FabricMC/fabric#1532]
The `ArmorRenderingRegistry` is missing in **fabric-rendering-v1**.

**Comment by shedaniel** [comment]
Correct, it was merged to 1.16.5 but not 1.17 of Fabric API, drafting a PR...

**Comment by AzureDoom** [comment]
> Correct, it was merged to 1.16.5 but not 1.17 of Fabric API, drafting a PR...

so about that PR? Geckolib needs it for doing it's Armor.

**Comment by Aelpecyem** [comment]
Any progress on this? I was considering drafting a PR by myself otherwise

**Comment by K0-RR** [comment]
I think this can be closed now.

**Comment by Technici4n** [comment]
Implemented by #1607.
