### ISSUE TITLE
I keep getting this error

### ISSUE THREAD

**Issue by Tr1ckstr** [FabricMC/fabric#1535]
I've been trying to download some mods for cool survival stuff ok yh
Whenever I was almost done, I got this message 
![image](https://user-images.githubusercontent.com/66033914/124327237-09b7ae80-db88-11eb-8897-b3db64f1f6b7.png)
Anyone know a fix?

**Comment by Technici4n** [comment]
You installed a mod (called `fab`) that requires Minecraft 1.17, and apparently you are not on Minecraft 1.17.
