### ISSUE TITLE
fabric wont lauch

### ISSUE THREAD

**Issue by gudmelademad** [FabricMC/fabric#1542]
when i try lauching my fabric mod it sends this message 
Could not find required mod: notenoughmilk requires {fabric @ [*]}
and i have tryed evrything i can but it wont work. please help

**Comment by frqnny** [comment]
You need to install Fabric API mod

**Comment by Technici4n** [comment]
(Can be found there: https://www.curseforge.com/minecraft/mc-mods/fabric-api).
