### ISSUE TITLE
Could not find required mod: iris requires {minecraft @ [1.17 || 1.17-rc.2]}

### ISSUE THREAD

**Issue by cedarRed123** [FabricMC/fabric#1544]
ive tried so many different fabric apis does anyone know the right one for 1.17.1 w sodium

**Comment by arm32x** [comment]
That error message says that Iris requires Minecraft 1.17 (not 1.17.1). Is there a newer version of Iris available?

**Comment by cedarRed123** [comment]
> That error message says that Iris requires Minecraft 1.17 (not 1.17.1). Is there a newer version of Iris available?

Ohhh ok gotcha, there isnt im pretty sure ill just wait for the update

**Comment by liach** [comment]
They did just carry out a patch that allow them to run on 1.17.1 as well. Feel free to check that out. https://github.com/IrisShaders/Iris/pull/480
