### ISSUE TITLE
DecoderException: java. util.zip.DataFormatException: incorrect header check

### ISSUE THREAD

**Issue by Howie0715** [FabricMC/fabric#1558]
I start a new server, and only install fabric api 0.36.1,it's show the error message (DecoderException: java. util.zip.DataFormatException: incorrect header check)

**Comment by Technici4n** [comment]
Please try reinstalling fabric api, this looks like a corrupt jar. Then if it still doesn't work please send the full log.

**Comment by Howie0715** [comment]
[latest.log](https://github.com/FabricMC/fabric/files/6805326/latest.log)
(update to 0.37.0 )

**Comment by Olexorus** [comment]
Can confirm, had the same issue when updating my server from 1.17 to 1.17.1, I made sure everything was up to date about three times (that was on Sunday). Had to switch to Vanilla for now. Interestingly it didn't happen on my local test server, even though I have the same Fabric version and mods there.

**Comment by Howie0715** [comment]
> Can confirm, had the same issue when updating my server from 1.17 to 1.17.1, I made sure everything was up to date about three times (that was on Sunday). Had to switch to Vanilla for now. Interestingly it didn't happen on my local test server, even though I have the same Fabric version and mods there.

Same, my local connection (in same device) everything correct.

**Comment by wh0oo** [comment]
I had this issue as well.   I fixed it by removing the .fabric directory in your main minecraft directory

**Comment by Olexorus** [comment]
> 
> 
> I had this issue as well. I fixed it by removing the .fabric directory in your main minecraft directory

Thank you so much, that seems to have fixed it for me :D

**Comment by Technici4n** [comment]
Mind explaining what steps you used to update your server so it can be reproduced by us? This is likely an issue with the way the upgrade happened (possibly a fabric issue).
