### ISSUE TITLE
I'm getting "Could not find required mod: requiem requires {cardinal-components-base @ [^2.7.0]}" on Fabric Loader

### ISSUE THREAD

**Issue by Averyu2** [FabricMC/fabric#1559]
I'm getting "Could not find required mod: requiem requires {cardinal-components-base @ [^2.7.0]}" when trying to play "fabric-loader-1.17". It's fabric-loader-0.1.6-1.17.1-pre1 
![snip](https://user-images.githubusercontent.com/41842054/125231292-7ded0300-e2a8-11eb-8dba-d940c030c0ea.png)

**Comment by SpinnyBoiii** [comment]
https://www.curseforge.com/minecraft/mc-mods/cardinal-components

**Comment by Technici4n** [comment]
Yeah, this error means that you need to install cardinal components.

**Comment by Averyu2** [comment]
i have put the mod in the mods folder. I get this:
![Capture](https://user-images.githubusercontent.com/41842054/125362862-9ce9a480-e33d-11eb-902c-7fdb51c296f3.PNG)

**Comment by Averyu2** [comment]
i have just installed an updated version of "Cardinal Components" to 1.17. And now I'm getting the same error message as the one before that says i require the mod. even though i installed it.

**Comment by Juuxel** [comment]
Requiem hasn't been updated to 1.17 yet, at least from what I can see on Curseforge.

The error messages are from Requiem wanting the 1.16 version of Cardinal Components, which doesn't run on MC 1.17. It looks like you still have to wait for a 1.17 update of Requiem.

**Comment by Averyu2** [comment]
I just installed the brand new version of "Fabric-Loader-1.17.1"

**Comment by Averyu2** [comment]
same error message. im guessing you were right..
