### ISSUE TITLE
The licence seems to use boilerplate name and year of copyright

### ISSUE THREAD

**Issue by micnekr** [FabricMC/fabric#1563]
The document [here](https://github.com/FabricMC/fabric/blob/master/LICENSE) seems to be using the default placeholder values, e.g. on line 189, `Copyright {yyyy} {name of copyright owner}`

**Comment by Juuxel** [comment]
It is the sample header template that is not supposed to be modified in the license itself. If you read a bit further above, it says:

> To apply the Apache License to your work, attach the following boilerplate notice, with the fields enclosed by brackets "{}" replaced with your own identifying information.

The placeholder fields are replaced in the [actual header](https://github.com/FabricMC/fabric/blob/1.17/HEADER) that is applied with licenser.

**Comment by micnekr** [comment]
I am sorry for opening this issue, I thought that the text meant replacing the text of the license itself.
