### ISSUE TITLE
Can it support Spigot or Craftbukkit ？

### ISSUE THREAD

**Issue by molehzy** [FabricMC/fabric#157]
I want to add some funny plugins in my server

**Comment by asiekierka** [comment]
Debatable. I'm looking into it, but no promises yet.

**Comment by liach** [comment]
Uh, why close. Fabric loader can support spigot already, but fabric cannot yet.

**Comment by asiekierka** [comment]
Because it's the wrong repo.

Fabric API's Spigot support issues will be for individual crashes.

Fabric Loader's Spigot support is in a private branch and very preliminary, and it has to be added there first.
