### ISSUE TITLE
Feature Request: Render distances past 32 chunks

### ISSUE THREAD

**Issue by SirPytan** [FabricMC/fabric#1586]
I am not sure if this is the right place to ask for it, else move or create a new request at the right git repo.

Since there get so many performance improving mods developed for fabric, it would be a shame, if we can't take advantage of the extra frames we get to increase the render distance of minecraft with fabric past the 32 chunks line. A max of 64 chunks would be enough for the beginning, but in general it would be cool to set it to what ever amount your pc can handle.

I have heard that it is hard coded, but it would be nice if a skilled java developer would be able to extend the limit and take care of that. I and probably a lot of people would be very thankful for that.

**Comment by haykam821** [comment]
You can use [GitHub Discussions](https://github.com/FabricMC/fabric/discussions) or the [Fabric Discord's #requests channel](https://discord.gg/v6v4pMv) for ideas like these. Overarching rendering changes are considered out of scope for Fabric API.

**Comment by SirPytan** [comment]
@haykam821 Why is that out of scope of the Fabric API and who would I need to ask for that feature, or which person or team would be able to or responsible of changing/extending it?

**Comment by frqnny** [comment]
Fabric API is for compat and basic utilities between mods, not feature changes

**Comment by SirPytan** [comment]
Ok, but does someone know a fabric mod that extends the render distance?

**Comment by Lentern** [comment]
its called options.txt

**Comment by Player3324** [comment]
This is out of scope for Fabric API, please see https://github.com/FabricMC/fabric/discussions/1587 for further discussion.
