### ISSUE TITLE
I can't join my vanilla fabric server

### ISSUE THREAD

**Issue by UndeadKitten** [FabricMC/fabric#1595]
https://gist.github.com/UndeadKitten/b353010dc15f887b18361d83463fe900

I was able to join my FabricMC server 2 days ago, but now I can't.
I'm able to host and join Forge and PaperMC servers, as well as public servers.
I restarted my computer and my modem to no avail.

**Comment by modmuss50** [comment]
The version of fabric-networking-api-v1 installed on the server is for 1.17 not 1.17.1. I assume one of your mods is including it. Also installing fabric api from: https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3398557 should fix it.

**Comment by UndeadKitten** [comment]
That fixed it, thank you!
