### ISSUE TITLE
Fabric Mod crashing minecraft 1.16.5

### ISSUE THREAD

**Issue by DanKhon** [FabricMC/fabric#1598]
I downloaded fabric minecraft 1.16.5, the mod loader is 1.16.5, and my mod is for 1.16.5, but whenever I put my mod and the fabric 1.16 api in the mods folder, and try to run minecraft, it just crashes

**Comment by DanKhon** [comment]
the mod works in the development enviornment but not in the actual minecraft

**Comment by K0-RR** [comment]
You realize nobody is able to help you if you don't include any logs, right?

**Comment by DanKhon** [comment]
there are no crash logs

**Comment by DanKhon** [comment]
minecraft literally just shuts down with no logs, heres all that was left

this is all of the log: [13:18:22] [main/INFO]: Loading for game Minecraft 1.16.5
[13:18:22] [main/INFO]: [FabricLoader] Loading 51 mods:
	- fabric@0.37.1+1.16
	- fabric-api-base@0.3.0+c88702897d
	- fabric-api-lookup-api-v1@1.2.0+6aebe11a7d
	- fabric-biome-api-v1@3.1.10+3661eaa17d
	- fabric-blockrenderlayer-v1@1.1.5+ca58154a7d
	- fabric-command-api-v1@1.1.2+95b14da07d
	- fabric-commands-v0@0.2.2+ca58154a7d
	- fabric-containers-v0@0.1.11+9354966b7d
	- fabric-content-registries-v0@0.2.1+ca58154a7d
	- fabric-crash-report-info-v1@0.1.3+ca58154a7d
	- fabric-dimensions-v1@2.0.6+61336ba97d
	- fabric-entity-events-v1@1.1.0+c88702897d
	- fabric-events-interaction-v0@0.4.3+f941baf07d
	- fabric-events-lifecycle-v0@0.2.1+ca58154a7d
	- fabric-game-rule-api-v1@1.0.6+ca58154a7d
	- fabric-item-api-v1@1.2.1+ca58154a7d
	- fabric-item-groups-v0@0.2.7+2868a2287d
	- fabric-key-binding-api-v1@1.0.4+9354966b7d
	- fabric-keybindings-v0@0.2.1+ca58154a7d
	- fabric-lifecycle-events-v1@1.2.1+ca58154a7d
	- fabric-loot-tables-v1@1.0.2+ca58154a7d
	- fabric-mining-levels-v0@0.1.3+ca58154a7d
	- fabric-models-v0@0.3.0+bc7a746f7d
	- fabric-networking-api-v1@1.0.3+e3c9d0627d
	- fabric-networking-blockentity-v0@0.2.8+ca58154a7d
	- fabric-networking-v0@0.3.2+ca58154a7d
	- fabric-object-builder-api-v1@1.9.5+c88702897d
	- fabric-object-builders-v0@0.7.2+ca58154a7d
	- fabric-particles-v1@0.2.4+ca58154a7d
	- fabric-registry-sync-v0@0.7.4+ca58154a7d
	- fabric-renderer-api-v1@0.4.4+f3e8589e7d
	- fabric-renderer-indigo@0.4.4+ca58154a7d
	- fabric-renderer-registries-v1@2.3.0+2868a2287d
	- fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d
	- fabric-rendering-fluids-v1@0.1.13+ca58154a7d
	- fabric-rendering-v0@1.1.2+ca58154a7d
	- fabric-rendering-v1@1.6.0+2868a2287d
	- fabric-resource-loader-v0@0.4.7+6afaa13c7d
	- fabric-screen-api-v1@1.0.0+c045166c7d
	- fabric-screen-handler-api-v1@1.1.5+9354966b7d
	- fabric-structure-api-v1@1.1.11+ca0ef93d7d
	- fabric-tag-extensions-v0@1.1.1+ca58154a7d
	- fabric-textures-v0@1.0.6+ca58154a7d
	- fabric-tool-attribute-api-v1@1.2.7+8183d3957d
	- fabric-transfer-api-v1@1.0.0+5f6b94517d
	- fabricloader@0.11.6
	- java@8
	- lithium@0.6.4
	- minecraft@1.16.5
	- phosphor@0.7.1+build.11
	- sodium@0.1.0
[13:18:22] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/16692/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.9.4+mixin.0.8.2/sponge-mixin-0.9.4+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT

**Comment by warjort** [comment]
Do you have anything in a crash-reports folder?

Does it load with just fabric-api installed?
If it does, try adding each mod individually until you find the problem mod.

**Comment by warjort** [comment]
You might also want to post your issue here (the actual mod loader):
https://github.com/FabricMC/fabric-loader/issues

This area is for the modding api.

**Comment by Technici4n** [comment]
You should ask on discord for these kinds of practical problems.
