### ISSUE TITLE
API to allow for adding additional Creative Tabs

### ISSUE THREAD

**Issue by therealfarfetchd** [FabricMC/fabric#16]
Vanilla MC can only handle 12 creative tabs (the already existing ones). There's no support for additional ones, which a lot of mods will surely want to add.

Implementing the logic should be relatively easy, there needs to be a method to create a new ItemGroup which also resizes the ItemGroup.GROUPS array (it's only 12 in size by default) to allow storing the newly created group. That _should_ be everything that's needed to get this part to work.

Creative inventory UI will be a bit more difficult. There's a couple approaches I've thought of that can be taken:

 - The Forge approach:
Just add two buttons that switch between the creative tabs currently displayed, like Forge does. This is kind of ugly imo, since the two buttons don't fit into the rest of the GUI.

- Scroll bar:
Move all the creative tab buttons (except search & inventory ones) into a list on one side of the inventory gui, and add a scroll bar to it. This would look way nicer, and would be more user friendly in my opinion (dragging the mouse lets you scroll way faster to search for a tab than clicking a button a gajillion times, depending on how many mods are installed). Something like [this](https://i.imgur.com/IPSqPn2.png) would do the trick, I think. (I haven't moved the three tabs that are special, the search, saved items, and player inventory tab, these could either stay where they are, move to either the top or bottom completely, or just get added into the list too, which would probably be the easiest to handle.)

Thoughts? :P

**Comment by modmuss50** [comment]
2 Buttons - Is good as it would be easy to implement, but as you said it is ugly and not very user friendly.

Scroll - That screenshot looks really good! And I feel like it doesn't move too far away from vanilla MC. One thing I would suggest is to default back to vanilla when there are no extra item groups added. I think keeping the 3 special buttons as is its fine.

**Comment by Prospector** [comment]
I think the API should exist in Fabric but the GUI shouldn't be included. Similar to Mod Menu, different mods could have their own takes on ways to display the tabs.

**Comment by therealfarfetchd** [comment]
But then you'd have to install a mod just to make it display more tabs than the default, which you almost always want unless you don't have mods installed that add blocks/items. I'd prefer modmuss's suggestion - displaying the original tab layout, in case they fit.
Of course, other mods can always override the GUI if they want, just like they can in Forge, but there should be a reasonable default implementation

**Comment by modmuss50** [comment]
Unlike mod menu there can only be one creative gui, I understand what you are saying however. Once option would be to have the API for adding new creative tabs, and possibly a default implementation in fabric, and then a way to allow other mods to come in and replace it. 

Im not sure if this is over-complicating it however. 

The creative GUI is something that all mods that add a block or item usually use so having an built in solution might come in handy.

**Comment by Prospector** [comment]
Ok, Fabric should have an API method to revert the GUI to vanilla then IMO and I would be fine with that.

**Comment by Lemonszz** [comment]
I agree with having an overrideable default implementation. IMO it should be as close to vanilla as possible (The two button version).

**Comment by modmuss50** [comment]
Yeah, one other idea would be to have a basic forge like version with the two button that just adds to the creative tab, and then have the fancy version as a separate mod. By the sounds of it this would be the preferred idea.

**Comment by therealfarfetchd** [comment]
The two button one is annoying to use though and looks less vanilla/more out of place than the one I made (of course, I wouldn't say no to different suggestions for how it could look :P)

**Comment by Prospector** [comment]
What about sub-categories under the existing vanilla ones? The vanilla kinda covers most themes already... sub-categories could fix the massive amount of items in each

**Comment by Lemonszz** [comment]
I agree it looks good but if there's no mods that add a tab, the layout should be identical to vanilla.

**Comment by therealfarfetchd** [comment]
> What about sub-categories under the existing vanilla ones? The vanilla kinda covers most themes already... sub-categories could fix the massive amount of items in each

Interesting idea, how would you handle mods whose items don't fit under one of the existing tabs, like some tech mod, though? Let's take IC2 for example, the closest I would put it under would be Redstone, but that doesn't quite fit in most cases. Or have this as an addition, because this would also fix some mods having like 4 tabs for each category of their items, instead they could just have one tab and some subcategories instead, so they take up less space overall. And then just have a small dropdown arrow that pops up a list with clickable subcategories or something.

This might take it a bit too far though, because in addition to rendering code, more logic code would have to be added to allow for this ;)
Might not be too bad though, idk

> I agree it looks good but if there's no mods that add a tab, the layout should be identical to vanilla.

Yeah, I agree with that, because if they all fit, the existing one is actually easier to use since you don't have to scroll at all

**Comment by RedstoneParadox** [comment]
I think that a default implementation should be fine provided that there are hooks for mods to replace it with their own, or at the very least make it friendly to Mixins.

**Comment by modmuss50** [comment]
I think sub categories might not be the best idea (in another add on possibly) this is because right now its easy to add your item to any creative tab, the methods are already there. Adding sub categories would require a whole new api.

Categories might be great for a mod pack maker who has the time and energy to go though and put stuff into them.

**Comment by modmuss50** [comment]
See #44

**Comment by Boundarybreaker** [comment]
@asiekierka I think this can be closed

**Comment by asiekierka** [comment]
Indeed.
