### ISSUE TITLE
Where is the source of fabricmc.net/versions.html?

### ISSUE THREAD

**Issue by K0-RR** [FabricMC/fabric#1608]
When this website URL was https://modmuss50.me/fabric.html a link to the source was displayed at the bottom https://github.com/modmuss50/fabric-versions/commit/798cda656031f4f78773a803e257932f2e3a3bbb.

**Comment by modmuss50** [comment]
Inspect element gives you the source. my repo is woefully out of date as we just kept editing it on the server. A better page will come at somepoint.

**Comment by K0-RR** [comment]
Ah, I understand.
