### ISSUE TITLE
Separate mod keybinds from vanilla options

### ISSUE THREAD

**Issue by Madis0** [FabricMC/fabric#161]
_Not sure if this is related to API or loader, assuming the former._

When Fabric loads the mods, default keybind values are appended to `options.txt`. The user can change them (or any other setting) and they are saved properly.

Now, if a non-Fabric client (e.g. vanilla) runs the in the same folder and changes any setting, the Fabric keybinds will get removed from the file, presumably because they are unknown to the client. To user, it means that any modified keybinds are reset when next launching the Fabric profile.

I propose it can be solved like Optifine does - just a separate file like `optionsof.txt`.

**Comment by asiekierka** [comment]
That's actually non-trivial due to the way we currently store the keybinds - by appending them to the list used for saving them in the first place!

**Comment by Prospector** [comment]
Personally I think it'd be good to have an `options` folder which mods can use—sorta like the config folder—but to store client-side options

**Comment by UpcraftLP** [comment]
This has been implemented in https://github.com/FabricMC/fabric/commit/7dfef87c3a83d0535eeb3452900b7f773a62de76

**Comment by Technici4n** [comment]
Probably not something we will ever fix, running a vanilla client in a modded instance folder is generally a bad idea.
