### ISSUE TITLE
Registry remapping failed

### ISSUE THREAD

**Issue by pnot0-alt** [FabricMC/fabric#1612]
So i was trying to play a modpack with my friend on curseforge using fabric, it was Better Minecraft and when i tried to log in his minecraft server a error occured 
![Screenshot_1](https://user-images.githubusercontent.com/88410663/128102831-320cadd8-3730-46af-b4bf-fb6112adb555.png)
I tried looking around for a solution but no find, any help is appreciated!

**Comment by liach** [comment]
You need to install an up-to-date notforgotten mod on your side; most likely you are using an outdated version that lacks these new items.
