### ISSUE TITLE
Whevenver I try adding Sodium to Origins, it says my game crashed

### ISSUE THREAD

**Issue by QuadraticFormulas** [FabricMC/fabric#1619]
So my PC isn't the greatest and i get really low fps, so I tried downloading Sodium to it. When I run minecraft, it says my game crashed and a message appears saying, "The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'imm_ptl_core'!
Exit Code: -1"
I'm not sure what I'm doing wrong, but here is my crash report

[minecraft crash report.txt](https://github.com/FabricMC/fabric/files/6947222/minecraft.crash.report.txt)

**Comment by warjort** [comment]
Not a Fabric issue, the answer is in your crash report:

````
Caused by: java.lang.RuntimeException: The sodium version that you use is incompatible with Immersive Portals. Check https://github.com/qouteall/sodium-fabric/releases
````
