### ISSUE TITLE
[MultiMC] Fabric crashes on clinet startup

### ISSUE THREAD

**Issue by qu4rk** [FabricMC/fabric#162]
I am using the latest version of Fabric, and when I try to launch Minecraft i get this error:

[https://pastebin.com/B2cjktns](https://pastebin.com/B2cjktns)

This happens whenever I try to load a mod.

**Comment by asiekierka** [comment]
Fabric API is missing, and the mod did not declare a dependency on it. Tell the mod author to fix this, you can link them to the issue.
