### ISSUE TITLE
Could not find required mod: fabric requires {minecraft @ [~1.17.1-rc]}

### ISSUE THREAD

**Issue by VeinSX** [FabricMC/fabric#1627]
So, My isue is that i am trying to lounch McFabric but this isue comes up
I use mainly optimize Mods and when i add them this Comes up and when i dont it works Just Fine!
Yes i use the Correct Fabric Version and the Correct Fabric API.
Could any one help me?

**Comment by Juuxel** [comment]
You're using a Fabric API version meant for Minecraft 1.17 on a different Minecraft version. You can download the correct Fabric API version [here](https://www.curseforge.com/minecraft/mc-mods/fabric-api).

**Comment by VeinSX** [comment]
Thx
