### ISSUE TITLE
[OptiFine] (Reflector) Field not found: World.tileEntitiesToBeRemoved 

### ISSUE THREAD

**Issue by VeinSX** [FabricMC/fabric#1628]

**Comment by VeinSX** [comment]
Any sugestions what is this Coused by?

**Comment by warjort** [comment]
This area is for bug reports of the fabric api.
It is not the Optifine or any other help forum.
Try the discord, or the discussions tab but you are going to need to post a lot more than one line of an error message out of context.

**Comment by VeinSX** [comment]
ok Thanks
