### ISSUE TITLE
The game crashed whilst unexpected error Error: java.lang.NoSuchMethodError: 'void com.mojang.blaze3d.systems.RenderSystem.color4f(float, float, float, float)' Exit Code: -1

### ISSUE THREAD

**Issue by VeinSX** [FabricMC/fabric#1630]
The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: 'void com.mojang.blaze3d.systems.RenderSystem.color4f(float, float, float, float)'
Exit Code: -1

So, i think This is Caused by Optifine but i have no idea why!
What/When it hapens:
it hapens when i try to load in to a new Server or in to a Game (like on Hypixel bed wars or smt like this)!

Could any one Help me?

**Comment by VeinSX** [comment]
This hapens whith
preview_OptiFine_1.17.1_HD_U_G9_pre32

But when i use
preview_OptiFine_1.17.1_HD_U_G9_pre33
It dose not even Load

**Comment by Technici4n** [comment]
We don't support optifine.
