### ISSUE TITLE
[1.17] Creating a custom RenderLayer is high-friction

### ISSUE THREAD

**Issue by williewillus** [FabricMC/fabric#1635]
`RenderLayer.of` was made package-private in 1.17 (and its overload was made private).

Furthermore, because the return type is unnameable, an AW is required if you wanted to use an accessor to invoke it.

This is a lot of hassle for every single mod that does any sort of complex rendering, so I think Fabric API probably should have a call for this.

**Comment by modmuss50** [comment]
This sounds like another great opportunity for global access wideners.
