### ISSUE TITLE
I cant install the new fabric api update because it apparently contains virusses

### ISSUE THREAD

**Issue by NxstyKxng** [FabricMC/fabric#1645]

**Comment by modmuss50** [comment]
What anti virus are you using? Where did you download the file from? What version?

**Comment by Psybercop** [comment]
I'm Having the same issue.  Windows Defender and Curseforge.   Keeps coming up as Trojan:Script/Wacatac.B!ml, fabric-api-0.38.0+1.17.jar

**Comment by modmuss50** [comment]
I have sumbitted the file to Microsoft for false positivie analysis, not much more I can do.

**Comment by Psybercop** [comment]
Thanks

**Comment by modmuss50** [comment]
This seems to have passed over now. 👍
