### ISSUE TITLE
In fabric-api 0.38.0, a dropper deletes shulkerboxes when attempting to drop them into another shulkerbox

### ISSUE THREAD

**Issue by Tsolval** [FabricMC/fabric#1646]
As specified in the title, having a dropper attempt to move a shulker box from its inventory into a shulker deletes the contained shulkerbox (and all its contents).  If I had to guess, I'd say that the dropper attempts to insert the contained shulkerbox into the target shulkerbox, fails (properly), and then deletes the contained shulkerbox as if it succeeded.  

Changing the mod back to Fabric-api 0.37.2 fixes the issue and the shulkerbox remains in the dropper container.

**Game**
Minecraft Version: 1.17.1

**Launcher**
Fabric Launcher Version: 0.11.6

**Mods**
Fabric-api 0.38.0

**Steps to Recreate**
1. Create a new fabric server with minecraft 1.17.1 and fabric-api 0.38.0
1. Make a new Creative world.
1. Place a dropper facing into an empty shulkerbox
1. Put a button on the dropper
1. Place another shulkerbox (empty or with contents, does not matter) into the dropper's inventory
1. Activate the dropper with the button

**Expected**
Dropper fails to insert the contained shulkerbox into the placed shulkerbox and dropper still contains the shulkerbox.

**Actual**
Dropper fails to insert the contained shulkerbox into the placed shulkerbox and dropper no longer contains the shulkerbox.

**Comment by Technici4n** [comment]
Many thanks for reporting this, I'll have a look in a bit. This is probably a consequence of #1553.

**Comment by modmuss50** [comment]
@Technici4n please ping me when you have a fix for this so we can get a hotfix out ASAP, this is quite critical.

**Comment by modmuss50** [comment]
Tested and fixed, going to release a new build now. Thanks for reporting and thanks @Technici4n for the fix.
