### ISSUE TITLE
Could not find required mod: fabric requires {java @ [>=16]}

### ISSUE THREAD

**Issue by patrickissa** [FabricMC/fabric#1654]
![1](https://user-images.githubusercontent.com/3579214/130329850-8c3a696b-7516-4b93-bfe9-1d0957583baa.png)
![2](https://user-images.githubusercontent.com/3579214/130329851-46423357-ea3c-4289-a733-cde94aef17b9.png)
![3](https://user-images.githubusercontent.com/3579214/130329852-fd13f31d-52b1-408e-adb8-54c8ee3c706c.png)

this a picture of everything related to  it anyone got any idea

**Comment by Technici4n** [comment]
Make sure you have a java 16 install on your computer, then select it by clicking on `Auto-detect` (like in your last picture).

For example (this is for my laptop) you should pick the third one (you can see in the version that it's java 16):
![image](https://user-images.githubusercontent.com/13494793/130330232-51f3ca75-8b6a-4a8d-a8f2-648d7e7900e0.png)

**Comment by patrickissa** [comment]
oh just download [https://www.oracle.com/java/technologies/javase-jdk16-downloads.html](url)
