### ISSUE TITLE
[1.16.5] Mod compile failed with Java 8

### ISSUE THREAD

**Issue by zlainsama** [FabricMC/fabric#1659]
Mod compile using Java 8 fails with 'org/eclipse/core/runtime/IAdaptable has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0'

I was updating one of my mods.
https://github.com/zlainsama/PeacefulSurface/runs/3397747492?check_suite_focus=true

**Comment by Juuxel** [comment]
You need to update Loom to a newer version which bundles Java 8 versions of these Eclipse libraries (or use up-to-date java). The last java 8 version of Loom is `0.7-SNAPSHOT` (the newer ones, 0.8 and 0.9, require java 16 like MC 1.17+).

**Comment by modmuss50** [comment]
This can also be worked around by ensuring fabric’s maven is first.
