### ISSUE TITLE
Give more information on registry remap failed

### ISSUE THREAD

**Issue by Blayyke** [FabricMC/fabric#167]
Currently when the server has mods the client does not have (or the other way around), fabric will throw a RemapException:
[19:40:19] [main/ERROR]: Registry remapping failed!
net.fabricmc.fabric.impl.registry.RemapException: Received ID map contains IDs unknown to the receiver!

with a stacktrace. However, it does not indicate what mods are missing / what IDs were missing. It would be very useful for finding out issues / mismatched mods if fabric could log the differences between the two ID maps.

**Comment by asiekierka** [comment]
Already implemented in 0.3.0-pre; just not released yet.
