### ISSUE TITLE
Fabric API causes datapack custom dimensions to only load a single biome.

### ISSUE THREAD

**Issue by Pundus** [FabricMC/fabric#1675]
(I am working on a datapack for a server, with server-side only Fabric mods.)

Loading the server with the Fabric API included causes my datapack's custom dimensions to not load correctly; the worldgen and mob spawns are correct, but the biome listed in F3 and the visual effects do not work.

It used to work correctly when I was developing the server in the 1.17 snapshot 21w14a (with API version 0.32.7).

![2021-08-27_21 57 02](https://user-images.githubusercontent.com/52001632/131142948-2c21e4bd-5cd2-4a24-8d6c-980ab8397749.png)

**Comment by warjort** [comment]
You don't say what version of fabric api you are using, there is a recent fix in this area:
https://github.com/FabricMC/fabric/pull/1571

This was released 3 days ago:
https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3437870
but the latest at time of writing is 0.39.2

Failing that, it is impossible to answer your question without more concrete information.
Just posting a screenshot and saying "look its different" doesn't help without psychic abilities. :-)

**Comment by Pundus** [comment]
Apologies, my bad! Yes, I was already using  0.39.2, which has this issue. I have since done further tests. There were no errors in either the client or server log relating to this issue.

I spent a few hours trial and error-ing and it was caused by the fabricDynamicRegistry.dat file. Deleting it and restarting the server fixed it.

**Comment by warjort** [comment]
That file exists to try to work around this vanilla bug:
https://bugs.mojang.com/browse/MC-202036

That you are still this bug maybe a sign that it is not fully fixed?
