### ISSUE TITLE
Hoppers to fast for comparators

### ISSUE THREAD

**Issue by NotOttomann** [FabricMC/fabric#1686]
When i made a autobrewer in singleplayer and it didnt work cuz the comparator didnt get powered so i checked without mods and it worked and when i watch the hopper while the potions come out i see them go thru so i started removing mods and adding them back if i had the same issue but when i removed fabric api the brewer worked again anything i can do to fix this?

**Comment by haykam821** [comment]
Could you send a screenshot of a simple system that causes this issue?

**Comment by Technici4n** [comment]
If you are using fabric API 0.38.x or less, please update to the latest version, that should solve this issue.
Otherwise, could you post a forced crash report (F3+C) that will contain the list of available mods?

**Comment by NotOttomann** [comment]
I downloaded the newest 1.17.1 api and it worked thank you so much it was ruining like half my farms lol

**Comment by NotOttomann** [comment]
> If you are using fabric API 0.38.x or less, please update to the latest version, that should solve this issue.
> Otherwise, could you post a forced crash report (F3+C) that will contain the list of available mods?

I downloaded the newest 1.17.1 version of the api and it worked thanks! it was ruining like half my farms lol
