### ISSUE TITLE
this error does not happen on 38.2 or earlier 

### ISSUE THREAD

**Issue by morottao** [FabricMC/fabric#1697]
multimc, all information is in the log:
https://paste.ee/p/atrCq

**Comment by lostopkk** [comment]
is written in the log: 
 
 - Conflicting versions found for fabric-api-base: used 0.3.0+a02b446313, also found 0.3.0+a02b44633d, 0.3.0+a02b4463d5, 0.3.0+a02b446318
 - Mod 'Bewitchment' (bewitchment) conflicts with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.11.20!
	 - While this won't prevent you from starting the game, the developer(s) of 'Bewitchment' (bewitchment) have found that version 1.11.20 of 'OptiFabric' (optifabric) conflicts with their mod.
	 - It is heavily recommended to remove one of the mods.
	 - Mod 'OptiFabric' (optifabric) v1.11.20 is being loaded from the user's mod directory.
 - Mod 'Clear Despawn' (cleardespawn) recommends version 1.1.7 or later of mod modupdater, which is missing!
	 - You must install version 1.1.7 or later of modupdater.

**Comment by lostopkk** [comment]
sorry for my comment, doesn't help solve, my bad :/

**Comment by modmuss50** [comment]
No, thats not correct @lostopkk

A mod is conflicting with the new changes added in 0.39

`@Redirect conflict. Skipping fabric-entity-events-v1.mixins.json:PlayerEntityMixin->@Redirect::redirectDaySleepCheck(Lnet/minecraft/class_1937;)Z with priority 1000, already redirected by somnus.mixins.json:MixinPlayerEntity->@Redirect::somnus$isDay(Lnet/minecraft/class_1937;)Z with priority 1000`

The somnus mod needs updating to support the newer version of fabric, looking at it, it appears that the changes in fabric have superseeded it.

**Comment by lostopkk** [comment]
> 
> 
> No, thats not correct @lostopkk
> 
> A mod is conflicting with the new changes added in 0.39
> 
> `@Redirect conflict. Skipping fabric-entity-events-v1.mixins.json:PlayerEntityMixin->@Redirect::redirectDaySleepCheck(Lnet/minecraft/class_1937;)Z with priority 1000, already redirected by somnus.mixins.json:MixinPlayerEntity->@Redirect::somnus$isDay(Lnet/minecraft/class_1937;)Z with priority 1000`
> 
> The somnus mod needs updating to support the newer version of fabric, looking at it, it appears that the changes in fabric have superseeded it.

yeah yeah, sorry, i didn't see it right, i just took a quick look at warn
