### ISSUE TITLE
[1.17.1] [Latest Fabric Api] tons of entity errors

### ISSUE THREAD

**Issue by itsdinkd** [FabricMC/fabric#1704]
Continous entity errors that keep pushing errors while playing, nothing happening in game, cannot tell, and then suddenly I just crash. 
------
Error Log
https://pastebin.com/SKmfhNBX

-------

Mod List
[09:29:55] [main/INFO]: [FabricLoader] Loading 360 mods:
	- addendum@1.0.2
	- adorn@2.1.4+1.17.1
	- advancementplaques@1.4.0
	- advancements-enlarger@0.2.4
	- adventure-platform-fabric@4.1.0-SNAPSHOT
	- adventurez@1.2.11
	- agape_space@0.3.0
	- ambientenvironment@6.0.21
	- apoli@1.0.4
	- appleskin@mc1.17-2.1.3
	- aqupdcaracal@1.17-1.3.11
	- architectury@2.5.27
	- artifality@0.3.4
	- artifice@0.15.3+21w07a
	- artofalchemy@1.2.0+1.17.1
	- attributefix@1.0.3
	- audiooutput@0.0.4
	- balm-fabric@1.3.0+0
	- bclib@0.3.1
	- better_wandering_trader@1.7.0
	- betterend@0.11.0-pre
	- betterf3@1.1.5
	- bettermineshafts@1.17-1.0.1
	- betternether@5.1.3
	- betterstrongholds@1.17-1.1.1
	- bewitchment@1.17-5
	- blast@1.7
	- blockshifter@1.4.0+fabric-1.17.1
	- blockus@2.2.8+1.17.1
	- blue_endless_jankson@1.2.1
	- blur@2.1.0
	- bosses_of_mass_destruction@1.2.3-1.17.1
	- breakprogress@1.0.1
	- c2me@0.2.0+alpha.4.0
	- calio@1.0.2
	- can-i-mine-this-block@1.1.0
	- cardinal-components@3.1.1
	- cardinal-components-base@3.1.1
	- cardinal-components-block@3.1.1
	- cardinal-components-chunk@3.1.1
	- cardinal-components-entity@3.1.1
	- cardinal-components-item@3.1.1
	- cardinal-components-level@3.1.1
	- cardinal-components-scoreboard@3.1.1
	- cardinal-components-util@3.1.1
	- cardinal-components-world@3.1.1
	- carpet@1.4.45
	- carpet-extra@1.4.43
	- carpet-tis-addition@1.21.3+build.672
	- charm@3.3.2
	- charmonium@3.3.0
	- chesttracker@1.0.14
	- cleancut@1.17-4.0-fabric
	- cleardespawn@1.17.1-fabric0.36.1-1.1.1
	- cloth-api@2.0.54
	- cloth-basic-math@0.5.1
	- cloth-client-events-v0@2.0.54
	- cloth-common-events-v1@2.0.54
	- cloth-config2@5.0.38
	- cloth-datagen-api-v1@2.0.54
	- cloth-scissors-api-v1@2.0.54
	- cloth-utils-v1@2.0.54
	- cloud@1.5.0
	- cloud_commandframework_cloud-brigadier_@1.5.0
	- cloud_commandframework_cloud-core_@1.5.0
	- cloud_commandframework_cloud-minecraft-extras@1.5.0
	- cloud_commandframework_cloud-services_@1.5.0
	- clumps@fabric-1.17.1-7.0.5
	- colorutility@2.0.1
	- com_electronwill_night-config_core@3.6.2
	- com_electronwill_night-config_toml@3.6.2
	- com_moandjiezana_toml_toml4j@0.7.2
	- com_typesafe_config@1.4.1
	- completeconfig@1.0.0
	- confabricate@2.1.0-SNAPSHOT+4.1.1
	- conjuring@1.0.7
	- cosmetic-armor@1.1.0
	- craftingtweaks@13.0.0+0
	- craftpresence@1.8.4
	- croptopia@1.6.1
	- crowdin-translate@1.3+1.17
	- ctm@0.5.1+1.17
	- cullleaves@2.2.0
	- customportalapi@0.0.1-beta41-1.17
	- customportals@2.1.0
	- dankstorage@2.1-1.17.1
	- dark-enchanting@0.4.1-1.17.1
	- defaultsettings@3.0.3
	- disable_custom_worlds_advice@1.3
	- dml-refabricated@0.4.4-beta
	- dml-refabricated-base@0.4.4-beta
	- dml-refabricated-events@0.4.4-beta
	- dml-refabricated-modular-armor@0.4.4-beta
	- dml-refabricated-rei@0.4.4-beta
	- dmlsimulacrum@1.0.3
	- doom@4.0.6
	- dragonloot@1.0.9
	- drippyloadingscreen@1.1.0
	- dual_riders@1.0.5
	- dungeons_arise@2.1.47-fabric
	- eldritch_mobs@1.9.2
	- emagnet@1.2.3
	- enchant_giver@1.1.0
	- enchantedbookredesign@1.17.1-2.0
	- enchantmentdescriptions@4.0.1
	- expandedstorage@7.0.0
	- explorerscompass@1.17.1-2.0.1-fabric
	- extraorigins@1.17-6
	- fabric@0.40.0+1.17
	- fabric-api-base@0.3.0+a02b446313
	- fabric-api-lookup-api-v1@1.3.0+cbda931818
	- fabric-biome-api-v1@3.2.0+cbda931818
	- fabric-blockrenderlayer-v1@1.1.5+a02b446318
	- fabric-command-api-v1@1.1.3+5ab9934c18
	- fabric-commands-v0@0.2.2+92519afa18
	- fabric-containers-v0@0.1.12+cbda931818
	- fabric-content-registries-v0@0.3.0+cbda931818
	- fabric-crash-report-info-v1@0.1.5+be9da31018
	- fabric-dimensions-v1@2.0.11+6cefd57718
	- fabric-entity-events-v1@1.2.3+87cc6e4c18
	- fabric-events-interaction-v0@0.4.10+fc40aa9d18
	- fabric-events-lifecycle-v0@0.2.1+92519afa18
	- fabric-game-rule-api-v1@1.0.7+cbda931818
	- fabric-item-api-v1@1.2.4+cbda931818
	- fabric-item-groups-v0@0.2.10+b7ab612118
	- fabric-key-binding-api-v1@1.0.4+cbda931818
	- fabric-keybindings-v0@0.2.2+36b77c3e18
	- fabric-language-kotlin@1.6.4+kotlin.1.5.30
	- fabric-language-scala@1.1.0+scala.2.13.6
	- fabric-lifecycle-events-v1@1.4.4+a02b44633d
	- fabric-loot-tables-v1@1.0.4+a02b446318
	- fabric-mining-levels-v0@0.1.3+92519afa18
	- fabric-models-v0@0.3.0+a02b446318
	- fabric-networking-api-v1@1.0.13+cbda931818
	- fabric-networking-blockentity-v0@0.2.11+a02b446318
	- fabric-networking-v0@0.3.2+92519afa13
	- fabric-object-builder-api-v1@1.10.9+b7ab612118
	- fabric-object-builders-v0@0.7.3+a02b446318
	- fabric-particles-v1@0.2.4+a02b446318
	- fabric-permissions-api-v0@0.1-SNAPSHOT
	- fabric-registry-sync-v0@0.7.10+e2961fee18
	- fabric-renderer-api-v1@0.4.4+cbda931818
	- fabric-renderer-indigo@0.4.8+cbda931818
	- fabric-renderer-registries-v1@3.2.2+fc40aa9d18
	- fabric-rendering-data-attachment-v1@0.1.5+a02b446313
	- fabric-rendering-fluids-v1@0.1.13+a02b446318
	- fabric-rendering-v0@1.1.3+fc40aa9d18
	- fabric-rendering-v1@1.8.1+fc40aa9d18
	- fabric-resource-loader-v0@0.4.8+a00e834b18
	- fabric-screen-api-v1@1.0.4+198a96213d
	- fabric-screen-handler-api-v1@1.1.8+cbda931818
	- fabric-structure-api-v1@1.1.13+5ab9934c18
	- fabric-tag-extensions-v0@1.2.1+b06cb95b18
	- fabric-textures-v0@1.0.6+a02b446318
	- fabric-tool-attribute-api-v1@1.2.12+b7ab612118
	- fabric-transfer-api-v1@1.3.0+fc40aa9d18
	- fabricenchantments@0.4.2
	- fabricloader@0.11.6
	- fake-player-api@0.2.0
	- fallflyinglib@3.0.0-beta.2
	- fallingleaves@1.7.3+1.17.1
	- fallingtree@2.12.1
	- fastfurnace@1.17-3.0
	- fasttransferlib@0.5.6
	- ferritecore@3.0.3
	- fiber@0.23.0-2
	- flytre-lib-base@1.2.0
	- flytre-lib-compat@1.0.0
	- flytre-lib-config@1.1.0
	- flytre-lib-event@1.0.1
	- flytre-lib-gui@1.0.0
	- flytre-lib-storage@2.3.1
	- flytre_lib@1.3.7
	- food_highlight@1.0.3
	- gbfabrictools@1.3.4+1.17
	- geckolib3@3.0.13
	- gobber2@2.4.43
	- goldenhoppers@1.1.0
	- harvest_scythes@2.0.6
	- hctm-base@3.6.2
	- healthoverlay@4.0.1
	- heartbond@1.1.0
	- hologram-api@0.2.1+1.17.1
	- hookshot@19.0
	- horseinfo@0.3.0-1.17
	- hydrogen@0.3
	- iknowwhatimdoing@3.1.0
	- impersonate@2.3.3
	- incantationem@1.1.2+1.17.1
	- indium@1.0.0+mc1.17.1
	- indrev@1.10.0-alpha.12
	- inventoryprofilesnext@1.0.0
	- io_leangen_geantyref_geantyref@1.3.11
	- iris@1.1.2-rc1+rev.89f8898
	- itemscroller@0.15.0-dev.20210707.005506
	- jankson@3.0.1+j1.2.0
	- java@16
	- jumpoverfences@1.16-0.0.3
	- justenoughkeys@0.2.2
	- kanos_config@0.1.4+1.14.4-1.17.1
	- kibe@1.8.1-BETA+1.17
	- kirin@1.9.1
	- kjsextras@1.3.2
	- konkrete@1.2.3
	- ktdatataglib@1.5.4
	- kubejs@1605.3.10-build.9999
	- kyrptconfig@1.1.10-1.17
	- lambdynlights@2.0.2+1.17
	- lazydfu@0.1.2
	- libaddict@0.3.0
	- libblockattributes@0.8.17003
	- libblockattributes_core@0.9.0
	- libblockattributes_fluids@0.9.0
	- libblockattributes_items@0.9.0
	- libcd@3.0.3+1.16.3
	- libgui@4.1.6+1.17.1
	- libninepatch@1.1.0
	- libra@0.3.9.2
	- lightoverlay@6.0.0
	- lithium@0.7.4
	- logical_zoom@0.0.11
	- ltr@1.1.15+1.17.1
	- maelstrom_library@1.2.1-1.17
	- magick@1.0.5
	- magna@0.3.0-1.17-pre4
	- malilib@0.10.0-dev.24
	- mcda@1.7.10
	- mcdw@3.4.1
	- megane@5.2.1
	- megane-base@5.2.1
	- megane-fabric-transfer@5.2.1+1.1.0-3fe74aa118
	- megane-fast-transfer-lib@5.2.1+0.5.6
	- megane-industrial-revolution@5.2.1+1.10.0-alpha.12
	- megane-kibe@5.2.1+1.8.1-BETA-1.17
	- megane-lib-block-attributes@5.2.1+0.9.0
	- megane-runtime@5.2.1
	- megane-team-reborn-energy@5.2.1+0.1.1
	- megane-tech-reborn@5.2.1+5.0.6-beta-build.95
	- megane-vanilla@5.2.1+1.17.1
	- megane-wireless-networks@5.2.1+1.1.2
	- minecraft@1.17.1
	- minecraftcapes@11.0.1
	- mining_dims@1.1.12
	- mm@2.3
	- modmenu@2.0.9
	- mods-command@1.0.4
	- morevillagers-fabric@2.0.4-SNAPSHOT
	- mostructures@1.3.0-pre1-1.17.1
	- multipart_entities@1.1.2-1.17
	- mythic-mounts@1.17.1-1.2
	- naturescompass@1.17.1-2.0.1-fabric
	- net_kyori_adventure-api@4.8.1
	- net_kyori_adventure-key@4.8.1
	- net_kyori_adventure-platform-api@4.0.0-SNAPSHOT
	- net_kyori_adventure-text-feature-pagination@4.0.0-SNAPSHOT
	- net_kyori_adventure-text-serializer-gson@4.8.1
	- net_kyori_adventure-text-serializer-plain@4.8.1
	- net_kyori_examination-api@1.1.0
	- net_kyori_examination-string@1.1.0
	- noanglebrackets@1.1.0
	- notenoughcrashes@3.3.1+1.17
	- nyfsquivers@Fabric-0.2.6
	- omega-config@1.0.8
	- org_aperlambda_lambdajcommon@1.8.1
	- org_jetbrains_kotlin_kotlin-reflect@1.5.30
	- org_jetbrains_kotlin_kotlin-stdlib@1.5.30
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.5.30
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.5.30
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.5.1
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.5.1
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm@1.2.2
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm@1.2.2
	- org_objenesis_objenesis@3.2
	- org_spongepowered_configurate-core@4.1.1
	- org_spongepowered_configurate-extra-dfu4@4.1.1
	- org_spongepowered_configurate-gson@4.1.1
	- org_spongepowered_configurate-hocon@4.1.1
	- org_spongepowered_configurate-yaml@4.1.1
	- org_yaml_snakeyaml@1.30-SNAPSHOT
	- origins@1.0.3
	- origins-classes@1.2.2
	- outvoted@2.0.0-alpha.12
	- owo@0.1.1
	- packet_tweaker@0.2.0-1.17-pre1
	- patchouli@1.17-54-FABRIC
	- pehkui@2.3.0+1.14.4-1.17.1
	- pipe@1.4.0
	- placeholder-api@1.1.0+1.17.1
	- plantinajar@2.2.2
	- playerabilitylib@1.3.0
	- polymer@0.1.0-rc.4+1.17.1
	- polymorph@0.0.12-1.17.1
	- prefab@2.1.3
	- presencefootsteps@r32-1.17-rc1
	- pugh_lib@${version}
	- pugh_tools@${version}
	- qcommon-cfg-core@3.3.0
	- qcommon-croco@2.1.1
	- quarryplus@17.0.353
	- quickshulker@1.2.2-1.17
	- ratsmischief@1.2.2
	- reach-entity-attributes@2.1.1
	- reborncore@5.0.6-beta+build.94
	- redbits@1.10.0
	- reeses-sodium-options@1.2.0
	- repurposed_structures@2.3.2+1.17.1
	- resourceful_tools@1.1.19
	- respawnablepets@1.17-3
	- rhino@1605.1.2-build.40
	- right-click-clear@2.0.3
	- roughlyenoughitems@6.0.279-alpha
	- rpgstats@4.1.8+1.17.1
	- rswires@4.11.2
	- runelic@3.0.1
	- salutem@1.2.1
	- satin@1.6.0-nightly.1.17-pre3
	- schmucks@1.4.0
	- secretrooms@1.0.0+1.17
	- seedy-behavior@1.0.2+1.17.1
	- server_translations_api@1.4.5+1.17
	- servertick@1.5
	- sgui@1.0.0-rc4+1.17.1
	- shulkerboxtooltip@3.0.1+1.17
	- shulkerutils@1.0.4-1.17
	- simple_backpack@1.1.18
	- sodium@0.3.2+IRIS2-build.127
	- sodium-extra@0.3.4
	- somnus@0.0.14-1.17.1
	- spark@1.6.1
	- spruceui@3.2.0+1.17
	- staffofbuilding@1.3.2-1.17
	- statuseffecttimer@1.0.3
	- step-height-entity-attribute@1.0.0
	- team_reborn_energy@0.1.1
	- techreborn@5.0.6-beta+build.94
	- terraform-wood-api-v1@2.0.2
	- terralith@1.6.1
	- the_aether@1.17.1-1.5.0
	- things@0.2.5
	- toms_storage@1.1.14
	- toolstats@2.0.1
	- tooltipfix@1.0.3-1.16
	- torcherino@15.0.0
	- torohealth@1.17.1-fabric-12
	- transportables@1.0.6
	- trinkets@3.0.4
	- truerooms@1.1.5
	- universal-graves@1.0.8+1.17.1
	- voidtotem@1.17.0-1.0.0
	- voidz@1.0.5
	- ward_blocks@1.1.7
	- waterdripsound@1.17-0.2.2
	- waystones@2.0.4
	- whereisit@1.13.3
	- winged@1.17.1-3.0.0
	- wirelessnetworks@1.1.2
	- wthit@3.8.1
	- xaerominimap@21.16.0
	- xaeroworldmap@1.17.0
	- yungsapi@1.17-Fabric-16

**Comment by warjort** [comment]
Please don't just post any crash you get when running modded minecraft here.
This area is for bug reports of the fabric api. It is not a help forum.
i.e. Can you identify what change to the fabric api would fix your problem?

If you want help use the discussions tab or the discord.

I can tell you there is a mismatch between what the client expects (a byte) and what it is receiving from the server 
(sometimes a boolean and sometimes an integer).
This is for some modded tracked entity data (field 16 to be precise - vanilla only has 8 fields).

Most likely you have a discrepency between the mods/versions you are running on the server and those on the client.
If thats not true then you have a mod that is sending "random" data to the client.
The errors don't say which mod it is, maybe the server log has more information?

But post your follow up to a help forum.

**Comment by warjort** [comment]
Having said that:

This "next numbering" of tracker id does look like it would be brittle to any differences in mod loading between the client and server? like my suggested difference mods/versions above

There maybe a case for the fabric api doing some kind of sync when the client joins a server to validate they agree and give an error if they don't?

This wouldn't fix your potential problem, it would just move the error to when the client joins the server and might be able give better diagnostics?
