### ISSUE TITLE
Crash on connection caused by fabric loader

### ISSUE THREAD

**Issue by itsdinkd** [FabricMC/fabric#1705]
Hello.

cannot join server, getting this error on connect. versions of mods are matching, but I can join single player. 

1.17.1 

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 9/5/21, 2:04 PM
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_897.method_3933(net.minecraft.class_1297, net.minecraft.class_4604, double, double, double)" because "â˜ƒ" is null
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.52)
	at net.minecraft.client.render.entity.EntityRenderDispatcher.shouldRender(EntityRenderDispatcher:121)
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1199)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:1026)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:810)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1112)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728)
	at net.minecraft.client.main.Main.main(Main:217)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_898.method_3950(class_898.java:121)
	at net.minecraft.class_761.method_22710(class_761.java:1199)
	at net.minecraft.class_757.method_3188(class_757.java:1026)

-- Patchouli Book Info --
Details:
	Patchouli open book context: n/a
Stacktrace:
	at net.minecraft.class_128.handler$gch000$fillPatchouliContext(class_128.java:1521)
	at net.minecraft.class_128.<init>(class_128.java:37)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Affected level --
Details:
	All players: 1 total; [class_746['CloudyyDragon'/153568, l='ClientLevel', x=1224.28, y=118.66, z=1751.44]]
	Chunk stats: 1024, 361
	Level dimension: minecraft:overworld
	Level spawn location: World: (-66,80,-281), Section: (at 14,0,7 in -5,5,-18; chunk contains blocks -80,-64,-288 to -65,319,-273), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 1664903 game time, 1683863 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Generated Resources, Fabric Mods, cullleaves/smartleaves, charmonium/journeyman, KubeJS Resource Pack [assets]

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 515471360 bytes (491 MiB) / 2264924160 bytes (2160 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 6
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2.90
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: NVIDIA GeForce GTX 1050
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x1c81
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7168
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 21949.21
	Virtual memory used (MB): 13590.95
	Swap memory total (MB): 5632.00
	Swap memory used (MB): 81.71
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m -XX:PermSize=256m
	Fabric Mods: 
		addendum: Addendum 1.0.2
		adorn: Adorn 2.1.4+1.17.1
		advancementplaques: Advancement Plaques 1.4.0
		advancements-enlarger: Advancements Enlarger 0.2.4
		adventure-platform-fabric: adventure-platform-fabric 4.1.0-SNAPSHOT
		adventurez: AdventureZ 1.2.11
		agape_space: Space Dimensions 0.3.0
		ambientenvironment: Ambient Environment 6.0.21
		apoli: Apoli 1.0.4
		appleskin: AppleSkin mc1.17-2.1.3
		aqupdcaracal: Caracal mob 1.17-1.3.11
		architectury: Architectury 2.5.27
		artifality: Artifality 0.3.4
		artifice: Artifice 0.15.3+21w07a
		artofalchemy: Art of Alchemy: Memoriam 1.2.0+1.17.1
		attributefix: Attribute Fix {FABRIC} 1.0.3
		audiooutput: AudioOutput 0.0.4
		balm-fabric: Balm 1.3.0+0
		bclib: BCLib 0.3.1
		better_wandering_trader: Better Wandering Trader 1.7.0
		betterend: Better End 0.11.0-pre
		betterf3: BetterF3 1.1.5
		bettermineshafts: YUNG's Better Mineshafts 1.17-1.0.1
		betternether: Better Nether 5.1.3
		betterstrongholds: YUNG's Better Strongholds 1.17-1.1.1
		bewitchment: Bewitchment 1.17-5
		blast: BLAST 1.7
		blockshifter: Blockshifter 1.4.0+fabric-1.17.1
		blockus: Blockus 2.2.8+1.17.1
		blue_endless_jankson: jankson 1.2.1
		blur: Blur (Fabric) 2.1.0
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.2.3-1.17.1
		breakprogress: Break Progress 1.0.1
		calio: Calio 1.0.2
		can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.1.0
		cardinal-components: Cardinal Components API 3.1.1
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-block: Cardinal Components API (blocks) 3.1.1
		cardinal-components-chunk: Cardinal Components API (chunks) 3.1.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		cardinal-components-item: Cardinal Components API (items) 3.1.1
		cardinal-components-level: Cardinal Components API (world saves) 3.1.1
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 3.1.1
		cardinal-components-util: Cardinal Components API (utilities) 3.1.1
		cardinal-components-world: Cardinal Components API (worlds) 3.1.1
		carpet: Carpet Mod 1.4.45
		carpet-extra: Carpet Extra 1.4.43
		carpet-tis-addition: Carpet TIS Addition 1.21.3+build.672
		charm: Charm 3.3.2
		charmonium: Charmonium 3.3.0
		chesttracker: Chest Tracker 1.0.14
		cleancut: CleanCut 1.17-4.0-fabric
		cleardespawn: Clear Despawn 1.17.1-fabric0.36.1-1.1.1
		cloth-api: Cloth API 2.0.54
		cloth-armor-api-v1: Cloth Armor API v1 1.5.47
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config2: Cloth Config v5 5.0.38
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		cloud: Cloud 1.5.0
		cloud_commandframework_cloud-brigadier_: cloud-brigadier 1.5.0
		cloud_commandframework_cloud-core_: cloud-core 1.5.0
		cloud_commandframework_cloud-minecraft-extras: cloud-minecraft-extras 1.5.0
		cloud_commandframework_cloud-services_: cloud-services 1.5.0
		clumps: Clumps fabric-1.17.1-7.0.5
		colorutility: ColorUtility 2.0.1
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_typesafe_config: config 1.4.1
		completeconfig: CompleteConfig 1.0.0
		confabricate: confabricate 2.1.0-SNAPSHOT+4.1.1
		conjuring: Conjuring 1.0.7
		cosmetic-armor: Cosmetic Armor 1.1.0
		craftingtweaks: Crafting Tweaks 13.0.0+0
		craftpresence: CraftPresence 1.8.4
		croptopia: Croptopia 1.6.1
		crowdin-translate: CrowdinTranslate 1.3+1.17
		ctm: ConnectedTexturesMod for Fabric 0.5.1+1.17
		cullleaves: Cull Leaves 2.2.0
		customportalapi: Custom Portal Api 0.0.1-beta41-1.17
		customportals: Custom Portals 2.1.0
		dankstorage: Dank Storage 2.1-1.17.1
		dark-enchanting: Dark Enchanting 0.4.1-1.17.1
		defaultsettings: DefaultSettings 3.0.3
		detailab: Detail Armor Bar 2.4.1+1.17.1-fabric
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.3
		dml-refabricated: Deep Mob Learning: Refabricated 0.4.4-beta
		dml-refabricated-base: DML: Refabricated - Base 0.4.4-beta
		dml-refabricated-events: DML: Refabricated - Vanilla Events 0.4.4-beta
		dml-refabricated-modular-armor: DML: Refabricated - Glitch Armor 0.4.4-beta
		dml-refabricated-rei: DML: Refabricated - REI Integration 0.4.4-beta
		dmlsimulacrum: Deep Mob Learning: Simulacrum 1.0.3
		doom: Doom Fabric 4.0.6
		dragonloot: DragonLoot 1.0.9
		drippyloadingscreen: Drippy Loading Screen 1.1.0
		dual_riders: DualRiders 1.0.5
		dungeons_arise: When Dungeons Arise 2.1.47-fabric
		eldritch_mobs: Eldritch Mobs 1.9.2
		emagnet: E Magnet 1.2.3
		enchant_giver: Enchant Giver 1.1.0
		enchantedbookredesign: Enchanted Book Redesign 1.17.1-2.0
		enchantmentdescriptions: Enchantment Descriptions 4.0.1
		expandedstorage: Expanded Storage 7.0.0
		explorerscompass: Explorer's Compass 1.17.1-2.0.1-fabric
		extraorigins: Extra Origins 1.17-6
		fabric: Fabric API 0.40.0+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+cbda931818
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.0+cbda931818
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+cbda931818
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.0+cbda931818
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.3+87cc6e4c18
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.10+fc40aa9d18
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+cbda931818
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+cbda931818
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+cbda931818
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-language-kotlin: Fabric Language Kotlin 1.6.4+kotlin.1.5.30
		fabric-language-scala: Fabric Language Scala 1.1.0+scala.2.13.6
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446318
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+cbda931818
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa13
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612118
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+cbda931818
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+cbda931818
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.2+fc40aa9d18
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.3+fc40aa9d18
		fabric-rendering-v1: Fabric Rendering (v1) 1.8.1+fc40aa9d18
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+198a96213d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+cbda931818
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.1+b06cb95b18
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.3.0+fc40aa9d18
		fabricenchantments: Fabric Enchantments 0.4.2
		fabricloader: Fabric Loader 0.11.6
		fake-player-api: Fake Player API 0.2.0
		fallflyinglib: FallFlyingLib 3.0.0-beta.2
		fallingleaves: Falling Leaves 1.7.3+1.17.1
		fallingtree: FallingTree 2.12.1
		fastfurnace: FastFurnace 1.17-3.0
		fasttransferlib: Fast Transfer Lib 0.5.6
		ferritecore: FerriteCore 3.0.3
		fiber: fiber 0.23.0-2
		flytre-lib-base: Flytre Lib - Base Module 1.2.0
		flytre-lib-compat: Flytre Lib - Compat Module 1.0.0
		flytre-lib-config: Flytre Lib - Config Module 1.1.0
		flytre-lib-event: Flytre Lib - Event Module 1.0.1
		flytre-lib-gui: Flytre Lib - GUI Module 1.0.0
		flytre-lib-storage: Flytre Lib - Storage Module 2.3.1
		flytre_lib: Flytre Lib 1.3.7
		food_highlight: FoodHighlight 1.0.3
		gbfabrictools: GBfabrictools 1.3.4+1.17
		geckolib3: Geckolib 3.0.13
		gobber2: Gobber2 2.4.43
		goldenhoppers: Golden Hoppers 1.1.0
		harvest_scythes: Harvest Scythes 2.0.6
		hctm-base: HCTM Base 3.6.2
		healthoverlay: Health Overlay 4.0.1
		heartbond: Heartbond 1.1.0
		hologram-api: Hologram API 0.2.1+1.17.1
		hookshot: Hookshot 19.0
		horseinfo: Horse Info 0.3.0-1.17
		hydrogen: Hydrogen 0.3
		iknowwhatimdoing: I Know What I'm Doing 3.1.0
		impersonate: Impersonate 2.3.3
		incantationem: Incantationem 1.1.2+1.17.1
		indium: Indium 1.0.0+mc1.17.1
		indrev: Industrial Revolution 1.10.0-alpha.12
		inventoryprofilesnext: Inventory Profiles Next 1.0.0
		io_leangen_geantyref_geantyref: geantyref 1.3.11
		itemscroller: Item Scroller 0.15.0-dev.20210707.005506
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		jumpoverfences: JumpOverFences 1.16-0.0.3
		justenoughkeys: Just Enough Keys 0.2.2
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		kibe: Kibe 1.8.1-BETA+1.17
		kirin: Kirin UI 1.9.1
		kjsextras: KubeJS Extras 1.3.2
		konkrete: Konkrete 1.2.3
		ktdatataglib: KtDataTagLib 1.5.4
		kubejs: KubeJS 1605.3.10-build.9999
		kyrptconfig: Kytpt Config 1.1.10-1.17
		lambdynlights: LambDynamicLights 2.0.2+1.17
		lazydfu: LazyDFU 0.1.2
		libaddict: libaddict 0.3.0
		libblockattributes: LibBlockAttributes 0.8.17003
		libblockattributes_core: LibBlockAttributes (Core) 0.9.0
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.9.0
		libblockattributes_items: LibBlockAttributes (Items) 0.9.0
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.1.6+1.17.1
		libninepatch: LibNinePatch 1.1.0
		libra: Libra 0.3.9.2
		lightoverlay: Light Overlay 6.0.0
		lithium: Lithium 0.7.4
		logical_zoom: Logical Zoom 0.0.11
		ltr: LilTaterReloaded 1.1.15+1.17.1
		maelstrom_library: Maelstrom Library 1.2.1-1.17
		magna: Magna 0.3.0-1.17-pre4
		malilib: MaLiLib 0.10.0-dev.24
		mcda: MC Dungeons Armors 1.7.10
		mcdw: MC Dungeons Weapons 3.4.1
		megane: megane 5.2.1
		megane-base: megane-base 5.2.1
		megane-fabric-transfer: megane-fabric-transfer 5.2.1+1.1.0-3fe74aa118
		megane-fast-transfer-lib: megane-fast-transfer-lib 5.2.1+0.5.6
		megane-industrial-revolution: megane-industrial-revolution 5.2.1+1.10.0-alpha.12
		megane-kibe: megane-kibe 5.2.1+1.8.1-BETA-1.17
		megane-lib-block-attributes: megane-lib-block-attributes 5.2.1+0.9.0
		megane-runtime: megane-runtime 5.2.1
		megane-team-reborn-energy: megane-team-reborn-energy 5.2.1+0.1.1
		megane-tech-reborn: megane-tech-reborn 5.2.1+5.0.6-beta-build.95
		megane-vanilla: megane-vanilla 5.2.1+1.17.1
		megane-wireless-networks: megane-wireless-networks 5.2.1+1.1.2
		minecraft: Minecraft 1.17.1
		minecraftcapes: MinecraftCapes Mod 11.0.1
		mining_dims: Mining Dimensions 1.1.12
		mm: Manningham Mills 2.3
		modmenu: Mod Menu 2.0.9
		mods-command: Mods Command 1.0.4
		morevillagers-fabric: MoreVillagersFabric 2.0.4-SNAPSHOT
		mostructures: Mo' Structures 1.3.0-pre1-1.17.1
		multipart_entities: MultipartEntities 1.1.2-1.17
		mythic-mounts: Mythic Mounts 1.17.1-1.2
		naturescompass: Nature's Compass 1.17.1-2.0.1-fabric
		nearsightedly: Near-Sightedly 1.2.1
		net_kyori_adventure-api: adventure-api 4.8.1
		net_kyori_adventure-key: adventure-key 4.8.1
		net_kyori_adventure-platform-api: adventure-platform-api 4.0.0-SNAPSHOT
		net_kyori_adventure-text-feature-pagination: adventure-text-feature-pagination 4.0.0-SNAPSHOT
		net_kyori_adventure-text-serializer-gson: adventure-text-serializer-gson 4.8.1
		net_kyori_adventure-text-serializer-plain: adventure-text-serializer-plain 4.8.1
		net_kyori_examination-api: examination-api 1.1.0
		net_kyori_examination-string: examination-string 1.1.0
		noanglebrackets: NoAngleBrackets 1.1.0
		notenoughcrashes: Not Enough Crashes 3.3.1+1.17
		nyfsquivers: Nyf's Quivers Fabric-0.2.6
		omega-config: OmegaConfig 1.0.8
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.30
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.2
		org_objenesis_objenesis: objenesis 3.2
		org_spongepowered_configurate-core: configurate-core 4.1.1
		org_spongepowered_configurate-extra-dfu4: configurate-extra-dfu4 4.1.1
		org_spongepowered_configurate-gson: configurate-gson 4.1.1
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.1
		org_spongepowered_configurate-yaml: configurate-yaml 4.1.1
		org_yaml_snakeyaml: snakeyaml 1.30-SNAPSHOT
		origins: Origins 1.0.3
		origins-classes: Origins: Classes 1.2.2
		outvoted: Outvoted 2.0.0-alpha.12
		owo: OwO 0.1.1
		packet_tweaker: Packet Tweaker 0.2.0-1.17-pre1
		patchouli: Patchouli 1.17-54-FABRIC
		pehkui: Pehkui 2.3.0+1.14.4-1.17.1
		pipe: Pipe 1.4.0
		placeholder-api: Placeholder API 1.1.0+1.17.1
		plantinajar: Plant In A Jar 2.2.2
		playerabilitylib: Pal 1.3.0
		polymer: Polymer 0.1.0-rc.4+1.17.1
		polymorph: Polymorph 0.0.12-1.17.1
		prefab: Prefab 2.1.3
		presencefootsteps: Presence Footsteps r32-1.17-rc1
		pugh_lib: Pugh Lib ${version}
		pugh_tools: Pugh Tools ${version}
		qcommon-cfg-core: qcommon-cfg-core 3.3.0
		qcommon-croco: Croco 2.1.1
		quarryplus: QuarryPlus 17.0.353
		quickshulker: Quick Shulker 1.2.2-1.17
		ratsmischief: Rat's Mischief 1.2.2
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reborncore: Reborn Core 5.0.6-beta+build.94
		redbits: Red Bits 1.10.0
		reeses-sodium-options: Reese's Sodium Options 1.2.0
		repurposed_structures: Repurposed Structures 2.3.2+1.17.1
		resourceful_tools: Resourceful Tools 1.1.19
		respawnablepets: Respawnable Pets 1.17-3
		rhino: Rhino 1605.1.2-build.40
		right-click-clear: Right Click Clear 2.0.3
		roughlyenoughitems: Roughly Enough Items 6.0.279-alpha
		rpgstats: RPGStats 4.1.8+1.17.1
		rswires: RSWires 4.11.2
		salutem: Salutem 1.2.1
		satin: Satin 1.6.0-nightly.1.17-pre3
		schmucks: Schmucks 1.4.0
		secretrooms: Secret Rooms 1.0.0+1.17
		seedy-behavior: Seedy Behavior 1.0.1
		server_translations_api: Server Translations API 1.4.5+1.17
		servertick: Server Tick 1.5
		sgui: SGui 1.0.0-rc4+1.17.1
		shulkerboxtooltip: Shulker Box Tooltip 3.0.1+1.17
		shulkerutils: shulkerutils 1.0.4-1.17
		simple_backpack: SimpleBackpack 1.1.18
		simplegrinder: Simple Grinder 17.0.1-Fabric
		sodium: Sodium 0.3.2+build.7
		sodium-extra: Sodium Extra 0.3.4
		somnus: Somnus API 0.0.14-1.17.1
		spruceui: SpruceUI 3.2.0+1.17
		staffofbuilding: Staff of Building 1.3.2-1.17
		statuseffecttimer: Status Effect Timer 1.0.3
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		team_reborn_energy: Energy 0.1.1
		techreborn: Tech Reborn 5.0.6-beta+build.94
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		the_aether: The Aether 1.17.1-1.5.0
		things: Things 0.2.5
		toms_storage: Tom's Simple Storage Mod 1.1.14
		toolstats: Tool Stats 2.0.1
		tooltipfix: ToolTip Fix 1.0.3-1.16
		torcherino: Torcherino 15.0.0
		torohealth: ToroHealth Damage Indicators 1.17.1-fabric-12
		transportables: Transportables 1.0.6
		trinkets: Trinkets 3.0.4
		truerooms: True Secret Rooms 1.1.5
		universal-graves: Universal Graves 1.0.8+1.17.1
		voidtotem: Void Totem (Fabric) 1.17.0-1.0.0
		voidz: VoidZ 1.0.5
		ward_blocks: Ward Blocks 1.1.7
		waterdripsound: Drip Sounds 1.17-0.2.2
		waystones: Waystones 2.0.4
		whereisit: Where Is It 1.13.3
		winged: Winged Mod 1.17.1-3.0.0
		wirelessnetworks: Wireless Networks 1.1.2
		wthit: wthit 3.8.1
		xaerominimap: Xaero's Minimap 21.16.0
		xaeroworldmap: Xaero's World Map 1.17.0
		yungsapi: YUNG's API 1.17-Fabric-16
	Launched Version: fabric-loader-0.11.6-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1050/PCIe/SSE2 GL version 3.2.0 NVIDIA 471.68, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods, cullleaves/smartleaves, charmonium/journeyman, charmonium/journeyman, cullleaves/smartleaves
	Current Language: English (US)
	CPU: 6x Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Fabric Loader (fabricloader)

**Comment by warjort** [comment]
Please stop dumping your crashes in this issues section. It is not a help forum.
Go here:
https://github.com/FabricMC/fabric/discussions

This is not a fabric bug.

**Comment by warjort** [comment]
"Suspected Mods: Fabric Loader (fabricloader)"

This is not caused by fabric loader. This is just "not enough crashes" seeing the fabric loader in the stacktrace and blaming it.
But the fabric loader is always in the stacktrace because it is one that starts minecraft.

**Comment by itsdinkd** [comment]
So how do I know if its a fabric bug or not?

**Comment by warjort** [comment]
When you post it in discussions, if it is a bug in fabric, somebody will tell you raise it as a bug if it really is one.
99% of the time, it will be like this, a bug in some other bug or some misconfiguration.

**Comment by Technici4n** [comment]
Probably not a fabric issue, and certainly not a loader one.
