### ISSUE TITLE
A VERY Weird Crush. Again...

### ISSUE THREAD

**Issue by ghost** [FabricMC/fabric#1707]
[crash-2021-09-10_17.50.51-server.txt](https://github.com/FabricMC/fabric/files/7144619/crash-2021-09-10_17.50.51-server.txt)
^^^ Fifth Crush
[crash-2021-09-10_17.56.44-server.txt](https://github.com/FabricMC/fabric/files/7144632/crash-2021-09-10_17.56.44-server.txt)
^^^ Sixth Crush

**Comment by Juuxel** [comment]
This isn't a Fabric API bug but a crash from Literally Chunk Loader - seemingly TrattMods/LiterallyChunkLoader-1.15#11.

**Comment by ghost** [comment]
Thanks! How did you figure it out, @Juuxel?

**Comment by Juuxel** [comment]
The error message is

> Encountered undecorated Accessor method in lchunkloader.mixins.json:<some extra stuff>

Then I just scrolled down to the mod list to see what `lchunkloader` was, and then googled their issue tracker to see if it had been reported already.

**Comment by ghost** [comment]
Nice, didn't see that error message, tho.
