### ISSUE TITLE
Tinted glass shadow/AO issue

### ISSUE THREAD

**Issue by LizIsTired** [FabricMC/fabric#1708]
In at least the 0.4 Fabric API for 1.17.1, there appears to be issues with either shadows or ambient occlusion in specific situations using tinted glass.

**Setup:**
For my setup, I'm running Minecraft 1.17.1, Fabric Loader 11.6 and only 0.4 Fabric API with no resource packs.

This is an example of it working as expected with FAPI
![2021-09-10_18 23 17](https://user-images.githubusercontent.com/13466206/132893120-7f3d8203-0cfe-4e90-ac4e-f66cd8f8f6dc.png)
However, in this arrangement, there are clear lines where there shouldn't be, it should be smooth.
![2021-09-10_18 24 08](https://user-images.githubusercontent.com/13466206/132893202-e605c309-0edb-476b-9aff-13e0f262c5f1.png)

**Comment by modmuss50** [comment]
Are you using 0.40.1 or 0.40.0? If 0.40.1 can you try 0.40.0 and see if the resolves the issue?

**Comment by LizIsTired** [comment]
This is 0.40.0+1.17, I can try with 0.40.1 and post some SS for comparison

**Comment by modmuss50** [comment]
Ah, ok. The reason I ask is 0.40.1 had a rendering related change (https://github.com/FabricMC/fabric/pull/1701) and want to make sure that its not caused by that.

**Comment by LizIsTired** [comment]
This is FAPI 0.40.1 
![2021-09-10_19 28 18](https://user-images.githubusercontent.com/13466206/132900456-e5f83c48-7b99-48e2-be46-4879003ee2d0.png)
alt angle
![2021-09-10_19 27 52](https://user-images.githubusercontent.com/13466206/132900441-77a96106-2542-4341-b9c3-2be38ed2cf7a.png)
edit: reshot in daylight

**Comment by haykam821** [comment]
I couldn't reproduce this issue with Fabric API 0.40.1. What does it look like in vanilla? Could it be hardware-dependent?

&nbsp; | Vanilla | Indigo
--- | --- | ---
Square | ![Vanilla square][0] |  ![Indigo square][2]
Staircase | ![Vanilla staircase][1] | ![Indigo staircase][3]

[0]: https://user-images.githubusercontent.com/24855774/132934582-2c0f21ee-41e6-4c01-aef0-c917cfa77cf2.png
[1]: https://user-images.githubusercontent.com/24855774/132934579-a20fa156-7d3c-4450-9fdb-072943c73b94.png
[2]: https://user-images.githubusercontent.com/24855774/132934750-52ecf533-1642-45f9-83f7-d059e21f531a.png
[3]: https://user-images.githubusercontent.com/24855774/132934731-c2a39113-2173-44e6-919b-d21967a9acc4.png

**Comment by LizIsTired** [comment]
Sorry, I've been busy IRL.
> Could it be hardware-dependent?

It might be possible that it's hardware dependant, but don't take my opinion, I have no idea how any of the Fabric API works lmao
|  | Vanilla           | Indigo        |
| ---|:-------------:|:-----:|
| Square      | ![2021-09-12_23 45 13](https://user-images.githubusercontent.com/13466206/133005111-f872d451-1082-4b9e-955c-49aa94de027c.png) | ![2021-09-12_23 40 48](https://user-images.githubusercontent.com/13466206/133005076-5f63d1a6-f9d1-4b11-b676-a065ad638b3b.png) |
| Staircase     | ![2021-09-12_23 45 53](https://user-images.githubusercontent.com/13466206/133005122-697e9387-d413-4b48-95f4-585e7ee1c6ac.png)      |   ![2021-09-12_23 46 46](https://user-images.githubusercontent.com/13466206/133005151-7840ea3c-b31a-4e22-8a63-74a4f03535c6.png) |

I'll also leave a copy of my logs and a clear F3 screenshot as well as my driver versions
[latest.log](https://github.com/FabricMC/fabric/files/7150423/latest.log)
![2021-09-12_23 54 49](https://user-images.githubusercontent.com/13466206/133005347-dcd42bd0-37d0-408c-91fe-dbc717f01499.png)
![image](https://user-images.githubusercontent.com/13466206/133005391-511b2e7f-31a3-4557-bd9c-acb2c36c0c7a.png)


edit: included driver versions from Radeon Software

**Comment by FwuffyPetsOwO** [comment]
![2021-09-12_16 10 00](https://user-images.githubusercontent.com/65428450/133005672-ddaa9947-58a4-414d-900c-6e3f351ffdd0.png)

As you can see, I have this issue as well. I am using an M1 Mac, and Fabric API 0.40.1.

**Comment by LizIsTired** [comment]
![2021-10-08_10 57 37](https://user-images.githubusercontent.com/13466206/136537184-4e8b73e6-76bf-4140-9144-6356b52565be.png)
Issue persists in FAPI 0.40.6, any new developments or at least any luck in reproducing?
