### ISSUE TITLE
Fabric 1.17.1 creates huge logs full of opengl errors.

### ISSUE THREAD

**Issue by toErIpNid** [FabricMC/fabric#1716]
Log: https://pastebin.com/e9DK7fiu

I've tested this with ONLY the Fabric API mod installed and opened the game up to its main menu and immediately closed it after once it loaded. The log was already up to about 800 kb in that time. This is quite the problem regarding bug reporting and storage space because logs can easily get over 30 MB within minutes of play.

**Comment by warjort** [comment]
Do you see the same thing with vanilla? It appears to be a known bug:
https://bugs.mojang.com/browse/MC-228532

This bug linked to that bug report suggests it is caused by thirdparty game overlays like Overwolf:
https://bugs.mojang.com/browse/MC-219985

**Comment by toErIpNid** [comment]
Considering I'm using the forge launcher I think we found our suspect.

**Comment by toErIpNid** [comment]
Hmm. After looknig at those links I'm not so sure anymore. They're talking about z fighting and other stuff but i'm not seeing any of that, just the errors.

**Comment by warjort** [comment]
> Considering I'm using the forge launcher

If you mean curseforge, there is an option to launch a vanilla game (top right I think?)
Can you try that and see if you still get the errors.

**Comment by toErIpNid** [comment]
Can confirm this bug also appears on 1.17 vanilla. Hmm. Mojank as usual I guess.
