### ISSUE TITLE
Multi-server chat "stitching"

### ISSUE THREAD

**Issue by LazerSharkGaming** [FabricMC/fabric#1717]
Lately with fabric I have been noticing bugs of where i leave a server (such as minehut), and I still get the chat messages in another server such as a privately hosted world. I can replicate the even live if needed. maybe it is caused from a client mod but I doubt it. I am not sure if both servers see my chat but i know I can only use commands of the active server. ill give a log on request.

**Comment by Technici4n** [comment]
Can you reproduce this with only Fabric API installed? Otherwise it might be another mod.

**Comment by OakBricks** [comment]
I think this is vanilla behavior, me and some of my friends have seen this happen multiple times under instances of Vanilla or OptiFine without a modloader, but it usually involves trying to connect, canceling immediately, and then joining another server.
