### ISSUE TITLE
MultiMC Fabric 1.14 Crashing "main"

### ISSUE THREAD

**Issue by fricotype0** [FabricMC/fabric#172]
I _think_ I am using the latest version of every mod I have. I am using MultiMC with Fabric and no matter what I do I cannot fix it. I am also terrible at reading logs so... yeah.

https://pastebin.com/DR3ejHip

**Comment by Blayyke** [comment]
Suppressed: java.lang.NoClassDefFoundError: net/minecraft/class_1789
        at net.simplegrinder.SimpleGrinderMod.onInitialize(SimpleGrinderMod.java:18)

Simple Grinder needs updating to the version you are running on before it will work.

**Comment by fricotype0** [comment]
Ok so... I deleted Simple Grinder and it works now...

**Comment by strikerrocker** [comment]
Can be closed?
