### ISSUE TITLE
Conflict with fabric-resource-loader-v0

### ISSUE THREAD

**Issue by xxDark** [FabricMC/fabric#1733]
Hello!
Firstly, thank you for making Fabric and letting everyone use it!
I'm making a mod that reduces Minecraft's resource loading time.
My mod conflicts with fabric-resource-loader-v0
The conflicting mixin may be found [here](https://github.com/xxDark/BetterLoading/blob/1.17/src/main/java/dev/xdark/betterloading/mixin/NamespaceResourceManagerMixin.java).
I wonder if it's possible to somehow make a workaround in Fabric for that?
Perhaps, these optimizations may be implemented in Fabric directly?
Thanks.

**Comment by warjort** [comment]
If you are going to use ````@Overwrite```` you are going to conflict with lots of mods, not just fabric.
https://github.com/SpongePowered/Mixin/wiki/Introduction-to-Mixins---Overwriting-Methods

"Overwrites and Intrinsic Proxies ... should nearly always be avoided when possible."

Fabric itself does a horrible ````@redirect```` which I guess you've found
and instanceof/threadlocal hacks which severely limits what other mods can do without breaking the mod resource packs.
https://github.com/FabricMC/fabric/blob/46582230fb580d4c1f71e4b0737df27417ec9cb1/fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/mixin/resource/loader/NamespaceResourceManagerMixin.java#L53
See also https://github.com/FabricMC/fabric/pull/1395, there's probably other relevant discussions if you use search.

**Comment by Technici4n** [comment]
Hi, I tried optimizing resource loading a few months ago, and only managed to get very small improvements most of the time. I see you are mixing into a ton of stuff - I'd recommend you benchmark each change separately to avoid needless changes.

Benchmarked optimizations are of course welcome in fabric API (e.g. #1564).

**Comment by Technici4n** [comment]
If you can provide benchmarks, we will be happy to accept such optimizations.
