### ISSUE TITLE
[21w38a] Crash creating new world with Eclipse

### ISSUE THREAD

**Issue by lordrius** [FabricMC/fabric#1748]
Hi!
I'm just updating my mod to 1.18 snapshots using [https://fabricmc.net/versions.html?&version=21w38a](url) and latest example-mod file. No errors in the project, run the game, mod is loaded but when I click Single player button it crashes saying this...
https://pastebin.com/dgbAwYgw

I try to compile the mod with no issues and loaded it in a new MultiMC instance using latest Fabric API (0.40.4) and no problems at all...

Any ideas?

Many thanks and excuse my English, I'm spanish. Also sorry if this issue is posted on the wrong spot.

Best regards!

**Comment by OroArmor** [comment]
Make sure you are using loom `0.10-SNAPSHOT` and not anything lower.

**Comment by lordrius** [comment]
Oops, my mistake, you're completely right, it works now...

Thank you very much and sorry for the inconvenience!

Best regards!
