### ISSUE TITLE
bug with my mods or fabric? 1.16.5 

### ISSUE THREAD

**Issue by Reinified** [FabricMC/fabric#1754]
Sorry if i'm being a nuisance, I don't know if this is from fabric or one of the mods i'm trying to use, but whenever i start up Minecraft it instantly crashes but it was working fine the other day.
 This is the only warnings i can find in the crash log:
```
[19:52:08] [main/INFO]: Loading for game Minecraft 1.16.5
[19:52:09] [ForkJoinPool-1-worker-1/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[19:52:09] [ForkJoinPool-1-worker-1/WARN]: The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column 12
[19:52:09] [ForkJoinPool-1-worker-1/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[19:52:09] [ForkJoinPool-1-worker-2/WARN]: The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column 12
[19:52:09] [ForkJoinPool-1-worker-3/WARN]: The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column 12
[19:52:09] [main/WARN]: Mod `{}` ({}) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
```
I don't really know much about programming so I can't find any way to fix it.

[Full Crash Log](https://github.com/FabricMC/fabric/files/7247942/latest.log)

**Comment by Juuxel** [comment]
There's nothing really pointing to a crash here (no error messages or anything). The warnings there shouldn't cause any issues either, so from that log at least, it's hard to say what's going on.

**Comment by warjort** [comment]
I have seen this kind of thing happen before. 
i.e. no error message in the log when mixin hits unexpected errors

e.g. https://github.com/FabricMC/fabric/issues/1676 where it was a duplicate definition of a new field by 2 different mods

The only thing I can suggest is removing mods individually until you find which ones are causing the problem.
(A "binary chop" where you start by removing half the mods is a more efficient way to do this https://en.wikipedia.org/wiki/Binary_search_algorithm)

The no error in the log is something that needs fixing (assuming the recent refactoring of early loading in fabric-loader hasn't already fixed it?)

**Comment by warjort** [comment]
> imm_ptl_core@0.99
> immersive_portals@0.99

Immersive portals has a long list of known incompatibilities so I would start with that?
https://github.com/qouteall/ImmersivePortalsMod/labels/Mod%20Compatibility

**Comment by Reinified** [comment]
immersive portals was working for me before i downloaded a few more mods, i removed identity because i tried loading it on its own and got an error, so im gonna try binary chop. Hopefully that works

**Comment by Reinified** [comment]
> 
> 
> There's nothing really pointing to a crash here (no error messages or anything). The warnings there shouldn't cause any issues either, so from that log at least, it's hard to say what's going on.

yeah i thought there shouldnt be any issues, but i just cant start the game at all so idk
