### ISSUE TITLE
OverworldBiomes.setRiverBiome() does not work for null rivers

### ISSUE THREAD

**Issue by maityyy** [FabricMC/fabric#1761]
According to the Biome API documentation, `OverworldBiomes.setRiverBiome(BiomeKeys.MOUNTAINS, null)` should remove rivers for the selected biome (in our case, it's `MOUNTAINS`), however the game crashes: https://pastebin.com/fbyy6704

**Comment by maityyy** [comment]
Maybe this is the reason
https://github.com/FabricMC/fabric/blob/46582230fb580d4c1f71e4b0737df27417ec9cb1/fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/InternalBiomeData.java#L130
```
Makes sure that the given registry key is mapped in {@link BuiltinBiomes}
```

**Comment by warjort** [comment]
The ````ensureIdMapping```` looks like something added in 1.16 to automatically fix old mods when the biome registration mechanism changed (i.e. when worldgen got added to datapacks).

It shouldn't be applying this fix to ````null```` data.

The only workaround I can see, is to use the internal method that bypasses the validation and the data fix.
````
net.fabricmc.fabric.impl.biome.InternalBiomeData.getOverworldRivers().put(BiomeKeys.MOUNTAIN, null);
````
