### ISSUE TITLE
[rfc / enhancement] Entity model json module for 1.17 and 1.18

### ISSUE THREAD

**Issue by ghost** [FabricMC/fabric#1775]
I'm writing this just after the Minecraft live event has concluded. 1.19 will be the update in which Wardens are added so it seems unlikely the new entity model code will be finished for 1.18.

Therefore it may be nice to have a module provided by fabric which will likely be removed in 1.19 which allows loading entity models from json files instead of all the code that is needed currently.

This issue is mainly to figure out a scope for the potential API and maybe to find a person to implement it, if I have free time I may be able to do so.

I propose this API only loads the models and not any other potential planned features for 1.19 e.g. animations.
I also don't think this new module should remove any existing api's implemented to help adding models through code.

**Comment by ethsanders** [comment]
Is there a reason that geckolib wouldn't work for the purpose of using json files?

**Comment by ghost** [comment]
No, but I don't want to use it.

**Comment by Technici4n** [comment]
This is probably out of scope for Fabric API.
