### ISSUE TITLE
Registration API for potion recipes

### ISSUE THREAD

**Issue by LemmaEOF** [FabricMC/fabric#178]
Right now, potion types and potion recipes are still not data-driven, and instead must be registered through private methods that add to private fields. Fabric should probably add a way to register new potion recipes so people don't have to make lots of identical Invoker mixins.

**Comment by asiekierka** [comment]
This would make a good PR. But it would probably be better to hook at the end of registerDefaults, and provide the necessary methods as lambdas to a registry impl class + registry API class exposing the registration methods.

**Comment by Technici4n** [comment]
This was implemented using transitive access wideners.
