### ISSUE TITLE
Fabric Events Lifecycle Crash

### ISSUE THREAD

**Issue by obewi** [FabricMC/fabric#1785]
When I try to join a world or create a world the game goes to joining world and then saving and then it crashes. I have NotEnoughCrashes installed and it's saying this is the bug.
![error](https://user-images.githubusercontent.com/75388592/138549057-dfd6f10b-4463-4b9c-80ee-7f9e39973dfc.png)
These are my mods.
![mods](https://user-images.githubusercontent.com/75388592/138549123-1da9053a-8971-40cb-8aea-c113608f912f.png)
And here is the crash report
https://bytebin.lucko.me/mmRxBKcb79

**Comment by OroArmor** [comment]
```
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_630.method_22698(net.minecraft.class_4587, net.minecraft.class_4588, int, int)" because "model" is null
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.46)
	at dev.tr7zw.waveycapes.VanillaCapeRenderer.render(VanillaCapeRenderer.java:18)
	at dev.tr7zw.waveycapes.renderlayers.CustomCapeRenderLayer.render(CustomCapeRenderLayer.java:68)
	at dev.tr7zw.waveycapes.renderlayers.CustomCapeRenderLayer.render(CustomCapeRenderLayer.java:25)
```
seems like its waveycapes, not lifecycle events

**Comment by obewi** [comment]
> ```
> java.lang.NullPointerException: Cannot invoke "net.minecraft.class_630.method_22698(net.minecraft.class_4587, net.minecraft.class_4588, int, int)" because "model" is null
> 	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.46)
> 	at dev.tr7zw.waveycapes.VanillaCapeRenderer.render(VanillaCapeRenderer.java:18)
> 	at dev.tr7zw.waveycapes.renderlayers.CustomCapeRenderLayer.render(CustomCapeRenderLayer.java:68)
> 	at dev.tr7zw.waveycapes.renderlayers.CustomCapeRenderLayer.render(CustomCapeRenderLayer.java:25)
> ```
> 
> seems like its waveycapes, not lifecycle events

Thanks so much, it was wavey capes removed it now and it works.
