### ISSUE TITLE
Could not find required mod: modmenu requires {minecraft @ [>=1.18-]}

### ISSUE THREAD

**Issue by MrDDog** [FabricMC/fabric#1788]
I have seen a few of these and the answer always is that you aren't using the right API... but it was working like 30min ago, I logged off logged back in and now it won't load. If I need to install a new API... which ? as I tried the most recent and same error.

**Comment by Technici4n** [comment]
You have installed a version of modmenu which requires minecraft >= 1.18. In other words, you installed a 1.18 modmenu for an older version of minecraft.
