### ISSUE TITLE
[Issue] Features added through FAPI biome modifications does not spawn in 1.18-snapshots

### ISSUE THREAD

**Issue by oliviathevampire** [FabricMC/fabric#1793]
When trying to add features to vanilla biomes using biome modifications it does say that it adds the features in the console but they does not seem to spawn

**Comment by ghost** [comment]
A quick workaround until this is fixed is to mixin into whatever method suits your feature in `DefaultBiomeFeatures`

**Comment by ghost** [comment]
Or use json

**Comment by oliviathevampire** [comment]
> A quick workaround until this is fixed is to mixin into whatever method suits your feature in `DefaultBiomeFeatures`

Ye, this is what I've been doing mostly but it's a lot more work.
