### ISSUE TITLE
Ok so everytime i dowenload The api for 1.17 it always go to 1.17.1 any fix?

### ISSUE THREAD

**Issue by Asgerblau** [FabricMC/fabric#1797]

**Comment by warjort** [comment]
Which version are you downloading?

When I look at curseforge, the last release for 1.17 rather than 1.17.1 was 0.36.0+1.17
https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/all?page=2
https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3358619

**Comment by Technici4n** [comment]
Please reopen if the issue persists.
