### ISSUE TITLE
Getting a api error

### ISSUE THREAD

**Issue by renegade2k82** [FabricMC/fabric#1798]
Getting a ''@Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:server.WorldChunkMixin::handler$ccd000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.'' Error.How do i fix this?

**Comment by Player3324** [comment]
This warning is safe to ignore
