### ISSUE TITLE
FAPI .42 Broken Ores

### ISSUE THREAD

**Issue by itsdinkd** [FabricMC/fabric#1805]
WIth the latest Fabric API Update for 1.17.1, Industrial Ore, TechReborn Ore, Things Gleaming Ore are broken and will not allow Pickaxes to drop the ore upon breaking. Using any normally required pickaxe to break these, all it does is break the block. 

If you have WTHIT Enabled, it also says the required harvested tool is a shear. Using a shear, you can get the ore content. 

Vanilla ore seems in tact. only certain modded ore is broken. 

![image](https://user-images.githubusercontent.com/35115304/140588731-b067bccd-54c8-4725-bc01-abdb859815a6.png)

![image](https://user-images.githubusercontent.com/35115304/140589054-b51eecd1-46f8-4784-b293-18a27406c0ee.png)

**Comment by Juuxel** [comment]
This doesn't reproduce in a pure Fabric API test environment (where blocks are created the same way as in TR or other mods). Could you post your full mod list? I suspect some other mod is interfering here with hacky code.

**Comment by itsdinkd** [comment]
It's currently on my modpack. Another Quality Modpack 2
Modlist: https://pastebin.com/Dk7tZSHg

This all worked on .41 so I don't believe it to be a mod in particular. 

With the last update where 0.42 was added, the following mods were updated; 
![image](https://user-images.githubusercontent.com/35115304/140590189-1324efb3-b1a0-4e60-8e3d-970b87f1321b.png)

**Comment by itsdinkd** [comment]
Gobber dev updated his mod after I told him this, fixing his ore. They now drop ore after breaking with pickaxes. Tech Reborn, Indrev, Things ore still broken. WTHIT still shows Shears on gobber2 ore. 

![image](https://user-images.githubusercontent.com/35115304/140591079-9e27e53c-cc74-4f02-b049-e0062674c179.png)

**Comment by modmuss50** [comment]
I was able to reproduce this with just TR and API, the pickake still works as expected, but clearly beign able to use shears is not right.

I will update TR to the new api soon, but this still needs fixing for other mods that cannot update as quick.

**Comment by itsdinkd** [comment]
![image](https://user-images.githubusercontent.com/35115304/140591221-af10155c-77c0-494f-9397-de37dc2513a3.png)
![image](https://user-images.githubusercontent.com/35115304/140591268-542f58c3-29d9-4762-b67f-6c235791941d.png)


Pick axe didn't work for me, only shears. @modmuss50

**Comment by itsdinkd** [comment]
Can confirm Gobber 2.4.57 caused the ore to not drop with pickaxes, regardless of Fabric API version. 

Shears issue still happened though on 0.42 allowing you to break ore with shears and get its dropped content, as modmuss mentioned.

**Comment by kwpugh** [comment]
I got Gobber working correctly in dev, I was misunderstanding the new tags but got some help sorting it out on the Fabric discord.
