### ISSUE TITLE
Problem regarding fabric

### ISSUE THREAD

**Issue by MCgamer2232** [FabricMC/fabric#1855]
Could not find required mod: fabric requires {minecraft @ [~1.18-alpha.21.37.a]}
This error is showing and the game is crashing in Tlauncher. Please help!

**Comment by Daomephsta** [comment]
You've installed a Fabric API version meant for Minecraft 21w37a on a Minecraft version that's older than 21w37a.

**Comment by MCgamer2232** [comment]
> You've installed a Fabric API version meant for Minecraft 21w37a on a Minecraft version that's older than 21w37a.

But when I am downloading 1.17.1 Fabric Api, it is still showing this error. There are no tutorials about fabric api for tlauncher, which makes it more difficult.

**Comment by oliviathevampire** [comment]
Why are you using 21w37a? Why not update to a newer version?

**Comment by Technici4n** [comment]
We don't support hacked clients, sorry.
