### ISSUE TITLE
Optifabric not working with latest fabric

### ISSUE THREAD

**Issue by MajiCoder** [FabricMC/fabric#1856]
Simple: I installed the latest fabric (0.12.5), fabric api, optifine, and optifabric. But when I try to start mc, the game crashes, saying that optifabric only supports 0.8 - 0.12, and so 0.12.5 is not supported. The curseforge page said that optifabric supported every new fabric release?

**Comment by warjort** [comment]
What is the real error message?

When I look at their fabric-mod.json is says:
````    "fabricloader": ">=0.8.0",````
https://github.com/Chocohead/OptiFabric/blob/7256ce016287db291a468f1199755ac0347fe689/src/main/resources/fabric.mod.json#L35
There is no upper bound of 0.12

Their gradle config says they are building/testing against 0.12.5
https://github.com/Chocohead/OptiFabric/blob/7256ce016287db291a468f1199755ac0347fe689/gradle.properties#L6
but this was only changed 3 days ago.
If your version of OptiFabric is older than that, it probably wasn't tested against 0.12.5

You would be better off reporting this to the OptiFabric project, but give them the real log/error message instead of your summary.

**Comment by warjort** [comment]
I see it did have that upper bound until 3 days ago;
````"fabricloader": ">=0.8.0 <0.12",````
https://github.com/Chocohead/OptiFabric/commit/fc09c5188fd7b8968976df07e7286dcb0ab0c97e#diff-882c6606823cf6c4e4114c1125850a04ed3180c48aef0e1467f1e4022b235db2

**Comment by MajiCoder** [comment]
net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Remove mod 'OptiFabric' (optifabric) 1.11.9 (C:\Users\Ezekiel\AppData\Roaming\.minecraft\mods\optifabric-1.11.9.jar).
Unmet dependency listing:
	 - Mod 'OptiFabric' (optifabric) requires any version between 0.8.0 (inclusive) and 0.12 (exclusive) of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.12.5!
		 - Mod 'Fabric Loader' (fabricloader) 0.12.5 is being loaded from C:\Users\Ezekiel\AppData\Roaming\.minecraft\libraries\net\fabricmc\fabric-loader\0.12.5\fabric-loader-0.12.5.jar
Inactive mods:
	 - mod 'OptiFabric' (optifabric) 1.11.9, reason: to remove
	 - mod 'Manningham Mills' (mm) 2.2, reason: inactive parent mod (nested jar)
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:183)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:48)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:203)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:183)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:119)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by MajiCoder** [comment]
Huh. Just realized, somehow I was posting in the fabric project instead of OptiFabric. I'll take it there then. Thanks anyways!

**Comment by TheDrawingCoder-Gamer** [comment]
i thought optifabric was deprecated? you probably shouldn't be using it. you can use lithium for performance, ok zoomer for zoom, and others. [OptiFabric alternatives](https://gist.github.com/LambdAurora/1f6a4a99af374ce500f250c6b42e8754)

**Comment by Technici4n** [comment]
Report to optifabric, it's not officially supported.
