### ISSUE TITLE
Datapack Overrides Not Applied For Existing Worlds

### ISSUE THREAD

**Issue by InsomniaKitten** [FabricMC/fabric#186]
When a mod (datapack) is loaded into an existing world, overrides to other namespaces (tested only with `minecraft`) are not applied. They only successfully apply when a new world is created with the mod loaded. This has been a bug since December but I forgot to actually report it (https://github.com/SleeplessDevelopment/PersistentCake/issues/3)

**Comment by Indi-Code** [comment]
Same here: Custom rock as example:
![image](https://user-images.githubusercontent.com/43734540/57894416-b2b1bc80-77fb-11e9-8f85-ebb5576b936a.png)

**Comment by Yanis48** [comment]
#66 is probably related to that
