### ISSUE TITLE
Whenever I look at water the game crashes

### ISSUE THREAD

**Issue by FinlandCountryball** [FabricMC/fabric#1861]

**Comment by frqnny** [comment]
what

**Comment by FinlandCountryball** [comment]
![image](https://user-images.githubusercontent.com/95002178/143328762-b916228a-2774-4b3c-ae8e-b5a72bfb38eb.png)
The game crashes and this error message shows up

**Comment by frqnny** [comment]
try updating all the mods including fabric api , otherwise show us full crash log

**Comment by FinlandCountryball** [comment]
i cant use optifabric with the latest fabric api tho

**Comment by frqnny** [comment]
That's probably the problem then. Why not post the full crash log in a **Github Gist** so we know what is going on fully?

**Comment by FinlandCountryball** [comment]
Where do i find the crash log?

**Comment by FinlandCountryball** [comment]
[crash-2021-11-24_16.24.57-client.txt](https://github.com/FabricMC/fabric/files/7599437/crash-2021-11-24_16.24.57-client.txt)
There you go

**Comment by frqnny** [comment]
It is likely an Optifabric compat issue. report it to them and do it by downloading the latest fabric api pls
