### ISSUE TITLE
Authenticate client in Intellij

### ISSUE THREAD

**Issue by maxsupermanhd** [FabricMC/fabric#1862]
How can I launch debugging session with my own account (Microsoft/Mojang)? I can generate token and manage it myself but where can I put it? Can I set a constant username at least?

I have a tool that caches my Minecraft token from Microsoft account and refreshes it accordingly, I just want a place to execute it and put token in but I don't see a spot for it...

**Comment by warjort** [comment]
The token is passed on the command line to minecraft. See the top of MinecraftClient.main()

For gradle builds you change parameters with a loom run configuration, 
e.g. inject parameters from a file as part of your build script

I guess with Intellij you are using some kind of launch configuration?
I don't know how you do the same thing there.

**Comment by warjort** [comment]
When this question was asked before, the "Auth Me" mod was suggested, see the bottom of here:
https://github.com/FabricMC/fabric/discussions/1618

**Comment by maxsupermanhd** [comment]
Alright, I did a bit of digging and it is actually a loom issue because fabric does not launch game and/or generate tasks to the intellij. Issue of loom: https://github.com/FabricMC/fabric-loom/issues/90
