### ISSUE TITLE
Fabric api crashing

### ISSUE THREAD

**Issue by atp892** [FabricMC/fabric#1863]
so on thursday november 25th i downloaded fabric for a portal mod and it said "requires fabric api" so i download fabric api and when i opened it it said "Failed To Open" my computer is a macbook air and the version is yosemite

**Comment by atp892** [comment]
pls help me

**Comment by modmuss50** [comment]
Can you provide the crash log please?

**Comment by atp892** [comment]
its not in minecraft

**Comment by atp892** [comment]
i can send you a video

**Comment by atp892** [comment]
oh its to big

**Comment by atp892** [comment]
![Screen Shot 2021-11-25 at 8 12 55 AM](https://user-images.githubusercontent.com/95035612/143456927-bb524d77-1725-4b68-a262-81bc42e3f6b3.png)

**Comment by atp892** [comment]
click on it to make it big

**Comment by modmuss50** [comment]
Fabric API is not an executable jar, its a normal mod that you install into the mods folder.

You can get the installer for fabric loader from: https://fabricmc.net/use/
