### ISSUE TITLE
Game crashes on start in 1.18-RC1

### ISSUE THREAD

**Issue by Angular-Angel** [FabricMC/fabric#1865]
When starting a singleplayer game in the new release candidate, the game crashes immediately on loading. This happens with both new and old worlds.

Crash Report: [crash-2021-11-25_15.04.40-client.txt](https://github.com/FabricMC/fabric/files/7605374/crash-2021-11-25_15.04.40-client.txt)

**Comment by modmuss50** [comment]
Please try updating fabric api to the version built for 1.18-rc1

**Comment by Angular-Angel** [comment]
Okay, yeah that works! Thank you, issue resolved. XD
