### ISSUE TITLE
Im getting error when i try to launch minecraft

### ISSUE THREAD

**Issue by Brudzik** [FabricMC/fabric#1868]
When im trying to launch minecraft i get error saying (im on version 1.17.1) : 
Could not find required mod: fabric requires {fabricloader @ [>+0.12.0]}
Installed mods list:
Latest Fabric api
Origins
Pehkui
sodium
![image](https://user-images.githubusercontent.com/95091086/143598214-ef05e298-469c-408c-be05-770ad48a7f3f.png)

**Comment by oliviathevampire** [comment]
You need newer version of Fabric Loader

**Comment by Juuxel** [comment]
Yeah, this issue is solved by updating to Fabric Loader 0.12.
