### ISSUE TITLE
ClientSidePacketRegistry.INSTANCE.register can be called on dedi server, resulting in crash

### ISSUE THREAD

**Issue by Boundarybreaker** [FabricMC/fabric#187]
`ClientSidePacketRegistry.INSTANCE.register()` doesn't have an embedded environment check, so if the code gets called on a dedicated server, it will crash due to NoClassDefFoundError for MinecraftClient.

**Comment by asiekierka** [comment]
It should only be called on the client side, though.

**Comment by Boundarybreaker** [comment]
Definitely, but I feel like it should either fail more quietly or have a specific crash, maybe `WrongSideException` or something, just so it's easier to instantly diagnose what's going on.

**Comment by liach** [comment]
Hmm, so @Boundarybreaker do you suggest marking `@Environment` on api methods exposed to mods?

**Comment by LemmaEOF** [comment]
I think it'd definitely be helpful, but we should make some changes to Loader first. I've made [an issue](https://github.com/FabricMC/fabric-loader/issues/232) for it.
