### ISSUE TITLE
Manningham Mills (Farbic-ASM) showing up in Mod Menu

### ISSUE THREAD

**Issue by Eiion** [FabricMC/fabric#1876]
With Minecraft v1.18 Manningham Mills (which apparently is Farbic-ASM if I'm informed correctly) shows up in the Mod Menu causing confusion what this mod (i.e. Manningham Mills) is supposed to be when nothing like it was downloaded and put into the mods folder by the user.

Should this be a hidden mod or at least named differently so people can make a connection to it being part of OptiFabric?

**Comment by modmuss50** [comment]
Please report to fabric asm or mod menu. This issue tracker is for issues realted directally to fabric api.

Thanks.

**Comment by Eiion** [comment]
Alright, done.

**Comment by mobmob1392** [comment]
this happened to me too . its a library for item physicsc mod
