### ISSUE TITLE
Should Fabric have one "fabric-tags" module for the tags it defines, or multiple?

### ISSUE THREAD

**Issue by asiekierka** [FabricMC/fabric#188]
FabricBlockTags/FabricItemTags in fabric-tags vs FabricToolTags/etc. in separate modules

I'm more partial to the former, as they all extend vanilla anyway - easier to maintain!

**Comment by liach** [comment]
Multiple please! Fabric tags module should add stuff such as tag entry removal and optional tag entries. It should never actually add tags, just like you don't have a module in a mod that add all your items and another for all your blocks.

**Comment by RedstoneParadox** [comment]
I would say a single module; they're all just tags anyways.

**Comment by liach** [comment]
each tag should be in the module that uses the tag, or the tag base module if multiple modules use the tag and depend on tag api.

**Comment by grondag** [comment]
We've established in other PRs that events belong with the module most related to what the events do. (Or a new module if there isn't one.)

Does that precedent apply here?  I'm skeptical that it does. Tags are more narrow in their scope and purpose, generally decoupled from the game code, and it does seem easier to maintain if they are all together.

@liach Are the some examples of bad things you are worried might happen if tags are all together?

**Comment by liach** [comment]
adding all tags into the tags module may create unnecessary dependencies on the tag extension module.

**Comment by MCrafterzz** [comment]
I second liach. The tool tag should be in the same package as other tool-related stuff

**Comment by i509VCB** [comment]
I think the decision has been that tags will live in their corresponding module based on tool attributes v1.

Closing since a standard has been established. If you disagree please open an RFC about it.
