### ISSUE TITLE
Possible infection of a PUP?

### ISSUE THREAD

**Issue by SpuSpu** [FabricMC/fabric#1886]
Hey yall recently I downloaded fabric for 1.18 and noticed that when I made a new chrome account that it automatically installed a program named "Web Safety" which I thought was odd so I looked into it and all the reviews were saying it was a PUP that infects free software such as GIMP or maybe in this case Fabric then I used Malwarebytes to look into this and a PUP came up and said this was malware as well, it may just be the case that this has been on my computer for a while and I am just an idiot but I figured I may just let you guys know so you can possibly look into it, given you are the people behind Fabric, like I said I am no expert on computers but Malwarebytes which I know are a credible source are saying stuff. 
![image](https://user-images.githubusercontent.com/63257609/144734101-84954503-9665-40b7-bbae-9f7431d4fc2f.png)
![image](https://user-images.githubusercontent.com/63257609/144734012-36b04262-e522-4f80-9a37-3c2829d8c889.png)

**Comment by frqnny** [comment]
where did u download it?? only from curseforge modrinth and fabricmc official website please

**Comment by modmuss50** [comment]
Please make sure to only download fabric from the official website: https://fabricmc.net/use/. As well as beign careful as to what other software and mods you download.

If you are still unsure you can use the .jar installer version, or even build it from source code.
