### ISSUE TITLE
Event wishlist

### ISSUE THREAD

**Issue by NikkyAI** [FabricMC/fabric#19]
please provided as much info as you possibly can,
like the classes to look at for mixins, which arguments are important
and link to a separate issue if it gets too much

- [ ] chat event | `String message, ServerPlayerEntity player` | #26
- [ ] death event | `DamageSource damageSource, ServerPlayerEntity player, String deathMessage`
- [ ] connect event | `player`
- [ ] disconnect event | `player, disconnectReason`
- [ ] achievement/progress event
- [ ] dimension change event | `ServerPlayerEntity player, fromDimension, toDimension`

very rough list of things i (might) require for future features

**Comment by strikerrocker** [comment]
- [ ] BlockBreakEvent (World,BlockPos)
- [ ] BlockPlaceEvent (World , BlockPos

**Comment by bafomdad** [comment]
[ ]  ItemPickupEvent (as part of the PlayerInteractionEvent package, since it is somewhat a player interaction)

**Comment by raphydaphy** [comment]
ClientRenderLast() event for rendering overlays

**Comment by InsomniaKitten** [comment]
> [ ] ItemPickupEvent (as part of the PlayerInteractionEvent package, since it is somewhat a player interaction)

This would ideally be accessible by the client, with some sort of hook into the pickup packet too.

**Comment by InsomniaKitten** [comment]
> ClientRenderLast() event for rendering overlays

Given that name, I assume you are taking inspiration from Forge's.. which is an awful event to use for overlay rendering. Forge has events specific for overlay rendering that aren't as generic as "render last" that Fabric should provide too. It would be an event that's called for each overlay element being drawn, pre-draw and post-draw.

**Comment by raphydaphy** [comment]
No your right, it's a bad forge inspired name, i just added last so its clear what I'm referring to

**Comment by i509VCB** [comment]
Assigned myself to open up individual event category issues for the mega issue as we are avoiding those now.

**Comment by Technici4n** [comment]
Please open specific issues (or even better: PRs), one per issue, if they still exist.
