### ISSUE TITLE
Could not find required mod: fabric requires {minecraft @ [~1.18-alpha.21.37.a]}

### ISSUE THREAD

**Issue by luhoha** [FabricMC/fabric#1900]
when i try booting up fabric it says Could not find required mod: fabric requires {minecraft @ [~1.18-alpha.21.37.a]}.

i have fabric api 1.17.1 and launched fabric 1.17.1
and i have a 1.17.1 mod
help

**Comment by Juuxel** [comment]
You have a 1.18 build of Fabric API. The 1.17 version is available here: https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3546670
