### ISSUE TITLE
Packet Compression possibly Disabled

### ISSUE THREAD

**Issue by Plecra** [FabricMC/fabric#1902]
https://github.com/FabricMC/fabric/blob/3f7d361425fdbd99261776649b0acf5bae941b47/fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/mixin/networking/ServerLoginNetworkHandlerMixin.java#L75-L78

This redirect appears to prevent the server from starting the packet compression handshake, so the connection never compresses chunk data. I wasn't able to find any context on why it's needed for the networking code, and the server ran fine with the original implementation replaced.

Is there another piece of code responsible for enabling compression, or is this what it looks like?

**Comment by modmuss50** [comment]
This appears to be handled here: https://github.com/FabricMC/fabric/blob/1.18/fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/impl/networking/server/ServerLoginNetworkAddon.java#L74

**Comment by Plecra** [comment]
It sure does! Thanks for checking that, clearly I need to get a better handle on iDEA's search :D
