### ISSUE TITLE
Fabric Api makes game lag

### ISSUE THREAD

**Issue by plW0lf** [FabricMC/fabric#191]
For a while when I'm using Fabric API game lags frequently when I'm trying to do anything.
Checked - minecraft 1.14.1 and fabric loader itself doesn't lags game.
Checked on other minecraft and fabric loader builds - the same lags

Edit:
Decided to downgrade FabricAPI to version 0.2.7 build 127 - there are no more lags.

Also in reply to @Juuxel - It may be related, however I had the same bugs even without mods other than Fabric API.

In addition: used ModMenu to check something - Fabric APIs build 157+ have weird error making appearance of about 20 mods instead 4 - may causing this lag

**Comment by Juuxel** [comment]
Possibly related to #173.

**Comment by Juuxel** [comment]
If the performance issues are caused by the bundled Fabric API, a similar bug could be caused by the nested structure of Fabric API 0.3.

**Comment by asiekierka** [comment]
I am pretty confident I know what's going on. I guess I can't escape the need to take a wrench to the whole thing :-)

**Comment by calloatti** [comment]
This has been solved for me using 0.4.7 build 153. All lag on first use is gone. Thank you.

**Comment by asiekierka** [comment]
yes
