### ISSUE TITLE
mod making error on visual studio code

### ISSUE THREAD

**Issue by ItsTigre** [FabricMC/fabric#1919]
im trying to make a mod that adds more tools and weapons and i followed a yt tutorial for that but when i debugged it it said this 
[{
	"resource": "/C:/Users/raul_/Desktop/Weapons/",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "0",
	"severity": 8,
	"message": "The supplied phased action failed with an exception.\r\nA problem occurred configuring root project 'Weapons'.\r\nFailed to provide net.fabricmc:yarn:1.18.1+build.1 : java.lang.RuntimeException: Failed to remap minecraft\r\nFailed to remap minecraft\r\nFailed to remap JAR C:\\Users\\raul_\\.gradle\\caches\\fabric-loom\\1.18.1\\minecraft-merged.jar with mappings from C:\\Users\\raul_\\.gradle\\caches\\fabric-loom\\1.18.1\\net.fabricmc.yarn.1_18_1.1.18.1+build.1-v2\\mappings.tiny\r\nC:\\Users\\raul_\\.gradle\\caches\\fabric-loom\\1.18.1\\net.fabricmc.yarn.1_18_1.1.18.1+build.1-v2\\minecraft-intermediary.jar",
	"source": "Java",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}]

and this

 [{
	"resource": "/C:/Users/raul_/Desktop/Weapons/build.gradle",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "0",
	"severity": 8,
	"message": "The supplied phased action failed with an exception.\r\nA problem occurred configuring root project 'Weapons'.\r\nBuild file 'C:\\Users\\raul_\\Desktop\\Weapons\\build.gradle' line: 2\r\nAn exception occurred applying plugin request [id: 'fabric-loom', version: '0.10-SNAPSHOT']\r\nFailed to apply plugin 'fabric-loom'.\r\nYou are using an outdated version of Java (11). Java 16 or higher is required.",
	"source": "Java",
	"startLineNumber": 2,
	"startColumn": 1,
	"endLineNumber": 2,
	"endColumn": 1
}]
i dont know anything about the first one but for the second one i did downloaded the 16.0.2 version of java the next link is a picture of the file on my pc ![javavavava](https://user-images.githubusercontent.com/57403757/146812630-b8b31975-b690-4835-b8fe-4746ee8675b4.PNG)
but it stil says that at first i also had a error about JAVA_HOME but i fixed that by following the steps on this site
https://stackoverflow.com/questions/44081972/windows-10-gradle-java-home-is-set-to-an-invalid-directory
and also when i just proceed it loads for some time and then it sais the game crashed

crash log;
---- Minecraft Crash Report ----
// There are four lights!

Time: 20/12/2021 18:51
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'specialweapons'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:518)
	at net.minecraft.client.main.Main.main(Main.java:178)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
Caused by: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'main' provided by 'specialweapons'
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 12 more
Caused by: net.fabricmc.loader.api.LanguageAdapterException: java.lang.ClassNotFoundException: tigre007007.special.weapons
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:52)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	... 13 more
Caused by: java.lang.ClassNotFoundException: tigre007007.special.weapons
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	... 15 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:518)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:Geavanceerde Windows 32 basis-API:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:Bibliotheek met elementen voor gebruikerservaring:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:Crypto-API32:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.19041.867 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:API DLL van DNS Client:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.19041.1202 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP Helper API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:DLL-bestand voor Windows NT BASE API-client:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:DLL-bestand voor Windows NT BASE API-client:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
		NLAapi.dll:Network Location Awareness 2:10.0.19041.1151 (WinBuild.160101.0800):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.19041.610 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		Ole32.dll:Microsoft OLE voor Windows:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
		OleAut32.dll:OLEAUT32.DLL:10.0.19041.985 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Windows Performance Data Helper DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:Runtime voor RPC (Remote Procedure Call):10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Gemeenschappelijk DLL-bestand van Windows Shell:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
		USER32.dll:DLL-bestand voor Windows USER API-client (meerdere gebruikers):10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.27.29016.0 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Windows HTTP-services:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0 32-bits DLL-bestand:10.0.19041.1081 (WinBuild.160101.0800):Microsoft Corporation
		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		Wldp.dll:Vergrendelingsbeleid van Windows:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.19041.746 (WinBuild.160101.0800):Microsoft Corporation
		bcrypt.dll:Windows-bibliotheek van cryptografische primitieven:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:Microsoft COM voor Windows:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.19041.789 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc.DLL:DHCP Client-service:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc6.DLL:DHCPv6-client:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
		dt_socket.dll:OpenJDK Platform binary:17.0.1.0:Eclipse Adoptium
		fwpuclnt.dll:API voor FWP/IPsec in gebruikersmodus:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.19041.1387 (WinBuild.160101.0800):Microsoft Corporation
		iertutil.dll:Runtime-hulpprogramma voor Internet Explorer:11.00.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
		java.dll:OpenJDK Platform binary:17.0.1.0:Eclipse Adoptium
		java.exe:OpenJDK Platform binary:17.0.1.0:Eclipse Adoptium
		jdwp.dll:OpenJDK Platform binary:17.0.1.0:Eclipse Adoptium
		jemalloc.dll
		jimage.dll:OpenJDK Platform binary:17.0.1.0:Eclipse Adoptium
		jli.dll:OpenJDK Platform binary:17.0.1.0:Eclipse Adoptium
		jna2174680960780076990.dll:JNA native library:6.1.1:Java(TM) Native Access (JNA)
		jvm.dll:OpenJDK 64-Bit server VM:17.0.1.0:Eclipse Adoptium
		kernel.appcore.dll:AppModel API Host:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		lwjgl.dll
		management.dll:OpenJDK Platform binary:17.0.1.0:Eclipse Adoptium
		management_ext.dll:OpenJDK Platform binary:17.0.1.0:Eclipse Adoptium
		msvcp140.dll:Microsoft® C Runtime Library:14.27.29016.0 built by: vcwrkspc:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.19041.789 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Microsoft Windows Sockets 2.0 Service-aanbieder:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:Shim-provider van e-mailnamen:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
		ncrypt.dll:Windows NCrypt Router:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:OpenJDK Platform binary:17.0.1.0:Eclipse Adoptium
		netutils.dll:Net Win32 API Helpers DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		nio.dll:OpenJDK Platform binary:17.0.1.0:Eclipse Adoptium
		ntdll.dll:DLL-bestand voor NT-laag:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
		perfos.dll:DLL-bestand voor prestatiemeterobjecten van Windows-systeem:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
		pnrpnsp.dll:PNRP-naamruimteprovider:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.19041.844 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		shlwapi.dll:Shell lichtgewicht hulpprogrammabibliotheek:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
		srvcli.dll:Server Service Client DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		sunmscapi.dll:OpenJDK Platform binary:17.0.1.0:Eclipse Adoptium
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.19041.789 (WinBuild.160101.0800):Microsoft Corporation
		urlmon.dll:OLE32-extensies voor Win32:11.00.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.27.29016.0 built by: vcwrkspc:Microsoft Corporation
		verify.dll:OpenJDK Platform binary:17.0.1.0:Eclipse Adoptium
		win32u.dll:Win32u:10.0.19041.1387 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:Microsoft WinRT-opslag-API:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:OpenJDK Platform binary:17.0.1.0:Eclipse Adoptium
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:178)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Eclipse Adoptium
	Memory: 698022912 bytes (665 MiB) / 1660944384 bytes (1584 MiB) up to 6429868032 bytes (6132 MiB)
	CPUs: 4
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 3 3200G with Radeon Vega Graphics    
	Identifier: AuthenticAMD Family 23 Model 24 Stepping 1
	Microarchitecture: Zen / Zen+
	Frequency (GHz): 3,59
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce GT 730
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 2048,00
	Graphics card #0 deviceId: 0x1287
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7141
	Memory slot #0 capacity (MB): 8192,00
	Memory slot #0 clockSpeed (GHz): 2,13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192,00
	Memory slot #1 clockSpeed (GHz): 2,13
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192,00
	Memory slot #2 clockSpeed (GHz): 2,13
	Memory slot #2 type: DDR4
	Virtual memory max (MB): 28108,42
	Virtual memory used (MB): 11401,01
	Swap memory total (MB): 3584,00
	Swap memory used (MB): 0,00
	JVM Flags: 4 total; -Xdebug -Xnoagent -Xrunjdwp:transport=dt_socket,address=localhost:61231,server=n,suspend=y -XX:+ShowCodeDetailsInExceptionMessages
	Fabric Mods: 
		fabric: Fabric API 0.44.0+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cdc8
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.4.0+16d92c47c8
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a9c8
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d95c8
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d95c8
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cdc8
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c6c8
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73dc8
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d95c8
		fabric-data-generation-api-v1: Fabric Data Generation API (v1) 1.0.0+3fec4ad9c8
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.7+43d29571c8
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378ac8
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f17c8
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cdc8
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d95c8
		fabric-gametest-api-v1: Fabric Game Test API (v1) 1.0.5+03d159cfc8
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b5c8
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d95c8
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f3c8
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cdc8
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca335c8
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d95c8
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d95c8
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.7+b4f4f6cdc8
		fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d95c8
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d95c8
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cdc8
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.0+3b82842ec8
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.8+3ac43d95c8
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1acc8
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.8.5+3ac43d95c8
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.9+3ac43d95c8
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.12+3ac43d95c8
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cdc8
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d7c8
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d95c8
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cdc8
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378ac8
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d95c8
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d95c8
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d95c8
		fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a7c8
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d95c8
		fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d95c8
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.4+7de09f55c8
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.5+b4f4f6cdc8
		fabricloader: Fabric Loader 0.12.12
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.18.1
		specialweapons: Special Weapons ${version}
	Launched Version: Fabric
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

**Comment by ItsTigre** [comment]
i fixed the second error about java i need 17.0.1 so only the first one is cousing trouble

**Comment by warjort** [comment]
> Caused by: net.fabricmc.loader.api.LanguageAdapterException: java.lang.ClassNotFoundException: tigre007007.special.weapons
at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:52)

Do you really have a class called  ````tigre007007.special.weapons```` or did you mistype it in your fabric.mod.json?


Maybe related?
> specialweapons: Special Weapons ${version}

I guess this points to your fabric.mod.json not going through variable substitution?

**Comment by ItsTigre** [comment]
i do the person in the video tld me to use my minecraft user name and then mod nam
![saved file](https://user-images.githubusercontent.com/57403757/146821061-d9a8c971-7a9c-48e0-916c-799963d65065.PNG)
e

**Comment by warjort** [comment]
I think from the left hand side of your screen shot, that the class name you used for your entry point is
````tigre007007.special.weapons.SpecialWeapons````

**Comment by warjort** [comment]
Your screen shot also shows errors with you trying to use java 11 for your build.

**Comment by ItsTigre** [comment]
yes but i have the new version installed

**Comment by ItsTigre** [comment]
but he doest say its there or somthing idk ? btw look u mean this 
![saved file 2](https://user-images.githubusercontent.com/57403757/146824461-496550ee-606a-44b9-8767-8cff2535a7ca.PNG)
?

**Comment by warjort** [comment]
> btw look u mean this

Yes, the entrypoint is a class name that fabric invokes so you can initialise your mod.
You had the specified just the package name instead.

**Comment by ItsTigre** [comment]
if i start it like that i still get this error
[{
	"resource": "/C:/Users/raul_/Desktop/Weapons/build.gradle",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "0",
	"severity": 8,
	"message": "The supplied phased action failed with an exception.\r\nA problem occurred configuring root project 'Weapons'.\r\nBuild file 'C:\\Users\\raul_\\Desktop\\Weapons\\build.gradle' line: 2\r\nAn exception occurred applying plugin request [id: 'fabric-loom', version: '0.10-SNAPSHOT']\r\nFailed to apply plugin 'fabric-loom'.\r\nYou are using an outdated version of Java (11). Java 16 or higher is required.",
	"source": "Java",
	"startLineNumber": 2,
	"startColumn": 1,
	"endLineNumber": 2,
	"endColumn": 1
}]

**Comment by ItsTigre** [comment]
oke so it started up but it still says that i have a old version of java

**Comment by warjort** [comment]
That's what I said above. 
You have VSC configured to build with Java 11 when you need Java 16/17 for recent minecraft versions.

I am no expert on VSC, but there will be a configuration option for either your java or gradle extension.

I would guess it defaults to whatever is in your system path or you specified in the default environment variables as ````JAVA_HOME````

NOTE: Wherever you change the configuration, you will need to restart VSC and/or any background gradle daemons that might be running, to make sure they pick up the new configuration(s).

**Comment by ItsTigre** [comment]
how do i restart all of that

**Comment by warjort** [comment]
> how do i restart all of that

Restarting your computer is the easiest way if you don't want to read the fine manual. ;-)

**Comment by ItsTigre** [comment]
u maby have discord so we can talk this more true ?
her is mine if u have it 
TigerReborn# 0180
but with no space

**Comment by ItsTigre** [comment]
becus now after pc restart it sais this again
[{
	"resource": "/C:/Users/raul_/Desktop/Weapons/",
	"owner": "_generated_diagnostic_collection_name_#4",
	"code": "0",
	"severity": 8,
	"message": "The supplied phased action failed with an exception.\r\nA problem occurred configuring root project 'Weapons'.\r\nFailed to provide net.fabricmc:yarn:1.18.1+build.1 : java.lang.RuntimeException: Failed to remap minecraft\r\nFailed to remap minecraft\r\nFailed to remap JAR C:\\Users\\raul_\\.gradle\\caches\\fabric-loom\\1.18.1\\minecraft-merged.jar with mappings from C:\\Users\\raul_\\.gradle\\caches\\fabric-loom\\1.18.1\\net.fabricmc.yarn.1_18_1.1.18.1+build.1-v2\\mappings.tiny\r\nC:\\Users\\raul_\\.gradle\\caches\\fabric-loom\\1.18.1\\net.fabricmc.yarn.1_18_1.1.18.1+build.1-v2\\minecraft-intermediary.jar",
	"source": "Java",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}]

**Comment by ItsTigre** [comment]
and the discord is TigerReborn#0180
i forgot a number above

**Comment by ItsTigre** [comment]
oke i cant put a zero at start for a reason
its zero one eight zero

**Comment by warjort** [comment]
Sorry I don't use discord.

The error message you posted is not very informative its one of those long winded gradle/loom error messages that just says "it didn't work".

Can you look at the gradle build log and confirm you are using java16+
It looks like this in VSC (accessed from menu view/output):
![image](https://user-images.githubusercontent.com/275258/146833845-d1228d0e-2a8b-42f2-a05e-b41e65339184.png)

If there is nothing there, just run a gradle task like "build"
![image](https://user-images.githubusercontent.com/275258/146834463-641b9a0f-21f8-46bf-a118-bfc8043dd087.png)

But you really are asking for help in the wrong place on this.
This is issues section for the modding api of fabric.
You want somebody that can help you with VSC/gradle/java build configuration.

**Comment by intact** [comment]
did you set java 17 for `Java › Import › Gradle › Java: Home` too?

**Comment by ItsTigre** [comment]
![image](https://user-images.githubusercontent.com/57403757/146836205-88b38a07-1449-4e95-a3dc-972796b50a9d.png)
only have that there
and where do i ask about this stuff then ?

**Comment by ItsTigre** [comment]
i just have this error 
The supplied phased action failed with an exception.
A problem occurred configuring root project 'Weapons'.
Failed to provide net.fabricmc:yarn:1.18.1+build.1 : java.lang.RuntimeException: Failed to remap minecraft
Failed to remap minecraft
Failed to remap JAR C:\Users\raul_\.gradle\caches\fabric-loom\1.18.1\minecraft-merged.jar with mappings from C:\Users\raul_\.gradle\caches\fabric-loom\1.18.1\net.fabricmc.yarn.1_18_1.1.18.1+build.1-v2\mappings.tiny
C:\Users\raul_\.gradle\caches\fabric-loom\1.18.1\net.fabricmc.yarn.1_18_1.1.18.1+build.1-v2\minecraft-intermediary.jar

and this error

The supplied phased action failed with an exception.
A problem occurred configuring root project 'Weapons'.
Build file 'C:\Users\raul_\Desktop\Weapons\build.gradle' line: 2
An exception occurred applying plugin request [id: 'fabric-loom', version: '0.10-SNAPSHOT']
Failed to apply plugin 'fabric-loom'.
You are using an outdated version of Java (11). Java 16 or higher is required.

and i wanna fix them but dont know how and i have the latest version of the java installed
![image](https://user-images.githubusercontent.com/57403757/146836511-2650a9fb-ca97-447a-9af8-8c32edeaec8b.png)

**Comment by intact** [comment]
open settings in vs code and search `java home` there

**Comment by ItsTigre** [comment]
![image](https://user-images.githubusercontent.com/57403757/146836793-3fa2854a-bf61-48f0-b863-56e5de6f45b9.png)
yess and then ?

**Comment by intact** [comment]
set path for `Java › Import › Gradle › Java: Home`

**Comment by ItsTigre** [comment]
C:\Program Files\Java\jdk-17.0.1
you mean that ?
in there on visual studio

**Comment by intact** [comment]
yes, something like that

**Comment by ItsTigre** [comment]
witch one do i need to put there
![image](https://user-images.githubusercontent.com/57403757/146840761-a3871451-d6bc-4905-9ee1-c1a8f04bf31d.png)

**Comment by intact** [comment]
you can use java 17 for any Minecraft version (and you need java 17 for Minecraft 1.18)

**Comment by ItsTigre** [comment]
like that right, beed i accept or save it somwhere ?
![image](https://user-images.githubusercontent.com/57403757/146842022-723dadee-8454-4d6f-8ebb-515b2bdac8ad.png)

**Comment by intact** [comment]
no,  `Java › Import › Gradle › Java: Home` is second one

**Comment by ItsTigre** [comment]
an what can i do about this error ? if i click on it it doesnt show me where the error is it trys to open somthing and then it closes emidiatly

The supplied phased action failed with an exception.
A problem occurred configuring root project 'Weapons'.
Failed to provide net.fabricmc:yarn:1.18.1+build.1 : java.lang.RuntimeException: Failed to remap minecraft
Failed to remap minecraft
Failed to remap JAR C:\Users\raul_\.gradle\caches\fabric-loom\1.18.1\minecraft-merged.jar with mappings from C:\Users\raul_\.gradle\caches\fabric-loom\1.18.1\net.fabricmc.yarn.1_18_1.1.18.1+build.1-v2\mappings.tiny
C:\Users\raul_\.gradle\caches\fabric-loom\1.18.1\net.fabricmc.yarn.1_18_1.1.18.1+build.1-v2\minecraft-intermediary.jar

**Comment by ItsTigre** [comment]
not fixed
