### ISSUE TITLE
BlockEntityType's registry is not synced on 1.18.x, causing desyncs

### ISSUE THREAD

**Issue by Patbox** [FabricMC/fabric#1921]
Since 1.18, Minecraft uses raw BlockEntityType ids in packet for syncing data (BlockEntityUpdateS2CPacket).
Fabric currently doesn't sync these, which can cause desyncs.

Placing PipeBlock, and displaying Block (Entity) update packets, uses wrong BlockEntityType
![image](https://user-images.githubusercontent.com/39821509/146895307-bbea2b5b-840b-4fed-937e-cb2d57c83203.png)

Effected packet's serialization
![image](https://user-images.githubusercontent.com/39821509/146895438-95df7ee7-19eb-46d3-bab6-0d9afe87b0ee.png)

Effected line: https://github.com/FabricMC/fabric/blob/1.18/fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/impl/registry/sync/FabricRegistryInit.java#L89

**Comment by modmuss50** [comment]
That’s annoying. At least it’s a trivial fix.
