### ISSUE TITLE
java.lang.StackOverflowError: Exception in server tick loop

### ISSUE THREAD

**Issue by calloatti** [FabricMC/fabric#193]
MC crashed 2 times when right clicking a Villager to trade. The second time the villager was a baby villager if that matters.

No idea if this is fabric but I don't see any mod name in the log.

https://paste.ee/p/9ABmB

**Comment by calloatti** [comment]
After more crashes, it seems that the crash happens when one player right clicks a baby villager, or when two players right click on the same adult villager to trade.

**Comment by Prospector** [comment]
This looks to be the fault of a mod that adds ragdoll physics to entity models. Please refer this issue to whatever mod does that.
