### ISSUE TITLE
FabricBlockSettings generic constructor is missing copy methods for certain settings

### ISSUE THREAD

**Issue by Hugman76** [FabricMC/fabric#1947]
The FabricBlockSettings constructor does not copy values for the following attributes:
- `allowsSpawningPredicate`
- `solidBlockPredicate`
- `suffocationPredicate`
- `blockVisionPredicate`
- `postProcessPredicate`
- `emissiveLightingPredicate`

This would also require new mixin getters for the `AbstractBlockSettingsAccessor`

Issue on the following version:
```properties
yarn_mappings=1.18.1+build.14
fabric_version=0.45.0+1.18
```

**Comment by Technici4n** [comment]
See also #1873. A PR would be welcome I think. :wink:
