### ISSUE TITLE
Struggling to figure out why modpack is crashing upon launch

### ISSUE THREAD

**Issue by shembyy** [FabricMC/fabric#1970]
Title says it all. I'm fairly certain I know the mod that is causing the issues, however I am unsure of what specifically is wrong and how to fix it since I'm not the most tech-savvy. Below is the crash log provided. I've gone in and made sure that I have all the dependencies for Extra Alchemy, however the crashes still continue and I'm at a loss. Any help is appreciated. 

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 1/23/22 6:07 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'extraalchemy'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils$$Lambda$4212/1210569727.apply(Unknown Source)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:437)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	
Caused by: java.lang.NoSuchFieldError: BASE
	at zabi.minecraft.extraalchemy.compat.pehkui.ModSizeModifiers.registerModifiers(ModSizeModifiers.java:29)
	at zabi.minecraft.extraalchemy.compat.pehkui.PehkuiCompatBridge.init(PehkuiCompatBridge.java:18)
	at zabi.minecraft.extraalchemy.ExtraAlchemy.onInitialize(ExtraAlchemy.java:33)
	at net.fabricmc.loader.impl.game.minecraft.Hooks$$Lambda$2220/1450729045.accept(Unknown Source)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils$$Lambda$4212/1210569727.apply(Unknown Source)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:437)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1572898280 bytes (1500 MB) / 2244476928 bytes (2140 MB) up to 6055002112 bytes (5774 MB)
	CPUs: 12
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6496m -Xms256m
	Fabric Mods: 
		advancementbook: Advancement Book 1.0.4
		advancements-enlarger: Advancements Enlarger 0.2.3
		advdebug: Advancements Debug 2.3.0
		adventurez: AdventureZ 1.2.6
		amecsapi: Amecs API 1.1.4+mc1.16.5
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		animal_feeding_trough: Animal Feeding Trough 1.0.2
		anvil_fix: AnvilFix 1.2.1-1.16
		appleskin: AppleSkin mc1.16.4-2.2.0
		aqupdgrizzly: Grizzly Bear mob 1.16-1.2.2
		architectury: Architectury 1.28.48
		armorsoundtweak: Armor Sound Tweak 3.1.1
		artifacts: Artifacts 4.0.3+fabric
		artifice: Artifice 0.14.6+1.16.5
		autoconfig1u: Auto Config v1 Updated 3.3.1
		awesomedungeon: Awesome Dungeon 2.0.4
		axesareweapons: Axes Are Weapons 1.5.1
		backslot: BackSlot 1.1.11
		backslotaddon: BackSlot Addon 1.0.3
		bannerpp: Banner++ 2.0.3-snapshot+mc.1.16.2-rc1
		basicshields: Basic Shields [Fabric] 1.2.1-1.16.5
		battletowers: Battle Towers 3.3.4-1.16.4
		bclib: BCLib 0.1.45
		bedspreads: Bedspreads 1.3.1-1.16.4
		beenfo: Beenfo 1.16.5-fabric0.30.0-1.3.2
		betteranimalsplus: Better Animals Plus 1.16.5-11.0.3
		betterbiomeblend: Better Biome Blend 1.16.4-1.2.9-fabric
		bettercaves: YUNG's Better Caves 1.16.5-1.2
		betterdungeons: YUNG's Better Dungeons 1.16.5-1.0.1
		betterend: Better End 0.9.8.5-pre
		betterf3: BetterF3 1.1.3
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0.2
		betternether: Better Nether 5.0.7
		betterstrongholds: YUNG's Better Strongholds 1.16.5-1.1.1
		betterthanmending: BetterThanMending 1.3.0
		blue_endless_jankson: jankson 1.2.0
		blur: Blur (Fabric) 2.1.0
		bowinfinityfix: Bow Infinity Fix rv9
		byg: BYG 1.3.5
		caelus: Caelus API 0.0.15-1.16.4
		campanion: Campanion 1.3.5
		cardinal-components: Cardinal Components API 2.8.3
		cardinal-components-base: Cardinal Components API (base) 2.8.3
		cardinal-components-block: Cardinal Components API (blocks) 2.8.3
		cardinal-components-chunk: Cardinal Components API (chunks) 2.8.3
		cardinal-components-entity: Cardinal Components API (entities) 2.8.3
		cardinal-components-item: Cardinal Components API (items) 2.8.3
		cardinal-components-level: Cardinal Components API (world saves) 2.8.3
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.8.3
		cardinal-components-util: Cardinal Components API (utilities) 2.8.3
		cardinal-components-world: Cardinal Components API (worlds) 2.8.3
		charm: Charm 2.3.2
		charmonium: Charmonium 2.3.2
		cherishedworlds: Cherished Worlds 2.0.1-1.16.5
		chipped: Chipped 1.1.1
		cloth-api: Cloth API 1.6.59
		cloth-armor-api-v1: Cloth Armor API v1 1.6.59
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-client-events-v0: Cloth Client Events v0 1.6.59
		cloth-common-events-v1: Cloth Common Events v1 1.6.59
		cloth-config2: Cloth Config v4 4.13.49
		cloth-datagen-api-v1: Cloth Datagen v1 1.6.59
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.6.59
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.6.59
		cloth-scissors-api-v1: Cloth Scissors API v1 1.6.59
		cloth-utils-v1: Cloth Utils v1 1.6.59
		com_electronwill_night-config_core: core 3.6.5
		com_electronwill_night-config_toml: toml 3.6.5
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		controlling: Controlling For Fabric 1.1.2
		couplings: Couplings 1.5.0+1.16
		craftpresence: CraftPresence 1.8.8
		croptopia: Croptopia 1.4.0
		crowdin-translate: CrowdinTranslate 1.3+1.16
		cullleaves: Cull Leaves 2.1.0
		curioofundying: Curio of Undying 1.1.1-1.16.5
		curios: Curios API 0.0.13-1.16.5
		curiouselytra: Curious Elytra 1.1.1-1.16.5
		darkpaintings: DarkPaintings 3.0.4
		dawn: Dawn API 1.8
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.4
		dungeons_arise: When Dungeons Arise 1.16.5-2.1.47-fabric
		dynamicsoundfilters: Dynamic Sound Filters 1.2.0+1.16.5
		eggtab: Egg Tab 2.1.0+1.16-fabric
		eldritch_mobs: Eldritch Mobs 1.8.0
		enchdesc: EnchantmentDescriptions 2.0.8
		entitybanners: Entity Banners 1.0-BETA
		entityculling: EntityCulling-Fabric 1.3.0
		expandability: ExpandAbility 2.0.1
		explorerscompass: Explorer's Compass 1.16.5-2.0.2-fabric
		extraalchemy: Extra Alchemy 1.4.5
		fabric: Fabric API 0.42.0+1.16
		fabric-api-base: Fabric API Base 0.4.0+3cc0f0907d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.1+3cc0f0907d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.13+3cc0f0907d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.6+3cc0f0907d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+3cc0f0907d
		fabric-commands-v0: Fabric Commands (v0) 0.2.3+3cc0f0907d
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+3cc0f0907d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.5+3cc0f0907d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.4+3cc0f0907d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.8+3cc0f0907d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.4+3cc0f0907d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.5+3cc0f0907d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.2+3cc0f0907d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+3cc0f0907d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.2+3cc0f0907d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.1+3cc0f0907d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.5+3cc0f0907d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+3cc0f0907d
		fabric-language-kotlin: Fabric Language Kotlin 1.7.0+kotlin.1.6.0
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.2+3cc0f0907d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.3+3cc0f0907d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.4+3cc0f0907d
		fabric-models-v0: Fabric Models (v0) 0.3.1+3cc0f0907d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.3+e3c9d0627d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.9+3cc0f0907d
		fabric-networking-v0: Fabric Networking (v0) 0.3.3+3cc0f0907d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.6+3cc0f0907d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+3cc0f0907d
		fabric-particles-v1: Fabric Particles (v1) 0.2.5+3cc0f0907d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.6+3cc0f0907d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.5+3cc0f0907d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.5+3cc0f0907d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.1+3cc0f0907d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+3cc0f0907d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.15+3cc0f0907d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.3+3cc0f0907d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.1+3cc0f0907d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+3cc0f0907d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.1+3cc0f0907d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.6+3cc0f0907d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.12+3cc0f0907d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.2+3cc0f0907d
		fabric-textures-v0: Fabric Textures (v0) 1.0.7+3cc0f0907d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.8+3cc0f0907d
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.0+3cc0f0907d
		fabricloader: Fabric Loader 0.12.12
		fabricshieldlib: Fabric Shield Lib 1.4.5+1.16
		fallingleaves: Falling Leaves 1.6.0+1.16.5
		fallingtree: FallingTree 2.11.5
		farmersdelight: Farmer's Delight 1.16.5-0.0.7
		fatxporbs: Fat Experience Orbs 0.0.9
		ferritecore: FerriteCore 2.0.3
		fiber: fiber 0.23.0-2
		fiber2cloth: Fiber To Cloth 3.0.1
		fpsreducer: FPS Reducer 1.24-mc1.16.5
		gateofbabylon: Gate Of Babylon 1.4.4-1.16.5
		gbfabrictools: GBfabrictools 1.3.2+1.16.4
		geckolib3: Geckolib 3.0.63
		glassential: Glassential 1.16.4-1.1.5
		goblintraders: Goblin Traders 1.4.1
		grass_pass: Grass Bypass 1.0.0
		graveyard: The Graveyard 1.1
		iknowwhatimdoing: I Know What I'm Doing 4.0.0
		illuminations: Illuminations 1.5.1
		indium: Indium 1.0.0+mc1.16.5
		inmis: Inmis 2.2.1-1.16.5
		inventorysorter: Inventory Sorter 1.7.9-1.16
		iris: Iris 1.2.0-pre
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		kirin: Kirin UI 1.7-1.16.2
		konkrete: Konkrete 1.3.3
		kyrptconfig: Kytpt Config 1.1.6-1.16
		lambdynlights: LambDynamicLights 1.3.4+1.16
		lazydfu: LazyDFU 0.1.2
		libgui: LibGui 3.2.0+1.16.3
		library_of_exile: Library of Exile 1.0.14
		libraryferret: Library Ferret 1.0.3
		libstructure: LibStructure 1.5
		lithium: Lithium 0.6.6
		malilib: MaLiLib 0.10.0-dev.21+arne.8
		mesh: Mesh 0.6.1-alpha.21+1.16.4
		mesh_api: Mesh API 0.6.1-alpha.21+1.16.4
		midnight-hats: Midnight Hats 2.0.1
		minecraft: Minecraft 1.16.5
		mm: Manningham Mills 2.1
		mobz: MobZ 2.4.6
		mocolors: Mo' Colors 1.1.2
		modmenu: Mod Menu 1.16.22
		morevillagers-fabric: MoreVillagersFabric 1.4.1-SNAPSHOT
		mostructures: Mo' Structures 1.2.0-1.16.5
		mousetweaks: Mouse Tweaks 2.22
		naturescompass: Nature's Compass 1.16.5-2.0.1-fabric
		no-potion-offset: No Potion Offset ${version}
		nomoreglowingpots: No More Glowing Pots 1.0.2
		notenoughanimations: NotEnoughAnimations 1.2.4
		npcvariety: NPC Variety 1.2.4
		observable: Observable 0.2.1
		okzoomer: Ok Zoomer 4.0.1+1.16.2
		omega-config: OmegaConfig 1.0.4
		openloader: OpenLoader 1.0.2
		org_anarres_jcpp: jcpp 1.4.14
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_codehaus_groovy_groovy: groovy 3.0.3
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.3
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.0
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		patchouli: Patchouli 1.16.4-53-FABRIC
		pehkui: Pehkui 3.1.0+1.14.4-1.18.1
		phosphor: Phosphor 0.8.0
		pling: Pling 1.3.0
		polymorph: Polymorph 0.0.14-1.16.5
		presencefootsteps: Presence Footsteps r29+1.16.4
		quickshulker: Quick Shulker 1.1.14-1.16
		ratsmischief: Rat's Mischief 1.1.2
		reach-entity-attributes: Reach Entity Attributes 1.1.1
		reeses-sodium-options: Reese's Sodium Options 1.3.0
		repurposed_structures: Repurposed Structures 1.16.5-1.11.6-fabric
		reroll: Reroll 1.2.1-1.16.5
		rocks: This Rocks! 1.3.1
		roughlyenoughitems: Roughly Enough Items 5.12.385
		roughlyenoughitems-api: REI (API) 5.12.385
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.12.385
		roughlyenoughitems-runtime: REI (Runtime) 5.12.385
		roughlyenoughresources: Roughly Enough Resources 2.1.5
		runelic: Runelic 1.0.2
		satin: Satin 1.5.1
		savemystronghold: Save My Stronghold! 1.16.4-1.0
		shulkerutils: shulkerutils 1.0.1-1.16
		sit: Sit 1.16.5-11
		skinlayers: 3d Skin Layers 1.1.0
		slight-gui-modifications: 'Slight' GUI Modifications 1.7.1
		snowundertrees: Snow Under Trees 1.0.0
		sodium: Sodium 0.2.0+build.4
		sodium-extra: Sodium Extra 0.3.5
		someforgepatchesported: Some Forge Patches Ported 1.0.0
		spruceui: SpruceUI 2.0.4+1.16
		static-content: Static Content 1.0.2-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stoneholm: Stoneholm 1.2.1
		structure-helpers: Structure Helpers 3.0.0
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.4
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.5
		things: Things 0.1.4
		thonkutil: ThonkUtil 1.3
		toolstats: Tool Stats 1.0.1
		tooltipfix: ToolTip Fix 1.0.2-1.16
		torohealth: ToroHealth Damage Indicators 1.16.5-fabric-6
		transliterationlib: TRansliterationLib 1.0.4
		trinkets: Trinkets 2.6.7
		villagernames: Villager Names 1.6.0
		voidz: VoidZ 1.0.2
		voyager: Voyager 1.0.0
		waila: Hwyla 1.9.22
		wildworld: Wild World 2.0.0+1.16.5
		worldedit: WorldEdit 7.2.5+57d5ac9
		xaerominimap: Xaero's Minimap 22.1.0
		xaeroworldmap: Xaero's World Map 1.20.0
		yosbr: YOSBR 0.1.1
		yungsapi: YUNG's API 1.16.5-Fabric-9
	Patchouli open book context: n/a
	Launched Version: fabric-loader-0.12.12-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

**Comment by warjort** [comment]
I am sure you would get better help if you asked on the extra alchemy issues page or discord.
This issue has nothing to do with the fabric api.

Anyway your problem is pehkui 3.0.0+ is not compatible with the version of extra alchemy you are using.
The major change with version 3.x broke backwards compatability.

See for example:
https://github.com/zabi94/ExtraAlchemy/issues/126
https://github.com/FabricMC/fabric/discussions/1881

You should ask ExtraAlchemy which version to use for 1.16.

This:
https://github.com/zabi94/ExtraAlchemy/blob/1.16-fabric/gradle.properties
suggests they compiled over this
https://www.curseforge.com/minecraft/mc-mods/pehkui/files/3274223
but that is fairly old.

**Comment by deirn** [comment]
Not a fabric issue.
