### ISSUE TITLE
SingleStackStorage impl can cause unwanted side effects (ex. furnaces can't ever smelt)

### ISSUE THREAD

**Issue by TropheusJ** [FabricMC/fabric#1972]
`SingleStackStorage.extract` calls [`setStack`](https://github.com/FabricMC/fabric/blob/e66b59e98c4fc80778b077da360be59d99c03098/fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/item/base/SingleStackStorage.java#L147) and appears to rollback afterwards if the transaction was aborted. However, this does not take into account any side effects of setStack. In the case of furnaces, it resets the cooking timer. A simulated extraction running every tick will completely prevent any furnaces from smelting items. This is exactly what happens [here](https://github.com/Fabricators-of-Create/Create/blob/076236b24846b62200ec25c4b379284b2e7d2015/src/main/java/com/simibubi/create/lib/transfer/item/ItemStorageHandler.java#L75). (Note that this example does not use `simulateExtract` directly, howerver switching to use it instead behaves identically.)

**Comment by Technici4n** [comment]
Ok this is not going to be fun, but I'll see what I can do. Probably a good use case for game tests at least.

**Comment by Technici4n** [comment]
BTW this is somewhat related to #1912.

**Comment by Technici4n** [comment]
Fixed by #1979.
