### ISSUE TITLE
Going through end portal (dragon portal) returns the player to spawn area, and not spawn point.

### ISSUE THREAD

**Issue by WigglyFox** [FabricMC/fabric#1973]
Going through end portal (dragon portal) returns the player to spawn area, and not spawn point. When a player is killed, the player is returned to the spawn point as intended. 
Discovered this a few days ago after feedback from my server community. I've done some troubleshooting and found that this issue exists in a fresh 1.18.1 world as well. 
Tested the same world in Vanilla, and it works fine. 
Currently using the Fabric 0.12.12.

Player NBT data has spawn set correctly. 
![image](https://user-images.githubusercontent.com/98458298/151151928-ea9ddd6e-080d-4e56-8a63-637915b75360.png)

See video for further details. Feel free to reach out if further feedback is required. https://youtu.be/sbySFyRzLoE

Mr. Wiggles

**Comment by deirn** [comment]
What version of Fabric **API** do you have? 0.12.12 sounds more like the version of Fabric Loader.

**Comment by WigglyFox** [comment]
Was using 0.45.1, but just updated to 0.46.1. That solved the issue!
Thank you! :)
