### ISSUE TITLE
Game crashes when trying to render extended (FabricBakedModel) item model

### ISSUE THREAD

**Issue by therealfarfetchd** [FabricMC/fabric#198]
Tested on 1.14.1 and 1.14.2 pr2. This only happens when it needs to render an extended model. The same model renders fine as a block.

Game log: https://paste.therealfarfetchd.dev/udoqowequs.md

**Comment by grondag** [comment]
Looks like a bad mapping in the indigo item renderer.  I will work this one.

**Comment by grondag** [comment]
Not seeing an obvious problem.  Have you got the code I could use to reproduce?

**Comment by asiekierka** [comment]
This is in a dev->prod->dev situation, I think.

**Comment by therealfarfetchd** [comment]
> Not seeing an obvious problem. Have you got the code I could use to reproduce?

Yes, it's this codebase: https://github.com/therealfarfetchd/HCTM

**Comment by asiekierka** [comment]
As I said, it's a remapping problem... I'll investigate it, just give me a few

**Comment by asiekierka** [comment]
I think the bug might actually be in Mixin, but I need to look into it deeper

**Comment by grondag** [comment]
Yeah, I recognize that it may be a mixin bug but wanted to at least get a workaround out. 

Mod authors can’t use Indigo for its intended purpose until we have a patch for this. Canvas works but that’s not a solution for everyone.

**Comment by asiekierka** [comment]
Fixed properly as of Loader 0.4.7+build.149.
