### ISSUE TITLE
Vanilla Bug:  Glowstone creates AO shade

### ISSUE THREAD

**Issue by grondag** [FabricMC/fabric#199]
Block.getAmbientOcclusionLightLevel() only checks for the block being a full cube and so the result is this.

https://i.imgur.com/wkLrnF3.png

This could be fixed with an additional check in Indigo.  But should it be?

(Hat tip to @InsomniaKitten for the find.)

**Comment by asiekierka** [comment]
We've already done some AO fixes, no? With a way to toggle between "emulate vanilla", "emulate vanilla for non-Fabric models, fix bugs for Fabric models" and "fix bugs for all models", with that last bit being the default, IIRC. I would just put this "additional check" under the same "fix bugs?" check.

**Comment by grondag** [comment]
Alright.  Is there any supported way to expose configuration options for API yet?

**Comment by asiekierka** [comment]
No, but implementing the check in the right place will allow to expose it a bit later.
