### ISSUE TITLE
Issue with starting fabric on my computer

### ISSUE THREAD

**Issue by Pursteige** [FabricMC/fabric#1997]
Whenever I try to start my server, It always comes up with this error message. I have tried newer and older versions, yet it hasn't done anything yet. Any advice on that? 
![image](https://user-images.githubusercontent.com/99557803/153724795-7e833316-d62d-4af0-bb44-2a46c44bde77.png)

**Comment by warjort** [comment]
Duplicate of https://github.com/FabricMC/fabric/issues/1758?
