### ISSUE TITLE
BlockApiLookup doesn't support BlockEntityTypes with a custom supports override

### ISSUE THREAD

**Issue by Juuxel** [FabricMC/fabric#1998]
For example Adorn's [`AdornBlockEntityType`](https://github.com/Juuxel/Adorn/blob/1334e4b6263c25450db6ae6acfb00bec436960bc/common/src/main/kotlin/juuxel/adorn/block/entity/AdornBlockEntityType.kt#L13) overrides `supports` to handle it by the block class instead of block type for mod compat.

`BlockApiLookupImpl` doesn't use the public methods but instead accesses the private `blocks` set - which should be unused since I override its only use - with an accessor and crashes because it's empty.

Since doing a fallback provider automatically for these cases is inefficient, it's probably best to just add some javadoc like

```html
<p>The type is not used directly for detecting the supported blocks and block entities in the world, but it is converted to
its {@linkplain BlockEntityType#blocks} when this method is called.

@throws <whatever the exception currently is> if {@link BlockEntityType#blocks} [of any of the types]/[of the type] is empty
```

**Comment by Technici4n** [comment]
I should add this to #2086.
