### ISSUE TITLE
Fluid emptying sound API

### ISSUE THREAD

**Issue by Juuxel** [FabricMC/fabric#1999]
This would be sort of similar to the existing fluid rendering APIs - a fluid like lava could provide its own emptying sounds unless they want to use the default (water) sounds.

**Comment by haykam821** [comment]
Can't fluid filling sounds be done in vanilla? For example:

```java
@Override
public Optional<SoundEvent> getBucketFillSound() {
	return Optional.of(SoundEvents.ITEM_BUCKET_FILL_LAVA);
}
```

**Comment by Juuxel** [comment]
TIL. Anyway, there's still the emptying sound that is hardcoded in `BucketItem.playEmptyingSound`. Even if a modded bucket overrode that, you couldn't access the sound event in other mods.

**Comment by devpelux** [comment]
This way does not works??

```java
public class OilBucketItem extends BucketItem {
    public static final String NAME = "oil_bucket";
    public static final Identifier ID = new Identifier(Main.MODID, NAME);

    public OilBucketItem(Fluid fluid, Settings settings) {
        super(fluid, settings);
    }

    @Override
    protected void playEmptyingSound(@Nullable PlayerEntity player, @NotNull WorldAccess world, BlockPos pos) {
        world.playSound(player, pos, SoundEvents.ITEM_BUCKET_EMPTY_LAVA, SoundCategory.BLOCKS, 1.0F, 1.0F);
        world.emitGameEvent(player, GameEvent.FLUID_PLACE, pos);
    }
}
```

**Comment by ghost** [comment]
I've added this in #2043 please check if is correct!

**Comment by Technici4n** [comment]
Is what I am suggesting in #2095 for the transfer API enough?

**Comment by Juuxel** [comment]
@Technici4n This would be for fluids, not variants, so not fully. Requiring the transfer api for all use cases of a simple fluid emptying sound doesn't really make sense.

**Comment by Technici4n** [comment]
Well, you could `FluidVariantProperties.getEmptySound(FluidVariant.of(fluid))`. Imo it doesn't make sense to require modders to implement this twice, hence the suggestion to only implement it once for the transfer api.

**Comment by devpelux** [comment]
My idea is to inject the method inside the fluid class, to have a direct acces without using FluidVariant.
I think this is exactly what this issue "want".
Maybe the two ways could be merged...?
`FluidVariantProperties.getEmptySound(FluidVariant.of(fluid))` could also get tge property from `getFabricBucketEmptySound()`

**Comment by Technici4n** [comment]
> My idea is to inject the method inside the fluid class, to have a direct acces without using FluidVariant.

I really don't see what this achieves though. Given the few use cases, `FluidVariantAttributes.getEmptySound(FluidVariant.of(fluid))` should be concise enough imo.

**Comment by Technici4n** [comment]
I don't like the idea of injecting this method to the `Fluid` class, it feels unnecessary (a static registry like in #2095 works fine) and will lead to a messy API if we start doing it for 100s of classes imo.
