### ISSUE TITLE
Modded server connection management/versioning

### ISSUE THREAD

**Issue by asiekierka** [FabricMC/fabric#2]
- [ ] Implement version checking (MAJOR.MINOR checked, unless 0.x.y or prerelease in which case whole string checked)
- [ ] Make sure mods can opt out of version checking (with proper "side" etc.)
- [ ] Kick vanilla clients out

**Comment by Yoghurt4C** [comment]
PSA: having block/item adding mods on the client while connecting to a server "scrambles" the clientside ID registry, causing small-to-severe ID mismatches and rendering the game somewhat unplayable, especially on larger modlists
