### ISSUE TITLE
i just downloaded it but this keeps happening 

### ISSUE THREAD

**Issue by markimoofan** [FabricMC/fabric#2000]
net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace 'Minecraft' (minecraft) 1.18 with 'Minecraft' (minecraft) 1.18.1 (later versions might work too).
	 - Replace mod 'Fabric Loader' (fabricloader) 0.12.5 (C:\Users\helee\AppData\Roaming\.minecraft\libraries\net\fabricmc\fabric-loader\0.12.5\fabric-loader-0.12.5.jar) with mod 'Fabric Loader' (fabricloader) 0.12.12 (later versions might work too).
Unmet dependency listing:
	 - Mod 'Fabric API' (fabric) requires "version 0.12.12 or later" of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.12.5!
		 - Mod 'Fabric Loader' (fabricloader) 0.12.5 is being loaded from C:\Users\helee\AppData\Roaming\.minecraft\libraries\net\fabricmc\fabric-loader\0.12.5\fabric-loader-0.12.5.jar
	 - Mod 'Fabric API' (fabric) requires "version 1.18.1" of 'Minecraft' (minecraft), but only the wrong version is present: 1.18!
		 - 'Minecraft' (minecraft) 1.18 is an environment reference and usually requires installation or launcher changes to adjust
Inactive mods:
	 - mod 'Fabric Loader' (fabricloader) 0.12.5, reason: to replace
	 - 'Minecraft' (minecraft) 1.18, reason: to replace
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:183)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:48)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:203)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:183)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:119)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by warjort** [comment]
It is telling you how to solve the problem?

````
A potential solution has been determined:
- Replace 'Minecraft' (minecraft) 1.18 with 'Minecraft' (minecraft) 1.18.1 (later versions might work too).
- Replace mod 'Fabric Loader' (fabricloader) 0.12.5 (C:\Users\helee\AppData\Roaming.minecraft\libraries\net\fabricmc\fabric-loader\0.12.5\fabric-loader-0.12.5.jar) with mod 'Fabric Loader' (fabricloader) 0.12.12 (later versions might work too).
````

Alternatively, if you really want to use the older minecraft 1.18 you will need an older version of the fabric api, e.g. see:
https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/all?filter-game-version=2020709689%3A8830
