### ISSUE TITLE
[Enhancement Req] NBT Crafting

### ISSUE THREAD

**Issue by xanthian** [FabricMC/fabric#2002]
Request to implement NBT Crafting within FApi
Would be handy for mod makers to apply NBT to recipes to for conditions .
eg. Dispenser crafting only accepts a bow with damage = 0

Something not too dissimilar to : https://github.com/Siphalor/nbt-crafting

**Comment by Technici4n** [comment]
This is out of scope for fabric API due to maintainability issues (we absolutely don't want to change vanilla behavior in this area), however nothing stops a third party mod from providing an ecosystem-wide solution.
