### ISSUE TITLE
Game crashes at start when mods are loaded

### ISSUE THREAD

**Issue by AestheticPixels** [FabricMC/fabric#201]
https://pastebin.com/D9XGyh3s - Crash logs

I can start the game with Fabric if I dont have any mods loaded but when I put mods into the mods folder the game crashes when openning.

**Comment by Juuxel** [comment]
Looks like you don't have [Fabric API](https://minecraft.curseforge.com/projects/fabric).

**Comment by AestheticPixels** [comment]
Oh it worked when I installed Fabric API. That's weird because I installed Fabric the same way my friend did using the official website and MultiMC and he event sent me his .minecraft folder and it didnt worked for me but it worked for him.

**Comment by calloatti** [comment]
MultimMC can export and import instances, so there is no need to be sending folders. Export creates a zip file.
