### ISSUE TITLE
API for EnchantmentTargets

### ISSUE THREAD

**Issue by Siphalor** [FabricMC/fabric#202]
Enchantment targets (so like different kinds of tools or the armor pieces) are in an ugly enum.

It would be nice to be able to easily register own ones without having to `@Redirect` or `@Overwrite` a lot of the games logic.

**Comment by UpcraftLP** [comment]
I actually have an implementation for this, tho due to the fact that enchantment targets are anonymous inner classes it heavily relies on chocohead's fabric-ASM.

**Comment by apple502j** [comment]
Vanilla got this :)

**Comment by UpcraftLP** [comment]
> Vanilla got this :)

Damn, Mojang mod loader killing Fabric /j
