### ISSUE TITLE
Reference to FabricBlockSettings is ambiguous

### ISSUE THREAD

**Issue by Atten007** [FabricMC/fabric#2023]
Hi folks,

I'm currently making a 2nd version of "ComputerCraft" with Mcreator for Minecraft fabric 1.16.5. But when Mcreator tries to compile some mod elements, a very shitty error named "Reference to FabricBlockSettings is ambiguous" occurs and also the shitty error "A type with the same simple name is already defined by the single-type-import of FabricBlockSettings. What I've made wrong here? How can I fix these both very shitty errors? I'm very sorry for swearing!

Sincerely yours,
Atten007😊

**Comment by haykam821** [comment]
Duplicate of #2022

**Comment by Atten007** [comment]
> Duplicate of #2022

I closed this, pls answer this in #2022!
