### ISSUE TITLE
Minecraft Crashing because of unknown reason

### ISSUE THREAD

**Issue by edgvrl** [FabricMC/fabric#2025]
Version:
1.18.1

No crash report

Log
[latest.log](https://github.com/FabricMC/fabric/files/8126052/latest.log)

**Comment by warjort** [comment]
````
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector
 fast_getFirstMatch(Lnet/minecraft/class_1863;Lnet/minecraft/class_3956;Lnet/minecraft/class_1263;Lnet/minecraft/class_1937;)Ljava/util/Optional; 
in recipecache.mixins.json:AbstractFurnaceBlockEntityMxn from mod recipecache 
failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap recipecache-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
````
Not a fabric api bug.

Looks like the ````recipecache```` mod has failed to redirect a method in the abstract furnace class.

If this is not a bug in the recipecache mod, it is caused by a conflict with some other mod doing the same thing.
Only one mod can redirect a method.

**Comment by deirn** [comment]
This is probably a conflict between recipecache and fastfurnace+fastworkbench. I suggest you to choose either one.
