### ISSUE TITLE
Game keeps crashing in 1.18.2

### ISSUE THREAD

**Issue by KB-Q** [FabricMC/fabric#2033]
I installed the Fabric API for 1.18.2 released 4 days ago on curseforge. Downloaded the fabric installer and created a new profile for 1.18.2 today. Removed all incompatible mods based on the errors that fabric was throwing. Yet still the game keeps crashing and I get the error message attached below.

![image](https://user-images.githubusercontent.com/59303688/156034424-d3665d73-5e80-4636-87fd-237f57383ffa.png)

**Comment by modmuss50** [comment]
Can you provide the logs please? Does this happen with only fabric API?

**Comment by KB-Q** [comment]
There's a file in the logs folder named 'latest', I assume that is the logs you want. Attaching it here:
[latest.log](https://github.com/FabricMC/fabric/files/8155657/latest.log)

**Comment by modmuss50** [comment]
sodium is causing that crash, please check to see if it has an updated version for 1.18.2
