### ISSUE TITLE
Game keeps crashing in 1.18.2

### ISSUE THREAD

**Issue by KB-Q** [FabricMC/fabric#2034]
I got a new installation for 1.18.2 using the fabric installer, put the latest fabric api for 1.18.2 in the mods folder. Removed all incompatible mods yet I am getting this error:

![image](https://user-images.githubusercontent.com/59303688/156037401-98ec45d5-bdf8-46eb-b993-fd82b17a6e38.png)

Here is the crash report:
[crash-2022-02-28_23.56.34-client.txt](https://github.com/FabricMC/fabric/files/8155741/crash-2022-02-28_23.56.34-client.txt)

**Comment by apple502j** [comment]
I don't think FerriteCore is compatible given how big the changes are.

Also, you have 1.18.1 fabric API somewhere (either as a jar or as a dependency).

**Comment by KB-Q** [comment]
Sorry for the delay, but no, 1.18.1 fabric-api isn't there in the mods folder... none of the other mods also have it as a dependency

**Comment by deirn** [comment]
A mod is bundling `fabric-tag-extensions-v0` which is removed on Fabric API for 1.18.2. Can you provide your full log? It should contains the information of what mod is that.

**Comment by KB-Q** [comment]
It was due to some incompatibilities only, I was able to troubleshoot by adding one mod at a time to the mods folder and launching the game, until I was able to figure out the mods that were causing this error. Thanks for your time anyways.
