### ISSUE TITLE
Get player's current server

### ISSUE THREAD

**Issue by CommandCracker8** [FabricMC/fabric#2036]
How can I get the current server IP and/or world name the player is currently on?

**Comment by warjort** [comment]
I assume you are trying to do this programmatically?

Using logic similar to Vanilla's ````MinecraftClient.getWindowTitle()````
````
ServerInfo info = MinecraftClient.getCurrentServerEntry();
````
which has a name and address when not null.

Or you use the network information;
````
ClientConnection clientConnection = MinecraftClient.getInstance().getNetworkHandler().getConnection();
````
If this is not null you can ````getAddress()````.
If it is a remote server the address should be castable to a ````java.net.InetSocketAddress````

**Comment by CommandCracker8** [comment]
Okay thanks! What about the world name?

**Comment by Technici4n** [comment]
Probably a similar way, have a look at MC's source code.
