### ISSUE TITLE
Ice Spikes Biome not Generated with Fabric API

### ISSUE THREAD

**Issue by ccluong** [FabricMC/fabric#204]
Minecraft ver.: 1.14.1
Fabric Loader: 0.4.7 build 147
Fabric API: 0.3.0 pre build 157a
Issue:
When going to a place where ice spikes should generate, only snowy tundra generates.
Tested using seed -7498160597261473799 at coordinates
X: -13232
Z: -4408

When loaded the location with no fabric API in my mods folder, the ice spikes generates normally.
When I put the fabric API in my mods folder, there is no ice spikes.

**Comment by InsomniaKitten** [comment]
Do you have any mods installed that add biomes?

**Comment by ccluong** [comment]
The only thing I have in my mods folder is the api.

**Comment by calloatti** [comment]
Just commenting that I tested this out and I get the same world generation in both instances.

![image](https://user-images.githubusercontent.com/12817862/58217611-e8faaa80-7cd9-11e9-9bf3-337f6689fb60.png)

![image](https://user-images.githubusercontent.com/12817862/58217624-f57f0300-7cd9-11e9-8c67-0d61fa0dac2e.png)

Nothing in mods folder:

![image](https://user-images.githubusercontent.com/12817862/58217640-0c255a00-7cda-11e9-8406-fb7cb90b96d6.png)

**Comment by ccluong** [comment]
I think I found what's causing the problem. When I reinstall fabric, the ice spikes biome generates correctly, but as soon as I enter my main world ice spikes will stop generating even newly created worlds.

**Comment by ccluong** [comment]
Fixed with the latest version.
