### ISSUE TITLE
Crashing since updating to latest Fabric API

### ISSUE THREAD

**Issue by recon88** [FabricMC/fabric#2040]
Today I've update Fabric API in my private pack from 0.46.4 to 0.46.6. 
1.18.1 with Fabric Loader 0.13.3 
Now the game keeps crashing shortly after start: 
https://pastebin.com/raw/8s1aCHdf

**Comment by modmuss50** [comment]
`world-stripper` seems to be including a newer (most likely 1.18.2) version of one of fabric API's modules. Removing `world-stripper` or finding a version designed for 1.18.1 should solve your issue.

**Comment by EwyBoy** [comment]
Sorry I messed up, it's fixed now 😅
