### ISSUE TITLE
Game crashes when opening inventory - 1.18.2

### ISSUE THREAD

**Issue by KB-Q** [FabricMC/fabric#2046]
Game crashes when opening inventory - 1.18.2. I use fabric mods like sodium, lithium, starlight and a few others, everything updated to their latest versions. 

Here's the error screen: 
![image](https://user-images.githubusercontent.com/59303688/156921101-286b5fd5-023d-4835-a8e4-59786f8f3f0c.png)

And here's the crash report:
[crash-2022-03-06_16.41.05-client.txt](https://github.com/FabricMC/fabric/files/8192433/crash-2022-03-06_16.41.05-client.txt)

**Comment by deirn** [comment]
Try updating LibZoomer/OkZoomer to newer version.

**Comment by dvitski** [comment]
There is no newer version, used and latest is `5.0.0-beta.3+1.17.1`

**Comment by deirn** [comment]
https://github.com/EnnuiL/LibZoomer/releases/tag/0.4.0+1.18.2 put that on your mods folder.

**Comment by KB-Q** [comment]
I only have okzoomer (5.0.0-beta.3+1.17.1), not libzoomer in the mods folder. So how can I remove it and put this new one there?

**Comment by deirn** [comment]
LibZoomer is included _inside_ OkZoomer's jar. Loader will overload those with the jar on mods folder.

**Comment by KB-Q** [comment]
Tried it, it just gave an error: 
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'okzoomer'!

Should I remove okzoomer then, and just have libzoomer?

**Comment by deirn** [comment]
Hmm, can you send your new log?

**Comment by KB-Q** [comment]
[crash-2022-03-06_17.24.02-client.txt](https://github.com/FabricMC/fabric/files/8192486/crash-2022-03-06_17.24.02-client.txt)

**Comment by deirn** [comment]
Looks like LibZoomer changed its API that makes it incompatible with current OkZoomer release 🤦‍♂️.
The only option is to remove it from the mods folder.

**Comment by KB-Q** [comment]
Hey, I removed okzoomer, and the game works fine now. I can open my inventory and put stuff in it, no problem. Libzoomer is in the mods folder, but I don't think it is doing anything sitting there by itself. 

So I think the problem was with okzoomer only. Thanks for letting me know. If I may ask, how did you find it out by reading the crash report? Or did you just guess it by the version number?

**Comment by deirn** [comment]
I search for `renderItem mixin PlayerHeldItemFeatureRenderer` on GitHub (it's what that `class_5697` translates in Yarn Mappings.)

**Comment by KB-Q** [comment]
I see. Thanks again.
