### ISSUE TITLE
problem with fabric 1.18

### ISSUE THREAD

**Issue by vzixx** [FabricMC/fabric#2052]
whenever i try to use fabric with 1.18 it shows this error message. please help (Note: i have tried this with both 1.18.2 and 1.18.1 versions of the mod)
![git](https://user-images.githubusercontent.com/101080564/156965264-127948bd-0e4c-4b31-b785-d9aba8736970.PNG)

**Comment by Linguardium** [comment]
you are using a 1.16.2+ version of fabric api instead of a 1.18.1 version
