### ISSUE TITLE
Forge Demon Slayer Mod Parsing Error Loading Recipe

### ISSUE THREAD

**Issue by WeeboMitch** [FabricMC/fabric#2060]
Hey yall so I made a Forge 1.16.5 modded Minecraft server. After adding all of my mods, I configured one of the mods (Epic Fight Mod) to change weapon types of weapons in the Demon Slayer mod. After trying to load up the server it crashed and showed this log:
https://mclo.gs/p5XclCR

I have been told to install a different version of the mod or contact the creator about the bug. I have tried both of these things and to no avail. I guess now I'm just waiting for the bug to get fixed in the new update. But perhaps there's more to it than just that. But yeah could I get some help with this? That would be much appreciated. Thank you for your time.

**Comment by Linguardium** [comment]
This is the github issue tracker for the Fabric API mod for the Fabric modloader.  If you are running a forge server, you are certainly using neither of these.  You seem to be in the wrong github my dude. try the FeedTheBeast discord for forge assistance.
