### ISSUE TITLE
[1.18.2][FAPI 48.0] BiomeModificationContextImpl.addCarver fails for Biomes without initial carvers

### ISSUE THREAD

**Issue by quiqueck** [FabricMC/fabric#2079]
Adding a new Carver assumes, that the `generationSettings` of a Biome have a valid `RegistryEntryList` for the given `GenerationStep`.
https://github.com/FabricMC/fabric/blob/08b1b79b17d800aed105d8eba85a270a0876d355/fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/modification/BiomeModificationContextImpl.java#L308

However the vanilla Biome Builder will initialize Biomes with an empty map, which will cause a NullPointerException in the `plus`-Method:
https://github.com/FabricMC/fabric/blob/08b1b79b17d800aed105d8eba85a270a0876d355/fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/modification/BiomeModificationContextImpl.java#L325

A possible solution might be to amend `values.stream().toList()` with `values==null?Lists.newArrayList():values.stream().toList()` or something similar.

**Comment by DeKinci** [comment]
Mixin can be used to temporarily overcome this problem
```
import net.minecraft.util.registry.RegistryEntry;
import net.minecraft.util.registry.RegistryEntryList;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable;

@Mixin(targets = "net.fabricmc.fabric.impl.biome.modification.BiomeModificationContextImpl$GenerationSettingsContextImpl")
public class FapiCarverFixMixin {
    @Inject(method = "plus", at = @At("HEAD"), cancellable = true)
    private void fixPlus(RegistryEntryList<?> values, RegistryEntry<?> entry, CallbackInfoReturnable<RegistryEntryList<?>> cir) {
        if (values == null) {
            cir.setReturnValue(RegistryEntryList.of(entry));
        }
    }
}
```
