### ISSUE TITLE
Game can't start - Only fabric and api no mods

### ISSUE THREAD

**Issue by susan3333333** [FabricMC/fabric#2080]
22w11a snapshot
Fabric alone doesn't crash but as soon as I add fabric api, this crash happens:
I can't figure out what is causing it :(

[error.txt](https://github.com/FabricMC/fabric/files/8299696/error.txt)

**Comment by haykam821** [comment]
You also have Client Commands installed, as indicated by the 'Fabric Mods' section of your crash report:

```
Fabric Mods: 
	clientcommands: Client Commands 2.6.2
	clientcommands-scripting: Clientcommands Scripting 1.3.1
```

**Comment by warjort** [comment]
This just looks like a mixin hasn't had its signature updated for the latest snapshot:
https://github.com/FabricMC/fabric/blob/ac75df34b99e460d032c473bbcb9929b7f981af3/fabric-screen-api-v1/src/main/java/net/fabricmc/fabric/mixin/screen/MinecraftClientMixin.java#L78

https://github.com/FabricMC/yarn/commit/845467b67e1a15c46cff195d528fd531c6a857e9#diff-dd7739e9185688ad30243e16c633217323a42af724254495aa8efd7027a4b731R387
````
- METHOD method_29610 startIntegratedServer (Ljava/lang/String;Ljava/util/function/Function;Ljava/util/function/Function;ZLnet/minecraft/class_310$class_5366;)V
		ARG 1 worldName
		ARG 2 dataPackSettingsSupplierGetter
		ARG 3 savePropertiesSupplierGetter
		ARG 4 safeMode
		ARG 5 worldLoadAction
+	METHOD method_29610 startIntegratedServer (Ljava/lang/String;Lnet/minecraft/class_32$class_5143;Lnet/minecraft/class_3283;Lnet/minecraft/class_6904;)V
````
