### ISSUE TITLE
[22w11a] Issue with multiple mods adding blocks to Minecraft:mineable/pickaxe.json

### ISSUE THREAD

**Issue by kwpugh** [FabricMC/fabric#2091]
I'm perplexed with this behavior.  I've updated several of my mods from 1.18.2 to 22w11a and I'm noticing that when multiple mods added to minecraft:mineable/pickaxe.json, only one of the mod's entries appear to be in the list.

I tested this on the following mods:
- Resourceful Tools (mine) - https://github.com/kwpugh/resourceful_tools_fabric-1.17/tree/22w11a
- MoreGems (mine) - https://github.com/kwpugh/MoreGems/tree/22w11a
- Gobber (mine) - https://github.com/kwpugh/gobber_fabric-1.17/tree/22w11a
- Copper Equipment (someone else's mod)  - https://github.com/Redy1aye/CopperEquipment/tree/CopperEquipment/src/main/resources/data

If I add just one of these mods to the launcher, it's blocks display the proper tags  on  the f3  screen.

If I add a second of these mod, the first mods blocks no longer have the tags, but the second mod's blocks do.

Add a 3rd mod, only the 3rd's blocks have tags.

I tried different sequences of mods 1st, 2nd, 3rd  and I get the same results.

I have not be able to get any info on whether or not the method adding modded blocks to the mineable/pickaxe had changed with 22w11a, so I am using the same method since 1.18.2.

Here is a sample of the current method;
<img width="901" alt="Screen Shot 2022-03-21 at 2 15 41 PM" src="https://user-images.githubusercontent.com/8809210/159347572-5f014765-66fc-4d12-9742-39e9625cf0f4.png">

I asked my questions in the Fabric Discord but got no relevant responses, hence opening an issue.

Regards,

Kevin

**Comment by Technici4n** [comment]
I will have a look at this in a bit

**Comment by susan3333333** [comment]
When I looked at the gobber ores with f3 on minecraft they were not shown as minecraft:mineable/pickaxe they were mineable_by_pickaxe, is this cause or symptom?

**Comment by kwpugh** [comment]
That is the problem, they should show Minecraft:mineable/pickaxe.     that mineable_by_pickaxe is a gobber tag left over from testing in the past.  I removed that in dev, rebuilt and tested, still broken.    If Gobber is the only mod that is adding to mineable/pickaxe, it works fine.  If there is another mod that does that, it may or may not work.
So the mineable_by_pickaxe is unrelated.

**Comment by kwpugh** [comment]
to  reproduce:

- load up a new world with fabric, cloth config api and one of the 4 mods listed above
- place one the the mod's blocks (ore or something broken with pickaxe) 
- Use F3 and notice if block has Minecraft:mineable/pickaxe
- exit and add a second mod, then place and view a mineable block from the 2nd mod
- exit and add a third mod, repeat

You will notice that some blocks will lose their mineable tag as more mods are added.

It seems that only one mod will have its blocks added to mineable, in my testing.

**Comment by susan3333333** [comment]
If it was removed, then the gobber jar shouldn't have the file mineable_by_pickaxe.json still? Or it just shouldn't be doing anything?

**Comment by kwpugh** [comment]
it's not doing anything.   The published version  of Gobber still has it.  As I have been troubleshooting this issue, I noticed the json and removed it in my dev environment.

**Comment by Technici4n** [comment]
I confirm that this is indeed an issue, I was able to reproduce this with tags added to two fabric modules.

**Comment by Technici4n** [comment]
@kwpugh Hello, could you check if #2092 fixes the issue for you too? Thanks.

**Comment by Technici4n** [comment]
Fixed by #2092.

**Comment by kwpugh** [comment]
I will test when a new version of Fabric API is released

**Comment by kwpugh** [comment]
any idea when the new version of fabric will be released?

**Comment by Player3324** [comment]
In about 15 minutes
