### ISSUE TITLE
Modded blocks don'r drop on breaking

### ISSUE THREAD

**Issue by trollsdottir** [FabricMC/fabric#210]
I've written to the authors of the mods with which I have this problem, and one suggested it may be an issue with API, as this was the only common change:

Modded blocks don't drop when broken in survival mode. I tested it with .165, .166, .167 on mods: Cotton resources, Epicurean, Extra Pieces and Blockus.

**Comment by shedaniel** [comment]
For me, I have been using the following json file to add back the dropping blocks. Even though I don't know if this is the best / correct way.
In `data/modid/loot_tables/blocks/example_block.json`:
```json
{
  "type": "minecraft:block",
  "pools": [
    {
      "rolls": 1,
      "entries": [
        {
          "type": "minecraft:item",
          "name": "modid:example_block"
        }
      ],
      "conditions": [
        {
          "condition": "minecraft:survives_explosion"
        }
      ]
    }
  ]
}
```

**Comment by calloatti** [comment]
Blocks don't drop also on Trap Expansion

**Comment by Pannoniae** [comment]
I am not sure but I think this only happens in production because things work for me in development. (For cotton-resources)

**Comment by Boundarybreaker** [comment]
I *think* this could possibly be happening because of the [ByteBuf memory leak fix](https://github.com/FabricMC/fabric/commit/200eb5c2acd2aee792bc2de5415a785bebdfea23)?? It's the only commit in the timeframe that affected data packs, since data packs are 100% synced.

**Comment by trollsdottir** [comment]
I reverted to Fabric API [1.14.1] Fabric API 0.3.0-pre build 157a and it works again. As my programming skills are more on mysql/php front I don't know what the issue might be.

**Comment by calloatti** [comment]
Can confirm that going back to fabric-api-0.3.0-pre+build.157a makes modded blocks drop on breaking again.

**Comment by sargunv** [comment]
Went through the list of Fabric releases and confirmed this is broken since 158 but working on 157a. Will investigate further later.

**Comment by asiekierka** [comment]
Only registry-sync and resource-loader have changes which matter, here, and they're big ones. Try to triage one of those two.

**Comment by sargunv** [comment]
The problem is registry-sync, somewhere between commits f1618918 and 168284d8 ([comparison](https://github.com/FabricMC/fabric/compare/f1618918..168284d8)). I need to sleep now so I can't dive in and root cause it right now, but if this issue is still open tomorrow evening I'll investigate further then.

**Comment by asiekierka** [comment]
Nah, now that I know the exact issue I can dive in myself.

**Comment by calloatti** [comment]
This seems to be fixed using fabric-language-kotlin-1.3.30+build.2

**Comment by Knito58** [comment]
Nether Things blocks give xp but no block.

**Comment by Boundarybreaker** [comment]
Since this is fixed, can it be closed?

**Comment by modmuss50** [comment]
Fixed
