### ISSUE TITLE
ItemStack.getAttributeModifiers can't be easily influenced for foreign items

### ISSUE THREAD

**Issue by Flame115** [FabricMC/fabric#2120]
didnt create a crashlog but this is the log file i do have. 

https://pastebin.com/vK5EfqvU

**Comment by frqnny** [comment]
I'd recommend removing Not Enough Crashes as it is conflicting with better loading screen. 

Also, Cull Leaves mod is conflicting with Sodium but not crashing as far as I see.

**Comment by deirn** [comment]
Looks like Combat Tweaks has conflicting redirect mixin with Fabric Item API.

[Combat Tweaks' redirect](https://github.com/CammiePone/Cammies-Combat-Tweaks/blob/05925c3af92e99b8897370122a11a8f8002bbf37/src/main/java/dev/cammiescorner/combattweaks/core/mixin/ItemStackMixin.java#L24)
[Fabric API's redirect](https://github.com/FabricMC/fabric/blob/f79fc1d337432a62a77967cbdd42e9a26d68983f/fabric-item-api-v1/src/main/java/net/fabricmc/fabric/mixin/item/ItemStackMixin.java#L75)

Not sure how to fix this though 😞
@Technici4n @CammiePone

**Comment by Technici4n** [comment]
I suggest that CombatTweaks should fix it.

**Comment by Technici4n** [comment]
@CammiePone said she'd fix it on her side, so closing.

**Comment by CammiePone** [comment]
Yea, I'll get to fixing it eventually. For now, if you wanna use CCT, just use an older version of FAPI. I plan to use MixinExtras to remove all of my redirects in my mods eventually.

**Comment by Technici4n** [comment]
That doesn't help if fabric API doesn't use it though. Something to consider I guess.

**Comment by CammiePone** [comment]
Oh I assumed if my mixin applied first, Fabric API's would just redirect the call in the parameters of my inject

**Comment by CammiePone** [comment]
Wait, what is even the purpose of this redirect? It does the exact same thing as vanilla does it not?

![image](https://user-images.githubusercontent.com/16853086/164132724-618931c6-81d3-4c08-ae67-890c422efd05.png)
![image](https://user-images.githubusercontent.com/16853086/164132789-9d1c6d09-2ca0-4881-8e1c-935fcca4d0d2.png)

**Comment by frqnny** [comment]
Wasn't linking attributes to your entity locked to mods when the fabric entity attribute api was made

sorry saw attributes thought it was entities, this is item stuff.

**Comment by CammiePone** [comment]
My mixin does data-driven attribute modifiers, hence why I redirect on that method. I'm not sure what the Fabric API redirect is even used for.

I get that it's for stack-aware attributes, but also you can literally get the stack with the entity and the slot, and odds are if you have access to the slot, you can get access to the entity somewhere down the line.

**Comment by frqnny** [comment]
Looking at it, it's just a hook extension for stack-aware attributes as you said. I don't think removing it is ideal since having these hooks inside an Item class simplifies logic a lot and saves the modder time in implementing it. Otherwise, "somewhere down the line" really just becomes having to shove down logic wherever you can find a space for that.

**Comment by CammiePone** [comment]
Only ways I can see this working is if:
    a) we both use MixinExtras
    b) an event is added to FAPI so I can move my stuff to that, or
    c) I attempt to implement the stack-aware attributes on my end, set mine to a ModifyVariable to completely negate FAPI's mixin, and pray that works

Option A would be great for other modders since then they get access to MixinExtras, but seems the least likely to happen. Option B is probably the best middle-ground since then we both get what we want simultaneously. Option C is what's probably going to happen because what recourse do I have against the API everyone uses suddenly bricking my mixin?

**Comment by frqnny** [comment]
B sounds interesting. What use cases would this event have? (other than your use case)

**Comment by CammiePone** [comment]
Modders adding attributes to other items in-game, whether they be vanilla or modded, especially their own attributes (i.e. someone makes a magic resistance attribute they want to apply to gold armour)

**Comment by Player3324** [comment]
IMO having an event would be reasonable, changing Mixin in any form is currently no priority. Minecraft relies on item attributes staying consistent for the same stack, so such an event would look exactly the same as the Item extension and run after the item method invocation.

**Comment by Technici4n** [comment]
The event would give a chance to modify the existing map. How is it different from a ModifyVariable placed after the method calls?

**Comment by Technici4n** [comment]
The event is a good idea, but in the meanwhile it looks like it should work fine with a ModifyVariable.

**Comment by CammiePone** [comment]
It would, assuming I can capture it and manage to apply after your redirect. ModifyVariable likes to not work half the time it should for me. Sadly, only thing I can reliably target is when the variable is stored, and I dont remember how much redirects change the code, or if they add additional lines anywhere.

**Comment by Technici4n** [comment]
I'm pretty sure they just replace the method call. It should be safe to target the vanilla method with INVOKE_ASSIGN, in a mixin that applies before fabric's. Then fabric's mixin will replace the method call and your modify variable hook will still be there. You can add `-Dmixin.debug.export=true` to check.

**Comment by CammiePone** [comment]
`INVOKE_ASSIGN` didnt let me target the correct variable last time I tried it with a Modify Variable in FluidRenderer, so I think it targets in the bytecode before the variable is actually stored.

In this case it might work since the variable already exists, but I'll have to check tomorrow.

**Comment by Technici4n** [comment]
Closed by #2175.
