### ISSUE TITLE
Some methods in the FabricBlockSettings class unnecessarily use accessors

### ISSUE THREAD

**Issue by haykam821** [FabricMC/fabric#2133]
In particular, `hardness` and `resistance` have public vanilla equivalents:

https://github.com/FabricMC/fabric/blob/2ba370f3a86d6f99928f88f050b79514eafaca65/fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/block/FabricBlockSettings.java#L231-L239

**Comment by apple502j** [comment]
See #2741
