### ISSUE TITLE
custom sound doesnt work with fabric

### ISSUE THREAD

**Issue by w0crew** [FabricMC/fabric#2137]
fabric version 1.18.2-0.13.3
clear fabric and custom sounds from any Resource Pack
sounds from Resource Pack doesnt work
mods not installed
same issue and with previous versions of fabric

**Comment by Lotzyprod** [comment]
same problem

**Comment by w0crew** [comment]
not fabric api related problem

**Comment by Technici4n** [comment]
Could you please 1) confirm that the resource pack works with the regular MC launcher (no mods, no fabric) 2) link to the resource pack so we can test?

**Comment by Lotzyprod** [comment]
> Could you please 1) confirm that the resource pack works with the regular MC launcher (no mods, no fabric) 2) link to the resource pack so we can test?

Yes, it works with regular MC launcher (cant attach video with proofs at the moment). We have two fabric players whose sounds are not working in the resource pack. At first we thought about mods, but in the process we realized this is a fabric loader.
/playsound minecraft:crew.blinch.cosmic_temperance ambient @a ~ ~ ~
[resourcepack.zip](https://github.com/FabricMC/fabric/files/8504709/resourcepack.zip)

**Comment by Technici4n** [comment]
Oh wait this happens _without_ Fabric API? O_o @sfPlayer1 you might want to have a look then.

**Comment by Lotzyprod** [comment]
Yes, that's why we closed this issue

**Comment by Technici4n** [comment]
Ermm yes makes sense, sorry. I'll reopen the loader one then.
