### ISSUE TITLE
Conventional `brown_dyes` item tag references `purple_dye`

### ISSUE THREAD

**Issue by dvitski** [FabricMC/fabric#2146]
Pretty self-explanatory: [here](https://github.com/FabricMC/fabric/blob/bd8a4a184572832f0ee929f7094dfee511d7a1ac/fabric-convention-tags-v1/src/generated/resources/data/c/tags/items/brown_dyes.json)

**Comment by Technici4n** [comment]
Oh no... I hope it's the only case. 😄
