### ISSUE TITLE
Server not starting.

### ISSUE THREAD

**Issue by BigCasper** [FabricMC/fabric#218]
With Fabric for servers on 1.14.1.

**Comment by modmuss50** [comment]
Any logs? How did you install it? This doesnt give us a lot to go off. Thanks in advance.

**Comment by TimGoll** [comment]
https://github.com/CottonMC/EpicureanGastronomy/issues/20
it might be connected to this

**Comment by Boundarybreaker** [comment]
Yeah, it looks like Fabric's new registry API is causing Int2ObjectMap issues with at least Epicurean.

**Comment by Prospector** [comment]
This issue doesn't have enough info, and if it what is suspected, it's a duplicate.
