### ISSUE TITLE
Loader working but API Fails to load on server

### ISSUE THREAD

**Issue by GiantOranges** [FabricMC/fabric#220]
Using a hosting service that uses Multicraft to install mods. It doesnt seem like an optimal way to do things but I did not want to port forward. :-(
The server itself will run after installing Fabric (1.14.1 release 10), but when I add the Fabric API 0.3.0 build 157a to the mods folder the server refuses to start.  

28.05 02:57:29 [Multicraft] Loaded config for "Vanilla Minecraft (latest)"
28.05 02:57:29 [Multicraft] Updating eula.txt file
28.05 02:57:31 [Server] main/INFO Loading for game Minecraft 1.14.1
28.05 02:57:32 [Server] main/INFO [FabricLoader] Loading 24 mods: fabric-networking-blockentity-v0@0.1.0+f1618918, fabric-keybindings-v0@0.1.0+f1618918, fabric-resource-loader-v0@0.1.0+f1618918, fabric-textures-v0@0.1.0+f1618918, fabric-content-registries-v0@0.1.1+45e1a1c8, fabricloader@0.4.8+build.154, fabric-tag-extensions-v0@0.1.0+f1618918, appleskin@1.0.6, fabric-registry-sync-v0@0.1.0+f1618918, fabric-commands-v0@0.1.0+f1618918, fabric-containers-v0@0.1.0+f1618918, fabric-mining-levels-v0@0.1.0+f1618918, voxelmap@1.9.2, fabric-crash-report-info-v1@0.1.0+f1618918, fabric-events-interaction-v0@0.1.0+f1618918, fabric-events-lifecycle-v0@0.1.0+9232ac87, fabric@0.3.0-pre+build.157a, fabric-models-v0@0.1.0+f1618918, fabric-item-groups-v0@0.1.0+f1618918, fabric-api-base@0.1.0+f1618918, fabric-object-builders-v0@0.1.0+9232ac87, fabric-networking-v0@0.1.1+57f0d19c, fabric-rendering-v0@0.1.0+f1618918, notenoughwands@1.7.4.beta
28.05 02:57:32 [Server] main/WARN Mod `notenoughwands` (1.7.4.beta) does not respect SemVer - comparison support is limited.
28.05 02:57:32 [Server] main/INFO SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/jar/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
28.05 02:57:32 [Server] main/INFO Compatibility level set to JAVA_8
28.05 02:57:32 [Server] main/WARN Mixin config fabric-networking-v0.mixins.json does not specify "minVersion" property
28.05 02:57:32 [Server] main/WARN Mixin config fabric-networking-blockentity-v0.mixins.json does not specify "minVersion" property
28.05 02:57:32 [Server] main/WARN Mixin config fabric-resource-loader-v0.mixins.json does not specify "minVersion" property
28.05 02:57:32 [Server] main/WARN Mixin config fabric-mining-levels-v0.mixins.json does not specify "minVersion" property
28.05 02:57:32 [Server] main/WARN Mixin config fabric-containers-v0.mixins.json does not specify "minVersion" property
28.05 02:57:32 [Server] main/WARN Mixin config fabric-object-builders-v0.mixins.json does not specify "minVersion" property
28.05 02:57:32 [Server] main/WARN Mixin config fabric-rendering-v0.mixins.json does not specify "minVersion" property
28.05 02:57:32 [Server] main/WARN Mixin config fabric-item-groups-v0.mixins.json does not specify "minVersion" property
28.05 02:57:32 [Server] main/WARN Mixin config notenoughwands.mixins.json does not specify "minVersion" property
28.05 02:57:32 [Server] main/WARN Mixin config fabric-events-interaction-v0.mixins.json does not specify "minVersion" property
28.05 02:57:32 [Server] main/WARN Mixin config appleskin.mixins.json does not specify "minVersion" property
28.05 02:57:32 [Server] main/WARN Mixin config fabric-content-registries-v0.mixins.json does not specify "minVersion" property
28.05 02:57:32 [Server] main/WARN Mixin config fabric-registry-sync-v0.mixins.json does not specify "minVersion" property
28.05 02:57:32 [Server] main/WARN Mixin config fabric-keybindings-v0.mixins.json does not specify "minVersion" property
28.05 02:57:32 [Server] main/WARN Mixin config fabric-crash-report-info-v1.mixins.json does not specify "minVersion" property
28.05 02:57:32 [Server] main/WARN Mixin config fabric-events-lifecycle-v0.mixins.json does not specify "minVersion" property
28.05 02:57:32 [Server] main/WARN Mixin config fabric-commands-v0.mixins.json does not specify "minVersion" property
28.05 02:57:33 [Server] main/FATAL Mixin apply failed fabric-networking-blockentity-v0.mixins.json:MixinBlockEntity -> net.minecraft.class_2586: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow method method_11016 in fabric-networking-blockentity-v0.mixins.json:MixinBlockEntity was not located in the target class net.minecraft.class_2586. Using refmap fabric-networking-blockentity-v0-refmap.json
28.05 02:57:33 [Server] INFO org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method method_11016 in fabric-networking-blockentity-v0.mixins.json:MixinBlockEntity was not located in the target class net.minecraft.class_2586. Using refmap fabric-networking-blockentity-v0-refmap.json
28.05 02:57:33 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:387) ~[fabric-server-launch.jar:?]
28.05 02:57:33 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachShadowMethod(MixinPreProcessorStandard.java:363) ~[fabric-server-launch.jar:?]
28.05 02:57:33 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:296) ~[fabric-server-launch.jar:?]
28.05 02:57:33 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:264) ~[fabric-server-launch.jar:?]
28.05 02:57:33 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:244) ~[fabric-server-launch.jar:?]
28.05 02:57:33 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1145) ~[fabric-server-launch.jar:?]
28.05 02:57:33 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:268) ~[fabric-server-launch.jar:?]
28.05 02:57:33 [Server] INFO at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353) ~[fabric-server-launch.jar:?]
28.05 02:57:33 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724) ~[fabric-server-launch.jar:?]
28.05 02:57:33 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703) ~[fabric-server-launch.jar:?]
28.05 02:57:33 [Server] INFO at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509) ~[fabric-server-launch.jar:?]
28.05 02:57:33 [Server] INFO at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:179) ~[fabric-server-launch.jar:?]
28.05 02:57:33 [Server] INFO at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:142) ~[fabric-server-launch.jar:?]
28.05 02:57:33 [Server] INFO at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
28.05 02:57:33 [Server] INFO at net.minecraft.class_2246.<clinit>(class_2246.java:91) ~[intermediary-server.jar:?]
28.05 02:57:33 [Server] INFO at net.minecraft.class_2378.method_10237(class_2378.java:77) ~[intermediary-server.jar:?]
28.05 02:57:33 [Server] INFO at net.minecraft.class_2378.method_10238(class_2378.java:117) ~[intermediary-server.jar:?]
28.05 02:57:33 [Server] INFO at java.util.LinkedHashMap$LinkedEntrySet.forEach(Unknown Source) [?:1.8.0_201]
28.05 02:57:33 [Server] INFO at net.minecraft.class_2378.<clinit>(class_2378.java:116) [intermediary-server.jar:?]
28.05 02:57:33 [Server] INFO at net.minecraft.class_2966.method_12851(class_2966.java:38) [intermediary-server.jar:?]
28.05 02:57:33 [Server] INFO at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:903) [intermediary-server.jar:?]
28.05 02:57:33 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
28.05 02:57:33 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
28.05 02:57:33 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
28.05 02:57:33 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
28.05 02:57:33 [Server] INFO at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170) [fabric-server-launch.jar:?]
28.05 02:57:33 [Server] INFO at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129) [fabric-server-launch.jar:?]
28.05 02:57:33 [Server] INFO at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26) [fabric-server-launch.jar:?]
28.05 02:57:33 [Multicraft] Server shut down (starting)
28.05 02:57:33 [Multicraft] Not restarting crashed server.
28.05 02:57:33 [Multicraft] Looks like a crash, check the server console. Return value: 1
28.05 02:57:33 [Multicraft] Server stopped

**Comment by asiekierka** [comment]
Delete the .fabric folder and try again

**Comment by SuperSmol** [comment]
I'm having the same issue. I've tried deleting the .fabric folder, however it doesn't seem to change anything. I've tried reinstalling the server and I got it to work, however whenever I add any mod it gives the same error no matter which mod it is. Any idea what's wrong?
