### ISSUE TITLE
Oversized stacks should be handled more gracefully

### ISSUE THREAD

**Issue by warjort** [FabricMC/fabric#2201]
As per #2196 and its discussion #2199

Code like this
https://github.com/FabricMC/fabric/blob/1d2d03ecd5a4508d14d4bf0647324afef1b8d2bd/fabric-transfer-api-v1/src/main/java/net/fabricmc/fabric/api/transfer/v1/item/base/SingleStackStorage.java#L113
can lead to unloadble worlds when the capacity < stack size. 

It will always crash because working item amounts become negative which fails sanity checks elsewhere.
The crash means it can't be fixed in game.

Reasons for this to occur maybe:
* A bug in a mod
* Somebody cheating in an oversize stack
* Installing a mod that increases max stack sizes then removing that mod

The transfer api should handle these oversize stacks more gracefully without crashing.

**Comment by Technici4n** [comment]
Probably a good addition to #2189.

**Comment by Technici4n** [comment]
It's good practice to have the `return inserted` inside the `if (inserted > 0) {` for exactly this reason, I don't know why I didn't do that for a few implementations... #2189 contains a fix now.

**Comment by energy11a** [comment]
The crash was caused by hopper attempting to use overstacked(10) water bottles.
