### ISSUE TITLE
Registries added in Minecraft 1.19 should be synced

### ISSUE THREAD

**Issue by haykam821** [FabricMC/fabric#2205]
The following registries were added in Minecraft 1.19 and should be [acknowledged in registry sync](https://github.com/FabricMC/fabric/blob/729842f055b095e34cca9d9f6beb00983d6949d3/fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/impl/registry/sync/FabricRegistryInit.java):

- [x] `minecraft:cat_variant` - Uses a data tracker (and thus, raw IDs) to sync cat entities to the client
- [x] `minecraft:frog_variant` - Uses a data tracker (and thus, raw IDs) to sync frog entities to the client
- [x] `minecraft:painting_variant` - Uses a data tracker (and thus, raw IDs) to sync painting entities to the client
- [x] `minecraft:command_argument_type` - Uses the raw ID when syncing the command tree to the client
- [x] `minecraft:root_placer_type` - Appears to be unsynced
- [x] `minecraft:worldgen/world_preset` - Is a dynamic registry
- [x] `minecraft:worldgen/flat_level_generator_preset` - Is a dynamic registry
- [x] `minecraft:chat_type` - Is a dynamic registry

**Comment by deirn** [comment]
Since the registry sync packet is split now, should we just sync all modded registries?
