### ISSUE TITLE
[Feature Request] Adding "-DISABLE" suffix to end of mod .jar (or something similar) disables it from being loaded

### ISSUE THREAD

**Issue by onlycs** [FabricMC/fabric#2211]
this is going to save me a lot of time debugging my mod setup.

**Comment by haykam821** [comment]
Files renamed in this way (such as from `pling-1.5.0.jar` to `pling-1.5.0.jar-DISABLED`) will already not load.

**Comment by Technici4n** [comment]
Personally I like to use `.jar.disabled`, but what haykam suggested also works.
