### ISSUE TITLE
Incompatible Mod set..?

### ISSUE THREAD

**Issue by Lolcat2112** [FabricMC/fabric#2218]
version 1.16.5
I am a newbie to this. why does it show this?

> Incompatible mod set!
> net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod discovery failed!
> 	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
> Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod discovery failed!
> 	at net.fabricmc.loader.impl.discovery.ModDiscoverer.lambda$discoverMods$1(ModDiscoverer.java:137)
> 	at net.fabricmc.loader.impl.discovery.ModDiscoverer$$Lambda$17/1192171522.apply(Unknown Source)
> 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
> 	at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:137)
> 	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:208)
> 	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187)
> 	... 3 more
> 	Suppressed: java.lang.RuntimeException: java.lang.RuntimeException: Error analyzing [C:\Users\jenni\AppData\Roaming\.minecraft\mods\TooManyOrigins-1.16.5-0.5.1-fabric.jar]: java.util.zip.ZipException: error in opening zip file
> 		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 		at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
> 		at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
> 		at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
> 		at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:134)
> 		... 5 more
> 	Caused by: java.lang.RuntimeException: Error analyzing [C:\Users\jenni\AppData\Roaming\.minecraft\mods\TooManyOrigins-1.16.5-0.5.1-fabric.jar]: java.util.zip.ZipException: error in opening zip file
> 		at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:237)
> 		at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:194)
> 		at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:94)
> 		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
> 		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
> 		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
> 		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
> 	Caused by: java.util.zip.ZipException: error in opening zip file
> 		at java.util.zip.ZipFile.open(Native Method)
> 		at java.util.zip.ZipFile.<init>(ZipFile.java:220)
> 		at java.util.zip.ZipFile.<init>(ZipFile.java:150)
> 		at java.util.zip.ZipFile.<init>(ZipFile.java:164)
> 		at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.computeJarFile(ModDiscoverer.java:262)
> 		at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:232)
> 		... 6 more
> Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Error analyzing [C:\Users\jenni\AppData\Roaming\.minecraft\mods\architectury-1.31.60.jar]: java.util.zip.ZipException: error in opening zip file
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
> 	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
> 	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
> 	at net.fabricmc.loader.impl.discovery.ModDiscoverer.discoverMods(ModDiscoverer.java:134)
> 	... 5 more
> Caused by: java.lang.RuntimeException: Error analyzing [C:\Users\jenni\AppData\Roaming\.minecraft\mods\architectury-1.31.60.jar]: java.util.zip.ZipException: error in opening zip file
> 	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:237)
> 	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:194)
> 	at java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:94)
> 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
> 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
> 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
> Caused by: java.util.zip.ZipException: error in opening zip file
> 	at java.util.zip.ZipFile.open(Native Method)
> 	at java.util.zip.ZipFile.<init>(ZipFile.java:220)
> 	at java.util.zip.ZipFile.<init>(ZipFile.java:150)
> 	at java.util.zip.ZipFile.<init>(ZipFile.java:164)
> 	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.computeJarFile(ModDiscoverer.java:262)
> 	at net.fabricmc.loader.impl.discovery.ModDiscoverer$ModScanTask.compute(ModDiscoverer.java:232)
> 	... 6 more
> 

Does anyone have the same issue?

**Comment by Lolcat2112** [comment]
I forgot to mention the version I'm on.
I'm on minecraft 1.16.5

**Comment by Daomephsta** [comment]
The TooManyItems & Architectury JARs are probably corrupt, delete them, redownload them, and try again
