### ISSUE TITLE
translate fail

### ISSUE THREAD

**Issue by Enaium** [FabricMC/fabric#2246]
Game:1.18.2

## en_US.json
```json
{
"key":"value"
}
```

`new TranslatableText("key")`

in the dev:value

in the game:key(get translate fail

## en_us.json
```json
{
"key":"value"
}
```

`new TranslatableText("key")`

in the dev:value

in the game:value

**Comment by haykam821** [comment]
The names of language JSON files should be lowercase. The development environment is problematic here for accepting `en_US.json` as a valid alternative to `en_us.json`.
