### ISSUE TITLE
Command redirection without argument throw error even if it should be valid

### ISSUE THREAD

**Issue by Elikill58** [FabricMC/fabric#2255]
| Type | Version |
| - | ---------|
| Minecraft | 1.18.2 |
| Loader | 0.14.5 |
| Fabric | 0.53.0+1.18.2 |

I'm registering command like that:
```java
private void registerCommand(String cmd, CommandDispatcher<ServerCommandSource> dispatcher, String... alias) {
	LiteralCommandNode<ServerCommandSource> node = dispatcher
			.register(CommandManager.literal(cmd).executes(new CommandsExecutorManager(cmd)));

	for (String sub : alias)
		dispatcher.register(CommandManager.literal(sub).redirect(node));
}
```
Then, I use: `registerCommand("negativity", dispatcher, "neg")`.

But in chat, the command is not well founded (I made /neg then /negativity, both without any arguments):
![image](https://user-images.githubusercontent.com/17381066/169983735-0128e6a4-f71f-4585-9f55-717893b114d6.png)

**Comment by Technici4n** [comment]
I don't think this is really a fabric API issue, all we do is expose access to Brigadier, but you're probably using it incorrectly?
