### ISSUE TITLE
OnPlayerConnect/Disconnect events

### ISSUE THREAD

**Issue by magneticflux-** [FabricMC/fabric#226]
Mentioned previously in https://github.com/FabricMC/fabric/issues/19.

Relevant methods:
* `net.minecraft.server.PlayerManager::onPlayerConnect` (onConnect)
* `net.minecraft.server.PlayerManager::remove` (onDisconnect)

Creating mixins to fire the events seems simple as there are already Mojang hooks in place.

I can submit a PR if it is likely to get accepted.

**Comment by magneticflux-** [comment]
@SquidDev What's the status of https://github.com/FabricMC/fabric/pull/34?

**Comment by i509VCB** [comment]
I'd say this is somewhat covered by https://github.com/FabricMC/fabric/pull/605

**Comment by i509VCB** [comment]
Closing since this has been implemented in `ServerPlayConnectionEvents`
