### ISSUE TITLE
Recent fabric-networking-v0 version causing mixin apply errors when installed with fabric-networking

### ISSUE THREAD

**Issue by sargunv** [FabricMC/fabric#227]
I'm still investigating https://github.com/CottonMC/SkillCheck/issues/19, but I suspect this is a Fabric API issue so I'm reporting here.

Mixin apply errors on launch: https://paste.ee/p/bNi9t

Error happens with fabric-networking-v0-0.1.2+200eb5c2
Works fine with fabric-networking-v0-0.1.0+f1618918

**Comment by sargunv** [comment]
Minimal reproduce case: fabric-networking-0.1.0+93af775a and fabric-networking-v0-0.1.2+200eb5c2 installed together. Replace fabric-networking-v0 with commit f1618918 and it's fine.

https://paste.ee/p/chJkq

**Comment by sargunv** [comment]
Narrowed it down to somewhere between 57f0d19c and 945f265f. Jar fabric-networking-v0 57f0d19c is good while 945f265f triggers the crash (when installed alongside fabric-networking 93af775a). Since 57f0d19c is the parent of 945f265f, the problem must have been introduced in 945f265f. Looking at 945f265f, the only real change I see is a mappings update. Perhaps this is triggering some mappings related issue in loom or loader?

**Comment by sargunv** [comment]
My best guess as to how this could be happening is that one mod's refmap is somehow interfering with another, and since the Screen class moved packages in the mappings between commit A and B, that interference caused the mixin to fail to apply.

To test this theory, I modified the modids of fabric-networking-v0 at commit A and B so I could load them at the same time. Since A's refmap is the same as fabric-networking's refmap, I expected this to also reproduce the error. However, the error did not occur.  So, there must be some other trigger than just two mod refmaps referring to the same intermediary name with different yarn names.

**Comment by liach** [comment]
Does it still happen?

**Comment by sargunv** [comment]
Just tested, no crash on MC 1.14.4 with fabric-networking@0.1.0+93af775a and fabric-networking-v0@0.1.4+f6e5d2dc42. I guess it no longer happens, unless I forgot how to reproduce.

https://paste.ee/p/1CaEA

**Comment by liach** [comment]
Thanks! I've seen this happen in log messages, but usually when this happens mods are faulty. Dunno how as well, guess it's not a problem.
