### ISSUE TITLE
Datapack error after update

### ISSUE THREAD

**Issue by ardissaps** [FabricMC/fabric#2271]

**Comment by modmuss50** [comment]
Are you able to provide any more infomration, such as what Minecraft verison you are using? Or any logs?

**Comment by ardissaps** [comment]
1.18.2, the update is 100% the cause of error. I already revert back Fabric api to previus version and the problem gone, maybe because latest update? The log maybe not accurate because the game not crashing, just refuse to load world or create new.

**Comment by modmuss50** [comment]
Yes, it wouldnt surprise me if it was the latest update, however I am unable to fix something without any information about what caused it. The log should provide some light on what is causing it.

**Comment by ardissaps** [comment]
> Yes, it wouldnt surprise me if it was the latest update, however I am unable to fix something without any information about what caused it. The log should provide some light on what is causing it.

the log too big to paste here
https://www.mediafire.com/file/x6pr4pbfaw0xuu1/log.txt/file

**Comment by modmuss50** [comment]
Thanks for that 👍

I have a funny feeling optifine might be causing this issue? Would you be able to try without it?

**Comment by ardissaps** [comment]
> Thanks for that 👍
> 
> I have a funny feeling optifine might be causing this issue? Would you be able to try without it?

actually i am on fabric with sodium and indium

**Comment by modmuss50** [comment]
Oh my bad, the log mentions optifine a lot. Im quite confused about this one.

**Comment by ardissaps** [comment]
> Oh my bad, the log mentions optifine a lot. Im quite confused about this one.

Maybe because of mod parity such as ETF, CEM, CIT, MCPP that would detect incompatible resourcepack that need to be converted to compatible fabric mod format

**Comment by Technici4n** [comment]
What's quite strange is that many fabric modules seem to be missing from the mod list in your log.

**Comment by Technici4n** [comment]
Are you using quilt standard libraries, or is any mod using them, by any chance? That would cause this issue.

**Comment by ardissaps** [comment]
> 

I am not using Quilt for this the instance, but many of my mod is from modrinth which usually mod author packed 1 file that compatible with both fabric and quilt. like OkZoom and Inspecio they both now not support Fabric for newer version but older version still exist, just not updated.

**Comment by Technici4n** [comment]
In the modlist in the logs, you can see which mods include quilt modules. They are causing this issue and you'll have to remove them.

**Comment by ardissaps** [comment]
> In the modlist in the logs, you can see which mods include quilt modules. They are causing this issue and you'll have to remove them.

which one could be causing it, shall I just CTRL+F in the log and look for anything that contain quilt?

**Comment by Technici4n** [comment]
![image](https://user-images.githubusercontent.com/13494793/171213894-6b50d474-6db9-4e8d-9c7f-6eca978f0e02.png)

**Comment by ardissaps** [comment]
> ![image](https://user-images.githubusercontent.com/13494793/171213894-6b50d474-6db9-4e8d-9c7f-6eca978f0e02.png)

Damn, yes the world now loads after removed Inspecio with updated Fabric API. Why would he post it as compatible with fabric but in reality it is not, so sad it is time to say goodbye with that mod that currently no available alternative. Thx for the help!
