### ISSUE TITLE
The various ItemTags.of, BlockTags.of, etc... should be transitive access widened

### ISSUE THREAD

**Issue by Technici4n** [FabricMC/fabric#2275]
Example:
![image](https://user-images.githubusercontent.com/13494793/171500794-f317efb4-eec8-4751-abc4-e025678a6c97.png)

Forge has these AT'ed, and it is very convenient.

**Comment by haykam821** [comment]
Methods which take stringified identifiers should not be access-widened.

**Comment by Technici4n** [comment]
Right, I didn't pay attention. Which method did I use on forge then... 🤔

**Comment by Technici4n** [comment]
Lol ok nevermind, Forge patches in additional methods that take an `Identifier`.
