### ISSUE TITLE
Include `LICENSE` file within Fabric API module JAR files

### ISSUE THREAD

**Issue by bytzo** [FabricMC/fabric#2277]
> *Disclaimer: I am not a lawyer or legal expert. Bear in mind that any statements made below may be wrong or incorrect.*

Mods that include the Fabric API in their own JAR file must also include the Fabric API `LICENSE` file in order to comply with the Apache license. [Unlike the Fabric example mod](https://github.com/FabricMC/fabric-example-mod/blob/9bfeedcc577bb8f30f4fa7c9f3b3b0c395abaae0/build.gradle#L51-L55), the Fabric API does not embed its license inside of its own JAR file.

To help people who include the Fabric API in their mod, the Fabric API should include the `LICENSE` file within each of the Fabric API module JAR files.

**Comment by youmukonpaku1337** [comment]
hmmm good idea
