### ISSUE TITLE
Misleading "Registry remapping" error

### ISSUE THREAD

**Issue by youmukonpaku1337** [FabricMC/fabric#2278]
![unknown-3](https://user-images.githubusercontent.com/50289495/171576228-66e45d1d-4b4e-43f8-a188-d3e24037c498.png)
When a server has some specific mods but the client doesn't, fabric shows a confusing registry remapping error with a few IDs.
Forge, on the other hand shows a missing mods error, would it be possible to implement that in fabric? It's causing me to lose a lot of potential new members, because for some reason nobody reads the description and decides to join anyway, and then sees the error and just leaves.

It could look something like that:
"You're missing mods, please install Fabric and the Fabric API and add these mods:
list
of
mods
goes
here"

By the way, is this an issue with the API or the loader? I'm not sure so i made the issue here, please tell me if the issue should be moved to the fabric modloader issues page

There are also other variations of the error, like:
![unknown-4](https://user-images.githubusercontent.com/50289495/171577133-40202dea-2995-48e8-838f-eeef2ae2918e.png)

**Comment by youmukonpaku1337** [comment]
as you can see, a normal vanilla player might not understand what is happening when they get that error

**Comment by apple502j** [comment]
This is an API issue.

However, there is one slight problem; the client does not know what mod provides the registry, so we need to make the server send the mod info in addition to the registry. This can increase the size of the packet, which is already an issue.

Even if we do fix that, there will be another problem - that the server doesn't know what mod added what. Fabric uses the vanilla registry, so nothing can tell us what mod added to what, without hacky solutions like examining stack trace every time registry is modified.

**Comment by youmukonpaku1337** [comment]
just wondering, why can't 2 packets be sent? also, i have no idea what a registry is

**Comment by apple502j** [comment]
Okay, let's clarify what a registry is.

Almost all ingame things like blocks, items, entities, biomes, etc are registered in a "registry". In most cases the contents of the registry are static (e.g. in vanilla, the client and the server have the same blocks), but this might not be true in modded situations. Registry Sync ensures that the client has everything the server needs in the registry.

Fabric mods use vanilla game's methods to add registry entries, which makes tracking which registry entry belongs to which mod hard, if not impossible. This is I believe the main difference between Forge.

That said, nothing prevents us from sending a list of mods independently, as you said. This should be opt-in (usually a waste of time), but listing that in the error, perhaps with a diff, might be enough.

**Comment by youmukonpaku1337** [comment]
maybe at least make it show something like 
"You're missing some mods, please install Fabric and the Fabric API and check the server description/website on which mods have to be installed"

**Comment by youmukonpaku1337** [comment]
that wouldn't require making the packet bigger, or maybe make it opt-in?

**Comment by apple502j** [comment]
Yeah, we can improve it. (Note that if "Registry remapping failed" error is displayed the client should have Fabric and API at that point. We can't do much about those without Fabric/Fabric API, they'll just error and the server does not know why.)

**Comment by youmukonpaku1337** [comment]
oh, i see

**Comment by youmukonpaku1337** [comment]
guess ill have to put the fact that you need fabric and the api in the motd

**Comment by youmukonpaku1337** [comment]
wait, just wondering, doesn't forge show the missing mods error to vanilla too?

**Comment by MattiDragon** [comment]
> wait, just wondering, doesn't forge show the missing mods error to vanilla too?

Probably, but forge just detects that the client is vanilla and gives an error. Vanilla doesn't send mods (it doesn't even know about them) forge just knows the mods aren't loaded since forge isn't

**Comment by youmukonpaku1337** [comment]
> > wait, just wondering, doesn't forge show the missing mods error to vanilla too?
> 
> Probably, but forge just detects that the client is vanilla and gives an error. Vanilla doesn't send mods (it doesn't even know about them) forge just knows the mods aren't loaded since forge isn't

so maybe make it show that fabric is missing on vanilla?

**Comment by youmukonpaku1337** [comment]
and that some mods are missing on fabric itself, with modlist as opt-in

**Comment by Technici4n** [comment]
As a "temporary" solution, would it make sense to simply adjust the warning as follows? The modids would just be the namespaces for the erroring entries.

"Missing content from the following mods: modid1, modid2, modid3. Make sure that they are installed, with a version compatible with the one on the server. This can also be caused by pack version mismatches.

<technical error below, or even in the logs>"

**Comment by youmukonpaku1337** [comment]
yes, that'll do

**Comment by youmukonpaku1337** [comment]
wait, we can use the same thing as what this uses to get what item comes from which mod https://modrinth.com/mod/shoutout

**Comment by MattiDragon** [comment]
It just looks up the mod name using the namespace of the item id as a mod id. The problem is that not all mods support it; some use a different namespace from their id

**Comment by youmukonpaku1337** [comment]
oh, then how can i solve that?

**Comment by Technici4n** [comment]
The message was improved in #3004.
