### ISSUE TITLE
Minecraft Crashes after 100% loading into your Minecraft World.

### ISSUE THREAD

**Issue by tonwu** [FabricMC/fabric#2286]
Fabric API causes my game to crash whenever I try to load into a world. After 100%, my game freezes. I have tried multiple times without Fabric API and it works fine. Mods I have installed are OptiFabric and Optifine. I'm not sure if OptiFabric and Optifine are the cause to this issue or it's just me.

**Comment by Linguardium** [comment]
there is an open issue about this on optifabric. it is a mod issue not a fabric api issue.

that said, use fabric api 0.53.3 or earlier as optifabric doesnt support later versions

**Comment by tonwu** [comment]
@Linguardium Thanks :D
