### ISSUE TITLE
OS crash - Fabric Loader 0.14.7-1.19

### ISSUE THREAD

**Issue by jan-Sanku** [FabricMC/fabric#2302]
Very simple issue: starting Fabric 0.14.6 works fine, but running 0.14.7 for the first time will instantly power off my PC. Event Viewer Event ID 41 "Kernel-Power": "The system has rebooted without cleanly shutting down first. This error could be caused if the system stopped responding, crashed, or lost power unexpectedly."

Running Fabric a second time yields the following error:
![image](https://user-images.githubusercontent.com/56739341/172854512-0fd7eb29-51df-46da-9ccf-c5e3cb0ef64d.png)

Deleting the file in question and restarting crashes the system again, same as before. I think the file is created by Fabric but couldn't be finished due to the crash, crashing Fabric 1 step before the system crash would normally occur.

***

Here is the latest.log when the system crashes: https://pastebin.com/rx54zN56

Here is the latest.log when launching again without deleting the corrupted file: https://pastebin.com/PGfdqJef

***

It looks like the "optimized datafixer" thing is the last entry before the system crash.

Reverting to 1.14.6 is a valid workaround for this issue.

NOTE: all this happens regardless of installed mods, I just had them installed when I copied the logs.

**Comment by Player3324** [comment]
There is no difference in Loader that could cause this, only that it wouldn't keep reusing the same cached jar because the cache is version locked.

The fact that it causes your computer to reboot unfortunately suggests that the real issue is with your OS, drivers or hardware. A regular program without admin perms is unable to crash the OS if those three components are intact. Check your filesystem (chkdsk), disk (smart with selftest) and RAM (memtest) thoroughly. Antivirus interference is also possible, but less likely.

**Comment by jan-Sanku** [comment]
You're right, renaming the remappedJars folder crashes Fabric on any version. I already ran all those tests before submitting this issue, since I didn't think it could be Fabric at first, but they're all nominal. AV is just windefender and it's generally not interfering.

This crash only occurs when Fabric tries to build the datafixer thingy, do you know what exactly it tries to do? As in what kinds of drivers are needed that I might try to check and reinstall?

**Comment by Player3324** [comment]
I'd start with the filsystem and disk parts.

**Comment by jan-Sanku** [comment]
"Windows has scanned the file system and found no problems"
All my disks turn out fine after a S.M.A.R.T. test, and chkdsk also doesn't find any issues, as you can see. Anything else I could check? I'm genuinely lost right now, since I literally managed to run Fabric 0.14.6 when it came out 2(?) days ago.

I changed nothing since then, no installs or changed settings.

**Comment by Player3324** [comment]
did you already delete/rename the .fabric folder instead of the just the file? smart also has a self test that goes beyond checking the values.

**Comment by warjort** [comment]
Here's a similar report to this problem: https://github.com/FabricMC/fabric/discussions/2267

That report also says the error happens with vanilla minecraft:

> I've been getting a lot of BSODs any time that I try and launch the normal version of minecraft. (code clock_Watchdog_timeout)`

BSOD = Blue Screen of Death = Crash

Assuming yours is the same problem, suggested fixes include updating device drivers, bios, etc. to latest versions.
You are probably better off reporting the problem to Microsoft or your PC supplier, to get more informed help.

**Comment by jan-Sanku** [comment]
> did you already delete/rename the .fabric folder instead of the just the file? smart also has a self test that goes beyond checking the values.

yes, tried that.

> Assuming yours is the same problem, suggested fixes include updating device drivers, bios, etc. to latest versions.
You are probably better off reporting the problem to Microsoft or your PC supplier, to get more informed help.

I'm not entirely sure if that's related, since I'm not getting a BSOD or errors of any kind... I already updated my GPU drivers and I'm not sure what else I can update other than stuff like mouse drivers but that seems useless. I'll try BIOS but I've never done that before. My PC is brand new, so it's definitely not wear and tear...

I'll close this issue since it doesn't look like it's directly related to Fabric, but if anyone has any ideas or tips, please let me know.
