### ISSUE TITLE
IDK what I'm doing or what I'm dong wrong, Please help.

### ISSUE THREAD

**Issue by RemedyG** [FabricMC/fabric#2303]
it won't let me even paste in the crash report, how am I supposed to get help??

**Comment by RemedyG** [comment]
I am just trying to launch minecraft with updated 1.19 mods and it keeps crashing and I don't know why and it won't let me paste the crash report here on this website. what am I supposed to do??

**Comment by RemedyG** [comment]
the crash report is 152954 characters, am I supposed to chop it up and paste it in pieces???

**Comment by Juuxel** [comment]
You can upload it on [github gist](https://gist.github.com) or some other "paste" site designed for that purpose.

**Comment by RemedyG** [comment]
OK, does this work?
https://gist.github.com/RemedyG/14e4fb49b341057eac5cc7aa53f8f9e7
