### ISSUE TITLE
Registry remap events are causing colliding IDs

### ISSUE THREAD

**Issue by Boundarybreaker** [FabricMC/fabric#231]
I've now run into a few issues with folks playing with Epicurean Gastronomy running into `Int2ObjectMap contained two equal IDs` crashes when they try to load their world with the new Fabric API. I thought it might be something with Epicurean, but then OliviaTheVampire in the Fabric discord ran into it with their mods as well. It seems to be happening with real items along with the `minecraft:air` bug Epicurean's been running into. The crash only begins happening in builds 171 and above, so it's probably something with the new API.

[Epicurean issue 1 (air)](https://github.com/CottonMC/EpicureanGastronomy/issues/19)
[Epicurean issue 2 (real item)](https://github.com/CottonMC/EpicureanGastronomy/issues/20)

**Comment by SDUBZ** [comment]
any update on this issue

**Comment by TimGoll** [comment]
The problem is that downgrading fabric does not solve this at all. It solves this bug, yes, but intoduces a lot of others. 50s builds tend to work, but some mods have no working GUI and 60s builds sometimes prevent dropping items when mining a block.

**Comment by Boundarybreaker** [comment]
https://github.com/CottonMC/EpicureanGastronomy/issues/20#issuecomment-499684297 Another instance found.

**Comment by Boundarybreaker** [comment]
I'm working on a PR that should *hopefully* make the error message a lot clearer, so that we can better see what's going on.

**Comment by Boundarybreaker** [comment]
hey @TimGoll @Luxley, could you try [this](https://dsc.cloud/b0undarybreaker/fabric-api-0.3.0-local.jar) version of Fabric API and send me the crash logs? It should get us one step closer to fixing it, since the logs will actually say what the real problem is.

**Comment by Boundarybreaker** [comment]
@el0c you too, please

**Comment by Luxley** [comment]
@Boundarybreaker 

The game crashed whilst unexpected error
Error: java.lang.RuntimeException: Registry minecraft:item contained two objects with ID 1411 (net.minecraft.class_1093@1475c59c/1411 vs superores:super_platinum_ore/1411)!

[crash-2019-06-06_18.06.48-client.txt](https://github.com/FabricMC/fabric/files/3263805/crash-2019-06-06_18.06.48-client.txt)

**Comment by Boundarybreaker** [comment]
Oh *boy*.

**Comment by Boundarybreaker** [comment]
That actually clears *everything* up. Thank you so much for helping!

**Comment by Luxley** [comment]
Whats the problem?

Enlighten my peanut brain!

**Comment by Boundarybreaker** [comment]
It's trying to map the block model registry *and* the item registry at the same time, causing their IDs to run into each other!

**Comment by Boundarybreaker** [comment]
Wait, hm. It looks like it's something else. Gonna make a new test build.

**Comment by Boundarybreaker** [comment]
@Luxley [new one to try with](https://dsc.cloud/b0undarybreaker/fabric-api-0.3.0-local.jar)

**Comment by Luxley** [comment]
@Boundarybreaker 

Sorry on the slowness

The game crashed whilst unexpected error
Error: java.lang.RuntimeException: Registry minecraft:item contained two objects with ID 1411 (net.minecraft.class_1093@319537bd/1411 vs superores:super_platinum_ore/1411)!

[crash-2019-06-06_19.01.40-client.txt](https://github.com/FabricMC/fabric/files/3263926/crash-2019-06-06_19.01.40-client.txt)

**Comment by Boundarybreaker** [comment]
Ugh, it did't upload properly. [New name so it doesn't collide!](https://dsc.cloud/b0undarybreaker/fabric-api-0.3.0-local-2.jar)

**Comment by Luxley** [comment]
@Boundarybreaker  
The game crashed whilst unexpected error
Error: java.lang.RuntimeException: Int2ObjectMap contained two objects with int ID 1411 (superores:super_platinum_ore/1411 vs superores:super_platinum_ore/1411)!
[crash-2019-06-06_19.16.56-client.txt](https://github.com/FabricMC/fabric/files/3263947/crash-2019-06-06_19.16.56-client.txt)

**Comment by Boundarybreaker** [comment]
AH HA!

**Comment by TimGoll** [comment]
that sounds great! @Boundarybreaker  :D

**Comment by asiekierka** [comment]
Flaw in Epicurean Gastronomy. Fabric will now correctly detect it and throw at the game load stage. o/
