### ISSUE TITLE
More convention tags

### ISSUE THREAD

**Issue by kittech0** [FabricMC/fabric#2330]
So i think about adding tags like `birch_forest`,`spruce_forest` etc. It would be useful for mods that adds structures wood type-specific.

**Comment by Technici4n** [comment]
That seems to make sense. Going to request the expert's comments: @TelepathicGrunt.

**Comment by TelepathicGrunt** [comment]
I do already make my own birch and taiga tags to try and collect birch-like and non-snowy/non-mega taiga biomes. It would be a welcomed addition. Though the hard part is determining how to handle taiga as people may tag a snowy taiga as taiga tag. or their own mega taiga (redwood) as a taiga. Unless it is meant to include all taigas. 

I'm more interested in a birch tag as that's most usable for me and less likely to get biome entries I rather not spawn certain structures in

**Comment by kittech0** [comment]
@TelepathicGrunt what do you think about tag that has all natural biomes, live biomes, due that there already exist tag like wasteland so what about something that is reverse of wasteland?

**Comment by TelepathicGrunt** [comment]
I think the term you might be looking for is lush? Forge has a biome tag called lush for very lively and greenery biomes.

**Comment by TelepathicGrunt** [comment]
Here’s forge’s biome tags if there’s any that anyone is interested into pulling to fabric https://github.com/MinecraftForge/MinecraftForge/tree/1.19.x/src/generated/resources/data/forge/tags/worldgen/biome

**Comment by Technici4n** [comment]
Birch forest was added in #2955.
