### ISSUE TITLE
[Bug] Dimensions do not generate server side on first creation

### ISSUE THREAD

**Issue by itsdinkd** [FabricMC/fabric#2334]
Can reproduce with just Fabric API (any version for 1.18.2) and A mod that adds dimension.

When you create a local or dedicated server, and it starts for the first time, dimensions do not get generated in the world folder.  Only until you shut down the server and start it up again so that the world loads for the second time will it create the dimensions. 

MC: 1.18.2
Loader: Any
FAPI: Any

**Steps to reproduce**
1. Use any FAPI version
2. Add a mod that adds dimensions (Space Dimensions for this example)
3. Start local or dedicated server
4. Check world/, there will be no dimensions
5. shut down server
6. start up again, wait till server is fully running
7. check world folder, the dimension will be created in /dimensions

**Comment by warjort** [comment]
This is probably a bug in whatever mod you are using?
FAPI world generation mostly revolves around biome modification, it has no api for creating or saving dimensions.
What dimensions api exists is only about teleportation.
https://github.com/FabricMC/fabric/tree/1.19/fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/api/dimension/v1

Although see this: https://github.com/FabricMC/fabric/issues/2316
https://github.com/FabricMC/fabric/blob/1.19/fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/mixin/dimension/LevelStorageBugfixMixin.java

This bug fix of vanilla by forge maybe related to what you are seeing? But that is just a guess based on the similar reported behaviour.
https://github.com/MinecraftForge/MinecraftForge/blob/fa84c2266233961a2b92531ac73ac3d59a6ed109/patches/minecraft/net/minecraft/server/Main.java.patch#L70

**Comment by apple502j** [comment]
Already fixed for 1.19, backport for 1.18.2 will come soon (#2321)

**Comment by apple502j** [comment]
Hey GitHub, why did you decide not to close this? Weird.

**Comment by apple502j** [comment]
Seems like this issue (of dimensions not loading) does exist even after the patch.

**Comment by itsdinkd** [comment]
> Seems like this issue (of dimensions not loading) does exist even after the patch.

Its a weird one. I spent about 3 hours debugging, binary searching 380 mods thinking it waa a mod in my modpack. 

My question is how long was this a thing and how did no one notice it inxluding myself lmfao. I looked back for server pack exports where i tested a server instance and even back it didnt generate dimensions haha

**Comment by itsdinkd** [comment]
> This is probably a bug in whatever mod you are using? FAPI world generation mostly revolves around biome modification, it has no api for creating or saving dimensions. What dimensions api exists is only about teleportation. https://github.com/FabricMC/fabric/tree/1.19/fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/api/dimension/v1
> 
> Although see this: #2316 https://github.com/FabricMC/fabric/blob/1.19/fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/mixin/dimension/LevelStorageBugfixMixin.java
> 
> This bug fix of vanilla by forge maybe related to what you are seeing? But that is just a guess based on the similar reported behaviour. https://github.com/MinecraftForge/MinecraftForge/blob/fa84c2266233961a2b92531ac73ac3d59a6ed109/patches/minecraft/net/minecraft/server/Main.java.patch#L70

It does it with just fapi and mostly any mod that adds a dimension, except ae2. Ae2 for some reason generates

Also that forge patch doesnt help with this

**Comment by deirn** [comment]
> My question is how long was this a thing and how did no one notice it inxluding myself lmfao

Since it only happens on first load and fixes itself after restart, people probably think it's a fluke :P.
Anyway, #2343 should fix this.
