### ISSUE TITLE
Nobody can connect to my fabric server and everyone has the same mods

### ISSUE THREAD

**Issue by PenguinGiraffey** [FabricMC/fabric#2347]
I cant figure out why it wont work, all the mods are the same on server and client
![borked mc](https://user-images.githubusercontent.com/72631864/174661920-b9545a4d-5856-45c9-bba1-bdfa285736f3.png)
![modlist](https://user-images.githubusercontent.com/72631864/174661943-1e56faf2-06f5-4371-96d1-e5c7343bf58a.png)
![modlist2](https://user-images.githubusercontent.com/72631864/174661946-ff11e31c-d07a-4aae-a2b5-48797d0d17cc.png)
![modlist3](https://user-images.githubusercontent.com/72631864/174661953-91a63310-acdd-4ee4-85e5-07df077c5a14.png)
![modlist4](https://user-images.githubusercontent.com/72631864/174661962-17735fb2-6d43-427f-9a69-57c1e8d0d997.png)

**Comment by warjort** [comment]
Not a fabric issue;
https://github.com/MrKacafirekCZ/doggomod/issues/5
