### ISSUE TITLE
Game Crashed in Hypixel Game

### ISSUE THREAD

**Issue by Etnad29** [FabricMC/fabric#2357]
My game crashed at the end of a Hypixel Skywars Game. Version: 1.19
Here is the Crash Report:

The game crashed whilst rendering entity in world
Error: java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because the return value of "net.fabricmc.fabric.api.renderer.v1.RendererAccess.getRenderer()" is null
Exit Code: -1

I'm not quite sure why it happened...

**Comment by Linguardium** [comment]
this is unlikely to be a fabric api issue. can you open your latest.log, upload the contents to https://mclo.gs/ and paste the link here

**Comment by Etnad29** [comment]
https://mclo.gs/ghaZ0Pu

Here's the link, but I think it was a mod called "Custom Entity Models"
that caused it. Thanks for helping!
