### ISSUE TITLE
Wrong Logic In GlobalReceiverRegistry

### ISSUE THREAD

**Issue by warjort** [FabricMC/fabric#2359]
The check here is wrong:
https://github.com/FabricMC/fabric/blob/f11b62ad061f64269324c9f1c659fc495ae5e828/fabric-networking-api-v1/src/main/java/net/fabricmc/fabric/impl/networking/GlobalReceiverRegistry.java#L71

See:#2358
It should be ````if (replaced)````. This wasn't noticed before because most people register their receivers in the mod initialiser.

**Comment by liach** [comment]
I don't know who wrote this code, but the original author is incorrectly using write lock in multiple occasions when a simple read lock suffices.

**Comment by modmuss50** [comment]
Hi @warjort sorry for hyjacking your issue as I haven't been able to get in contact with you by any other means.

As you have been very active and helpful on the issues and discussion pages we were just wondering if you would like to join the triage team. This would provide you with some extra magical powers, such as being able to help moderate and manage the issues/discussions.

There is no commitment to be made, but I just wanted to confirm it with you first.

Thanks 👍

**Comment by warjort** [comment]
Ok with me, but I probably won't use any special powers, except maybe the support tag? :-)

**Comment by modmuss50** [comment]
Awesome, thanks. Thats basically the extent of the magical powers 😆

**Comment by modmuss50** [comment]
FYI, I invited you to the team a few days ago, I think you need to accept it somewhere. Possibly check your emails?

**Comment by warjort** [comment]
Ok done. :-)
