### ISSUE TITLE
Add fat-jar to the full api / meta dependency

### ISSUE THREAD

**Issue by NikkyAI** [FabricMC/fabric#239]
the dependency `net.fabricmc:fabric-api:0.3.0+Bbuild.175` https://maven.fabricmc.net/net/fabricmc/fabric-api/fabric-api/0.3.0%2Bbuild.175/
is a meta package, does not include the jar-in-jar (in turn its not production ready)

having a dependency configuration like so:
```
dependencies {
	include("net.fabricmc:fabric-api:0.3.0+Build.+")
}
```

will result in a project that will break once put into a production environment because none of the apis got included

now that might be intended, but i think either the dependency should be renamed and have `-meta` or `-dependencies` appended
or have the jars added
or add another artifact like `fabric-api-fat`

the experience i had was tinkering around, testing a thing, then testing it in multimc and noticing that because of this particular meta package that the produced mod jar was broken

i get that we are trying to discourage bundling the whole api (and i think we should not)
but i think improving consistency and reducing annoying surprises also has value

of if anyone has a idea of how to make `include` act transiently in only this particualr case it would fix the issue too

**Comment by modmuss50** [comment]
This was fixed in 1.19.2 and 1.19.3 fabric API. The default distribution is now the same fat jar uploaded to curseforge.
