### ISSUE TITLE
Fabric crashes loading the fabric-api mod when DRI_PRIME=1 is set.

### ISSUE THREAD

**Issue by m-soweli** [FabricMC/fabric#2403]
### Info
- **OS:** Void Linux x86_64
- **Launcher:** MultiMC
- **Fabric Loader:** 0.14.8
- **Fabric API:** 0.57.0+1.19
- **Java:** OpenJDK 17.0.3

### Description
When trying to run Fabric using my dedicated gpu, by setting the DRI_PRIME environment variable,
a java runtime crash is triggered. Note that this is a desktop computer, not a dual-gpu laptop. It's a long story.

### Logs
- [multimc and game](https://github.com/FabricMC/fabric/files/9140729/multimc.and.game.log)
- [java](https://github.com/FabricMC/fabric/files/9140746/hs_err_pid11688.log)

**Comment by modmuss50** [comment]
Can you confirm that this works with vanilla? Or without fabric-api (Just loader)?

**Comment by m-soweli** [comment]
I have tested with vanilla and without fabric-api. I see the game launch sometimes, other times I see the same crash. Sorry it seems like this might be a java bug.
