### ISSUE TITLE
add a way for the apis to be used by datapacks

### ISSUE THREAD

**Issue by Danjhop4** [FabricMC/fabric#2413]
If you want to add a biome to the world you need to make a mod or use multinoise that’s hard to use to add one biome where’s the api can do the same but can’t use data driven features like biomes or blocks may add more

**Comment by apple502j** [comment]
There are a few issues with data pack based APIs:

- They can only do what the game (or Fabric API) provides a means of. Modding directly allows anything.
- They can get pretty complex as new features get added. (That's happening with worldgen data packs, see?)
- Java code is performance-wise much better than data packs.
- It is too hard to maintain in Fabric API, as it has strong compatibility requirement and updates to every snapshot.

Note that if you want to add biomes easily, there are other options, like Terrablender. For now though, this suggestion is unlikely to be implemented.
