### ISSUE TITLE
Datapack driven access to the fabric api biome gen and blocks

### ISSUE THREAD

**Issue by Danjhop4** [FabricMC/fabric#2414]
Add a way to add biomes to multinoise easily as with code not useful for this and apis built on top of fabric won’t do as I can’t compile a mod so it has to be json based since Java will not work it would have to extend the fabric api
Modding will not work I know it would be work but it’s the only way that will work for my case

**Comment by Technici4n** [comment]
No for the third time (at least). Stop spamming our issue tracker.

**Comment by Danjhop4** [comment]
2 times this is my second post explaining why it would be good
