### ISSUE TITLE
Biome api does not include overworld and 3D biomes

### ISSUE THREAD

**Issue by Danjhop4** [FabricMC/fabric#2444]
Please update the biome api to include the overworld and 3D biomes as it is lacking them and way to force world noise maps to use density functions to override datapacks and mod biome sources

**Comment by apple502j** [comment]
I do not believe density functions are involved in the biome selection. That said, that is exactly why there is no such API: too complicated.

I recommend using other, third-party API mods like Terrablender. They don't provide the same support we do (i.e. does not update to every snapshot) but has more functionality than we can provide here.

**Comment by Danjhop4** [comment]
What  yes they are in noise settings for world gen
https://www.planetminecraft.com/data-pack/better-cave-gen/

**Comment by Danjhop4** [comment]
That pack is my own and and example

**Comment by Danjhop4** [comment]
{
  "sea_level": 63,
  "disable_mob_generation": false,
  "aquifers_enabled": true,
  "ore_veins_enabled": true,
  "legacy_random_source": false,
  "default_block": {
    "Name": "minecraft:stone"
  },
  "default_fluid": {
    "Name": "minecraft:water",
    "Properties": {
      "level": "0"
    }
  },
  "noise": {
    "min_y": -64,
    "height": 384,
    "size_horizontal": 1,
    "size_vertical": 2
  },
  "noise_router": {
    "barrier": 0,
    "fluid_level_floodedness": 0,
    "fluid_level_spread": 0,
    "lava": 0,
    "temperature": 0,
    "vegetation": 0,
    "continents": 0,
    "erosion": 0,
    "depth": "minecraft:end/sloped_cheese",
    "ridges": 0,
    "initial_density_without_jaggedness": 0,
    "final_density": {
      "type": "minecraft:interpolated",
      "argument": "minecraft:overworld/base_3d_noise"
    },
    "vein_toggle": 0,
    "vein_ridged": 0,
    "vein_gap": 0
  },
  "spawn_target": [],
  "surface_rule": {
    "type": "minecraft:sequence",
    "sequence": []
  }
}

**Comment by Danjhop4** [comment]
Depth is for the height dependent noise I picked a random one so it may not be 3d

**Comment by apple502j** [comment]
As you're probably aware, that is not a biome definition.
