### ISSUE TITLE
Fabric Minecraft keeps crashing with error code -1

### ISSUE THREAD

**Issue by DogemanMC** [FabricMC/fabric#2463]
Fabric Minecraft keeps crashing with error code -1, I have tried: Restarting Pc and Reinstalling Fabric.
You can download the crash log here.                                                                                                        
[crash-2022-08-13_12.31.23-client.txt](https://github.com/FabricMC/fabric/files/9331926/crash-2022-08-13_12.31.23-client.txt)

Please respond ASAP. I really want to use the following with Minecraft: Better F3, Sodium and Fabric API.

**Comment by DogemanMC** [comment]
WHY???

**Comment by apple502j** [comment]
@DogemanMC Please update Fabric API.

**Comment by DogemanMC** [comment]
@apple502j  Thanks! It works now!
