### ISSUE TITLE
Fabric 1.19.2 "Chat message validation failure"

### ISSUE THREAD

**Issue by ghost** [FabricMC/fabric#2465]
Hi, we just ported the server from Paper to Fabric and currently run two mods Lithium and Sodium. 

Performance was the main issue on Paper and we are quite happy with what Fabric is offering at this time however, lately without warning everyone gets booted off the server with this error: "Chat message validation failure" and we are not sure what specifically is causing it. Obviously this is incredibly irritating so we are looking any solution that can resolve this issue please.
![image](https://user-images.githubusercontent.com/87863492/184544095-eac4a5c8-4817-483c-a15e-8a20e90f5d74.png)

Thanks, Hell

**Comment by apple502j** [comment]
Please provide a list of mods, both on the server and the client.
