### ISSUE TITLE
Could not execute entrypoint stage 'client' due to errors, provided by 'toomanyorigins'!

### ISSUE THREAD

**Issue by Raikazarashi** [FabricMC/fabric#2468]
So apparently, the mod build is working as fine as it is until my PC crashed while my minecraft is still on.
After that I reopened the entire thing but this time it keeps giving me the same crash report over and over
Can someone identify what's wrong with this
[crash-2022-08-15_22.57.34-client.txt](https://github.com/FabricMC/fabric/files/9338029/crash-2022-08-15_22.57.34-client.txt)

**Comment by apple502j** [comment]
Open `config` folder in your Minecraft instance (`.minecraft` folder), find a file from Too Many Origins mod, and delete it. (It's somehow corrupted.)
