### ISSUE TITLE
Falling blocks cause game to crash

### ISSUE THREAD

**Issue by EmiMango** [FabricMC/fabric#2479]
When blocks affected by gravity fall, the game will crash and give a crash message
![Github Report](https://user-images.githubusercontent.com/111930443/186284330-1ea6432b-82e6-4621-b61d-ab625230ff09.png)

**Comment by Juuxel** [comment]
Not an issue with Fabric API itself but some mod using it. If you have Sodium installed, installing Indium might fix the crash.
