### ISSUE TITLE
20w14infinite appears to be a 1.17 version not a 1.16

### ISSUE THREAD

**Issue by Danjhop4** [FabricMC/fabric#2481]
The name on the mappings site ends in 1.17

**Comment by warjort** [comment]
That might be part of the joke? :-)

I think this is the correct version.
https://maven.fabricmc.net/net/fabricmc/fabric-api/fabric-api/0.5.7%2Bbuild.2-20w14infinite/

**Comment by Danjhop4** [comment]
At least it has the right files

**Comment by Danjhop4** [comment]
Missing any thing past 20w16a or so
