### ISSUE TITLE
Could not execute entrypoint stage 'main' due to errors, provided by 'fabric-networking-api-v1'!

### ISSUE THREAD

**Issue by ghost** [FabricMC/fabric#2494]
Hey, i get this error message along with this crash log whenever I try to open the game (custom modpack). I've looked everywhere and cant seem to find anyone else with this problem. Sorry if this isn't the right place to ask for help
[crash-2022-08-29_18.44.02-client.txt](https://github.com/FabricMC/fabric/files/9446936/crash-2022-08-29_18.44.02-client.txt)

**Comment by warjort** [comment]
Looks like an issue with cardinal components including the fabric-network-api for 1.19.1 in its jar?
This version won't work with 1.19

Others have already reported this problem:
https://github.com/OnyxStudios/Cardinal-Components-API/issues/138

**Comment by warjort** [comment]
Using 5.0.1 of cardinal components is the suggested workaround.

**Comment by ghost** [comment]
It worked! Thank you so much, I've been trying to fix this for several days.
