### ISSUE TITLE
Failed to run data generator - "Missing blockstate definitions" for every block in mod.

### ISSUE THREAD

**Issue by devvoid** [FabricMC/fabric#2495]
Developing a mod, trying to use model generation to cut down on the number of hand-made json files needed, but even registering an empty model generator causes the "Data Generation" task to fail.

Crash log: https://pastebin.com/SwWrNZFm

My code can be found here: https://github.com/devvoid/voidfurniture

Commenting out [this specific line](https://github.com/devvoid/voidfurniture/blob/1.18/src/main/java/net/prismaticvoid/voidfurniture/datagen/VoidFurnitureDatagen.java#L12) stops the crash, but then I can't use model generation at all.

Running on Windows 10, using IDEA.

**Comment by warjort** [comment]
````Caused by: java.lang.IllegalStateException: Missing blockstate definitions for: [Block{voidfurniture:oak_chair}, etc.````

It's crashing because you don't actually generate any models for your blocks, it's telling you what is missing.
https://github.com/devvoid/voidfurniture/blob/14e395f34a1fba72d08eb8c46b13f70cfeedae56/src/main/java/net/prismaticvoid/voidfurniture/datagen/ModelGenerator.java#L16
