### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by KeeveeKoomoo** [FabricMC/fabric#2500]
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'fabric-networking-api-v1'!
[crash-2022-09-01_04.17.32-client.txt](https://github.com/FabricMC/fabric/files/9466560/crash-2022-09-01_04.17.32-client.txt)

I am pretty sure I have an incorrect version of the fabric loader, however, idk what the correct version is, could I have help figuring this out pls lol

**Comment by apple502j** [comment]
Downgrade Cardinal Components.
