### ISSUE TITLE
fabric-rendering-fluids-v1-0.60.0

### ISSUE THREAD

**Issue by Waitner98** [FabricMC/fabric#2501]
I play on 1.19.2. Installed resource pack Nature+X where lava rendering was changed, but due to fabric-rendering-fluids-v1-0.60.0 lava is displayed according to testurka, and not as intended by the author. By removing this mod, the lava problem was gone, but the journeymap mod stopped rendering fluids. How can I fix it so that both work?

**With mod**
![2022-09-01_18 56 43](https://user-images.githubusercontent.com/93567213/187959416-c5bd5c7b-95d5-48d9-b5b3-99fd95817b81.png)
![2022-09-01_18 57 10](https://user-images.githubusercontent.com/93567213/187959420-097166a5-cdc5-4206-b840-fc25b41ca745.png)

**Without mod**
![2022-09-01_18 54 05](https://user-images.githubusercontent.com/93567213/187958937-4ad32715-3987-443c-8b35-b4ef7b32e873.png)
![2022-09-01_18 54 09](https://user-images.githubusercontent.com/93567213/187958947-2b4a45b9-7587-4f29-8662-92f2ef57ec39.png)

**Comment by apple502j** [comment]
Is https://www.curseforge.com/minecraft/texture-packs/nature-x the pack you're using? Any other packs installed?

**Comment by Waitner98** [comment]
Yes I have Nature X - v6.5 installed for 1.17.1 and Nature X 2.1 Beta which fixes some bugs. But this error is not related to the resource package, because without fabric api, namely fabric rendering fluids, this error does not exist. Of course there are other resource packs, but they won't affect this problem either.

> Используемый вами пакет https://www.curseforge.com/minecraft/texture-packs/nature-x ? Какие-то другие пакеты установлены?

**Comment by Technici4n** [comment]
We don't support Optifine, and we have no idea what they change, so we can't fix this.
