### ISSUE TITLE
Backport the "fabric-api" ID/alias

### ISSUE THREAD

**Issue by Madis0** [FabricMC/fabric#2527]
Fabric API recently added an alias _fabric-api_ to its current mod ID _fabric_, [then later did the opposite](https://github.com/FabricMC/fabric/commit/f60060dfe365941c3b7514d1e53cc7e09dbd671e). 

I suggest backporting either of those changes to as many older MC versions as feasible, so modders can start using the new ID sooner and with that, reduce users' confusion on what is that _fabric_ they really need.

**Comment by Player3324** [comment]
Definitely something I want to see, I think it tested out fine so at least all Loader 0.12+ dependent API versions can go for it.

**Comment by modmuss50** [comment]
Backported to 1.18.2.
