### ISSUE TITLE
1.18.2 custom items for crafting that do not get deleted in the process

### ISSUE THREAD

**Issue by Abalieno** [FabricMC/fabric#2570]
So, here we are.

I'm trying to create some custom kubeJS items that go in crafting recipes but that are returned, losing some durability rather than being deleted.

KubeJS has three commands to do this: replaceIngredient, damageIngredient, keepIngredient

None of these three commands work when used with kubejs items. 

After countless hours of testing all possible workarounds and chats with support channels, it seems the problem bogs down to a lack of support in Fabric API, and the problem being possibly fixed in 1.19.

That's great, but:
I cannot design a progression in 1.19, due to an handful core mods missing.
I can design a progression in 1.18, but cannot due to lack of support in Fabric/KubeJS for custom items that I need.

So my last attempt is to ask if someone can "patch back" 1.18 so that it's also usable.

**Comment by warjort** [comment]
Questions about kubejs should be asked on the kubejs discord.

**Comment by kwpugh** [comment]
@Abalieno on a side note, you can do the recipe remainder in 1.18.2 with a simple mixin in a mod.  let  me know if you need the  code.

**Comment by Abalieno** [comment]
@kwpugh thanks but it shouldn't be required at the moment.
I found a bandaid solution by "layering" Crafttweaker on top of KubeJS, and it's been able to work with kubeJS created objects without bugs.

Hopefully I won't find other problems.

**Comment by kwpugh** [comment]
Wonderful, glad you found a solution.
