### ISSUE TITLE
Indigo MaterialFinder doesn't seem to honor Translucent for blend mode

### ISSUE THREAD

**Issue by AlexIIL** [FabricMC/fabric#258]
Most likely caused by https://github.com/FabricMC/fabric/pull/213, as the `BLEND_MODE_MASK` is `0b011` rather than `0b111`, because the 5 possible values for `BlockRenderLayer {null, solid, cutout_mipped, cutout, trancluent}` needs 3 bits rather than 2.

**Comment by grondag** [comment]
Yep, looks like I did a bad.  Thank you for the report.  Will fix quickly.

**Comment by grondag** [comment]
Test build for fix is available here:  https://github.com/grondag/fabric/releases/download/fix-258-test/fabric-renderer-indigo-0.1.5+f8c32967.jar

**Comment by AlexIIL** [comment]
Thanks!
