### ISSUE TITLE
Fabric is not Vanilla

### ISSUE THREAD

**Issue by chyzman** [FabricMC/fabric#2592]
The Splash Text "Vanilla!" can appear while using fabric. This should not be the case due to the fact that that is a lie. For having fabric would mean that you aren't in fact using "Vanilla". pls fix

**Comment by haykam821** [comment]
This issue is unenforceable as splash texts already provide misinformation, such as in the currently incorrect splash text "Finally complete!" Therefore, the status of whether the game is modded does not inherently need to affect the presence of the splash text.

**Comment by modmuss50** [comment]
I like to think its refrencing vanilla ice cream. 🍨 

But yeah, not something we are going to change, you can quite clearly see if the game is modded on the main menu. Nice idea though 👍
