### ISSUE TITLE
Could not execute entrypoint stage 'client' due to errors, provided by 'byg'

### ISSUE THREAD

**Issue by Nyxnius** [FabricMC/fabric#2596]
Hello. I am trying to make a modpack for myself and friends to use, but right now am testing only singleplayer. I recently updated several mods in the pack, only to be met with a crash telling me it was Oh the Biomes You'll Go's fault. I unfortunately could not figure out what to do to fix it, without completely removing BYG (not an option, as that would corrupt all my in-use worlds)

https://pastebin.com/REMJkzZ1

Link to the crash report ^

If anyone is able to help, I would gladly appreciate it

**Comment by itsmiir** [comment]
you have a mixin conflict. one of your fishing mods (i assume) is messing with a class that BYG apparently mixes in to. remove your fishing mods one by one and you should find the issue.

also, this is a support issue and should be posted on the discord. the github is reserved for actual issues with the fabric toolchain.
