### ISSUE TITLE
[Suggestion] hook for sending resource reload changes to players

### ISSUE THREAD

**Issue by UpcraftLP** [FabricMC/fabric#262]
It would be nice to have a hook for when the resource reloading finishes, to send changes to all connected players.
(The hook would also need to provide access to the Playermanager instance)

in Vanilla, this is done in `Playermanager#onDataPacksReloaded()`, where ex. crafting recipes are sent to all connected clients.

**Comment by Pyrofab** [comment]
This hook should probably be fired when the data is first sent to a player too. [Prior art can be found here](https://github.com/Ladysnake/Requiem/blob/fabric/src/main/java/ladysnake/requiem/mixin/server/PlayerManagerMixin.java#L74-L84).

**Comment by UpcraftLP** [comment]
> This hook should probably be fired when the data is first sent to a player too.

Yes, totally forgot about that because I already had a mixin for it ^^

**Comment by liach** [comment]
#363 has an event that covers this need.

**Comment by Technici4n** [comment]
Implemented in #2265.
