### ISSUE TITLE
1.19.2 crash during startup: Could not execute entrypoint stage 'client' due to errors

### ISSUE THREAD

**Issue by KB-Q** [FabricMC/fabric#2620]
I'm getting this weird error in 1.19.2, can't figure out which mod is causing it, but going through the crash report seems like a general issue across all mods...  

This is 1.19.2 via MultiMC, with a bunch of structure, terrain and optimization mods.

Crash report: https://paste.ee/p/affwK
Mods list: https://paste.ee/p/IMISY

**Comment by apple502j** [comment]
Install https://github.com/Ladysnake/Satin and try again.

**Comment by KB-Q** [comment]
> Install https://github.com/Ladysnake/Satin and try again.

What should I do with that? It doesn't look like a mod, the page says it's a library to be added by modders to their project...
