### ISSUE TITLE
Biome tags

### ISSUE THREAD

**Issue by Prospector** [FabricMC/fabric#263]
allow people to add tags for biomes. Especially useful for modding, where the primary way to add features to existing biomes is by looping over them and finding what you want. This would allow us to loop over it and check if the tag contains the biome.

**Comment by valoeghese** [comment]
I approve of this idea

**Comment by valoeghese** [comment]
How difficult would it be to create biome tags

**Comment by LemmaEOF** [comment]
Cotton Resources [already does both biome and dimension type tags](https://github.com/CottonMC/CottonResources/tree/master/src/main/java/io/github/cottonmc/resources/tag). It's very easy.

**Comment by liach** [comment]
it is simple but it should be done async really

**Comment by ghost** [comment]
Hey this would still be really cool if it were a thing

**Comment by i509VCB** [comment]
So upon deliberation and recent tag changes, this cannot work in fabric api without imposing a client and server dependency on the extra tags module. I will make a new api (or a future fabric api pr) myself to handle this case specially due to the client/server mod requirements.

**Comment by liach** [comment]
This should have a new module.

**Comment by i509VCB** [comment]
Fun story, that was the original intention. It was a separate module in #521 until I tossed it today
