### ISSUE TITLE
Not compliable for 22w44a, not found that version

### ISSUE THREAD

**Issue by ghost** [FabricMC/fabric#2636]
I can't build for 22w44a. So, all projects, that can't working on 22w44a, is dead. 
Here is error build log: [error.txt](https://github.com/FabricMC/fabric/files/9934764/error.txt)
If anything, I don't know where, what or how to address it. Pass it on to other places if necessary. 

```
A problem occurred configuring project ':common'.
> Failed to setup Minecraft, java.lang.RuntimeException: Failed to find minecraft version: 22w44a
```

**Comment by apple502j** [comment]
Try with `--refresh-dependencies`. If this fails, check your firewall, VPN, government censorship, etc that can block access to Mojang server.

**Comment by unit-a-user** [comment]
About censorship, I have VPN.

**Comment by unit-a-user** [comment]
But error still have.

**Comment by unit-a-user** [comment]
Needs correct `version_manifest.json`, there is no `22w44a`.
