### ISSUE TITLE
Biome modification spawns do not work in cave biomes.

### ISSUE THREAD

**Issue by IMB11** [FabricMC/fabric#2640]
(1.19.2) When creating a biome modification that targets cave biomes, the spawn settings are ignored and no injected spawns are applied:

```java
iomeModifications.addSpawn(
                    biomeSelectionContext -> {
                        return biomeSelectionContext.getBiomeRegistryEntry().isIn(ConventionalBiomeTags.CAVES);
                    }, 
                    SpawnGroup.AMBIENT, 
                    EntityType.WOLF, 
                    100, 
                    2, 
                    4
            );
```

You would expect a large amount of wolves spawning in the cave biomes now - yet this is not the case.

`/tp @e[type=wolf,dy=106] @s` (I am standing on y=-46 when running this command, max y is 64

This command will teleport all of the wolves spawned in the cave biomes to the player.

![](https://oh.why-am-i-he.re/5MqMv9vzL.png)

As you can see, there are no wolves in the biomes.

**Comment by warjort** [comment]
I think you need to look at WolfEntity.canSpawn() or more accurately the SpawnRestriction class.
You won't find many grass and snow blocks above light level 8 in caves. :-) 
https://github.com/misode/mcmeta/blob/data/data/minecraft/tags/blocks/wolves_spawnable_on.json

**Comment by IMB11** [comment]
Going to be honest, never knew about these spawn restrictions. Thanks :+1:
