### ISSUE TITLE
Update fabric loot table to 1.14.3 async json loading

### ISSUE THREAD

**Issue by liach** [FabricMC/fabric#265]
In 1.14.3 pre-1, mojang [introduced async json loading for vanilla data](https://github.com/FabricMC/yarn/commit/4419bb581149af08f65db8f995006c630e11c1ef#diff-59086ebda1662467d2be49722b960752R1). This broke the loot table api's mixin at https://github.com/FabricMC/fabric/commit/05f11b75e48ed916fce820a704e601202cbc2e1e#diff-0a1c21c182b8708aff532f69a5f4feffR40

The correct way is to inject at the `apply` method that takes `(T, Executor)`.

Example error log: 
https://hastebin.com/metaquketa.rb
https://hastebin.com/hadetobere.makefile

Reports on discord:
https://discordapp.com/channels/507304429255393322/507982478276034570/587759437687554078 (includes a log snippet)
https://discordapp.com/channels/507304429255393322/507982463449169932/587859116484067328
https://discordapp.com/channels/507304429255393322/507982478276034570/587918350437318656

**Comment by liach** [comment]
Another fresh log coming! https://pastebin.com/AEa4qMV1

**Comment by MCrafterzz** [comment]
Another one: https://pastebin.com/AEa4qMV1

**Comment by liach** [comment]
Fixed in f0d568005e1f342e346c6060a0388556bf22a5bd
