### ISSUE TITLE
Unable to invoke commands on server

### ISSUE THREAD

**Issue by Lurmey** [FabricMC/fabric#2656]
Whenever I try to invoke an operator command, be it a vanilla command such as /kick or a modded command such as /yigd (from You're In Grave Danger) I get a "Cannot invoke" error and the command doesn't execute.

I haven't been able to test different mod configurations as the server is live and in-use.

[latest.log](https://github.com/FabricMC/fabric/files/9997694/latest.log)

**Comment by apple502j** [comment]
Seems like a race between `onCommandTree` and `onGameJoin`.

**Comment by modmuss50** [comment]
Do you have the same mods on the server, I assume its also a fabric server.

Would be nice if we can reproduce this with a minimal set of mods.

**Comment by Lurmey** [comment]
> Do you have the same mods on the server, I assume its also a fabric server.
> 
> Would be nice if we can reproduce this with a minimal set of mods.

This is what I checked first. Copied the mods list directly from the server into my client and it had no effect. I'll try to reproduce with minimal mods this evening.

**Comment by Lurmey** [comment]
Okay, I've just done a load of testing. Here's what I've found.
The issue occurs:
- on singleplayer worlds as well as multiplayer servers
- only on the FIRST world load of any Minecraft session
- 100% of the time on dedicated servers, as every server load is the first world load
- with only Accurate Maps, Fabric Language Kotlin, and The Twilight Forest installed

The issue does not occur:
- when Accurate Maps is removed, but Fabric Language Kotlin and Twilight Forest are still installed
- when Twilight Forest is removed

So it seems to be a conflict between Accurate Maps and The Twilight Forest. I'm still not 100% sure whether you can do much about this, I'll leave that to you to tell me, but I will report this to both the developers of Accurate Maps and Twilight Forest.

**Comment by Technici4n** [comment]
This is indeed probably not a Fabric bug.
