### ISSUE TITLE
[Suggestion] Access paths passed to game arguments

### ISSUE THREAD

**Issue by killjoy1221** [FabricMC/fabric#266]
We already have the `--gameDir` argument, but we're missing the `--assetsDir` which is not always `$gameDir/assets`. In development, this is located in `~/.gradle`. In the vanilla launcher, it is always `~/.minecraft/assets` no matter where the game dir is. This used to be accessible via `Launcher.assetsDir`, but this is not available in Knot.

A simple mixin to access it from `MinecraftClient` would work, but it really should be a dedicated class that can hold these paths.

**Comment by i509VCB** [comment]
Closing since this has been resolved via a recent fabric loader PR to get the game's launch args.
