### ISSUE TITLE
Error reported in the self-made module registration block

### ISSUE THREAD

**Issue by alazeprt** [FabricMC/fabric#2660]
I recently created a mod called [Alazeprt's Computer](https://github.com/alazeprt/Alazeprt-s-Computer), based on https://fabricmc.net/wiki/tutorial:blocks After creating the block, the game runs crashed
Crash Report:
[minecraft.log](https://github.com/FabricMC/fabric/files/10008948/minecraft.log)

**Comment by haykam821** [comment]
It seems that you are running your mod in a production environment. Which JAR file are you using for the mod? You need a remapped JAR file, so `dev` and `sources` will not work.

**Comment by alazeprt** [comment]
> It seems that you are running your mod in a production environment. Which JAR file are you using for the mod? You need a remapped JAR file, so and will not work.`dev``sources`

I used the JAR file of `dev` to load as the mod

**Comment by haykam821** [comment]
Use the JAR file that doesn't have a suffix.

**Comment by alazeprt** [comment]
> 使用没有后缀的 JAR 文件。

What do you mean?

**Comment by alazeprt** [comment]
> Use the JAR file that doesn't have a suffix.

But after the gradle is built, there are only two JAR files, dev and source

**Comment by alazeprt** [comment]
Problem solved
