### ISSUE TITLE
Game crashes when trying to create a new world

### ISSUE THREAD

**Issue by Suntix06** [FabricMC/fabric#2671]
With the 0.65.0 and 0.66.0 versions for 1.19.2 the game crashes when trying to create a new world.

https://user-images.githubusercontent.com/111528555/202874746-19832058-2ea8-47f5-a586-f68ed0f35346.mp4

Here is a link to the crash report: https://gist.github.com/Suntix06/5ebeda4562069551cc7e6b114d66f1e7

**Comment by modmuss50** [comment]
Update lithium to the latest version.
