### ISSUE TITLE
[Suggestion] show server tps command

### ISSUE THREAD

**Issue by 1a2s3d4f1** [FabricMC/fabric#268]
Add a command to show tps 

forge can use /forge tps show tps
`[Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Dim  0 (overworld) : Mean tick time: 42.796 ms. Mean TPS: 20.000`

**Comment by mattmess1221** [comment]
This is a perfect example of something a mod can do.

**Comment by TheInfamousAlk** [comment]
TPS is universal across all of java minecraft. It would benefit fabric to have a simple lightweight tps command like forge, neoforge, spigot, and many more do.

**Comment by Lolothepro** [comment]
> TPS is universal across all of java minecraft. It would benefit fabric to have a simple lightweight tps command like forge, neoforge, spigot, and many more do.

use `/tick query`
