### ISSUE TITLE
mixin crash fabric-api-0.67.0+1.19.2

### ISSUE THREAD

**Issue by Abalieno** [FabricMC/fabric#2680]
0.66 api seems to be loading fine.

No idea what's causing this.

[latest.log](https://github.com/FabricMC/fabric/files/10056603/latest.log)

**Comment by Technici4n** [comment]
Please report to NBT Crafting for `@Overwrite`'ing a method that we inject into.

**Comment by Abalieno** [comment]
Well, any chance you know where the mod is? It's not on the list, so I guess it's bundled inside some other mod?

It seems already notified anyway: https://github.com/Siphalor/nbt-crafting/issues/126

Maybe it's "spice of fabric"

**Comment by Technici4n** [comment]
Yeah it's spice of fabric. You can see `nbtcrafting 2.2.0+mc1.19 via spiceoffabric` in the modlist at the beginning.

**Comment by Siphalor** [comment]
> Please report to NBT Crafting for `@Overwrite`'ing a method that we inject into.

While you're correct that Nbt Crafting uses an `@Overwrite` where it's not necessary (anymore - it was for a long time because the target is an interface), I‌ just want to clarify that Nbt Crafting came first and Fabric API‌ just introduced that functionality *yesterday*.
So, I could say Fabric API‌ is `@Inject`ing a method I was overwriting for multiple years without big issues.
 
I agree with your conclusion, I‌ just want to point out the tone again, which just emphasizes why I‌ originally dropped out of the Fabric API‌ community.

I'm gonna try to get this issue fixed as soon as possible.

**Comment by modmuss50** [comment]
There isnt a major rush, I released this version as a beta so issues like this have less of an impact. I will keep it in beta for a few more days.

I dont thinkthere was any intention of a negative tone, it can be read either way imo. Lets all be positive 👍

**Comment by Technici4n** [comment]
Hi, you are correct that your overwrite has existed for years without a problem. I don't think we can or should adapt for it, so I only shared the conclusion as I thought it would be the only information that would matter. Next time I'll include more context to avoid such misunderstandings.

Nonetheless, thanks for getting this resolved ASAP. :+1:

**Comment by Abalieno** [comment]
For whoever might be checking this. It's not only spice of fabric.

New version of Create is out, I need to test if it's related to a recipe fix. But it now requires the new API and even removing spice of fabric from the folder still gives the same error. So I guess nbt crafting is embedded again somewhere else.

Curseforge says MI embeds it? It doesn't look so, maybe an old version. But there's nothing else on the dependency CS page...

**Comment by Siphalor** [comment]
I've published a fixed release (2.2.3) yesterday.  

If you put that in your mods folder, you should hopefully be fine :)

**Comment by Abalieno** [comment]
Adding the mod fixed the other mods.
The one I was using beside Spice of Fabric, was Peculiar Pieces.
Tech gave a nice suggestion since dependencies show in log: "nbtcrafting 2.1.3+mc1.19 via peculiarpieces"

One more thing learned :)

**Comment by Technici4n** [comment]
Thank you for the quick fix ! :)
