### ISSUE TITLE
[Crash] - 0.67.1 crashes - 0.66.0 works - fabric item api v1 failed

### ISSUE THREAD

**Issue by xR4YM0ND** [FabricMC/fabric#2687]
Hey, looks like the newest version crashes on startup

client [latest.log](https://gist.github.com/SpigotDE/db53e0947080f03b6ee9291b9f8db19d)

**Comment by Technici4n** [comment]
Hi, this is caused by an incompatibility between the latest fabric API and older versions of NBT crafting (included in spice of fabric). You can install the latest version of NBT crafting (version 2.2.3) to fix this: https://www.curseforge.com/minecraft/mc-mods/nbt-crafting.
