### ISSUE TITLE
SoundEvent turned private

### ISSUE THREAD

**Issue by haubna** [FabricMC/fabric#2694]
In 1.19.3-pre2 the SoundEvent class is private and thus you are unable register SoundEvents as described here https://fabricmc.net/wiki/tutorial:sounds
The static constructor methods of SoundEvent also seem to be protected. The SoundEvents class can register them due to being in the same package but as a modder it seems like we need to use AW or a Mixin now.

**Comment by apple502j** [comment]
Yeah, we should TAW this.

**Comment by modmuss50** [comment]
I think it would be better to TAW the two `of` builder methods. 👍

**Comment by meza** [comment]
Looking forward to this
