### ISSUE TITLE
Crash when opening world

### ISSUE THREAD

**Issue by Sajeyson** [FabricMC/fabric#270]
Minecraft: 1.14.3-pre2
Fabric API: fabric-api-0.3.0+build.184
Fabric Loader: 0.4.8+build.155-1.14.3-pre2+build.4
Crash report https://pastebin.com/WZX8RsCc

**Comment by Prospector** [comment]
Fabric API currently targets 1.14.2 and does not have support for 1.14.3

**Comment by asiekierka** [comment]
Well, no; you can compile a compatible version of API from snapshot/1.14.3, now
