### ISSUE TITLE
MC-129409 is not resolved in fabric server 0.14.10(1.19.2)

### ISSUE THREAD

**Issue by Khhs167** [FabricMC/fabric#2702]
***What is the issue?***
When entering water, the players gravity isn't affected, swimming cancels immediately etc.  
This is addressed in the stated-to-be-fixed issue [MC-129409](https://bugs.mojang.com/browse/MC-129409)

**Reproduction**

1. Start a Fabric 1.19.2 server, Modloader 0.14.10, java 19
2. Join the game from client
3. Enter water

**System Information**
```
Raspberry PI 4B 4GB
Fabric 0.14.10
Minecraft 1.19.2
```

**Comment by Khhs167** [comment]
Please tell me this is the right place to put this lol

**Comment by apple502j** [comment]
Also I believe we have nothing to do with this

**Comment by Khhs167** [comment]
well the issue doesn't seem to be present in *any* other version so
