### ISSUE TITLE
Crash on loading world in dev setting at version 183 and 184 but 181 and before works.

### ISSUE THREAD

**Issue by MrPurple6411** [FabricMC/fabric#271]
[crash-2019-06-14_05.25.51-client.txt](https://github.com/FabricMC/fabric/files/3290409/crash-2019-06-14_05.25.51-client.txt)

# Fabric Properties
minecraft_version=1.14.3-pre2
yarn_mappings=1.14.3-pre2+build.10
loader_version=0.4.8+build.155

#Fabric api
fabric_version=0.3.0+build.184

**Comment by asiekierka** [comment]
What version of Minecraft is that build of Fabric API for?

**Comment by MrPurple6411** [comment]
@asiekierka ok but then why does fabric api 181 work just fine????????

**Comment by asiekierka** [comment]
New versions of API add new features. It turns out the loot table logic changed in 1.14.3-pre2, so that version needs fixed patches (on the API's snapshot branch, but not pushed publicly due to buildsystem deficiencies)

**Comment by MrPurple6411** [comment]
good reason
thank you... sorry still new to modding
