### ISSUE TITLE
Game chrashes when sand/gravel falls

### ISSUE THREAD

**Issue by Ben10Gh** [FabricMC/fabric#2715]
The game crashed whilst rendering entity in world
Error: java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because the return value of "net.fabricmc.fabric.api.renderer.v1.RendererAccess.getRenderer()" is null

**Comment by Juuxel** [comment]
(This is mostly likely a compatibility issue between Sodium and a mod using the Fabric Rendering API - installing Indium may fix it in that case)
