### ISSUE TITLE
IndigoRenderer: strange black shadows in some blocks

### ISSUE THREAD

**Issue by LordRius** [FabricMC/fabric#272]
Hi!

I'm using Fabric API 0.3.0 build 184 with no mods, no resource packs and i have discovered something strange that do not seem to happen without API or with 0.2.7 build 127. You can see a black shadow in some blocks in a certain facing...

https://gfycat.com/cookedmeaslyheterodontosaurus
https://gfycat.com/incompleteanothercanine

I hope you can reproduce the issue,

Regards.

**Comment by grondag** [comment]
Definitely should not be doing that. Will take a look.

**Comment by grondag** [comment]
@LordRius This [test build](https://github.com/grondag/fabric/releases/download/273-Test-Build/fabric-renderer-indigo-0.1.7+d2b912dd.jar) should fix your problem until the main distribution is updated.

**Comment by LordRius** [comment]
Many thanks @grondag for your super fast fix! I'm trying it now with latest api build 0.3.0 - 185 and all is working fine, no more black shadows :D

**Comment by grondag** [comment]
You’re welcome. Thank you for the  good bug report. Good bug reports get fixed.
