### ISSUE TITLE
Hey I cant see entities when using the API

### ISSUE THREAD

**Issue by jharrison123** [FabricMC/fabric#2725]
### Discussed in https://github.com/orgs/FabricMC/discussions/2711

<div type='discussions-op-text'>

<sup>Originally posted by **jharrison123** November 27, 2022</sup>
Hey so I am running GDLauncher on a Linux Mint system and whenever I load minecraft Fabric with the fabric api, no other mods, I cant see animals, mobs, or any entity with an AI it looks like. Is there any way to patch this?</div>

**Comment by apple502j** [comment]
- Can you try other versions of Fabric API?
- Can you try if it works with alternate rendering implementations, such as Sodium?
- Can you give the crash report (press F3+C for 10 secs)?

Note, Minecraft rendering code is incompatible with some graphic drivers, and Linux support is not usually good.
