### ISSUE TITLE
In order to play a specific version of fabric, you need to have played that version of vanilla first

### ISSUE THREAD

**Issue by redstonerti** [FabricMC/fabric#2732]
I was trying to use the cli to install fabric 1.19.2. First, I deleted the .minecraft folder, reinstalled and played vanilla 1.19.3 and then used the cli to install fabric. Every time I try to launch the game, I get this popup:
![image](https://user-images.githubusercontent.com/48157961/206527859-77b5f43a-472e-4edc-8d5b-0c79741a0f1d.png)
After that, the green button keeps on loading infinitely and the launcher is broken. I can't play any instance of minecraft and have to close and reopen it.
![image](https://user-images.githubusercontent.com/48157961/206528051-18b71976-82d5-4d8e-bb1c-e661d2ae55f0.png)
Command I used to install the profile:
![image](https://user-images.githubusercontent.com/48157961/206528554-59ed5717-7c37-4c22-8f79-4441052d5fc4.png)

Launcher log: https://pastebin.com/jUWpJSh7

Edit: I checked some other versions other than 1.19.3, and all of them failed.

Ryzen 7 7700x
Windows 11 10.0.22621 Build 22621
Installer version: 0.11.1
Loader version: 0.14.11
I'm using a Microsoft account and own the game.

**Comment by modmuss50** [comment]
This is a launcher bug, I have opened a report here: https://bugs.mojang.com/browse/MCL-22850 (Please vote on it)

As far as I know there is nothing I can do to fix this. I will keep this issue open to track it however.

**Comment by modmuss50** [comment]
Closing this as there isnt anything we can do about it.
