### ISSUE TITLE
zero-knowledge proof for modlist privacy

### ISSUE THREAD

**Issue by SoniEx2** [FabricMC/fabric#2733]
using a ZKP for client-server compatibility check might provide useful privacy advantages.

**Comment by haykam821** [comment]
I'm not sure what this issue is proposing a change for. There is no specific compatibility check in Fabric API, and the closest functionality is registry sync, which is required for general protocol compatibility.

**Comment by SoniEx2** [comment]
there's no compatibility check in ping packet?

**Comment by Patbox** [comment]
There never was in fabric. There are 3rd party mods for that through

**Comment by modmuss50** [comment]
Its an intresting idea maybe something to consider if/when we add this, but yeah we currently do not send the mod list.

Its not something I knew existed before I quickly looked up what it was. Adding something like this may involve some complex code that may open us up to possible security vulnerabilities.
