### ISSUE TITLE
[Suggestion] ItemStack model provider?

### ISSUE THREAD

**Issue by Takakura-Anri** [FabricMC/fabric#274]
Such as (ItemStack, ModelProviderContext) -> UnbakedModel is needed, as they are very useful in mapping custom models

**Comment by grondag** [comment]
Could you elaborate on what you’re trying to do? There are already a couple different ways to handle custom item models.

**Comment by asiekierka** [comment]
You can't... really do that, though. Not at this level, as BakedModels are keyed by Item, not ItemStack.

ModelItemPropertyOverrideList is what you're looking for, plus providing your own BakedModels. I recommend writing a helper library to handle this, but I don't think it belongs in API unless doable easily.

**Comment by grondag** [comment]
There are currently two ways to vary item model content based on item stack.  The most conventional way is via ModelItemPropertyOverrideList and a custom BakedModel implementation, per Asie's post above.  This method is unsuitable for a very large number of variations. 

The second way is to implement [`FabricBakedModel`](https://grondag.github.io/renderosity/fabric-api-javadoc/net/fabricmc/fabric/api/renderer/v1/model/FabricBakedModel.html) and override `emitItemQuads()`.  This second method provides practically unlimited flexibility but will most performant when model content is statically baked.

The hooks in `net.fabricmc.fabric.api.client.model` provide the means for injecting custom models.

Closing given that hooks already exist and no additional requirements were given.
