### ISSUE TITLE
No "group" option upon updating to 1.19.3

### ISSUE THREAD

**Issue by Logboy2000** [FabricMC/fabric#2760]
A basic example of what my items look like
`public static final Item DIAMOND_NUGGET = new Item(new FabricItemSettings().group(ItemGroup.MATERIALS).group(LMod.LMODGROUP));`
![image](https://user-images.githubusercontent.com/72185335/207740429-751ae770-db99-4dd8-930b-faae2d690768.png)
![image](https://user-images.githubusercontent.com/72185335/207740522-48861937-a63c-4834-a019-b75ac189602d.png)

**Comment by Technici4n** [comment]
That's due to vanilla changes, please look at the update post: https://fabricmc.net/2022/11/24/1193.html#item-groups.

**Comment by Logboy2000** [comment]
Thank You!
