### ISSUE TITLE
some intrusive holders were not added to registry: [Reference{null=air}]

### ISSUE THREAD

**Issue by shupliance** [FabricMC/fabric#2786]
from having searched for this issue, I can tell this is the sort of error people who are developing mods get when they fail to add something (a block?) they implement to a registry. i'm not exactly fluent with java or javascript so i'm slightly lost here, but i'm not a mod developer, this crash occurred after changing a config that affected items (not blocks) in the server's world, presumably resulting in them being corrupted but I really can't tell. if anyone has a solution it would be greatly appreciated, let me know if more information is required!

the specific config I edited was the betterend items config, I disabled all of the hammers (which some people had crafted by now.) the crash did continue when I set the hammers back to "true."

crashlog: https://pastebin.com/2yNw5S3K

**Comment by warjort** [comment]
Not a fabric api issue.

You get this error for any unregistered object that has instrusive holders, which includes items.

I suggest you speak to whichever mod author's configuration you changed 
and describe the configuration settings that cause the problem.
