### ISSUE TITLE
Items don't drop - 1.14.3 pre 1

### ISSUE THREAD

**Issue by blank-blank-blank-blank-blank** [FabricMC/fabric#279]
When running fabric 1.14.3 pre 1 - build 0.5.0.30 - blocks don't drop items. I do not have the API installed, but the API also crashes when attempting to load on 1.14.3 pre 1 because (from what I understand) the API doesn't work past 1.14.2.

**Comment by asiekierka** [comment]
That... I don't believe that, sorry. No mods?

**Comment by modmuss50** [comment]
Closing as no response.
