### ISSUE TITLE
Reproducible lag on fabric 1.19.2 server with no mods.

### ISSUE THREAD

**Issue by ShibeTemple** [FabricMC/fabric#2804]
Hey all, hope you are doing well. On fabric version 1.19.2 (happens on both 0.14.12 and 0.14.11), there seems to be a persistent issue with clients syncing with the server on join and right after resuming from death. 

The issue is that there is a brief period of about 3 seconds where data is sent from the client, but data seemingly is not received/processed on the client.

This occurs on a stock fabric server with no mods.

I am able to reproduce this issue consistently, and it gets worse when you add mods to the mix. With mods, the latency increases, and it can reach a point to where the client leaves due to a timeout.

Some examples include: 

- user sends message in chat. Chat is seen by server and sent to all players but the client that sent it does not see it themselves. 
- Blocks break, but no items drop.

Adding Krypton and Lithium to both the clients and server does not absolve the issue.
This is not a network performance issue, as after the delay has passed, gameplay resumes as normal. Also, ping is low for client and server (12-20ms). Bandwidth is high. Speeds excess of 400Mb/s on both client and server. This is also not a client or server performance issue. Server is running with 8GB allocated, and on an i7 CPU, NVMe SSD. No bottlenecks present while monitoring the server or client performance. This also would not be a performance issue as it only occurs after resuming from death or on join. 

Since this issue is reproducible with no mods on a fabric server, I am seeking your help in reducing or eliminating this lag. Especially, as with mods, it only gets worse. I initially did not think this could've been a fabric issue but it's still present on a stock fabric server with no mods.

**Comment by ShibeTemple** [comment]
I did not attach logs, as no relevant information is displayed in them. Everything appears as normal on both the client and server.

**Comment by Technici4n** [comment]
Hi, have you tried attaching a profiler such as VisualVM to figure out what's going on?

**Comment by ShibeTemple** [comment]
No, what would you like me to monitor in VisualVM? @Technici4n

**Comment by Technici4n** [comment]
The lag. Without a profile we can't really tell where the lag is coming from.
