### ISSUE TITLE
The interface events in PlayerBlockBreakEvents are named horribly

### ISSUE THREAD

**Issue by WaveringAna** [FabricMC/fabric#2815]
They're just named `Before, After, Cancelled` instead of something more descriptive like `BeforeBreak` and `CancelledBreak` like any of the other events

https://github.com/FabricMC/fabric/blob/e6f4ce589f01b312457ba02668ecf86134332cbc/fabric-events-interaction-v0/src/main/java/net/fabricmc/fabric/api/event/player/PlayerBlockBreakEvents.java#L80

https://github.com/FabricMC/fabric/blob/e6f4ce589f01b312457ba02668ecf86134332cbc/fabric-events-interaction-v0/src/main/java/net/fabricmc/fabric/api/event/player/PlayerBlockBreakEvents.java#L97

https://github.com/FabricMC/fabric/blob/e6f4ce589f01b312457ba02668ecf86134332cbc/fabric-events-interaction-v0/src/main/java/net/fabricmc/fabric/api/event/player/PlayerBlockBreakEvents.java#L111

**Comment by Technici4n** [comment]
This is intended, and matches our newer conventions for event naming. See also the example under https://github.com/FabricMC/fabric/blob/1.19.3/CONTRIBUTING.md#events.

**Comment by WaveringAna** [comment]
its a terrible naming convention

**Comment by WaveringAna** [comment]
To be less crass and give examples, this shows very clearly what event I'm listening to without the need of a comment
<img width="202" alt="image" src="https://user-images.githubusercontent.com/10069649/210218959-542b525e-299a-453b-8ff8-fdb8bd35c8bf.png">
However this just says `after` and won't be clear unless I look at the imports, and even then if I have many packages imported, it will not be clear unless I add an unnecessary comment
<img width="372" alt="image" src="https://user-images.githubusercontent.com/10069649/210219114-daebb3fd-b438-48db-9888-4b02d5236f64.png">

**Comment by Technici4n** [comment]
Two notes:
1. You can use a more qualified name, for example `implements BlockBreakEvents.After`.
2. It's recommended to use lambda functions for event listeners. Then the listener declaration will look like `BlockBreakEvents.AFTER.register((...) -> {...});`
