### ISSUE TITLE
Remove leftover `@ApiStatus.Internal` annotations

### ISSUE THREAD

**Issue by Technici4n** [FabricMC/fabric#2822]
Since the annotations are now autogenerated for impl classes, most of the remaining annotations can be removed.

**Comment by Juuxel** [comment]
I thought I removed all the ones in impl 🤔

**Comment by Technici4n** [comment]
This is the one I saw: https://github.com/FabricMC/fabric/blob/2dae9cfaf02178bc9444422e65fd9681862d2da6/fabric-resource-conditions-api-v1/src/main/java/net/fabricmc/fabric/impl/resource/conditions/ResourceConditionsImpl.java#L51 and there's a lot more apparently.

**Comment by Juuxel** [comment]
Some of them have been introduced after my PR at least like the new recipe remainders and item groups I think
