### ISSUE TITLE
cant trade with villagers

### ISSUE THREAD

**Issue by stoneshout** [FabricMC/fabric#2839]
i encountered a  issue ware i go trade with villagers with updated version of fabric api and the villagers trade ui wont open up when i play on later older versions it works

**Comment by apple502j** [comment]
@stoneshout Please provide a list of mods (at least screenshot of mods folder) and the Minecraft version. If you can, please also provide the log files.

**Comment by stoneshout** [comment]
fixed it by updating fabric mod loder to 0.14.12 then updating fabric api to 0.71.0
