### ISSUE TITLE
Fabric API 71 and above crashes whole game if booting up with mods.

### ISSUE THREAD

**Issue by RealmKebab** [FabricMC/fabric#2843]
Fabric API entirely crashes the game (even if the game isn't even shown-on screen since its loading everything)
API versions above 70 crashes the game.
Here are my crash logs:
[crash-2023-01-10_17.49.36-client.txt](https://github.com/FabricMC/fabric/files/10383809/crash-2023-01-10_17.49.36-client.txt)
[crash-2023-01-10_17.46.38-client.txt](https://github.com/FabricMC/fabric/files/10383812/crash-2023-01-10_17.46.38-client.txt)

**Comment by warjort** [comment]
Not a fabric api issue:
https://github.com/TeamMidnightDust/MidnightControls/issues/158
Upgrade the midnightcontrols mod to the latest version.
