### ISSUE TITLE
Feature idea a way to disable custom world screen

### ISSUE THREAD

**Issue by Danjhop4** [FabricMC/fabric#2846]
a way to disable custom world screen Since early modders or people may want to use datapack features with out the screen in there mods

**Comment by notlin4** [comment]
Use this [mod](https://www.curseforge.com/minecraft/mc-mods/fabric-disable-custom-worlds-advice)

**Comment by Danjhop4** [comment]
I know mod exists that give me the idea lol

**Comment by Danjhop4** [comment]
I mean built in

**Comment by Danjhop4** [comment]
Appears ether fabric has patched it or mojang has

**Comment by Danjhop4** [comment]
> Use this [mod](https://www.curseforge.com/minecraft/mc-mods/fabric-disable-custom-worlds-advice)

Appears mojang or fabric already patched it
