### ISSUE TITLE
server stating old even tho there is same build /mods configs etc loaded(1.14.3)

### ISSUE THREAD

**Issue by SDUBZ** [FabricMC/fabric#286]
no matter if i have mods or not fabric server appearing as old as seen here: http://puu.sh/DN6TO/84c7ab58a9.png

i also noticed with virtual server the /stop and /debug are doing nothing in the cmd output 

http://puu.sh/DN8rI/26e3217d8b.png
http://puu.sh/DN8s9/0b7cd2f778.png
http://puu.sh/DN8sr/a829de038b.png

server:
[latest.log](https://github.com/FabricMC/fabric/files/3343954/latest.log)

client:
[latest.log](https://github.com/FabricMC/fabric/files/3343956/latest.log)

**Comment by modmuss50** [comment]
In the log you provided the server had not finished starting. This seems to be a mod issue, feel free to ask for more support on the fabric discord.

If you can repoduce this issue with just fabric installed please open a new issue.
