### ISSUE TITLE
Key binds registered using KeyBindingHelper aren't showing on settings

### ISSUE THREAD

**Issue by Lucasmellof** [FabricMC/fabric#2879]
Minecraft version: `23w05a`
Fabric API version: `0.73.3+1.19.4`
Fabric Loader version: `0.14.13`
Mappings: `23w05a+build.4`

**Comment by apple502j** [comment]
Please provide the mod source code.

**Comment by modmuss50** [comment]
I can reproduce this with the testmod in fabric API. Appears to be a 1.19.4 only issue.
