### ISSUE TITLE
fabric api shows so many mods on menu.

### ISSUE THREAD

**Issue by SaltyWhiteBoy** [FabricMC/fabric#288]
![image](https://user-images.githubusercontent.com/52527718/60652080-2e210900-9e50-11e9-835e-bff6532148b2.png)

![image](https://user-images.githubusercontent.com/52527718/60652032-16498500-9e50-11e9-9dcd-20b7b36e6333.png)

it's really annoying to go thorugh all of these just to adjust a mod. please fix

**Comment by Dinolek** [comment]
#235

**Comment by SaltyWhiteBoy** [comment]
didnt understand a thing. cant i just stop seeing them ?

**Comment by Boundarybreaker** [comment]
This is not an issue with Fabric API. Fabric API does not add this mod menu, so there's nothing we can do about it. Something to fix this is being worked on in mod menu currently.

**Comment by grondag** [comment]
Agree this is not something to be addressed in the Fabric API directly.

**Comment by Prospector** [comment]
The system in Mod Menu to deal with this is implemented, and is currently waiting on Fabric API to either support it (see #235) or for Fabric Loader to add their own metadata for grouping that modmenu can then use. The ball's no longer in my court.

**Comment by partisani** [comment]
I see this as normal
