### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Tobias-Rumpe** [FabricMC/fabric#2885]
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'fabric-api-lookup-api-v1'! Pls Help

**Comment by haykam821** [comment]
Could you post a full game log? This issue will be hard to diagnose otherwise.

**Comment by Tobias-Rumpe** [comment]
translator  Naturally 
[crash-2023-02-04_00.13.17-client.txt](https://github.com/FabricMC/fabric/files/10609289/crash-2023-02-04_00.13.17-client.txt)

I hope it helps Thank you for trying to help me

**Comment by apple502j** [comment]
"Maybe data" mod is for a different game version.
