### ISSUE TITLE
cutout fabric api render on trapdoor xrays on ground

### ISSUE THREAD

**Issue by Danjhop4** [FabricMC/fabric#2891]
![render](https://user-images.githubusercontent.com/106870098/217049105-22dfaef1-11bf-4e4c-a199-77e1036ba071.png)
it does not do xray effect when open on the ground

**Comment by haykam821** [comment]
You've set the block to render its faces as cutout so that transparent pixels are rendered as transparent. Does your model set cull faces properly, and does its outline match with its model? Those two things must be correct for culling to not create this effect.

**Comment by Danjhop4** [comment]
its using the oak trapdoor blockstate
