### ISSUE TITLE
Fabric API resource pack description should be translatable

### ISSUE THREAD

**Issue by Madis0** [FabricMC/fabric#2895]
https://github.com/FabricMC/fabric/blob/1.19.3/fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/impl/resource/loader/FabricModResourcePack.java#L50 should have a translation string on https://github.com/FabricMC/fabric/blob/1.19.3/fabric-resource-loader-v0/src/main/resources/assets/fabric-resource-loader-v0/lang/en_us.json

**Comment by Technici4n** [comment]
This is now released in 1.19.4. Thanks again for the PR!
