### ISSUE TITLE
A patch to load to datapacks into world data and and out

### ISSUE THREAD

**Issue by Danjhop4** [FabricMC/fabric#2897]
If you remove a datapack after making a world it crashes 
And if you add one it does not show up in a world I would add a patch to restore or add and remove packs if the pack does not exist and add new ones
This is in at least 23w05a

**Comment by apple502j** [comment]
This is a deliberate decision by Mojang to prevent world corruption, and I don't believe we should change this.

**Comment by Danjhop4** [comment]
it’s annoying and makes no sense I would fix it but I don’t know how it’s not fair people lose the there worlds because mojang want a dumb system

**Comment by Danjhop4** [comment]
> This is a deliberate decision by Mojang to prevent world corruption, and I don't believe we should change this.

It cause world corruption

**Comment by apple502j** [comment]
Removing or adding worldgen data packs after world creation is not supported.

We are not Mojang, we don't fix their mistakes.

**Comment by Danjhop4** [comment]
Already fixed in 23w06a come to close it
