### ISSUE TITLE
Misleading api in BlockRenderLayerMap

### ISSUE THREAD

**Issue by SHsuperCM** [FabricMC/fabric#2925]
Although it is very clear that `BlockRenderLayerMap` only handles the render layers of blocks, it contains both api and javadocs that imply that the same map could handle items extending the general `Item` class.
https://github.com/FabricMC/fabric/blob/ad80728a79f936d9182d58122a876696a8b82a8c/fabric-blockrenderlayer-v1/src/client/java/net/fabricmc/fabric/api/blockrenderlayer/v1/BlockRenderLayerMap.java#L59-L75
It would be much clearer if the arguments for these methods took `BlockItem`s instead and their javadocs should clearly state that this affects only items extending `BlockItem`.

**Comment by Technici4n** [comment]
Thank you for the issue! I think deprecating the methods entirely is the best course of action. See #2930.
