### ISSUE TITLE
[1.19.4] Client screen glitches out after being kicked from a dedicated server

### ISSUE THREAD

**Issue by Wesley1808** [FabricMC/fabric#2944]
Reproduction Steps:
- Launch Minecraft client on 1.19.4 pre-2 with Fabric API 0.75.1
- Join or setup a 1.19.4 pre-2 server with permission to disconnect yourself
- run `/kick @s`

You will get a screen similar to this one, with a small part of the server list in the middle.
You can still interact with everything, just hardly see anything (this image is from after rejoining the server whilst glitched).

![Screenshot (31)](https://user-images.githubusercontent.com/74668381/222143403-8c2c941c-0646-433b-bc45-ebc5257d5430.png)

**Comment by modmuss50** [comment]
Thanks for reporting this, I can reproduce it, its not great...

<img width="966" alt="Screenshot 2023-03-01 at 13 11 45" src="https://user-images.githubusercontent.com/4324090/222148969-f84e2e1a-10c3-443e-8311-c3917988dd22.png">
