### ISSUE TITLE
Advancement event hook?

### ISSUE THREAD

**Issue by 0x4e49434f4c45** [FabricMC/fabric#2949]
Hi!

I've searched past issues and discussions and haven't found anything so I'll ask here. It seems like listening to advancements is a common and simple thing for a mod to do. Fabric currently provides APIs for registering new advancements, but (as far as I've been able to find) there's no event that fires when a player gets an advancement. The mixin to do this seems trivial, but then your mod has entered Mixin Territory with all the compatibility issues that implies.

Has an event of this type been considered for Fabric API in the past? Would it be a welcome addition?

**Comment by Daomephsta** [comment]
> The mixin to do this seems trivial, but then your mod has entered Mixin Territory with all the compatibility issues that implies.

It doesn't imply any compatibility issues. The idea that any usage of Mixin inherently risks incompatibilities is common, but utterly false.
