### ISSUE TITLE
ExtendedScreenHandlerFactory is not passed ScreenHandler for context

### ISSUE THREAD

**Issue by Ueaj-Kerman** [FabricMC/fabric#2963]
`ExtendedScreenHandlerFactory` has method `void writeScreenOpeningData(ServerPlayerEntity player, PacketByteBuf buf)`, however this method is not passed the ScreenHandler that is being written. This makes it rather annoying to take data straight from the ScreenHandler and write it on open. As a result the same code can't be used for sync-on-change and sync-on-open.

<img width="884" alt="image" src="https://user-images.githubusercontent.com/28693059/224834662-9f92172b-7107-4515-b7b9-073a59814e51.png">

This can be fixed by either changing the signature of the method or creating a `ContextAwareExtendedScreenHandlerFactory` of sorts to retain compatibility.

**Comment by Technici4n** [comment]
With #3077, the screen handler can be accessed via the passed player object.
