### ISSUE TITLE
Suggestion: built-in obj. model loader.

### ISSUE THREAD

**Issue by starboyceleste** [FabricMC/fabric#2986]
Not sure if this is the right place to put this. I'd like to suggest the addition of a built-in support for obj. models. I'm currently using and writing documentation for morimori's SpecialModelLoader, see here: https://github.com/TeamFelnull/SpecialModelLoader/

Forge includes a loader for the .obj model format: https://docs.minecraftforge.net/en/1.19.x/rendering/modelloaders/

Would love to see something like this built-in to Fabric, thanks!

**Comment by Technici4n** [comment]
This is out of scope for fabric, the libraries already handle it nicely.
