### ISSUE TITLE
API crush in 23w13a_or_b

### ISSUE THREAD

**Issue by JiJiang233** [FabricMC/fabric#2993]
fabric-api-0.76.3+23w13a_or_b.jar in mods folder:
[latest.log](https://github.com/FabricMC/fabric/files/11154403/latest.log)

without fabric-api-0.76.3+23w13a_or_b.jar:
![image](https://user-images.githubusercontent.com/34643810/229959636-3d4cd378-4179-47d6-8704-c92da9c934fa.png)

**Comment by apple502j** [comment]
Make sure you use the latest release.

**Comment by shenjackyuanjie** [comment]
> Make sure you use the latest release.

sorry, but which release is the latest for 23w13a_or_b

**Comment by modmuss50** [comment]
23w13a_or_b was re-released by Mojang, you are either running the re-release version with the old fabric or the other way around.

I would reccomend re-installing fabric to make sure you are running the correct version. You will likely also need to delete the .fabric folder (next to mods)

**Comment by shenjackyuanjie** [comment]
> 23w13a_or_b was re-released by Mojang, you are either running the re-release version with the old fabric or the other way around.
> 
> I would reccomend re-installing fabric to make sure you are running the correct version. You will likely also need to delete the .fabric folder (next to mods)

OH! thanks! (bad mojang

**Comment by shenjackyuanjie** [comment]
> 23w13a_or_b was re-released by Mojang, you are either running the re-release version with the old fabric or the other way around.
> 
> I would reccomend re-installing fabric to make sure you are running the correct version. You will likely also need to delete the .fabric folder (next to mods)

![image](https://user-images.githubusercontent.com/54507071/230445643-d88cde53-e11f-48b0-b95e-f1ef76864e08.png)

wait, this error mean's what? should I reinstall fabric? or use the newer fabric api?
(I tryed with https://github.com/FabricMC/fabric/actions/runs/4583183365 , same result)

**Comment by shenjackyuanjie** [comment]
oh, my PCL2 have some issue on the new version of 23w13a_or_b
thanks!

**Comment by PRO-2684** [comment]
Got the same error with fabric-screen-handler-api today. Using Minecraft `23w13a_or_b` released at `2023/04/01 20:52:18` with fabric `0.14.19` and fabric api `0.76.3+23w13a_or_b`.
