### ISSUE TITLE
Negative space font breaks when using Fabric API

### ISSUE THREAD

**Issue by LukeJS** [FabricMC/fabric#2994]
https://github.com/AmberWat/NegativeSpaceFont

Using this resource pack and running

```
/tellraw @a [{"text": "Start", "color": "blue"},{"translate": "space.-11"},{"text": "End", "color": "red"}]
```

displays

![image](https://user-images.githubusercontent.com/17252963/230056163-6efa6d5b-668a-4852-9f5b-8a2436ca7d32.png)

when using Fabric Loader 0.14.19 and Fabric API 0.77.0+1.19.4

Removing Fabric API (but not Fabric loader) makes the font display correctly

![image](https://user-images.githubusercontent.com/17252963/230056364-34460448-5b0c-4239-b041-b065f11e9650.png)

**Comment by modmuss50** [comment]
Have you got any other mods installed? I cannot reproduce this in a fabric API development env: 
<img width="966" alt="Screenshot 2023-04-05 at 11 45 45" src="https://user-images.githubusercontent.com/4324090/230058755-857d459b-883e-4bae-8412-6f585478af09.png">

A log file might also be helpful.

**Comment by LukeJS** [comment]
Another resource pack was interfering with the translations, apologies for taking your time 🤦

**Comment by modmuss50** [comment]
No worries, glad its working 👍

**Comment by LukeJS** [comment]
There was still a discrepancy between vanilla/Fabric, I'm guessing the lang file load order from different resource packs is different or something, but can resolve this myself 😅

**Comment by Juuxel** [comment]
That sounds like #2943
