### ISSUE TITLE
Fabric api

### ISSUE THREAD

**Issue by kilian12321** [FabricMC/fabric#2996]
Every time I start minecraft with the api I get the error I've looked at everything and I can't figure it out. I also selected the correct versions! it comes every time the error incompatible mod set!
Kilian

![Bildschirmfoto vom 2023-04-05 15-49-00](https://user-images.githubusercontent.com/87136868/230101193-3ac35bab-713b-42cf-b43c-1ab8be581639.png)
![Bildschirmfoto vom 2023-04-05 15-47-45](https://user-images.githubusercontent.com/87136868/230101167-ff0da3cf-9036-4d85-845f-878de7b9e479.png)
![Bildschirmfoto vom 2023-04-05 15-48-28](https://user-images.githubusercontent.com/87136868/230101179-b2a55914-6f88-43e1-bb0d-946e9122a49b.png)

**Comment by NebelNidas** [comment]
Looks like the Fabric API file got corrupted somehow (most likely during download). Re-downloading should fix your issues.

Edit: Also, please don't create issues for support questions like these, the `player-support` channel on Discord or GitHub discussions are better suited for helping you out with these issues

**Comment by kilian12321** [comment]
It also doesn't Work with the redownload.

**Comment by modmuss50** [comment]
This was an old arch linux bug, please update zlib. (Or downgrade it). See: https://bugs.archlinux.org/task/74371
