### ISSUE TITLE
Transfer API's ComposterWrapper insert behavior is inconsistent with vanilla use

### ISSUE THREAD

**Issue by TheRealWormbo** [FabricMC/fabric#3017]
When putting a compostable item into an empty composter by hand or via a hopper, it has a 100% chance to increase the fill level to 1 regardless of the item type. The item specific probabilities are only applied when the composter is not empty.

**Expected behavior:**
When interacting with a composter using Fabric Transfer API, it should behave the same way as it does when interacting with the composter using a vanilla hopper.

**Observed behavior:**
Inserting items into an empty composter via Transfer API has a chance to leave the composter at level 0, which is inconsistent with vanilla behavior.

While I found this issue testing with a 1.19.2 build, the Git history of `ComposterWrapper` suggests this inconsistency is present in all versions since that class was [added in a 1.17 changeset in August 2021](https://github.com/FabricMC/fabric/commit/0d7a4ee070ab3155ea4da1c7cb432172aa0df956#diff-4654d5840c07a9d262cf14d9d985fed81e10b7cc9f7a10c4e36bfdac877c880b).

**Comment by Technici4n** [comment]
Ah, I hadn't noticed that when writing the `ComposterWrapper`. Thank you for the report, I'll propose a fix soon.
