### ISSUE TITLE
Game crashes due to rendering issue

### ISSUE THREAD

**Issue by Randomised1** [FabricMC/fabric#3024]
The error is the following:

The game crashed whilst rendering entity in world
Error: java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because the return value of "net.fabricmc.fabric.api.renderer.v1.RendererAccess.getRenderer()" is null

Game frequently crashes after mining a block
How can i fix this?

**Comment by kapoostaa** [comment]
how i fixed that issue was removing a mod called continuity

**Comment by ro-nan** [comment]
I get this too!
