### ISSUE TITLE
Backport #2755 for 1.19-1.19.2

### ISSUE THREAD

**Issue by DragonOfMath** [FabricMC/fabric#3034]
Many mods not yet updated for 1.19.3+ would benefit from having APIs that are marked client-side only in their versions, as they can actually run server-side as well if the environment annotations weren't present.

See #2755 which does exactly this but only for 1.19.3 and above.

**Comment by Technici4n** [comment]
The whole point of removing the annotations in the source code is that they are added automatically by the build system (Loom) anyway, since Fabric uses split source sets. Backporting that PR would change nothing for end users.

**Comment by apple502j** [comment]
@Technici4n That PR fixed some issues with things *wrongly marked* as client-only. That part needs backporting.

**Comment by Technici4n** [comment]
The only such case is `BoundedIntRule.validate`, which is only called on the client anyway. That environment annotation is likely a relic from the 1.16 era - not worth PRing imo.
