### ISSUE TITLE
FabricBlockLootTableProvider breaks depending on the mapping set

### ISSUE THREAD

**Issue by ChampionAsh5357** [FabricMC/fabric#3069]
This affects all Fabric APIs from Minecraft 1.19.3 onwards.

## A Brief Background

`FabricBlockLootTableProvider` implements `FabricLootTableProvider`. `FabricLootTableProvider` extends a `Consumer` which is used to register the loot table entries to be written to the disk. The consumer itself is implemented within `FabricBlockLootTableProvider#accept` which implements the registration method.

https://github.com/FabricMC/fabric/blob/926dc7fcc3b8096d7c395ee351d23fbe6193839c/fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/FabricBlockLootTableProvider.java#L79-L114

## What is `#accept`?

It would be fine if `#accept` was just the name of the method passed into the `Consumer`. However, it is also the yarn mapping name for `BlockLootTableGenerator#accept`. In Yarn mappings, this is fine as `#accept` would then override `Consumer#accept` and implement perfectly. However, in other mapping sets, such as Mojmaps, the name is `BlockLootSubProvider#generate`. This requires a modder using Mojmaps to implement the `#accept` method from the Consumer and delegate to `BlockLootSubProvider#generate`.

This is an issue since it means that the code is reliant upon the mapping set. You need to add the method in non-Yarn mappings sets and remove the method in Yarn mapping sets, otherwise the call would infinitely recurse.

## Possible Solution

Because of how Fabric implements loot table providers, the main solution would be to change `FabricLootTableProvider` to extend `LootTableGenerator` and call the associated method. This would prevent any disambiguation between mapping sets as the method's name would then change according to which mapping set it was apart of, rather than be static from the `Consumer`.

**Comment by Technici4n** [comment]
See #3070 for a potential fix.
