### ISSUE TITLE
game closes whoever loading up a world

### ISSUE THREAD

**Issue by Nathan22211** [FabricMC/fabric#307]
this shows up as the fatel in the log https://pastebin.com/tYi6Y5q0 

it's happened in 1.14.4 pre 5 with build 1 of that version's fabric loader and fabric API 0.3.0 build 192

**Comment by sindrefag** [comment]
Fabric API is not working for 1.14.4 yet, the fix is on a separate branch and can't be pushed because of a fault with their versioning system I think it was, so you will have to play on 1.14.3 for now

**Comment by modmuss50** [comment]
Update to the 1.14.4-pre5 fabric api that has now been released as an alpha.
