### ISSUE TITLE
Missing model ingame when using multiple blockstate variants

### ISSUE THREAD

**Issue by Patzlyk** [FabricMC/fabric#308]
When i use multiple blockstate variants, i can see the model with texture in inventory, but when i place the block, there is only a purple and black checkerboard.

My blockstate file:

```
 {
   "variants": {
       "facing=east": { "model": "testmod:road_block" },
       "facing=south": { "model": "testmod:road_block", "y": 90 },
       "facing=west": { "model": "testmod:road_block", "y": 180 },
       "facing=north": { "model": "testmod:road_block", "y": 270 }
   }
 }
```

Also, how to make a crafting recipe? I tried putting a minecraft recipe file to `src/main/resources/assets/modid/recipes/` but it did not work.

**Comment by shedaniel** [comment]
Recipes are in the data folder, check how datapacks do them

**Comment by Patzlyk** [comment]
Where exactly should the data folder be? Data packs have it in the main folder, but that doesn't work.

**Comment by sindrefag** [comment]
for the blockstate you need to replace ```testmod:road_block``` with ```testmod:block/road_block```

**Comment by Patzlyk** [comment]
Just tried that and it still doesn't work.

**Comment by grondag** [comment]
It’s unlikely this is a Fabric API issue. Have you tried the support channels in the Fabric Discord.

If you believe it is a Fabric issue, please provide steps/code to reproduce: block state JSON, model JSON, folder structure, block registration code, logs, etc. We can’t do anything but guess with what is given.
