### ISSUE TITLE
Injected getFluidName method for fluids

### ISSUE THREAD

**Issue by Juuxel** [FabricMC/fabric#3114]
Currently, if you only want to provide a name for a fluid that has no block, it's pretty cumbersome and needs you register an additional object like this:

```java
FluidVariantAttributes.register(MY_FLUID, new FluidVariantAttributeHandler() {
    @Override
    public Text getName(FluidVariant variant) {
        return Text.translatable("fluid.my_mod.my_fluid");
    }
});
```
I'm proposing a `FabricFluid` injected interface with these methods:
```java
public interface FabricFluid {
    default Text getFluidName() {
        // the current default in FluidVariantAttributeHandler
        return ((Fluid) this).getDefaultState().getBlockState().getBlock().getName();
    }

    // If this interface is part of the transfer API:
    default Text getFluidName(FluidVariant variant) {
        return getFluidName();
    }
}
```

The default fluid variant attribute handler would then delegate to these methods.

(`getFluidName` so that a fluid class doesn't end up inheriting both this unobfuscated method and `method_5477` - present in many classes such as [`Nameable`](https://github.com/FabricMC/yarn/blob/de6b90b586e5fe8cb814a134cb3bb9a307acd8a6/mappings/net/minecraft/util/Nameable.mapping#L10) - which would cause a remapping conflict)

**Comment by Technici4n** [comment]
I think a better fix is to change the default implementation of `FluidVariantAttributeHandler` to something like this:

```java
	/**
	 * Return the name that should be used for the passed fluid variant.
	 */
	default Text getName(FluidVariant fluidVariant) {
		Block fluidBlock = return fluidVariant.getFluid().getDefaultState().getBlockState().getBlock();

		if (fluidBlock.isAir()) {
			// Some unplaceable fluids use air as their fluid block, use "block." translation key.
			return Text.translatable(Util.createTranslationKey("block", Registries.FLUID.getId(fluidVariant.getFluid())));
.getName();
		} else {
			return fluidBlock.getName();
	}
```

PR welcome of course.
