### ISSUE TITLE
Resource conditions API seem to be broken with loot tables in 1.20

### ISSUE THREAD

**Issue by Hugman76** [FabricMC/fabric#3116]
```json
{
	"type": "minecraft:block",
	"pools": [
		{
			"rolls": 1,
			"entries": [
				{
					"type": "minecraft:item",
					"name": "promenade:carbonite_column"
				}
			],
			"conditions": [
				{
					"condition": "minecraft:survives_explosion"
				}
			]
		}
	],
	"fabric:load_conditions": [
		{
			"condition": "fabric:all_mods_loaded",
			"values": [
				"columns"
			]
		}
	]
}
```

Error: `Expected name to be an item, was unknown string 'promenade:carbonite_column'`
It tries to load that table even if the `columns` mod is absent

**Comment by Daomephsta** [comment]
Have you tried putting `fabric:load_conditions` at the top?  
There's code in the resource conditions module that forces datagen to put it first, so that's evidently important.

**Comment by Hugman76** [comment]
The issue occurs no matter what the order is
Also, IMO the order of objects should never affect how a JSON is parsed
