### ISSUE TITLE
I can't find the version I need

### ISSUE THREAD

**Issue by Straighten-Your-Back** [FabricMC/fabric#312]
Following [these instructions](https://fabricmc.net/wiki/tutorial:install_with_multimc), I installed minecraft, the intermediary mappings, and fabric loader.

However, the part where I download the API is where I'm stuck. Looking at the listings, the only version I can find that says "build.155" is for 1.14.1, and starts with 0.3 and not 0.4. MultiMC has selected "0.4.8-build.155", which doesn't seem to exist on [this page](https://www.curseforge.com/minecraft/mc-mods/fabric-api/files) (or the next page, I didn't not notice the page buttons)

**Comment by swordglowsblue** [comment]
0.4.8+build.155 is the latest version of Fabric Loader. 0.3.0+build.198 is the latest version of the Fabric API. The two are separate projects (run by the same team) and need to be installed separately. Technically the API is optional, but most mods do require it.

**Comment by Straighten-Your-Back** [comment]
Ah, I think you should rewrite the instructions because they don't make that clear.

"and download the correct version for the Minecraft MultiMC instance you just created. " is particularly misleading, it suggests I need to find the same filename. How do I know which version I need without some kind of indicator?

**Comment by swordglowsblue** [comment]
"Step 3: Install the Fabric API" makes it fairly clear in my opinion. To quote:

> If that sounds too complicated just consider the Fabric API as a mod that will be loaded by the Fabric Loader, and almost all Fabric mods depend on it, so this will be the first mod to install.

I can understand how you might miss that if you were just skimming, though.

**Comment by Straighten-Your-Back** [comment]
I already know what an API is.

My question is: **How do I know which one I need to download**?

**Comment by swordglowsblue** [comment]
By simple logic - the most recently released for the correct version of Minecraft. That goes for both the loader and the API.

**Comment by Straighten-Your-Back** [comment]
I picked the most recent version for 1.14.2 without issue, though I might not need it since I'm only using fabric to get optifabric (at least for now...I know I'll add more mods once I've got 1.14 stable)

Thank you.

**Comment by calloatti** [comment]
I edited the tutorial to make it less confusing, but 2 paragraphs down it makes it very clear:

> For example if you created the MultiMC instance for MC 1.14.2, the correct Fabric Api file would be “[1.14.2] Fabric API 0.3.0 build 175” (there may be a newer version of the 1.14.2 Fabric Api after this tutorial was written).
