### ISSUE TITLE
Bump all submodule version numbers

### ISSUE THREAD

**Issue by sargunv** [FabricMC/fabric#315]
There's been some discussion about this in #player-general (just search my name in that channel), but essentially, I believe (but haven't confirmed) fabric-loader is selecting outdated versions of api modules due to them being bundled by outdated mods that otherwise work fine on the latest MC. I believe (but haven't confirmed) this is because there are different versions of the api submodules with the same version number but different commit hash in the version number. If this is true and if every submodule version is bumped by at least a patch number (and this is repeated for every new MC patch like a hypothetical 1.14.5), then this problem should disappear. 

This is causing players with large modlists to complain about crashes, with crashlogs that don't point to the error itself (this has happened a lot since I updated beach-slimes to the latest MC, since registering mobs is affected by the api version discrepancy).

As a secondary issue, the same problem is also happening due to instances like fabric-networking-v0 being loaded alongside fabric-networking (from Crochet). It might be worth special-casing those modids to block the one without v0 if the one with v0 is present.

**Comment by asiekierka** [comment]
See #316 for my take on the first part of the problem.

**Comment by modmuss50** [comment]
This issue has been sorted.
