### ISSUE TITLE
[SCULK SENSOR] Sculk sensors emit too much light

### ISSUE THREAD

**Issue by Lolothepro** [FabricMC/fabric#3153]
## Expected Behavior

![2023-06-28_17 26 25](https://github.com/FabricMC/fabric/assets/68275908/a8dbf577-c8c4-409b-bd83-3909db7abdd3)

## Actual Behavior

![2023-06-28_17 27 16](https://github.com/FabricMC/fabric/assets/68275908/cf9f4d70-6843-493f-8f36-6196bfd3788b)

[Sodium BR](https://github.com/CaffeineMC/sodium-fabric/issues/1852)

**Comment by Technici4n** [comment]
Thanks, we are investigating the issue.
