### ISSUE TITLE
The climate_cold biome tag is missing the Snowy Slopes biome

### ISSUE THREAD

**Issue by Apollounknowndev** [FabricMC/fabric#3160]
You can see it in the file [here](https://github.com/FabricMC/fabric/blob/1.20.1/fabric-convention-tags-v1/src/generated/resources/data/c/tags/worldgen/biome/climate_cold.json).

**Comment by MrBElga** [comment]
a

**Comment by TelepathicGrunt** [comment]
this was fixed in the tag unifying PRs so issue should be resolved now
