### ISSUE TITLE
[fabric-item-groups-v0] inconsistent behaviour when switching inventory pages

### ISSUE THREAD

**Issue by UpcraftLP** [FabricMC/fabric#321]
when switching between itemgroup pages via the page buttons, the game always selects the top-left itemgroup of that page.
There is only one exception to this: Having the `Search` itemgroup selected.

In that case, going to the `previous` (vanilla) page, the search group stays selected.
However, when going to the `next` (modded) page from the vanilla page, it switches back to the top-left itemgroup of that page.

tested on `fabric-item-groups-v0`, version `0.1.0+1e69a0a542`

**Comment by ExtraCrafTX** [comment]
This behaviour also persists with the `Saved Toolbars` and `Survival Inventory` tabs.

I also don't think changing pages should change the selected group at all. For example, if I have decorations selected and I go to the next page, I think decorations should still be selected but I should be able to see the tabs from the next page.

**Comment by UpcraftLP** [comment]
> I also don't think changing pages should change the selected group at all.

well I think it should, but only if the selected tab is not part of the next page.
(i.e. if the group is not inventory, search or hotbars)

**Comment by Technici4n** [comment]
This was entirely re-written since this issue was opened. Please open a new issue if this is still a problem in 1.19.3.
