### ISSUE TITLE
[FAPI 0.86] RegistryLoaderMixin is overwriting Registry Path

### ISSUE THREAD

**Issue by quiqueck** [FabricMC/fabric#3215]
This mixing is changing the path for every, non vanilla Registry. Even if a Registry is not managed  with `DynamicRegistries`:

https://github.com/FabricMC/fabric/blob/e3d1b5f3d89f780b644f6e967963224c2cdef194/fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/mixin/registry/sync/RegistryLoaderMixin.java#L65-L71

The results in registries not getting loaded (quiqueck/BetterEnd#273)

**Comment by quiqueck** [comment]
I am not 100% sure, but I think that `FabricDynamicRegistryProvider` is not using the changed paths to serialise the registry content:

https://github.com/FabricMC/fabric/blob/e3d1b5f3d89f780b644f6e967963224c2cdef194/fabric-data-generation-api-v1/src/main/java/net/fabricmc/fabric/api/datagen/v1/provider/FabricDynamicRegistryProvider.java#L223

I think it is just reading the unchanged Identifier-Path

**Comment by Technici4n** [comment]
Hmmm, the problem here is that some mods were registering dynamic registries in non-API ways, and without prepending the path. We can indeed check if the dynamic registry was registered via FAPI for now.

**Comment by quiqueck** [comment]
First off, I like the general idea of the change, and I was (obviously) not aware of a previous API to add custom, dynamic registries. But did that old API auto prefix the Mod Id, because if it does not, and the Registry was previously manually prefixed with the mod id, it would have two prefixes in the new version...

This is just my personal take on this, but as this change alters the registry paths between versions this is prone to cause soft fails (in our case, the surface rules are no longer loaded). It will also invalidate some data packs that did target our registries.

**Comment by modmuss50** [comment]
I agree, this should only make the change to registries created the API 👍

**Comment by modmuss50** [comment]
I have created a PR to fix this, the current "broken" build is still marked as beta, and I expect to keep it this way.
