### ISSUE TITLE
when i use fabric api 1.20.1 all the text in game turns to OOOOOOOOOOO

### ISSUE THREAD

**Issue by ItsVxcle** [FabricMC/fabric#3236]
i have tried removing all mods but keeping fabric api and the text is still glitch. when i removed fabric api the text was alright again but i want to use it cuz i wanna download some mods
the mods i use are not causing any problems and the fabric api is

**Comment by modmuss50** [comment]
I imagine you have optifine, if so remove it.

**Comment by ItsVxcle** [comment]
@modmuss50 i have optifine on fabric and it works without fabric api and it works fine so i dont think thats the problem

**Comment by modmuss50** [comment]
> @modmuss50 i have optifine on fabric and it works without fabric api and it works fine so i dont think thats the problem

It works without optifine, its on optifine/optifabric to fix.
