### ISSUE TITLE
fabric-models-v0 added, causing game to crash

### ISSUE THREAD

**Issue by znepb** [FabricMC/fabric#3250]
When I created a mod with an attempt to use [CC-Tweaked](https://github.com/cc-tweaked/CC-Tweaked) as a dependency, it caused Fabric to add the `fabric-models-v0` module, even though, to my knowledge, the latest version of CC-Tweaked has moved away from it. Not having the dependency added does not cause the game to refuse to start. I've tried everything I could think of, including clearing Gradle cache system-wide. Fabric seems to add it every time I start the game in development mode. The error does not occur when the mod is not in a development environment. If I could get some pointers to why this is happening, that would be great. Thanks!

**Comment by Technici4n** [comment]
Hmmm, as a workaround you can add `modImplementation "net.fabricmc.fabric-api:fabric-api-deprecated:${project.fabric_version}"` to your `build.gradle` file for the moment.

We will stop removing deprecated modules from the main artifact as it's causing issues, see #3246.
