### ISSUE TITLE
Fabric ModList broadcast

### ISSUE THREAD

**Issue by INotSleep** [FabricMC/fabric#3269]
Hi! I'm creating server on Paper and want to restrict some mods by modid. Theres any information about channel, that client send information about mods, and it datasheet? Thank you

**Comment by modmuss50** [comment]
Fabric does not send the mod list, even if it did it would be trivial for mods (such as the ones you are trying to protect against) to remove themselves.

The client will negotiate the packet channels with a server, this is better documented in 1.20.2 here: https://github.com/FabricMC/fabric/pull/3244
