### ISSUE TITLE
Fabric Furnaces 1.14 Crash

### ISSUE THREAD

**Issue by SquidHCF** [FabricMC/fabric#327]
I have a problem and don't know how to fix the problem so im posting it here to see if someone can help me. So the problem is that everytime i put the Fabric Furnace mod in my mod folder it crashes when i try to load it and i really want to play with Fabric Furnace so i hope someone you can find a solution for me to play with Fabric Furnace instad of removing it from my mod folder. Im on 1.14 btw and here is the crash log. https://pastebin.com/40y8v9gs

**Comment by Boundarybreaker** [comment]
Why not check on the Fabric Furnaces issue page? It should be linked on the CurseForge.

**Comment by SquidHCF** [comment]
Don't worry i fixed it :) i only had to change to a diffrent update of fabric furnace becuase it seemed like the one i used didin't work for me. But thanks anyway
