### ISSUE TITLE
pack.mcmeta functionality is not available

### ISSUE THREAD

**Issue by maityyy** [FabricMC/fabric#3302]
FAPI does not seem to see the custom `pack.mcmeta` in the mod's root. This is a problem since `pack.mcmeta` provides several features that help modders (features, file filtering, overlays, etc.)

For example, this `pack.mcmeta` will make it impossible to get the Netherite Ingot recipe when a player obtains the Netherite Scrap. This works in an empty world data pack, but does not work in Fabric
[pack.mcmeta.zip](https://github.com/FabricMC/fabric/files/12542012/pack.mcmeta.zip)

**Comment by Technici4n** [comment]
Features and filtering are not relevant to mod packs.

**Comment by modmuss50** [comment]
> filtering are not relevant to mod packs.

Would there be a usecase for a mod to filter out some of vanilla's resources? I think this is whats requested here.

**Comment by maityyy** [comment]
> Features and filtering are not relevant to mod packs.

Hm? Well, I disagree about file filtering. I think it is convenient for modders
