### ISSUE TITLE
[Non functional] fabric-resource-conditions-api-v1

### ISSUE THREAD

**Issue by xanthian** [FabricMC/fabric#3322]
Seems that the `fabric:registry_contains` is non functional for loot tables.

Reasoning behind the claim :

When the following is present in loot_table json file 

```       
"condition": "fabric:registry_contains",
"registry": "minecraft:block",
"values": [
"modid:block_name"
```

You get the following error in console :  
`(Fabric Resource Conditions) Can't retrieve current registries. Failing registry_contains resource condition check.` 
this occurs if the block is present or not.
Game loads fine, no further console errors regarding the loot table json, however the loot table does not function (no item drops)

Removing the `fabric:registry_contains` does allow the loot to drop, but for the niche case i'm using it for (to stop console spam when another mod's block is not present - i'm already checking the mod is present) 
if the block is not present you get the console error as expected 
``` Couldn't parse element loot_tables:mymodid:blocks/missing_block_name ```

fabric_version=0.88.1+1.20.1
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.14.22
'fabric-loom' version '1.3-SNAPSHOT'

**Comment by xanthian** [comment]
In testing further (and trying to get my mod to function) it seems the tags_populated also doesnt work :(
`Can't retrieve deserialized tags. Failing tags_populated resource condition check.`

**Comment by apple502j** [comment]
These two are somewhat different, in what is causing the issue:

- Registry: likely thread issue.
- Tags: This is trickier because when the loot table conditions are evaluated, tags aren't loaded yet. See #3117

**Comment by xanthian** [comment]
Someone mentioned thread issue, although I have no clue what that means 👍🏼 
Does it mean its not likely to be resolved / any time soon?

**Comment by xanthian** [comment]
Any movement on this at all? 🤞

**Comment by xanthian** [comment]
This works perfectly, thankyou 😍
