### ISSUE TITLE
Crash on new version 0.89.0+1.20.1 caused by Indium

### ISSUE THREAD

**Issue by icynstant** [FabricMC/fabric#3325]
When i log into my world MC is crashing, but on previous version 0.88.1+1.20.1 everything is good.

Minecraft crash ended!
Minecraft ran into a problem and crashed.
The following modifications have been identified as possible causes:
Continuity, Fabric Renderer API (01), Indium, Sodium.

[crash-2023-09-19_12.09.09-client.txt](https://github.com/FabricMC/fabric/files/12658004/crash-2023-09-19_12.09.09-client.txt)

Links that NotEnoughCrashes gave me:
https://crashy.net/dde46eae-d2bc-4de6-a4d8-cd454d2a2900
https://bytebin.lucko.me/2q5sS1N96U

My first time uploading crash, did I do it correctly?

**Comment by apple502j** [comment]
Yes, the latest update is one of the causes of the bug. However, the fix should be done inside the Indium mod which needs to be updated to support the latest Rendering API.

**Comment by apple502j** [comment]
For now, please use FAPI 0.88.1.

**Comment by modmuss50** [comment]
Hi, thanks for the bug report, Indium needs to be updated to support some recent changes. See: https://github.com/comp500/Indium/issues/232

I have marked this version as a beta to allow a little bit of time for Indium to update. We technically didnt break the API, this was just a bit unluckly. I dont think there is anything else for us to do.

**Comment by icynstant** [comment]
You can download new version of Indium that works with FAPI 0.89.0 on GitHub
