### ISSUE TITLE
Persistent state types should support null data fixer types

### ISSUE THREAD

**Issue by haykam821** [FabricMC/fabric#3327]
As of Minecraft 1.20.2, persistent state types must be constructed with a data fixer type. If the data fixer type is `null`, then the following exception will be logged when loading the persistent state:

```
java.lang.NullPointerException: Cannot invoke "net.minecraft.datafixer.DataFixTypes.update(com.mojang.datafixers.DataFixer, net.minecraft.nbt.NbtCompound, int, int)" because "dataFixTypes" is null
```

**Comment by Dev0Louis** [comment]
Adding to that it would only be single change, since a method from DatafixerType is only once called afaik.
