### ISSUE TITLE
Water rendering aginst glass is diffrent from vanilla.

### ISSUE THREAD

**Issue by modmuss50** [FabricMC/fabric#333]
![](https://ss.modmuss50.me/chrome_2019-08-04_15-49-05.png)

Vanilla on the left, fabric + fabric-api on the right.

Edit: Not sure if its indigo, or the fluid rendering api.

**Comment by grondag** [comment]
This appears to be in the `fabric-rendering-fluids` module which is distinct from Indigo/rendering API.  Will work on a fix but will be a separate PR from the open Indigo bugs.
