### ISSUE TITLE
Game refuses to launch with Fabric API installed 1.20.2 on Linux

### ISSUE THREAD

**Issue by WindClan** [FabricMC/fabric#3333]
Ive tried with no mods, vanilla, mods that dont need vulkan API, and just Fabric API. Anytime fabric api is installed the game refuses to boot and just crashes with the same error every time, no matter what other mods are installed.

Log with just Fabric API:
https://mclo.gs/2O3xK4t

**Comment by intact** [comment]
Do you have realtime-privileges package installed?

**Comment by WindClan** [comment]
> realtime-privileges

No but retesting with the package installed results in the same thing so I'd say its unrelated

**Comment by intact** [comment]
[Minecraft ALSOFT Failed to set real-time priority for thread: Operation not permitted](https://old.reddit.com/r/linux_gaming/comments/wsxgd1/minecraft_alsoft_failed_to_set_realtime_priority/#thing_t1_inajcl0)

**Comment by WindClan** [comment]
> [Minecraft ALSOFT Failed to set real-time priority for thread: Operation not permitted](https://old.reddit.com/r/linux_gaming/comments/wsxgd1/minecraft_alsoft_failed_to_set_realtime_priority/#thing_t1_inajcl0)

Issue occurs only with Fabric API while this warning appears on vanilla too
Log without fabric API enabled: https://mclo.gs/MSIEnJ5

**Comment by apple502j** [comment]
@throughthefog The Fabric API Big Jar is actually a bundle of multiple jar files for each module (see `META-INF/jars`). Could you remove the big jar, extract those jars from the file and put all of them **except `fabric-sound-api-v1-VERSION.jar`**, on the mods folder and try to load it?

**Comment by WindClan** [comment]
> @throughthefog The Fabric API Big Jar is actually a bundle of multiple jar files for each module (see `META-INF/jars`). Could you remove the big jar, extract those jars from the file and put all of them **except `fabric-sound-api-v1-VERSION.jar`**, on the mods folder and try to load it?

Removing fabric-sound-api-v1-0.89.2.jar seemed to fix the issue

Log without sound API: https://mclo.gs/7L4m6HM
Log with sound API: https://mclo.gs/YsWcuzX

**Comment by modmuss50** [comment]
What OS and version are you running? I could maybe try in a VM to reproduce it, I have a feeling I'm going unsuccessfull. I have no clue how the sound-api could cause a native crash, its a really simple module. 🤔

**Comment by WindClan** [comment]
> What OS and version are you running? I could maybe try in a VM to reproduce it, I have a feeling I'm going unsuccessfull. I have no clue how the sound-api could cause a native crash, its a really simple module. 🤔

Im running Arch Linux and using pipewire for audio (with pipewire-pulse, pipewire-jack, etc.)
if it matters im using KDE plasma and using `jre17-openjdk-17.0.8.1.u1-1` java package

**Comment by Shnupbups** [comment]
Could you maybe share the `hs_err_pid4885.log` file? The log you posted says that error report has more information, it should just be in the `.minecraft` folder of your instance.

**Comment by WindClan** [comment]
> Could you maybe share the `hs_err_pid4885.log` file? The log you posted says that error report has more information, it should just be in the `.minecraft` folder of your instance.

[hs_err_pid4885.log](https://github.com/FabricMC/fabric/files/12709214/hs_err_pid4885.log)

(ignore the instance name, i upgraded it to 1.20.2 and forgot to change the name)

**Comment by modmuss50** [comment]
Im a little lost on this issue, I fail to see how the sound-api could cause this. On its own with no other mod using it it makes no affective changes. Clearly you have logs with it working without the sound api though...

If anyone has any ideas do let me know.

**Comment by modmuss50** [comment]
Just wondering if this might be a launcher problem, maybe using the worng natives? Could you try and see if this also happens when you use the offical Minecraft launcher?

**Comment by WindClan** [comment]
Alright I don't know *what* caused it but remaking the instance fixed it? Even downgrading LWJGL which I noticed was a newer version didnt recreate the bug

**Comment by modmuss50** [comment]
It seemed to be using a snapshot build of the natives, I found this `/tmp/lwjgluser/3.3.1-SNAPSHOT/libopenal.so` in the hs_err file. I cannot see any way this could be caused by fabric's api.
