### ISSUE TITLE
Fabric API Executable will not open

### ISSUE THREAD

**Issue by Skylieden** [FabricMC/fabric#3334]
I have tried .1 and .2 of .20 and will not launch. I have attempted to reboot the PC but with no effect other than the same issue will persist. All steps have been followed for AXIOM as I have requested support for them too, but with the API executable not working, I cannot go any further.

**Comment by apple502j** [comment]
Fabric API jar file is not meant to be executed on its own. Instead the file must be placed within the `mods` directory of your Minecraft installation. See https://fabricmc.net/wiki/player:tutorials:install_mcl:windows
