### ISSUE TITLE
Weird crash with Java 21

### ISSUE THREAD

**Issue by Abalieno** [FabricMC/fabric#3338]
I'm not sure if it's related to Java version, but since it's the first time I'm seeing this and I've made some changes recently, it's my primary suspicion.

I'm running official oracle GraalVM Java 21 released a few days ago, with 1.19.2.

Using these flags (I now use ZGC, but these caused the crashes):
-XX:+EnableJVMCI -XX:+UseJVMCICompiler -XX:+EagerJVMCI -Djvmci.Compiler=graal -Dfml.readTimeout=120 -Dgraal.ShowConfiguration=info -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -Dsun.rmi.dgc.server.gcInterval=900000 -XX:+DisableExplicitGC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=51 -XX:G1HeapRegionSize=32M

I get occasional crashes about different stuff. One was this, as soon I made a world and was waiting to get in:

```java.lang.SecurityException: SHA-256 digest error for net/fabricmc/fabric/api/event/server/ServerStartCallback.class```

The second time it was this

```java.lang.SecurityException: SHA-256 digest error for net/fabricmc/fabric/api/block/BlockAttackInteractionAware.class```

**Comment by modmuss50** [comment]
Java 21 should work fine, what operating system are you using? I vageully recall seeing this issue before, I forget what the cause was though.

**Comment by Abalieno** [comment]
Windows 10. Never had a similar problem up to this point.

**Comment by modmuss50** [comment]
I assume you have tried redownloading FabricAPI? This could possibly be caused by a corrupted jar file.

**Comment by Abalieno** [comment]
The jar itself in mod folder? The crc seems to be fine...
