### ISSUE TITLE
no cyrillic symbol

### ISSUE THREAD

**Issue by f1xc0d3** [FabricMC/fabric#3351]
Instead of symbols there are just squares. This happens after adding fabric api to the folder. Please fix for 1.20.1

**Comment by modmuss50** [comment]
There is a common issue where Optifine causes this, please try without optifine or reach out for support in one of the places detailed above.

**Comment by f1xc0d3** [comment]
It’s quite possible, I don’t rule out the fact that the problem may be in Optifine, but I installed fabric-api-0.83.1+1.20.1 and it helped me
