### ISSUE TITLE
Request : Get damage that would be done from a LivingEntity to another LivingEntity using a specific ItemStack

### ISSUE THREAD

**Issue by NatoBoram** [FabricMC/fabric#337]
I tried to extract the damage formula used by `PlayerEntity.attack()`, but honestly, it's bad.

This is a request to obtain a build-in function inside Fabric API to be able to calculate the damage that an `ItemStack` would do to a `LivingEntity` when used by another `LivingEntity`, taking account all modifiers, enchantments, effects, and armours.

**Comment by i509VCB** [comment]
On a case of feasibility, this could be quite challenging since entities could override the damage process themselves, which would make a universal injection into a LivingEntity near impossible in most cases.

**Comment by NatoBoram** [comment]
Yeah, that's precisely why I needed some kind of API. I was trying to get the most effective item in the inventory against the clicked mob, but I realized that formulas were hard-coded into the function that actually removed the `LivingEntity`'s health then scattered some more with enchanting stuff. [r/ProgrammingHorror](https://www.reddit.com/r/ProgrammingHorror) stuff, honestly.

**Comment by i509VCB** [comment]
One idea I thought of is possibly creating a dummy entity with all the same attributes and properties and applying the damage to the dummy to calculate. Though it's definitely a hack and probably a bad way to approach it.

**Comment by i509VCB** [comment]
Closing since this is currently unfeasible.

**Comment by NatoBoram** [comment]
In case anyone was crazy enough to take a shot at this:

https://github.com/NatoBoram/switcheroo/blob/ea465034429401c0586b3cf05b9a6c9ef5b8ea88/src/main/java/com/natoboram/switcheroo/ItemStackUtil.java#L225-L298
