### ISSUE TITLE
Wrong Water Texture on the sides of Ice

### ISSUE THREAD

**Issue by Joshua171** [FabricMC/fabric#338]
Much like the previous issue of the flowing water texture on Glass the issue still effects the sides of regular Ice 
![image](https://user-images.githubusercontent.com/12470717/62749910-95f6ef00-baa1-11e9-8cf2-3b61daa3ac0f.png)

**Comment by i509VCB** [comment]
Does this issue still occur?

**Comment by uiytt** [comment]
In .16.2, with fabric Loader 0.9.2+build.206 and fabric-api 0.19.0+build.398-1.16.
I fail to see any difference. 
Without fabric : 
![Without fabric](https://i.ibb.co/vmQPx1h/2020-08-27-00-19-14.png) 
With fabric 
![With fabric](https://i.ibb.co/bvKRD35/2020-08-27-00-22-46.png)

**Comment by grondag** [comment]
Should this not be closed?  Per images posted recently, looks same.

**Comment by uiytt** [comment]
I think it should be closed indeed

**Comment by i509VCB** [comment]
Closing since testing shows that everything looks like intended and no further feedback has been brought up.
