### ISSUE TITLE
ClientLoginNetworkAddon does not handle unsuccessful query responses 

### ISSUE THREAD

**Issue by masmc05** [FabricMC/fabric#3384]
https://github.com/FabricMC/fabric/blob/1fbc78fabb035f7902f21f9f1f34c13ad4d02aff/fabric-networking-api-v1/src/client/java/net/fabricmc/fabric/impl/networking/client/ClientLoginNetworkAddon.java#L87-L89

As we can see here, even though the listener correctly states that the buffer can be null, it doesn't handle that, resulting in NPE on serialization

Maybe it should have been like that?
```java
ServerboundCustomQueryAnswerPacket packet = new ServerboundCustomQueryAnswerPacket(queryId, result == null ? null : new PacketByteBufLoginQueryResponse(result));
```

**Comment by modmuss50** [comment]
Just to confirm are you using Minecraft 1.20.2?

**Comment by masmc05** [comment]
yes

**Comment by modmuss50** [comment]
Out of intrest whats your usecase for using the login networking APIs? In 1.20.2 in most cases the configuration phase should be a tottal replacement for the login phase.

**Comment by masmc05** [comment]
For several reasons from the past we add an additional security level for top admins, we'll feel safer that way

**Comment by modmuss50** [comment]
I would highly reccomend looking into doing this during the configuration phase, its the perfect place to send addional data such as this.

**Comment by apple502j** [comment]
No, this logic should be kept in the login phase.

**Comment by liach** [comment]
> I would highly reccomend looking into doing this during the configuration phase, its the perfect place to send addional data such as this.

The login query request is guaranteed to receive a response from a vanilla client. In comparison, detecting whether a packet is understood with ping and pong to and attaching pending authentication info onto server-side client objects are more error-prone and is more invasive. And the login network handler has a hold of the vanilla authentication information that modders wish to access.

**Comment by modmuss50** [comment]
> detecting whether a packet is understood with ping and pong to and attaching pending authentication info onto server-side client objects are more error-prone and is more invasive.

This is handled by Fabric API, if its error-prone I need to know about it ASAP as reg sync and other critical parts of fabric API wont be working as expected.

**Comment by apple502j** [comment]
The problem here is not that configuration networking is doomed (it isn't), it is that for this specific use (security check) you don't want to even proceed to configuration in the first place.
