### ISSUE TITLE
[fabric-screen-api-v1] The current screen (net.minecraft.class_3873) has not been correctly initialised, please send this crash log to the mod author. This is usually caused by calling setScreen on the wrong thread.

### ISSUE THREAD

**Issue by gamelamp** [FabricMC/fabric#3390]
This is the full crashlog. Why is the game crashing? I'm currently playing on my Steam Deck, and I've never had this issue before on this mudpack (I've made it myself) but I added a backpack mod, and once I equip said backpack and open/close it, then go to another storage GUI, the game always crashes. I tried several different backpack mods, but the same issue persist

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2023-10-24 15:33:57
Description: Rendering screen

java.lang.IllegalStateException: [fabric-screen-api-v1] The current screen (net.minecraft.class_3873) has not been correctly initialised, please send this crash log to the mod author. This is usually caused by calling setScreen on the wrong thread.
	at net.minecraft.class_437.ensureEventsAreInitialized(class_437.java:5316)
	at net.minecraft.class_437.fabric_getBeforeRenderEvent(class_437.java:5339)
	at net.fabricmc.fabric.api.client.screen.v1.ScreenEvents.beforeRender(ScreenEvents.java:126)
	at net.minecraft.class_757.handler$cim000$fabric-screen-api-v1$onBeforeRenderScreen(class_757.java:6638)
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_437.ensureEventsAreInitialized(class_437.java:5316)
	at net.minecraft.class_437.fabric_getBeforeRenderEvent(class_437.java:5339)
	at net.fabricmc.fabric.api.client.screen.v1.ScreenEvents.beforeRender(ScreenEvents.java:126)
	at net.minecraft.class_757.handler$cim000$fabric-screen-api-v1$onBeforeRenderScreen(class_757.java:6638)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_3873
	Mouse location: Scaled: (-16, -16). Absolute: (-50.000000, -50.000000)
	Screen size: Scaled: (427, 267). Absolute: (1280, 800). Scale factor of 3.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

-- Affected level --
Details:
	All players: 1 total; [class_746['MRAMNESIA8'/133, l='ClientLevel', x=-393.11, y=63.00, z=-288.98]]
	Chunk stats: 1024, 626
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,108,0), Section: (at 0,12,0 in 0,6,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 681868 game time, 889089 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:821)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, Moonlight Mods Dynamic Assets, betterbeds:fancybeds, file/Cobblemon Interface v0.8.zip, file/Cobblemon Tooltips v0.1.zip, betterbeds:connectedbeds, betterbeds:fancyconnectedbeds, file/Domix's Cobblemon GUI v0.2.zip, file/emissive-cobblemon-ores-1.0.zip, file/GeoFont-MC-2-v1.1.zip

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (amd64) version 6.1.52-valve3-1-neptune-61
	Java Version: 17.0.8.1, Flathub
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Flathub
	Memory: 3170400688 bytes (3023 MiB) / 5200936960 bytes (4960 MiB) up to 8673820672 bytes (8272 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Custom APU 0405
	Identifier: AuthenticAMD Family 23 Model 144 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: VanGogh [AMD Custom GPU 0405]
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MB): 258.00
	Graphics card #0 deviceId: 0x163f
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 23791.21
	Virtual memory used (MB): 10529.14
	Swap memory total (MB): 16384.00
	Swap memory used (MB): 25.50
	JVM Flags: 2 total; -Xms4092m -Xmx8268m
	Fabric Mods: 
		adorn: Adorn 5.0.0+1.20.1
		ambientsounds: AmbientSounds 5.2.24
		appleskin: AppleSkin 2.5.1+mc1.20
		architectury: Architectury 9.1.12
		athena: Athena 3.1.1
		attributefix: AttributeFix 21.0.2
		balm-fabric: Balm 7.1.4
		betterbeds: Better Beds 1.3.0
		bookshelf: Bookshelf 20.1.6
		bountiful: Bountiful 6.0.3+1.20.1
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.11.0
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.11.0
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.11.0
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.11.0
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.11.0
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.11.0
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.11.0
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.11.0
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.11.0
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.11.0
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.11.0
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.11.0
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.11.0
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.11.0
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.11.0
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0+alpha.11.0
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.11.0
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.11.0
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.0
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.11.0
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.0
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		cardinal-components: Cardinal Components API 5.2.2
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-block: Cardinal Components API (blocks) 5.2.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
			cardinal-components-item: Cardinal Components API (items) 5.2.2
			cardinal-components-level: Cardinal Components API (world saves) 5.2.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.2.2
			cardinal-components-world: Cardinal Components API (worlds) 5.2.2
		cavedust: Cave Dust 1.4.1
		cherishedworlds: Cherished Worlds 6.1.2+1.20.1
		chipped: Chipped 3.0.1
		citresewn: CIT Resewn 1.1.3+1.20
			citresewn-defaults: CIT Resewn: Defaults 1.1.3+1.20
		cleardespawn: Clear Despawn 1.1.13
		cloth-config: Cloth Config v11 11.1.106
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 12.0.0.3
		cobbledex: CobbleDex 1.0.0
		cobblefossil: CobbleFossil - A Cobblemon Fossil Addon Mod 0.0.6
		cobblemon: Cobblemon 1.4.0+1.20.1
		cobblemonintegrations: Cobblemon Integrations 1.0.1
		comforts: Comforts 6.3.4+1.20.1
			spectrelib: SpectreLib 0.13.14+1.20.1
		continuity: Continuity 3.0.0-beta.4+1.20.1
		controlify: Controlify 1.7.0-beta.1+1.20
			dev_isxander_libsdl4j: libsdl4j 2.28.2-11
			org_hid4java_hid4java: hid4java 0.7.0
			org_quiltmc_quilt-json5: quilt-json5 1.0.3
		craftingtweaks: Crafting Tweaks 18.2.1
		creativecore: CreativeCore 2.11.7
			net_minecraftforge_eventbus: eventbus 6.0.3
		ctov: ChoiceTheorem's Overhauled Village 3.3.5b
		cull-less-leaves: Cull Less Leaves 1.3.0
		dashloader: DashLoader 5.0.0-beta.2+1.20.0
			com_github_luben_zstd-jni: zstd-jni 1.5.2-2
			dev_notalpha_taski: Taski 2.1.0
			dev_quantumfusion_hyphen: Hyphen 0.4.0-rc.3
		debugify: Debugify 1.20.1+2.0
		detailab: Detail Armor Bar 2.6.3+1.20.1-fabric
		distinguishedpotions: Distinguished Potions 8.0.1
		dynamic_fps: Dynamic FPS 3.2.1
		dynamiccrosshair: Dynamic Crosshair 7.3+1.20
			yaclx: YetAnotherConfigLibExtensions 1.6+1.20
		easyanvils: Easy Anvils 8.0.1
		easymagic: Easy Magic 8.0.1
		eatinganimationid: Eating Animation 1.9.4+1.20
		emi: EMI 1.0.23+1.20.1+fabric
		emi_loot: EMI Loot 0.6.5+1.20.1
		emiffect: EMIffect 1.1.1+mc1.20.1
		emitrades: EMI Trades 1.2.0+mc1.20.1
			org_quiltmc_parsers_json: json 0.2.1
		enchdesc: EnchantmentDescriptions 17.0.8
		enhancedblockentities: Enhanced Block Entities 0.9+1.20
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.7
			spruceui: SpruceUI 5.0.0+1.20
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20.1
		exordium: Exordium 1.2.1-mc1.20.1
		fabric-api: Fabric API 0.90.4+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.12+215bbe9677
			fabric-block-api-v1: Fabric Block API (v1) 1.0.10+92a0d36777
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+92a0d36777
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.10+57aed33f77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.2+d7b148e077
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.11+d7b148e077
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.0+96dfa95977
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.44+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.8+d7b148e077
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.2+4ee0bc6077
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.0+39a511ba77
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.0+39a511ba77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.36+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.6+d7b148e077
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.1+195226a777
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabric-language-kotlin: Fabric Language Kotlin 1.10.10+kotlin.1.9.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.22.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.0
		fabricloader: Fabric Loader 0.14.23
		fallingleaves: Falling Leaves 1.15.4
		fallingtree: FallingTree 4.3.0
		ferritecore: FerriteCore 6.0.1
		forgeconfigapiport: Forge Config API Port 8.0.0
		fwaystones: Fabric Waystones 3.1.3+mc1.20
		geckolib: Geckolib 4.2.3
			com_eliotlash_mclib_mclib: mclib 20
		glore: Glowing ores 1.0.0
		handcrafted: Handcrafted 3.0.3
		hangglider: Hang Glider 8.0.1
		held-item-info: Held Item Info 1.5.0
		highlight: Highlight 2.0.1
		highlighter: Highlighter 1.1.6
		iceberg: Iceberg 1.1.15
		immediatelyfast: ImmediatelyFast 1.2.6+1.20.2
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-rc.5
			net_lenni0451_reflect: Reflect 1.2.4
		indium: Indium 1.0.27+mc1.20.1
		iris: Iris 1.6.10
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		jade: Jade 11.6.2
		jamlib: JamLib 0.6.1+1.20.x
		java: OpenJDK 64-Bit Server VM 17
		kambrik: Kambrik 6.1.1+1.20.1
		krypton: Krypton 0.2.3
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		lambdynlights: LambDynamicLights 2.3.2+1.20.1
			pride: Pride Lib 1.2.0+1.19.4
		lazydfu: LazyDFU 0.1.3
		legendarytooltips: Legendary Tooltips 1.4.4
		lithium: Lithium 0.11.2
		logcleaner: Log Cleaner 1.0.0
		make_bubbles_pop: Make Bubbles Pop Mod 0.2.0-fabric
		map_atlases: Map Atlases 2.6.0
		memoryleakfix: Memory Leak Fix 1.1.2
		merchantmarkers: Merchant Markers 1.3.1
		midnightlib: MidnightLib 1.4.1
		minecraft: Minecraft 1.20.1
		mod-loading-screen: Mod Loading Screen 1.0.4
			com_formdev_flatlaf: flatlaf 3.0
		modelfix: Model Gap Fix 1.14
		modernfix: ModernFix 5.8.1+mc1.20.1
		modmenu: Mod Menu 7.2.2
		moonlight: Moonlight 1.20-2.8.51
		moreculling: More Culling 1.20.1-0.19.0
			conditional-mixin: conditional mixin 0.3.2
		mousetweaks: Mouse Tweaks 2.25
		mousewheelie: Mouse Wheelie 1.13.0+mc1.20.1
			amecsapi: Amecs API 1.5.1+mc1.20-pre1
			coat: Coat 1.0.0-beta.20+mc1.20-pre1
			tweed4_annotated: tweed4_annotated 1.3.1+mc1.20-pre1
			tweed4_base: tweed4_base 1.7.1+mc1.20-pre1
			tweed4_data: tweed4_data 1.2.1+mc1.20-pre1
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc1.20-pre1
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.3+mc1.20-pre1
			tweed4_tailor_lang_json_descriptions: tweed4_tailor_lang_json_descriptions 1.1.0+mc1.20-pre1
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.4+mc1.20-pre1
		owo: oωo 0.11.2+1.20
			blue_endless_jankson: jankson 1.2.2
		packedup: Packed Up 1.0.30
		pickupnotifications: Pickup Notifications 1.5.1
		piercingpaxels: piercingpaxels 1.0.12
		polymorph: Polymorph 0.49.1+1.20.1
		presencefootsteps: Presence Footsteps 1.9.0
			kirin: Kirin UI 1.15.0
		prism: Prism 1.0.5
		puzzleslib: Puzzles Lib 8.0.24
		raised: Raised 3.1.0
		reeses-sodium-options: Reese's Sodium Options 1.6.5+mc1.20.1-build.95
		repurposed_structures: Repurposed Structures 7.1.9+1.20.1-fabric
		resourcefullib: Resourceful Lib 2.1.13
			com_teamresourceful_bytecodecs: bytecodecs 1.0.2
			com_teamresourceful_yabn: yabn 1.0.3
		sodium: Sodium 0.5.3
		sodium-extra: Sodium Extra 0.5.1+mc1.20.1-build.112
			caffeineconfig: CaffeineConfig 1.3.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		starlight: Starlight 1.1.2+fabric.dbc156f
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8+a
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.15
		supplementaries: Supplementaries 1.20-2.6.16
		toastkiller: The Open Sauce Toast Killer 1.0
		toolstats: ToolStats 16.0.4
		tooltipfix: ToolTip Fix 1.1.1-1.20
		trinkets: Trinkets 3.7.1
		utilitybelt: Utility Belt 1.3.5+1.20.x
			tutorial-lib: Tutorial Lib 1.1.2+1.20.x
		visuality: Visuality 0.7.1+1.20
		visualworkbench: Visual Workbench 8.0.0
		waterdripsound: Drip Sounds 1.19-0.3.2
		wwoo: William Wythers' Overhauled Overworld 2.0.0
		yet_another_config_lib_v3: YetAnotherConfigLib 3.2.1+1.20
			com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT
			org_quiltmc_parsers_gson: gson 0.2.1
		yosbr: YOSBR 0.1.2
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	Launched Version: 1.20.1
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: AMD Custom GPU 0405 (vangogh, LLVM 16.0.6, DRM 3.54, 6.1.52-valve3-1-neptune-61) GL version 4.6 (Core Profile) Mesa 23.2.1 (git-49a47f187e), AMD
	Window size: 1280x800
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric, Moonlight Mods Dynamic Assets, betterbeds:fancybeds (incompatible), file/Cobblemon Interface v0.8.zip, file/Cobblemon Tooltips v0.1.zip (incompatible), betterbeds:connectedbeds (incompatible), betterbeds:fancyconnectedbeds (incompatible), file/Domix's Cobblemon GUI v0.2.zip (incompatible), file/emissive-cobblemon-ores-1.0.zip (incompatible), file/GeoFont-MC-2-v1.1.zip
	Current Language: en_us
	CPU: 8x AMD Custom APU 0405
	Server Running: true
	Player Count: 1 / 8; [class_3222['MRAMNESIA8'/133, l='ServerLevel[cobble]', x=-393.11, y=63.00, z=-288.98]]
	Data Packs: vanilla, fabric, Moonlight Mods Dynamic Assets, Supplementaries Generated Pack, file/CobblemonLoot-v1.1.0.zip, file/Fortune-able Evolution Stones 1.0.zip (incompatible)
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable

**Comment by apple502j** [comment]
As noted in the error, please report it to the backpack mod author, not us.
