### ISSUE TITLE
IO.NETTY.HANDLER.CODEC.DECODEREXCEPTION WITH FOLIA 1.20.1

### ISSUE THREAD

**Issue by mddewittjr** [FabricMC/fabric#3402]
Today I decided to add a 1.20.1 instance in multimc.  I have added the fabric loader 0.14.24 and downloaded the API 0.90.7+1.20.1 to the instance, it loads up just fine, then when I connect to my folia server, I get this error:

Internal Exception: io.netty.handler.codec.DecoderException: java.lang.RuntimeException: Attempted to register ID ResourceKey[Minecraft:damage_type / Minecraft:outside_order] at different raw IDs (30,44)! If you are trying to override an item, use .set(), not .register()!

The same issue though occurred on 1.20. 
  
The same folia server is running on 1.20.1.
I have been running a 1.19.3 instance for the last 3 months or so and have had zero issues using fabric API (client side) when logging into the Minecraft server.  
Fabric API 0.76.0+1.19.3
Fabric Loader: 0.14.21

So what has changed between 1.19.3 and 1.20 to get this error?

**Comment by Linguardium** [comment]
I would recommend heading to the discord or opening a discussion so that the actual issue can be isolated to either a flaw in your server or a flaw in your mods
