### ISSUE TITLE
Something in Fabric causes seams in flowing water appear if shader pack touches how water acts (Iris, Optifabric) - non-fabric instances are not affected

### ISSUE THREAD

**Issue by Nyekomimi** [FabricMC/fabric#3410]
Hello

The issue depends from shader pack to shader pack, and there are some differences in behavior between Iris and Optifabric. But in both cases the issue has core specific characteristics.

Example under Sildurs Enhanced Default (one of packs in which it's more pronounced)
Iris: https://cdn.discordapp.com/attachments/237199950235041794/1171447468035149974/image.png?ex=655cb678&is=654a4178&hm=181a71024f1d886a9c92046d093b1900c15833d137cba1e0ad1be794599fb01c&
OptiFabric: https://cdn.discordapp.com/attachments/237199950235041794/1171445751654666271/image.png?ex=655cb4df&is=654a3fdf&hm=f8e77d0e677b5619fe551fe29047410fa9c6b679ab5e7a6b7217cf1e2d63e978&

In worst cases (like here) the seam widens to pop up and down. In best cases, the seam doesn't widen as the water above moves, but there still is clear seam visible: https://cdn.discordapp.com/attachments/782035818453401642/1171471442995593226/image.png?ex=655ccccc&is=654a57cc&hm=8b8b7fb9ad7989fdf3869a70bb04f683000e6041e684a521e4f9a3622d4729e2&

I am submitting this issue because it was known bug in Iris in older versions (back then people would usually tell you to just use Optifine). However, the behavior is new to OptiFabric (wasn't like this in 1.16 and 1.18).

This suggests that the issue is with the Fabric itself (since the OptiFabric test was done on "clean" install of Optifine, OptiFabric, Fabric 0.8.5 + minimap mods I need fabric for). The Iris test was done on newest fabric version i could get. 

I really hope that you could fix it, because right now only reason to use Optifine over Fabric-native alternatives is the seamless water in shaders. If you resolved this bug it'd mean people could switch to more reliable software...

**Comment by apple502j** [comment]
@Nyekomimi Just to confirm, this only occurs with Fabric API installed right?

**Comment by Nyekomimi** [comment]
That is correct! This is why I wrote the title way I did.

A regular Optifine instance does not have the problems with shaders. An OptiFabric instance does have the problem occur.

I dunno if it helps or not, but I also tried an Iris build based on "Quilt" and it did have same seam issue. So seems like the issue was forked over.
