### ISSUE TITLE
Minecraft crashes with FabricAPI

### ISSUE THREAD

**Issue by MikePeregrine** [FabricMC/fabric#342]
Minecraft crashes every time I launch Fabric with FabricAPI. I've tried both Minecraft and MultiMC.

Fabric: 0.4.6+build.143, 0.4.8+build159
FabricAPI: 0.3.1+build.208

Logs:
https://pastebin.com/wE9s7gr6

**Comment by modmuss50** [comment]
Possibly a fabric loader issue. https://github.com/FabricMC/fabric-loader/issues/138
