### ISSUE TITLE
Registry sync calls `getLootTableId` on every registered block for seemingly no reason

### ISSUE THREAD

**Issue by Technici4n** [FabricMC/fabric#3422]
See the following:
https://github.com/FabricMC/fabric/blob/65c120eded0fb3d65c10cd2a616e38e22746963d/fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/impl/registry/sync/trackers/vanilla/BlockInitTracker.java#L48

No idea why this exists and what that actually does.

Found while working on the NeoForge registry rework, NeoForge also has this but it's unclear why so it will be removed...

**Comment by Juuxel** [comment]
It might be something vanilla does/did? From an ancient version of reg sync:
https://github.com/FabricMC/fabric/blob/eff4f58df6fc9f121939359e54fbf2dc4acc11d4/fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/impl/registry/vanilla/BootstrapBlockRegistryListener.java#L41-L45

**Comment by modmuss50** [comment]
This is done as it matches Vanilla in `Blocks.<clinit>`. I expect at somepoint previously it mattered more. 

I think removing this could be breaking as `lootTableId` is only protected in Block, and a mod may not expect it to be null. I think it should be left alone.

**Comment by Technici4n** [comment]
Yes you are right, I didn't see that `Blocks.<clinit>` call... 🙃
