### ISSUE TITLE
Versions after 0.85 cause all Minecraft text to turn to 0s

### ISSUE THREAD

**Issue by F4ntommoth** [FabricMC/fabric#3427]
Went to update fabric api a few months ago and installed version 0.86.0. This caused all text on the main menu to turn to 0s making the game un-playable. I have tried a few other versions since, including 0.90.7 (current latest version for 1.20.1) and the problem still exist. Version 0.85.0 i believe is the last version before this issue became present. It is what I am using currently to be able to play the game. The only other mods I am using currently are optifine, optifabric, azure paxel’s, appleskin, & trinkets. Though I tried with just optifine/optifabric and the problem still existed. (I would remove all mods completely to test but my game is unplayable without optifine)

**Comment by apple502j** [comment]
And yes, the solution is to [remove Optifine](https://fabricmc.net/wiki/community:optifine_alternatives).

**Comment by F4ntommoth** [comment]
Except I can’t remove optifine. As i said no optifine = no game.

**Comment by Linguardium** [comment]
you were linked a page to provide alternatives. it seems you may have missed that or failed to read it

**Comment by F4ntommoth** [comment]
The alternatives do not work nearly as well for me as optifine. My apologies for not making that clear. I’m in a bit of a specific situation where my game quite literally will not run and be playable without optifine. Trust me I’ve tried all of the alternatives, combining the ones that are compatible, etc. Nothing comes close. Sodium and it’s accompanying mods almost* come close but not quite as it is seemingly only half as stable. Constantly fluctuating between 28-ish fps, 7-ish fps, and a frozen screen. Where with optifine I get a decently stable 35-45 ish fps.
