### ISSUE TITLE
[Bug] Creative Inventory has two pages when the `Op Items tab` is enabled with no mods.

### ISSUE THREAD

**Issue by Izaria138** [FabricMC/fabric#3429]
Version: 23w46a
Fabric Loader: 0.14.24
Fabric API: 0.90.9+1.20.3
No other mods.

How to reappear:
1. Enable _Options->Controls->Operator Items Tab_.
2. Open Creative Inventory.

**Comment by modmuss50** [comment]
Please try 0.90.10 as this should have been fixed in that version.
