### ISSUE TITLE
Vanilla launcher-fabric crashes on start, 1.14.4

### ISSUE THREAD

**Issue by lillycham** [FabricMC/fabric#343]
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors!
Crash Report attached
[crash-2019-08-16_21.08.36-client.txt](https://github.com/FabricMC/fabric/files/3511029/crash-2019-08-16_21.08.36-client.txt)

**Comment by modmuss50** [comment]
Not a fabric issue.

Could possibly be an incomablity between cardinal_components_item and optifabric.

I would try removing OptiFabric and see if that fixes the issue. If you need more help with your issue there are a number of places such as the fabric discord that would be able to help you.
