### ISSUE TITLE
Faulty Error for missing dependencie. 

### ISSUE THREAD

**Issue by emme1444** [FabricMC/fabric#344]
The game crashes due to missing dependencie. Even though I added it to the build.gradle file and to the fabric.mod.json file. 

Here is the log:
```
[15:53:24] [main/INFO]: Loading for game Minecraft 1.14.4
Exception in thread "main" java.lang.RuntimeException: Failed to resolve mods!
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:147)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:120)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: net.fabricmc.loader.discovery.ModResolutionException: Errors were found!
 - Mod gui_test_mod depends on mod {libgui @ [1.3.0]}, which is missing!
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:324)
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:504)
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:145)
	... 2 more
```

I've ran genSources multiple times to see if that is the problem but even so that doesn't affect the result. 

Here's the `depends` section in the `fabric.mod.json` file:
```json
"depends": {
    "fabricloader": ">=0.4.0",
    "fabric": "*",
    "libgui":"1.3.0"
}
```

And here's the `dependencies` section of the `build.gradle` file:
```gradle
dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}"
	modCompile "net.fabricmc:fabric-loader:${project.loader_version}"

	// Fabric API
	modCompile "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

	// LibGui
	modCompile "io.github.cottonmc:LibGui:1.3.0"
}
```

I'm also very new to fabric, but honestly I feel like these sort of things should come across pretty straight forward if you look at the documentation. At least I can say that LibGui's documentation is pretty damn bad. 

I don't think that this is an issue, it might as well be an issue but on the LibGui side of things. Or, kind of most likely, a mistake by me. 

Anyway, thanks for any HELP!

**Comment by Pyrofab** [comment]
For what it's worth, the actual libgui documentation is available on [Cotton Team's website](https://cottonmc.github.io/Wiki/getting_started/SetupDeveloper.html) rather than on the actual repository. Apart from that, this does not look like the issue has anything to do with Fabric API, which this issues tracker is for.

**Comment by RicePasteM** [comment]
Well now the [Cotton Team's website](https://cottonmc.github.io/Wiki/getting_started/SetupDeveloper.html) is not available.
