### ISSUE TITLE
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'somanyweapons'!

### ISSUE THREAD

**Issue by NickWithFewtex** [FabricMC/fabric#3441]
'somanyweapons' is my mod

error:
3---- Minecraft Crash Report ----
// Why did you do that?

Time: 2023-11-26 00:58:29
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'somanyweapons'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:387)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:385)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:458)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
Caused by: java.lang.ExceptionInInitializerError
	at net.mrnick.somanyweapons.SoManyWeapons.onInitialize(SoManyWeapons.java:23)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383)
	... 7 more
Caused by: java.lang.IllegalArgumentException: Cannot get property BooleanProperty{name=lit, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{minecraft:air}
	at net.minecraft.state.State.get(State.java:98)
	at net.minecraft.block.Blocks.method_26108(Blocks.java:51)
	at net.minecraft.block.AbstractBlock$AbstractBlockState.<init>(AbstractBlock.java:789)
	at net.minecraft.block.BlockState.<init>(BlockState.java:17)
	at net.minecraft.state.StateManager.method_28484(StateManager.java:61)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at net.minecraft.state.StateManager.<init>(StateManager.java:59)
	at net.minecraft.state.StateManager$Builder.build(StateManager.java:157)
	at net.minecraft.block.Block.<init>(Block.java:183)
	at net.minecraft.block.BlockWithEntity.<init>(BlockWithEntity.java:15)
	at net.mrnick.somanyweapons.block.custom.GemPolishingStationBlock.<init>(GemPolishingStationBlock.java:27)
	at net.mrnick.somanyweapons.block.ModBlocks.<clinit>(ModBlocks.java:18)
	... 9 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:387)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:385)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:458)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:Advanced Windows 32 Base API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:User Experience Controls Library:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:Crypto API32:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.22621.2361 (WinBuild.160101.0800):Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DNS Client API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.22621.2215 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.22621.1344 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP Helper API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:Windows NT BASE API Client DLL:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Windows NT BASE API Client DLL:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		OLEAUT32.dll:OLEAUT32.DLL:10.0.22621.1992 (WinBuild.160101.0800):Microsoft Corporation
		Ole32.dll:Microsoft OLE for Windows:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Windows Performance Data Helper DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:Remote Procedure Call Runtime:10.0.22621.1344 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Windows Shell Common Dll:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		USER32.dll:Multi-User Windows USER API Client DLL:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.16.27031.1 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Windows HTTP Services:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0 32-Bit DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		bcrypt.dll:Windows Cryptographic Primitives Library:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.22621.2361 (WinBuild.160101.0800):Microsoft Corporation
		breakgen64.dll
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:Microsoft COM for Windows:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc.DLL:DHCP Client Service:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc6.DLL:DHCPv6 Client:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		extnet.dll:OpenJDK Platform binary:19.0.2.0:Amazon.com Inc.
		fwpuclnt.dll:FWP/IPsec User-Mode API:10.0.22621.1635 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.22621.2361 (WinBuild.160101.0800):Microsoft Corporation
		iertutil.dll:Run time utility for Internet Explorer:11.00.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		instrument.dll:OpenJDK Platform binary:19.0.2.0:Amazon.com Inc.
		java.dll:OpenJDK Platform binary:19.0.2.0:Amazon.com Inc.
		java.exe:OpenJDK Platform binary:19.0.2.0:Amazon.com Inc.
		jemalloc.dll
		jimage.dll:OpenJDK Platform binary:19.0.2.0:Amazon.com Inc.
		jli.dll:OpenJDK Platform binary:19.0.2.0:Amazon.com Inc.
		jna4313151096524439280.dll:JNA native library:6.1.4:Java(TM) Native Access (JNA)
		jsvml.dll:OpenJDK Platform binary:19.0.2.0:Amazon.com Inc.
		jvm.dll:OpenJDK 64-Bit server VM:19.0.2.0:Amazon.com Inc.
		kernel.appcore.dll:AppModel API Host:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		lwjgl.dll
		management.dll:OpenJDK Platform binary:19.0.2.0:Amazon.com Inc.
		management_ext.dll:OpenJDK Platform binary:19.0.2.0:Amazon.com Inc.
		msvcp140.dll:Microsoft® C Runtime Library:14.16.27033.0 built by: vcwrkspc:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.22621.608 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.22621.608 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Microsoft Windows Sockets 2.0 Service Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:E-mail Naming Shim Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		ncrypt.dll:Windows NCrypt Router:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:OpenJDK Platform binary:19.0.2.0:Amazon.com Inc.
		netutils.dll:Net Win32 API Helpers DLL:10.0.22621.674 (WinBuild.160101.0800):Microsoft Corporation
		nio.dll:OpenJDK Platform binary:19.0.2.0:Amazon.com Inc.
		nlansp_c.dll:NLA Namespace Service Provider DLL:10.0.22621.2070 (WinBuild.160101.0800):Microsoft Corporation
		ntdll.dll:NT Layer DLL:10.0.22621.2361 (WinBuild.160101.0800):Microsoft Corporation
		perfos.dll:Windows System Performance Objects DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		pfclient.dll:SysMain Client:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		pnrpnsp.dll:PNRP Name Space Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.22621.1928 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		shlwapi.dll:Shell Light-weight Utility Library:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		srvcli.dll:Server Service Client DLL:10.0.22621.1928 (WinBuild.160101.0800):Microsoft Corporation
		sunmscapi.dll:OpenJDK Platform binary:19.0.2.0:Amazon.com Inc.
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.22621.608 (WinBuild.160101.0800):Microsoft Corporation
		urlmon.dll:OLE32 Extensions for Win32:11.00.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		verify.dll:OpenJDK Platform binary:19.0.2.0:Amazon.com Inc.
		win32u.dll:Win32u:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:Microsoft WinRT Storage API:10.0.22621.2428 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		wintypes.dll:Windows Base Types DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.22621.1778 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:OpenJDK Platform binary:19.0.2.0:Amazon.com Inc.
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 19.0.2, Amazon.com Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Amazon.com Inc.
	Memory: 488845824 bytes (466 MiB) / 855638016 bytes (816 MiB) up to 8497659904 bytes (8104 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i5-1155G7 @ 2.50GHz
	Identifier: Intel64 Family 6 Model 140 Stepping 2
	Microarchitecture: Tiger Lake
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) Iris(R) Xe Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x9a49
	Graphics card #0 versionInfo: DriverVersion=31.0.101.4032
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 37274.49
	Virtual memory used (MB): 19079.57
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 195.61
	JVM Flags: 0 total; 
	Fabric Mods: 
		fabric-api: Fabric API 0.90.7+1.20.1
		fabric-api-base: Fabric API Base 0.4.30+7abfd51577
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
		fabric-biome-api-v1: Fabric Biome API (v1) 13.0.12+215bbe9677
		fabric-block-api-v1: Fabric Block API (v1) 1.0.10+92a0d36777
		fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+92a0d36777
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
		fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
		fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
		fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
		fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
		fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
		fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.10+57aed33f77
		fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
		fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.2+d7b148e077
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.39+ae9f657a77
		fabric-gametest-api-v1: Fabric Game Test API (v1) 1.2.12+b3afc78b77
		fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
		fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.11+d7b148e077
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
		fabric-loot-api-v2: Fabric Loot API (v2) 1.2.0+96dfa95977
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.44+9e7660c677
		fabric-message-api-v1: Fabric Message API (v1) 5.1.8+d7b148e077
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
		fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
		fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
		fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
		fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.2+4ee0bc6077
		fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
		fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
		fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.0+39a511ba77
		fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.0+39a511ba77
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.36+92a0d36777
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
		fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.6+d7b148e077
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
		fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
		fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
		fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.2+1bc31aeb77
		fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabricloader: Fabric Loader 0.14.24
		java: OpenJDK 64-Bit Server VM 19
		minecraft: Minecraft 1.20.1
		somanyweapons: SoManyWeapons 1.0.0
	Launched Version: Fabric
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

**Comment by apple502j** [comment]
This is not the place to seek help on modding in general. (At least please provide the source code.) We recommend using the GitHub Discussions or Discord.
