### ISSUE TITLE
Entrypoint class cannot be found when using the package starting with `java.`

### ISSUE THREAD

**Issue by BenDol** [FabricMC/fabric#3444]
I am having an issue with `java.lang.ClassNotFoundException: java.bonfyre.fantasyrpg.Frpg` Entrypoint class cannot be found when using the package `java.bonfyre.fantasyrpg` as soon as I remove the `.java` and regenerate the project it works. No idea why.

## Reproduce
Generate a project like so from https://fabricmc.net/develop/template/

Mod Name: `frpg`
Package Name: `java.bonfyre.fantasyrpg`
[x] Split client and common sources

![image](https://github.com/FabricMC/fabric/assets/1935706/fdd7007d-651c-4a92-91dd-ad4f6952b79f)

**Comment by modmuss50** [comment]
I would not put your code in the `java.` package as this its expected to only contain code from Java. We have a number of optimistations such as [here](https://github.com/FabricMC/fabric-loader/blob/fe033879ca4ec2ad8a8e585722752a97db77f96e/src/main/java/net/fabricmc/loader/impl/launch/knot/KnotClassDelegate.java#L215-L217).

**Comment by Daomephsta** [comment]
@BenDol 
Sidenote: Mod IDs should not be abbreviations, as they are meant to be unique. Short is not good for uniqueness.
Abbreviated mod IDs are also much harder to match to the actual mod when they show up in logs and crashes.

**Comment by Player3324** [comment]
The JVM will prevent you from using any package starting with java. - the limitation in Loader is based on a similar one in ClassLoader
