### ISSUE TITLE
0.91.0 crashes with CustomHud and ViaFabricPlus

### ISSUE THREAD

**Issue by Longie520** [FabricMC/fabric#3447]
hi, i just downloaded the latest fapi for 1.20.2 (version 0.91.0), and now my game crashes on startup. i was able to eliminate other mods and find the conflict with customhud and viafabricplus. i have attached the crash report.

[crash-2023-11-27_17.31.23-client.txt](https://github.com/Minenash/CustomHUD/files/13470875/crash-2023-11-27_17.31.23-client.txt)

steps to reproduce:
1. install fapi 0.91.0, customhud 3.3.0 and viafabricplus 2.9.5 in the mods folder
2. starts the game
3. game crashes on start up

expected behavior:
game would run normally just like with an older version of fapi (0.90.7)

game environment:
MacOS M1
mc version 1.20.2
java version 17.0.8

i have also reported this on custom hud and viafabricplus

**Comment by apple502j** [comment]
Closing, please file on our bug tracker only after the other mods' developers asks so.
