### ISSUE TITLE
Ancient debris is not considered an ore by conventional tags

### ISSUE THREAD

**Issue by TheRealWormbo** [FabricMC/fabric#3462]
Ancient debris generates a lot like an ore (individually or in very small groups, similar to emerald ore) and smelts into an item that can be processed further, similar to how other metal ores behaved before they got a raw ore item, or how silk-touched ores still do.

Something that categorizes "ores" should likely include Ancient Debris. However, the conventional tags library does not mention ancient debris in its block or item tags for ores.

**Comment by haykam821** [comment]
Ancient debris isn't considered an ore, as it does not follow the same material format as ores and does not have the same appearance as ores.

Ancient debris drops itself and smelts into netherite scraps, which are crafted with gold ingots into netherite ingots. Ore drops raw ore (or itself with silk touch) and smelts into ingots or crystals directly.

In addition, ores are chunks of the material embedded in some type of stone. Ancient debris is an entire chunk of metal, serving a more similar role to iron blocks if they had generated underground. Ancient debris must be salvaged to be useful.

If you need a tag with ores and ancient debris, you can always make your own.

**Comment by maityyy** [comment]
#3310 [already adds](https://github.com/FabricMC/fabric/pull/3310/files?file-filters%5B%5D=.gradle&file-filters%5B%5D=.java&file-filters%5B%5D=.md&file-filters%5B%5D=.png&file-filters%5B%5D=.properties&file-filters%5B%5D=dotfile&show-deleted-files=true&show-viewed-files=true#diff-d9cfdadadfd49dd33439e648073dc1d59d2a54fec1ba07754d912ebdc57d28f7R84) the ancient debris to the ore tag.

This has also [been discussed](https://discord.com/channels/507304429255393322/566276937035546624/1171837139240099982) a bit on discord

**Comment by TheRealWormbo** [comment]
> #3310 [already adds](https://github.com/FabricMC/fabric/pull/3310/files?file-filters%5B%5D=.gradle&file-filters%5B%5D=.java&file-filters%5B%5D=.md&file-filters%5B%5D=.png&file-filters%5B%5D=.properties&file-filters%5B%5D=dotfile&show-deleted-files=true&show-viewed-files=true#diff-d9cfdadadfd49dd33439e648073dc1d59d2a54fec1ba07754d912ebdc57d28f7R84) the ancient debris to the ore tag.

Didn't see that before, thanks for pointing me to it.
