### ISSUE TITLE
Packets broken on latest FAPI in 1.20.1

### ISSUE THREAD

**Issue by AViewFromTheTop** [FabricMC/fabric#3464]
[01:00:07] [Render thread/ERROR] (Minecraft) Error executing task on Client
 io.netty.util.IllegalReferenceCountException: refCnt: 0

I've already seen that packets were likely broken on 0.91.0, I'd just like for an official hotfix to be released. The same exact code works flawlessly on 1.20.2 using 0.91.2.

**Comment by haykam821** [comment]
You should show your code, as there's a chance that the changes in Fabric API for Minecraft 1.20.2 fixed some edge case that wasn't supported before. `IllegalReferenceCountException` is known to be thrown if you are keeping around the buffer for longer than necessary, for example.

Note that the branch of Fabric API for Minecraft 1.20.1 hasn't received the recent networking changes.

**Comment by AViewFromTheTop** [comment]
![IMG_3017](https://github.com/FabricMC/fabric/assets/87103914/5d29c7db-55a5-4c50-abef-09405c2ef80b)
![IMG_3018](https://github.com/FabricMC/fabric/assets/87103914/69698abd-a7a8-4ece-9bfa-23459fa9e195)
I sincerely apologize for the lack of good photos, im about to fall asleep lol
It throws the error at the first read (readint)

**Comment by AViewFromTheTop** [comment]
Semi-related but is there anywhere I could go for help on porting a mod to 1.20.4?
A ton of things are randomly throwing errors about the level being null when im trying to load up the world and it’s at 100%, and I don’t think an issue report is a good way to ask for help lol

**Comment by apple502j** [comment]
You should construct one ByteBuf per player.
