### ISSUE TITLE
Villagers and players appear rotated in beds when Fabric API is installed

### ISSUE THREAD

**Issue by joshuaprince** [FabricMC/fabric#3470]
The sleeping pose incorrectly renders entities' rotation, causing them to show up incorrectly in beds. This happens with Fabric API and no other mods installed. Removing Fabric API fixes the issue.

MC 1.20.4, Fabric 0.15.2, FAPI 0.91.2+1.20.4:
![2023-12-15_21 50 31](https://github.com/FabricMC/fabric/assets/16515311/9be06c6a-1576-4c79-88c7-eb55de7b510a)
![2023-12-15_21 59 46](https://github.com/FabricMC/fabric/assets/16515311/0825d890-7668-4f8c-8d09-3f590e81be3b)

MC 1.20.4, Fabric 0.15.2, no other mods:
![2023-12-15_21 50 58](https://github.com/FabricMC/fabric/assets/16515311/5f5f6b9d-f4d4-45c3-ac1c-fc11407d4bb5)
![2023-12-15_22 00 22](https://github.com/FabricMC/fabric/assets/16515311/224c4c14-b388-4964-b086-8ba069401117)

Extra information:
MC 1.20.4
Fabric 0.15.2
Fabric API 0.91.2+1.20.4
OS: Arch Linux
Java: openjdk 17.0.9 (same happens on 21)

**Comment by dicedpixels** [comment]
Can confirm. 

![2023-12-16_11 48 06](https://github.com/FabricMC/fabric/assets/121529979/bf55a6ff-d2ec-48cf-9b7e-89ebd64aabe8)

The hitbox:

![2023-12-16_11 55 41](https://github.com/FabricMC/fabric/assets/121529979/10b38364-3c38-4218-a336-23dd0ddae8b8)

[latest.log](https://github.com/FabricMC/fabric/files/13691590/latest.log)

---
Edit:

Based on some quick testing based on GH Actions builds, it appears to be this https://github.com/FabricMC/fabric/commit/78d798af9d2313f25e5666e3dec3dc1fabe056f2

And likely this mixin: https://github.com/FabricMC/fabric/blob/78d798af9d2313f25e5666e3dec3dc1fabe056f2/fabric-entity-events-v1/src/main/java/net/fabricmc/fabric/mixin/entity/event/LivingEntityMixin.java#L113

~~(Probably the locals 🥲)~~

**Comment by apple502j** [comment]
Ah yes, `getReturnValue` before return. What could go wrong?
