### ISSUE TITLE
Old Fabric versions say to be supported in new versions but are not

### ISSUE THREAD

**Issue by Eatham532** [FabricMC/fabric#3472]
Hi, not exactly sure where to place this bug as I am guessing it is partially due to the [metadadta](https://meta.fabricmc.net). I stumbled upon this issue when trying to make my own Minecraft launcher and trying to run `1.20.4` with the fabric version of `0.1.0.48`.

The metadata says that this version is supported. View url [here](https://meta.fabricmc.net/v2/versions/loader/1.20.4/0.1.0.48/). However even your own fabric installer cannot install this version.

### Tests (All done running 1.20.4 with loader version 0.1.0.48)

When trying to install using fabric installer v0.11.2:
> java.lang.NullPointerException  at net.fabricmc.installer.util.Library. (Library.java:37)  at net.fabricmc.installer.client.ClientInstaller.install(ClientInstaller.java:70)  at net.fabricmc.installer.client.ClientHandler.lambda$doInstall$1(ClientHandler.java:100)  at net.fabricmc.installer.client.ClientHandler$$Lambda$26/117298272.run(Unknown Source)  at java.lang.Thread.run(Thread.java:745)
> 

When using my own launcher that does launch the latest Minecraft and fabric version I get the following error:
> Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
>

I tested with two other launchers. Both fail to launch. The Modrinth launcher doesn't give any logs. But GdLauncher gave a similar response to what I got in my launcher.
> Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap') at net.minecraft.launchwrapper.Launch.
>

**Comment by modmuss50** [comment]
Fabric loader only guarentees backwards compatibility, there is no way we can plan for the future. I do see this an issue, and is possibly something we can solve in metadata v3 as detailed here: https://github.com/FabricMC/fabric-meta/issues/25

**Comment by modmuss50** [comment]
Going to close this as I dont think there is a lot we can do to dermine what versions are supported or not. Generally always use the latest version.
