### ISSUE TITLE
File fabric-api-0.3.1+build.208.jar this mod is for Fabric and it cant be launched. 

### ISSUE THREAD

**Issue by w0rl3x** [FabricMC/fabric#348]
https://prnt.sc/ovykld

**Comment by LemmaEOF** [comment]
This mod will not work with Minecraft Forge. It is exclusively for the Fabric mod loader, and there's no reason *to* port it to Forge, since Forge already does practically everything Fabric API does.

**Comment by modmuss50** [comment]
Install fabric loader from: https://fabricmc.net/
