### ISSUE TITLE
Ask for your permission

### ISSUE THREAD

**Issue by DSLZL** [FabricMC/fabric#3484]
Hello, FabricMC creators.
I'm DSLZL, and I'm sorry for opening a new issue on your project that is completely unrelated, but I can only contact you on GitHub in China.
I'd like to ask if I can put this Fabric API you made into my modpack and release it in modrinth, because I don't know much about the license, so I'm here to ask your opinion, and if my actions violate your rights, I'm very sorry and delete the modpack and apologize as soon as I see your reply.
The modpack link in modrinth is: [only-optimized](https://modrinth.com/modpack/only-optimized), if you don't see it, it's because it's still under review.
Sorry to interrupt you, but please forgive me for any inconvenience I may have if I do not obtain your permission.
(This passage is supported by Microsoft Translator, if you agree with my behavior, please do not delete this issue, so that I can provide evidence if I need it)
Thank you so much.

**Comment by apple502j** [comment]
Yes, you can.

**Comment by DSLZL** [comment]
Thank you so much
