### ISSUE TITLE
Hi guys, so i'm making a pretty big modpack but i'm running into the same problem saying:"Could not execute entrypoint stage 'main' due to errors, provided by 'forge_tags'!"

### ISSUE THREAD

**Issue by JustADudeHUN** [FabricMC/fabric#3527]
Here is the full crash report: 
[crash-2024-01-13_23.43.29-client.txt](https://github.com/FabricMC/fabric/files/13929754/crash-2024-01-13_23.43.29-client.txt)

**Comment by apple502j** [comment]
This is a bug in Porting Lib, not Fabric API. Please update porting-lib.
