### ISSUE TITLE
Fabric doesn't work with Java 14

### ISSUE THREAD

**Issue by cyb3rm4n** [FabricMC/fabric#354]
Got this error when testing Fabric wiith Java 14: https://hastebin.com/yoqulenega.sql

**Comment by RedstoneParadox** [comment]
Does Minecraft even support Java 14?

**Comment by modmuss50** [comment]
Once ASM 7.2 is out of beta we can update to support j14

**Comment by Sollace** [comment]
Last I checked Minecraft didn't even support Java _9_. I highly doubt 14 is anywhere remotely possible.

**Comment by kgscialdone** [comment]
Minecraft is known to be able to run as high as Java 12, though it only explicitly supports Java 8. I don't much doubt that it could run on Java 14 considering Java's extreme distaste for any sort of breaking changes.

**Comment by modmuss50** [comment]
Java 13 is known to work.

The reason 14 doesnt work is due to the requirement of ASM 7.2, if you really want to use it you can use the beta but for now stick to 13 and bellow.

The current recommended version is 8.

**Comment by LemmaEOF** [comment]
According to Chocohead's reactions in fabricord, Minecraft itself will work with Java 14, but ASM7.2 is the primary bottleneck here.

**Comment by cyb3rm4n** [comment]
Clean unmodded Minecraft 1.14.4 works fine on Java 14.

**Comment by creeper123123321** [comment]
https://asm.ow2.io/versions.html ASM 7.2 is out of beta

**Comment by liach** [comment]
Pr open at https://github.com/FabricMC/fabric-loader/pull/160
Since this is related to the loader than the api, closing.

**Comment by asiekierka** [comment]
"Clean unmodded Minecraft 1.14.4 works fine on Java 14." - A bit off-topic, but... out of curiosity, does it not expose the same ConcurrentModificationException problems some users saw on Java 9 ~ 12?

**Comment by Player3324** [comment]
There is also a problem with something apparently trying to process java.* with asm, this shouldn't happen in the first place...
