### ISSUE TITLE
About mappings in 19w36a

### ISSUE THREAD

**Issue by forestbat** [FabricMC/fabric#355]
> Another week has gone by and we're busy trampling bugs here at the Mojang office. Apart from that we're now letting everyone take part of our obfuscation maps which should make your life easier if you're interested in creating mods for Minecraft: Java Editon.

https://launchermeta.mojang.com/mc/game/version_manifest.json

How do you think this news？I think you probably need to change links to get mappings and cancel yarn.

**Comment by shedaniel** [comment]
A lot has happened in fabricord, I think you would want to hear from there.
