### ISSUE TITLE
[1.20.4] `CommonLifecycleEvents#TAGS_LOADED` isn't called on client thread when joining a world

### ISSUE THREAD

**Issue by Fuzss** [FabricMC/fabric#3554]
The callback is supposed to run with the `client` flag set to `true` when the client receives the tag sync packet from the server. 

Currently this does not happen for both joining a singleplayer world and clients connecting to a dedicated server.

The callback however does run perfectly fine with the `client` flag set to `true` after executing `/reload`.

The callback on the server thread seems to work fine (when `client` is set to `false`).

**Comment by apple502j** [comment]
See also: https://discord.com/channels/507304429255393322/566276937035546624/1200117343674703883

**Comment by modmuss50** [comment]
Should be fixed into todays 1.20.2 and 1.20.4 releases 👍

**Comment by apple502j** [comment]
:ohno: https://github.com/FabricMC/fabric/commit/54b4400cee545de0c099a5783e1638666f4ac406#diff-c6e29ca83f05547caa3e3bc490be62d86b710ee412daf58db1ff84698cae0089L102
