### ISSUE TITLE
FabricBlockSettings.copy not copying all settings

### ISSUE THREAD

**Issue by xanthian** [FabricMC/fabric#3570]
```java
public static final Block COPPER_GRATE = new OxidizableGrateBlock(Oxidizable.OxidationLevel.UNAFFECTED, 
FabricBlockSettings.of(Material.METAL)
.strength(3.0F, 6.0F)
.sounds(ModSounds.COPPER_GRATE)
.mapColor(MapColor.ORANGE)
.nonOpaque()
.requiresTool()
.allowsSpawning(Blocks::never)
.solidBlock(Blocks::never)
.suffocates(Blocks::never)
.blockVision(Blocks::never));
```
registration for copper grate (which works)

```java
public static final Block WAXED_COPPER_GRATE = new GrateBlock(FabricBlockSettings.copy(COPPER_GRATE));
```
registration for waxed variant, copying the above
however, the `.solidBlock(Blocks::never)` is not copied over resulting in the block transmitting redstone.
Also not copying is ``.suffocates(Blocks::never)``
I've not tested but I would also presume the following are not copied :
`.allowsSpawning(Blocks::never)`
`.blockVision(Blocks::never)`

https://github.com/FabricMC/fabric/assets/7688001/2e5b28f2-1190-4e38-b75e-5df4e19a74f3

Even if i create a custom never boolean without using an AW on the Blocks::never it still doesn't copy over

**Comment by xanthian** [comment]
I think I'm a numpty and should be using copyOf and not copy
But will await a reply regardless

**Comment by modmuss50** [comment]
What Fabric API version are you using?

We have also deprecated FBS, you should be using `AbstractBlock.Settings#copy`

**Comment by apple502j** [comment]
In newer versions (1.20.4?) vanilla `copy` copies every attribute, `copyShallow` copies only some. (`copy` used to only copy some in older versions.) FAPI has never changed the behavior of `copy`, only the static `copyOf`.
