### ISSUE TITLE
remove OverlayVertexConsumerMixin in Fabric API for Minecraft 1.20.5

### ISSUE THREAD

**Issue by Lolothepro** [FabricMC/fabric#3582]
This seems to be unnecessary, as it is fixed in Minecraft 24w05a (see https://bugs.mojang.com/browse/MC-193656)

**Comment by Lolothepro** [comment]
![image](https://github.com/FabricMC/fabric/assets/68275908/5d108348-f3d3-41b9-950d-e634c8d4957f)

**Comment by Technici4n** [comment]
It can be removed, yes.
