### ISSUE TITLE
Ice/Honey block/Slime block/Frosted Ice cause water to show flowing animation at the sides

### ISSUE THREAD

**Issue by Lolothepro** [FabricMC/fabric#3592]
Fabric API:
![2024-02-14_20 44 18](https://github.com/FabricMC/fabric/assets/68275908/db95b7ec-926f-4c99-aec8-3c0dfff406d0)

Vanilla:
![2024-02-14_20 45 25](https://github.com/FabricMC/fabric/assets/68275908/b82ce2bf-17bf-4a0d-9f8f-f83efa7c71a1)

it would be nice if this bug was fixed before Sodium 0.6.0

**Comment by Lolothepro** [comment]
related to: https://github.com/CaffeineMC/sodium-fabric/issues/2335

**Comment by Lolothepro** [comment]
see https://bugs.mojang.com/browse/MC-91224

**Comment by maityyy** [comment]
What version of the game and fabric is this on?

**Comment by Lolothepro** [comment]
> What version of the game and fabric is this on?

Fabric API 0.95.4 with Minecraft 1.20.4
and also occurs with Fabric + Minecraft 1.20.5
