### ISSUE TITLE
`ClientPlayNetworking.registerGlobalReceiver` handler getting called with `null` player

### ISSUE THREAD

**Issue by henkelmax** [FabricMC/fabric#3602]
When using `ClientPlayNetworking.registerGlobalReceiver`, the `PlayPayloadHandler` is getting called with a `null` player in the `Context`.
Here a screenshot from the debugger:
![image](https://github.com/FabricMC/fabric/assets/13237524/f4c2118b-c903-4083-8c1b-84fd037f5266)

This happens in `24w07a` with `0.96.2+1.20.5`.

It seems to have been introduced in `24w03b` with the networking changes.

**Comment by modmuss50** [comment]
Thanks a lot for trying out the 1.20.5 builds and finding this. I have created a PR with the fix here: https://github.com/FabricMC/fabric/pull/3603 I plan to release this (along with some other fixes) later today. 👍

**Comment by henkelmax** [comment]
Thank you for the quick fix! Works perfectly in `0.96.3`.
