### ISSUE TITLE
Portable Offline Development Environment

### ISSUE THREAD

**Issue by Karaclysm119** [FabricMC/fabric#362]
So I'm sort of trying to develop fabric mods in my freetime at school, and the web filter blocks minecraft.net, and whenever i go to build and test, it tries to download a ton of libraries from libraries.minecraft.net, I was wondering 3 things.

1. Does it download these libraries on every build regardless of whether it has them or not?
2. If it doesn't where do they go when they are downloaded?
and
3. Would it be possible to change the location it points to when searching for these libraries?

**Comment by liach** [comment]
add --offlineb flag when building at school.

**Comment by Karaclysm119** [comment]
This is gonna sound stupid, but where?

**Comment by modmuss50** [comment]
This should work just fine, as there were some semi-recent changes to loom to allow this.

1) No it should only download the files when they are not found.

2) The files are all downloaded in `.gradle` in your user directory.

3) Possibly I would look into moving the gradle user dir.

Once you have your IDE setup, it will work just fine without internet. If you want to build a mod or use any of the gradle tasks I would run with `--offline`

**Comment by Karaclysm119** [comment]
okay thank you, I've built once at home so I should be able to move the files from there, although I'm using eclipse and sort of last as to where I'm gonna be inputting the --offline flag

**Comment by modmuss50** [comment]
If you using the eclipse you can use the run configurations provided and that will build the mod using eclipse without requiring the internet. You might be able to get away without using gradle or the offline flag, as for using it eclipse im not sure.

**Comment by Karaclysm119** [comment]
Alright I'll look into it. Thanks for all the help!

**Comment by Karaclysm119** [comment]
For anyone else looking at this also using eclipse, the gradle settings include both a location to use as the gradle directory, and also a check box for offline mode.
