### ISSUE TITLE
/title does not work on 0.15.7

### ISSUE THREAD

**Issue by starrider346** [FabricMC/fabric#3620]
Displaying a title on 0.15.6 will result in the title being showed like normal. 0.15.7 has nothing.

0.15.6:
![image](https://github.com/FabricMC/fabric/assets/58882729/aa6ed969-baf5-4ee0-afeb-1d5990d6ee32)

0.15.7:
![image](https://github.com/FabricMC/fabric/assets/58882729/7d414354-eb55-4332-a938-adab6c6acb4d)

**Comment by starrider346** [comment]
These installs are modless, just plain fabric so a mod isn't causing it.

**Comment by Linguardium** [comment]
this is the issue tracker for fabric api not fabric loader. i tested titles on 1.20.4 with fabric loader 0.15.7 and they work as they are supposed to. best to provide the test case rather than just pictures.

fabric mod loader is here:
https://github.com/FabricMC/fabric-loader

**Comment by Linguardium** [comment]
and just to make sure you werent reporting a fabric api issue, i added fabric-api 0.96.4+1.20.4 and titles still show correctly

**Comment by starrider346** [comment]
Oh OK

**Comment by starrider346** [comment]
I am not sure what is causing it then
