### ISSUE TITLE
How to edit Minecraft source code?

### ISSUE THREAD

**Issue by RadBe** [FabricMC/fabric#3622]
In Forge, I just changed the file I needed (for example "projects\forge\src\main\java\net\minecraft\server\MinecraftServer.java"), compiled, obfuscated, and threw it into the server files. How can I do this with Fabric? In the server file I see the files "a.class", "aaa.class", etc. How do I edit them? Mixins are not suitable for me, I want to change the source code itself.

**Comment by Linguardium** [comment]
fabric does not support this. mixins allow quite a lot of replacement, and Fabric-ASM mod allows even more cursed implementations but i would advise against what you seem to think is "required"

**Comment by modmuss50** [comment]
The entire fabric toolchain is fundamentally designed around using bytecode (usually using Mixins) modification, not source modification. There is no concept of "JarModding" like what you are after. I would strongly recommend making a normal mod with mixins (even on forge), you can do basically everything while being more compatible and portable.
