### ISSUE TITLE
[Suggestion] Resource Conditions support for dynamic registries

### ISSUE THREAD

**Issue by ChrysanthCow** [FabricMC/fabric#3632]
Currently, I don't think there's anything for this functionality. Imo, it'd be very neat to have this, for stuff like biomes.
This'll probably apply to blocks in the future too, so I'd say it's a priority when that happens.

**Comment by maityyy** [comment]
The problem is that this is the same as removing an entry from the registry

**Comment by ChrysanthCow** [comment]
> The problem is that this is the same as removing an entry from the registry

Ah, thanks for explaining.

**Comment by apple502j** [comment]
I think this is actually possible. Of course, certain features - like checking for tags - would be disabled, as tags are loaded after registries.
