### ISSUE TITLE
Registries.PROCESSOR_LIST Datagen does not create files

### ISSUE THREAD

**Issue by JT122406** [FabricMC/fabric#3633]
Trying to datagen ProcessorLists and this works on forge I tested but doesn't work on fabric Screenshots of code below:
![image](https://github.com/FabricMC/fabric/assets/75751882/73a43ce3-c247-4044-af33-193a60acb2a0)
![image](https://github.com/FabricMC/fabric/assets/75751882/494d80b3-e1e3-4571-aaca-a3ed3a7a3035)
Datagen runs and completes but no jsons are made

**Comment by JT122406** [comment]
1.20.1, Fabric Loader 0.15.7 and Fabric API 0.92.0

**Comment by JT122406** [comment]
also the other 3 registry set builders do work properly it's only processor list that isn't

**Comment by CrypticVerse** [comment]
Do you have the fabric-datagen entry point in fabric.mod.json?

**Comment by JT122406** [comment]
> Do you have the fabric-datagen entry point in fabric.mod.json?

Yes, as I stated all the rest of the datagen done in this mod works correctly

**Comment by brainage04** [comment]
May I ask why this was closed as completed? I'm doing a similar thing with processor list generation and also having the same issue. Some important values from `gradle.properties`:
```
minecraft_version=1.21.10
yarn_mappings=1.21.10+build.3
loader_version=0.18.1
loom_version=1.13-SNAPSHOT
fabric_version=0.138.3+1.21.10
```

buildRegistry call: https://github.com/brainage04/ProceduralDungeon/blob/33bff2e89420d57854b1cb48e30d8757f3e3c385/src/main/java/com/github/brainage04/procedural_dungeon/datagen/ModDataGenerator.java#L18

Same situation - fabric-datagen properly linked in fabric.mod.json, other things generate fine, but no files generated for processor lists.

**Comment by cputnam-a11y** [comment]
> May I ask why this was closed as completed? I'm doing a similar thing with processor list generation and also having the same issue. Some important values from `gradle.properties`:
> 
> ```
> minecraft_version=1.21.10
> yarn_mappings=1.21.10+build.3
> loader_version=0.18.1
> loom_version=1.13-SNAPSHOT
> fabric_version=0.138.3+1.21.10
> ```
> 
> buildRegistry call: https://github.com/brainage04/ProceduralDungeon/blob/33bff2e89420d57854b1cb48e30d8757f3e3c385/src/main/java/com/github/brainage04/procedural_dungeon/datagen/ModDataGenerator.java#L18
> 
> Same situation - fabric-datagen properly linked in fabric.mod.json, other things generate fine, but no files generated for processor lists.

It looks like you are missing a provider for ProcessorLists

**Comment by brainage04** [comment]
> It looks like you are missing a provider for ProcessorLists

I didn't realise I needed one. I wrote my code based off of his screenshots, and it doesn't look like he's using providers for any registries he's generating files for in his buildRegistry method (although I can't see what that last line is in onInitializeDataGenerator - not sure if that's relevant)

When I looked I couldn't find any providers in the Fabric API for processor lists. Now that I've looked again I see there is a FabricDynamicRegistryProvider - is that the provider I need to use?

**Comment by brainage04** [comment]
Ok I see what you mean now - I used FabricDynamicRegistryProvider instead and basically just replaced all of my Registerable<StructureProcessorList> usages with FabricDynamicRegistryProvider.Entries instead. Problem fixed!

See new implementation for reference: https://github.com/brainage04/ProceduralDungeon/blob/4357f6b4755d076ff30b81f9da73229693073eaa/src/main/java/com/github/brainage04/procedural_dungeon/datagen/processor_list/DungeonProcessorListProvider.java#L230
