### ISSUE TITLE
fabric-resource-loader-v0 causes crash in minecraft 1.20.4

### ISSUE THREAD

**Issue by Menion2k** [FabricMC/fabric#3637]
Hi all

I am trying to launch via multiMC a farly basic MC 1.20.4 Java Edition. I bring into the mods YetAnotherConfigLib (3.3.2) with Fabric Resource Loader V0 0.11.9 and Fabric APUI 0.96.4 required for Controlify.

But MC crashes at startup (yes I launched once online). The mod that causes the crash is Fabric Resource loader v0 (tried also older version), its pressence is enought to kick the crash.

It complains of:

java.lang.NoSuchMethodError: 'net.minecraft.class_2487 net.minecraft.class_2507.method_30613(java.io.File)'

Attached the crash log
[crash-2024-03-10_11.12.33-client.txt](https://github.com/FabricMC/fabric/files/14549769/crash-2024-03-10_11.12.33-client.txt)

**Comment by apple502j** [comment]
@Menion2k Could you upload the zip of the mods folder?

**Comment by Menion2k** [comment]
Do you want the actual content of the mods folder or the list of all jar files would be enough?

**Comment by apple502j** [comment]
@Menion2k Actual contents.

**Comment by modmuss50** [comment]
`resourceloader: Fabric Resource Loader 1.1.1` whatever mod this in the mods folder is causing the problem. It's not something we make.

**Comment by Menion2k** [comment]
> `resourceloader: Fabric Resource Loader 1.1.1` whatever mod this in the mods folder is causing the problem. It's not something we make.

Hi

If you gave me the time.... This mod is not causing the problema, here attached the crashlog with this mod disabled and the contents of mods as requested
[crash-2024-03-10_13.24.34-client.txt](https://github.com/FabricMC/fabric/files/14550131/crash-2024-03-10_13.24.34-client.txt)
[mods.zip](https://github.com/FabricMC/fabric/files/14550132/mods.zip)
