### ISSUE TITLE
[fabric-event-interactions-v0] Crashes in 19w37a

### ISSUE THREAD

**Issue by oliviathevampire** [FabricMC/fabric#364]
Whenever I try and start the game in 19w37a I get this https://hastebin.com/ragacadama.makefile

**Comment by Chocohead** [comment]
Are you definitely using Fabric API 225, 227 or 229?

**Comment by liach** [comment]
turns out mojang changed item interact mechanism so that they can fix that hand not swinging when placing lily pad bug, and we are messed up

**Comment by liach** [comment]
In fact, we need to split the old event into a client one and a server one for only the client handler has changed.
