### ISSUE TITLE
Summoning a large EXP orb damages mending items to the extreme negatives

### ISSUE THREAD

**Issue by CrypticVerse** [FabricMC/fabric#3657]
I was playing a world today, and was experimenting with summoning large EXP orbs. The only mod I had was Fabric API 0.96.11+1.20.4 and MC 1.20.4

Expected:
Elytra/tools would mend

What Happened:
Elytra/tools went into the extreme negatives of the durability

Reproduce
1. Give yourself an elytra or tools
2. Enchant elytra/tool with Unbreaking 3 and Mending 
3. Summon a large EXP orb a few times using /summon
4. Make sure the elytra/tool in in your hand and has < Max Durability
5. See that the elytra or tool has a extreme negative durability

Video:
[click here, too big for GH](https://www.dropbox.com/scl/fi/u85c0455v409euxfbuy6t/bug.mov?rlkey=jhgpaju9yj3ppvz9ns238negd&dl=0)

I did test this in vanilla, worked as expected.

**Comment by CrypticVerse** [comment]
Also works with other tools and other worlds

I also can kind of repro on 1.20.5. Instead, on 1.20.5, and when porting to 1.20.5, it just sets the durability to 0


![2024-03-19_18 17 17](https://github.com/FabricMC/fabric/assets/143554094/5def2af3-cb18-4571-8f7e-d1c859969e66)
![2024-03-19_18 17 14](https://github.com/FabricMC/fabric/assets/143554094/8fba0260-ef8e-4f78-9088-2b099af40e75)

**Comment by haykam821** [comment]
If I'm correct, these commands should be able to reproduce this issue:

```mcfunction
item replace entity @s weapon.mainhand with diamond_pickaxe{Damage:1,Enchantments:[{id:mending,lvl:1}]} # 1.20.4
item replace entity @s weapon.mainhand with diamond_pickaxe[damage=1,enchantments={levels:{mending:1}}] # 1.20.5

summon minecraft:experience_orb ~ ~ ~ {Value:100000}
```

In both Minecraft 1.20.4 and Minecraft snapshot 24w11a, I was able to get a near-broken pickaxe by running the above commands regardless of whether I was using vanilla or Fabric API.
