### ISSUE TITLE
fabric api crashes in MultiMC launcher

### ISSUE THREAD

**Issue by G93d14** [FabricMC/fabric#368]
here is the log of the crash, as you can see, only fabric API was installed. https://paste.ee/p/k1tcs

**Comment by Player3324** [comment]
Your fabric loader version is too old, it needs 0.6 or later, you have 0.4.8. I don't know how or if MultiMC selects the loader version.

**Comment by G93d14** [comment]
thank you! i recreated the fabric instance from the website and it works
now!
