### ISSUE TITLE
Convention tags v2 uses a separate datapack from the Fabric API main datapack

### ISSUE THREAD

**Issue by mrjasonn** [FabricMC/fabric#3732]
This issue has been found when I used the command `/datapack list` in a world. This has been tested with Fabric API `0.97.6+1.20.5`. When running the command, it shows that there are 3 datapacks enabled: the Minecraft vanilla datapack, the Fabric API one, and a very specific fabric convention tags v2 one. This is not the case with v1.

**Comment by apple502j** [comment]
@mrjasonn Please provide more information, like logs and command output. Also, make sure you have the latest version of Fabric API.

**Comment by mrjasonn** [comment]
> @mrjasonn Please provide more information, like logs and command output. Also, make sure you have the latest version of Fabric API.

The command output does show that there are 3 datapacks enabled: the Minecraft vanilla datapack, the Fabric API one, and a very specific fabric convention tags v2 one as I have said. The logs aren't that relevant. I have tested with Fabric API `0.97.6+1.20.5`.

**Comment by Lolothepro** [comment]
This is the same behavior as with "Fabric convention tags v1".

**Comment by apple502j** [comment]
[Working as intended.](https://github.com/FabricMC/fabric/blob/1.20.5/fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/mixin/resource/loader/DatapackCommandMixin.java) Note, although those data packs do show up in `datapack list`, they cannot be independently disabled.
