### ISSUE TITLE
Crash when loading void superflat with registered biome modifications

### ISSUE THREAD

**Issue by Oliver-makes-code** [FabricMC/fabric#3736]
Crash log: https://mclo.gs/lH6dDg6

Minimal reproduction repository: https://github.com/Oliver-makes-code/biome-modification-crash

Reproduction steps:
1. Run the client with the reproduction repository
2. Create a new void superflat world
3. Crash

**Comment by Oliver-makes-code** [comment]
I'm investigating this issue further

**Comment by Oliver-makes-code** [comment]
It appears I had the reproduction wrong, I amended that.

**Comment by Oliver-makes-code** [comment]
https://github.com/FabricMC/fabric/blob/a704f5c7f55870ec505e6c65d9b61bcc9f848072/fabric-biome-api-v1/src/main/java/net/fabricmc/fabric/impl/biome/modification/BiomeModificationImpl.java#L160

This could be where the issue is originating

**Comment by apple502j** [comment]
Pro tip: always test superflat worlds, even if you're testing Biome API...
