### ISSUE TITLE
Should `c:coal` item tag be removed in favor of minecraft's coal tag?

### ISSUE THREAD

**Issue by TelepathicGrunt** [FabricMC/fabric#3742]
It is a bit late now but wanted to document it here so it is not forgotten about. Nouns should be plural so this tag not being called coals was a typo. It isn't in neo side so no mismatch there. But it can't be fixed on Fabric's side without it being a breaking change in code unless a second coals tag is made, deprecate the singular one, and pull in the singular one into the plural one as an optional entry.

**Comment by apple502j** [comment]
Hmm, why is this `coals` in NeoForge? Coal is uncountable.

**Comment by Shnupbups** [comment]
> Hmm, why is this `coals` in NeoForge? Coal is uncountable.

I believe we decided that we still use the 's' even for uncountable nouns, since the tags collect different *types* of them, so it is sort of grammatically correct. Like you can have lots of fruit, but also lots of different fruits. You can have lots of coal, but also lots of different coals.

**Comment by TelepathicGrunt** [comment]
What shnup said. It’s why the tag convention is fishes and meats because it’s easier and less likely to cause confusion on whether to have an s or not for a noun by going with thinking of the tags as different types of stuff which would then required the s. Thus all nouns should have s generally. If confused, add s.

The coal tag isn’t on neoforge side yet though at all. Might add it over there to match if I can find some neoforge mods with different coal types.

**Comment by TelepathicGrunt** [comment]
: thonk : 
Coals is a Mc tag

https://github.com/misode/mcmeta/blob/data-json/data/minecraft/tags/items/coals.json

Now I’m curious, what was fabric’s motivation originally to have a coal tag under c instead of using mc’s?
