### ISSUE TITLE
Fabric loader 166 breaks the Controls menu

### ISSUE THREAD

**Issue by calloatti** [FabricMC/fabric#375]
The keybinds for mods are not listed.

166:
![image](https://user-images.githubusercontent.com/12817862/65399740-cdd99d80-dd94-11e9-83de-0bb5c6750674.png)

165:
![image](https://user-images.githubusercontent.com/12817862/65399748-d6ca6f00-dd94-11e9-8af8-773f8886db15.png)

**Comment by calloatti** [comment]
This belongs in Fabric-loader

**Comment by Prospector** [comment]
FYI in the future, issues can be moved by organization managers so you can just request them to be moved
