### ISSUE TITLE
Easiest way to get mojang mapped minecraft src?

### ISSUE THREAD

**Issue by ghost** [FabricMC/fabric#3759]
Whats easiest way to get mojang mapped minecraft client + server 'source'? (Including parameter names)
should be able to specify 1.20.5 or 1.20.6 or latest snapshot and it should be able to run client from it, currently I am using MCP reborn, but it takes a while to update when minecraft updates

**Comment by Jab125** [comment]
This is not related to Fabric API at all.

Use Parchment mappings to get parameter names.
