### ISSUE TITLE
Suggestion: Separate mod folders for each game version 

### ISSUE THREAD

**Issue by MCgrant360** [FabricMC/fabric#3767]
I suggest that fabric creates a new mods folder for each game version. This way, you can install multiple versions of the game e.g. 1.13, 1.16, 1.20, 1.20.2, 1.20.4 and not have to move files around to launch the game. This will not only make updating easier because you can see all of your mods you need to download, but it will make going back a few versions easier, e.g. playing 1.20.4 but needing 1.20.1 for an outdated server, much easier.

**Comment by apple502j** [comment]
This messes up not just mods, but configs, etc. Using a third-party launcher is probably the better idea. Or, you could use the system properties for the loader. Either way, not in scope for Fabric API.

**Comment by haykam821** [comment]
This issue duplicates FabricMC/fabric-loader#181 as well.

**Comment by Daomephsta** [comment]
Doesn't the Minecraft installer for Fabric Loader already do this anyway?
I'm pretty sure it creates a new profile (with a different game directory) in the vanilla launcher unless you tell it not to.

**Comment by skycatminepokie** [comment]
> Doesn't the Minecraft installer for Fabric Loader already do this anyway? I'm pretty sure it creates a new profile (with a different game directory) in the vanilla launcher unless you tell it not to.

Profiles share .minecraft folders by default, so it would be different.
