### ISSUE TITLE
Fabric 1.4.8 build 157 1.14.4 crash

### ISSUE THREAD

**Issue by RacerIvan** [FabricMC/fabric#377]
Hi everyone, I came across a problem with Fabric, on startup - the game crashes, but version 0.3.7.111 works, here's the log -
[L] Minecraft Launcher [21;11] has initialized
[L] Running under TLauncher 1.112.4+develop Legacy
[L] Current machine: Windows 10 (10.0) x64, Java 1.8.0_181, 7648 MB RAM, 4x CPU
[L] Collecting info...
[L] Force update: false
[L] Selected version: fabric-loader-0.4.8+build.157-1.14.4
[L] Version sync info: VersionSyncInfo{id='fabric-loader-0.4.8+build.157-1.14.4',
local=CompleteVersionCompleteVersion[id=fabric-loader-0.4.8+build.157-1.14.4,jar=1.14.4,inheritsFrom=<null>,url=<null>,time=Mon Sep 23 14:45:57 EEST 2019,releaseTime=Fri Jul 19 12:25:47 EEST 2019,downloads={client=net.minecraft.launcher.updater.DownloadInfo@481c1a82, server=net.minecraft.launcher.updater.DownloadInfo@777a50aa},assetIndex=AssetIndexInfo[id=1.14,url=https://launchermeta.mojang.com/v1/packages/d6c94fad4f7a03a8e46083c023926515fc0e551e/1.14.json,sha1=d6c94fad4f7a03a8e46083c023926515fc0e551e,size=226753,totalSize=209234283,known=true],source=LOCAL_VERSION_REPO,list=net.minecraft.launcher.updater.LocalVersionList@5ac889da,libraries=(65 items)],
remote=null, isInstalled=true, hasRemote=false, isUpToDate=true}
[L] Selected account: PlainUser[username=Racer_Ivan,displayName=Racer_Ivan,uuid=d737558a-4936-3928-a26d-1518c9e1f15f,type=plain]
[L] Looking up libraries for ely
[L] Command: C:\Users\racer\AppData\Roaming\.tlauncher\jre\win64\bin\javaw.exe
[L] Root directory: C:\Users\racer\AppData\Roaming\.minecraft\
[L] Game directory: C:\Users\racer\AppData\Roaming\.minecraft\
[L] Options: OptionsFile[file=C:\Users\racer\AppData\Roaming\.minecraft\options.txt,fileExist=true,options={version=1976, autoJump=true, autoSuggestions=true, chatColors=true, chatLinks=true, chatLinksPrompt=true, enableVsync=false, entityShadows=true, forceUnicodeFont=true, discrete_mouse_scroll=false, invertYMouse=false, realmsNotifications=false, reducedDebugInfo=false, snooperEnabled=false, showSubtitles=false, touchscreen=false, fullscreen=true, bobView=false, mouseSensitivity=0.5, fov=0.0, gamma=1.0, renderDistance=8, guiScale=1, particles=1, maxFps=260, difficulty=0, fancyGraphics=false, ao=0, biomeBlendRadius=2, renderClouds=fast, resourcePacks=["vanilla","file/Classic Alternative 1.14 v6.1.zip"], incompatibleResourcePacks=[], lang=ru_ru, chatVisibility=0, chatOpacity=1.0, textBackgroundOpacity=0.5, backgroundForChatOnly=true, fullscreenResolution=1366x768@60:24, hideServerAddress=false, advancedItemTooltips=true, pauseOnLostFocus=false, overrideWidth=0, overrideHeight=0, heldItemTooltips=true, chatHeightFocused=1.0, chatHeightUnfocused=0.44366195797920227, chatScale=1.0, chatWidth=1.0, mipmapLevels=4, useNativeTransport=true, mainHand=right, attackIndicator=1, narrator=0, tutorialStep=none, mouseWheelSensitivity=1.0, rawMouseInput=true, glDebugVerbosity=1, key_key.attack=key.mouse.left, key_key.use=key.mouse.right, key_key.forward=key.keyboard.w, key_key.left=key.keyboard.a, key_key.back=key.keyboard.s, key_key.right=key.keyboard.d, key_key.jump=key.keyboard.space, key_key.sneak=key.keyboard.left.shift, key_key.sprint=key.keyboard.left.control, key_key.drop=key.keyboard.q, key_key.inventory=key.keyboard.e, key_key.chat=key.keyboard.t, key_key.playerlist=key.keyboard.tab, key_key.pickItem=key.mouse.middle, key_key.command=key.keyboard.slash, key_key.screenshot=key.keyboard.f2, key_key.togglePerspective=key.keyboard.f5, key_key.smoothCamera=key.keyboard.unknown, key_key.fullscreen=key.keyboard.f11, key_key.spectatorOutlines=key.keyboard.unknown, key_key.swapHands=key.keyboard.f, key_key.saveToolbarActivator=key.keyboard.unknown, key_key.loadToolbarActivator=key.keyboard.x, key_key.advancements=key.keyboard.l, key_key.hotbar.1=key.keyboard.1, key_key.hotbar.2=key.keyboard.2, key_key.hotbar.3=key.keyboard.3, key_key.hotbar.4=key.keyboard.4, key_key.hotbar.5=key.keyboard.5, key_key.hotbar.6=key.keyboard.6, key_key.hotbar.7=key.keyboard.7, key_key.hotbar.8=key.keyboard.8, key_key.hotbar.9=key.keyboard.9, soundCategory_master=0.50993377, soundCategory_music=0.0, soundCategory_record=1.0, soundCategory_weather=1.0, soundCategory_block=1.0, soundCategory_hostile=1.0, soundCategory_neutral=1.0, soundCategory_player=1.0, soundCategory_ambient=0.0, soundCategory_voice=1.0, modelPart_cape=true, modelPart_jacket=true, modelPart_left_sleeve=true, modelPart_right_sleeve=true, modelPart_left_pants_leg=true, modelPart_right_pants_leg=true, modelPart_hat=true}]
[L] Checking conditions...
[L] Comparing assets...
[L] Instant state on: AssetIndex.AssetObject[compressed=false,hash=e7133a7d4822e40f0abd716faa3a8f340362b8d7,size=13332,reconstruct=false]
[L] Compared assets in 363 ms
[L] Unpacking natives...
[L] Constructing process...
[L] Constructing classpath...
[L] Half command (characters are not escaped):
C:\Users\racer\AppData\Roaming\.tlauncher\jre\win64\bin\javaw.exe -XX:+UseG1GC -XX:ConcGCThreads=1 -XX:ParallelGCThreads=1 -Xmx4096M -Dfile.encoding=UTF-8 -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Djava.library.path=C:\Users\racer\AppData\Roaming\.minecraft\versions\fabric-loader-0.4.8+build.157-1.14.4\natives -Dminecraft.launcher.brand=java-minecraft-launcher -Dminecraft.launcher.version=1.6.84-j -cp C:\Users\racer\AppData\Roaming\.minecraft\libraries\net\fabricmc\tiny-mappings-parser\0.1.1.8\tiny-mappings-parser-0.1.1.8.jar;C:\Users\racer\AppData\Roaming\.minecraft\libraries\net\fabricmc\sponge-mixin\0.7.11.36\sponge-mixin-0.7.11.36.jar;C:\Users\racer\AppData\Roaming\.minecraft\libraries\net\fabricmc\tiny-remapper\0.1.0.33\tiny-remapper-0.1.0.33.jar;C:\Users\racer\AppData\Roaming\.minecraft\libraries\net\fabricmc\fabric-loader-sat4j\2.3.5.4\fabric-loader-sat4j-2.3.5.4.jar;C:\Users\racer\AppData\Roaming\.minecraft\libraries\com\google\jimfs\jimfs\1.1\jimfs-1.1.jar;C:\Users\racer\AppData\Roaming\.minecraft\libraries\org\ow2\asm\asm\7.1\asm-7.1.jar;C:\Users\racer\AppData\Roaming\.minecraft\libraries\org\ow2\asm\asm-analysis\7.1\asm-analysis-7.1.jar;C:\Users\racer\AppData\Roaming\.minecraft\libraries\org\ow2\asm\asm-commons\7.1\asm-commons-7.1.jar;C:\Users\racer\AppData\Roaming\.minecraft\libraries\org\ow2\asm\asm-tree\7.1\asm-tree-7.1.jar;C:\Users\racer\AppData\Roaming\.minecraft\libraries\org\ow2\asm\asm-util\7.1\asm-util-7.1.jar;C:\Users\racer\AppData\Roaming\.minecraft\libraries\com\google\guava\guava\21.0\guava-21.0.jar;C:\Users\racer\AppData\Roaming\.minecraft\libraries\net\fabricmc\intermediary\1.14.4\intermediary-1.14.4.jar;C:\Users\racer\AppData\Roaming\.minecraft\libraries\net\fabricmc\fabric-loader\0.4.8+build.157\fabric-loader-0.4.8+build.157.jar;C:\Users\racer\AppData\Roaming\.minecraft\libraries\oshi-project\oshi-core\1.1\oshi-core-1.1.jar;C:\Users\racer\AppData\Roaming\.minecraft\libraries\net\java\dev\jna\jna\4.4.0\jna-4.4.0.jar;C:\Users\racer\AppData\Roaming\.minecraft\libraries\net\java\dev\jna\platform\3.4.0\platform-3.4.0.jar;C:\Users\racer\AppData\Roaming\.minecraft\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar;C:\Users\racer\AppData\Roaming\.minecraft\libraries\com\mojang\javabridge\1.0.22\javabridge-1.0.22.jar;C:\Users\racer\AppData\Roaming\.minecraft\libraries\net\sf\jopt-simple\jopt-simple\5.0.3\jopt-simple-5.0.3.jar;C:\Users\racer\AppData\Roaming\.minecraft\libraries\io\netty\netty-all\4.1.25.Final\netty-all-4.1.25.Final.jar;C:\Users\racer\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-lang3\3.5\commons-lang3-3.5.jar;C:\Users\racer\AppData\Roaming\.minecraft\libraries\commons-io\commons-io\2.5\commons-io-2.5.jar;C:\Users\racer\AppData\Roaming\.minecraft\libraries\commons-codec\commons-codec\1.10\commons-codec-1.10.jar;C:\Users\racer\AppData\Roaming\.minecraft\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar;C:\Users\racer\AppData\Roaming\.minecraft\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar;C:\Users\racer\AppData\Roaming\.minecraft\libraries\com\mojang\brigadier\1.0.17\brigadier-1.0.17.jar;C:\Users\racer\AppData\Roaming\.minecraft\libraries\com\mojang\datafixerupper\2.0.24\datafixerupper-2.0.24.jar;C:\Users\racer\AppData\Roaming\.minecraft\libraries\com\google\code\gson\gson\2.8.0\gson-2.8.0.jar;C:\Users\racer\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar;C:\Users\racer\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar;C:\Users\racer\AppData\Roaming\.minecraft\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar;C:\Users\racer\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar;C:\Users\racer\AppData\Roaming\.minecraft\libraries\it\unimi\dsi\fastutil\8.2.1\fastutil-8.2.1.jar;C:\Users\racer\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-api\2.8.1\log4j-api-2.8.1.jar;C:\Users\racer\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-core\2.8.1\log4j-core-2.8.1.jar;C:\Users\racer\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\3.2.2\lwjgl-3.2.2.jar;C:\Users\racer\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-jemalloc\3.2.2\lwjgl-jemalloc-3.2.2.jar;C:\Users\racer\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-openal\3.2.2\lwjgl-openal-3.2.2.jar;C:\Users\racer\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-opengl\3.2.2\lwjgl-opengl-3.2.2.jar;C:\Users\racer\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-glfw\3.2.2\lwjgl-glfw-3.2.2.jar;C:\Users\racer\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-stb\3.2.2\lwjgl-stb-3.2.2.jar;C:\Users\racer\AppData\Roaming\.minecraft\libraries\com\mojang\text2speech\1.11.3\text2speech-1.11.3.jar;C:\Users\racer\AppData\Roaming\.minecraft\libraries\by\ely\authlib\1.5.25.1\authlib-1.5.25.1.jar;C:\Users\racer\AppData\Roaming\.minecraft\versions\fabric-loader-0.4.8+build.157-1.14.4\fabric-loader-0.4.8+build.157-1.14.4.jar net.fabricmc.loader.launch.knot.KnotClient --username Racer_Ivan --version fabric-loader-0.4.8+build.157-1.14.4 --gameDir C:\Users\racer\AppData\Roaming\.minecraft --assetsDir C:\Users\racer\AppData\Roaming\.minecraft\assets --assetIndex 1.14 --uuid d737558a49363928a26d1518c9e1f15f --accessToken [nothinginteresting] --userType legacy --versionType release --width 925 --height 530
[L] Launching Minecraft...
[L] Starting Minecraft fabric-loader-0.4.8+build.157-1.14.4
[L] Launching in: C:\Users\racer\AppData\Roaming\.minecraft
[L] Processing post-launch actions. Assist launch: true
===============================================================================================
[14:49:39] [main/INFO]: Loading for game Minecraft 1.14.4
Exception in thread "main" java.lang.RuntimeException: Failed to resolve mods!
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:147)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:120)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: net.fabricmc.loader.discovery.ModResolutionException: Could not resolve valid mod collection (at: modmenu requires {fabricloader @ [>=0.6.1]})
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:185)
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:508)
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:145)
	... 2 more
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97)
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81)
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401)
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:183)
	... 4 more
[L] Minecraft closed with exit code: 1 (0x1)
[L] Launcher stopped.

P.S Sorry for my english

**Comment by Juuxel** [comment]
> Caused by: net.fabricmc.loader.discovery.ModResolutionException: Could not resolve valid mod collection (at: modmenu requires {fabricloader @ [>=0.6.1]})

This is not a problem with Fabric. ModMenu needs a newer version of Fabric Loader (at least 0.6.1).

**Comment by modmuss50** [comment]
Yeah, update fabric loader.

**Comment by RacerIvan** [comment]
Thanks
