### ISSUE TITLE
Crash when Loading World in 1.15 latest snapshot

### ISSUE THREAD

**Issue by frqnny** [FabricMC/fabric#379]
here's my gradle.properties
minecraft_version=19w38b
yarn_mappings=19w38b+build.9
loader_version=0.6.2+build.166

#Fabric api
fabric_version=0.3.4+build.236-1.15
I get a crash when I try to load a world with the latest fabric api version. 
crash: https://pastebin.com/4fKG0z1R

**Comment by grondag** [comment]
Ah, I think is because I forgot to bump the patch number of the renderer API.  Bumped it for Fabric itself and indigo, but forgot the renderer API.

**Comment by grondag** [comment]
Yep, should be `fabric-renderer-api-v1-0.2.0+d2ac651a3c` but `fabric-renderer-api-v1-0.2.0+a5d709c33c` is loaded.

My mistake and I will fix the build but ~I do wish people would stop bundling Fabric API with mods.~ See next post.

**Comment by frqnny** [comment]
It was in a dev environment, with gradle runClient

**Comment by grondag** [comment]
Right, was just about to post that this looks like dev.  Even with updated patch numbers I still see problems in dev occasionally depending on how the maven POM looks for your library dependencies and how you include them.

If you explicitly exclude Fabric API from your dependencies that should be a reliable fix, like so:
```gradle
modImplementation ("io.github.cottonmc:Jankson-Fabric:${jankson_version}") {
    exclude group :"net.fabricmc.fabric-api"
} 
```

**Comment by grondag** [comment]
~Given that this is in dev, think we can hold off on bumping the patch numbers until after tomorrow's snapshot.~

Was going to bother me all night to have this remain broken.  Build 237 is up now but it may or may not fix your problem.
