### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by Ayutac** [FabricMC/fabric#3806]
I am running Minecraft on Linux (Xubuntu). I usually use Fabric (because it's better) for my mods, but recently I tried out running Forge because I'm helping developing a mod for both platforms. To my surprise Forge is much faster in world loading and saving than Fabric on my device, and apparently with ticking as well. Which is to say, everything works normally with Forge but on Fabric I am usually 100 to 1000 ticks behind at a time and world saving takes *minutes*. Makes modding for fabric a pita as well.

I would like to find out why Fabric is so slow on my device.

I will provide you with any data you deem necessary. Not sure if there are good benchmark methods somewhere I could use.

**Comment by modmuss50** [comment]
Really need a lot more infomation before this can be an issue, what mods are you using? Is this a dev env? A profile would be a start. A good starting point for profiling is to just use Minecraft's builtin profiler (`/jfr start` wait a bit, and then `/jfr stop`).

Until a specific cause has been found, and if that is indeed fabric then an issue is a good idea for now this is really a support request imo.
