### ISSUE TITLE
Method for getting the mining level of a block

### ISSUE THREAD

**Issue by Juuxel** [FabricMC/fabric#381]
Edit: current status as of tool attributes 1.1

> tool attribute 1.1 added a method to get it, however it is still in impl classes
> `ToolManagerImpl.entryNullable(block).getMiningLevel()`

<details>
<summary>Old description</summary>
Currently you have to do some mixin/reflection hacks on `ToolManager.EntryImpl` if you want to get the mining level of a block that uses `FabricBlockSettings.breakByTool(Tag, int)`, so a public method for doing that would be nice.
</details>

**Comment by i509VCB** [comment]
Did tool attributes v1.1 cover this?

**Comment by Juuxel** [comment]
I'll have to check. I know that tool attributes 1.0 didn't include this.

**Comment by shedaniel** [comment]
tool attribute 1.1 added a method to get it, however it is still in impl classes
`ToolManagerImpl.entryNullable(block).getMiningLevel()`

**Comment by apple502j** [comment]
Resolved by #1629
