### ISSUE TITLE
Latest update 0.99.3+1.20.6 broke HIDE_ATTRIBUTES ItemFlag

### ISSUE THREAD

**Issue by technorxseeee** [FabricMC/fabric#3812]
Title self-explanatory.
Before: 
![2024-05-30_13 14 58](https://github.com/FabricMC/fabric/assets/42143745/e754e090-2f0d-4519-aba6-8a75a3087645)
After:
![image](https://github.com/FabricMC/fabric/assets/42143745/047e5f19-8f96-4896-ad6c-63e88ee47ce7)

**Comment by modmuss50** [comment]
Hi, What do you mean by HIDE_ATTRIBUTES ItemFlag? Can you please provide steps to reproduce this please.

**Comment by technorxseeee** [comment]
Reproduce:
1. Go to any give command generator (e.g. https://www.gamergeeks.net/apps/minecraft/give-command-generator)
2. Set version to Snapshot Java
3. Attributes -> Display Attributes Hidden
4. Add Attribute
5. Copy command
6. Go in-game and execute
7. Compare between old and new version.

**Comment by modmuss50** [comment]
Thanks for reporting this, I have reverted the change. It will be fixed in the next version that is releasing now.
