### ISSUE TITLE
ModelLoadingPlugin$Context#resolveModel does not support non `inventory` ModelIdentifiers

### ISSUE THREAD

**Issue by ChrysanthCow** [FabricMC/fabric#3819]
This may be a regression with the new API, but I don't think you can handle non `#inventory` based model ids through `resolveModel` methods. 

This is a problem in my case, where I wish to register dynamic block models created by the user.

**Comment by PepperCode1** [comment]
`ModelResolver` never supported `ModelIdentifier` (`Identifier` + variant) models as that is not its goal (use `BlockStateResolver` or `ModelModifier.OnLoad` instead), so I assume you mean that models that are referenced in blockstate files are not received by `ModelResolver`s. The code should support this; can you provide the code that stopped working?

**Comment by ChrysanthCow** [comment]
Sorry for the long wait, I've noticed that my code for this wasn't even working in the first place, and I've since realised I was doing it wrong. I'll be marking this as invalid, and going with the intended methodology.
