### ISSUE TITLE
Assertion error when re-entering configuration.

### ISSUE THREAD

**Issue by Aspw-w** [FabricMC/fabric#3821]
Crashes when Fabric 1.20.6 (latest) is opened in idea and bungeecord world travel is performed
(For example: cubecraft)

**Comment by modmuss50** [comment]
Please can you provide a crash log?

**Comment by Aspw-w** [comment]
> Please can you provide a crash log?

[log.txt](https://github.com/user-attachments/files/15530468/log.txt)
[crashreport.txt](https://github.com/user-attachments/files/15530470/crashreport.txt)

**Comment by modmuss50** [comment]
Intresting thanks, can you try without any other mods such as viafabricplus? It seems to be happening when re-entering configuration, I might need to get setup to try and reproduce this.

**Comment by Aspw-w** [comment]
> Intresting thanks, can you try without any other mods such as viafabricplus? It seems to be happening when re-entering configuration, I might need to get setup to try and reproduce this.

I've already tried it, but I get the exact same error.
There is logs without any other mods

[crashreport.txt](https://github.com/user-attachments/files/15532509/crashreport.txt)
[latest.log](https://github.com/user-attachments/files/15532513/latest.log)
