### ISSUE TITLE
Mangrove Swamp should be in `c:is_dense_vegetation/overworld`

### ISSUE THREAD

**Issue by jacobsjo** [FabricMC/fabric#3823]
The `c:is_dense_vegetation/overworld` tag should include all overworld biomes that have dense vegatation.

Mangrove swamp has vegetation dense enough to significantly hinder travel through that biome. It is more dense than old growth birch forest and old growth spruce taiga, which are in the tag. So mangrove swamp should be part of the tag as well.

NeoForge issue: neoforged/NeoForge#1055

**Comment by TelepathicGrunt** [comment]
The c:is_taiga here should be minecraft:is_taiga <https://github.com/FabricMC/fabric/blob/6e5bbc4a94f0976be5d13c59c7ee2f6eb17e2487/fabric-convention-tags-v2/src/generated/resources/data/c/tags/worldgen/biome/is_tree/coniferous.json#L4>

**Comment by TelepathicGrunt** [comment]
Edit nvm on my last point. We have c:is_taiga which pulls from minecraft:is_taiga so it's fine
