### ISSUE TITLE
[1.21-pre3] Crash on first run after updating from pre1

### ISSUE THREAD

**Issue by kwpugh** [FabricMC/fabric#3828]
I do not think this crash is anything to do with my mod code

crash report:  https://gist.github.com/kwpugh/4b991550d733d05424d84ae3d644566a

**Comment by modmuss50** [comment]
Fix coming soon, I incorrectly assumed that FAPI would just work on the new version. It needs a small fix 👍

**Comment by modmuss50** [comment]
Fixed: https://github.com/FabricMC/fabric/releases/tag/0.99.5%2B1.21
