### ISSUE TITLE
ComponentMap to string Usable in minecraft commands

### ISSUE THREAD

**Issue by JoeTheOrangeCat** [FabricMC/fabric#3833]
I have a mod that lets me view NBT and reuse it, well now its broken because of the switch to Components, and I can find a good way to convert it to a string usable in the /give command. The default .toString give a weirdly formatted in an unhelpful way, I tried other things, but none of them worked well, any help?
![image](https://github.com/FabricMC/fabric/assets/110697200/91ed3d4f-fa1f-457a-a577-bc541b351aa8)

My main problem comes from when it just gives Literal or Wonky NBT looking stuff.

**Comment by apple502j** [comment]
Does not appear to be a Fabric API issue. Anyway, the format used in commands is `ComponentChanges.CODEC`.
