### ISSUE TITLE
Fabric launches and tells that fabric is missing

### ISSUE THREAD

**Issue by kienerxyzzy** [FabricMC/fabric#3842]
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Install fabric, version 0.80.0+1.20 or later.
	 - Replace 'Minecraft' (minecraft) 1.20.4 with any version between 1.20.5 (inclusive) and 1.20.6 (inclusive).
More details:
	 - Mod 'Copper Hopper' (copperhopper) 0.7.0+1.20.4 requires any version of fabric, which is missing!
	 - Mod 'Dispenser Configurator' (dispenser_configurator) 1.2.15 requires version 0.80.0+1.20 or later of fabric, which is missing!
	 - Mod 'Dispenser Configurator' (dispenser_configurator) 1.2.15 requires any version between 1.20.5 (inclusive) and 1.20.6 (inclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
![image](https://github.com/FabricMC/fabric/assets/109198154/0ec9ecd8-089d-4d01-8147-aed6e4a54350)

**Comment by kienerxyzzy** [comment]
I'll admit that I messed up the version, but the fact that fabric tells that it itself doesn't exist just makes absolutely no sense. pls fix.

**Comment by Jab125** [comment]
Fabric Loader and Fabric API are 2 completely separate things, `fabric`, in this case, refers to [Fabric API](https://modrinth.com/mod/fabric-api).
