### ISSUE TITLE
Fabric Version 0.100.0+1.20.6 Crashes in Minecraft

### ISSUE THREAD

**Issue by creatineghg** [FabricMC/fabric#3843]
When i start Minecraft with the new Fabric version and then click on the window minecraft crashes. When changing to the old fabric version it works just fine.
[Log.txt](https://github.com/user-attachments/files/15752980/Log.txt)

**Comment by apple502j** [comment]
Issue exists in owo-lib, not us.

**Comment by creatineghg** [comment]
ok
