### ISSUE TITLE
Impossible to add enchanted loot when modifying loot tables after 1.21

### ISSUE THREAD

**Issue by dayofpi** [FabricMC/fabric#3846]
The EnchantRandomlyLootFunction expects a `RegistryEntryList<Enchantment>` or a `WrapperLookup`, neither of which can be obtained with the current modify event.

**Comment by apple502j** [comment]
Ugh. Valid issue, guess I should fix it. The clock is ticking (almost 24h before release), however it should not be impossible. We'll pass the DRM, which functions as the wrapper.

**Comment by haykam821** [comment]
Is this issue solved by the introduction of the `fabric-loot-api-v3` module in #3903?
