### ISSUE TITLE
Game Crashes during piston activation

### ISSUE THREAD

**Issue by KingKennyboy** [FabricMC/fabric#3855]
The game crashes when trying to render a piston firing.

Error Code: -1
The game crashed whilst rendering block entity
Error: java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because the return value of "net.fabricmc.fabric.api.renderer.v1.RendererAccess.getRenderer()" is null

**Comment by Alex-Forrest2010** [comment]
Im having the same issue and if its useful its with both sticky and regular pistons, also it crashes all players (that are using the version of fabric API) games with the same error code

**Comment by apple502j** [comment]
Remove Sodium, or install Indium. (Not really our issue.)
