### ISSUE TITLE
[Bug][MC1.21] Entity Rendering Crash

### ISSUE THREAD

**Issue by nickkeane** [FabricMC/fabric#3857]
Crash occured with error:
Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because the return value of "net.fabricmc.fabric.api.renderer.v1.RendererAccess.getRenderer()" is null

Crash occurred while I was wandering around exploring the world.

MC Version: 1.21
Fabric Loader: 0.15.11
Fabric API: 0.100.1+1.21
Log: https://mclo.gs/VhvNCg7

OS: Windows 10 Enterprise 22H2
CPU: AMD Ryzen 9 5900HS
GPU: nVidia RTX 3070 Laptop
RAM: 16 GB

**Comment by PepperCode1** [comment]
Without Indium and with Sodium, Continuity will crash. Indium is not updated yet, but this is not Fabric API's problem.
