### ISSUE TITLE
Cant install Fabric Server with java 19

### ISSUE THREAD

**Issue by RandomGamerde** [FabricMC/fabric#3870]
Hello,
i tryed to install a Fabric Server with Java 19 installed and it gives me this Error:
RuntimeException: Error invoking MC server bundler: java.lang.UnsupportedClassVersionError: net/minecraft/bundler/Main<br>has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java<br>Runtime only recognizes class file versions up to 63.0

OS: Ubuntu

**Comment by modmuss50** [comment]
You must use Java 21 or later for the version of Minecraft that you are using.
