### ISSUE TITLE
(19w39a) EntityRendererRegistry hook is ineffective

### ISSUE THREAD

**Issue by Pyrofab** [FabricMC/fabric#389]
EntityRenderDispatcher used to register every renderer in its constructor, allowing Fabric API to simply hook the end of it to register modded renderers. 
In 19w39a, the EntityRenderDispatcher started actively checking that every entity type had an associated renderer. More specifically, if an entity type lacks a renderer, the constructor throws instead of returning. 
The result is that `EntityRendererRegistry#initialize` is never called, and the game will always crash if a mod adds an entity.

**Comment by grondag** [comment]
Fixed in ~~API 0.4~~

Update: er, I mean in the next 1.15 build, which will probably be 1.0.0
