### ISSUE TITLE
Issue with Java 24/Project Leyden

### ISSUE THREAD

**Issue by Cartrigger** [FabricMC/fabric#3890]
https://mclo.gs/EuQOO1k
Current crash with Fabric API, the loader works fine.

**Comment by Cartrigger** [comment]
https://github.com/SpongePowered/Mixin/issues/670

**Comment by zml2008** [comment]
As commented on the Mixin issue, there is no "Java 24" that exists yet -- the errors you see are because ASM cannot support a version that has not been finalized.

**Comment by modmuss50** [comment]
Yes, once there is a version of ASM for Java 24 we will update. FYI we havent updated to a Java 23 compatible version of ASM due to a bug that will be fixed in the next version.
