### ISSUE TITLE
[1.21] Crash when rendering falling sand

### ISSUE THREAD

**Issue by Creewie** [FabricMC/fabric#3891]
java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because the return value of "net.fabricmc.fabric.api.renderer.v1.RendererAccess.getRenderer()" is null

**Comment by NotRyken** [comment]
@Creewie install [Indium](https://modrinth.com/mod/indium)
