### ISSUE TITLE
[Convention Tags] Entries missing from certain tags/categories

### ISSUE THREAD

**Issue by Patbox** [FabricMC/fabric#3895]
- [ ] Maces are missing from c:tools/melee_weapons
- [ ] Flint and steel is missing from c:tools

**Comment by TelepathicGrunt** [comment]
Flint and steel is a weird one. It's like on border of tool and not. Where would the line be drawn of what is a tool? What about Name Tags or Lead? Would people have any negative experience if flint and steel was in Tools tag when compared to the other items in Tools tag?

**Comment by apple502j** [comment]
I believe a tool is something with a durability (excluding armor and perhaps weapons).

**Comment by Patbox** [comment]
Weapons are included in tools tag via inclusion of their tags. But yes, flint and steel is a tool in both looks and usecase, it's just not mining tool. But yeah, you can go with mc wiki definition for that https://minecraft.wiki/w/Tool

**Comment by TelepathicGrunt** [comment]
Should flint and steel only be in tools or should be there be a subcategory for it?
`c:tools/firestarter`?
