### ISSUE TITLE
Missing mod channel for client mod list

### ISSUE THREAD

**Issue by BurkenDev** [FabricMC/fabric#3915]
Fabric need a plugin channel that will send the currently client installed mods to the server.
This is very important in order to combat hacks and cheats on servers.

Please implement this asap.

**Comment by Benonardo** [comment]
Cheats would be able to bypass it trivially, and other mods usually add their own server communication. 
This just hurts the normal player having all their mods sent to any server they connect.

**Comment by modmuss50** [comment]
Yeah, this wont help combat hacks at all unfortunately. You cannot trust what the client says.
