### ISSUE TITLE
Crash upon Opening Creative Inventory Help (MC 1.21)

### ISSUE THREAD

**Issue by cymophic** [FabricMC/fabric#3917]
---- Minecraft Crash Report ----
// There are four lights!

Time: 2024-07-07 16:00:44
Description: Unexpected error

java.lang.IllegalStateException: Item group has no page
	at net.minecraft.class_1761.fabric_getPage(class_1761.java:1096)
	at net.minecraft.class_481.getPage(class_481.java:1214)
	at net.minecraft.class_481.isGroupVisible(class_481.java:1204)
	at net.minecraft.class_481.handler$bfl000$fabric-item-group-api-v1$setSelectedTab(class_481.java:1176)
	at net.minecraft.class_481.method_2466(class_481.java)
	at net.minecraft.class_481.method_25426(class_481.java:439)
	at net.minecraft.class_437.method_25423(class_437.java:309)
	at net.minecraft.class_310.method_1507(class_310.java:1143)
	at net.minecraft.class_490.method_25426(class_490.java:50)
	at net.minecraft.class_437.method_25423(class_437.java:309)
	at net.minecraft.class_310.method_1507(class_310.java:1143)
	at net.minecraft.class_310.method_1508(class_310.java:2068)
	at net.minecraft.class_310.method_1574(class_310.java:1938)
	at net.minecraft.class_310.method_1523(class_310.java:1246)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_1761.fabric_getPage(class_1761.java:1096)
	at net.minecraft.class_481.getPage(class_481.java:1214)
	at net.minecraft.class_481.isGroupVisible(class_481.java:1204)
	at net.minecraft.class_481.handler$bfl000$fabric-item-group-api-v1$setSelectedTab(class_481.java:1176)
	at net.minecraft.class_481.method_2466(class_481.java)
	at net.minecraft.class_481.method_25426(class_481.java:439)
	at net.minecraft.class_437.method_25423(class_437.java:309)
	at net.minecraft.class_310.method_1507(class_310.java:1143)
	at net.minecraft.class_490.method_25426(class_490.java:50)
	at net.minecraft.class_437.method_25423(class_437.java:309)
	at net.minecraft.class_310.method_1507(class_310.java:1143)
	at net.minecraft.class_310.method_1508(class_310.java:2068)

-- Uptime --
Details:
	JVM uptime: 117.069s
	Wall uptime: 103.811s
	High-res time: 96.921s
	Client ticks: 1637 ticks / 81.850s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2501)
	at net.minecraft.class_310.method_54580(class_310.java:949)
	at net.minecraft.class_310.method_1514(class_310.java:905)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['Cymophic'/49, l='ClientLevel', x=-1.96, y=73.00, z=4.75]]
	Chunk stats: 1024, 313
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,72,0), Section: (at 0,8,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 364 game time, 364 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 164

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, ambientsounds, appleskin, armorchroma, authme, azurelib, bettercommandblockui, betterf1, betterhurtcam, betterstats, betterthirdperson, blur, bridgingmod, capes, chat_heads, chatanimation, cherishedworlds, chunky, cicada, clean-debug, cloth-config, completedshieldfix, concentration, continuity, controlling, creativecore, damagenumbers, ding, distanthorizons, durabilityplus, dynamic_fps, eatinganimationid, elytrapitch, emi, emojitype, enhancedblockentities, entity_model_features, entity_texture_features, entityculling, essential, essential-container, essential-loader, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fallingleaves, firstperson, forgeconfigapiport, freecam, highlight, horsebuff, ichunutil, indium, interactic, iris, itemswapper, jade, jjelytraswap, justenoughbreeding, languagereload, leahs-immersive-thunder, lighty, lithium, midnightlib, modernfix, modmenu, morechathistory, motionblur, musicnotification, noisium, notebook, notenoughanimations, owo, particlerain, presencefootsteps, reeses-sodium-options, satin, scribble, searchables, serverpingerfixer, shulkerboxtooltip, simplehudenhanced, skinlayers3d, slotted_armor_hud, sodium, sounds, spyglass_improvements, talkbubbles, tcdcommons, ukulib, visuality, waveycapes, yet_another_config_lib_v3, continuity:default, continuity:glass_pane_culling_fix, armorchroma:alternative-icons, highlight:highlight_extended, minecraft:supporteatinganimation, presencefootsteps:default_sound_pack, musicnotification:dark_mode, file/Particles+V.1.3.1.zip, file/enchant icons colorless 1.21 v1.1.zip, file/animated-items-1_21 - 1_2.zip, file/RefinedEnchants_0.1.0.zip, file/Tools&Trims_0.1.0.zip, file/Expressive Fresh Moves v3.0.1.zip, file/FreshAnimations_v1.9.1.zip, file/VanillaTweaks_MC1.21.x.zip, file/Default-Dark-Mode-1.20.2+-2024.6.0.zip, file/qrafty's-capitalized-font.zip, file/cubic-sun-moon-vb1-7-4a.zip, itemswapper:default, Essential Assets, essential

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2241217552 bytes (2137 MiB) / 4596957184 bytes (4384 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 5
	Microarchitecture: Comet Lake
	Frequency (GHz): 2.90
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce GTX 1050
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 2048.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.5612
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MiB): 8192.00
	Memory slot #2 clockSpeed (GHz): 2.40
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MiB): 8192.00
	Memory slot #3 clockSpeed (GHz): 2.40
	Memory slot #3 type: DDR4
	Virtual memory max (MiB): 37481.55
	Virtual memory used (MiB): 19610.32
	Swap memory total (MiB): 4864.00
	Swap memory used (MiB): 108.66
	Space in storage for jna.tmpdir (MiB): available: 2815.80, total: 228366.56
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 2815.80, total: 228366.56
	Space in storage for io.netty.native.workdir (MiB): available: 2815.80, total: 228366.56
	Space in storage for java.io.tmpdir (MiB): available: 2815.80, total: 228366.56
	Space in storage for workdir (MiB): available: 2815.80, total: 228366.56
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		ambientsounds: AmbientSounds 6.0.2
		appleskin: AppleSkin 3.0.2+mc1.21
		armorchroma: Armor Chroma 1.2.8
		authme: Auth Me 8.0.0+1.21
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c90
		azurelib: AzureLib 2.3.4
		beautifiedchatclient: Beautified Chat Client 2.5
		bettercommandblockui: BetterCommandBlockUI 0.5.2
		betterf1: BetterF1 1.0
		betterhurtcam: BetterHurtCam 1.9.1+mc1.21
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a790
		betterstats: Better Statistics Screen 3.12-alpha.1+fabric-1.21
		betterthirdperson: Better Third Person 1.9.0
		blur: Blur+ (Fabric) 4.1.0
			midnightlib: MidnightLib 1.5.7
		bridgingmod: Bridging Mod 2.4.0+1.21
		capes: Capes 1.5.4+1.21
		chat_heads: Chat Heads 0.12.3
		chatanimation: ChatAnimation 1.0.6
			mixinextras: MixinExtras 0.3.6
		cherishedworlds: Cherished Worlds 10.0.0+1.21
		chunky: Chunky 1.4.16
		cicada: CICADA 0.8.0+1.21-and-above
		clean-debug: Clean F3 0.4.5
		cloth-config: Cloth Config v15 15.0.127
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 18.0.0.1
		collective: Collective 7.64
		completedshieldfix: Walksy's Complete Shield Fixes 1.0.2
		concentration: Concentration 1.1.3
		continuity: Continuity 3.0.0-beta.5+1.21
		controlling: Controlling 18.0.1
		creativecore: CreativeCore 2.11.34
			net_neoforged_bus: bus 7.2.0
		damagenumbers: Damage Numbers 1.4.1-fabric
		ding: Ding 1.5.0
		distanthorizons: Distant Horizons 2.1.2-a
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.10+e633f88390
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b559734490
		durabilityplus: DurabilityPlus 1.1.0
		dynamic_fps: Dynamic FPS 3.5.0-beta.3
			net_lostluma_battery: battery 1.0.0
		eatinganimationid: Eating Animation 1.21+1.9.72
		elementa: Elementa 649
		elytrapitch: Elytra Pitch 1.3.1
		emi: EMI 1.1.10+1.21+fabric
		emojitype: Emoji Type 2.2.5+1.21
		enhancedblockentities: Enhanced Block Entities 0.10.1+1.21
		entity_model_features: Entity Model Features 2.1.3
		entity_texture_features: Entity Texture Features 6.1.3
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling 1.6.6
		essential: Essential 1.3.2.8
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.2.3
		fabric-api: Fabric API 0.100.4+1.21
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.67+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.28+6fc22b99d1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.48+f71b366fd1
			fabric-command-api-v2: Fabric Command API (v2) 2.2.27+6a6dfa19d1
			fabric-commands-v0: Fabric Commands (v0) 0.2.65+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.14+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.15+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.3.2+78017270d1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.24+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.9+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.52+6573ed8cd1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.2+78017270d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.11+8f3583aed1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.11+6573ed8cd1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.0+ab7edbacd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.12+d1321076d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.10+65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.23+78017270d1
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.3.0+0ae0b97dd1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.6.5+48fb1586d1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.67+df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.70+df3654b3d1
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.4+5a8c785ed1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.2.1+d153f344d1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.1.5+78017270d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.80+b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.15+3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.12+6573ed8cd1
		fabric-language-kotlin: Fabric Language Kotlin 1.11.0+kotlin.2.0.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.24.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricloader: Fabric Loader 0.15.11
		fallingleaves: Falling Leaves 1.16.0
		ferritecore: FerriteCore 7.0.0
		firstperson: FirstPerson 2.4.3
		forgeconfigapiport: Forge Config API Port 21.0.1
			com_electronwill_night-config_core: core 3.7.4
			com_electronwill_night-config_toml: toml 3.7.4
		freecam: Freecam (Modrinth Edition) 1.3.0-beta1+mc1.21
		gjeb: GJEB (GammaJustExtremeBright) ${version}
		highlight: Highlight 3.0.0
			resourcefullib: Resourceful Lib 3.0.1
				com_teamresourceful_bytecodecs: bytecodecs 1.1.0
				com_teamresourceful_yabn: yabn 1.0.3
		horsebuff: HorseBuff 2.1.8
		ichunutil: iChunUtil 1.0.0
		indium: Indium 1.0.34+mc1.21
		interactic: Interactic 0.2.2+1.21
		iris: Iris 1.7.3+mc1.21
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		iseelava: I See Lava 1.0.1
		itemswapper: ItemSwapper 0.7.0
		jade: Jade 15.0.4+fabric
		java: OpenJDK 64-Bit Server VM 21
		jjelytraswap: Auto Elytra Swap 2.1
		justenoughbreeding: Just Enough Breeding 1.2.4
		languagereload: Language Reload 1.6.1+1.21
		leahs-immersive-thunder: Immersive Thunder 1.21+1.2.2
		lighty: Lighty 3.0.0-beta.3
		lithium: Lithium 0.12.7
		minecraft: Minecraft 1.21
		modelfix: Model Gap Fix 1.21-1.6
		modernfix: ModernFix 5.18.5+mc1.21
		modmenu: Mod Menu 11.0.1
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		morechathistory: More Chat History 1.3.1
		motionblur: Motion Blur 1.0.5+mc1.21
		mousetweaks: Mouse Tweaks 2.26
		mru: Mineblock's Repeated Utilities 0.4.4+1.21
			yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.21-fabric
				com_twelvemonkeys_common_common-image: common-image 3.10.0
				com_twelvemonkeys_common_common-io: common-io 3.10.0
				com_twelvemonkeys_common_common-lang: common-lang 3.10.0
				com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
				com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
				com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
				org_quiltmc_parsers_gson: gson 0.2.1
				org_quiltmc_parsers_json: json 0.2.1
		musicnotification: Music Notification 2.0.2
		no-resource-pack-warnings: No Resource Pack Warnings 1.3.0
		noisium: Noisium 2.2.0+mc1.21
		notebook: Notebook 4.0.2
		notenoughanimations: NotEnoughAnimations 1.7.4
		org_jetbrains_annotations: annotations 23.0.0
		owo: oωo 0.12.10+1.21
			blue_endless_jankson: jankson 1.2.2
			io_wispforest_endec: endec 0.1.0
			io_wispforest_endec_gson: gson 0.1.0
			io_wispforest_endec_jankson: jankson 0.1.0
			io_wispforest_endec_netty: netty 0.1.0
		particlerain: Particle Rain 2.1.0
		pickupnotifier: Pick Up Notifier 21.0.0
		presencefootsteps: Presence Footsteps 1.10.0+1.21
			kirin: Kirin UI 1.19.0+1.21
		puzzleslib: Puzzles Lib 21.0.4
		reeses-sodium-options: Reese's Sodium Options 1.7.2+mc1.21
		satin: Satin 2.0.0
		scribble: Scribble 1.1.0
		searchables: Searchables 1.0.1
		serverpingerfixer: Server Pinger Fixer 1.0.5
		shulkerboxtooltip: Shulker Box Tooltip 5.0.1+1.21
		simplehudenhanced: Simple Hud Enhanced 4.7.0
		skinlayers3d: 3d-Skin-Layers 1.6.6
		slotted_armor_hud: Slotted Armor HUD 1.2.5
		sodium: Sodium 0.5.11+mc1.21
		sounds: Sounds 1.0.0+1.21
		spyglass_improvements: Spyglass Improvements 1.5.3
		talkbubbles: Talk Bubbles 1.0.8
		tcdcommons: TCD Commons API 3.11.1+fabric-1.21
		ukulib: ukulib 1.3.0+1.21
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		universalcraft: UniversalCraft 342
		vigilance: Vigilance 297
		visuality: Visuality 0.7.4+1.21
		waveycapes: WaveyCapes 1.4.8
	Loaded Shaderpack: (off)
	Launched Version: fabric-loader-0.15.11-1.21
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: NVIDIA GeForce GTX 1050/PCIe/SSE2 GL version 3.2.0 NVIDIA 556.12, NVIDIA Corporation
	Window size: 1920x1081
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Render Distance: 8/8 chunks
	Resource Packs: vanilla, fabric, ambientsounds, appleskin (incompatible), armorchroma, authme, azurelib, bettercommandblockui, betterf1, betterhurtcam, betterstats, betterthirdperson, blur, bridgingmod, capes, chat_heads, chatanimation, cherishedworlds (incompatible), chunky, cicada, clean-debug, cloth-config, completedshieldfix, concentration (incompatible), continuity, controlling (incompatible), creativecore, damagenumbers, ding, distanthorizons (incompatible), durabilityplus, dynamic_fps, eatinganimationid, elytrapitch, emi, emojitype, enhancedblockentities, entity_model_features, entity_texture_features, entityculling, essential (incompatible), essential-container, essential-loader, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fallingleaves, firstperson, forgeconfigapiport, freecam, highlight, horsebuff, ichunutil, indium, interactic, iris, itemswapper, jade (incompatible), jjelytraswap, justenoughbreeding (incompatible), languagereload, leahs-immersive-thunder, lighty, lithium, midnightlib, modernfix (incompatible), modmenu, morechathistory, motionblur, musicnotification, noisium, notebook, notenoughanimations, owo, particlerain, presencefootsteps, reeses-sodium-options, satin, scribble, searchables (incompatible), serverpingerfixer, shulkerboxtooltip, simplehudenhanced, skinlayers3d, slotted_armor_hud, sodium, sounds, spyglass_improvements, talkbubbles, tcdcommons, ukulib, visuality, waveycapes, yet_another_config_lib_v3 (incompatible), continuity:default, continuity:glass_pane_culling_fix, armorchroma:alternative-icons (incompatible), highlight:highlight_extended (incompatible), minecraft:supporteatinganimation, presencefootsteps:default_sound_pack, musicnotification:dark_mode, file/Particles+V.1.3.1.zip, file/enchant icons colorless 1.21 v1.1.zip, file/animated-items-1_21 - 1_2.zip, file/RefinedEnchants_0.1.0.zip, file/Tools&Trims_0.1.0.zip, file/Expressive Fresh Moves v3.0.1.zip, file/FreshAnimations_v1.9.1.zip, file/VanillaTweaks_MC1.21.x.zip, file/Default-Dark-Mode-1.20.2+-2024.6.0.zip, file/qrafty's-capitalized-font.zip, file/cubic-sun-moon-vb1-7-4a.zip (incompatible), itemswapper:default
	Current Language: en_us
	Locale: en_US
	System encoding: Cp1252
	File encoding: UTF-8
	CPU: 16x Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['Cymophic'/49, l='ServerLevel[Test]', x=-1.96, y=73.00, z=4.75]]
	Active Data Packs: vanilla, fabric, collective, fabric-convention-tags-v2, sounds, spyglass_improvements
	Available Data Packs: bundle, collective, fabric, fabric-convention-tags-v2, sounds, spyglass_improvements, trade_rebalance, vanilla
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: -3952778547834275336

**Comment by apple502j** [comment]
@cymophic One question, does this happen with just Fabric API? Are there any other mods you need to use?

**Comment by JustAPotota** [comment]
Looks like this issue on EMI’s repo: https://github.com/emilyploszaj/emi/issues/602
