### ISSUE TITLE
[1.21] Boat Hitbox stacking bug

### ISSUE THREAD

**Issue by jackie4289** [FabricMC/fabric#3948]
Hi, has anyone faced the issue when placing a boat on another one causes the top boat to slide off on 1.21 fabric servers?

Its kinda hard to explain so heres a video of it happening, this only happens when the chunk is not loaded for a while (ex. leaving server and opening a single player world for abt 4 minutes, then rejoining server)  or sometimes when the server reboots: https://cdn.discordapp.com/attachments/699511817696706642/1262918035682103296/Untitled.mov?ex=66985793&is=66970613&hm=2b249e800312199f8fe5bd85bb3efa7cf871d4773b05dda76c5bb4341fe4dfde&

the boats are stacked like this...
![image](https://github.com/user-attachments/assets/16025d70-b87c-47a5-9b5a-735694b1f7f4)

these are the only mods server side
![image](https://github.com/user-attachments/assets/29d21501-8891-4184-8e33-274337a028fd)

This farm is based on this design by Rays works: https://www.youtube.com/watch?v=sT4noYO1xUE&

Console log: [04:15:58] [main/INFO]: Loading Minecraft 1.21 with Fabric Loader 0.15.11
[04:15:58] [main/INFO]: Loading 41 mods:
	- fabric-api 0.100.6+1.21
	   |-- fabric-api-base 0.4.42+6573ed8cd1
	   |-- fabric-api-lookup-api-v1 1.6.67+b5597344d1
	   |-- fabric-biome-api-v1 13.0.28+6fc22b99d1
	   |-- fabric-block-api-v1 1.0.22+0af3f5a7d1
	   |-- fabric-block-view-api-v2 1.0.10+6573ed8cd1
	   |-- fabric-blockrenderlayer-v1 1.1.52+0af3f5a7d1
	   |-- fabric-client-tags-api-v1 1.1.15+6573ed8cd1
	   |-- fabric-command-api-v1 1.2.49+f71b366fd1
	   |-- fabric-command-api-v2 2.2.28+6ced4dd9d1
	   |-- fabric-commands-v0 0.2.66+df3654b3d1
	   |-- fabric-content-registries-v0 8.0.14+b5597344d1
	   |-- fabric-convention-tags-v1 2.0.17+7f945d5bd1
	   |-- fabric-convention-tags-v2 2.4.1+86024ea6d1
	   |-- fabric-crash-report-info-v1 0.2.29+0af3f5a7d1
	   |-- fabric-data-attachment-api-v1 1.1.24+6a6dfa19d1
	   |-- fabric-data-generation-api-v1 20.2.11+16c4ae25d1
	   |-- fabric-dimensions-v1 4.0.0+6fc22b99d1
	   |-- fabric-entity-events-v1 1.6.12+6fc22b99d1
	   |-- fabric-events-interaction-v0 0.7.10+e633f883d1
	   |-- fabric-game-rule-api-v1 1.0.53+6ced4dd9d1
	   |-- fabric-item-api-v1 11.0.0+afdfc921d1
	   |-- fabric-item-group-api-v1 4.1.2+78017270d1
	   |-- fabric-key-binding-api-v1 1.0.47+0af3f5a7d1
	   |-- fabric-keybindings-v0 0.2.45+df3654b3d1
	   |-- fabric-lifecycle-events-v1 2.3.11+8f3583aed1
	   |-- fabric-loot-api-v2 3.0.12+3f89f5a5d1
	   |-- fabric-loot-api-v3 1.0.0+3f89f5a5d1
	   |-- fabric-message-api-v1 6.0.13+6573ed8cd1
	   |-- fabric-model-loading-api-v1 2.0.0+fe474d6bd1
	   |-- fabric-networking-api-v1 4.2.0+ab7edbacd1
	   |-- fabric-object-builder-api-v1 15.1.12+d1321076d1
	   |-- fabric-particles-v1 4.0.2+6573ed8cd1
	   |-- fabric-recipe-api-v1 5.0.10+65089712d1
	   |-- fabric-registry-sync-v0 5.0.24+6ced4dd9d1
	   |-- fabric-renderer-api-v1 3.3.0+0ae0b97dd1
	   |-- fabric-renderer-indigo 1.6.5+48fb1586d1
	   |-- fabric-renderer-registries-v1 3.2.67+df3654b3d1
	   |-- fabric-rendering-data-attachment-v1 0.3.48+73761d2ed1
	   |-- fabric-rendering-fluids-v1 3.1.6+b5597344d1
	   |-- fabric-rendering-v0 1.1.70+df3654b3d1
	   |-- fabric-rendering-v1 5.0.4+5a8c785ed1
	   |-- fabric-resource-conditions-api-v1 4.2.1+d153f344d1
	   |-- fabric-resource-loader-v0 1.1.5+78017270d1
	   |-- fabric-screen-api-v1 2.0.24+b5597344d1
	   |-- fabric-screen-handler-api-v1 1.3.81+b5597344d1
	   |-- fabric-sound-api-v1 1.0.23+6573ed8cd1
	   |-- fabric-transfer-api-v1 5.1.15+3dccd343d1
	   \-- fabric-transitive-access-wideners-v1 6.0.12+6573ed8cd1
	- fabricloader 0.15.11
	   \-- mixinextras 0.3.5
	- java 21
	- minecraft 1.21

**Comment by apple502j** [comment]
Does this appear like that in a vanilla client as well?

**Comment by jackie4289** [comment]
YES! it seems it does the same thing on vanilla as well. But only for servers tho since it works fine in single player

**Comment by apple502j** [comment]
Ah yes, typical server-client desync. :mojank:
