### ISSUE TITLE
Should `c:tools/melee_weapon` contain Hoes, Pickaxes, and Shovels? (Maybe Trident too)

### ISSUE THREAD

**Issue by TelepathicGrunt** [FabricMC/fabric#3949]
Someone brought up that the melee weapon tag inherited from Fabric API's past only contains Swords, Axes and Maces by default.
https://github.com/FabricMC/fabric/blob/1.21/fabric-convention-tags-v2/src/generated/resources/data/c/tags/item/tools/melee_weapon.json

Should this be changed to also have Hoes, Shovels, and Pickaxes? Specifically, any tool that has an ATTACK_DAMAGE attribute? (Maybe paired with ATTACK_SPEED attribute too?) Might also mean we should add Trident to it as it can be used both ranged and melee. 

If not, what would be a better way to describe this tag to someone to make it clear that only Swords, Axes, and Maces belong in this tag? Like weapons that are a viable melee weapon where being up close with physical attacks is the main attacking method as oppose to throwing or attacking being a weak secondary use like shovels.

Neo: https://github.com/neoforged/NeoForge/issues/1327

**Comment by OroArmor** [comment]
Trident for sure. You can enchant it with sharpness.

**Comment by apple502j** [comment]
> Trident for sure. You can enchant it with sharpness.

@OroArmor You sure? Trident has Impaling, but not Sharpness.

**Comment by OroArmor** [comment]
Huh fairly sure you could. Saw it in game recently, but double checking the code it doesn't look like it.

**Comment by TelepathicGrunt** [comment]
Yeah sharpness only applies to items that are in the sharp weapon tag here: https://github.com/misode/mcmeta/blob/data-json/data/minecraft/tags/item/enchantable/sharp_weapon.json
