### ISSUE TITLE
Crafting recipes randomly don't unlock on SERVERS, only common denominator is fabric modloader/api

### ISSUE THREAD

**Issue by winterdrake** [FabricMC/fabric#395]
This is going to be a difficult bug to explain because I don't have specific steps to recreate it.

I just started my second server today, with a brand new fabric modpack and no commonality to the last server I ran a while ago. However, both servers rarely had an issue where crafting recipies would not be unlocked for players unless we used commands to unlock them manually. The most common recipe that was locked was torches, both in the new server and the old server, there were times in which a player would try to craft torches but there would be no output to the recipie. You could also search "torch" in the recipe book and nothing would appear. 

Has anyone else encountered a bug like this when running a fabric server? I'm almost certain it must be a fabric issue

**Comment by liach** [comment]
By default, the game rule `doLimitedCrafting` should be false. Something should be messing up with your game rule.

**Comment by winterdrake** [comment]
Weird, I don't know what mod must have enabled that, but now that I know it's a gamerule, I can fix it! Thank you!!
