### ISSUE TITLE
After Brewing Potion Crash [1.21]

### ISSUE THREAD

**Issue by JaaiDead** [FabricMC/fabric#3950]
minecraft_version=1.21
yarn_mappings=1.21+build.9
 @loader_version=0.15.11

Fabric API
fabric_version=0.100.7+1.21

Setps To Reproduce My Issue : 
Setp 1 : Make a Custom Potion Mod in Fabric for the latest version (1.21).
Step 2 : Register the potion following fabric docs .
Setp 3 : Brewing The Potion In a single player world which should lead to [Server thread/ERROR] Failed to save chunk -1,-2. 
Step 4: Break The Brewing Stand Block with the custom potion in it to crash both server and client.
Referance : 
[Discord - 1 ](https://discord.com/channels/507304429255393322/507982478276034570/1263178447874818128)
[Discord - 2 ](https://discord.com/channels/507304429255393322/507982478276034570/1263177864023642267)
[Crash Log](https://pastebin.com/8AKZqa1P)

**Comment by apple502j** [comment]
It appears you are constructing new instance of RegistryEntry; you should be looking them up from `Registries.POTION` instead,
