### ISSUE TITLE
I want to know how to run spiget

### ISSUE THREAD

**Issue by wuming123** [FabricMC/fabric#396]
Vanilla servers have too little functionality. I want to run this mod on spigot or sponge

How can I do it, please?

**Comment by modmuss50** [comment]
There is an experimetal branch of fabric-loader that was working towards this, its about 50-75% done, but it does need some more work.

There were a few issues that would need to be sloved such as allowing modded blocks to be placed as the bukkit api has no idea of them currenly. If someone is intrested in working on it more we could sort that out, but its not something that is currenly been looked at by anyone as far as I know.
