### ISSUE TITLE
Occasional ConcurrentModificationException when loading datapacks

### ISSUE THREAD

**Issue by xllifi** [FabricMC/fabric#3969]
**Description:**
Only happens when Fabric API is present. 50 launches without Fabric API mod were all successful.
This doesn't occur on every load. That's why I've written a node.js script that helped me debug this behavior: https://hst.sh/siloravisa.js

**Relevant info:**
Dungeons and Taverns: https://modrinth.com/datapack/dungeons-and-taverns
Log: https://hst.sh/aluripatij.log

**Using:**
Java Temurin 21.0.2.13
Loader 0.15.11
Minecraft 1.21
Fabric API 0.100.7+1.21
Dungeons and Taverns 4.3

**Reproduction:**
1. Add Fabric API to `mods`, add Dungeons and Taverns as either mod or datapack
2. Run the server multiple times. Either using a script or manually

**Comment by davepusey** [comment]
Been seeing exactly the same problem on a small community server I admin.
We do a daily auto-restart, and every ~10 days it takes two attempts because the first attempt fails with this error.

We don't even have "Dungeons and Taverns", just a couple of basic mods, plus a bunch of the Vanilla Tweaks datapacks.

Log file from last night...

[2024-07-28-3.log](https://github.com/user-attachments/files/16413104/2024-07-28-3.log)

**Comment by xllifi** [comment]
> Been seeing exactly the same problem on a small community server I admin. We do a daily auto-restart, and every ~10 days it takes two attempts because the first attempt fails with this error.

For now you can build Fabric API from [apple502j's fork](https://github.com/apple502j/fabric/tree/reg-sync/concurrent-attribute-access) and use it for your server. I did this and tested with 50 launches, not a single crash.

Here's my build for 1.21 if you don't want to do it yourself (remove `.zip` and use the file as a replacement for Fabric API):
[fabric-api-0.100.7+local-unknown.jar.zip](https://github.com/user-attachments/files/16413839/fabric-api-0.100.7%2Blocal-unknown.jar.zip)
You should totally build it yourself though.

**Comment by modmuss50** [comment]
Seems like a few people are having this crash suddenly, ill merge and release the fix shortly. I was going to wait until the next feature release, but it seems more important. Please do make sure to report issues as you as you see them, they cannot be fixed if we dont know about them.

**Comment by xllifi** [comment]
> Seems like a few people are having this crash suddenly, 

I don't think that's the case, more probable is that this issue is now searchable (at least on Fabric discord), so people don't have to go through all of their mods just to find out that the last suspect, Fabric API, is guilty.

**Comment by davepusey** [comment]
To be honest, I was still investigating it is a datapack issue, not a Fabric/mod issue. It was only when looking for something else that I came across this report and had the a-ha moment.
