### ISSUE TITLE
Fabric crashes on world launch

### ISSUE THREAD

**Issue by agmass** [FabricMC/fabric#397]
![Annotation 2019-10-04 194823](https://user-images.githubusercontent.com/56167347/66221395-ed9b8a80-e6df-11e9-8a3c-1254815a4415.png)
when i try to open Hypixel, this happens.
Mods:
optifabric, replaymod, orderly, fabric api

**Comment by coderbot16** [comment]
Could you post a full log, and if present, a crash report? While I would guess that this is an intermittent conflict between OptiFine and Orderly we unfortunately cannot help you any more without more information.

**Comment by agmass** [comment]
Okay. ill remove orderly.

**Comment by Prospector** [comment]
Is this still an issue for you?

**Comment by uiytt** [comment]
There was no response on this since 5 October 2019.
And it's terribly likely that he is never going to do so
Can someone close this ?
