### ISSUE TITLE
Fabric doesn't follow symlinks when looking for mods

### ISSUE THREAD

**Issue by ajloveslily14** [FabricMC/fabric#399]
I run two different servers that use the same mods, one is creative one survival. I wanted to have just one mods folder for the both of them and use a symlink in the game directories linking to the same directory located elsewhere, however upon doing so and launching the server, no mods are found as fabric doesn't seem to follow symbolic links for directories.

**Comment by i509VCB** [comment]
I think this issue would be more related to fabric-loader, could you create an issue over there if this till occurs
