### ISSUE TITLE
Network Protocol Error when joining Hypixel

### ISSUE THREAD

**Issue by AzureAaron** [FabricMC/fabric#3993]
After updating to Fabric API 0.101.0 attempting to join Hypixel results in my client being kicked because of a Network Protocol Error related to registries, downgrading to 0.100.8 fixes the issue.

Here's the Network Protocol Error Report: https://mclo.gs/ADMTl1z
Regular Log: https://mclo.gs/rf4O2dJ

**Comment by modmuss50** [comment]
Fixed, https://github.com/FabricMC/fabric/pull/3994

Many thanks for the quick report.
