### ISSUE TITLE
[1.21 — v0.101.0] Mod compatibility errors with Indium and Sodium crashes upon loading world

### ISSUE THREAD

**Issue by ADVENTdev** [FabricMC/fabric#3995]
Hi, I [unintentionally] updated to the beta uploaded last night (v0.101.0) and when I tried loading into my world, my game crashed to desktop. I just wanted to let you know that happens, and that I do not have problems with this on the earlier stable release version (v0.100.8). I do not know if this is something that you Fabric API devs can fix or if this is a problem for Indium/Sodium to fix, but I am reporting this crash and attaching my log regardless since I noticed it when I updated your mod.

[2024-08-04-2.log](https://github.com/user-attachments/files/16488644/2024-08-04-2.log)

**Comment by modmuss50** [comment]
This is an Indium issue as they use internal functions from Fabric API that changed.
