### ISSUE TITLE
Game Crash When Pondering in AOF Orion

### ISSUE THREAD

**Issue by Kira076** [FabricMC/fabric#3996]
Client crash during pondering (Create mod) a millstone.

This was originally reported in [Create's Issue #4593](https://github.com/Creators-of-Create/Create/issues/4593#issue-1640954537). It was advised there to open an issue here if this persists (See [IThundxr's comment](https://github.com/Creators-of-Create/Create/issues/4593#issuecomment-2098404352)).

The error is:
Description: Ticking screen

java.lang.ClassCastException: class com.simibubi.create.foundation.ponder.PonderWorld cannot be cast to class net.minecraft.class_2791 (com.simibubi.create.foundation.ponder.PonderWorld and net.minecraft.class_2791 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @59ec2012)

[crash-2024-08-04_15.42.12-client.txt](https://github.com/user-attachments/files/16488730/crash-2024-08-04_15.42.12-client.txt)

### Reproduction Steps
1) Running AOF Orion
2) Open inventory and search for Create millstone
3) Hold W to ponder
4) Allow to play for a few seconds
5) Game crashes

### Details
OS: Windows 10
Minecraft: 1.19.2
Fabric: 0.14.17
Fabric API: 0.75.1+1.19.2
Java: 17.0.12 (OpenJDK)

**Comment by PepperCode1** [comment]
IThundxr meant the Create Fabric repository, not the Fabric API repository. https://github.com/Fabricators-of-Create/Create
