### ISSUE TITLE
After update Bedrock/Geyser clients cannot join fabric servers

### ISSUE THREAD

**Issue by cr-gomezm** [FabricMC/fabric#3998]
Hello, early this morning, I updated all my FabricMC server mods, including Fabric API. 

A bunch of users that connect using Bedrock client through GeyserMC reported that the server was returning a message requiring them to instal Fabric loader or Fabric API.

I think the change that triggered the issue is this one:

![image](https://github.com/user-attachments/assets/894c8355-eb7a-433a-bf3a-ee8b0ca1dcb9)

Does this represent a real issue or is something that should be fixed on Geyser's side?

Thx!!!!

**Comment by modmuss50** [comment]
What mods do you have on the server? This should only happen if one of your mods is adding an entry to a synced registry.

Can you join the server with only Fabric API installed on Java edition?

**Comment by modmuss50** [comment]
FYI: I have reverted the changes to limit distruption and plan to bring them back in 1.21.1. However there are still likely issues with your server setup, that should ideally be fixed. Id be happy and intrested to help figure out what is going on.

**Comment by cr-gomezm** [comment]
Hello modmuss, I really appreciate your help and your quick response.

[mc-server-load-modlist.txt](https://github.com/user-attachments/files/16494888/mc-server-load-modlist.txt)

Attached you will find the modlist, as printed by server stdout while starting.

MC Server: 1.21
Fabric Server: 1.0.1
Fabric Loader: 0.15.11

The only mod that I am aware of and I have already planned to remove is "Waystones" as it causes disruption with bedrock players (but I need to wait till World's reset to avoid disruption with my users' progress), actually every player, Java or Bedrock can connect without issues, apart of those that are already known and acknowledged by Geyser's Team.

I actually run the server inside a "containerd" instance under Windows, if you want me to test something I can do it, just need to deploy a copy of my PRD server into Testing.

**Comment by modmuss50** [comment]
Thanks for getting back, so yes Waystones would have been causing the problem here as it adds a block, this gets synced to the client on login. Without this mod installed on a Fabric API client you would not be able to connect. It was an oversight that a fabric server would allow vanilla (and in your case Bedrock) clients to join with this mod installed. This was what the change we made fixed.

When we bring this back in 1.21.1 we will try to improve the messaging to point to the exact mod causing the issue.
