### ISSUE TITLE
Crashes on all three current beta releases of Fabric API when rendering stripped spruce logs (I think)

### ISSUE THREAD

**Issue by Tom1817** [FabricMC/fabric#4001]
Hello, I would like to report what looks like an identical/near-identical crash when loading into a world where stripped spruce logs are present. I have tested all three beta releases without any changes to mods/configs/java/anything and the crashes occur each time

With Fabric API 0.101.2+1.21 - [crash-2024-08-05_16.40.17-client.txt](https://github.com/user-attachments/files/16500041/crash-2024-08-05_16.40.17-client.txt)

With Fabric API 0.101.1+1.21 - [crash-2024-08-05_16.54.18-client.txt](https://github.com/user-attachments/files/16500053/crash-2024-08-05_16.54.18-client.txt)

With Fabric API 0.101.0+1.21 - [crash-2024-08-05_16.55.41-client.txt](https://github.com/user-attachments/files/16500062/crash-2024-08-05_16.55.41-client.txt)

The crashes look to be identical to me although I'm not experienced with looking at crash logs. Please let me know if there's anything else I can do

**Comment by Lolothepro** [comment]
Caused by Indium

**Comment by Tom1817** [comment]
Ah yes, thank you. I just tested with the latest API 0.101.2 without indium and it works just fine. Seems it's been reported on their issue tracker already

[https://github.com/comp500/Indium/issues/324](https://github.com/comp500/Indium/issues/324)

Thank you :)
