### ISSUE TITLE
doLimitedCrafting stuck at true

### ISSUE THREAD

**Issue by winterdrake** [FabricMC/fabric#401]
Hi,
My server has been having some issues with users not being able to craft basic items like torches. We've traced this to the gamerule doLimitedCrafting, which seems to be eternally stuck at true. I can make it false in console, but if I then check its value again, it says it's true.

This has happened on two servers for me with completely different mods installed. I've contacted my server provider and they've never heard of this issue and suspect fabric.

Is there any reason that doLimitedCrafting would keep being reset to true automatically?

fabric-loader-0.6.2+build.166-1.14.4
fabric-api-0.3.3+build.234-1.14

**Comment by i509VCB** [comment]
If you can get me a log detailing this issue you can re-open this issue.

Since you say crafting fails, I likely thing there is something to do with the resource loader.
