### ISSUE TITLE
[Crash] Hard crash on Fabric API 0.102.0

### ISSUE THREAD

**Issue by Shadowdane** [FabricMC/fabric#4016]
Updated Fabric API from 0.100.8 to 0.102.0 on Minecraft 1.21 and it instantly hard locks my client on loading into a modded world.  It basically rendering about 1/2 the screen then crashes.

Crash Log:  https://mclo.gs/2Ley5Pd

Rolling back to Fabric API 0.100.8 fixes the issue and my world loads normally.     I'm not sure if this is an API bug or a bug in another mod, but rolling back to the older API version fixes this crash.

**Comment by zed1ker** [comment]
Identical error

**Comment by dmstewart42** [comment]
See [comp500/Indium#324](https://github.com/comp500/Indium/issues/324)
