### ISSUE TITLE
Installer Crash

### ISSUE THREAD

**Issue by HerrWolke** [FabricMC/fabric#402]
So, I if I try to open the fabric installer I get a pop-up message that says "Java Se binary is not responding!". What should I do?

![BUG](https://user-images.githubusercontent.com/49591248/66717593-093b1b00-eddb-11e9-9bde-a432df776f5c.PNG)

**Comment by KirppuAapo** [comment]
Probably uninstall java and install back

**Comment by HerrWolke** [comment]
Ok thx I will try it
