### ISSUE TITLE
Unable to fit 2176652 into 3 Server Error

### ISSUE THREAD

**Issue by houlss** [FabricMC/fabric#4066]
I have a 1.20.1 Fabric Server with around 300 mods. The server has 16GB of Ram and Ryzen 7 7800x3d as the CPU (It's running on my own pc). The server is also LAN.

First I tried to just put every single mod in the modpack in the server's mods but this problem occured more than once. Then I started adding every mod one by one, running the server and game and check if I can join. I have noticed that every single mod that caused this problem was always a furniture mod.

The thing is, I don't wanna remove my furniture mods and some of the mods that cause the problem used to work perfectly on my old server. I can also create a singleplayer world with the same mods, but when I try to do it on the server I always get this error (Unable to fit 2176652 into 3) When someone tries to join.

I really need to find a way to fix this because I can't take out the furniture mods, nor there are much alternatives to the mods I want to use. What could the problem be? Is there a way to fix it?
![image](https://github.com/user-attachments/assets/cc235cce-5435-45df-be06-7156aa3094fe)
I can provide if anything else is needed. Thanks!

**Comment by apple502j** [comment]
Unfortunately, if you have a mod that doesn't work, the natural thing to do is to remove that mod. Maybe contact its author instead...

**Comment by houlss** [comment]
> 👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.

Sorry, will do that next time I didn't know. Also deleting Krypton fixed everything. If anyone else is having the same problem just so yk
