### ISSUE TITLE
Gradle build fails for no reason!

### ISSUE THREAD

**Issue by DRD2k8** [FabricMC/fabric#4071]
I tried rebuilding the project a HUNDRED times and gradle fails after 24 seconds and says "(Mod Directory)\build\loom-cache\remapped_working\loom_mappings_1_20_1_layered_hash_2198_v2.net.fabricmc.fabric-api-fabric-api-0.92.2+1.20.1.jar The process cannot access the file because it is being used by another process"! Why is this happening?

**Comment by WhyMyMilkChunky** [comment]
having same issue
