### ISSUE TITLE
FabricToolTags.X.contains(item) returns wrong value when player is on a server

### ISSUE THREAD

**Issue by dexman545** [FabricMC/fabric#408]
Fabric for MC 1.14.4

When in singleplayer, FabricToolTags.AXES.contains(item) (same for picks, etc.) correctly identifies if the item in question has the tag or not. This is not the case when connected to a dedicated (vanilla) server (unable to test fabric server at this time), it returns false for all tools.

~~Should also add that it returns false for wooden pickaxes outside of a dev environment in singleplayer.~~

**Comment by liach** [comment]
the tags are defined by servers. and since the vanilla server does not have fabric, don't expect client-side mods to work on the server (just like how hypixel won't have modded blocks if you join hypixel with an ftb infinity client)

**Comment by dexman545** [comment]
Shouldn't clients have knowledge of what tools have those tags, at least the vanilla ones?

**Comment by liach** [comment]
tool tags are not in vanilla lol
