### ISSUE TITLE
Crashed before even starting.

### ISSUE THREAD

**Issue by Dracathio** [FabricMC/fabric#411]
No clue what you did wrong, but you did something wrong in your coding.

Neither .net nor .jar work when installing into the vanilla client.

The game crashed whilst initializing game
Error: net.fabricmc.loader.api.EntrypointException: Could not look up entries for entrypoint client!

**Comment by SDUBZ** [comment]
@Dracathio you do have the fabric api in your mods folder right ?

**Comment by liach** [comment]
Post full crash log!

**Comment by liach** [comment]
Closing as this has no response and not enough info.
