### ISSUE TITLE
[Fabric API 19w42a] Baked models in inventory renders black when it have layers

### ISSUE THREAD

**Issue by oliviathevampire** [FabricMC/fabric#412]
What it looks like in-game ![What it looks like in-game](https://user-images.githubusercontent.com/11768384/67617550-6d4edd80-f7e4-11e9-89c9-5ef65e475ec6.png)

**Comment by grondag** [comment]
What sort of models are these and could you please provide or link to model code/JSON?

**Comment by oliviathevampire** [comment]
this is the model https://github.com/vampire-studios/Randomly-Adding-Anything/blob/dimensions-1.15/src/main/java/io/github/vampirestudios/raa/client/OreBakedModel.java

**Comment by oliviathevampire** [comment]
and it's a baked model

**Comment by grondag** [comment]
Ah, this uses the Fabric API.  Nice.

Could be an issue with normals or light maps, could be Indigo-related or could just be unresolved Vanilla strangeness.  I will take a look at this after the next snapshot - I expect it may break everything again at that time.

**Comment by liach** [comment]
Does this still happen in 19w44a?

**Comment by thecatcore** [comment]
Yes

**Comment by i509VCB** [comment]
Has this been resolved?

**Comment by grondag** [comment]
I have many multi-layer models and they are all fine in the latest builds except for the bugs fixed the latest PR.  Would close.

**Comment by i509VCB** [comment]
Got it
