### ISSUE TITLE
Client can't connect to server on modified BetterMC and gives obscenely large error

### ISSUE THREAD

**Issue by Mallowwww** [FabricMC/fabric#4159]
I recently wanted to play Better MC with some friends, so I set up a Google Cloud VM to run it. All I've done is add some mods (Create, Female Characters, Voice Chat) to the modpack. The server works perfectly fine, but when I attempt to connect with a client, I get an obscenely large message that is partially obscured unless I set GUI scaling to 1 on my 4k monitor.
Here's the server logs:
https://paste.gg/p/anonymous/511d3a3b5c45497ba814836fd071a769
and here's the message I got (I'm not typing all that out):
https://i.imgur.com/6pbqR80.jpeg
From what I've seen, it could be the server malforming a packet, but honestly I have no clue. Everything seems to work otherwise.

**Comment by modmuss50** [comment]
You should make sure that the client and server have the same mods and same versions of those mods installed.

👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
