### ISSUE TITLE
Dynamic registry loading location ignores namespace

### ISSUE THREAD

**Issue by Gaming32** [FabricMC/fabric#4179]
The dynamic registry loading code calls `RegistryKeys.getPath` which, unlike `getTagsPath`, is unpatched by Fabric API. This means that my custom `bingo:difficulty` dynamic registry gets loaded from `data/<namespace>/difficulty` instead of the namespaced `data/<namespace>/bingo/difficulty`.

**Comment by modmuss50** [comment]
Is this a new issue in 1.21.2? Or are you seeing this in an older version as well?

**Comment by Gaming32** [comment]
I don't think it's new in 1.21.2, which would technically make fixing this a breaking change.
