### ISSUE TITLE
Texture Desync 1.15 Snapshots

### ISSUE THREAD

**Issue by xDraxxis** [FabricMC/fabric#418]
When a player on my server joins with a vanilla 19w44a client, entity models are swapped around, some sounds as well. I have tested this with and without Carpet mod, happens either way. For example, endermen are replaced with Enderdragons. Not the real thing of course, just textures. 

My client log also gets spammed with this : https://pastebin.com/n6bLTSmA

Version : 19w44a
Fabric API Version :  0.4.9 Build 258-1.15

**Comment by xDraxxis** [comment]
Should mention but forgot to in the main post, we run FabricCarpet and Carpet-Extras. It adds carpet:craftingtable. We usually have no issue with this outside of when we add Fabric API to our mods folder.

**Comment by modmuss50** [comment]
Do you have fabric installed on your client? As I doesn’t appear you do.

If a mod adds a block or entity it will be required on the client side.

**Comment by xDraxxis** [comment]
Carpet itself doesn't require the mod to join on its own. Does FabricAPI make that a requirement?

**Comment by LambdAurora** [comment]
@xDraxxis you mentioned that you use carpet-extras on the server.

And on the GitHub page of carpet-extras it says: ```Due to how autoCraftingTable feature is implemented, if you are using other mods that require you to use fabric-api (carpet doesn't need it, btw), and you run carpet-extra on a server, the clients must run the same mod configuration as well. If you are only using carpet-style mods, you can connect to the servers with whatever vanilla compatible client you are using.```

So, it will require the same mods on the client when FabricAPI and carpet-extras are combined.

If I said something stupid or if I misunderstood something please ignore this comment.

**Comment by DraxxisGH** [comment]
Thank you! I must've missed that when reading

**Comment by DraxxisGH** [comment]
Actually after testing that solves nearly no problems, it seems this may be a carpet issue as the blocks stick around after I remove the mod/disable crafting table. Is there a way to fix this in Fabric?

**Comment by modmuss50** [comment]
Should be fixed going forward in 1.16
