### ISSUE TITLE
How can I install the Fabric？ 

### ISSUE THREAD

**Issue by 1798643961** [FabricMC/fabric#42]
How can I install the Fabric？

I want to install to the vanilla launcher.

But I’m fail.

**Comment by asiekierka** [comment]
Use the Fabric installer on the website's /use page. If it doesn't work, ask @modmuss50 for advice

**Comment by 1798643961** [comment]
Yes,but the API don't install.It's show jsonobject.

**Comment by modmuss50** [comment]
Update the installer, someone else reported an issue with it that sounds similar to what you are experiencing.
