### ISSUE TITLE
Error: " - Mod wurst depends on mod {fabric @ [*]}, which is missing!"

### ISSUE THREAD

**Issue by HEybruhSUp** [FabricMC/fabric#420]
- Mod wurst depends on mod {fabric @ [*]}, which is missing!

How do I fix this?

**Comment by Player3324** [comment]
It needs the Fabric API mod, available from https://www.curseforge.com/minecraft/mc-mods/fabric-api

**Comment by zophub** [comment]
> It needs the Fabric API mod, available from https://www.curseforge.com/minecraft/mc-mods/fabric-api

(I'm getting the same error as OP) I already installed Fabric API, and it still doesn't work. IT says something about me needing to download 0.12.2 but I cant find it

**Comment by deltanedas** [comment]
> needing cheats for minecraft

git gud

**Comment by Nlk29** [comment]
guy why do you even use cheats such as wurst? you'll just get banned.

**Comment by CoolName3** [comment]
> > It needs the Fabric API mod, available from https://www.curseforge.com/minecraft/mc-mods/fabric-api
> 
> (I'm getting the same error as OP) I already installed Fabric API, and it still doesn't work. IT says something about me needing to download 0.12.2 but I cant find it

It Wont Work Because It Dont Need Fabric API If It Needs Fabric API It Will Say
fabric.resource.loader which is missing
