### ISSUE TITLE
Add hook for only sending packet if the other side can receive

### ISSUE THREAD

**Issue by liach** [FabricMC/fabric#424]
In JamiesWhiteShirt/clothesline-fabric#11, I realized that fabric's network api have no convenience method for mods to opt-out of packet sending to the other side if the other side has no corresponding packet receiver. This causes rejection/client kick from certain servers such as paper. A hook to send only if the packet is identified can ease such conflicts.

**Comment by magneticflux-** [comment]
I encountered this issue as well here: [magneticflux-/fabric-mumblelink-mod#22](https://github.com/magneticflux-/fabric-mumblelink-mod/issues/22). There's a corresponding Spigot issue here, which was recently resolved (to some degree at least): [SPIGOT-5681](https://hub.spigotmc.org/jira/browse/SPIGOT-5681).

**Comment by liach** [comment]
This is implemented in https://github.com/FabLabsMC/networking-api-v1-draft, a draft repo for #455. Will probably update that pr a bit later with the stuff from the draft repo; you can test out my networking draft for now.

**Comment by liach** [comment]
This has been in networking v1, I think?
