### ISSUE TITLE
Slight grammar issue on Modrinth page

### ISSUE THREAD

**Issue by TriflingToad** [FabricMC/fabric#4251]
hello o/
Sorry if this isn't the correct spot, the contributing.md thing GitHub told me to read doesn't have anything about Modrinth issues and this is where the 'report issues' button on the mod page lead me 🤷‍♀️

I noticed on the Modrinth page there is a slight grammar issue, "Make sure you have install fabric loader first." where "have install" should be "have installed" or you could cut out 'have' and just make it "Make sure you installed fabric loader first." 

Also i think Fabric Loader should be capitalized, but I don't know much about grammar 😅

link to the page where issue is: https://modrinth.com/mod/P7dR8mSH

**Comment by modmuss50** [comment]
Fixed, many thanks :)

**Comment by haykam821** [comment]
Note that this issue was previously fixed for the README in #3127.
