### ISSUE TITLE
CustomIngredient broken equality

### ISSUE THREAD

**Issue by MehVahdJukaar** [FabricMC/fabric#4270]
CustomIngredient instances (the vanilla Ingredient wrapped ones) dont have a custom equality implementation. This can cause all sorts of issues as a custom igredient will be considered equal to an empty one

**Comment by modmuss50** [comment]
Whats the use case for checking their equality? I assume this isnt a new issue to 1.21.4?

**Comment by MehVahdJukaar** [comment]
use case can be anything. like putting ingredients in any data structure will break when mods throw it custom ones. Neoforge which has an awfully similar custom ingredient implementatio does have an equality check for it. This was tested in 1.21.1

**Comment by haykam821** [comment]
Aren't custom ingredients part of the ingredient codec? Optional field codecs with default values [use equality checks](https://github.com/Mojang/DataFixerUpper/blob/d0f713b0719b5f1ad77506e6a019c41782b8bcf1/src/main/java/com/mojang/serialization/Codec.java#L299) to determine whether the value is serialized.

**Comment by MehVahdJukaar** [comment]
![image](https://github.com/user-attachments/assets/a4c221ec-efe5-426a-a170-95930a86352b)

What codecs do or dont do has nothing to do with this
