### ISSUE TITLE
Decorated Pot Sherd textures

### ISSUE THREAD

**Issue by marnikdenouden** [FabricMC/fabric#4272]
# Issue
A decorated pot that has been crafted with sherds does not display the sherd icons on the block or item model.

![2024-12-04_19 41 13](https://github.com/user-attachments/assets/996a4c4f-be7e-442d-9ef1-d6d1a89d0c20)

![2024-12-04_19 43 01](https://github.com/user-attachments/assets/f278f14a-99db-433e-9ea3-c4498b3502e8)

# Version
Running fabric loader 0.16.9-1.21.4 with fabric-api-0.110.5+1.21.4.jar as only file in mods directory.

**Comment by apple502j** [comment]
Can confirm with provided setup.
