### ISSUE TITLE
[Fabric API 19w46b] Crash when activating a piston when a custom BER is registered.

### ISSUE THREAD

**Issue by MariaTheDinkus** [FabricMC/fabric#429]
In the latest snapshot the game crashes if a `BlockEntityRenderer` is registered in any way and you activate a piston via redstone. The block that uses the BER does not need to be placed in the world, or even be capable of rendering anything. If it simply exists and is registered, the game will crash when activating a piston.

I'm not entirely sure why this happens, but I can confirm that it has happened for both me and NinjaPhenix on the latest snapshot when we each registered two entirely different BERs.

Here's the crash report: https://hastebin.com/yacixegaxe.http

**Comment by liach** [comment]
On the first sight this looks like a classloading issue, as both mod might have caused the block entity render dispatcher to load too early.

[Where crash report is from](https://discordapp.com/channels/507304429255393322/608088354042544139/646853554471960576)

My previous analysis:
> [if npe, it is `vertexConsumerProvider` `blockState` `this.manager` or `this.manager.getModelRenderer()`](https://discordapp.com/channels/507304429255393322/608088354042544139/646856554108420096)

**Comment by liach** [comment]
Apparently in 9c45b1ef78a9c9e1d2f16a3fd629c797f0baefba (19w39a update) the lazy block entity renderer registration scheme is removed. This may have been the cause of this crash.

**Comment by liach** [comment]
Mechanism is explained in #430

**Comment by liach** [comment]
a1ff8ff878a834ff1f05aeb3689dd7e2daec8576
