### ISSUE TITLE
No Biome Replacers

### ISSUE THREAD

**Issue by HealerPlus** [FabricMC/fabric#4290]
Hello Fabric team,
I was wondering: There are several options for biomes, including BiomeSelectors.
So why are there no options to replace Biomes?
As in api (Biolith)
So that we don't have to use it 
I hope you reply.
API link: 
https://github.com/TerraformersMC/Biolith

**Comment by apple502j** [comment]
Because biolith already exists.

As this appears to be a question, I am closing this issue.

**Comment by HealerPlus** [comment]
But don't you think that Biome Replaceable should be placed in your library?
