### ISSUE TITLE
[BUG] When using the "-Dfabric.addMods=mods/libs;mods/performance" java start argument is doesn´t work on servers

### ISSUE THREAD

**Issue by NextRaven10** [FabricMC/fabric#4296]
When I add this argument to my client start arguments it works and also loads mods that are in the subfolders mods/libs and mods/performance but when I do the same to the startup arguments to the minecraft server it doesn´t work and instead says the following:

```
To specify an argument for a long option, you can use --<name>=<value> or
--<name> <value>.

./start.sh: line 5: mods/performance: Is a directory
./start.sh: line 5: mods/customization: Is a directory
./start.sh: line 5: mods/content: Is a directory
./start.sh: line 5: mods/ownmods: Is a directory
```

This is my startup script for the server:
```
#!/bin/sh

cd /srv/minecraft/****/ravensadventures
#java17 -Xms1G -Xmx8G -jar fabric-server.jar --nogui
/usr/lib/jvm/java-17-openjdk/bin/java -Xms8G -Xmx8G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=40 -Dfabric.addMods=mods/libs;mods/performance;mods/customization;mods/content;mods/ownmods -jar fabric-server.jar --nogui
```

**Comment by apple502j** [comment]
This is a shell question; it is running "mods/performance" and "mods/customization", and so forth... as commands. (like the semicolon in `sudo apt update;sudo apt upgrade -y`.) Just quote the value of addMods.

Closing as this has nothing to do with Fabric Loader.
