### ISSUE TITLE
Rendering Seriously Broken in 1.15-pre1

### ISSUE THREAD

**Issue by ghost** [FabricMC/fabric#431]
Not sure exactly what is causing the issue yet as I saw on modmuss's stream that they didn't encounter the rendering issue but other users seem to have also experienced this.

I had minor changes between 42a and 1.15pre1 so I don't think it is my mod causing the issue, but it is reproducable using [ExpandedStorage](https://github.com/NinjaPhenix/ExpandedStorage/tree/1.15-snapshot).

![image](https://user-images.githubusercontent.com/5214513/69433822-45e02780-0d34-11ea-91d3-ab72c52591ad.png)

Update:
Error doesn't occur if I don't register my blocks.

Reproducable with only these modules (minimun my mod uses):

fabric-api-base-0.1.2+b7f9825d74.jar
fabric-blockrenderlayer-v1-1.1.3+58e820e074.jar
fabric-containers-v0-0.1.3+b7f9825d74.jar
fabric-item-groups-v0-0.1.4+b7f9825d74.jar
fabric-networking-blockentity-v0-0.2.2+b7f9825d74.jar
fabric-networking-v0-0.1.7+12515ed974.jar
fabric-object-builders-0.1.2+b7f9825d74.jar
fabric-renderer-registries-v1-1.0.4+b7f9825d74.jar
fabric-resource-loader-v0-0.1.9+f3d8141b74.jar
fabric-textures-v0-1.0.0+f3d8141b74.jar

**Comment by liach** [comment]
looks like https://bugs.mojang.com/browse/MC-165959

**Comment by ghost** [comment]
Yes it does look like the exact same issue, likely due to my chest textures being odd sizes? Guess I can close this as its not an API issue.

Edit, Turns out textures that aren't 16x16 multiples will cause this bug, I had a 14x14 texture that I was using for breaking particles and resizing it completely fixed the issue.
