### ISSUE TITLE
Payload "minecraft:brand" isn't registered

### ISSUE THREAD

**Issue by arch-fan** [FabricMC/fabric#4317]
Well, I have the next receiver:

```kt
ServerPlayNetworking.registerGlobalReceiver(BrandCustomPayload.ID) { payload, context -> ...
```

And when running, Minecraft server outputs the next error:
```
Caused by: java.lang.IllegalArgumentException: Cannot register handler as no payload type has been registered with name "minecraft:brand" for SERVERBOUND PLAY
```

I think "minecraft:brand" should be registered.

**Comment by apple502j** [comment]
You are expected to register all custom payloads, including built-in ones.

**Comment by arch-fan** [comment]
Ok, it should be registered like this:

```kt
PayloadTypeRegistry.playC2S().register(BrandCustomPayload.ID, BrandCustomPayload.CODEC)
```

But then, when registering a global receiver like this:

```kt
ServerPlayNetworking.registerGlobalReceiver(BrandCustomPayload.ID) { payload, context ->
```

callback is never executed. That's a expected behaviour?
