### ISSUE TITLE
FabricBlockSettings.copyOf(Block.Settings) can mutate argument

### ISSUE THREAD

**Issue by reoseah** [FabricMC/fabric#439]
`FabricBlockSettings#copyOf(Block.Settings)` returns a wrapper of an argument. Calling methods such as 'hardness(...)` on this "copy" changes original, while it's expected to only change the copy.
```java
public static FabricBlockSettings copyOf(Block.Settings settings) {
        return new FabricBlockSettings(settings);
    }
    protected FabricBlockSettings(final Block.Settings delegate) {
        this.delegate = delegate;
    }
```

Instead, `FabricBlockSettings#copyOf(Block.Settings)` should make a deep copy of an argument and then wrap it into `FabricBlockSettings`. Method `FabricBlockSettings#copy(Block)`, for example, calls `Block.Settings#copy`, which does make a deep copy:
```java
public static Block.Settings copy(Block source) {
         Block.Settings settings = new Block.Settings(source.material, source.materialColor);
         settings.material = source.material;
         settings.hardness = source.hardness;
         settings.resistance = source.resistance;
         settings.collidable = source.collidable;
         settings.randomTicks = source.randomTicks;
         settings.luminance = source.lightLevel;
         settings.materialColor = source.materialColor;
         settings.soundGroup = source.soundGroup;
         settings.slipperiness = source.getSlipperiness();
         settings.dynamicBounds = source.dynamicBounds;
         return settings;
      }
```

**Comment by liach** [comment]
This has since been fixed in object builder api v1. https://github.com/FabricMC/fabric/blob/6d41837a9609bf5287d39af5e475654d7eb8f4b9/fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/block/FabricBlockSettings.java#L51-L76
