### ISSUE TITLE
block entity rendering fix broken

### ISSUE THREAD

**Issue by liach** [FabricMC/fabric#441]
https://github.com/FabricMC/fabric/commit/a1ff8ff878a834ff1f05aeb3689dd7e2daec8576#diff-aba3371336d2d6af7ab993ec944fa638R43-R46

look at that lines above; 
<clinit>: calls <init> and assign to INSTANCE; <init>: when it's called INSTANCE is not yet assigned

fix is simple: change this to 
```java
	static {
		BlockEntityRendererRegistryImpl.setup((t, function) -> renderers.put(t, function.apply(INSTANCE)));
	}
```
so that the INSTANCE field is used when it has been properly initialized.

**Comment by liach** [comment]
Related discussion in fabric discord: https://discordapp.com/channels/507304429255393322/566276937035546624/648786511952871424

**Comment by Player3324** [comment]
Thanks for the analysis, this should be fixed now!
