### ISSUE TITLE
Maven repository

### ISSUE THREAD

**Issue by eirikh1996** [FabricMC/fabric#446]
Hello, Does it exist a Maven repository for this project?

**Comment by natanfudge** [comment]
Hello, yes
https://maven.fabricmc.net/net/fabricmc/fabric-api/

**Comment by liach** [comment]
Maven url: `https://maven.fabricmc.net/`
Maven coordinates: group: `net.fabricmc.fabric-api`, module: `fabric-api`, version see https://modmuss50.me/fabric.html (has different versions for different mc versions)
