### ISSUE TITLE
Continuation Indent in EditorConfig

### ISSUE THREAD

**Issue by Draylar** [FabricMC/fabric#452]
I'm using IDEA 2019.1 with the latest 1.15 API branch. When auto-formatting event classes (using CheckStyle-IDEA & EditorConfig formatting), I noticed the following error:

![unknown](https://user-images.githubusercontent.com/17728338/70187197-3c02e080-16b3-11ea-94c9-264b87abc27c.png)
I did a bit of poking around, and with the help of #mod-dev, discovered it was related to the continuation indent property in `Code Style -> Java`:

![image](https://user-images.githubusercontent.com/17728338/70187263-5b017280-16b3-11ea-908d-a9edcf3d3adf.png)
Messing with this value didn't change anything, so I figured EditorConfig was forcing some sort of default value somewhere. This hypothesis was correct: according to the interwebs, you need to set `continuation_indent_size` in `.editorconfig`. Adding this under the `[*]` block, and setting it to 8, fixed my issue and made checkstyle happy.

Making an issue as I'm not sure if this is the best solution to the problem. If it is, I can easily PR the changes.

**Comment by Technici4n** [comment]
Was fixed in b4f4f6c.
