### ISSUE TITLE
Armor stands get deleted in 1.15-1.15.1 after the game is closed and reopened.

### ISSUE THREAD

**Issue by Nathan22211** [FabricMC/fabric#466]
To reproduce
1. put some armor stands in the world
2. close the game (make sure it's not running in the background)
3. reopen the game.
4. check where you put the armor stands. They should no longer be there.

I can confirm this has happened with different fabric API's and loader versions

**Comment by Sollace** [comment]
I've been testing with armour stands and 1.15 and have bot had any of them deleted.

**Comment by Nathan22211** [comment]
it's been happening to me for some reason via both multiMC and the vanilla launcher

**Comment by modmuss50** [comment]
What mods do you have installed?

**Comment by Nathan22211** [comment]
[✔️] BadAnvil-0.1.0.1
  [✔️] beeinajar-19w36a-1.0.0
  [✔️] betterbees-1.5.0
  [✔️] bigbuckets-1.0.0
  [✔️] blockus-1.3.0
  [✔️] carpet-extra-1.15-pre4-1.2.5
  [✔️] coloredcampfire-1.1.1
  [✔️] cotton-1.0.0-rc.6
  [✔️] creeper-spores-1.3.1-nightly.1.15-pre3
  [✔️] demeter-1.15-1.0.6
  [✔️] expandedstorage-3.8.34+1.15
  [✔️] extradoors-1.2.2-1.15
  [✔️] fabric-api-0.4.24+build.279-1.15
  [✔️] fabric-carpet-1.15-pre4-1.2.5+v191203
  [✔️] fabric-language-kotlin-1.3.50+build.1
  [✔️] farmcraft-v1.0.1-build-3-19w41a
  [✔️] glassdoor-1.4.1
  [✔️] ironbarrels-2.0.4
  [✔️] Just_Another_Redstone_Gate_Mod-1.1.0
  [✔️] libcd-2.0.0+1.15
  [✔️] MobZ+1.8.2
  [✔️] moreberries-1.2.3
  [✔️] nbtcrafting-1.2.6+1.15-pre1
  [✔️] requiem-1.1.0-pre2
  [✔️] simplexterrain-0.2.0
  [✔️] StuffZ+1.2
  [✔️] terrestria-1.1.1+build.18
  [✔️] traverse-2.1.3+build.9
  [✔️] unlimiter-1.1.0

**Comment by modmuss50** [comment]
does it happen without the mods? if so then its a fabric issue. If not id start by disabling 1/2 the mods to track down the mod causing the issue.

**Comment by Nathan22211** [comment]
ok it's definitely being caused by a mod than

**Comment by Nathan22211** [comment]
found one cause, unlimiter

**Comment by i509VCB** [comment]
Do you get a large amount of log barf from the Datafixer when this occurs?

**Comment by liach** [comment]
Hmm, so does this happen without unlimiter mod?

**Comment by modmuss50** [comment]
Closing as its a mod issue
