### ISSUE TITLE
Broken random block placement

### ISSUE THREAD

**Issue by avifee** [FabricMC/fabric#467]
Version: `0.4.25 build 282`
Description: Blocks that are supposed to appear at random position render at the center instead.

*especially annoying with Bamboo*

|Expectation|Outcome|
|-|-|
|![noapi](https://user-images.githubusercontent.com/17984234/71112292-d98e0200-21d3-11ea-9904-4a444e52f933.png)|![withapi](https://user-images.githubusercontent.com/17984234/71112277-d3982100-21d3-11ea-9642-c472aec6ee81.png)|

**Comment by grondag** [comment]
I will look into this one if nobody else gets to it first. Guess Mojang made changes to when/how offsets are applied in chunk baking.

**Comment by modmuss50** [comment]
Are you sure this is working in vanilla? Is your screenshot from vanilla 1.15.1?

**Comment by liach** [comment]
not really random position but an offset; and the displayed hitbox is valid (not like a render issue) when last tested in 1.15 pre bee merry. looks like server or engine side and very likely vanilla.

**Comment by avifee** [comment]
The screenshot on the left is fabric loader with no api and api intact on the right one

**Comment by coderbot16** [comment]
I think this is fixed.

**Comment by modmuss50** [comment]
Yes this is fixed
