### ISSUE TITLE
fabric 14.4 mods and 14.4 universal mods not being loaded together?

### ISSUE THREAD

**Issue by DebuggingDiscontinuity** [FabricMC/fabric#468]
Running "release fabric-loader-0.7.2+build.174-1.14.4" with "fabric-api-0.4.2+build.246-1.14." I'm using the Vanilla launcher.

Any mods with the fabric dependency work with no issues. No universal mods (does not require Fabric or Forge) will load. My mods are located in .\.minecraft\profiles\1.14.4\mods. I tried moving the universal mods to the .\.minecraft\mods folder, but nothing changed. The mods are not mentioned in the logs at all. 

This has been duplicated on two computers. 

How do I get both types of mods to play nicely? If there's no other dependencies for these others, I'm honestly not sure why I'm having this issue unless the fabric profile only loads mods with fabric dependencies.

**Comment by zabi94** [comment]
Pardon my ignorance, but what do you mean with "universal mods"? Any example?

**Comment by shedaniel** [comment]
Jar mods or forge mods are not supported by the fabric loader, there are projects (i.e. patchworks to load forge and optifabric to load optifine) to load such jars, but they are not official.

P.S. Patchwork is still in WIP.

**Comment by liach** [comment]
What do you mean by universal mods? Also given this is a fabric loader support issue and does not belong to the API, closing. Feel free to ask for help though.
