### ISSUE TITLE
BlockRenderLayer not found

### ISSUE THREAD

**Issue by JoshPJackson** [FabricMC/fabric#469]
I'm following the tutorial on the website for making a fluid. I can't find the BlockRenderLayer class that is referenced as the return class of getRenderLayer()

**Comment by shedaniel** [comment]
It is now gone in 1.15. Do the following:
```java
BlockRenderLayerMap.INSTANCE.putFluid(yourFluid, layer);
```

**Comment by shedaniel** [comment]
The wiki is outdated but this repo is not where you should ask/report, this is the fabric api repo. You should better ask from discord and tell someone to update the wiki.

**Comment by JoshPJackson** [comment]
ok thanks
