### ISSUE TITLE
Hooks for chunk unload and world unload

### ISSUE THREAD

**Issue by fnuecke** [FabricMC/fabric#47]
Hooks/events for these two are (among other things) useful to allow BlockEntities to have a guaranteed "dispose" callback, e.g. in case they hold some unmanaged resource (such as GL memory). Relying on finalizers for this is suboptimal. Maybe even implement them as an interface BlockEntities can implement. Might be fine to just call `invalidate`, even, that'd need some proper thinking about tho.

My quick and dirty mixins currently look like [this for world unload](https://github.com/MightyPirates/TIS-3D/blob/edbe14510f91369719440571332701748b82ab2a/src/main/java/li/cil/tis3d/client/mixin/WorldUnloadMinecraftClientMixin.java) (which is really just the set world in MinecraftClient, does not handle actual world unloading on server e.g., mostly because I couldn't figure out if that even happens in vanilla MC or if dim unloading was just a Forge thing), and [like this](https://github.com/MightyPirates/TIS-3D/blob/edbe14510f91369719440571332701748b82ab2a/src/main/java/li/cil/tis3d/common/mixin/ChunkUnloadMixin.java) for chunk unloading, which is bad if every mod has to mixin the loop themselves.

**Comment by i509VCB** [comment]
This has been implemented in `lifecycle-events-v1`.
