### ISSUE TITLE
UseItemCallback crashes when a custom result is set

### ISSUE THREAD

**Issue by Pyrofab** [FabricMC/fabric#470]
Mixins to `ServerPlayerInteractionManager` and `ClientPlayerInteractionManager` attempt to set a `TypedActionResult` as the return value of methods that return an `ActionResult`.
Mixin does not report that error, but the game crashes with a `ClassCastException` whenever a mod registers a callback that returns a result other than `PASS`.
https://gist.github.com/Pyrofab/1cf5149616504ddb91ab3fc854dd4bbc

**Comment by Player3324** [comment]
Thanks, fixed by https://github.com/FabricMC/fabric/pull/484
