### ISSUE TITLE
Move ideconfig.gradle to repo itself

### ISSUE THREAD

**Issue by liach** [FabricMC/fabric#472]
Currently, the gradle build of fabric api imports from `https://github.com/FabricMC/fabric-docs/raw/master/gradle/ideconfig.gradle`. This is somewhat troublesome as now in PRC, raw.githubusercontent.com has been blocked, which prevents building fabric api in PRC.

**Comment by i509VCB** [comment]
Should probably be included in the repo and applied using
```groovy
apply from: ideconfig.gradle
```

**Comment by i509VCB** [comment]
Should be a simple change for someone to do if they wish.

**Comment by i509VCB** [comment]
Closing since those remote buildscripts are no longer used.
