### ISSUE TITLE
Registration API for data loaders

### ISSUE THREAD

**Issue by bluebear94** [FabricMC/fabric#473]
I'm working on a mod that adds the concept of tool materials, and I'd like to be able to load their properties from data packs. Right now, Minecraft has a hardcoded list of `DataLoader`s, which makes doing so hard. It would be easier to do if Fabric provided a way to register our own `DataLoader`s (or more precisely, functions to generate them per `Server`) and sync its data to the client if requested.

**Comment by Juuxel** [comment]
Fabric API has a class called [`ResourceManagerHelper`](https://github.com/FabricMC/fabric/blob/1.15/fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/api/resource/ResourceManagerHelper.java) for registering `ResourceReloadListener`s for resource pack / data pack loading.

**Comment by bluebear94** [comment]
Thanks, that was what I was looking for.
