### ISSUE TITLE
Access to creating StateProviderTypes

### ISSUE THREAD

**Issue by Prospector** [FabricMC/fabric#474]
StateProviderType.register is private

**Comment by Prospector** [comment]
Sorry, I'm tired. That method just calls Registry.register lol

**Comment by Prospector** [comment]
Wait no, the constructor is private.

**Comment by i509VCB** [comment]
If this now refers to `BlockStateProviderType`s you should be able to use mixin 0.8 to instantiate the private constructor.

Whether we should include a method to expose a public method to create it could be discussed.
