### ISSUE TITLE
Expose InternalBiomeUtils.transformBiome

### ISSUE THREAD

**Issue by Juuxel** [FabricMC/fabric#475]
`transformBiome` can be used by dimension mods for transforming modded biomes into their variants, which is done in the `SetBaseBiomesLayer` mixin in the biome API. (`SetBaseBiomesLayer` places all registered continental biomes, so I can't use that directly.)

**Comment by liach** [comment]
@valoeghese should speak given he wrote the biome api.

**Comment by valoeghese** [comment]
I didn’t write it by myself, coderbot and prospector also contributed

**Comment by valoeghese** [comment]
Anyway, we should expose it through a method in `FabricBiomes`, I think (since that’s the class for stuff not pertaining to a specific dimension). Possibly `FabricBiomes#transformBiome` or `FabricBiomes#transformBiomeVariant`?

**Comment by Juuxel** [comment]
Yeah, I think a method in `FabricBiomes` would be good, though biome variants are registered in `OverworldBiomes#addBiomeVariant`. Should we move that to `FabricBiomes`? (It only applies to dimensions that use either the overworld base biome layer or transform the biomes themselves)

**Comment by coderbot16** [comment]
I think it makes sense to keep it all in OverworldBiomes because these biomes only spawn in the Overworld by default or Overworld-like biomes.

**Comment by apple502j** [comment]
Not applicable for 1.18+
