### ISSUE TITLE
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors!

### ISSUE THREAD

**Issue by ghost** [FabricMC/fabric#476]
The game was okay with fabric. I left my game window open until the power outage occurred earlier. I got my game open but it crashed it shows that error. It did not occur prior to the power outage.

I'm using 0.6.4 version, tried to delete all the mods solves the issue so then I can restore them in my recycle bin folder. This has to be Fabric API but I'm using 0.3.1+build.208 anyways. Many users have that problem, and it must be fixed.

**Comment by Juuxel** [comment]
Could you post the full game log?

**Comment by liach** [comment]
Try with both latest loader and latest fabric api. Power outage of computers afaik can cause world corruptions but shouldn't cause launch crashes (unless mods crash on broken config)

**Comment by Prospector** [comment]
Never posted log, nothing we can do
