### ISSUE TITLE
How to draw string to screen?

### ISSUE THREAD

**Issue by pvorisek25** [FabricMC/fabric#477]
I am trying to use the drawWithShadow method to draw to screen. I am calling this method every client tick callback but there is no text after loading a world.

This is my actual code that I call every client tick:
`MinecraftClient.getInstance().inGameHud.getFontRenderer().drawWithShadow("Help", 1, 1, 0xffffff);`

**Comment by shedaniel** [comment]
tick != render frame, you must mixin to InGameHud manually until #359 is merged

**Comment by pvorisek25** [comment]
Thanks @shedaniel ! It works now.
