### ISSUE TITLE
Side-aware Block.getPickStack

### ISSUE THREAD

**Issue by fnuecke** [FabricMC/fabric#48]
For some blocks it is necessary to know the side when trying to get the ItemStack via middle-click to return the expected result. Thinking one step further, the hit information or at least x/y/z offset might be nice, as well, I guess. Possibly an interface Blocks can implement?

My current (as I've been told evil) mixin looks [like this](https://github.com/MightyPirates/TIS-3D/blob/edbe14510f91369719440571332701748b82ab2a/src/main/java/li/cil/tis3d/client/mixin/PickModuleMixin.java). Will try to get rid of the `@Redirect` at least, until this makes it in...

**Comment by SquidDev** [comment]
I looked into this a couple of days ago, and then realised it was possible to get the current hit result with `MinecraftClient.getInstance().hitResult`. 

I'm not sure how much it's worth adding a variant of `getPickStack` which accepts a `HitResult`, given that it can be emulated pretty easily. However, there may be some use-cases I'm missing.

**Comment by asiekierka** [comment]
Is getPickStack client-side-only?

**Comment by SquidDev** [comment]
Yes.

**Comment by asiekierka** [comment]
Well then, once we add environment stripping that settles it, doesn't it?... At least for now

**Comment by fnuecke** [comment]
The issue I'd see with this is that getPickStack may be called (by mods) on any block, not just the one the player is looking at. Using the global player hitResult is potentially unexpected implicit behaviour.

**Comment by asiekierka** [comment]
Solved in 0.2.0.
