### ISSUE TITLE
Hooks to BuiltinModelItemRenderer

### ISSUE THREAD

**Issue by Juuxel** [FabricMC/fabric#488]
It would be useful to have hooks for items that can be rendered using a BER, for example. (Vanilla uses this class for things like chests)

**Comment by liach** [comment]
So like a new module?

**Comment by Juuxel** [comment]
Yeah, or just within some current rendering module (rendering-v1?). We have a lot of those already 😄

**Comment by modmuss50** [comment]
Yes, something like this is needed. its not hard to use a mixin, but a real api would be useful.
