### ISSUE TITLE
Wrong sounds are being outputted when fabric api is installed on fabric server 1.15.1

### ISSUE THREAD

**Issue by jack-bkr** [FabricMC/fabric#489]
This issue only occurs when fabric api is installed and when on a specific world. I cannot reproduce it on any other worlds and I have also tried all 1.15 fabric api versions, with no change. I doubt this is a client-side problem as the client is on the vanilla game, it doesn't occur when the world is run locally or when the server is running without the fabric api.

**Comment by modmuss50** [comment]
Try deleting the the fabric registry files in the data folder of the world. Make sure to backup first. It’s a known bug that occurs when updating worlds.

**Comment by jack-bkr** [comment]
Thank you that fixed it xD
