### ISSUE TITLE
Particles Example Mod not working

### ISSUE THREAD

**Issue by NathanPB** [FabricMC/fabric#494]
Well I've been messing around with particles for the last 12 hours, I got several different problems on different contexts, but right now I wanna talk about the [Particle Testmod](https://github.com/FabricMC/fabric/blob/1.15/fabric-testmods/java/net/fabricmc/fabric/resources/ResourceReloadModClient.java) not working at all.

Well, I copy/pasted the mod in a [separated repository](https://github.com/NathanPB/fabric-particle-example) to make things easiers, because I couldn't figure out how to run it from the module provided in this repository.

Even before the game starts with the exact same workspace of the example mod repository template (currently in [this](https://github.com/FabricMC/fabric-example-mod/tree/18fd282e3e0cc4752d5e34a4360f57f54fd11b64) revision) the game crashes with this: https://gist.github.com/NathanPB/c00dbb93ee6adcc7720374ed8e636d4f

If I remove the "textures" entry of the JSON file at ``src/main/resources/assets/modid/particles/custom.json`` the game just loads, but just as expected the particle doesn't have a texture and its transparent (so, useless)

I'd like someone to assert me if the API is broken or I'f I'm just missing some steps or something. Thank you all

**Comment by liach** [comment]
Indeed it is out of date. #593 will refactor test mods, so we can get a working particle test mod again.

**Comment by i509VCB** [comment]
This issue is now in a state where someone can whip up a particles testmod if they wish.
