### ISSUE TITLE
Fabric API Error loading language-1.14.4

### ISSUE THREAD

**Issue by VIQingNiao** [FabricMC/fabric#497]
![YNW6S$33H@5_Y1TXD UUZ8](https://user-images.githubusercontent.com/46963763/74080750-47db9c00-4a82-11ea-9ccc-bdccc1d01379.png)
when i try to open MC, this happens.
fabric-loader-0.7.6+build.181-1.14.4
fabric-api-0.4.2+build.246-1.14
replaymod-1.14.4-2.2.0-b7

Can you fix it  I really need it ,thank you

**Comment by liach** [comment]
looks like a replay mod translation bug

**Comment by VIQingNiao** [comment]
> looks like a replay mod translation bug

Normal operation after fabric-api-0.4.1+build.245-1.14
But I don't need fabric-api-0.4.1+build.245-1.14

**Comment by liach** [comment]
maybe fabric resource loader broke. does any other mod have translation issues

**Comment by VIQingNiao** [comment]
> maybe fabric resource loader broke. does any other mod have translation issues

It's all like this

**Comment by modmuss50** [comment]
Looks like a mod issue. Make sure you have the latest version of fabric and fabric loader along with all the versions you are using. If that doesnt help contact the replay mod authors.
