### ISSUE TITLE
Make blacklists in RegistrySyncManager accessible

### ISSUE THREAD

**Issue by Siphalor** [FabricMC/fabric#509]
Please 🥺
Since I think I'm gonna need to mixin to the class to access features that are implemented but for some reason not exposed 😟

https://github.com/FabricMC/fabric/blob/d9bddadaa0a4f16e1e07345268e110488c211a49/fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/impl/registry/sync/RegistrySyncManager.java#L55-L56

**Comment by liach** [comment]
[Blame asiekierka](https://github.com/FabricMC/fabric/blame/d9bddadaa0a4f16e1e07345268e110488c211a49/fabric-registry-sync-v0/src/main/java/net/fabricmc/fabric/impl/registry/sync/RegistrySyncManager.java#L55-L56) for making them immutable! We can do this in a refactor later (the registry sync module is one of the most problematic/buggy module in fab api right now)

**Comment by i509VCB** [comment]
My question is why does the blacklist even exist. Obviously something related to not syncing certian registries would be nice incase but makes generally no sense unless you mixin to Registry and add yourself registry to REGISTRIES.

**Comment by Siphalor** [comment]
> My question is why does the blacklist even exist. Obviously something related to not syncing certian registries would be nice incase but makes generally no sense unless you mixin to Registry and add yourself registry to REGISTRIES.

e.g. I manually block syncing of some recipes in nbtc, so I don't want fabric to mess that up. btw it's quite cool to keep some recipes only on the server side 🙂.
I could either block the whole registry sync for recipes through these blacklists or I would need to mixin even more to block single recipes from being synced by Fabric (maybe I should make a feature request for that).

**Comment by i509VCB** [comment]
This no longer exists in #525 

I'd say when it is merged, this issue should be changed to for example `Allow blacklisting entries in registry sync`

**Comment by liach** [comment]
No, in #525 it is handled by the `SYNCED` registry attribute, which I think you can modify freely.

**Comment by i509VCB** [comment]
Well was the request the registry entries or the entire registry?

>  I manually block syncing of some recipes in nbtc

This makes me think it is entries, not whole registries.

**Comment by liach** [comment]
This is more like syncing a fake registry to client instead then than a simple blacklist of registries.

**Comment by Siphalor** [comment]
I agree to i509VCB. 

When I first opened this issue I thought it would be done with blacklisting whole registries but right now I‘m mostly in need to block single entries. 

Maybe this should bestimmt a separate issue?

**Comment by i509VCB** [comment]
Probably a new issue. Also I noticed this was issue 509

**Comment by modmuss50** [comment]
These's blacklists will be removed in my PR, and an API is in place to expose marking registries as modded, synced or persisted.

**Comment by modmuss50** [comment]
No longer applicable.
