### ISSUE TITLE
Add @Environment annotations to the API

### ISSUE THREAD

**Issue by Earthcomputer** [FabricMC/fabric#511]
Explicitly annotating client-side classes and members with `@Environment(EnvType.CLIENT)` will help tools identify when people are trying to call client code from a common/server context.
Currently, this will be useful for my mcdev fork, but it will also be useful for anyone else wanting to make a static analysis tool to this effect.

**Comment by modmuss50** [comment]
This is no longer required since we built with split source sets. All client only classes will now always have the annotation in a mod dev/prod env 👍
