### ISSUE TITLE
Registry remapping failed:Received ID map for minecraft:sound_event contains IDs unknown to the receiver!

### ISSUE THREAD

**Issue by KawaiiTamako** [FabricMC/fabric#516]
![QQ图片20200310000731](https://user-images.githubusercontent.com/51044119/76233466-32b18300-6263-11ea-901a-a5c68b74bcf8.png)
1.14.4 fabric client join 1.15.2 fabric server with viaversions
plz! fix it

**Comment by liach** [comment]
hmm, how does viaversion handle like bees on 1.14.4? just curious so we can get a better "fix"

first, remove the fabric registry sync from your client's fabric api jar

**Comment by CrazyHPi** [comment]
btw using multiconnect in 1.15.5 client to join 1.14.4 fabric server has similar problem

**Comment by KawaiiTamako** [comment]
> 嗯，viaversion如何像1.14.4上的蜜蜂一样处理？只是好奇，所以我们可以获得更好的“修复”
> 
> 首先，从客户的Fabric API罐中删除Fabric注册表同步

How to do it? I deleted it from both the client and the server, but it failed to start

**Comment by modmuss50** [comment]
Try withou viaversion or similar mods.

**Comment by KawaiiTamako** [comment]
> Try withou viaversion or similar mods.

This is not a problem with viaversions. Delete the fabric-api on the server, 1.14.4 can go in,but you cannot use carpet.

**Comment by modmuss50** [comment]
fabric on its own doesn’t support connecting to different version servers, it must be a mod doing that

**Comment by CrazyHPi** [comment]
vanilla client works perfectly fine w/ viaversion+fabric server tho
the purpose of using lower version to join 1.15.2 server ppl is using replay mod which still not update to 1.15.2

**Comment by KawaiiTamako** [comment]
> vanilla client works perfectly fine w/ viaversion+fabric server tho
> the purpose of using lower version to join 1.15.2 server ppl is using replay mod which still not update to 1.15.2

yes, so how to fix egistry remapping failed:Received ID map for minecraft:sound_event?

**Comment by modmuss50** [comment]
Like I said fabric doesn’t support this, so report the issue to the mod devs who make the mods that do allow this.

**Comment by KawaiiTamako** [comment]
> Like I said fabric doesn’t support this, so report the issue to the mod devs who make the mods that do allow this.

So can't I enter the server by deleting fabric registry sync from client's fabric api jar?

**Comment by modmuss50** [comment]
That may well work

**Comment by KawaiiTamako** [comment]
> That may well work

No, it won't start at all

**Comment by liach** [comment]
问下，原版1.14.4客户端进1.15服务器遇到蜜蜂会怎么样，就是隐形蜜蜂？
