### ISSUE TITLE
"warning while loading mods" when starting up minecraft

### ISSUE THREAD

**Issue by FBGAccurate** [FabricMC/fabric#519]
I tried installing Fabric API, I put the Java file into my mods folder but it doesn't work. If i am doing it wrong please give me a step by step process on how to set it up.
![Minecraft_ 1 15 2 3_10_2020 10_12_24 AM](https://user-images.githubusercontent.com/50580898/76327376-eba1ad00-62b7-11ea-8119-c394e818db0d.png)

**Comment by i509VCB** [comment]
You seem to be on a forge environment, and fabric's api is not supported on forge. Change your launcher profile to the one fabric created and things should work.

**Comment by FBGAccurate** [comment]
> You seem to be on a forge environment, and fabric's api is not supported on forge. Change your launcher profile to the one fabric created and things should work.

So how do I do that? I tried opening it and it wasn't doing anything... I go to installations and its also not showing up there.

**Comment by i509VCB** [comment]
If you look at the launcher page you should see a bar down below where on my launcher it says `fabric-loader-x.xx.x` https://i.imgur.com/Tu3yFnN.png if you click the bar there should be multiple options on the popup. If fabric doesn't show there then install it from here:
https://fabricmc.net/use/
