### ISSUE TITLE
Registry sync mod

### ISSUE THREAD

**Issue by KawaiiTamako** [FabricMC/fabric#523]
I delete registry sync mod form fabric api，so i can't launch the game

**Comment by liach** [comment]
you need to delete its jar in jar reference in a file in META-INF of fabric api jar also. will post detailed instructions later

**Comment by KawaiiTamako** [comment]
> you need to delete its jar in jar reference in a file in META-INF of fabric api jar also. will post detailed instructions later

Oh, thank you so much. I really need this.I am waiting for you

**Comment by KawaiiTamako** [comment]
![QQ图片20200312030734](https://user-images.githubusercontent.com/51044119/76454055-e73bd800-640e-11ea-8e22-2eb0f7aae00e.png)
My god, I deleted fabric-registry-sync.jar from fabric-api.jar, and now I ca n’t open the game, what should I do?

**Comment by liach** [comment]
我等下发个具体流程

**Comment by KawaiiTamako** [comment]
> 我等下发个具体流程

We're done. It's especially simple, but we didn't notice fabric.mod.json at the beginning.

**Comment by liach** [comment]
good then, issue resolved?

**Comment by liach** [comment]
Yes, you need to go to the `jars` section of the fabric mod json metadata and remove the entry that refers to the registry sync jar (this way you actually don't even need to delete the registry sync mod jar)

**Comment by liach** [comment]
@KawaiiTamako 最后删掉后viaversion能不能用

**Comment by KawaiiTamako** [comment]
> 能不能用
服务端不需要任何改变，只需要修改fabric.mod.json和registry-sync-mod

**Comment by liach** [comment]
实际上两个端哪个registry sync删掉都可以，如果你客户端是玩家自己打的话推荐删服务器上fabric api的registry sync
