### ISSUE TITLE
Allow for compatibility with Forge

### ISSUE THREAD

**Issue by OverloadedWolf** [FabricMC/fabric#524]
While I don't dislike fabric, MinecraftForge has been around since the beginning and should be notarized as the main modding source. Having incompatibilities between Fabric and Forge only splits the modding community as they have to either create for both or create for one or the other. This also leads to frustration on the Twitch Launcher when you do not automatically install Fabric into the newly created instance.

Please consider either making Fabric compatible or discontinuing fabric for the next Minecraft Version.

**Comment by haykam821** [comment]
> While I don't dislike fabric, MinecraftForge has been around since the beginning and should be notarized as the main modding source.

Directly patching the JAR has been around longer. Why shouldn’t that be the main modding source?

> Having incompatibilities between Fabric and Forge only splits the modding community as they have to either create for both or create for one or the other.

Patchwork is being developed, which allows Forge mods to run on Fabric, which should solve this issue.

> This also leads to frustration on the Twitch Launcher when you do not automatically install Fabric into the newly created instance.

This is a Twitch app problem. The workaround is to use Jumploader.

> Please consider either making Fabric compatible or discontinuing fabric for the next Minecraft Version.

Why does Fabric need to do this and not Forge?

**Comment by florensie** [comment]
lmao wat

**Comment by modmuss50** [comment]
I see your frustration, however adding forge support isnt trivial, but it is doable. Its not something that I have the time or energy to sink into it.

There are 3d party solutions being worked on, and I have nothing against those platforms and encorage them.

Fabric supports every (major) launcher other than twitch, and im always happy to work with the launcher developers to provide the tools they need to add support.

No one is forcing you to use forge or fabric, please use what you want to use, its a similar argument to the iOS/Andorid thing.
