### ISSUE TITLE
Events Jamboree (Issue tracking for events and ideas) 

### ISSUE THREAD

**Issue by i509VCB** [FabricMC/fabric#532]
I've opened this up since I would like a central issue to track which events are in progress and for discussion of events we would like to add to fabric's api. 

Current events in issues and or PRs

Entity Tick Callback (Fired each time tick is called on an entity): #505, ~~#184~~

Player Respawn Callback (called when a player is respawned (by dimension transfer or death): #508 

Player Connect/Disconnect Callback: Issues: #226  PRs: #455 (mentioned/by proxy)

Listening to keybinds: #129   

Now the fun part, we would like some ideas on more events to implement into the api. The reccomendations should follow the criteria:

Reasonable (does the event idea actually make sense)

Compatible (does this event leave room for mod compatibility or does it require rewriting subsystems) 

Precision/Flexibility (does this event cover the exact case it is designed for, or is the coverage too broad for any real context). Depending on the type of event this could be a good or bad thing.

Practical (Is this event partial to use from the standpoint of a mod developer, and would it see use.

So let the discussion begin.

**Comment by Juuxel** [comment]
There's also something in #19.

**Comment by i509VCB** [comment]
Oh, didn't know that

**Comment by i509VCB** [comment]
Closing since mass issues are not preferred for this, for anyone else please open an issue for a category of suggested events.
