### ISSUE TITLE
Crash on load with MixinFireBlock (20w13a)

### ISSUE THREAD

**Issue by dvitski** [FabricMC/fabric#544]
I've no idea how to fix this myself, so here's the issue info

```properties
minecraft_version=20w13a
yarn_mappings=20w13a+build.5
loader_version=0.7.8+build.189

#Fabric api
fabric_version=0.5.6+build.313-1.16
```

https://pastebin.com/jr8vCgYM

**Comment by liach** [comment]
Hmm, don't think this happens on 14a... sorry for late response, but if this happens in 14a comment and I will reopen thread.
