### ISSUE TITLE
Brightness issue

### ISSUE THREAD

**Issue by andrei1058** [FabricMC/fabric#546]
Why is this software changing my brightness?

**Comment by liach** [comment]
Hey man you need to learn about smooth lighting

**Comment by liach** [comment]
Try set smooth lighting in your minecraft settings. It appears your smooth lighting level is low. If you change it higher the brightness should look better.

**Comment by Prospector** [comment]
It's still incorrect at any smooth lighting level. Blocks with custom models have no AO I believe. And there's like no shading at all with smooth lighting off.

**Comment by LemmaEOF** [comment]
![](https://cdn.discordapp.com/attachments/507304429255393324/700789549869039626/2020-04-17_14.26.54.png) There's someone else reporting issues with smooth lighting off.

**Comment by gudenau** [comment]
No smooth lighting:
![2020-04-17_14 40 48](https://user-images.githubusercontent.com/5642329/79608618-f28fbc80-80ba-11ea-9a09-df35b9691167.png)
Minimal smooth lighting:
![2020-04-17_14 44 20](https://user-images.githubusercontent.com/5642329/79608636-fb808e00-80ba-11ea-8e71-2aa8425ed291.png)
Maximum smooth lighting:
![2020-04-17_14 44 32](https://user-images.githubusercontent.com/5642329/79608657-01766f00-80bb-11ea-865a-e960d5be0bab.png)

This is pretty bad.

**Comment by modmuss50** [comment]
I have opened a PR that should fix the issues, It may be worth doing a side-by-side with vanilla to ensure it is correct in all situtations.
