### ISSUE TITLE
Set block luminance based on lambda funcion

### ISSUE THREAD

**Issue by IbraheemR** [FabricMC/fabric#549]
As of the 1.16 snapshots (at least since 20w13b) `Block#getLuminance` no longer excists.
Looking at the vanilla code, luminance is now set with a lambda, that takes a block state and returns a light level. For most lit blocks this returns a constant, but for blocks like redstone lamp this returns a value based on its "lit" property.

This should probably be added to the `FabricBlockSettings` API, as without it there seems to be no way to create blocks with 'dynamic' light levels (without entering mixin hell).
@modmuss50 tells me this is already planned for an upcoming revamp, but that it could trivially be added sooner

**Comment by paulevsGitch** [comment]
Light lamda functions can be used without mixins, like [here](https://github.com/paulevsGitch/BetterNether/blob/4c6afeb89d552c2ab0745d2f9269f968288a9625/src/main/java/paulevs/betternether/blocks/BlockCincinnasiteFireBowl.java#L40)

**Comment by liach** [comment]
So vanilla currently restricts the context of luminance (server side lighting) but allows you to return custom emissive light levels ( i.e. client only light level). Weird indeed, hope they can move the luminance to one of the lambdas in settings.

**Comment by i509VCB** [comment]
As of object builders v1, there is a `ToIntFunction<BlockState>` inside of `FabricBlockSettings` to calculate the value. However whether this provides enough context for this use case is a different question.

**Comment by Technici4n** [comment]
We can't realistically patch all of these call sites: 
![image](https://user-images.githubusercontent.com/13494793/210391568-733de163-cd2e-41bd-a487-b02e7ba1007e.png)

A workaround for dynamic blocks is to store the luminance as a block state property.
