### ISSUE TITLE
[20w14a+] Default Attribute Registry

### ISSUE THREAD

**Issue by liach** [FabricMC/fabric#551]
Since 20w14a, default attributes for subtypes of living entities are registered in a fashion similar to the render layers for blocks and fluids. As a result, we need a way to register default attributes for living entities in the api, maybe in a new module.

**Comment by Shnupbups** [comment]
I'd really like something to be done about this ASAP, as it stands it is incredibly awful to add new entities as of 20w14a.

At least it very much seems like it, full disclosure, I haven't attempted the Mixins required for it.
