### ISSUE TITLE
Could not find or load main class net.fabricmc.loader.launch.knot.KnotClient

### ISSUE THREAD

**Issue by vbajs** [FabricMC/fabric#553]
I was playing with minecraft as usual until it crashed and when I tried to launch it again, these errors stopped minecraft from being launched.

This is what it said on the game output
`Error: Could not find or load main class net.fabricmc.loader.launch.knot.KnotClient`
And this is what it said on launcher logs
`[17:40:07 ERROR]: Game ended with bad state (exit code 1)`

I tried re-installing fabric loader no avail
This is happening on verision 0.7.10+bulid191-1.15.2

**Comment by modmuss50** [comment]
Do you have any mods?
Can you post the full log?
What launcher are you using?

**Comment by vbajs** [comment]
Yes, They are :-
`CustomSkinLoader_Fabric-14.12-SNAPSHOT-109.jar
optifabric-1.0.0-beta8.jar
preview_OptiFine_1.15.2_HD_U_G1_pre13.jar`

The game crashes quickly before it creates any game output logs and the error is the only sentence writtens. But the full lanucher log can be found [here](https://ghostbin.co/paste/rawde)

I am using SKlauncher v3 Beta 14

**Comment by modmuss50** [comment]
That seems like the launcher log, can you get the game log?

It sounds like an installer/launcher issue tbh, SKlauncher isnt one of our offically supported launchers, but im happy to try and help get it running.

**Comment by vbajs** [comment]
As I said, the game crashes quickly before it creates any logs and `Error: Could not find or load main class net.fabricmc.loader.launch.knot.KnotClient` is the only thing that is being output.

I'll see if this issue is reporduced in other lanuchers. If it doesn't, then looks like I'll have to pass it on with the devloper of SKlauncher. Thanks for helping!

**Comment by modmuss50** [comment]
Closing this issue as I thought you were using SKCraftLauncher, however you are using the SKLauncher, this launcher allows the game to be pirated.

Please use one of the officall installation methods listed on the fabric website.

I will be closing and locking this issue as we do not support piracy here.
