### ISSUE TITLE
The problem comes from AbstractDonkeyEntity.class 44 lines

### ISSUE THREAD

**Issue by baka4n** [FabricMC/fabric#555]
at net.minecraft.entity.passive.AbstractDonkeyEntity.createDefaultAttributes(AbstractDonkeyEntity.java:39)

Is there a solution for this?

**Comment by i509VCB** [comment]
Okay so in your `gradle.properties` you need to change your `yarn_version` to `20w14a+build.4`. This issue with the mappings will be fixed in a later version of yarn

**Comment by liach** [comment]
Also this is more of a support issue. This is not related to fabric api at all.

**Comment by i509VCB** [comment]
oh so it's on a real client

EDIT: misread what you said liach

**Comment by liach** [comment]
Update yarn to 20w14a+build.8 or later, which has this issue fixed.
