### ISSUE TITLE
[20w14a+] Lang files no longer work as intended

### ISSUE THREAD

**Issue by dookbold-zz** [FabricMC/fabric#556]
In 20w14a, the language file does not work anymore.
![image](https://cdn.discordapp.com/attachments/507982478276034570/696644852703559720/unknown.png)
The second image is 1.15.2.
![image](https://user-images.githubusercontent.com/35373795/78543243-3fb38a80-77ad-11ea-8176-1a531c5456b1.png)
The language files are the exact same with the same exact location.
 B0undaryBreaker suggested on Discord I report this issue here, so thanks to her!

**Comment by Prospector** [comment]
I've not been able to reproduce this; lang files work fine for me on 20w14a+. My guess is it is most likely a local IDE/caching issue or something. Is this still an issue for you?

**Comment by dookbold-zz** [comment]
I have to test it again

> 
> 
> I've not been able to reproduce this; lang files work fine for me on 20w14a+. My guess is it is most likely a local IDE/caching issue or something. Is this still an issue for you?
