### ISSUE TITLE
1.15.2 crashes with and without mods

### ISSUE THREAD

**Issue by 8bit-coder** [FabricMC/fabric#557]
I've been going to hell and back just to get fabric working. Yes, i downloaded the newest installer, have the correct API, and have the newest version of java, but fabric just will. not. work. It just always crashes for some reason with this: 
`18:50:54.196
Preparing to launch minecraft client for fabric-loader-0.8.2+build.194-1.15.2
18:50:55.860
Checking installations.
18:50:55.861
Minecraft client fabric-loader-0.8.2+build.194-1.15.2 is ready to start.
18:50:55.861
Starting!
18:50:56.392
Using default game log configuration client-1.12.xml (outputs XML)
18:50:58.240
Loading for game Minecraft 1.15.2
18:51:01.635
[FabricLoader] Loading 34 mods: minecraft@1.15.2, fabric-renderer-api-v1@0.2.9+aea78a250c, fabric-networking-blockentity-v0@0.2.3+e08a73050c, fabric-keybindings-v0@0.1.1+dfdb52d60c, fabricloader@0.8.2+build.194, fabric-renderer-indigo@0.2.22+203491ea0c, fabric-containers-v0@0.1.3+b7f9825d0c, fabric-dimensions-v1@0.2.4+203491ea0c, fabric-biomes-v1@0.1.5+3b05f68e0c, fabric-crash-report-info-v1@0.1.2+b7f9825d0c, fabric-events-interaction-v0@0.2.7+a1bd31180c, fabric-api-base@0.1.2+b7f9825d0c, fabric-rendering-v0@1.1.0+534104900c, fabric-rendering-v1@0.1.0+534104900c, fabric-rendering-data-attachment-v1@0.1.3+b7f9825d0c, fabric-resource-loader-v0@0.1.10+06c939b30c, fabric-textures-v0@1.0.4+821cdba70c, fabric-content-registries-v0@0.1.3+b7f9825d0c, fabric-tag-extensions-v0@0.1.3+abd915800c, fabric-rendering-fluids-v1@0.1.6+12515ed90c, fabric-commands-v0@0.1.2+b7f9825d0c, fabric-registry-sync-v0@0.2.6+f3d8141b0c, fabric-blockrenderlayer-v1@1.1.4+c6a8ea890c, fabric-mining-levels-v0@0.1.1+b7f9825d0c, fabric-renderer-registries-v1@2.0.1+5a0f9a600c, fabric-loot-tables-v1@0.1.5+e08a73050c, fabric-events-lifecycle-v0@0.1.2+b7f9825d0c, wurst@v7.1.2-MC1.15.2, fabric@0.4.29+build.290-1.15, fabric-particles-v1@0.1.1+dfdb52d60c, fabric-models-v0@0.1.0+dfdb52d60c, fabric-item-groups-v0@0.1.6+ec40b2e10c, fabric-object-builders-v0@0.1.3+e4c9a9c30c, fabric-networking-v0@0.1.7+12515ed90c
18:51:01.636
18:51:01.728
SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Users/8bit_coder/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.8+build.18/sponge-mixin-0.8+build.18.jar Service=Knot/Fabric Env=CLIENT
18:51:01.887

Exception in thread "main" org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config fabric-networking-v0.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
	at net.fabricmc.loader.launch.common.FabricMixinBootstrap.addConfiguration(FabricMixinBootstrap.java:44)
	at net.fabricmc.loader.launch.common.FabricMixinBootstrap$$Lambda$62/103103526.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.fabricmc.loader.launch.common.FabricMixinBootstrap.init(FabricMixinBootstrap.java:83)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:133)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: java.lang.IllegalArgumentException: The specified resource 'fabric-networking-v0.mixins.json' was invalid or could not be read
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1090)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
	... 8 more
18:51:01.887
Process crashed with exit code 1`
What do I do? This is really bugging me and I'd like to be able to use fabric. It also crashes without any mods in the mods folder.

**Comment by i509VCB** [comment]
> wurst@v7.1.2-MC1.15.2
Sorry mate can't help you because of the hacked client you have installed.

**Comment by liach** [comment]
does this crash without the "wurst" mod? If it doesn't then consider using the api that matches the requirement of your "wurst" mod.

**Comment by 8bit-coder** [comment]
It still crashes without wurst, in fact it crashes with literally any fabric mod that I put in the folder(provided that it is built for the same minecraft, fabric, and fabric API version.)

**Comment by liach** [comment]
Can you try deleting the existing fabric api and redownloading it from curseforge and install it?

**Comment by Prospector** [comment]
Please send a full log using the Vanilla or MultiMC launcher without Wurst.

**Comment by liach** [comment]
Closing as the issue reporter failed to respond in a while, which prevents us from getting necessary info for fixing bugs if there is any.
