### ISSUE TITLE
Need help! Server crash and i don't know why

### ISSUE THREAD

**Issue by ahkui** [FabricMC/fabric#560]
here is the [crash-2020-04-08_14.25.48-server.txt](https://github.com/FabricMC/fabric/files/4451250/crash-2020-04-08_14.25.48-server.txt)

**Comment by liach** [comment]
Your server is too laggy and your server watchdog just terminated it. 
Change `max-tick-time` in your [`server.properties`](https://minecraft.gamepedia.com/Server.properties#Java_Edition_2) to `-1` from the default `60000`.
