### ISSUE TITLE
Installer for 1.15.2 is broken

### ISSUE THREAD

**Issue by Solverbolt** [FabricMC/fabric#566]
Jar file comes up empty, console states that the file is invalid, so its ignoring it during load up

**Comment by Solverbolt** [comment]
whatever. apparently expecting you dumpster fire programmers to actually do anything is on par with expecting any government official in any country to act like adults for longer than 5 minutes. I will just go back to Forge and use their tried and TRUE working system. Since apparently none of you can be trusted to actually support your own work

**Comment by Daomephsta** [comment]
It's only been 2 hours since you filed the issue.

**Comment by modmuss50** [comment]
You didnt provide enough infomation, and you waited a matter of minutes before making a fuss. Github issues arent the normal way to get support, Discord or IRC is.
