### ISSUE TITLE
Hot i can install the fabric api in intellij idea project?

### ISSUE THREAD

**Issue by ghost** [FabricMC/fabric#567]
When I want to test the mod, and launching the client, it crashes. I read about this error and realized that I need to install the fabric api so that everything works, but I do not know how to install it.

**Comment by liach** [comment]
You declare 
`modImplementation "net.fabricmc.fabric-api:fabric-api:0.5.1+build.294-1.15"` (or whatever fabric api version for your minecraft version, see https://modmuss50.me/fabric.html) in your `build.gradle` and then your development environment will launch with the fabric api.

**Comment by ghost** [comment]
> You declare
> `modImplementation "net.fabricmc.fabric-api:fabric-api:0.5.1+build.294-1.15"` (or whatever fabric api version for your minecraft version, see https://modmuss50.me/fabric.html) in your `build.gradle` and then your development environment will launch with the fabric api.

I hope I don’t have to re-create my whole mod? I just took right now for creating entities, and because of this, such a problem arose. Thanks for helping!
