### ISSUE TITLE
Could not find required mod: fabric requires {minecraft @ [~1.16-alpha.20.6.a]}

### ISSUE THREAD

**Issue by HypeSquidd** [FabricMC/fabric#569]
I'm trying to play on an anarchy server in minecraft, and since there's no impact client 1.16 I'm using wurst, the directions are to put the wurst client .jar file into mods and the fabric API 1.16
but then the error message: Could not find required mod: fabric requires {minecraft @ [~1.16-alpha.20.6.a]} pops up.
Anyone know whats happening?

**Comment by Ueaj-Kerman** [comment]
Hacks aren't supported
