### ISSUE TITLE
ModelVariantProviders not called for every state if one state loaded by vanilla

### ISSUE THREAD

**Issue by TwilightFlower** [FabricMC/fabric#571]
If a ModelVariantProvider chooses to not override one state and lets it load the vanilla way, it will not be called for any further states of that block. This is a rather niche bug but I'm having trouble finding a workaround.

**Comment by Jkmcameron** [comment]
Bump, still an issue. Not much else to be said other than what is said here. Not really niche at this point, seems more like an oversight

**Comment by Technici4n** [comment]
This will be addressed by the Model Loading API v1: #3145.

**Comment by Technici4n** [comment]
Fixed in #3145.
