### ISSUE TITLE
ID's are shifted by -1 in fabric api 20w16a

### ISSUE THREAD

**Issue by NeoTheLynx** [FabricMC/fabric#578]
When installing the fabric api on a server and then join with a client that does not use the fabric api mod, the ID's of the blocks and items are shifted by -1, example a bow is a apple.

![Image Of Bug](https://media.discordapp.net/attachments/698588774065635449/700187216475062282/unknown.png?width=1295&height=677)

**Comment by liach** [comment]
Hmm, can you try without the fabric registry sync mod (remove its reference from `fabric.mod.json` in the api mod jar)

**Comment by NeoTheLynx** [comment]
@liach that fixed the problem

**Comment by HumanGamer** [comment]
I had the same issue, and I can confirm this fixes the issue.

**Comment by asiekierka** [comment]
fabric-registry-sync does not freeze the IDs for vanilla registry entries - this is one of those TODOs I forgot to get around to, and this should be implemented ASAP (Carpet keeps running into it, among others).

**Comment by modmuss50** [comment]
Block Ids dont need to be saved, only sycned. I started looking into fixing all the issues here: https://github.com/FabricMC/fabric/pull/525

Including not doing anything with registrys that havent been modified.

**Comment by Prospector** [comment]
Duplicate of #122
