### ISSUE TITLE
Crashes, immediately upon start up

### ISSUE THREAD

**Issue by SpookyKitty** [FabricMC/fabric#581]
No matter what I try to do it won't work. It always ends up crashing with this text

Could not find required mod: fabric requires {minecraft @ [~1.15-alpha.19.42.a]}

**Comment by liach** [comment]
You are using fabric for Minecraft 19w42a. If you are not running 19w42a, the game will crash.

You need to download the fabric api for the Minecraft version you use at https://www.curseforge.com/minecraft/mc-mods/fabric-api/

**Comment by SpookyKitty** [comment]
Works now, thanks for the help!
