### ISSUE TITLE
20w16a Crash

### ISSUE THREAD

**Issue by MarinaMarissa** [FabricMC/fabric#582]
game version：20w16a
Fabric loader 0.8.2 build 194

Command: "C:\\Program Files\\Java\\jre1.8.0_45\\bin\\java.exe" -Dminecraft.client.jar=.minecraft\versions\20w16a\20w16a.jar -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx4096m -Dfml.ignoreInvalidMinecraftCertificates=true -Dfml.ignorePatchDiscrepancies=true -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump "-Djava.library.path=C:\\Users\\27303\\Documents\\Tencent Files\\2291550517\\FileRecv\\test\\XPLUS Snapshot\\.minecraft\\versions\\20w16a\\natives" -Dminecraft.launcher.brand=HMCL -Dminecraft.launcher.version=3.3.162 -cp "C:\\Users\\27303\\Documents\\Tencent Files\\2291550517\\FileRecv\\test\\XPLUS Snapshot\\.minecraft\\libraries\\net\\fabricmc\\tiny-mappings-parser\\0.2.2.14\\tiny-mappings-parser-0.2.2.14.jar;C:\\Users\\27303\\Documents\\Tencent Files\\2291550517\\FileRecv\\test\\XPLUS Snapshot\\.minecraft\\libraries\\net\\fabricmc\\sponge-mixin\\0.8+build.18\\sponge-mixin-0.8+build.18.jar;C:\\Users\\27303\\Documents\\Tencent Files\\2291550517\\FileRecv\\test\\XPLUS Snapshot\\.minecraft\\libraries\\net\\fabricmc\\tiny-remapper\\0.2.2.64\\tiny-remapper-0.2.2.64.jar;C:\\Users\\27303\\Documents\\Tencent Files\\2291550517\\FileRecv\\test\\XPLUS Snapshot\\.minecraft\\libraries\\net\\fabricmc\\fabric-loader-sat4j\\2.3.5.4\\fabric-loader-sat4j-2.3.5.4.jar;C:\\Users\\27303\\Documents\\Tencent Files\\2291550517\\FileRecv\\test\\XPLUS Snapshot\\.minecraft\\libraries\\com\\google\\jimfs\\jimfs\\1.1\\jimfs-1.1.jar;C:\\Users\\27303\\Documents\\Tencent Files\\2291550517\\FileRecv\\test\\XPLUS Snapshot\\.minecraft\\libraries\\org\\ow2\\asm\\asm\\8.0\\asm-8.0.jar;C:\\Users\\27303\\Documents\\Tencent Files\\2291550517\\FileRecv\\test\\XPLUS Snapshot\\.minecraft\\libraries\\org\\ow2\\asm\\asm-analysis\\8.0\\asm-analysis-8.0.jar;C:\\Users\\27303\\Documents\\Tencent Files\\2291550517\\FileRecv\\test\\XPLUS Snapshot\\.minecraft\\libraries\\org\\ow2\\asm\\asm-commons\\8.0\\asm-commons-8.0.jar;C:\\Users\\27303\\Documents\\Tencent Files\\2291550517\\FileRecv\\test\\XPLUS Snapshot\\.minecraft\\libraries\\org\\ow2\\asm\\asm-tree\\8.0\\asm-tree-8.0.jar;C:\\Users\\27303\\Documents\\Tencent Files\\2291550517\\FileRecv\\test\\XPLUS Snapshot\\.minecraft\\libraries\\org\\ow2\\asm\\asm-util\\8.0\\asm-util-8.0.jar;C:\\Users\\27303\\Documents\\Tencent Files\\2291550517\\FileRecv\\test\\XPLUS Snapshot\\.minecraft\\libraries\\com\\google\\guava\\guava\\21.0\\guava-21.0.jar;C:\\Users\\27303\\Documents\\Tencent Files\\2291550517\\FileRecv\\test\\XPLUS Snapshot\\.minecraft\\libraries\\net\\fabricmc\\intermediary\\20w16a\\intermediary-20w16a.jar;C:\\Users\\27303\\Documents\\Tencent Files\\2291550517\\FileRecv\\test\\XPLUS Snapshot\\.minecraft\\libraries\\net\\fabricmc\\fabric-loader\\0.8.2+build.194\\fabric-loader-0.8.2+build.194.jar;C:\\Users\\27303\\Documents\\Tencent Files\\2291550517\\FileRecv\\test\\XPLUS Snapshot\\.minecraft\\versions\\20w16a\\20w16a.jar" net.fabricmc.loader.launch.knot.KnotClient
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager
	at net.fabricmc.loader.launch.common.FabricLauncherBase.<clinit>(FabricLauncherBase.java:44)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.LogManager
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 2 more

**Comment by liach** [comment]
Is this a bug with HMCL that it does not include any Minecraft libraries in the classpath? I see no minecraft libraries on the classpath, such as gson, lwjgl, log4j (guava is there though)

Try with a different launcher or launch vanilla 20w16a before running the fabric game.

你这个启动命令行……怀疑是hmcl没设置好，启动的classpath里面没有minecraft本身的库，只有fabric的库。试试看启动原版后再启动带mod的，一般别的启动器都要获得原版的快照版本后才能加载fabric/forge的版本（依赖关系）

**Comment by coderbot16** [comment]
This appears to be a bug with HMCL, not with Fabric. Ensure that you have the latest version of HMCL, then try reporting the issue at https://github.com/huanghongxun/HMCL/issues.
