### ISSUE TITLE
Mixins shadowing final fields should use @Final

### ISSUE THREAD

**Issue by Chocohead** [FabricMC/fabric#587]
A more general clean-up problem, but with a purpose too. With newer Java versions mutating a final field will crash, so it is important that those which are changed are annotated with `@Mutable`. Therefore it is only reasonable that all the final shadowed fields are annotated accordingly so those which are mutated are marked too to avoid crashing.

Don't have a list of which ones need it, but I do know `MixinGameOptions#keysAll` needs it at least as that [crashes at launch](https://ghostbin.co/paste/troet).

**Comment by i509VCB** [comment]
Related to the conventions discussion otherwise in #510 and #637

**Comment by modmuss50** [comment]
This was fixed in 1.17
