### ISSUE TITLE
20w16a fabric-api

### ISSUE THREAD

**Issue by inklesspen1rus** [FabricMC/fabric#590]
When I install fabric-api 0.6.0 swords, pickaxe and other tools breaking anything faster (pickaxe breaking wood like axe for example)
MInecraft version 1.16 snapshot 20w16a
Fabric Installer: 0.5.2.39
Fabric Loader version: 0.8.2+build.194
Fabric-Api: 0.6.0+build325-1.16
Minecraft log:
[2020-04-22-5.log](https://github.com/FabricMC/fabric/files/4515738/2020-04-22-5.log)

**Comment by shedaniel** [comment]
Fixing in #589

**Comment by modmuss50** [comment]
Is this also an issue in 1.15.2?

**Comment by Player3324** [comment]
(should be unless I missed something in the port)

**Comment by modmuss50** [comment]
I will downgrade the builds on curseforge to a beta then. as this is quite a big issue...

**Comment by Prospector** [comment]
Fixed in 0.10.8
