### ISSUE TITLE
MCUpdater XML issue

### ISSUE THREAD

**Issue by smbarbour** [FabricMC/fabric#596]
The XML to be imported in MCUpdater modpacks to include Fabric is missing the `side="BOTH"` attribute for the Module and Submodule entries, which causes a server-side install to not include Fabric.

**Comment by liach** [comment]
~~Mind link to the xml? I am not aware that such an xml exists 🤔~~

Oh it's on website, @modmuss50 might take care of that :+1: https://fabricmc.net/use/?page=mcupdater

**Comment by modmuss50** [comment]
I will take a look, its generated in some php code that im less than familiar with

**Comment by NeRdTheNed** [comment]
@modmuss50 Any updates on this? I'm trying to use MCUpdater to manage a Fabric server, which is annoying if MCUpdater doesn't work!

**Comment by modmuss50** [comment]
Should now be fixed, thanks to asie.
