### ISSUE TITLE
Some sort of thing to add biomes to the vanilla biome source

### ISSUE THREAD

**Issue by Prospector** [FabricMC/fabric#6]

**Comment by asiekierka** [comment]
Could you please provide the necessary hook points?

**Comment by ProfessorProspector** [comment]
That's the issue...I can't figure out where they are or else I'd do it myself :P

**Comment by asiekierka** [comment]
I've looked into the problem domain, with help from Ansraer.

Short version: [WAAAAAAAAAAAAAAAAAAAAAAAAAAA](https://www.youtube.com/watch?v=czizBiAhHiI)

Long version:

* The BiomeGroupToBiomeLayer class is the one which determines the initial biome sampling. However, the way it's designed means that you can't safely just add custom biomes to the list - the arrays are static!
* We'd most likely need to add hooks after every layer in the game, allowing contextual modification, filtering *and* registration of your own layers. This is actually pretty hard.

At this point, I think the sanest solution... I don't know.

**Comment by asiekierka** [comment]
In general, I feel that the vanilla world generation mode should be left alone, with an extended world generation mode being added by either library mods or started (but extendable into custom ones) by API itself.

**Comment by grondag** [comment]
@Prospector Is this still a going concern?

**Comment by valoeghese** [comment]
Wait... this was a thing? :P
