### ISSUE TITLE
Multiple builtin item renderers for one item?

### ISSUE THREAD

**Issue by Juuxel** [FabricMC/fabric#602]
The builtin item renderer API (#563) also allows replacing the builtin renderers of vanilla items (intended feature), but there will be a crash if multiple mods want to replace the renderer of one item.

![](https://user-images.githubusercontent.com/6596629/80839617-42669b80-8c04-11ea-80bd-24375df014b2.png)

Should we make the implementation use a `Multimap` instead, and render the item with all registered builtin renderers?

**Comment by i509VCB** [comment]
I'd say hard fail if multiple mods register a renderer for the same item (but allow querying ). Maybe throw a special exception.

Rendering with all registered builtin renderers isn't a great idea since it makes things look weird.

**Comment by Juuxel** [comment]
Hard fail with an `IllegalArgumentException` is the current and documented behaviour. Querying could be a good idea.
