### ISSUE TITLE
Cant't launch mod in the Eclipse workspace

### ISSUE THREAD

**Issue by Bulldog83** [FabricMC/fabric#606]
There is an issue when I try to launch mod in the debug mode in the Eclipse IDE.

```
Exception in thread "main" java.lang.RuntimeException: Failed to read accessWidener file from mod fabric-object-builder-api-v1
	at net.fabricmc.loader.transformer.accesswidener.AccessWidener.loadFromMods(AccessWidener.java:60)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:130)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
Caused by: java.lang.RuntimeException: Namespace (intermediary) does not match current runtime namespace (named)
	at net.fabricmc.loader.transformer.accesswidener.AccessWidener.read(AccessWidener.java:78)
	at net.fabricmc.loader.transformer.accesswidener.AccessWidener.loadFromMods(AccessWidener.java:58)
	... 3 more
```
Minecraft 20w18a
Fabric 0.10.2+build.337-1.16
Yarn 20w18a-build.9
Loader 0.8.2+build.194
Loom 0.4.3

**Comment by baka4n** [comment]
You can try build.14 version.

**Comment by baka4n** [comment]
I have tried to build both build.4 and build.14 without problems

**Comment by Bulldog83** [comment]
With build 14 the problem still exists. Also I have a warning while running 'gradlew eclipse' command:
```
:remapping fabric-object-builders-v0-0.5.0+bf7c167ae8.jar (TinyRemapper, intermediary -> named)
duplicate input class net/fabricmc/fabric/mixin/object/builder/MixinBlock, from C:\Users\Bulldog\.gradle\caches\modules-2\files-2.1\net.fabricmc.fabric-api\fabric-object-builder-api-v1\1.0.1+bf7c167ae8\a16920d5ed6317d228db8e97dc1b4fb882da900f\fabric-object-builder-api-v1-1.0.1+bf7c167ae8.jar and C:\Users\Bulldog\.gradle\caches\modules-2\files-2.1\net.fabricmc.fabric-api\fabric-object-builders-v0\0.5.0+bf7c167ae8\efdddd05c8cc477e2f3beb5860a6763b71b2986b\fabric-object-builders-v0-0.5.0+bf7c167ae8.jar
```
I've tried to clear gradle cache.

**Comment by modmuss50** [comment]
You need to update loom to 0.2.7. After doing that you may need to delete the remapped mods folder, this will be in your projects .gradle folder

**Comment by Bulldog83** [comment]
With loom 0.2.7 errors still exists :/
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'JustMap'.
> Failed to find mapping for EntryTriple{owner=net/minecraft/class_4970$class_2251,name=<init>,desc=(Lnet/minecraft/class_3614;Lnet/minecraft/class_3620;)V}

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 54s
duplicate input class net/fabricmc/fabric/mixin/object/builder/MixinBlock, from C:\Users\Bulldog\.gradle\caches\modules-2\files-2.1\net.fabricmc.fabric-api\fabric-object-builders-v0\0.5.0+bf7c167ae8\efdddd05c8cc477e2f3beb5860a6763b71b2986b\fabric-object-builders-v0-0.5.0+bf7c167ae8.jar and C:\Users\Bulldog\.gradle\caches\modules-2\files-2.1\net.fabricmc.fabric-api\fabric-object-builder-api-v1\1.0.1+bf7c167ae8\a16920d5ed6317d228db8e97dc1b4fb882da900f\fabric-object-builder-api-v1-1.0.1+bf7c167ae8.jar
```
With Minecraft 1.15.2 all are ok.

**Comment by liach** [comment]
We do need to fix this object builder mixin clash immediately

**Comment by Bulldog83** [comment]
I've tryed to clear all 20w18a gradle cashe, remove all eclipse configs, clear all 20w18a mapped files.
All the same, I have this error:
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'JustMap'.
> Failed to find mapping for EntryTriple{owner=net/minecraft/class_4970$class_2251,name=<init>,desc=(Lnet/minecraft/class_3614;Lnet/minecraft/class_3620;)V}
```
And, as a consequence:
```
duplicate input class net/fabricmc/fabric/mixin/object/builder/MixinBlock, from C:\Users\Bulldog\.gradle\caches\modules-2\files-2.1\net.fabricmc.fabric-api\fabric-object-builders-v0\0.5.0+bf7c167ae8\5c6fcd0b9de00a60deb87ee3ead959d46b35d022\fabric-object-builders-v0-0.5.0+bf7c167ae8.jar and C:\Users\Bulldog\.gradle\caches\modules-2\files-2.1\net.fabricmc.fabric-api\fabric-object-builder-api-v1\1.0.1+bf7c167ae8\660d66966bbe9768e589a8f29897538335969d50\fabric-object-builder-api-v1-1.0.1+bf7c167ae8.jar
```
I use gradle-wrapper from the last fabric-example-mod.

**Comment by Bulldog83** [comment]
20w19a - problem still exists.

**Comment by liach** [comment]
The title should be `Duplicate MixinBlock` from object builder v0 and object builder api v1

**Comment by Bulldog83** [comment]
This error still exists:
```
:remapping fabric-object-builder-api-v1-1.2.0+57dbcc4cd2.jar (TinyRemapper, intermediary -> named)

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'JustMap'.
> Failed to find mapping for EntryTriple{owner=net/minecraft/class_4970$class_2251,name=<init>,desc=(Lnet/minecraft/class_3614;Lnet/minecraft/class_3620;)V}

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 59s
```

**Comment by i509VCB** [comment]
That PR didn't specifically target the EntryTriple issue but rather another issue elsewhere with some classes having identical names.

Really odd since I am not having this issue with bulky shulkies. 

Does those issue occur with Loom `0.2.7`?

**Comment by Bulldog83** [comment]
Yes, I use: ```id 'fabric-loom' version '0.2.7-SNAPSHOT'```

**Comment by Bulldog83** [comment]
I have identical build.gradle scripts for all my branches, except a dependencies versions. For 1.15.2 all works fine, for 1.16 appeared this error since 20w18a.

**Comment by i509VCB** [comment]
Hmm, so I cloned JustMap's 1.16 branch and set modmenu to `transitive = false`. I did manage to get an access widener error this time related to namespaces (wrong namespace).

So in your `build.gradle`, see what happens if you change your modmenu entry to this:
```groovy
	modCompile ("io.github.prospector:modmenu:${project.modmenu_version}") {
		transitive = false
	}
```

EDIT: The modmenu change did let the jar build but it fails in `runClient`

**Comment by Bulldog83** [comment]
This error appears only ones, at first run of the 'gradlew eclipse' command. At second time, this error not appears, but game runs with crash. If you'll delete the ```fabric-object-builder-api-v1``` cache, the error will appear again.

**Comment by i509VCB** [comment]
Huh so it seems to be an accesswidener issue since the error message is similar to here:

https://github.com/FabricMC/fabric-loom/blob/dev/0.4/src/main/java/net/fabricmc/loom/util/accesswidener/AccessWidenerRemapper.java#L101-L109

This is really odd.

**Comment by modmuss50** [comment]
Make sure you are using v2 mappings, I need to improve the access widner remapping so this doesnt happen. Its a bit of a fluke that it works on v2 mappings.

**Comment by i509VCB** [comment]
Bingo:
https://github.com/Bulldog83/JustMap/blob/master/build.gradle#L39

@Bulldog83 See what happens if you use v2 mappings

**Comment by Bulldog83** [comment]
It works. Thanks!
