### ISSUE TITLE
Container issues

### ISSUE THREAD

**Issue by RedstoneParadox** [FabricMC/fabric#61]
So it seems that if you attempt to open a Container (Menu) that is registered to Fabrics registry instead of directly to the vanilla one, it will open the player's Container (Menu) on the server; resulting in various issues such as the clicking on a slot with an id of greater than 44 causing an OOD Exception on the slotList of the Container (Menu), slots 1-8 (hotbar) not being interactable, and other things that result from such desyncs.

**Comment by asiekierka** [comment]
Fixed
