### ISSUE TITLE
Any way to install on Vivecraft?

### ISSUE THREAD

**Issue by RusJJ** [FabricMC/fabric#612]
Q in a title. Any ways?

**Comment by liach** [comment]
Vivecraft I recall depends on forge, so not yet

**Comment by liach** [comment]
Hmm, you might be able to tweak fabric loader's 1.15.2 profile to refer to the game installation of vivecraft's 1.15.2 baseedit, but cannot guarantee that this runs well. And that is related to the loader and not the API
