### ISSUE TITLE
Fabric in Server Failed 1.15.2: Failed to setup Fabric server environment!

### ISSUE THREAD

**Issue by wnchstrboy** [FabricMC/fabric#616]
![srevr3 edailed farbic ](https://user-images.githubusercontent.com/65130964/81507473-4741e400-92c3-11ea-8a2b-8c00f62e3e9d.png)

It keeps failing and saying this :(

**Comment by liach** [comment]
try installing fabric loader on server again. do a fresh install.

**Comment by wnchstrboy** [comment]
It worked! thank you

**Comment by liach** [comment]
Glad to hear that. Have fun!
