### ISSUE TITLE
Particle texture not showing

### ISSUE THREAD

**Issue by RandomOnlineName** [FabricMC/fabric#620]
Currently I am trying to make a mod that adds a couple of new particles to the game but dispite using code from other minecraft particles(eg: campfire) the texture won't load but there is no sort of warning in the console to suggest that.
I think it could have something to do with the json file however but i am probably wrong.`
these files are the particles folder with json files in it, the textures folder for the mod, the particles folder containing the classes and the main class with modInitializer in it.
[particles.zip](https://github.com/FabricMC/fabric/files/4614865/particles.zip)
[textures.zip](https://github.com/FabricMC/fabric/files/4614868/textures.zip)
[particles.zip](https://github.com/FabricMC/fabric/files/4614874/particles.zip)
[firstmod.zip](https://github.com/FabricMC/fabric/files/4614875/firstmod.zip)

`

**Comment by JamiesWhiteShirt** [comment]
You are probably encountering the issue resolved by both #527 and #534, but they have been stuck in review hell for months. I left a comment describing a workaround on #527 if you are interested.

**Comment by wieping-shaddow** [comment]
Thanks that worked and the particle os registering but now an error is being thown on startup java.lang.IllegalStateException: Redundant texture list for particle firstmod:test_particle which I have tried to understand but I can't find what is causing it.

**Comment by RandomOnlineName** [comment]
I found the workaround and it seems good but I don't understand from that thread how it is suppost to work.

**Comment by i509VCB** [comment]
Either #527 or #534 needs to be merged soon.
