### ISSUE TITLE
Server Logs Not Showing

### ISSUE THREAD

**Issue by izumi-06** [FabricMC/fabric#621]
The server logs and chat doesnt show in the gui when running

**Comment by i509VCB** [comment]
This is a known issue with fabric-loader here: https://github.com/FabricMC/fabric-loader/issues/119

We have not figured out why the issue has occured but the simple workaround is the run the server in `nogui` mode by adding the `-nogui` argument to the end of the start script and use the command line to input.

**Comment by modmuss50** [comment]
I have a possibe idea on how to fix this, I think copying the server log4j config into the launch jar might slove the issue. Needs testing however.

**Comment by TorJonasHansen** [comment]
> I have a possibe idea on how to fix this, I think copying the server log4j config into the launch jar might slove the issue. Needs testing however.



> I have a possibe idea on how to fix this, I think copying the server log4j config into the launch jar might slove the issue. Needs testing however.

Could u show me how?

**Comment by i509VCB** [comment]
Closing since this is not an issue with Fabric API and is being tracked on Fabric Loader.
