### ISSUE TITLE
Not able to setup new project

### ISSUE THREAD

**Issue by PssbleTrngle** [FabricMC/fabric#624]
When trying to import the example fabric project via the build.gradle file in IDEA, I get the following error as gradle tries to to build.

```
Caused by: java.lang.ClassNotFoundException: org.gradle.api.internal.plugins.DefaultConvention
```

I don't think that gradle is outdated, as it is shipped with IDEA which is up to date.

The full stack trace is [here](https://pastebin.com/eg0QHcJK)

**Comment by PssbleTrngle** [comment]
The gradle plugin is also up to date

**Comment by liach** [comment]
Idea should be using the gradle as defined in project's gradle wrapper. Check if idea is importing the gradle project using the local gradle wrapper from the project.

**Comment by PssbleTrngle** [comment]
I set it to the local gradle wrapper

**Comment by liach** [comment]
Mind close the project in idea, remove it from recent projects, and then open the `build.gradle` file fresh and see the results?

**Comment by PssbleTrngle** [comment]
I had this issue with two seperate projects I wanted to create now, I think its a problem with the Jetbrains Gradle Plugin

**Comment by liach** [comment]
Hmm, what idea version are you using? Mind update to 2020.1

**Comment by PssbleTrngle** [comment]
Seems like I was still on 2018.3 without getting an update notification, my bad.
Works now on 2020
