### ISSUE TITLE
Could not execute entrypoint stage 'client' due to errors, provided by 'replaymod'!

### ISSUE THREAD

**Issue by JhonatanSanga** [FabricMC/fabric#628]
Cliente> [18:19:08] [main/INFO]: Setting user: Jhonatan58_
Cliente> [18:19:11] [main/INFO]: Definitely not up to no good
Cliente> [18:19:12] [main/INFO]: [Indigo] Registering Indigo renderer!
Cliente> [18:19:12] [main/INFO]: [Indigo] Compatibility mode enabled.
Cliente> ---- Minecraft Crash Report ----
Cliente> // Daisy, daisy...
Cliente> 
Cliente> Time: 20/05/20 18:19
Cliente> Description: Initializing game
Cliente> 
Cliente> java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'replaymod'!
Cliente> 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
Cliente> 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
Cliente> 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
Cliente> 	at net.minecraft.class_310.method_1503(class_310.java)
Cliente> 	at net.minecraft.class_310.method_1514(class_310.java:394)
Cliente> 	at net.minecraft.client.main.Main.main(Main.java:155)
Cliente> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Cliente> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
Cliente> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
Cliente> 	at java.lang.reflect.Method.invoke(Unknown Source)
Cliente> 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
Cliente> 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
Cliente> 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Cliente> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Cliente> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
Cliente> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
Cliente> 	at java.lang.reflect.Method.invoke(Unknown Source)
Cliente> 	at net.minecraft.a.m.main(Unknown Source)
Cliente> Caused by: java.lang.ClassCastException: net.minecraft.class_310 cannot be cast to com.replaymod.core.mixin.MinecraftAccessor
Cliente> 	at com.replaymod.replay.ReplayModReplay.initClient(ReplayModReplay.java:168)
Cliente> 	at java.util.ArrayList.forEach(Unknown Source)
Cliente> 	at com.replaymod.core.ReplayMod.onInitializeClient(ReplayMod.java:300)
Cliente> 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
Cliente> 	... 17 more
Cliente> 
Cliente> 
Cliente> A detailed walkthrough of the error, its code path and all known details is as follows:
Cliente> ---------------------------------------------------------------------------------------
Cliente> 
Cliente> -- Head --
Cliente> Thread: Client thread
Cliente> Stacktrace:
Cliente> 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
Cliente> 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
Cliente> 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
Cliente> 	at net.minecraft.class_310.method_1503(class_310.java)
Cliente> 
Cliente> -- Initialization --
Cliente> Details:
Cliente> Stacktrace:
Cliente> 	at net.minecraft.class_310.method_1514(class_310.java:394)
Cliente> 	at net.minecraft.client.main.Main.main(Main.java:155)
Cliente> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Cliente> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
Cliente> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
Cliente> 	at java.lang.reflect.Method.invoke(Unknown Source)
Cliente> 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
Cliente> 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
Cliente> 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Cliente> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Cliente> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
Cliente> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
Cliente> 	at java.lang.reflect.Method.invoke(Unknown Source)
Cliente> 	at net.minecraft.a.m.main(Unknown Source)
Cliente> 
Cliente> -- System Details --
Cliente> Details:
Cliente> 	Minecraft Version: 1.14.4
Cliente> 	Minecraft Version ID: 1.14.4
Cliente> 	Operating System: Windows 10 (amd64) version 10.0
Cliente> 	Java Version: 1.8.0_241, Oracle Corporation
Cliente> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Cliente> 	Memory: 457990040 bytes (436 MB) / 939524096 bytes (896 MB) up to 1073741824 bytes (1024 MB)
Cliente> 	CPUs: 8
Cliente> 	JVM Flags: 9 total; -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:+IgnoreUnrecognizedVMOptions -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
Cliente> 	Fabric Mods: 
Cliente> 		fabric: Fabric API 0.4.2+build.246-1.14
Cliente> 		fabric-api-base: Fabric API Base 0.1.2+28f8190f42
Cliente> 		fabric-biomes-v1: Fabric Biomes (v1) 0.1.1+28f8190f42
Cliente> 		fabric-commands-v0: Fabric Commands (v0) 0.1.2+28f8190f42
Cliente> 		fabric-containers-v0: Fabric Containers (v0) 0.1.3+28f8190f42
Cliente> 		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.2+28f8190f42
Cliente> 		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+28f8190f42
Cliente> 		fabric-dimensions-v1: fabric-dimensions-v1 0.1.1+28f8190f42
Cliente> 		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.1.2+28f8190f42
Cliente> 		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.1+28f8190f42
Cliente> 		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.1+28f8190f42
Cliente> 		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+933c24c242
Cliente> 		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.1+28f8190f42
Cliente> 		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.1+28f8190f42
Cliente> 		fabric-models-v0: Fabric Models (v0) 0.1.0+933c24c242
Cliente> 		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.1+28f8190f42
Cliente> 		fabric-networking-v0: Fabric Networking (v0) 0.1.4+28f8190f42
Cliente> 		fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.2+28f8190f42
Cliente> 		fabric-particles-v1: fabric-particles-v1 0.1.1+933c24c242
Cliente> 		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.3+28f8190f42
Cliente> 		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.1.1+933c24c242
Cliente> 		fabric-renderer-indigo: Fabric Renderer - Indigo 0.1.14+28f8190f42
Cliente> 		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.2+28f8190f42
Cliente> 		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.3+28f8190f42
Cliente> 		fabric-rendering-v0: Fabric Rendering (v0) 0.1.2+28f8190f42
Cliente> 		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.4+28f8190f42
Cliente> 		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+d423005742
Cliente> 		fabric-textures-v0: Fabric Textures (v0) 0.1.4+933c24c242
Cliente> 		fabricloader: Fabric Loader 0.8.4+build.198
Cliente> 		minecraft: Minecraft 1.14.4
Cliente> 		mm: Manningham Mills 1.8
Cliente> 		optifabric: Optifabric 0.7.1
Cliente> 		org_slf4j_slf4j-api: slf4j-api 1.7.29
Cliente> 		org_slf4j_slf4j-simple: slf4j-simple 1.7.29
Cliente> 		org_zeroturnaround_zt-zip: zt-zip 1.13
Cliente> 		replaymod: Replay Mod 1.14.4-2.3.0
Cliente> 	Launched Version: fabric-loader-0.8.4+build.198-1.14.4
Cliente> 	LWJGL: 3.2.2 build 10
Cliente> 	OpenGL: NO CONTEXT
Cliente> 	GL Caps: 
Cliente> 	Using VBOs: Yes
Cliente> 	Is Modded: Definitely; Client brand changed to 'fabric'
Cliente> 	Type: Client (map_client.txt)
Cliente> 	Resource Packs: ~~ERROR~~ NullPointerException: null
Cliente> 	Current Language: ~~ERROR~~ NullPointerException: null
Cliente> 	CPU: <unknown>
Cliente> 	OptiFine Version: OptiFine_1.14.4_HD_U_F4
Cliente> 	OptiFine Build: 20191025-153543
Cliente> 	Shaders: null
Cliente> 	OpenGlVersion: null
Cliente> 	OpenGlRenderer: null
Cliente> 	OpenGlVendor: null
Cliente> 	CpuCount: 0
Cliente> #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\PC-2\AppData\Roaming\.minecraft\crash-reports\crash-2020-05-20_18.19.12-client.txt
El juego termino de forma incorrecta (exit code -1)
Informe de error detectado en: C:\Users\PC-2\AppData\Roaming\.minecraft\crash-reports\crash-2020-05-20_18.19.12-client.txt
El error fue generado en el juego y no en el launcher por lo que no se trata de un error del launcher.
Borrando C:\Users\PC-2\AppData\Roaming\.minecraft\versions\fabric-loader-0.8.4+build.198-1.14.4\fabric-loader-0.8.4+build.198-1.14.4-natives-130648863021700
Los archivos nativos serán removidos una vez que cierre el launcher

**Comment by liach** [comment]
Read the title, replay mod has a problem. It is not registering its accessor mixins correctly
