### ISSUE TITLE
Lets Talk: Inconsistent names for classes and mixins.

### ISSUE THREAD

**Issue by i509VCB** [FabricMC/fabric#637]
This may sound similar to #510 but this specifically for class names.

### Why is this an issue?

The naming of classes makes the classes' purpose obvious. The naming style can help with reviews and maintenance since maintainers and reviewers can see very quickly see what the original purpose of the class was.

Across the entire fabric api project, names are quite inconsistent due to many contributors and maintainers. And the changing standards over at yarn also have an influence on the naming of this project.

Finally, a project looks more professional when naming is consistent across the entire board.

### **For Accessors:**
**Target**Hooks
Example:
[EntityHooks](https://github.com/FabricMC/fabric/blob/1.16/fabric-dimensions-v1/src/main/java/net/fabricmc/fabric/mixin/dimension/EntityHooks.java)

**Target**Accessor
Example:
[KeyCodeAccessor](https://github.com/FabricMC/fabric/blob/1.16/fabric-keybindings-v0/src/main/java/net/fabricmc/fabric/mixin/client/keybinding/KeyCodeAccessor.java)

Accessor**Target**
Example (Inside of a PR):
[AccessorRegistry](https://github.com/FabricMC/fabric/pull/525/files#diff-641401b19fe22b107baf4525595a7475R110)

Mixin**Target** (Not actually a normal mixin)
Example:
[MixinFormat4ResourcePack](https://github.com/FabricMC/fabric/blob/1.16/fabric-resource-loader-v0/src/main/java/net/fabricmc/fabric/mixin/resource/loader/MixinFormat4ResourcePack.java)

Throughout the codebase, **Target**Accessor is the most widely used.

### **For Mixins**

Currently, all mixins in the 1.16 branch use Mixin**Target**. Throughout the codebase, almost every class uses natural language order for names, such as `LootEntryTypeRegistryImpl`, `FabricBakedModel`, `CommandRegistrationCallback`. This naming between classes and mixin class names is inconsistent. For additional consideration, [yarn's conventions](https://github.com/FabricMC/yarn/blob/20w21a/CONVENTIONS.md) require the use of natural language order.

### **For Duck Interfaces**

For clarification, a duck interface is an interface which is implemented onto a class using a mixin. Public facing duck interfaces in api packages, are not counted in this section, and should be the exception.

**Target**Hooks (ish) (Sometimes it refers to an arbitrary name or the target)
Example:
[FabricTagHooks](https://github.com/FabricMC/fabric/blob/1.16/fabric-tag-extensions-v0/src/main/java/net/fabricmc/fabric/impl/tag/extension/FabricTagHooks.java)

**Target**Hook (ish) (Similar to above)
Example:
[ServerPlayerEntitySyncHook](https://github.com/FabricMC/fabric/blob/1.16/fabric-containers-v0/src/main/java/net/fabricmc/fabric/impl/container/ServerPlayerEntitySyncHook.java)

**Target**Internals
Example:
[BlockSettingsInternals](https://github.com/FabricMC/fabric/blob/1.16/fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/impl/object/builder/BlockSettingsInternals.java)

Access**Target**
Example:
[AccessAmbientOcclusionCalculator](https://github.com/FabricMC/fabric/blob/1.16/fabric-renderer-indigo/src/main/java/net/fabricmc/fabric/impl/client/indigo/renderer/accessor/AccessAmbientOcclusionCalculator.java)

**Target**Extensions
Example:
[ItemGroupExtensions](https://github.com/FabricMC/fabric/blob/1.16/fabric-item-groups-v0/src/main/java/net/fabricmc/fabric/impl/item/group/ItemGroupExtensions.java)

**Target**Accessor (Not actually an accessor mixin)
Example:
[CustomPayloadC2SPacketAccessor](https://github.com/FabricMC/fabric/blob/1.16/fabric-networking-v0/src/main/java/net/fabricmc/fabric/impl/networking/CustomPayloadC2SPacketAccessor.java)

**Target**Manager
Example:
[VanillaParticleManager](https://github.com/FabricMC/fabric/blob/1.16/fabric-particles-v1/src/main/java/net/fabricmc/fabric/impl/client/particle/VanillaParticleManager.java)

### **Public facing api class names (Not mixin related)**

This is the most consistent area, as all classes follow the natural language order and have reasonable names.

### **Private facing implementation class names (Not mixin related)**

Classes here seem to generally follow the natural language order. The infrequent exceptions are due to naming of vanilla counterparts or other reasons.

### **The steps to a possible solution**

* [ ] Debate the naming scheme that fabric api as a project should adopt.
* [ ] Write a PR defining this naming scheme in a `CONVENTIONS.MD` similarly to [Yarn](https://github.com/FabricMC/yarn/blob/20w21a/CONVENTIONS.md)
* [ ] Pass the conventions PR through last call in order to iron out final minor issues
* [ ] Upon merging of the conventions PR, all future PRs shall be subject to the new naming scheme.
* [ ] At some point in the future, some PRs (advise is multiple PRs for quicker reviews) to migrate old code over to the new naming scheme.

**Optional:**
* [ ] In the future if a `CONTRIBUTING.MD` is written, link to the `CONVENTIONS.MD` file.

**Comment by modmuss50** [comment]
All of the mixin names are now validated at build time, if you feel like there is still stuff to be done feel free to open a new issue based on the current state of things.
