### ISSUE TITLE
Indigo applying diffuse shading twice on modded meshes

### ISSUE THREAD

**Issue by grondag** [FabricMC/fabric#638]
![image](https://user-images.githubusercontent.com/6106235/82756036-5ed1a000-9d8c-11ea-8524-78e8b0e5a214.png)

All these blocks are white concrete. Note how the top face is fine.

I'll get a PR going.

**Comment by modmuss50** [comment]
I assume this is in 1.16?

**Comment by grondag** [comment]
Yes, only affects 1.16.  They moved the diffuse shading to chunk bake time or in GPU, which is what Indigo/Canvas want anyway so that it can be controlled.  Noticed it during Canvas port.   Should be an easy fix.

**Comment by grondag** [comment]
What I think should be the fix took like two minutes. I'm spending my whole day updating all my crap to the latest snapshot to test it...

**Comment by oliviathevampire** [comment]
finally! would you be able to fix a bug where the sides of doors are darker also?

**Comment by grondag** [comment]
> finally! would you be able to fix a bug where the sides of doors are darker also?

You should log defects you want to see fixed.  Screenshots and steps to reproduce improve chance of fixing.
