### ISSUE TITLE
Modules don't have module dependencies in the POM

### ISSUE THREAD

**Issue by Juuxel** [FabricMC/fabric#646]
For example, registry sync depends on api-base and networking, but it only has Loader as a dependency:
![](https://media.discordapp.net/attachments/566276937035546624/715833797978882138/unknown.png)

This is probably caused by modules using `compile` and Loom not having non-mod dependencies in the POM (FabricMC/fabric-loom#200).

**Comment by kvverti** [comment]
Fixing this issue is required for implementing https://gist.github.com/kvverti/3fc6a05d974210f785a9a751d5e0ae28

**Comment by i509VCB** [comment]
PR #1104 should fix this?

**Comment by Juuxel** [comment]
This is fixed now. :tada:
