### ISSUE TITLE
[fabric-biomes-v1] Crash upon adding biomes to the Nether generator

### ISSUE THREAD

**Issue by Hugman76** [FabricMC/fabric#650]
**Links**
- [Used method](https://github.com/FabricMC/fabric/blob/c6ab3e1b2d2cf0691a0083e6d7445a2014c63dd4/fabric-biomes-v1/src/main/java/net/fabricmc/fabric/api/biomes/v1/NetherBiomes.java#L37)
- [Method usage](https://github.com/Hugman76/Mubble/blob/7dcf1c8b82ce2065693de27a4f92195a2055758a/src/main/java/hugman/mubble/init/world/MubbleBiomes.java#L44)
- [crash-2020-05-31_10.44.25-client.txt](https://github.com/FabricMC/fabric/files/4707375/crash-2020-05-31_10.44.25-client.txt)

**Crash details**
`Caused by: java.lang.ClassCastException: hugman.mubble.objects.world.biome.MushroomNetherWastesBiome cannot be cast to com.mojang.datafixers.util.Pair`
Occurs on selecting "Singleplayer" on the main menu

**Comment by i509VCB** [comment]
For maintainers, this is 20w22a
