### ISSUE TITLE
20W22A commands

### ISSUE THREAD

**Issue by Markus23** [FabricMC/fabric#659]
Registering commands for integrated servers
it does not work

**Comment by LemmaEOF** [comment]
This is an issue with 22a itself, and not something we have much control over. For now, we have disabled registration of commands, and will reactivate it once Mojang fixes it.

**Comment by modmuss50** [comment]
Vanilla bug, https://bugs.mojang.com/browse/MC-186109 It should start working again once vanilla fixes it, hopefully today.
