### ISSUE TITLE
[1.16 pre1] Can't load mods datapack on server

### ISSUE THREAD

**Issue by AsakuraFuuko** [FabricMC/fabric#662]
[12:21:26] [main/WARN]: Missing data pack fabric/fabric-tool-attribute-api-v1
[12:21:26] [main/WARN]: Missing data pack fabric/expandedstorage
[12:21:26] [main/WARN]: Missing data pack fabric/simple_backpack

[12:21:26] [main/INFO]: Reloading ResourceManager: Default, craftingpp.zip, treecapitator-v2-5-4-1568017495.zip
[12:21:27] [Worker-Main-9/INFO]: Loaded 7 recipes

**Comment by haykam821** [comment]
What version of Fabric loader and Fabric API are you using?

**Comment by AsakuraFuuko** [comment]
Fabric Loader : 0.8.7+build.201
Fabric API : 0.11.4+build.353-1.16

**Comment by i509VCB** [comment]
Is there anything else that appears in the log?

**Comment by AsakuraFuuko** [comment]
emm, nothing
I can see the SimpleBackpack mod in the client's log, but the server cannot see it. And cannot craft backpacks on the server. Sorry for my bad english.

This mod
https://www.curseforge.com/minecraft/mc-mods/simple-backpack-fabric

server side
> [13:12:36] [main/INFO]: Reloading ResourceManager: Default
[13:12:37] [Worker-Main-10/INFO]: Loaded 7 recipes

client side
> [13:15:12] [main/INFO]: Reloading ResourceManager: Default, Fabric Renderer API (v1), Fabric Networking Block Entity (v0), Fabric Key Bindings (v0), Mod Menu, Fabric Tool Attribute API (v1), Fabric Renderer - Indigo, Fabric Containers (v0), Fabric Object Builder API (v1), Fabric Biomes (v1), Roughly Enough Items, Fabric Events Interaction (v0), Fabric Crash Report Info (v1), Fabric API Base, Fabric Rendering (v0), Fabric Rendering (v1), Cloth Config v2, Fabric Rendering Data Attachment (v1), Auto Config v1 Updated, Fabric Resource Loader (v0), Fabric Textures (v0), Fabric Content Registries (v0), Fabric Tag Extensions (v0), Fabric Rendering Fluids (v1), Fabric Registry Sync (v0), Fabric BlockRenderLayer Registration (v1), **_SimpleBackpack_**, Fabric Mining Levels (v0), Fabric Renderer Registries (v1), Fabric Loot Tables (v1), Fabric Events Lifecycle (v0), Fabric API, Fabric Models (v0), Fabric Item Groups (v0), Fabric Object Builders (v0), Fabric Networking (v0)
[13:15:15] [main/INFO]: OpenAL initialized.

**Comment by i509VCB** [comment]
Hmm, are there any issues with the mod's datapack?

**Comment by AsakuraFuuko** [comment]
Maybe not? There are only three recipes in the datapack.
UPDATE: I tried other mods and had the same issues.

**Comment by LemmaEOF** [comment]
Looks like Modmuss' fix didn't work, then. Time for me to take a look.

**Comment by LemmaEOF** [comment]
I think I might have found the issue. `ResourcePackManager` isn't used directly on the server; a subclass of it is. I need to find that subclass and do the injection there for it to work.

**Comment by LemmaEOF** [comment]
Hm, it doesn't seem to be that...

**Comment by LemmaEOF** [comment]
WAIT A SECOND! MOD DATAPACKS ARE STARTING DEFAULT DISABLED!

**Comment by i509VCB** [comment]
Weirdly mod datapacks work in dev for me, but haven't tested a real server yet.

**Comment by LemmaEOF** [comment]
them starting disabled is indeed a problem, it looks, but might not be the *whole* problem.

**Comment by LemmaEOF** [comment]
.....uh,

**Comment by Boundarybreaker** [comment]
![Capto_Capture 2020-06-05_01-42-08_AM](https://user-images.githubusercontent.com/6722691/83856010-c4e3ee80-a6cd-11ea-99d8-6fa7fd5ccdff.png)
MODMUSS.

**Comment by LemmaEOF** [comment]
![Capto_Capture 2020-06-05_01-44-23_AM](https://user-images.githubusercontent.com/6722691/83856239-155b4c00-a6ce-11ea-9586-9e374fed6f12.png)
MODMUSS.

**Comment by LemmaEOF** [comment]
there's *some* stuff that MixinResourcePackManager does client-only and some not. Time to split it up!

**Comment by LemmaEOF** [comment]
Alright, this is fixed, but I'm gonna make mod resource packs auto-enable before I do anything else.

**Comment by LemmaEOF** [comment]
#663
