### ISSUE TITLE
Feature Suggestion: Expand The Data Pack/Recipe System

### ISSUE THREAD

**Issue by SmushyTaco** [FabricMC/fabric#677]
A perfect example of this is: https://www.curseforge.com/minecraft/mc-mods/nbt-crafting

It builds upon the data pack/recipe system to give it more functionality and I think having something like this integrated in the Fabric API would be amazing since most people would find a use out of it.

**Comment by haykam821** [comment]
Things like this aren't generally considered to be in scope for Fabric API, as they modify vanilla mechanics.

Mod developers generally should register a special crafting recipe type, and since I believe those are largely hardcoded, a module for that instead could be added.

**Comment by Technici4n** [comment]
This is out of scope for fabric API due to maintainability issues (we absolutely don't want to change vanilla behavior in this area), however nothing stops a third party mod from providing an ecosystem-wide solution.
