### ISSUE TITLE
/reload on a dedicated server does not reregister commands added via CommandRegistrationCallback

### ISSUE THREAD

**Issue by i509VCB** [FabricMC/fabric#679]
Also weirdly the client still thinks said commands are in it's completions, but the server doesn't recognize them.

To reproduce:

A dedicated server with some custom commands and connect.

Execute a command which was added

execute `/reload`

try to execute the same command again.

Tests do not fail here since the tests only run when server has first started.

**Comment by liach** [comment]
Hmm, previously commands are all registered before a server is created. Wonder how the recent command changes worked.

**Comment by i509VCB** [comment]
Fixed by #822
