### ISSUE TITLE
Crashes while loading saves, build 74

### ISSUE THREAD

**Issue by KannaHayabusa** [FabricMC/fabric#68]
Fabric Mods: 
		Fabric API: 0.1.4 (fabric-0.1.4.74.jar)
	Launched Version: MultiMC5
	LWJGL: 3.1.6 build 14
	OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 417.71, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
#@!@# Game crashed! Crash report saved to: #@!@# C:\MultiMC\instances\Fabric\.minecraft\crash-reports\crash-2019-01-16_23.09.17-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code -1.

**Comment by Boundarybreaker** [comment]
Just got a crash like this too. [Here](https://dsc.cloud/b0undarybreaker/pb-130Go2OaRZ.txt)'s a log.
