### ISSUE TITLE
API for adding blocks to existing blockentities

### ISSUE THREAD

**Issue by SollyW** [FabricMC/fabric#684]
API for adding blocks to existing blockentities. See #682. This can be done by simply replacing the ImmutableSets in BlockEntityType or its builder with HashSets, creating an accessor for `BlockEntityType.blocks`, and creating a registry system to add to it

**Comment by i509VCB** [comment]
I feel this is not a great way to approach this specific issue. Adding blocks to existing block entities is probably not the best way to approach this. As such I am closing this issue. If you disagree let me know and we will continue further discussion.
