### ISSUE TITLE
Creative Tab page management problem

### ISSUE THREAD

**Issue by arthurbambou** [FabricMC/fabric#69]
My mod adds more than 8 Creative Tab and I can't access page 3 of the Creative Tabs. (Button to page 3 is disable)

**Comment by arthurbambou** [comment]
![2019-01-17_18 28 55](https://user-images.githubusercontent.com/34719527/51336893-f67efa00-1a85-11e9-9e8a-771843fd8d26.png)

**Comment by asiekierka** [comment]
Could you send a JAR with which we can reproduce?

**Comment by arthurbambou** [comment]
https://github.com/arthurbambou/PaintingMod-Builds-Fabric/releases/download/0.2.1.0.752-19w03a/PaintingMod-19w03a-0.2.1.0.752.jar
