### ISSUE TITLE
Add a compound resource pack entry for "Fabric Mods"

### ISSUE THREAD

**Issue by spyguy26** [FabricMC/fabric#79]
when I was updating my personal resource pack to 1.14 I noticed that whenever I tried to replace textures from fabric mods they would stubbornly stay the same despite recreating the filestructure (ex. assets/modid/textures/blocks) and was wondering if this is a larger issue with fabric

**Comment by asiekierka** [comment]
Known.

**Comment by asiekierka** [comment]
Implemented something which should do it for now. I'd like to consider adding a compound resource pack entry for "Fabric Mods" later, so that you can prioritize some resource packs below/above their additions.

**Comment by spyguy26** [comment]
seems to be working now thank you!

**Comment by ghost** [comment]
The mention of "compound resource packs" as being the solution to this issue sounds awfully similar to #1011. @FabricMC/fabric-triage and @spyguy26 do you believe that #1011 sufficiently addressed this issue?
