### ISSUE TITLE
I cannot set up a development environment without it erroring

### ISSUE THREAD

**Issue by JSJBDEV** [FabricMC/fabric#80]
Effectively, whenever I do anything after setting up the example mod as an idea project it refuses to load with the only error message being "failed to provide" it seems to generally happen after I add a second mod to the run folder generated after ./gradlew runClient is first run, after this error message shows in the console, it never seems to work ever again. any help would be appreciated,
thanks in advance

**Comment by JSJBDEV** [comment]
also Im not sure if this is a similar problem but when I tried circumnaviagting the the example mod by trying to build the fabric Dark-Utilities, i get an error 

>  error: cannot find symbol
import net.minecraft.client.render.block.BlockRenderLayer;

when I try to run the client. am I missing something here?

**Comment by Juuxel** [comment]
> error: cannot find symbol
> import net.minecraft.client.render.block.BlockRenderLayer;

It's in `net.minecraft.block` now. ([link to Yarn file](https://github.com/FabricMC/yarn/blob/19w05a/mappings/net/minecraft/block/BlockRenderLayer.mapping))

**Comment by JSJBDEV** [comment]
Ok fair enough, so I may be able to fix up the dark-utils repo, I might be able to work round that. But this original issue still evades me

**Comment by JSJBDEV** [comment]
so I Just manage to set up a development environment. I have a feeling it is something to do with putting fabric in the mods folder (even if it is subsequently removed) that causes the first error I experienced, after reusing the example mod WITH THE DEFAULT VERSION (19w03c) it worked. (I did change the modid line, etc)
