### ISSUE TITLE
Fabric has plugin messaging channels (like as in FML)?

### ISSUE THREAD

**Issue by rantuhin** [FabricMC/fabric#826]
Forge has plugin message chanell **['FML|HS'](https://wiki.vg/Minecraft_Forge_Handshake)** (_[about plugin message chanells](https://wiki.vg/Plugin_channels)_), could you tell me where I can read about it? 
sorry for my English

**Comment by modmuss50** [comment]
Im not really sure what your question is. The link you posted has all the details you need for the forge message. Fabric does not have anything like this currenly.

**Comment by liach** [comment]
it's a vanilla thing. fabric can connect to any server/client without needing to send any packets, and if you.want to deal with packets we have networking api.
