### ISSUE TITLE
Crash at start

### ISSUE THREAD

**Issue by AndreiTS** [FabricMC/fabric#831]
![image](https://user-images.githubusercontent.com/13489837/85226239-f25ab880-b3ac-11ea-890b-5b7e64181aa8.png)
![image](https://user-images.githubusercontent.com/13489837/85226248-fdade400-b3ac-11ea-825e-74bacb456e05.png)

log: https://paste.ee/p/LD0fA

**Comment by jackmawer** [comment]
To elaborate, build 369 of Fabric API crashes the game when using 1.16 RC1 with fabric loader build 202. The key part of the log seems to be as follows:
```10:48:25] [main/FATAL]: Mixin apply failed fabric-particles-v1.mixins.json:ParticleManagerAccessor$SimpleSpriteProviderAccessor -> net.minecraft.class_702$class_4090: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException No candidates were found matching sprites:Ljava/util/List; in net/minecraft/class_702$class_4090 for fabric-particles-v1.mixins.json:ParticleManagerAccessor$SimpleSpriteProviderAccessor->@Accessor[FIELD_GETTER]::getSprites()Ljava/util/List; [INJECT Applicator Phase -> fabric-particles-v1.mixins.json:ParticleManagerAccessor$SimpleSpriteProviderAccessor -> Apply Accessors ->  -> Locate -> fabric-particles-v1.mixins.json:ParticleManagerAccessor$SimpleSpriteProviderAccessor->@Accessor[FIELD_GETTER]::getSprites()Ljava/util/List;]
org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching sprites:Ljava/util/List; in net/minecraft/class_702$class_4090 for fabric-particles-v1.mixins.json:ParticleManagerAccessor$SimpleSpriteProviderAccessor->@Accessor[FIELD_GETTER]::getSprites()Ljava/util/List; [INJECT Applicator Phase -> fabric-particles-v1.mixins.json:ParticleManagerAccessor$SimpleSpriteProviderAccessor -> Apply Accessors ->  -> Locate -> fabric-particles-v1.mixins.json:ParticleManagerAccessor$SimpleSpriteProviderAccessor->@Accessor[FIELD_GETTER]::getSprites()Ljava/util/List;]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTarget(AccessorInfo.java:518) ~[sponge-mixin-0.8+build.18.jar:0.8+build.18+unknown-b18.git-unknown]
```

A temporary workaround for the issue is to downgrade to build 367, which also supports RC1.

**Comment by shedaniel** [comment]
I don't think mixins remap when the class is referenced by a string https://github.com/FabricMC/fabric/blob/3c9757ac95ea15379aaa3bcca2ff70217a046ee3/fabric-particles-v1/src/main/java/net/fabricmc/fabric/mixin/client/particle/ParticleManagerAccessor.java#L46-L50

**Comment by modmuss50** [comment]
uhh

**Comment by modmuss50** [comment]
Removed all the broken version as I dont have time to fix this right now.

**Comment by calloatti** [comment]
Crashes on 1.15.2 also https://paste.ee/p/erxPJ

**Comment by modmuss50** [comment]
The mixin looks valid, so it seems to be a mixin remapping bug somewhere. The question is where 🤔

**Comment by modmuss50** [comment]
Took a few hours to find the issue, but ive applied a work around, and pushing out 0.13.1 to all versions now.

**Comment by jackmawer** [comment]
Thanks for the speedy work as always :) you make this stuff look easy!
