### ISSUE TITLE
Crash on opening inventory [1.16]

### ISSUE THREAD

**Issue by paulevsGitch** [FabricMC/fabric#838]
On 1.16 (release) latest version of fabric-api (0.13.1 build 370) crashes if you open your inventory in creative or survival.

Latest log: [https://pastebin.com/MpdmRZT5](https://pastebin.com/MpdmRZT5)
Crash Log: [https://pastebin.com/YDtPmXnD](https://pastebin.com/YDtPmXnD)

**Comment by paulevsGitch** [comment]
Issue happens only in MultiMC launcher, in Vanilla launcher everything is OK

Options in MultiMC:
![image](https://user-images.githubusercontent.com/17707380/85445410-03b5e780-b59c-11ea-891e-a76712c1c309.png)

Should I redirect this to MultiMC launcher?

**Comment by modmuss50** [comment]
Minecraft 1.16 was re-released, you may need to delete the libraries and/or the .fabric folder for your launcher to redownload the latest version of fabric's mappings.

**Comment by paulevsGitch** [comment]
Thank you
