### ISSUE TITLE
Unable to load any mods in 1.16 release

### ISSUE THREAD

**Issue by Xwicked-knightX** [FabricMC/fabric#839]
literally any mod i try using will crash the game before it can even load, Able to load just api but as soon as i click anything it crashes

**Comment by modmuss50** [comment]
Minecraft 1.16 was re-released, you may need to delete the libraries and/or the .fabric folder for your launcher to redownload the latest version of fabric's mappings.

**Comment by shane-smith** [comment]
Just wanted to confirm that deleting the `.fabric` folder solves this issue. Thank you @modmuss50

**Comment by Xwicked-knightX** [comment]
Yes it did thank you! Sry I didn't say so sooner, forget to check this often
