### ISSUE TITLE
ClientPacketRegistry and ServerPacketRegistry -> ClientboundPacketRegistry and ServerboundPacketRegistry

### ISSUE THREAD

**Issue by Boundarybreaker** [FabricMC/fabric#84]
In places where there's confusion about C<=>S communication, things should be named `Clientbound` and `Serverbound`. Discussed on IRC.

**Comment by asiekierka** [comment]
Lowercase the bound :thinking:

**Comment by asiekierka** [comment]
ClientSide/ServerSide used instead
