### ISSUE TITLE
FabricBlockSettings#breakByTool(Tag, int) allows lower mining levels than specified

### ISSUE THREAD

**Issue by nnym** [FabricMC/fabric#841]
The method specified in the title does not prevent the blocks whereto the settings are applied from being broken with pickaxes of lower mining levels than the value passed to the said method. So far, I tried this only with `FabricToolTags#PICKAXES`, but I suspect that it should not make a difference for the other `Tag`s.

**Comment by bladeofthegrass** [comment]
It also allows other tools if using FabricToolTags#SHOVELS, not sure about axes

**Comment by Azagwen** [comment]
still not working on the latest API version `0.19.0+build.398-1.16` despite being mentioned as fixed.

`FabricBlockSettings#breakByHand` doesn't seem to work either.

**Comment by Azagwen** [comment]
> still not working on the latest API version `0.19.0+build.398-1.16` despite being mentioned as fixed.
> 
> `FabricBlockSettings#breakByHand` doesn't seem to work either.

Adding `.requiresTool()` SEEMS to fix it, might require further testing.

**Comment by shedaniel** [comment]
it's mentioned in the javadoc, https://github.com/FabricMC/fabric/blob/a607839c1a6ab684a230b6f1a455711914d51e4e/fabric-object-builder-api-v1/src/main/java/net/fabricmc/fabric/api/object/builder/v1/block/FabricBlockSettings.java#L284

**Comment by i509VCB** [comment]
If `requiresTool` fixes this I will close the issue. If that does not solve the issue please let me know and I will reopen the issue.
