### ISSUE TITLE
Attribute#mergeAttributes doesn't respect modifier UUIDs

### ISSUE THREAD

**Issue by bluebear94** [FabricMC/fabric#842]
[Attribute#mergeAttributes](https://github.com/FabricMC/fabric/blob/686e6e57ad66a76aa674f622b0492dda402ea0e3/fabric-tool-attribute-api-v1/src/main/java/net/fabricmc/fabric/impl/tool/attribute/AttributeManager.java#L40) completely ignores the UUIDs of the modifiers in the input multimaps, causing problems for code that depends on particular UUIDs (such as `Item.ATTACK_DAMAGE_MODIFIER_ID`). I'm not sure what the intended behavior for this method is.

**Comment by LemmaEOF** [comment]
I'll take a look when I can.

**Comment by bluebear94** [comment]
Actually, since the purpose of `mergeAttributes` is to prevent duplicate entries in the tooltip, couldn't the current calls to that method be replaced with one that merges only the multimaps (using `ImmutableMultimap.Builder#putAll`), while handling duplicate entries when the tooltip is displayed?

**Comment by bluebear94** [comment]
I don't mean to be rude, but is there any progress on this issue?

**Comment by bluebear94** [comment]
It's been 3 weeks since this issue was opened; any response would be nice.

**Comment by LemmaEOF** [comment]
#855 might be helping with it? I've taken a step back from modding for the time being due to personal circumstance.

**Comment by bluebear94** [comment]
#855 concerns mining levels. It isn't relevant to attribute modifiers at all from what I can get from the code.

**Comment by LemmaEOF** [comment]
They're both part of the same module.

**Comment by shedaniel** [comment]
IMO they should become two different modules then.

Also yes #855 will not affect this.

**Comment by LemmaEOF** [comment]
I mean, `AttributeManager` solely exists to help deal with Fabric Tool Attribute API, so it doesn't make sense to spin it out. We're not NPM.

**Comment by shedaniel** [comment]
No, I mean that the mining level stuff is completely unrelated to tool attributes

**Comment by LemmaEOF** [comment]
uhhh, no? the mining level stuff was literally one of the primary points of tool attributes

**Comment by shedaniel** [comment]
The attributes mean the actual entity attributes, like attack speed and stuff. The mining speed and is effective is not really an attribute in my opinion.

**Comment by shedaniel** [comment]
Anyway, I completely went off-topic here, sorry about that. As stated, #855 won't fix this issue and this issue should be looked into.

**Comment by i509VCB** [comment]
I may look into this a bit later and write unit tests for the merging. No guarantees though

**Comment by Technici4n** [comment]
Closed by #1355.
