### ISSUE TITLE
It wont load up

### ISSUE THREAD

**Issue by BLOODWOLF1445** [FabricMC/fabric#843]
basically whenever i hit open on fabric api it never loads a menu and a i dont see fabric on the menu in the minecraft launcher

**Comment by i509VCB** [comment]
The API jar is actually not meant to be run. You need to run the fabric-installer (https://fabricmc.net/use/) to install into the launcher, and then place the api in the mods folder.

I am assuming that is your issue. Please respond if that doesn't sound correct

**Comment by uiytt** [comment]
No answer since 2 month, can someone close this ?

**Comment by i509VCB** [comment]
Closing, if this is still an issue please make a new issue.
