### ISSUE TITLE
With Fabric API, disabling default datapack in world creation menu and clicking "Done" crashes game.

### ISSUE THREAD

**Issue by helpimnotdrowning** [FabricMC/fabric#847]
When in the "Create New World" menu in 1.16.1 and going into the Data Packs menu, if you disable the default datapack and keeping "Fabric Tool Attribute API (v1)", then click done, the game will show the "Saving Chunks" screen for a second and then crash. [This is the crash log with only Fabric API loaded.](https://github.com/FabricMC/fabric/files/4839671/crash-2020-06-26_18.42.54-client.txt) The new datapack doesn't appear without Fabric API, so this crash can't happen.

I think it would be best if the Done button was also greyed out if the Default datapack was disabled, not just when the list is empty.

Minecraft : 1.16.1
Fabric : 0.8.8 build 202
Fabric API : 0.14.0 build 371

**Comment by uiytt** [comment]
The datapack "Fabric Tool Attribute API (v1)" does not appear anymore as for 0.17.0+build 386, so this bug can't happen anymore.

**Comment by i509VCB** [comment]
Closing, if this is still an issue please make a new issue.
