### ISSUE TITLE
I can't open the Fabric API jar file on mac

### ISSUE THREAD

**Issue by KKKJolyne** [FabricMC/fabric#851]
[
<img width="422" alt="Screen Shot 2020-06-28 at 4 57 18 pm" src="https://user-images.githubusercontent.com/67535294/85940565-83f39880-b960-11ea-80a2-23b171fa7caf.png">
](url)

**Comment by i509VCB** [comment]
The Fabric API jar is meant to be placed into your mods folder. Make sure you ran the installer first.

**Comment by KKKJolyne** [comment]
ok thanks
