### ISSUE TITLE
fabric-climbable-api-v1 is causing weird issues with ViaBackwards

### ISSUE THREAD

**Issue by creeper123123321** [FabricMC/fabric#859]
See: ViaVersion/ViaBackwards#219
> **How can we reproduce it?**
> Steps to reproduce the behavior:
> 
>     1. Login on 1.16.1'
> 
>     2. Click on space
> 
>     3. Fly
> 
> 
> **Screenshots**
> ![2020-06-28_09 30 44](https://user-images.githubusercontent.com/38764610/85939964-39532b80-b922-11ea-8fad-058e4c1e412c.png)
> 
> client: 1.15.2
> mods:
> ![image](https://user-images.githubusercontent.com/38764610/85940000-86370200-b922-11ea-89a9-d8b0569e10e4.png)
> 
> Server: vanila 1.16.1

**Comment by creeper123123321** [comment]
Seems to be ViaBackwards fault (sending invalid minecraft:climbable tags)

**Comment by fantahund** [comment]
With ProtocolSupport there is the same problem!

And only if I have Fabric API in my mod folder

**Comment by Earthcomputer** [comment]
1.15 Fabric API reimplements the `minecraft:climbable` tag. These protocol proxies should be sending the right tags to the right clients, that's the issue here. Too many of them don't, this isn't the first issue it's caused.
