### ISSUE TITLE
Fabric api 0.14.x breaks nether biome generation

### ISSUE THREAD

**Issue by NeusFear** [FabricMC/fabric#861]
**Current Issue**
All nether biome mods that use fabric api lost their generation in 0.14.0 there are no errors produced, the only things wrong are that the biomes dont generate at all. Cinderscapes (https://github.com/TerraformersMC/Cinderscapes) has a /mapbiome command in addition to the findbiome command, and neither find the biomes, nor does flying around for a time.

**Versions**
Minecraft: 1.16.1
Fabric-API: 0.14.0+build.369-1.16 or greater
Fabric Loader: 0.8.8+build.202

**Comment by i509VCB** [comment]
Lol @SuperCoder7979 I have no idea why this occurs.

**Comment by jaskarth** [comment]
don't look at me i have no idea either 👀

**Comment by i509VCB** [comment]
I may have an idea what happened. So haykam said on discord earlier that the debug chunk generator does not contain new modded blocks since it's list is generated in static init. Could this be one of those cases?

EDIT: If this is the case I'm going to just PR registry events so I don't have to worry about load order anymore. /s

**Comment by Prospector** [comment]
well the problem is with biomes, not blocks. Unless you mean it could be a similar issue?

**Comment by i509VCB** [comment]
Well it may be related to biomes as well.

**Comment by modmuss50** [comment]
I can confim this with the api's test mod.

**Comment by modmuss50** [comment]
With a debugger attached it doesnt seem to be a load order issue.

**Comment by modmuss50** [comment]
I also cleaned the mixin up to just:

```java
@Redirect(method = "method_28467", at = @At(value = "INVOKE", target = "Lcom/google/common/collect/ImmutableList;stream()Ljava/util/stream/Stream;"))
private static Stream<Biome> injectBiomes(ImmutableList<Biome> biomes) {
	return Stream.concat(biomes.stream(), InternalBiomeData.getNetherBiomes().stream());
}
```

Didnt seem to slove the issue as it achieves the same as before.

**Comment by Hugman76** [comment]
> I can confim this with the api's test mod.

The API testmod is a very bad example, and that's entirely of my fault. The `fabric-biome-api-v1-testmod:test_crimson_forest` biome has the same noises as `minecraft:crimson_forest` and therefore cannot be generated at all. The `minecraft:beach` biome has pretty bad noises so it's very very rare.

**Comment by Hugman76** [comment]
Also this does not affect my own mod ([Mubble](https://github.com/Hugman76/Mubble/tree/1.16-fabric)) and biomes spawn correctly, even with custom blocks and anything.

**Comment by NeusFear** [comment]
Well unless Minecraft changed their noise points to exactly ours then this wouldnt be an issue with cinderscapes biomes, because they do not share the same noise points. In addition we did test with the /mapbiome command in cinderscapes and it found nothing to map but vanilla biomes, so I dont think it's just a simple "change the noise points" fix.
