### ISSUE TITLE
Getting notifacations for all releases again

### ISSUE THREAD

**Issue by MMK21Hub** [FabricMC/fabric#862]
I'm subscribed to this repo for **Releases only**, and 9 hours ago I got notifications for all the releases that exist. This is surely a bug.

**Comment by MMK21Hub** [comment]
![image](https://user-images.githubusercontent.com/50421330/86215663-c5f52800-bb74-11ea-95a8-c8bbbcde2b76.png)

**Comment by liach** [comment]
No? There was no release ever published until 9 hours ago. Refer to https://discordapp.com/channels/507304429255393322/511987279477211137/727649511295680542
