### ISSUE TITLE
Could Not Start (1.16.1) 

### ISSUE THREAD

**Issue by renatotolentino** [FabricMC/fabric#865]
Now This Is My First Fabric Crash. What About Mean Of This? It Just Gives You A Big Anger. Now I get Upset... 
![image](https://user-images.githubusercontent.com/66835724/86286649-6f8df500-bc19-11ea-9718-6055efb013e6.png)

**Comment by liach** [comment]
Install fabric language kotlin. https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin
