### ISSUE TITLE
crash when trying to open the "control menu"

### ISSUE THREAD

**Issue by unrealmanchen** [FabricMC/fabric#868]
using fabric api 0.14.0+build.317-1.15. fabric-api-0.13.1+build.316-1.15 has the same problem.

**Comment by unrealmanchen** [comment]
the game version is 1.15.2

**Comment by Daomephsta** [comment]
Your issue seems similar to #852, though reverting to build 316 doesn't fix it for you.
More information is needed to debug this issue, please provide:
* Installed mods & their versions
* the crash report MC shows after it crashes

**Comment by Prospector** [comment]
Please provide a log or this issue will be closed

**Comment by uiytt** [comment]
More than one month and no log, can someone close this please ?

**Comment by i509VCB** [comment]
Closing, please open a new issue if this is still a problem.
