### ISSUE TITLE
[Suggestion] CauldronInteractionRegistry

### ISSUE THREAD

**Issue by YanisBft** [FabricMC/fabric#87]
As several vanilla blocks and items can be cleaned with a cauldron (leather armor, banners, shulker boxes), I think a registry for this behavior would be interesting.

The syntax would be something like:
`CauldronInteractionRegistry.getDefaultInstance().add(currentItem, resultItem);`

Or for even more customization:
`CauldronInteractionRegistry.getDefaultInstance().add(currentItem, resultItem, waterLevelsConsumed);`

**Comment by Boundarybreaker** [comment]
This is already in Cotton, with provisions for mods adding their own cauldrons which can store items for use in interactions.

**Comment by i509VCB** [comment]
My experience with a system like this in bulky shulkies for my custom shulker boxes has been to listen to the `UseBlockCallback` and force a success state if my shulker box is cleaned and drop the water level then.

I personally feel this isn't necessary.

**Comment by ghost** [comment]
I would agree I think maybe the only part that might be a reasonable addition would be some sort of interface for compatibility of modded cauldrons. Something similar to what Boundarybreaker mentioned in Cotton, but even that seems a little niche.

**Comment by YanisBft** [comment]
Out of scope and also this won't be needed in 1.17
