### ISSUE TITLE
FabricRegistryBuilder is unusable for creating custom registries

### ISSUE THREAD

**Issue by i509VCB** [FabricMC/fabric#872]
~~`createDefaulted` does not specify a supplier to the default value, of a defaulted registry. Hence it is unusable because vanilla fails if there is not default entry.~~

EDIT: Upcraft clarified that any registry has a default value, so it applies to every custom registry

**Comment by UpcraftLP** [comment]
update:
FabricRegistryBuilder is fine, so long as registries are only created AFTER the vanilla `Registry` class has been fully loaded.

**Comment by i509VCB** [comment]
Not applicable for most cases where people create registries after registry class has been loaded.
