### ISSUE TITLE
Mixin impl of IdentifiableResourceReloadListener for FontManager is on wrong class

### ISSUE THREAD

**Issue by comp500** [FabricMC/fabric#878]
In both 1.15 and 1.16, `FontManager` doesn't implement `ResourceReloadListener` - it now uses an anonymous class to implement it. However, `MixinKeyedResourceReloadListener` implements `IdentifiableResourceReloadListener` on `FontManager` rather than `FontManager$1`, so when `ResourceManagerHelperImpl.sort` traverses the listener list it doesn't find the identifier, making it impossible to declare dependencies on the font resource reload listener.

![image](https://user-images.githubusercontent.com/1138417/87096499-e4c18180-c23a-11ea-902f-e7680b0f404a.png)

**Comment by liach** [comment]
In fact mojang has in like 1.15 added another default method for displayed name for a resource reload listener. we can probably switch to that
