### ISSUE TITLE
game crash while entering a 'nether waste' single biome world

### ISSUE THREAD

**Issue by yenvenTEST** [FabricMC/fabric#879]
[crash-2020-07-10_09.46.16-server.txt](https://github.com/FabricMC/fabric/files/4901494/crash-2020-07-10_09.46.16-server.txt)

**Comment by Prospector** [comment]
Does this happen with just Fabric API installed?

**Comment by uiytt** [comment]
More than one month and no reply.
Can someone close this please ?

**Comment by i509VCB** [comment]
Closing, if this is still an issue please make a new issue.
