### ISSUE TITLE
[Sugestion] When loading a file fails due to zip END header not found, include the file name in the log

### ISSUE THREAD

**Issue by calloatti** [FabricMC/fabric#883]
If I place a random file renamed to fakemod.jar in the mods folder and start the game, this is the crash log:

https://paste.gg/p/anonymous/dcccb7b557274fc6bd784389b643baac

The actual file name of the broken jar file is not in the crash log, having the file name would make troubleshooting crashes easier.

**Comment by shedaniel** [comment]
Look at https://github.com/FabricMC/fabric-loader/pull/204

**Comment by Prospector** [comment]
Wrong repo and duplicate of FabricMC/fabric-loader#185

**Comment by calloatti** [comment]
ouch sorry I got spanked hard.
