### ISSUE TITLE
Could not find required mod: fabric requires {minecraft @ [~1.16.2-alpha.20.28.a]}

### ISSUE THREAD

**Issue by DaJue** [FabricMC/fabric#886]
whenever i try to launch fabric this is what pops up and i cant find a way to fix it.

**Comment by JadedKitteh** [comment]
I'm encountering the same problem :(

**Comment by Player3324** [comment]
It means that your fabric-api version needs the Minecraft 1.16.2 snapshot 20w28a, you most likely need to download a different version of fabric-api since you appear to run a different MC version.

**Comment by JadedKitteh** [comment]
Thank you!!!

**Comment by DaJue** [comment]
> 这意味着您的fabric-api版本需要Minecraft 1.16.2快照20w28a，由于您似乎在运行其他MC版本，因此您最有可能需要下载其他版本的fabric-api。
thank you very much! I changed the correct version and it works now!

**Comment by PurPLeEPiC** [comment]
and which version i have to use so i can use mods on 1.16.1

**Comment by Player3324** [comment]
At the time of writing, it is https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3007384 - just go to https://www.curseforge.com/minecraft/mc-mods/fabric-api/files and look for the one with `[desired mc version]` in front of it.

**Comment by 123yuyu123** [comment]
le meme problème

**Comment by 123yuyu123** [comment]
je n'arrive pas a lancer tissu Could not find required mod: fabric requires {minecraft @ [~1.16.2-alpha.20.28.a]}

**Comment by dream79** [comment]
how do i fix it?? i dont know how to fix this and im searching a solution because i want to play in the 1.17 snapshot

**Comment by Technici4n** [comment]
You need to install Fabric API for the correct Minecraft version from https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/all.
