### ISSUE TITLE
Picking event logic leads to missed picks deviating from vanilla behaviour

### ISSUE THREAD

**Issue by fnuecke** [FabricMC/fabric#89]
Think I forgot to mention this on Discord: just in case nobody else noticed this yet, the current event implementation seems to change default vanilla behaviour when missing a pick (i.e. picking "nothing"). When middle-clicking into thin air in vanilla, nothing happens. Using 0.2.0 an empty stack is picked (i.e. the selected hotbar slot gets cleared).

Maybe it's because the container is [initialized to an empty stack](https://github.com/FabricMC/fabric/blob/master/src/main/java/net/fabricmc/fabric/mixin/events/playerinteraction/MixinMinecraftClient.java#L54)? Didn't dig very deep.

PS: Wasn't sure whether to just post as a comment in #86.

**Comment by asiekierka** [comment]
I will be rewriting the whole hook because the current implementation has been quite a miss relative to the patches we need to do. (I guess I never miss, huh?)
