### ISSUE TITLE
More player/world/server related events

### ISSUE THREAD

**Issue by LambdAurora** [FabricMC/fabric#890]
What would be very cool is to have events for when a player joins a server, with possibility to change the join text and to check if it's the first time the player joined (tho not sure if that's still in-scope), same for when a player disconnects.
For client focused events: an event for when the player joined a world/server

 - [ ] Player join event
 - [ ] Player disconnect event
 - [ ] Client player joined event
 - [ ] Player eat event
 - [ ] Entity damage event for HalfOf2

**Comment by Ueaj-Kerman** [comment]
"Entity damage event for HalfOf2" would this only get thrown if I get damaged

**Comment by yyny** [comment]
Connection and disconnection events are `ServerPlayConnectionEvents.JOIN` and `ServerPlayConnectionEvents.DISCONNECT`. There is also `ClientPlayConnectionEvents.JOIN`, although I'm guessing when you say "Client player joined event" you mean "An event that fires on the client whenever a new player joins".

**Comment by Technici4n** [comment]
Closing as some of these were implemented, and we generally track separate events in separate issues. If you want to request some events, please also provide a use case to help guide the event design.
