### ISSUE TITLE
Found a warning in game log

### ISSUE THREAD

**Issue by linzexin022** [FabricMC/fabric#897]
Hi there! I found a warning in game log:

`[main/WARN]: Warnings were found! 
 - Conflicting versions found for fabric-api-base: used 0.1.3+12a8474c7c, also found 0.1.3+12a8474c02`

Version: 0.15.0+build.379-1.16.1

**Comment by Martmists-GH** [comment]
You likely have two versions of Fabric API installed

**Comment by uiytt** [comment]
Can someone please close this as there is no answer.
