### ISSUE TITLE
Flying while use Fabric

### ISSUE THREAD

**Issue by Leo182x** [FabricMC/fabric#900]
Hello!
I installed Minecraft and Fabric to play on a private server. But in the game, if I hold space I start to float, if I let go I fall from above and die, and I'm kicked from the server if I go too high.
The only mods I installed was optfine, fabric and voxel map, and I didn't use any commands or anything. And i updated Java.

So i try to play without using fabric, and stopped happening. I tried to install other builds and the same thing happened.
Is some fabric configuration? Does anyone know what's going on?

**Comment by i509VCB** [comment]
This sounds a lot like a previous issue where via version or something like it would send the client the wrong tags, so the client thinks everything is climbable (so it tries to climb) but the server doesn't think you can climb (kicks you). I think there was an update for via version or whatever that fixed the tag synchronization.

**Comment by Leo182x** [comment]
so i tried to reinstall everything, and instal the latest versions, disable all mods and leave only the fabric, and it keeps happening. And it was normal before, does it have anything to do with me updating the java? I haven't tried to install the version I was before.

**Comment by i509VCB** [comment]
Does the server run via version or some sort of proxy system to let other versions join? Should have clarified the server is sending the client bad data in this case.

**Comment by Leo182x** [comment]
so I tried to run or minecraft via two different launchers, it's the minecraft 15.2.

**Comment by Leo182x** [comment]
the server its not mine, if i talk to the owner can he solve it?

**Comment by Leo182x** [comment]
i tried install a older version of java, not worked.

**Comment by i509VCB** [comment]
Go talk to whoever runs the server, if they use via version or something like that they probably need to update it so your client doesn't get sent bad tags.

**Comment by Leo182x** [comment]
I spoke to him, and he told me that he uses protocolsupport, to allow access to other versions, but it is in the latest version. He and other users use fabric and don't have this problem

**Comment by i509VCB** [comment]
https://github.com/ProtocolSupport/ProtocolSupport/issues/1255

This was the related issue from an earlier bug report. (#859) where the issue occurred with via backwards

**Comment by Leo182x** [comment]
ok, thanks, i will follow the report

**Comment by uiytt** [comment]
No further replay, can we assume this is solved ? 
And if so, can someone close this please ?

**Comment by i509VCB** [comment]
Closing since this issue has a solution, just up to ProtocolSupport to implement it and the server owner to update ProtocolSupport.
