### ISSUE TITLE
Fabric API Single player Crashing

### ISSUE THREAD

**Issue by nschwa115** [FabricMC/fabric#902]
Whenever I try to play in singleplayer with the fabric API mod my game crashes with an error message of: 
The game crashed whilst exception in server tick loop
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
The version of Minecraft that I am playing on is fabric-loader-0.8.8+build.202-1.15.2 of Fabric and the only mod I have that requires the fabric API is ReplayMod.
Thank you for looking into it at some point.

**Comment by i509VCB** [comment]
We are going to need a full log to figure out the issue. Please attach that if you can.

**Comment by nschwa115** [comment]
If what you are wanting is the full crash report then here it is.
[Crash Log.txt](https://github.com/FabricMC/fabric/files/5010704/Crash.Log.txt)

**Comment by nschwa115** [comment]
If needed for some more reference points, in some further testing, I found the same Issue in the Fabric API files named;
fabric-api-0.16.0+build.321-1.15.jar   and
fabric-api-1.16.2+build.322-1.15.jar

All of the versions of Fabric API for 1.16.1 are working fine no crashing.

**Comment by amnotbananaama** [comment]
You're using a version of Fabric API for 1.15.2 in that log. Please update to the latest version of Fabric API for 1.16.1

**Comment by nschwa115** [comment]
I have and it has been working perfectly.

**Comment by i509VCB** [comment]
Closing since issue seems to have been resolved.
