### ISSUE TITLE
"Duplicate versions for mod ID" for the Fabric API after updating

### ISSUE THREAD

**Issue by CosmicCow** [FabricMC/fabric#915]
Hello there!!

I'm getting an error on launch after updating Fabric! "Duplicate versions for mod ID" for the Fabric API (Update to 0.15.1 for 1.16.1)

The old version is deleted, but the error is still displayed as duplicate versions for builds 372 and current 380. Like if both files were there.

Do I need to do something for the update to run properly?

**Comment by Linguardium** [comment]
then you still have the old version of Fabric API in your mods folder

**Comment by CosmicCow** [comment]
Nope, is already deleted. Even deleted from trash.

**Comment by uiytt** [comment]
More than one month without answer.
Can someone close this please ?

**Comment by dwnsdp** [comment]
I have this problem. Fabric API is definitely not in the mods folder
![image](https://github.com/user-attachments/assets/7c37de54-0ce0-4ab7-bc46-b1c90672116a)
