### ISSUE TITLE
Server Side Command don't work 

### ISSUE THREAD

**Issue by UnRealDinnerbone** [FabricMC/fabric#93]
Server-side commands don't get registered
This is because the call to CommandRegistry.entries is called before the mods have a chance to register them in their onInitialize

**Comment by modmuss50** [comment]
This https://github.com/FabricMC/fabric/pull/106 PR fixes it.

**Comment by Juuxel** [comment]
Is this fixed now?

**Comment by modmuss50** [comment]
yes, it should be fixed? has it broken again?

**Comment by Juuxel** [comment]
Nope (at least to my knowledge), just checking if an old issue should be closed.
