### ISSUE TITLE
Mod resolution failed "zip END header not found"

### ISSUE THREAD

**Issue by MeticulousTheGreat** [FabricMC/fabric#954]
Not entirely sure what is happening, maybe someone can help?
Here is the log file:

[latest.log](https://github.com/FabricMC/fabric/files/4976248/latest.log)

**Comment by linzexin022** [comment]
The same problem

**Comment by i509VCB** [comment]
One of the jar files seems to have had an issue, I'd redownload the mods again to see if that fixes it.

**Comment by MeticulousTheGreat** [comment]
> One of the jar files seems to have had an issue, I'd redownload the mods again to see if that fixes it.

**Comment by MeticulousTheGreat** [comment]
oops

**Comment by MeticulousTheGreat** [comment]
I have redownloaded but the problem persists

**Comment by uiytt** [comment]
What is your fabric api version and fabric loader version ? 
And what launcher are you using ?
Also due to #1016 what drive are you using to run fabric on ?

**Comment by MeticulousTheGreat** [comment]
I did something and it works now, I changed some files so I can't say for sure what API, loader, or launcher I was using.
I do have an SSD (my main drive) running fabric.

**Comment by uiytt** [comment]
I'm quite sure that the fact it's SSD is not the problem. 
But well, if it works now, it may be closed.

**Comment by i509VCB** [comment]
Closing due to lack of feedback, if this is still an issue, please make a new issue.

Since this seems to be an issue with ZIP end header not found, maybe your Antivirus could be corrupting the zip file?
