### ISSUE TITLE
Fabric crashes after launching

### ISSUE THREAD

**Issue by Ion-1** [FabricMC/fabric#958]
I just downloaded today a bunch of mods and put them on a separate Fabric Game Directory. When i try launching Fabric it crashes in the client stage.
[crash-2020-07-26_15.32.36-client.txt](https://github.com/FabricMC/fabric/files/4977291/crash-2020-07-26_15.32.36-client.txt)

**Comment by JamiesWhiteShirt** [comment]
This is not an issue with Fabric API. Report the issue to [Resource Pack Organizer](https://github.com/chylex/Resource-Pack-Organizer/issues).

**Comment by Ion-1** [comment]
My Mistake! Downloaded the 1.15 version.
