### ISSUE TITLE
Can't use modmenu

### ISSUE THREAD

**Issue by Gengyen** [FabricMC/fabric#959]
I reinstalled fabric to get 1.16 (I was using 1.14) and modmenu now doesn't work.
![image](https://user-images.githubusercontent.com/42317852/88482556-cde19580-cf83-11ea-9bba-be4a9004b60f.png)

These are my current mods:
![image](https://user-images.githubusercontent.com/42317852/88482564-dafe8480-cf83-11ea-957c-7979de010f7f.png)

When I launch, it crashes with that error message and I can't play.

**Comment by i509VCB** [comment]
So you need to install [fabric-api](https://www.curseforge.com/minecraft/mc-mods/fabric-api) itself. `resource-loader` is a completely different mod.

**Comment by Gengyen** [comment]
> So you need to install [fabric-api](https://www.curseforge.com/minecraft/mc-mods/fabric-api) itself. `resource-loader` is a completely different mod.

sorry for the delay; I already have fabric api. It's in the screenshot

**Comment by uiytt** [comment]
Do you still have this issue in 1.16.2 with latest fabric api ? (0.19) 
and also `worldedit-forge` ...
and I'm not used to windows 7; are the mods folder ?

**Comment by i509VCB** [comment]
Closing due to lack of feedback. If you need further assistance, please join the Fabric discord https://discord.gg/v6v4pMv
