### ISSUE TITLE
Minecraft with Fabric API can't load world with custom dimension

### ISSUE THREAD

**Issue by NikitaCartes** [FabricMC/fabric#960]
UPD: Forgot to mentions.
Minecraft: 1.16.1
Fabric Loader: 0.9.0 build 204
Fabric Api: 0.16.0 build 384

Step to reproduce:
1) Create new world with [imported settings (e.g.)](https://misode.github.io/worldgen/?q=eyJzZWVkIjotMTQ2NDI0NTg2MywiZ2VuZXJhdGVfZmVhdHVyZXMiOnRydWUsImJvbnVzX2NoZXN0IjpmYWxzZSwiZGltZW5zaW9ucyI6eyJtaW5lY3JhZnQ6b3ZlcndvcmxkIjp7ImdlbmVyYXRvciI6eyJiaW9tZV9zb3VyY2UiOnsic2VlZCI6LTE0NjQyNDU4NjMsImxhcmdlX2Jpb21lcyI6ZmFsc2UsInR5cGUiOiJtaW5lY3JhZnQ6bXVsdGlfbm9pc2UiLCJiaW9tZSI6Im1pbmVjcmFmdDpwbGFpbnMiLCJiaW9tZXMiOlt7ImJpb21lIjoibWluZWNyYWZ0OmNyaW1zb25fZm9yZXN0IiwicGFyYW1ldGVycyI6eyJhbHRpdHVkZSI6MCwid2VpcmRuZXNzIjowLCJvZmZzZXQiOjAsInRlbXBlcmF0dXJlIjowLCJodW1pZGl0eSI6MH19LHsiYmlvbWUiOiJtaW5lY3JhZnQ6YmFzYWx0X2RlbHRhcyIsInBhcmFtZXRlcnMiOnsiYWx0aXR1ZGUiOjAuMSwid2VpcmRuZXNzIjowLjIsIm9mZnNldCI6MCwidGVtcGVyYXR1cmUiOjAsImh1bWlkaXR5IjowfX0seyJiaW9tZSI6Im1pbmVjcmFmdDpkZXNlcnRfaGlsbHMiLCJwYXJhbWV0ZXJzIjp7ImFsdGl0dWRlIjowLjMsIndlaXJkbmVzcyI6MS4yLCJvZmZzZXQiOjAsInRlbXBlcmF0dXJlIjowLCJodW1pZGl0eSI6MH19LHsiYmlvbWUiOiJtaW5lY3JhZnQ6bXVzaHJvb21fZmllbGRzIiwicGFyYW1ldGVycyI6eyJhbHRpdHVkZSI6MC4yLCJ3ZWlyZG5lc3MiOjEsIm9mZnNldCI6MCwidGVtcGVyYXR1cmUiOjAsImh1bWlkaXR5IjowfX1dfSwic2VlZCI6LTE0NjQyNDU4NjMsInNldHRpbmdzIjoibWluZWNyYWZ0Om92ZXJ3b3JsZCIsInR5cGUiOiJtaW5lY3JhZnQ6bm9pc2UifSwidHlwZSI6eyJ1bHRyYXdhcm0iOmZhbHNlLCJuYXR1cmFsIjp0cnVlLCJzaHJ1bmsiOmZhbHNlLCJiZWRfd29ya3MiOnRydWUsImFtYmllbnRfbGlnaHQiOjAsImxvZ2ljYWxfaGVpZ2h0IjoyNTYsImluZmluaWJ1cm4iOiJtaW5lY3JhZnQ6aW5maW5pYnVybl9vdmVyd29ybGQiLCJuYW1lIjoic2xhdmFfc2VsIiwicGlnbGluX3NhZmUiOnRydWUsInJlc3Bhd25fYW5jaG9yX3dvcmtzIjpmYWxzZSwiaGFzX3JhaWRzIjp0cnVlLCJoYXNfc2t5bGlnaHQiOnRydWUsImhhc19jZWlsaW5nIjpmYWxzZX19LCJtaW5lY3JhZnQ6dGhlX25ldGhlciI6eyJnZW5lcmF0b3IiOnsiYmlvbWVfc291cmNlIjp7InNlZWQiOi0xNDY0MjQ1ODYzLCJwcmVzZXQiOiJtaW5lY3JhZnQ6bmV0aGVyIiwidHlwZSI6Im1pbmVjcmFmdDptdWx0aV9ub2lzZSJ9LCJzZWVkIjotMTQ2NDI0NTg2Mywic2V0dGluZ3MiOiJtaW5lY3JhZnQ6bmV0aGVyIiwidHlwZSI6Im1pbmVjcmFmdDpub2lzZSJ9LCJ0eXBlIjoibWluZWNyYWZ0OnRoZV9uZXRoZXIifSwibWluZWNyYWZ0OnRoZV9lbmQiOnsiZ2VuZXJhdG9yIjp7ImJpb21lX3NvdXJjZSI6eyJzZWVkIjotMTQ2NDI0NTg2MywidHlwZSI6Im1pbmVjcmFmdDp0aGVfZW5kIn0sInNlZWQiOi0xNDY0MjQ1ODYzLCJzZXR0aW5ncyI6Im1pbmVjcmFmdDplbmQiLCJ0eXBlIjoibWluZWNyYWZ0Om5vaXNlIn0sInR5cGUiOiJtaW5lY3JhZnQ6dGhlX2VuZCJ9fX0=) in vanilla Minecraft or with Fabric
[Create New World -> More World Options... -> Import Settings -> Choose file with JSON-content from url]
2) Save and quit.
3) Try to open a world.

Expected Behavior: world open.
Actual behavior: world doesn't open.

Vanilla Minecraft instead can open this world and all functioned normally.

Log File: 
[Fabric Modded Log.txt](https://github.com/FabricMC/fabric/files/4987256/Fabric.Modded.Log.txt) // https://paste.ee/p/xexhf
Vanilla log file:
[Vanilla Log.txt](https://github.com/FabricMC/fabric/files/4987280/Vanilla.Log.txt) // https://paste.ee/p/24hmO
World with settings from URL:
[New World.zip](https://github.com/FabricMC/fabric/files/4987266/New.World.zip)

**Comment by liach** [comment]
Ok registry sync, you've constantly proven yourself more problematic than useful  ![concern](https://cdn.discordapp.com/emojis/707016186281590855.png?v=1)

**Comment by boasbakker** [comment]
this is the oldest bug still open. Is this fixed?
