### ISSUE TITLE
How do I send message to a player's chat on 1.16?

### ISSUE THREAD

**Issue by UQuark** [FabricMC/fabric#962]
Hello. On 1.15.2 I could use a PlayerEntity.addChatMessage() method to send a message to the player's chat. How do I do it in 1.16.1? Was that method just renamed or I should do it completely another way? Thank you.

**Comment by Juuxel** [comment]
The method was renamed in Yarn to `sendMessage`.

**Comment by UQuark** [comment]
And, before you close this issue, is there something like a Fabric Forum? I don't really want to spam on github issues with my stupid questions.

**Comment by UQuark** [comment]
Thank you very much

**Comment by modmuss50** [comment]
The discord server is the main point of contact, there are channels there where you can ask for help: https://discord.gg/v6v4pMv
