### ISSUE TITLE
Game crashed

### ISSUE THREAD

**Issue by hornta** [FabricMC/fabric#968]
Fabric version:
![image](https://user-images.githubusercontent.com/4553604/88861190-bb729080-d1fd-11ea-9950-207478cc044f.png)
I'm using build 389 of Fabric API:

This is what I'm getting
![image](https://user-images.githubusercontent.com/4553604/88861092-8403e400-d1fd-11ea-9e9d-cbd824f22ea9.png)
![image](https://user-images.githubusercontent.com/4553604/88861532-726f0c00-d1fe-11ea-8e53-5c53b1029678.png)

**Comment by modmuss50** [comment]
I can confirm that the 1.16.2 version does not work, I will fix.

**Comment by modmuss50** [comment]
I have reverted the loom update, and pushed a new version.

**Comment by hornta** [comment]
https://hastebin.com/jelotufibu.pl

**Comment by hornta** [comment]
Ok will test it.
