### ISSUE TITLE
BlockBreak Event

### ISSUE THREAD

**Issue by sylv256** [FabricMC/fabric#969]
We need a BlockBreak Event

**Comment by liach** [comment]
Concerning, this will be a giant performance burden

**Comment by modmuss50** [comment]
A player block break event might be a good idea, we have the block attack one right now.

**Comment by shedaniel** [comment]
my dreams of having a block break event is close

**Comment by i509VCB** [comment]
A player event for breaking blocks makes some sense. 

However a raw `setBlockState` event is probably not contextual enough. Even then a full `ChangeBlockStateEvent` would require almost every mod which uses it to fail as fast as possible.

**Comment by Ueaj-Kerman** [comment]
> Concerning, this will be a giant performance burden

no not really, fabric events are fast enough, and really, no matter what u do, it can't possibly be worse than TACS, 99% of time in setBlockState is spent waiting on chunks anyways. 
But a PlayerBreakBlockEvent is probably more useful, so meh

**Comment by i509VCB** [comment]
Either way these types of events if they are Cancellable need a sort of post/after event for mods to listen to if notification of block changes are needed

**Comment by Ueaj-Kerman** [comment]
Yes ofc

**Comment by liach** [comment]
A player break block event based on packet input is definitely useful. The mass block change one isn't as needed imo and has more potential side effects.

**Comment by Ueaj-Kerman** [comment]
[shameless plug](https://github.com/Devan-Kerman/OneEvents/blob/master/LOOK%20IN%20HERE/PlayerBreakBlock.java), u don't need any packet stuff

**Comment by i509VCB** [comment]
Oh look this has been merged
