### ISSUE TITLE
0.2.2.102 hangs on launch

### ISSUE THREAD

**Issue by Boundarybreaker** [FabricMC/fabric#97]
Launching Fabric with loader 0.3.7.108 on 19w08a.4 will cause the game to hang. Confirmed in both dev and prod environments.
[dev env log](https://gist.github.com/Boundarybreaker/b092e001c4919e48afcee23ca2a41d08)
[prod env log](https://gist.github.com/Boundarybreaker/2d66963a444b621cc9c7c0e230b352ea)

**Comment by Boundarybreaker** [comment]
Due to new NIO code for resource loading

**Comment by asiekierka** [comment]
Could you check with 0.2.3, please?

**Comment by Boundarybreaker** [comment]
It works just fine on Mac.
