### ISSUE TITLE
Crash Please Help

### ISSUE THREAD

**Issue by YassaaaTU** [FabricMC/fabric#979]
### **`I do not know if I should post this here or not but I will do it anyway `**

> So I installed multiple mods (made a modpack) for fabric and when I wanted to start it I got this message but no crash report:
> 
> > ![crash](https://user-images.githubusercontent.com/5587106/89082651-e3452e00-d38e-11ea-8556-9ac9517d9a11.png)
> 
> After I disabled the mod "BetterEnchantments" and I got a crash report:
> [The link to the Crash Report](https://gist.github.com/HyburdzMC/36233bc1d862c0f8053d0172c9d9ce2a)

**Comment by i509VCB** [comment]
There seems to be an issue with getting the max level of the silk touch enchantment. I'd probably bring this up with the author of the mod.

**Comment by uiytt** [comment]
This is not a fabric error, you can go on [the fabric discord](https://discord.gg/v6v4pMv) for mod support...
Can someone close this please ?
