### ISSUE TITLE
Hook to expose DefaultBiomeCreator.getSkyColor

### ISSUE THREAD

**Issue by Juuxel** [FabricMC/fabric#981]
All (AFAIK) vanilla overworld/nether biomes have their sky colour assigned with this private static method, so exposing it would be useful for modded biomes. (It takes the biome temperature and calculates a sky colour from it.)

**Comment by Juuxel** [comment]
Here's another addition that'd benefit from global AW.

**Comment by Technici4n** [comment]
It's now called `OverworldBiomeCreator.getSkyColor` in 1.19.3 and it's protected. Is that good enough?
EDIT: not good enough, no
