### ISSUE TITLE
Endermite crash my server

### ISSUE THREAD

**Issue by ahkui** [FabricMC/fabric#992]
Log [here](https://paste.gg/p/anonymous/b1aa8a0c47614fb381e9f6f1178f1ba0)

**Comment by asiekierka** [comment]
```
asie | endfestation was never updated past 20w07a
asie | so it's not gonna work on 1.16.1
```

Either way, this is not an API issue - it's a Minecraft version incompatibility issue.

**Comment by ahkui** [comment]
thank you
