### ISSUE TITLE
[1.16.1] Crash on startup

### ISSUE THREAD

**Issue by ghost** [FabricMC/fabric#993]
With the file "[1.16.1] Fabric API 0.16.2 build 385" from curseforge I'm getting the following crash on startup
https://pastebin.com/raw/dM7rnU68

**Comment by i509VCB** [comment]
> java.lang.ClassNotFoundException: net.minecraft.class_2378

2378 -> Registry

Well this is concerning, it can't find registry. Can you give us a list of mods by chance or more info?

**Comment by i509VCB** [comment]
Closing due to lack of feedback. If this is still an issue please open a new issue report.
