### ISSUE TITLE
[Q]Is there a Fabric API for version 1.16 not 1.16.1

### ISSUE THREAD

**Issue by PM-yanmao** [FabricMC/fabric#998]
I can't find it.

**Comment by dexman545** [comment]
https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/2985289

**Comment by i509VCB** [comment]
It may seem a bit odd, but the `1.16.1` versions refer to 1.16.1 while `1.16` refers to the latest 1.16 release/snapshot.

**Comment by uiytt** [comment]
I think this can now be closed.
